sprite $103 [93x93/16z] {
xPZPce9834R_XVNzNtY0eZjAFiFICrVZkL4fwn12XINud_7bovSlNqZv1udyTwJk-d6SviGq3hr5F4NzE9yn3HqVc8VfDyJE4WyvwlhXvu36ctwFcxUtKAAk
nJ1SrtDLJrVZqR3gErp3ww4Q16201YJ0VFtwEa9sqpA3k42tH6ti2a867FBz9m-x7PP9l1JtIDoJjsaJpk3Y1aZiQRaW9q1oiGyuOLmFZpQnmZFvZgqrdKQ9
qZ-eZt8TunfHCkn9UOSyog7qbpKmeM9TiBA9J2Gvq-PCSt-oLF2Shbum_KdQJayOovGFW1PmapQdJleqTy_bRNebD_x0M9xHV5oPEgjbxHFq2d43UGNeapoT
RguWGwqG6MwiQt5yjipbNrWkz5hE77hBbKXIMG-kH735dfd3W-p81_FenfRM-mMgREFD4ZsSxSf5cvzMMxrEjS7I9FlbHoFNIQumkl5scqdOZE-D2_ACZGpp
ratkGjuX8GieGa_NfkgYI3VqPg7tv6iVYNtAZIjogC78odu2BHe4Dm53lhCBQdaGScAL4oOeXRp8Qv6oT3wDtI_Vb-USPpdXxIlVvDwvb1OsSkIo34c7d3Cc
JFUN8ZV5fW4enkOZjRpFaTD6NLfi54LKbJ_Bqc9T_lKDLlR5wcUIdrzoRPri2ZbFRXRQA5MsqvrRSRCeRh2nojEDBNuUX-qcVtBtzm93fNB-xK7v1Jvvj53r
nCNTBnPFN2C-mkA9gu8RQIa_UX2jYx2-vXQ1bx7NLzmsIY_W7crEYwsk_-T4LkkrzFo5gnwcz6aO885CczEdqFAzI3OIhs_GOfQVl-H-shdIkpyCWAc-XGeU
6qfXOxCnTItYg4VK3FEiUAwDK0ziyiYGBFGHU97rYP1ux1JnjNjpx1H9z1mPhnRCfFjjg6wEf1HuR-Jfgbm4Xt3NQ6hzkLZO9A3uoVOL-mYufFjoQNFOsg74
9PoRbZNwQRVojDqwh_J47THFBtrY8hVJ--6tKVpN5lSqZUEmCKxJQulRn5CO0GPnICJVeUIkwtSwMyH_pPSlN_u1
}

