sprite $103 [96x96/16z] {
xPa9ckie38HLLV21xd_XQHkdvSHDP6QVUVbx3KiX9214jd-E3ny-VFZm0LIfjNtHlsWRjHGHVrnPjNMVqdkhmk_MFadlPjS7-qoYhigMOJiwjpfp15GUi-iL
lqEzLTvoOTyRmsvJlqqw_G3nygMOsn2zs3tGHcF2J338zX_AJ3JJjHZ0PbAx9z-FoIhHnrCnsiq1cdinMzOtkpT0tUH1ci7kwiFs7irTbe3T24YmGQP_G0dM
l5l23qquZozVMhgNrFnY02xb5tt3QnFSc41nXqapDvAX_Of4epiJzpJx8tIlINsn1LRjWpiD966hSEzLtWU0xZ18uhg-99ZSRSwepaWDd1FJMoSSFAUEpRi1
Mo3wk2iBFxXXFp0FFRY1R04sh-yZE62o0LPhGvta-n5Qeb--xRGdpY71fHhQGRB1HdGmU9N7Yvu5fpurrm_Eybb9hC1qzM8d4PDuiN_ie4oV6fozOLVEXHem
ruTT0o0nyLdqaFlowH52IN6YFoelzlF9qF5huxHWemTpVOOtJpeKZsMgOq16YmCa1wYy_s2_D69CWupZnKlOeqUcF_UpQDGkBSq3W5mV3sRwHZthuq7Ol-n_
U-CVtl7_DFZ7I15VHNnpYNpzOxh-iR3-8pZW3XRs5mV8zMa6xJ0vArzQRE36-NRN4vHMRo1n_kTQaB1q_eS-j3D_-nhoj1FQGQRVlNp7rrxwS_Oo0Xpllylt
1uOaul_a_h1KgpFh5iRzZRFx8JNWz7uuF9pTFtTiXUZahd_m_YptFwoFxEC18u0BZC38FPzUk7yn0E7WV-3pOzG3i7M0TFcR5VVftHLcEd84i_iStPdd7ww0
X_Ov1v5dHz8MaPyPsiImFV8pkNMN9lKK0OI-uUogR_sZ9O0mBibVoI3XERyNCIGkQIV0A67lcj97gsl-ZKd-hRYtc_d3QdyeVvWFq9Ndzw8OPkftvOSftcIt
GUa-9dqJRUrx4om76ibgsWgb-qQhXPXBixIZdMmLrkw3tbej8l60Kgbjazvf1R__yOM_P-q1nlmnGlSWvWJxypWS8mAmVveF7pxy1W
}

