sprite $103 [446x446/16z] {
xDI5TKGX0011_47_3IVmuvvpcUbXDvmC000000000000000000000000000000000000000000000EbL_Yoz4Iu1UQfjwM-Cp_eRRQbvIk6aIAMKEWwfbKVX
I5WtBBEoSKopoksouH18QurhXoUppRNa7FPWa7sSNId_wP2qSklZSlGPugyt9ULvoV70tXajEOx2K5Iw0Wh__m_lfZfLqvs-KMW74s5pzcayEqxmCH88x4Ia
rbAoGIWBItMRWF8GIXUmNBPvg2NTE-726c9bn3YQH9QwRLvgllIKu3rrzKR9Dv9PMztBxkHyu_rvPCbsINMx9mMrt6sXNx4qvPBtQgmj0bV0h2cb0INKVY5q
JGrghJbdCmnUk_WAgrip5vaAfkQ8MN8YraO2IxarejQQSNftjJL8IXpG6axBcVqXDqoZSZA9Y5dEjLvs18DIfwzWm5AkhyA6d91ydg2JnZKbVhwh4qvvapTT
FTdunHntsUOj5LrY0kYqqb4tTmojE7V7EqUL7hcUEVsL9-uIXA2g3KUann5LxVBXi7pMqIV-5bTWPlQhXWp_Y9gPwSDfs17XH_mJmpsnFw3E9ymBjPWuyin-
7S6lDHuyN6Cp_NNatHFBinChBG2UBVk1jYZZrUgRFbuk4-S8VbrsUtP4UtqKmygvekT6A0zz3M_RC-V807lwxoIs4T9fnfgr_9Q56UtnDl3ucN2Ewae1ot8w
gJtUXbJFaFpIwqROUUp1dIBLwNjUpI8NiCTJHiNayY2NiIUIfjQNoBJrIlO44mVFLCcavrBsHCgq-Ye96rUp9sdIgXcPdr_Gdg3Eg8zywQlPusDFa_Xa8kzg
zdZlgpRRaX24SCPQ2wVEDNAnXhljn7LENr_DKwsaP_8UAfKV1tNsDOQVhyxIXtQYJXGxqxFHfdr3XJ2RFOxQFy1o7wOPRsOkp_0Y4qAYsbD--xdjj6cc3UL9
ZbRxWVZw9AmzqUQkTuF4esgJ35cSLZb09B0z4OL8ipsYhuIEcxossMvFOjlZS7kW8IdDC6J99A7TqVFPyzk9Ei6ahpgLQJ1vizlpzJdtTVIkP-9mHdi-9Npd
gqVavl7soFxSpllhKlIk9z9Ldtp67eYydUJWdQyU5De1o7XxTm2LBg26BhXO7N1p3R57E7tdAwC2E_7GmHuvSMT2hzDMclLKxqW_O6QG_lO4dUJnXgTuamRw
tGgP_42bAptjzKT9nGKrRkXa0qxOTuxEXDXbJmw15inos4a3M5WmseZ-uC53apqTq_LkaCwNesv5gZRQdYYWqcxlZW8Y0-r9sD1Po1SZzaRWFpjB66OlHHnr
yg30yzxGgqUE40RaFTBvIj0H9uJgKncjJyaqOnJu9e_FYIK4xLzhWPYXixfZuKNeKITeu5puWxiefBOljKWHdwPj30WBr81R0vra79qrGB0TyM0blXBGddWi
KZnxkVKhBH3lHY_DWvP5kB86dgHY_VNVHV3QNQ8Dy53PDuBz0d81QCkLPPaSpXufirzD7uoWOOSjnc8vZ24Nm1XWHSM04mRVth9NWzdBRD2YozxB5Le4cp2a
bVVuVIlCdWMpPsxsLha42di06jUU4yaNNfwnYSi7orwPsDwoLsFPAp8PQvN1_bBxMLWDrVVINdlB7bOeMFR63O4NiUpLlVQMFLiRojQsiZVjyKW0ZiffKN1q
2dkyM7k9UgVVOZXBCX6t0wevo2an1-KphAZsS3bxQWwWzaeaUsLYUyjUNf7p6GXQ5yxSdk1oenROSuJRYxkHMl6XAOCg07i0WEg02GCds8eQjnUb0mJizl7j
fM031muqt4wILUPK626Ym1p77cBOW_qHZRB_TTbJsu46i9S3sOlTx_n9sEfxaViTHo--4SW-QqzXxo7Z0R5toJSEkExmZm3XazhRujZRmWHDLiy1lF2vx1LM
D-BeWHrFrGcpFRlVtkQYHhINseEQuHXvmAv42NaRSq6uOei__5NpqGEYflRwf_rdBUhO2rZcXBsWkppjzw_xsyCJUtP5UtYdSia3A2vkxq-JQ7IzLjgXzs9O
v8nlJp1E7eQUXcC-eKfbF0CFcZ6WLyfITDJdDpUelV4pJnpNYn7yuUVvxUcHOqLSrbwTInvFM7fLUqL6q7-50CFrMOrdBm-NXoCIwLXxDUX3w_7bSNsufhqo
UBY9mETjjuVhz3qMulhhqsNlQ7aui5TVqPuDZPl1xmoVAFRoStleNQS-DhgzSske-I2elKBi4NazzA6hFDz0zmsbCUrjp-nfxzsKkiFxeBl3NFoj4HRI7ZhQ
uv4jJEpKT-obIzZJxd7J_uZBsECHlFC-vX53GhpptNmqkhscLDuZEWsPKA9Fv-Ddo-7jYQXFXzylRs78FQ8kK39BZcklFuCg8KSbrvZsR90z3BYgh8ilU_6x
7l-WCVRA-UqfwHA7Vv8kUx5xXFzH5x0tv6iCBF_hDUtb8MC98Sntfs3PcpbqNiaU6KbCUAiiUzAEWZuOfcetL0VSAz7jPSTUj_Ubw8jCfEJlG3z2xHlea_ZK
6eXfhpotP_QEFcu2pb_ZwHLzUfsrG-XKQy8fC4QqfzO4tavx86SYbuv-8tq_K6DNExT_XBG7Q-FTjCUk3yYbur_fxSItxBN7fiOIcdq1mBxuVXmtN3rOzZf5
JjyUw9dmxNz-Z9tuULBuGj0lxyrbJxH_saFRumVV_wm_EX4UpmfV27ebFerkZuGrl43rhRcwVV4uvjI7QCb383hOQswdI7nxFMctXyTkTBVvmXBQ1ftTMFRO
t-W_YpGcwXCD88V7sQkNiESFMjHCfSaUtC0vtbvUzkwZ46vFITyZvPbnzfOz2hSd_8ze6V3YSlRgRFOWCgszrVUWCzjRaTDqDdlB7en5pvNt7j6N3BJ7_Q27
FNt9VFCzjGPmc3rzCLjlMoAwJ9qpxLfRHsTxxRMMJlRKcj1JhX2PlAI7FJoxwlgElRKwss4_eBl60DyUXB3iQH1x_WgHgHiC4TrU_3rbBmVuZQkpIaSjlhqh
vhtsPccFAKFZpWYszSLsx6lfqCx8EmBR9q8YlUmnDL1yltXs0r1LmAmfxMdF-HwtLyx-Yi0_smDDhaReka2qdcFOqnSQT-EwyfQzxl1XYs-F5wEvFMtvk6Ml
VvsQs_CLQDllJjcoDpBnyP61WYXI47LEe5xFhVUqXyyyVRdU6R6UV5xsTE0x8tJP6nywu_TpFaqU3mQy8v14it0tYhw0s9lz_Pmw89oD2TBs2ftCdjfhplAM
ENkDpcKFzXeDDsxHzi2vtYeU-ksgLxQdVUs1N8WmhnK_cRt-xuHN8Zr0rskECnBINXtrEqGseFErtrblDdMEtm3hCDqB_siQxKsDRozOJehHlPSz4jS6_OfK
VopWx-zb6TVvCDlfro-NsZTqmC_lNSfUaODHeY_okUFRmx2-n_SQnO-RlhqY7-LZlzYDeqviCNyjV_xTKMhVEKYU3XZgnUjxcyZOs8dZphhiAPwZaIwqTUdH
2eVfxC5S-bngxHsDhSDjHK27IVB8jzsf-MWGVUgShskTcjip-IZbYJtO2pfTRiXRWCWxt5w9Q2yDi4TwTLTvG-pLyFQqeJcTz6c_4mstbsBPQn-rzDC7tPb1
E-PGyv5uVS_VtAOzUXv7EvmFZhpUlG_kI6_2Py0wwpEyUmAL0GIsLsKWR_Lds2VbOOjeRvEHm7OgKD2yT7LxLJwkpw0xr1bYFBep7dmkYAjH07rc3aRHs6kY
yzlZ684h1EmfCfWKqvx9QDHySCDSz9CxkT9bx75WRm4PJrvzhuy_6KMa9OPO1NFTwGyQO5acZBsQcmOAq13z3phiDWByKal0bpnYRBB1v_ETDdxS5j-U3ayt
YW-7J7D0j5Uh-hCN3BF71OxFTlftUqKaJgciZBN70RfExlhRGr1xTNpavEZZ99tyHd5_6ci2QG9x0gyfvyHhSK1xVXBM9yXfqMSukn7Ys8EyP973sMiljYpg
ihViVRZGkUnLau-mEmil4E2nvxqZu8M5jPTbCfOzB7lpFRJELpmMunvxNlQMlShjWHJQBu6w3S_14asXzeo0QyWZK7iMp5xoss1o0U3VjtK6UxYiFPlBdksp
j-mXcBrjvJr-tofz_2kkFQLTxwBw88wzc9lXzH6v2lf0rBeYjnUVjRBE1vqkYnhPNfR5yBBY-DBTibSb1hQsbNLToew_CMcblRo-qngqV2JnhOLr2nVD_P7K
8aSR8VY5yu-LMPGV6LzlYHga-8olyeeVnfSQzV48T9WwtdAGj1SsTEgdIjJwwnCnzZiqbAXDmc0Rkwa-jZpq-nF7FZcezWCdH8KhL9VnzW20s3FV7e0nzfJF
h68clk7s7bGrshiV660l_D0yiT29CNbFUPpazXwFZCnxF706AvOLEkRKmuS8k-pf8RCA9VB8Y3DYwDnm_7H0Zx07CyEOgRf9AB2D2Wl4Gnzxk1yOCBAhWUkl
cmqOZNUpnq_S7zi2r_ADPBukgEhdxAaUSdj3Oi03WtNkQlliuJrxzqC8U7Vt9n_ozHuyjDdJ9pdDv4_sjED45QJhHGsT6mxAShuzFXFdHzhjsO1xEzQuPVk0
FP8iQGeRRu_dbRYJXYsFiuTT0SuxSNzxPS24gkTNn31xikSQtvth67lOuc_SGdM2U-FZ3AhQPk_HXBvLicctfoekj9arRjVZgNdBVk6FWwuTedyt1sd0wtOM
Cg0Bdlcsv1JTtN1ceUpngGY7jpEHcpfyvwiWhI9NVi10SDG0IPazq8iIVjPGNorNAWnwY3q0U3XYq4Fi0L2ldLP9G8ezSF4tIVmuYexso8d9aGxsw8bvtoly
YiIFdLkco-puUL2xslDFtCyU_oZxZh9a4flgw7jektMpfxfdJvbgDtiWxTHVFQycYSwsDOIAhlRKdDLsVoMzdprEsSX083A9zBv3xVchxVvAEewrb-FByx_o
be-sXtVsb6bNUtxFCvc1Ge9dTtl4LJHxnRkDuqyRxbHSqHugaJUbldGzUwaw4IWsjZsGhsOlRp-fCX6vFkh3bUnPtPpaCTkyWKTFdCUU-lTkXSn5sXwfSCgH
izfJKbAj6m-R4mVF6uak1SngZxS1lzjT81F_ueu_-7pR7lRlnlLFh5wMQxzdiqm9jjzK4ug_QHODHxJzkNL-fFt4wcHx8czM2l6NuUdZssZ5tPuEVaHVdnZE
YTi-YYGy4cqc9RFkLvmMgUgk8_BgY7OxulGx5cfcnZP6JN8oIgNjbCb1sIW9SXhmn5sM2U73C1v0vyTIsIZ5plDZdLoWpNzhresJXJ1jz-FK39aLMDcUKI3d
0NbxIiqsPy2i6-6aexAwEGBhN0B10kQvNn2St1PlDHkcC4Sw7Sa5vyFAvb9BJYPnCSkbrkrYxdWnYLDhZMamvUgOkyXBrQtKxJKrPq1Y05ZEMmCroVb1gbiB
jPQSpUHpW8PAJir9BWBgraYzaH9aC2dboYCb9ykL01s1-YEQ31nk4K3ExZVZ9QFBOJI2-jHwivXxluhHp5BEph34LGUvABbkUwXtql_OE-7n7Y2RjOslHCSF
eNLxcvg_W4_ANsplK-jDtGAMoZONDNyVI2qiJwHE2AiFad53A6ejJfvT02cNa0PBRfnsBYpNMER-xcq5qb86Hb8-koncifyLILCkusDfkGLAGFgmI3aFYfBP
v10MPb_njEVWjDuefGpwcRa50AJ_oUN6pavsutOIGu0GkK9holc_zkJQ060G201WNFOVE1ugUkmEtf-qxH5pE8zT1W0000000000000000000000003W1
}

