sprite $103H [446x446/16z] {
xC6n00000C2WV_x04wa20000000000000000000000000000063sxcIzMMiB0kY0cfZtVz_Rasv_vEO8bK7EEXbb_-ZWOgbmB__SzVMZLz1z-8Btj8Klft7T
FnLF_U3XW_SLUje7ZzxtVhZftgbwoaUFtYV7alEJGmdwTy7RynEJtX19L954fIUIg2A9AX8zUYA9AfAezEYD8qucyv3hs-I5RUZDu-Pa3EPaRPlCoT8szCuF
6vDClVD9nkHyutrfifA1tfnaJBw6yDncPPAQ7hslbSb-TKAFth7evKVgwHuztQEdU_HqJ_VewHuztQEdUxf7J_VewPxkqTCzUhhdvrgUtRq_Z-1dofxLFJzJ
jXJfaTsx7fLUVgwUxj7JFNgwHo_7WtIliFgHZeVSqBrnSdeN8_MxrufARrxav-lHctljxz8R6zFhHZesUQVUCMn7fPVndd3TgdA5wQslbwpIVMlehRydxB-N
ezTR_VialVeAlK-EDCzKE3Uzwlbc7tTw7nifEpsH_dJH4rKaKKKIbPv8eeeagaZqw8aagaYYqgCdgaYYYYGgFP545KbKaUZH4qbKaKIbHqzKaKGLILHw8eag
agWYqQCdagWYYKgF7ZsHH1L9L7hqH1L9L97eqHD9L954fKUFdaYYYYGgFNgYYfJjDujU8L9PRQxGAqHgonLwIAzeLsWWlTgQHdr0UdsxFY2zljrSjqUbbu7I
yAFNxbtpzaclNBn-_UZrxVhrezV7MpZoswFIEozJCluyTFOakLG_UltYvRM7VMjKUYztA2-fqsitByL7q-lYhUsmoaUlYPVo7lHwUAblGw-6z-fE2tpqIdZv
ZhteTV2-vwb0hu6NgnikF1deTIvsVqTwxyTBeywbgFGwtvhBmbE2NlqozvyKzDRNnEkqhn2LthZ4BRxGcv6ALxXUQtg5krk1hwz7Rz_luwEtlXRm2iyEUlrg
5Cz0hr-zsYde5OhHuylRej9B0M-vVFJwBo7GUOxGAzpJckLhHALtxwk4qEjNhyz7hr-z_fdezQlNFnMz-wktfwX7B_j-swsJtlK-b5VeBKHgrQ5OzBuUlSBP
w5NRiCrBlioGbXwztqp7P1fd6_23y_Z7bISBlNMyQJKPZdNOZU5zUlGoXwS_53Rrig0tkqxlNH_2PumoUvR1TwkUxXsJqr7s0PLzNzDBKK_tiasz_8hmctaE
bJnOZzvlJVAx-PBUh7QkHQMt_HMzRV3aWNhq3elz_-XjSu_SeKTlVXQ-xwTw6NhPfbwEDPNIrACtmCwxjyr7RsFfNYrI5lH6zmR4rFk8xkbUzkTtZrvElzJv
aTtJlMDzJlTqx-I3pkDVyv__zeTsJ_Sco2T-laTlNz0hTO_UTggt3xsnoTExHozZ_ZbtJdhRRw76DzxlrlCTegbt-htrRQpzplTxlhT-hhTtzBfHTU_yTR0c
tgrwkfSvFk_enBlrfv9qRvlpSTbFtXTclq6FtigTB4ao9tb3r-czk1Qwa36vTZfwVeV8dVFvUlJyxYmzlxVkDIFeUSKFUla-lesULxgYjr2-JlKAKUd5Apnw
TTKBfw7NAr-_UlJwhpdSFmczVldwvw1tV_doK_wQXhz3b5vKUlcGlm56hyytgrUDIc_BBVTDUlq_VjdVczxwwl3DdVjHwMqfuQKHbLwsJliMjwNNlyxzIjEx
ltrPmAFNuElZqMlSvhRSXqVlEj_sFPlHUnhVt2hbgFJohck-lRDvz1RuhljjQtZqYdpR6xP8EIgzy-9igThHA_DjkV3OhH2LtXf1MW-ar_X-wbmvXqYoNS2Z
rwdVN6VO5-wQzAfyS-Kl7aNlbaZR6zPTKUabL-soqxilKffuzFgHRg2ZTxlVCwBIsrCl7htkwjQENdkbs3fw_PMqwUZrL_DkIQ-_ClwVdaZqw8aagaYYqgCd
gaYYYYGgFP545KbKaUZH4qbKaKIbHqzKaKGLILHw8eagagWY_NxHeoUIg2A9Ie-Ug2A9AX8zUYA9AfAe8j6Z9vAe8ebAZvwe8eagagZqH19L9555eaTF9555
4fKUFL55oZXJuTpqogSRW-T7fJTFLJqvlUkxh-gb-CRGMzzyJMyCxeXABo_fVT6xATAnnv2vC1aRLwBIcxV0OrtKMtZpw5tSwkrwOz2BIk_h0_JePNmsKDMR
PwCt8gq-yXQzZ3UOtaiFp358NMzEBaIbDsG-Ke_UvtTFz-Zf7ZtTepUFUsptne3UYTKJkxUGWTuDtQEdU_HqJ_VewHuztQEdUxf7J_VewPxkqTCzUhf7J_Tq
ZvxkqQD7x-JdSnjMzDOZPHvoJ8RLE2JpGUUJSvciR4nl7hWm6OErISOXMTk6tleILIHHwT6Z9vAe8ebAZvwe8eag4hr-9adxcVxPFdtG00W0C13COFiNZ0Zc
mvs3vjFOA4FNyYexrp_QojJhKc_OFiFroWRroiHB4wzi44y-yPuYNfjsRTgr3TiP0000000000000000001W1m
}

