sprite $103H [96x96/16z] {
xTa5ijmm60JXdfcI9Tt_mE7aWKAg_HrKBzEtP3RiTpgTJjgChJBcPfsDD9TAtw3DOMtLvXG_tJKlzjAS_lDyTU4EwT0QN84UD9xV_O3l6J956z07Z0jcUxfx
Gk__iQ-k7_YF_Vx03_o2uJDyovSBX_zsVV4rTC_urG9DltxyFVxnZtzyvqEwnLVoLBtl95wkblb9n1ENfDHFlBnVdR_oaBZCLy9IeYe_OKr9aQyOrXBL-8bW
JN6L3mXaa0K20qcPhmH200j3wdp5G909o13fJb_t-FYUtuS4C3Z2CHXSwwyL-evWpN6DhmJMahhfZrXoNEMJV6FoLkGxMNdL-JZHAzuK-lWvg2IYodyoOqbo
aa2n3ygNH8M_9jlIMRuz_jBnZo_0D_a9Z0QpGIlsqvRjUxgAV8zlRvySZ_hvuVPF-vTi7px-rJyDd-7fxWTznDC9q7BwKwSFdRsyjNygSuw-rPo3ZQwvsmWx
fMqc_gvEfxS
}

