sprite $103H [93x93/16z] {
xC610000082W_QaNgG80000000000000000000000000000006RdRlTZHPKeZ5C5yiFxl-3pVYOqPSmsAmosUUhJJEr8qlvxGMkhzoihjUtFhLQBFTSkq3qH
C3yJh-o_eyeZWxV_bghsEBs0z-1g1juRLsNDU-VQdeHd-syhOzvyushFmSljVHa8tpQiwS-izimFBjR2mUmZAp_ogC7QWXUr_8Ncnxmddv-ykC2Nv-crzEog
pplaos_xaj133ptqq4CFFVJGGmyzzD133xsSysl3ShQhdJZCyS3vMmCRUf-_zbPjE6_ONhRPZZjvl6oqZfrMKrUbxKUTqdVgSSVGEtdfDPopty9fu38EtlDj
uSkCC70AmzZ-oS0M1qRlvCTixBJmFMyD-wkCCdlkP4RXieyGSU0M1nw7YOMUdNHgr1ixjWUzqDa-rRFEQloBzplfeLSjU4QzjyaUsMlFo1upvnvNmkVgaJtq
MFVG8tkiUsIFxAqirhrAziWUUgnxw94zZlUUf4Vsq6llUvuJFMl3xhfRzYhVhNyLlchfhkjUhljmfGjwuKAlssQFQyekRxZ-UEz2eNURxCbwwAq_pwdfeTVI
EsOFlNPYDNlTg_7e3hthVCsMPCzgU6u7UXUhb99IMh7kfPHBiJGKUa9jix9NBlnzw6dFaie_hcVjmYg7di3NCQXwmnBx1HvwSba-sb-Rikxzjx9WXvwq4kPB
Uda8h53eILK7XnEzmRpPQZtqhDHQqaMzL6hT13pqPbNxH4-F6dhpQmjhMWqTeT2Rp7Vop0Ynq9jVTl2y5ajweNVNGWyzzD133ptqq4CFFVJGGmyzzD133ptq
q4CFFVJGGmyzzD133ptqq4CFFVJGGmyzzD133ptqq4CFFVJGGmyzzD133ptqq4CFFVJGGmyzzD133ptqq4CFFVJGGmyzzD133ptqq4CFFVJGGmyzzD2pZteV
FVJCt7CeTxkv7dhcdLmK50ZHcqwN_w04GFIMqEc0w4qi3tOJ_D1R5hi8U0Szz8BT4Z_qz3bpmVo9dZ9fQcNBzD0xiVE-vEaJlMbsqStix0ICFdsYf-DTnZ0N
ueVUv1NFtIvi9l2XfvLzVmeqlxufUdDdJTToQt-R7dgkXiTSu4DFnDCdFdCXlEY9UFgY9V2Xf-BfEzsqaT3JyMpHMEZfEzmjIMK27tegtayVzDj4FVGiuCab
yA4du-bymfZe2Jjw9Hzww_7Yk3P53pqJy5G-zDGAU7FuND13Jzp3-k3suthesIoyE2kZ5_NMfKD_Sw2tQDxKtnsw7dewdluRqDDthQKfPKBuq5E3CJzywEcv
IDFg97pe2ULXlou87tfoz3nDB1SIZfuGlRNXGq-FdbwY7dfwz1Q473rfELeVFlIEozJewMyKz1P6Jt-dw7heUH9A-cNewMkHlPiUUgQVdzQdJlJcfy7C3bec
VEgSeuUUZ_7m453pkEMGAe_ZedUifozx8yoHLFQk4oY-rBCZFVJqXIWqUuOW5UxE-pEzD4KFFOzKzjfnxzl_QtbdVqalcwg7daSzVzc_dTGhXsNlKsX_gESp
zT3pc0xxwz_DF_eMZ9RfeMTnahJuMSGFzhjVoPx5iEjww7KDjtIgvpVLGozvzawadpZx_-whQwtHGyy_Mkc2tl2ZN-ibdwc7NlfZFNDpps6EzRygd-bbKGyz
owTwCK7MOLdSDeUwkHvwRc-eXruGkfyUUlQ9NkgVAMv7wvxVJmyzF-0uFDToJptqeiVzz3XYw4sYNfXDr-YXbu_qul-ugcShZjRHyw4_Zc4tErE6NWYN_VMZ
FdgaXNheMUpRc2xxsEsUtQsR2Nsb7df-ecUvhmlNjIp-TXQzO6K7UcvtqUEQigYNR7JoaBorLoLnFMTNvkx-qZ3_TzdGw7jnCnl-MR-U4prX9fFBv-YXvqce
9VSne6Uhz6ob7lVlwH-IT3tqk7UMEv-vRvrdHg1tu_3v-pwlXQVjM5wYntFAxl-aAvuHwEkYXvuU2LyNFVJqPmulZ1vwUlXMH0-zXK_RrnzTZjxTmvU5tu7U
ul3vMVJGayfdyvaGFVIKUMq-7dfQkSmdP1kzXVjNVs-WfyzjEfy-DdfwFl84l0lHGq_ZSrk0XvvGbgTCddOrrEZfSsUUWcSpzD2BV6u_WfSlp9leIPLVofRX
eQTFS_fXkp0SUZhVii7GqwUwx2OETNqYHa_dqnFZEXvwEfy9iwQ6XvxEbrsm4_7GqoUzxFBsGg6dHYUx2HjBUEZfwSlP_yZ0FMTzraHFvxiSGFEJZMRheHSb
eeKTQfY5rEbuwEdnYo3kzXUYcRa7EN7MH4ylosfv4WgzPNxwf8cUNlvzFC4ElSL-dlH2JozplqntsGwzcO0BrZlq5lW9TEZD1FGl2DtrsA6tOWrqDrqElVbb
PY-6kXjwjohqq4CFFVJGGmyzzD133ptqq4CFFVJGGmyzzD133ptqq4CFFVJGGmyzzD133ptqq4CFFVJGGmyzzD133ptqq4CFFVJGGmyzzD133ptqq4CFFVJG
GmyzzD133ptqq4CFFVJGGmyzzD133ptqq4CFlLptLgplbBhN_0vwwEMs_wjgrzdsVrTv0ptqslxlQXzPi_s_7RkV7dgMiwKqMkqvTbutoklrqDlQlhToKQ-q
ON9TeeVUziaykN_LkSw7tgpzLIxfbQELqARheRVLMYtkhtf9R_jlen_8jbOtcwg7Nkqo8-cDuxIkCKSFlHA6qVJ6WSjFwg7N7Gr4ArrlxDJXK4JGGy_QnpOJ
zAeTUlQj_5qzzAmEqzcyxCLE2PpeVMV3PlFrOXfR-8lH-zQ6jY1xTzT3hwxMGu_ieHVJk8TVXTwN7p7BZRDNsjusG-_afM-tNVUspyE8Ncw3rSso5x-qH-ya
QMlNlVWNxnVqq2Dxw8dhNlqLsIDxwB7keKVsMFV87jbRMQnxbUoHFVHOzz0ZUnpleKVsxbsSvqIlNT9BL-uX2fxfGlRGYzVUjl1zRUqwOPWoogGQTd8RasPX
uD8Ft7lce6Ve7LNfzdhNYJTyLHlDInhCOwTP6cXQ7BXhM8kTZXEzcBwwvTTDQzrix9INZfLQNpUohTOmJBKmyF3UgRKCdJ1m7JheFQ3GGmyzzD133ptqq4CF
FVJGg-YziLv3xutrzlneF6lFrgkFnkkYrt9wIBMUptu5tjuiFQIslQzQdbbjx-f1AtpU_zcENHKm54DH02k3VyEpiA_1UOc4zlBpzAXHBD_tKq_oIJt9jz8M
eNXV7ZXzdxhf-qwFt6M3vTyZ-hdvpYYfnZhPNtTcILRx25RB6m000000000000000000W1S
}

