sprite $104 [446x446/16z] {
xC610000082W_QaNgG80000000000000000000000000000000000000000000000000000000000020sRCFCzTX60R0X17YW_PV-DNhHQa-I-8_m9Km1eiF
eu3vmks5yvKuW0A0_4s_kLtA-Ytv6u3OJo4foR-rs_atIIGH3rMOsHx8IiQT5O2avBOBAKaWRbV0bEssCriYute5gVQpV4MK5f2fTWpM1K5QcBBReLX9H4S1
rJgE6AC5OBhTmg_fXL-x_pDOmBHRH-TgGkALU85N-5VgDzzbAopKLHzYCcx5pFGrlnpnMxaeBsrBIV8HC-vbUwKhGy7pyqiY2HpdfcEBgC0ytBJ7rEqHMe5f
AubZdUWgGa6xzIX9_FXvNAufz0suzPY8mpYdWc9TKrw5vR6GiljVkCaXtKjB7FXoxaw2Sk4XSuG1l5T0hXYPTdAW7TMh1IZbJbvEikxOYPWBtRv4n80Wjoyf
9eASyfqPqvu_F-bPhnHWUkuJ6ZJtrvEQUFoa9rsD-WagJ5ay4qjiGs8CBPVPQA7P_bMm4vdJNm6D65PwhNTXe3jFtyWzpp4zpZAwm9qUlaP-vWmJYubO0pH1
Tj9pvF_j__heZvwDY5NBPuwT7qx4Mk2nEnyxV_v2vJD63auZriEXe_DLS386Kn-0Ellgz3X7zOnO4GRk-rKzjcSQEVOHAygHavCrjGmySzATs9-THsuTUFNN
BzxsSjnBMMthpbMwThMzQdpRjkLRfstRgd5SLpt5Je3jbFfIdZR4FZXuzR3pqBNnbAckx9Hm_-IfvCUholLbRjNrExXNzS3KnNB3JgUcEh9_RMFgEfd47ljI
30axL6_Br0toX8TNJp4cFpevjzGdyg_jDUPV-iJf5tldekOuYaFXIEBe8-__mBipbQwQd2g18J6kDkRirT-asvZVkY0mwE2uXxDNsLsEiZl0LAKqcb033afX
B9zuhCxkGuwnEpHrL0h-e0p0H_3EA47-Hov3sVLRa1WmtdzQ_bTsEx74P0IxX3ThA6B9IJ0vvE6NZDcLh4u_zSPViwGfxVfYQzrZYcZw6TkGaif6teEzR4xf
PcUMWXAA7GHocJsrJi1CA_4JikSJJm5lTxzKCXP5OvLQYlpIW2S-inBrz9ws1yYh1JEOnFpIdgu1CnpZzIdPsHTh0xf6W8Rzw0dcIOFKYTv--EpjMYVmqs1i
1th-fKMlnxgP3SiZ9QLN01LuYzu0QOfdprL4diOGegffeyRPiF9bqHjTwrJfcSPb_tbrUffO648lPW50NvcPq57qa5XwYi5TB1bxCvY-N2RL8VH2F_qN2tuS
FNqB09ijqZ1wB9mZo8sdbpPhdGd_EJ0LgPekZg7dTYxJ6qyF74ze0fsZegaK-TanzB3e4Jsgbn6vYE0EDR95RqWbNnJU87ApXaNleBZ7KhAazdeP-rf98AI3
wQMLSyQMs2D0-O_QoZblWXvwuzcLIfmSBqLLnuuOpZBhe0ci0-WfuWHJLJwab8OENKV6zC1gkT-QOu19mmSFVOFqLQKUPNZjfKvHl5WZM_I6mqC3337WNVDJ
Mjkqw1aRJRlI2zy32HFlloV8Q6UbnxPHW_VomoPdTbpe_2npcafvbaXVUo4dfzU-mahnyc38c5rvKIUGJ7QfaINwOmrFFFbwpjJ_jEm5GRKJDCslATwZ1vbv
FITN4g4DW5ypRi1QIouyI0Urh3kKfqdNKhD4_rL3xBBncmzmjofUiX3KZ8-VU7x9Jc4YCRjn1IisllabifrukEvVwYoMEI5xP6BL9vQ93lPqaqfViEc99Uj4
AQbOw8oNSi8wdN8KNLFjcs67J7IgIvQwwHcbaT1tQftGRUE4T6Us3P6FdtYYhT6zs37SDQdVjnaF2ngBPDeRwPIkYyvUyZpxaZfjDLSq2QEUwJI-rBggKnDU
mPVSO-FRsAh59ZgFnnexvdLwqAxv_zIRPHhTi7G_ZpVQcN6NpkyTQSuufR5tsylKYdvwFm8TvItpRiWjTNhc_18BcvusJacdBcirDD6Jz9LeffBnpRuPVaYl
642KJG_SHUE-lcNnpJdBP6lKAZsRbbxS2Q1iBWrRFfu0Q5CYgpokYLBbChsvzqQtWkabOfiEBVy4pf6S1BTSvZu4nchqk4_OGN6qELvyToqON_1CCnt0X0ez
8ST9nlOp1egP_ihCf8IkaffQiBtRlBR7ZfE7KK4CL0pPYZ5EDEd-5cR7Md2TWfZUVFiRW-a9NRFf2VgTg3tKHHnyotBa4tgtuXsfvwR77S1pHN7wYTQSnFp-
99YqCJGsjzZuU7rBcPvFUe1dx7pOz3W6eeEU8Tz_g6rIoE9OntaA__Igz5BD5oL22-Ukq_BzBETxgEpMIiyJ6n-_N9pLoBpqUBWkOTXBqNkl6p4GMc9thmXI
X1xEcuUDq21XRZqiU9wZkmKKI0Xc70EXj0emCfrxNJdcb-0mhe5ohEC6ikkOTR1UF_nP4NaYC2_sPnlBOIk65pU2EF2DvTcPfmYNXlHaLdekbR37bngRNdr9
5vXJ_XGpBHSDwCu4p8FtYowlPtkSmx6rfK8Cv0I6XKmf2imUzcC6ppLyGYuHqQsrt6BelBR7TR-epuGlESGGBw7fMwbONZRXBXNBPNmIshQLtwdQffwOYvxz
f4SkYY_1JedctxcdY_3Y8om4ESH7RqGP60zGwO-bKZjaSdfnsECBJlouevaDsrtCByQ7w1PQT0dAJt0vUh4RYWDC8IgHhAdFBC37uqaEW-McS7dXklIKQfvG
oXNuWgiVCHOqhhB9OVxhPSkFgcEuBhtO2mcv9EhBikc9jnvC7_-IgweSTJLAGHSzpZwKHbabrwK8lq80MLwRzMKB8r_HMohdoTJEwzAJe4mMEawUles9z2nH
T3Q-86y18GfgctfPUXBIqvynC4pcIUZgBiiruqlaBKieZP5VZnw_jnA66WfxnLMKGZYsXQ1m5uTNfN4feQHX_gNfSSKwDZVoQ2qqM7NQN5dbmCU87krSz2oc
nv66lMYyZakyjxCio76Oc4LH-EhqBEmijYgk_d9u31S2MIOMFSOdMu6F1gRSDW8xBps9lyhWRZ3AqIdzOthbAHbhNo-DZSeTZ-jIs3O2ExtjnVISke423GtS
4nbesN6AuRyQSgQ1eG5MCbSYHkCwkksrwKc3xL5i2VrP2atRlh38qxHYjcS7wpJdIED38XR7EdRuYzxNWqkXjnXo2kaz9P0FcvBFJipv2Py_3z11z88MfL9x
RD4hXlzRbHugOI_BrmoG_B58V_ptqy-SCftlOuRq7hrbUz91ZtlBF_vVzlouYptGMFwCX_d-x3cbbHx5uPWUptWis_FNwDazcptHauUDoSDlvcTwjmezAzJ9
eKIFcderUl6mbyRnlVHk9b-u_0-g_4XdB6Vp6ZtEBHbBcTwYHxOdP0Ezz6vVnYPFzF3XAFssGO-RfAZGM_IaOdkxq_Dxbl7qLjmROdkM_tMVmptdoZcfItQY
P_cUOVOn-BE-hCKswAL6UckyrqxlSLENnyX07WtW2VLNndjIeBV6Us_Jo_ATNhR7_n0zZ1kjBzlJ1dfXfOpfFVuN3mSgOc8cvl_I4gOdErJAbktTKakLsYhq
xaRqFZhH_NdYo1khrBVUAlMYPripH9JEH7CCplJ4wMjPfYThXkWDUbIBQfkTfNdsSk0pkCk3439_qs3k5a_elZuxYwlIqu0UUwUsbH6CeczLMV_A225wPABH
tb0dL_bbrDTN9Ld3AfLOyTGwsz4xgvBc__APwO7f4TZ65O7UsrbUSvplhWYqwUcHIsnPZSiEpQMqEBf95XahlnbUMesR-9sxakrnT_MjXESlw-8xe6-D6uQi
X9_VzWXHzrSevKqshASzMGgEa-sTB-AlKAuMz-eTmJaw3UJ3lCNRiZosZNU-00lizLAsnuXYPzN-zMLknITM-02Ctf78SqjvJbadjhqSnZr65CSwJlEqSc0O
MiTOLl_uqgNfo-TKevSdtIEGEqm3UkIWma_z2uVrUHC-GRqjdlft7OZNTizFZs98c2c0BgIoqxXasaSkbf4Jxzhn0nh5wWlJaxWhYdiGSDu2YV6LDsmHv8qT
qzZQs75APRUTA-wkoZw9H-AAhTsc7AM8nloONUnU5L7GrUQThYvdU_7c9_NtdmjNRXLyzumdW69MscQE_yQtTvbZUddQ7Vqv_QxlRXNl5Uz14ONtTtJx46tn
66xHItTkt-7HwJBOPku2z5oZox17ZNhRwlXOPNZcaMb3DtTNjO8BduaUGdgX8ufUUk4kPSm_X2r-t0XEMVYgx09IqDxBsLwyEIu77Ev5DaM4KTPxjwNcLYWD
szjs5R-YxN427YHxz0-T_bc2EwnIJM7LD-vK4AxD7VqzsbyqfcUJ5igulXAv8gMUCuQfPb8kPNeEsHLvuolrIDvocWRRx3LFJsHSvLty8wEeImWWZI12YOYm
tpGsFNRit7Yx93tEsjZSw0h1UMej0l93v6Ih0jrI_8_gfqXTb1vdZzn1vMEaz3PENZcyKVd-x3YPtlGdTiUkKn4P7y64ZAUdFQSdJdrYTzsFM1XBugEZ1DHR
8uHd80ZzU8fMKh1yHdhPjizyDkunK1Tfmbv-Komynrt1VhDyP3SxJfRFQdlDnmO7MKHLghhBUUjgLBUZg1iT6focfbSUhCSEoEAipsvrMLS-OmsZ3nwX29aU
pMTLwTbiw-1PKdYdeJn8RxAb98s6jqrFDyuEhxNBfgHNUyTHi8jDUXoZY4Se0RoT7YnWISdnjUbfuQtcjDrQwBNy4luatQONk57AOQQcnpFDJSQdF6HMD9YK
FI51Aa4H9NRrE6buD8g2iHGQFTNPfUsh6taABKmqnRR3cS292-m76KsW7sqE-pKbux_TjTXcLfwG7kezZs2PIRkIVnVi4w5Pz4zlhMA_oKs-F3qkOF8ukMy8
rwwUKJ_N3BYci4dFPRuDuLb2i3Wds9qVSv26GJxbLTo-bc_UPYcro9RNqtZElLs6TdRjOtmbLZmD6Gkpq1Ed1wcx9kBPM92MX6Jj_92KRjk23_GpTWrrXvCn
otZFvTPiVBVK3EzxrseD85G8TEDBakWErDg6K-9cm5U65y-RQrV9aWt1W1_S7bP7jwpJQ_SKBDu6xVGoppcZ12yk8_QF5634MzLImaCf9LDb0as3zlwsyZEV
71ul-YbBg2Txb3YaDKd9DB6NwR7ecITN_n2F4y8E-kQaFh_9PTYbi1Zr-YW1IQLo6mKYtFrl2ww3HbNsc32D9SbP8894Zj2zP42fJfsg05C8JIDl4BttYomm
iy--D4lXJrvtyQbX52EJm6jv69x86r5aOG7QO2djPFWdi-1BhUb1wZS7Xj-bf8GUrlEYGDkUU0xJUqWs0S1wWU4LVcmMs3c75BhBkQLEz7PIlAfF3Gq4-Hsn
tGr56fAYHIz5IRzOsYfI2xl1twEtw36_kWa2fkNr57OylKMF-N6PC-6vq2cHv-NHmwAdB1iRzpYOjKkCpTDk8-YPiWwakVl0IswxuoD1Xl_9TdgnqWa6TmFf
iHAS1FAFiKGDmKg90VJEXazzFBrwZTDH8oYFHPsi9BVXz4uH2Z6MNdkD9GMhSGqRutQrKVGuErhqH6YkDHIG_WZbMYU_1caylKNF01ZvprT4kmW-2CCkJ2yT
GyyesNXnac5OlKpyh6aB1jFZk_0YiTGEiBI-R3mzw5zCJt44lQUu9M5YKXTCYsss4VGOtadnoGWBXpGqW8sEfDXxs2udWySQNoap1FEiD1vF2RI81G1ID8m0
evMXbR9LfGxm0IRnsFnB4ZOjeTqorXp3mFGeQR-F7v0DBdelTZvCfTsvfpWUiXOzmSWP8XQ8GKEjizbfBdeOy7bBf6JLMRtngI0zyPd5--NlBmCA0uDaIYfM
Em4TzyJd5uQMY9IWl5Jht5rf0jEZ00KRFv_VB-Z09zRJWxDESECDa5ESiH9pTvEpGUEJIRBB0GRUkr_B07HpVVvi1s-DhgaZrerNFlSMg_duNKj4Kq9viXt9
zFXzXZ3NdiRZ6Qecbgcg_DPHrulUgSJqyWGxKb-Odaom8_MPj5vU370T4-oEUBATEHSzJBUdyVoYvr_ltWJ7HYw_lxAsGnj_bulJkziQxvnDDWSzlpmzB7fd
a_JGMvvJO1s_hVvuUSwZ6mygIZLKqB6obfR6-p5J6kob1RIgYoubZwy_MZvpeTFkn_fzV1kTPEeslfGypYJe5cTDkhdvE8fU5ZP5eNV9kMqOVue8tVQChlE1
JyOVkaAumilCbpxKRPxLSV8JZFSUR4vCB_QhJfUZ7_tKiyly1exjC2lGiqouR2GzmPrafprxRxpt91wvbTx0jCMSuVbvQqKi79QqI84UJzzWo2lBogTUJ7sC
_Gcb9JmcADFp_UtknnFR1BCae_a9uI3N65xxY7m2n8xWdHaVQmG_eGI1ROzT9JlQ0Odc3F3OURAocmnEMco3dktRkIBqd3F0urUIjJS_TDAJFTCeuN0tqTGO
5utO0FUdzzqMfKZFwNh0yysod8Uy2XlWRW-Os-XvdAE-BZ5YDuVNZ0Um0oCWcnRJO-FaQndWCOFKUgRentBRZPwrqpEAJ3izqhIBGSHolkzkWToLBktqnD_n
Rc8eeykpiUCG4GEqz_31JPZcmvEohL5pOA_TojXXiZB_hHFxJrOssJS99Hl0FgDpenHisdZN7kVvnHNPwrRstMJUV3jai_NpikENjwnCKV2laPbpu8wZz_mI
Sg21yjyMFCZc6jp-vEBkYEMmN-yHaI15QQuRNJ42iXU5_LR7s9EpN1upd7zeKJxUZmhutQeFxgugUhlhSZSpaU6Eqfp0RILOjqjB30omtbtP7MOse1a6zqnD
sJ8wcDoMQ1AY6IFswJm1a2DgxIdcaXbtO8S9FApHJBuKO_gKVGZUu26R1wHBOfGgT2j_oH7yApyKczdobwChsSUhlm2zPA14TB2MknoJ0UQ_Xfnt3rMMH0o_
J-xTCBU6WuSvKaw1zbaqjGW-XjB7UKhOW0BvygGOZD0nFiAjZAPnuDO-J3nuEcePefYP-Rzw3PgxkvcP_AgvBSc7yAaSuy8VMQMSzl_su5W00000O92_zHZs
LmC00000000000000000000000000000000G
}

