sprite $104 [446x446/16z] {
xC6n00000C2WV_x04wa200000000000000000000000000000000000000000000000000000000000006RlpDQSLtKWUiVwqFk_xnds_WStCML1R190rLVk
320jbm1F-Hfbbx2FAqJsQ26WmKtBHYcu1SA0zYp6KFwaiBSLv89WrCg1XJJG1S0ebW4mmEcHCFHeZhyJOB3Zb-mVmL7sHnprytzl5T4GNv6xi62FlYjZJ-r6
mGx07XQ_I-gD_8ASWGqLgeD1S9AXfRkW1pkmZmiCQFHVp34D4_hMEeg5xJ2chHXxiyE-MS2k_bibxXqBAClK7B3T2kXgEoliOxz50yrIEy0pR5wnFhwrwmii
ZMzUrmK_jEsMvxSYF0nRJAo7Rw-ZWOlXOwz3WTXIyOgpFciAM0RVn3KpeaRiX7lnMo48jhtACKAOUi-D06QEdhcjXzdM-EQcP_jf7NgseGXwCsiLUk4zWjva
2dfFAYfdq0jwCUUCNI-6lLYjXlN2VFtXnywNpiKth_PYvoEvnFT57mDVQb7G-wO0KhE2tbSCVAHkCIHumdiThlka0tFGUzHtcb_Gus5wf9iKbVDCZzAZOK3Z
wlq3OfzEdu07uZF61_1XSuh7uBs7OCpyKyG-4pyR0e-tls50yDE94UpGxtEMNWO4FvcuEpEaKePuLVZhANxYksRJtOK9aN2IHuhVhQN19j3eM6hiI6xvzeMW
bmww_oirEIrE-yX34GUzaXIQdT-10-a5FOf4lt-8ZA0tB1QWRE1zWBrz37hzmZ6qWH_Vm8Y3di06u2HjGZlH8oaDOMVealjupv8Iqy9BttAiyzciTkKWw66O
InWFTYxDQhwazMHRj0rmc7XnS1A2djl_cd_G6qyF5pfzU2teCRJZvIoJxZLwq1lVSIeSf4fM4FG-rF7tZdKM-6BMOgCxZcZMeKElBLOC5rt_H9jQJ922eIBz
_3jeB3mCuuzIHG_tX-CVSPIwK0kHSuPV577GmuI06_3nevsW9nBV1i_eECRvrYMEGO_kO2iKz1I50Y1zRGOzaG-NE67WMwCV5VGSwNtYUjsNqqEjY_H-UiaJ
yIhkSwIZ_-ixdlX1PxDSmM5Av-beFUcmNj5rBNLdizUU5N3d4-2hhOCVrm9zIRuq7m2sYiYPfiBPdjAkWsHWNd4wBPAtNgxrmv1Uwz7kGrA7EaPNRwaN4K_x
v0YdzNgJMmh3J1tcRFz-f_b4nDF2onU9xv-oyO85AyK9Org_dx8zLdnSX8v5JpWxhE5cqeal9M6-fUdbmVGm8N3JqvqCUaNYJoSnk7AC9YxAh6EYgSs7Y7Xv
UkYQX9E9i9Bq7yw99kKd5F-ypxXNjHx7Lts6CbfBhVjD9Iqsf8U09wpdAuWTY_i6n5NpiGszt4ZloQlHz5qhHUjgv5kQ7YgO-boEnn-TGTDKY3tfcOzUkStv
z3DXJ-jF8ybfFX4mAzEZo83CrvYJPbJ7Ek-y9Uz2BzNeKMVPqxJvLJGfQkVkz92xivv-Qf5FH0izYluKk8ulihltTE4y0Urd9vfld6YAAoiMfQUZgQM3opc3
cBva9TpqA05Hzc43Uch9W9Z57JPgHaImQ-Md1jjoA-ZfmYbsU_G49ZjahwgMQ4NFhkdPBlJyGmvgeTo5pr6nKRFEhUcPeYTScKHBKeYfYXfzWvx3UkKM5PHS
mpCe3AdNdGAOA9r1hu88j_LG1XFuHBKKm-0kzEmjUi8Q2Xu6Sap4QJxQIcTupxcH19l67-CivxIwSKsFvRrNughNokehUfNLF_rDPUjKkhAvzn3xiQDsKODd
T5VniX6gVM5ZxvMXEu7LhIUDvtgdSw8fwiKctjF37YMzDkjX5_AO3nyz2Yk6ztJ2kBAUOLTgCfySaCsszLu9mZNFkvooTDzOGNMLXxX6CRo7-UrsPJsi6vzT
L-iwlRIjz_Ia1PeAfqi-UdhvLnXsM--TRBNDEDkJTUhLqzA9ddI6zqwsBWid7VSwIjx2Rz12Bxp7fVVEzmxtxVBq3Nowsx-rDJsLEaVX_DiAHOiSIkLTzAXw
B-WXNgWCOeTMoYRpWHxXlTleURE5dd7-XN8sjd6aPoVJ5cfzu0xl1JtJz8uSVpdjG2YVqijMwT5OxmKzUA5dLbYnarwv4TxZRdfcWXu5FNFJApV2UthXH2yz
SlwDYwFdpCWtqWllbIHkyPwTLipVczn3Bxodpr9pDxrVJhoYHtCVmdlfMUyTk7sZzsBEgUcLydcldnuzz88UVxSAYYVqw5WnFEYze9TRw9tczwkEjGGzSWkz
DFnOInobvfoUlRPP76lHHwa7Uo_E4E6d5-VtRgN7NMTdAsU87gANEhmNrxLqFmMQ4-3ooWYnCyLrBPtq67XL4gc97fjT2U-dXwDqUjH_HM1SpwaVmISsdhkU
KxIZvfziIa_Vnz1z9JoTy8JT6g-43tgatjBv_dqC-Y9IagGNz33NfSpqFX6Jz-u0Y_lt_6VuKf5NdhhxafwxBuaxdo-UAUKp7zwCKQ6N72sAFMx39pmwwT7w
r07UwGlEfmvKlSUMz3WbLhmYw1qbZESVzRGFmtlDpskXFlAHB_bb1pmaIYfTPdDw_cUq9E4-aJXo7Hx9qRRgicr8ZrkVCWUv51Mmwb4x_Yfgf6tfYMG89nPR
fRsqD3njFV-mPwn43myz0Sm_xSIobkv6_zDLou3ty9w9NsEWw_dmjBFJZo1ijvxPRlJqCnxh-Am77nqFyHV3NdWlDQRHn4FXkJQUg02e0j3klRpfhsd0CO-S
_QAKdGg5xvntWSip-AhXTvVVlaIMpifMiWk1O5V5nx6LagNSrzZmbqjrwPG-k1RGuW6Wj5F7hqW5FS5BqTF2758jKhI_3xtihvo6otpsbAZWqhyRpAxq36s-
qspUHWeh9N0Xh2T2NlTGYof7vGoGc-cTsmR_i4kT7hjupv8q7wy34NKSj9V8ynVq65ZkTkphFRpcSrZ9om_njM8C5DPRSk3JePIqjFcSqmsVyIGzqO-Yc-lJ
uoAITCVlvGiUabrAFkjHxoNRU4zd_lHyZJdf7OMkcJxKOjbUz7ezUlv8k32V-Ifd8GGG7pqaFVaDx4FFkCWC8iqAJ1BlyFlPU2a7ZeA-8xtqyW-yXxf87JAd
afXmdefTwEdvN3Ale9-Tdvu9UYBeLPTxZb7b8Nn_M_Bxcagra44lxZr3pEWS0cZYLsB0j2hT4v_SXfukJNQjYckL10JLFRobWLrMwzfy9YHIAuLHlf6cGzgE
pwrucBfbNc0uo-PPBeNfeFYSfgTRTEooDhjm1DAHo3DGSWbHN_pHrw8ZPcmDVFIcH4jp4FyzgjzwEcXi3z5llaBGkh9ukwUXxcIIJjHoH8PEU6adD7YpqcdR
KXtlSydrGTRnfZDFtVJKAW40KbNz9TuJ2llKn7SAKkgJmT-FtxSlBbHSyUxfl14nf0uXUMWsEE3DYAy_biPuESunWJxVqPLfzg17Ion0ppTt5D2pxc4T2k_T
M9ATx2ZUFenUq5EP1oCfKHainzCBxntbc8JgvPy5FPBGmotLtyBBHEF1pYMXBtUQrECx2XHlSQyl9iZ1uo993McDdjpQC7fCOBqXz0pQ6c98HjEavcDin_KQ
dKAkjHy3w8Ntn8KihJBw3xC6lNwFY_BfLj-b6K6lN-ZhaFmghb4AUb8FBeUX7TtFxmjw3AUNHDjAr3x7lYi6iv7qodpWAw78_Mr02YRbzvZ3wJjKXQYd0nBm
ZUBvOxQNL4x1-B-cNpfYuXn3BV4Wp_J2vGWzAEAWP--K9dhc4q5loFIsapi38mvw1YQFSLeXWDI6FEZnP2pf7l5KnEnsXy9uVWo8U5xnP2Iy2T20-_kqXlCO
SmzYwjQGkuRdXJSe03vJChKc_qsDeVVUO_HxBkXz_i4N61yOwnPzS4GUtt-uF4hTGIxe3THlRr783EjIqDjEV2hye1VXCq7lWrvOB-YjZO-W5mcOe_CnwOpE
n-uRzC9xuJrMfXVqWbvBGmDw5PNpgHFvBUyDUWDKjdNSA3T7z2ilizxBdwANxMoJ0TtA2z7BZAEdDldv8iEYdqoGX-v-sKElD1y3uCrwXgZG67gqM36FWOTD
g5o8WOLJu-99UkHIDYUzKX-WfpU7mCEq0Xyb7esBn_gJ2qr-CNMfmPCMlJqcu9NmvIVfDMuFYNOnV7ayFSJhDqc4EZs-KcFfbMRZvcva4UQI-F9OUazwBwyA
ps18RCNad47qD3jiVf65k9UUjNelFnYROROwl_mHUjpGEbdALX7FyjFqz1kUOeUjf7mXFaElcvoMBQVi1TYVpvV6gDCgDWS4Chd8p-sp07PGyNtmqW3GWsu7
TXgVrcrMvwNjR-vy0DJYdMu7kqaJGNO9sqDah_ZyJ2lGbOByzOd93J949uFW5vFB6BQbShCONj2rR6UHkpHkDzAo4BbN3sFJGbJCAA7zecCN2TEDTE1uwHbc
YEydoApWmeCsKW4mq4KL1MjM23wE47jJeTd9XO2vvvKXCBEOc4Gr_Vo5io6WUsh3Bzad5QALUF71YVJVzk101W00062Gl_Kzlke800000000000000000000
00000000000W
}

