sprite $104 [93x93/16z] {
xPY7RiMi4eHdTdS6UFyNlh8XpN4KVDlVpgVYGlnfpWhG1lp0YnSlNhnuyU858pApgZ8Z-5-pPhdrSQ5tA_aVYjq_V6tH-_ihL_oRvcfBgWfUYvHodyDwxiys
eoNnCw4s_SG3waZLYrkLE_pUrlF8utWMfR177qF44wBjsclqm5Cq1dRm49upHko5C1x3COWDSdJS4LcIAcFxe_iGDsRPKbL9TX5NQlVdPjwebGH80anzrxE8
BQZ2LoGYIZvG4I5VWejRPZ8it6QFO4J92WI-82V9Nzqp7IwaYs1aPPov2rVv0N-JwrPE8cLByfaxx-HRfNal2_4Et-T8r1TBB7bWavh1IdY7IPPiAqdbXtlM
8WkxLCsmWU37IoiZikmFTHAQVolkxnESmUb4OAB09Btk0geLNKFOf8y0u4GP9Ln3yRqYQS89mAFsvGdm_91EEfPKhRamAK459Ke0sgvy_Mdwp2P8K0AeCPhR
wETzqZ67qolE9ZxafPcEZZGFjmc0xV2a8S4P9irLo0To9POPAY26C6aTEBseWWEEvt8dbe4Em1sBcB-BZjGP8VyDUM36pZYhwZ8jED0DfE08G_KVoFKk5vtf
TA1v5ZsNlFxpv8AZN2wq_o3vcehwLdCY2O9dpUlVhVavsrG_p1PttioMVBH2rppFDS-XQQVFmSiyRq-MVs2jqCClg73Ok-LnQ7XeOmwdd-qjuv3J0SzL7YG0
XFje8W0cz6LlyT2pxacrIdDjWm80nFpO5Q7XVJa0fF5vJtHnZjPyiwRuuGTgDEmHipMZStuwILkL9Ii-NX6gpMvkmIuSb834X0f4IQf0UhrbdFxroIO4LlIF
LwkXGwHSU4VhdjjkhnX1B28GvKaHLLW4JkGjUqJaNSUb11WH15F-tXHbHFpglctd29QjpCYINMHUvGU_salIDxcKuEcLAe2qhd99XGtYU_AoAzPzb6_A4jWZ
Ad25AQz6rCgRuU2U-uVLniY3-77XxL1B_WZ-6VuFzJ1ke8440Z1lHZVbEMwZPmS7CHAzlhlxPisXCNhYYXfY03rXNzKQA_W6TNT2OqzvGUtxkKyZzbXHHbFW
Wo1eG0dczIod9HvHxRSZiaZrSQ3uzq_GHc-kZE0Y8akjhp45_brIRVn8Tn7_8SoIFvyczjQi9FwxaFnT-UB5YnV_0W
}

