sprite $105 [446x446/16z] {
xDC7ZGKm30MmHb6VKlw0_m9mUv_DmUl7000000000000000000000000000000000000000000000000000000000000001wFynvJlR3-aPKLT_avhpP9Dbz
KrNhAz2zaypD-IXpawIxrcUXzvxpsR9xVI2gkfFpTIRf3uX8Tp9pli5CScNlJDHKrO4WR7UbyiNtV-7xENF6Qsl5415c3AcxSZQHFxsc0RwCS0eivzzNvYJH
9mDoEVyPbSK9pHIuXw_iJqjpY-0Ko_alYnM0KuPteIjQx_AYTeTm2ZcNDPVq8lp8fF0ZvelAYiLnKnDE6L-yZ2InxeDVRW3a2V0Ye7Jd3vdlJGA_3RBNkHw-
6aHFUlcFcctPq-dpuCloqEamTmqrHdQuK3iYEkIoq4_-YeUovJswSZG3N8Wk2qUvCqBcPITw87PboGNXPtbusens5_t1ffGjIQ-80xZCJqtZh5tRbA7vMGiT
FzxfSroxQwKe8zIeXNOqdra-gsy1v4FnisVeyaUkniFuJyiZDfl0KWwGlw0CXIu2h2TWOoWF_GLHvJTmn2iPm-TZ67Hf5cAqblk8pWMIdHsb4P57WrSA3ZGy
d8U2D_H0Zw4CXC_AuRPHE4xgakzzfft6LovZu8DgFumlb15yfudYzHZY0AkMeczx4B5ylF4L2U-0thDy-XVWwM2o3r-w4BxZeDQNFplisU7WnNBfey-UfmCA
azu7oygaDstlr-DUdlJcsN-ixyaVd3BFd9EV7RLnG7gVlCimwQqC7DFnc_lttxyRzikarqajaMJ--VjBta5nfjpOVuZCp96OdmXmixz7Rz8p1vaNY83FfEKl
VO50hYqosHwxcvDUMvQO-qMO_RBZcVMg8UKNHS8clGq2ztPc5xML1-K61SDe9O-dcb6HAIN_KKefaHNETDk_N9hj1fTsb-1kPggQS4yIT_ATwKrwhj2XpS50
PN-pJRXZrcpfCOB15bU6f8X_czERIQUs7oQtxjB-eO3OPdjiRb0sdAPBFZUIR1_u-ToQtlux66D-wO_lTgDka9b5YlSUDDdMwVQavtL_vvx8vnqo18AE-FEs
SSoO6xJ8Lo6W4-GqGQ_cFxunlKdFLPvew6knt5YWtK37nhNIB1cCzpMsT_SweyzrRarl9ftnOhkqdRPqlkDlzPmMavP9Byezn2qftYfh9O_jRln-VtxsgPdW
xdPLlSTvay7u-mPVqA0tXoE4pspsJ5mLWcbJduD9hoAdiAJ-7cTscqCjIbi-ES5IhTVPt-FqIM_Vhs6i0-WtMzYkBcVk4GMp4xtE57kS_hp7cIQzFJj6TeF6
Gp41CjSoKQlbg_H9RyV2nrHdsLgjJXAklI_c7FMUXG_lRSQSUOdebHxP76gf9vrRv9o4YHcbjfBRtJOzVTBRjrrhmeRwUvp6IeDpthcupto7CVSfMfjVMKvw
k_UCN3Sm4_n7I8chvZWdFPwsqICOmarrM9ezqJcI5CMjwLdFRA0zb8AqIM_z7f6PlMXvCfUiopn5V3Xrom3tdkyy-5YPaqoskbzchxItyTBM1ht3tunDp_EN
LlRBBDx03bP7EIt4IdkfJP277IZJ-PUrhWTMX3tO_-IGgBVHNUxJ-ciVcOv53mtJo-dbk4TRrEdaRM-6A-bbxwXn1wQN0hrE9PAucfqcfuiyC93lffSw-alZ
bklEpW2aqzN-BhMbJjEBhe9s97gvONeuhHBOtoHpl5AlYsnLqoj3qujBUSzMPx9tt0OptEvU_tVX_KesJuJtiGDbexFUvYJwW2Kcc3ZbrfxcuCqMUuWYwCyb
q6fWcY7bA5gljQLmM8lK79IULIwyl3Ifn_J4rbrxb9FMsu_pXohpEJsCJi_k4qxZAdhFVQuxNy8NVaEZGZqFHCyYlNREWho67ff0_9KMvqE9zwJIBuBUgEFK
gM9w6JsR3-neKrlgfuSGw4ALCwxjjR-CrKoFTZrClgxjNsyFU8DPIWcc0nshPKvmDcFJI_bfFf2MLeBci9u2GyKzRN0GYogSU3lG3piCpqewmElHDXlWJfA-
gFvtPNpXH0UcHqbFvMwnVn-FtYmTJpKzwkPco9MFG2zNim4N2MUuOhihcbjqbV5uq5QBfgUBFMrwWQKvuBjWiyY75YgDHid7mz5BzQXtPMiCrsepUVgfF2m_
TUE1xK1Zy55FlWsUUgFWkOpT8T3me-xz0rf8DADNboS_FhrIgHSOJ55VE-yhi8tbVAl5DyS-Mp_HsEmuzFHMynqHY8ibClQcm7n-LA5rTZHZYoKQMopODJqC
JS_rvSZsM1yZDXRDlMvsfPorIa6Rdbv1WUoTdvVrxVZqe5rHKXSk19rKxujPFZzJjchvPm595h4EEklqaLzSbwlq6EZ5dCM3Nqh247aI2k5EIPkVKvSf9ei6
Y8pvIFIYhScS9Nem1TRK_65RfLgOUwXJr6bertaGUjHXJvM_CLaFHwmsYCizg7yIvgVEX28_oie5kAWP1BtJoFJmv5guZe5ohqt3Avdu4KkfuGjKKkpFtVwK
Sfr-P7hHyLWuvCtWPMp1E6ijgWWeiZMK9_WYCDQNqUs1ha5n7f-UY296OMtYSgRAut6WwMZJBAWCjzVjNkLP0UQOz52b5pEuvehdirqZAm6D5Ag_1jBuWkiC
vsKYQJuOFHtsme5N3oZWwP9E5uEbFX8SrqvqZ-ASZqOlHWtLywoxgzpgBdAX6yzwAYtuxSTOHndulBwzD-eqDQ8HgS8gnRgzFY-88ZoY5FMlZ4DYIGHQckYh
FwN7mUYT1Rqa_AXfnrclzQv8k3o9AdBEZ7RlBQ5gXaWFnwENwau8md5c2tOOn9uBbfLdY-iYUijssfAEHo-kMzJyamN7AKtF-Y9DLhupziHKmPB49d4wEZqN
oRUg5r3Vb67V31VAinGutQAihgKKw55OzX7frNrLkCAwMi2f9Kqxah1QyIaQHE6d1gIdEtynqCKrhMCWw--RGVVufCJj8Zl2GwoRzCISTBXqNeiwaFtft7sr
87z7SD6XP16DEelq9ZrTOGcBq8wpz8xdn_FHwoHaAl54jJEOzAWYKB2EkY41kDtwvdKsa01n1ILSPo3cWbxI3d_IYnMUk5hqG5Bb8FRJIk5jPbb2ucHtQMTM
WQyQwoQzgz17pm994VRAzV_vywbVk-fPq5FUDX8p4UicFHrbT9nXZPwfcRLy_IJ-CxU2YuqL-pxWHTVVAUW559fUg4KLlKalvdXOIezV7vH_F6V-_k_by8kU
xgqLR4ZF3crxVZ-md9xJE-KpJp_qofLU_lVl8AobXpQzqxIzAxtm_vg3uKhDoZSPV7d7Slbvm3IzhJtdf9UMqBknEJjVwPt_ZtBPxikC9htG9EYmlKal45j3
Bv__3NNcNjkBzDgsD-dPs-cT2E2hnhEzFUUqFPsrQ1-ewLst0R6AtcQUSrOCWTufVvFAjnVnaTxvZROtUosnhzXRhLyawZr5huXD9P_q5k_E-hiwPKNIunSQ
b0im-sP6GK_sEJVeb4rwjIvrCADos-Ta-UcW5RBSv9mGz9fTQavwFJj4fwuT8WHwFu0ARWPPSdM7A4BITeWbz7XiUlsxim4Dht0jN-jpV5d43VNyvjrPEzfC
MNsJEe8LerviJAaeIU2bDHc1QWpqw6oFGAzKPyeirxnJQaubCHZVwgaa2tPOtQaz7ZrsJmH6UpCT-4eelRNQGsZidmYSz52VniL3siAdZqZ9dQQNzPi5LapZ
7kSEi2IlmzLloUkLAWETNP6FvyOuP_ya_A7fnKn5LtzyyaJQqeCFHKLXwxWBHVZxGzst7X1rt05cbCqoT3oDrlJaWcTnimkgj-wAs7qiUYOl14HzB5mdz6Uq
yLdb1h2amcjmup46nYLtk2T-H2UaSuDuO26tK9tmDZwhSFOrTpxJ3a4FAj8WEb9b2Q9QPYsu5YoBmOWdANrbywa3Xw9NUUQwxhPer-c1fNhMJk6IHwwo-uaV
uZQO_9oU3KfF5Buc4dDvDTlFWowe9Pi1daWuqV6qdU1KXttAd7GbqK7LBvC7omZ61x497FWfThgkZoiYhtdIbHtYwQewRT6kqwZ28FtPSrKBORUlnYpdEZo4
gBVeANDn-HsCNdGyVKzuj7mzKlZYyns9_FYCH-fLbDbwcd7Iw-rmpwLMKIGSohmlEjAiUc1jbInFuzw-igkdgyP8VIXwfV90VuimnPEDgOgkB1EJbWggRwnv
ySd6gD7Zk6_JY86l4UiyYv-ZB0eQyDXuMnIpyW0fU4eJfp_e-nZmvDk4QwDYNKmUujEYwIUfKkfsfr_IB71bV_M9_la0xo6IssDGLuu_Hy670R3gUicbmWvF
NfnfwcEoRW353ORZlKLAkqwPu55azGsP0CWwRdF0mcVADza4iE7a3_46DxRUEaknJIJVax2GO2dbN2w2O2xaMQyO-HOfDkcLeUYX-lfbUsPysM8vs2F0Udwr
y9ig1aPJFEHxPsEaQxyz4OBUUcbFlkBjYJZ2Ev_r9KYALqnSV7jwARfHbuuoXUD3qZjLtccNJHYV9PB-9axCcQvzGOeVJk7KOwCbQaXw-ikWig8PbpzQBses
9E-uLgdsDc87t8AjDTxOZMTV6EFIarjafjrLjhOfvRPTYWzf933Dj-LR8z1_jb2d5_YOt6hJE-crPfSkwKIYswWTutb4qrErJjJv4FHqtkAvVdTAsvY8DZlc
gxnDpyDHDbNiHV50z4mOdqXSclIkIjQkw89TQQLA-YcBlV7fwSPHdD1KYUQIY6QyPLBBNynJ3l2y-KTIf9-Yxp9egwpTj8s32F85mO2tSyWWfdk2vY1pKBAc
Y_tfVWRSekyoR9kwlM4I4uAunRPKXlmeml_z5Rb54crvy0Qnxo9aXw8Nw-1OvIsNfzmXfixYC5gQC3rT8mqwIQsDJ_NBUar4InkUUKhUfXTOXI6fmUbPQTFp
Xv9SqblFJuSlNqYFZM9V5Nm7e6SFnkVB6zBcpCbDP9LQJ5TsuBBmwdU_38suN8QaP-rjjTWjVgLZQNK3ZDqO3utCDZuNYwqPB6mSUYSfVJtClQzbcUpM7Ad8
qIryfAIdvIuAVclJuv0FQwb7lavPCAjR-43YLO3Ve8i6Idlj4t6QzBfBl2WJ8Uqgk-gkkBYowywDOjz52oFIooiMT5tDvfUsytvugelUNh6ZJfHf2Ft6ntiQ
Nj_2DKzyiUKYkh2Zqsl70553TSh074Mcnvp7t1EPxuIN5ujFUfM6HlyLLQBZ-bUMIlRoPwL6dZqSFMjSbkZ9jccIwRBT0Lyz4QFfOT2RzpI1r0NDBMpTzOWU
FnWznaS_JNfHHj9xdLYoSBXKDxK5UalDTYCX3q1lwtxxWwjraClCJlNLV9jWFsIvjruMxAZLvTG5XT_WnYRqyf1p4Uk5Mg_BqnDqzKhVjbcpGnRhwsKHYzs5
9e2t0k2HZoE2tOPUiI5l85glf3OGOfTJDJhrDeJRQTBRQwvOzyYi_tVsz-SclVNIAGhXPgtVb1v_rscT1hqHnJPUX8QSPPDJIxOwSx9F2HXjVPeBILaAxdVW
m2mKPYhSTd0vavwPcxYjH2cnqUiCTnPXWmUfHyropqaI5V_vOh-CApekemp3RzzqqDiHpjmjg2GK6vVhavwhlLLFFG0Pscif8DsqlJkBTUZR4Sp1fUYijZVl
6sojVAXiEtfNfSvzMaO-XWLb-wHdcpLPy7YhNYAPWqWomVtvxPZ9tXyoCFGmv_f121Agn-bVWdzBz3f12hDyDprEUifvhhloJjrpcGNV3e_ByyHwBjAkzTC6
x0OQ2jpUVrXgz3YrJFSw-qntqbilpr94lKjTc_pSDb_xJ6t-5UebEbDA_hzI2hzo0xiRRoXm1_VXO5uZOWMxIM-zrl3pVNk4SnnGEz2tcTsaj_y-YJbIv-QG
sqxVlSoKywqFtA7lloyzHvBQSaSYwzYOalUZc_JsazbtYN1hYIabkBlPBrHB1NEePMvjxgb9R_kWFzEklHBkETGoYzr9R_ynyZdKCjk42pNfpQGJPS_5DpjD
Stjv9fspO12hTspFCUbDUcP_AckRz3elLq67Ny_JzghYpcTlvQwZQi3b81p6a-C8tt_xjPTt-Rn81AMKWfC-BA5vldN1b3-xtYlOhJfc-FXYyMmiDaAmfIVu
xAojd0E-dUbbUPW5lStXbGyjLtTSVxQ87YFgl9tV-NHwTWxA-toQQMFJXsMh41o4J-yLRUyzeUan7fx5uRjb-HnKx5FRx465jlbIATgHNk4ArcyMota0qmlk
V_le5s9CSAIINjdeok9yBmpGPm_sjo4zjkb5qtod3ELyhpp0DadWXwt2NZ-zie7F705Un1TLR2jw1OAUSfLlfsV1PuwoDyPo5igmJNhY1PMqn2Az-ElN2vMl
UVfqePoLIhODqjiYKb1fUtXZJc4HtM3ZFEMiLRWVFQlGupkROgA-7K2iyyDx3PmjUhpBKVCRiyoeRAT1X7m-RmGmqaEBNZczhzDfp5Ls1IDEUMY0RwDdsfFM
NIlNVUJuXXT3krQ1lIFdpFUmSfKUoWeJiUXCT49sA7ubOsripNPlwmXu0qwK5wqUp4-_26tq2LMjah7PbClfFTMp1N92WTreGcby-mpOUnAbKcZnkXUHe_Jx
ouFPNHHuRgXaOelfJhCLPutSMdUb6Rm7hl-YIgaIt5-ekyiZtjrjme4AvGopNprF0_AvhJ9UcjdVrzNNXVWLAmGedQLkE1nFffUrPeYTbvRcfhigHrMbTAfd
Cp2p3Hsb0LrdL6Yd8yl2vMghb482m7jF0Y1pQLYSsgISGZdtgbmmvjKG0R1Se8Kpw7IOKw6SwbM-YFYMNNJI_-2VyaMTdnSpgMXrKo7ah56fw_m6PMAYgzSH
Vrd4PDHCO_uWmhAyVpS9ClybWfczJPyfvbtGRBPlC8LGXUtjA_FQYcJA37ixqWktj_hAATid8ILFMsaAGCcYU5jR8kxd9wVCx5_FfAoYzjEZiLzrazEfNhIC
9B_qryri8ltHV-t10G4000G3CFrJYm7VLZi10000000000000000000000000000003G
}

