sprite $105 [93x93/16z] {
xPY9jgGs34IhL5BP_lyVJZzCCmiantJsX3lpThWk6uaDkERXuU7XuU7XWGpbZYA8FuPGjJvEz5OPlq-SxJjTx-r5xtqSj8eFpTNVXbJmf-daCHyBTyc-fNKI
lmhbkLNnjhglp9apnRgUNzixi4ZKLv9OTnTnXtpfr-m-RRWKg665DWgtqHYBoOtRvEXOeQvdo52zICLYelKPHjbLcLcsy-plYsiPO_2iBX4W2L3buaakB76k
bYeYiln5PI3A-04kLrWVYPzHkJ9UAEqAn6csmAUrc4uYf5GGKSw5ObckHH9fkwhi4gHJXNNWLYsIEE2xHXW_7iuuyjnhY2eSC3cFQ8bHmfjmtEjgZV7UJyIR
UKILjl16HDLH0tSAFGkq69WSSTE1ZO0JChVg5TRWb5l8GXM87-6n8Z9X7QsntaLXqWf774chjPPJlO_hH1R0Mt81QSZS72m1g35QwwDltslctZOwvhf47m9g
2-NT0jGm0KIR8xFc7qd7qQ3B_M-Xaeuqd40SnTOxG4lJ7xWfRxlSakS8W3jsOYHGHOSAbR2Wct8ww93d2C1mELnLH3UWUW-D-bIUTSYJpd0wq1eWVohlLyaB
LfgfBNdMxv73WcDVSmAjWn13LsiUj-G2Ih1exjMYKSUYSLOBlgyMtcgYggFEqmGyxVovpiC4Rya3q7STwWJWqUqsHWBXZpjqRXgEuzn20e3Szzjb2lK-jrJD
EBVaS28tGmP-802mg2qxhLkdtFtOfq6BdcewER-f_JTE7EVplYpNbDD26czappkkYdqKf8dAlUrkNaEp064I5LIzo80iR4JimU5HTw_-5jwmNEABK3bnuDnt
yTtxbY1sGeZo98ayz77a-VoEIou1yOAWR9qEKyUdzuhSSbTAohAJrAVtYkUYhHAeAjkLGQRheZKMkDgGQUUx0fMshWAjzz19lyMUuRMmb3UVdHZAb8A_vn7G
e-4szKzu3ctNtHODoEr_2vp8HNcEo-ZLeS4OuiYhVOp5wAFd-RSDES0Xz9yzwcDqB59NRrkwKL_oH6lu3bOVC_SYuN7o9v4DQ488RwBQUD42DvXvNhGISGaZ
ps-Xxhz16ysLYk16XBBSzhzr1pw4UxXhkfFudOJAhVVlfBsvCeW_4ExWDtbuU7Zu1G
}

