sprite $105 [96x96/16z] {
xPZhUgiw34HdDD8Ol_yBduqWJVjjVk2qvvwLUs9M910N2_zMthnvy-RDcpTlI6NQuy1sIlmXTNhCQpQdlkl-PDi3RyROvWSZ-QfyFCFytK4z4pFNxJxSgLj1
3AtPnqBgEa99t2PxF74RZJqSt4GTpHeQz_zWperOndCATs0FN6VEN1YupksmjcbSmL3zGa5SfqtSmbTRYYhRLTKlubLLt2_FYo9tFU9cbAqxIpLt8aad4Lcs
NHbWkkvaZPjhakmCIfAgewTkRBNx1Kex0unV456kMAYw6qEPfCfDYQpynbuphbBLBWuoLBPUBy_s3-nauKaLgQnAaULuYe_tMl3xyFDhcAn7_IS_z0Igbihp
ELPcBtnI5bif5nuu4OvUPblrLo4SOJvZFQ3GH54cd4lbVwxBZgkgxu4JISH9Y4vOI9yriUQNGKSSTnrvDTbsffdUvM6k-Td-AiYeEk-0vvPIRcroqQ8L3bh0
DdF5By2vQtT9o0Jo4Q5tbJhw7e1AOAxxzI6l0lZSW6C2iCBCCy4rFtO_7QUZOqHEYKnaGbD0rST_vul-5XmYm5E3Gpa4JWDPvz__c1_9mSn1VDFFfp_CAXxh
XqbRESZTLQU_NlJ3Qa6da81E0G5t-URvMw7M_Mp_6MESUwZGQ0xWa3_hSrlsLo4FGz82U8QOZrzRVfJPYyU73f8oEm5kSuxzqJz6ttcCMlO3lPYpxmLYHzw6
rIa6NMSIykBnCzk_cpl02E4h0i3gdnoeUisVHWTvsklnHcLYntcU8vxBh9uVvVXoVimikzZ-vodkzA-Utyk0S5B2UNrBf0CD0-4UeYM_yTi9FkqCxigq4nzK
FMjwzVeg0Wy4fa-IBE4ak7nzTNrzA88X1K7PUldwy3eKfbrIXB8wWy1Njdl-wqknjF3v-XEoBpRQo_CBbfq1W0JGMvWlN_zxRhXSFwxAh7BRBw9QAFyhGjKe
RinwLkUFwxEUdv__vlVcxqdi4CmR_kN-0sTY3EH4JjxeFwpsJpI5RVTJCs_qJnRxFntrzEFb2zdzds_sht82qvt6y7N_Qht_Pk4p8g25_jlVr3zSxt_-_VtR
zVxpFvOtRzwy-GC
}

