sprite $114 [446x446/16z] {
xC6n00000C2WV_x04wa200000000000000000000000000000000000000000000002OlJlRRf17WW1yeOiwzE7zNtTMdPaak6aiDsqLgfhrLuADzBc0c2o_
eYX0Z_55sROUcpeI6e_LH04GW6LGpdEaLS_u2ocqUaOT9BTPKdWuLT_KGx7vFRGNqQ5oeuc1XL2Tyu-ZYjEvTGH5P_QVVr_Dbj1sdGOJNlhefqt3EwTO6D9s
Gwtx_bBXkgG4FrWTc672FOJiF3S0LXfWQ4zxH6Sz0DK-oywcoF5GlVO154RzwiKbmKLxrzU78GlwXJE6qGIsc1zhw_oS-c49kyU-9fUm0_Iwf9oWFILFzXkP
MVjFhWpYFuCOtjwSGNTqO9B46RbEQJqlHiS74NpgmFF7VdYWNPJMCp0uk7qxEBkVYlVcYcVX_LsdJ_JmeHvUwhNBq7qyc2vfeglCzf_CqBrnlJuM-_7Z1OlS
WmezltlmzE97nKk_P-0v3MkKtVC77y4NpW7CtVC7OSRE1sS6AtGFeEUxSENS7jcz7ce-vqhpyTth0J4VpDdpXRe7MZu7Rutk-Si0qkQjr3t_w4dQl5Mx1wDx
pnCk7ldNU_6dndppv_eE4tRFVoedLAS-k7ZjVt5lWheVm0TwoEgUjIltVDl_yuAFj7cjvpXNkBNi_tV_LqRr-lOVTQy_Vny_dhiSF48-EFkAvl15mVxV3Elr
xSUxrxS_2uvud7pUONDKp-xKyxjttFvI6fsUNpsRMy_ltgWUNauJB7n_yA3k4RNFtqimTSymekTF4p0wlRDNfOtesKtTyqSHw4NbWv6KBzx7NvCQqZCSjiKD
tVlrLA7UnMcIwLbAujLBxPx__Abh0m8y2ZtxXfv9p_dXWbZFsJv3hvvlJhpnrOlrd4XFUdvcraEuT_LwBx_Ym9VqC6dv_9rhFvEi5_iTjkzu1SyVlUD2K3sq
x-a1UBKzOFLwxSNh6_EVzThdV1ZKoploZHsvoSeNtv9juyjdzZKzsFkRGth9LpsbYVMsMV6a1s_Y17hkkNkTxk49UhQi7bxU9yAaV6cxLQ-dPSAqUDRrmBTE
gbxtiraYlO5WneMQSQTCIT5JzGXkn53fYOzOJv5UGOYNIdZIQwzY2wIz2fbUMrKFfpC7YTwQVF74fVVjI4zwsxnVWRQNWJq-eD7hYU_CwfgJJCzMn8idZYdq
1lT7aTu4aHvlf2S-lPeI8ZtXIK_VsgAR_OT8JzsJdW8ElNOIUsJQIMQzH8V_uqD-biBp-IOxZXFhII-UY_GWFNLFUj9pT-RhUFkFV9tFvjI3kpFubjtkncuD
N3-OCNMl1yT_5SlL2_fpzayrUfiJHpeV43DTA6XV0hguWT83WPtd9pq2EzTFUZHslf_qwkt8_AHti1kDmMe3wSLu0v-exjK5zgR7zS-NNZiFRYfUmaOZGJkF
jsIJwhKeT-2POMp3B3m_q-jPaLvCKE_7gOSlwNsw_Dbywjudroi9_khU6sU2pERLFugl5r-aOVxksMruI5lsp2_SoQuvuprfVWmsdhGrX-Mr3mZivjABZmBm
OwLuVfBuukaoTA_-pR7i6_9M48Bk4U3rV85lnkunuVdjmq8t6V1DlOaUbBzx8C2hvIFIgsyU4P_qOCuQ9_CPf7TpzKWUEpxTJAg75YHXWIVXQq5-4s5olMwN
oeTvzLeSS7MlNKdUyjRpZKyLw-aX4I_cCsJhBTwz0A-yVEhUyDBMywbxzTKRvwkwQh4fzGoPUjYhzNPawXcyLPlr9sTHr0g2fu6_QjFU89AUbmNqt5KbV2BM
xabFtQl2WwbxsS6X4INbWxfNKBsfdqlTSwfNzcJgdlIaPmMHNjxxrF5wze-xs_cRP5nrebt9z7hEhA8a7Clwnpo6S1F_jG8Bqwu5a-d5lvmpN-_qerw7JhOP
glhOFBcwrwvcKC__OBpHdgVNYFNmPJt_gBfBhw9xzf7U_YFnUC-Ug6UFx1wGfkT3xB_YVS1vl5ezS7NFS7lrzj_nntszAZupXkxb9zOpHyz2yrXlbQ_Mw_LW
VUpFH_k0mRyMjNdqjbMxr_LUA7LLwStPlPxzvoUuuqUyx-kfUprmRO_Z-pHwwbxFkth6gAVkTJmGwgbxVS08kwVkeLUFKK_TwtYNzDIzTYM5tTlJzNHllQvx
-yiKtIB2C-_lbNLlpzVJ_RsMrZtfrNUl4NTFtRFvkgTxwq2M7gBLHAmNVqZtraVyx4AYd-f9reEhDyx7zxtKC4InAvcuUptnD6dqwjziAT8RZ_JAkWVfbVuq
SfgUVeQeldpOXt-6Q2az_VoUzFIpiz1l7M1-hbNrTfBgyNUldUPPUkqi2Bh7UPDXhiFP-3ErCC6gKVvEU73_dhBngKwlrwxa4NeO-yt6_7halv-J__TIIm_w
dV1pyEbtmlU0xtV2uyO_o61StJDO60poiRyfGA37zoVMTkcLy35NJthx18-lltr9yTSJfQU_NAg_bd_VNxN7BhsR0_t5xkHWgpzqvg_oxhTQtPjycR5NLu-W
UsWdoU6RgT43T_ScxbuBad7gswTfNWj2rhtMKz2-kPlNCwUUSmP6aTvUWCUlvoUpU_Ly-z9wgDUp_KycU2HrhthH_STHzooSJYBVNlGWVi1ppVdzNTa_N7eu
Zr0IBAld-oNeazoNuTU3xSC2BpU5z4gpluX52l2sC-dLynqpjCsYUa2bNboZ7WTk2ZkeUprxb2kVKfrDUXVz1koan-97lsByv-0RxAJNt5XkOADuiDICl556
U9F1yZD1xzf9oBhNMZ6VVSDkQCOJuU7rImcrUZrlqKdFFn3Kw_NKoaalFmLoqYl8a9dqR02FEDTdZBdqtjiRXLTFWMtaUgfU3xZq54YlDkgUekxbHykryV99
3ylegNl2u-XUEyQMI3jcvjVwzRUfryFh8TDhg-grrvbL3uuU0P_qd1rwd9xqf0SgFLsr-DspUVLiHRnuvY3GOuhMIdhIavw-LKFlKUl49psIQAMaLwId4v--
9Kc7Jkdfm4bpUzrAi--7NyrZ1YjAmOtruhSwwt-Dn674lgBNkFLwgl5sP-J-kFSNfjJ3kthIc_PyNApNRTxM6-2KNi5P3evULHlXJ7nZqDkAhbfyY5Azc6_w
wY4kN-vnwU2Ge9UtcoJVqX9U30CzUNXtwQM-oe2Uroi4cogeEgYtdXCz3EcrdZNVa9f7pwRKsrZqDhExpdAex5xCoL-z_EFw4UkzxbcENkjPe7guPVzQw_bC
3zO7f3V0LwhNjGo_1lf8WHuPNa-97bgF0-6amysX1mA-ikwPW-UcNizV6UcPXnVpMOtUng3dyw7z2A9Bp3VqnWFhUKSlUkxsCrpLW_CQwoen7rgXdhbwusra
kBdWn-DhVn9D_bbw6uSUy7j7SQhNnmEzw9hJBx4paghN7zYPfeF7KZvFxzTeVlSwyP7c1hq-u4zpuz73WI_MQmbw0GGIzDm7zlcS1I4eNtoR7GLwpaYQNZlJ
WuF7nWSxubdBqdC6pY7G5pXDx-XtN0tGyHs2P3tuUl58gbwy5aHw_jsYSJsqf6Klq7FmoFWozOn0pyK38z-4UYZGSuv1T7nBTczp5e6FRrj0ZnSlvbj7ZnyF
LtOV_DUSSFGsLhmUN9W1NVVy4GHJfyjbFcFMwqFEl7dnS7KQZ7f--F7yYMplwU4sFLpu57zaq8wVRxl0TpRILn1d8yqR6NYguCd3-HgO-Tm9-NplZXpxS5XZ
7CZXFum_qlKINglKVXy58zl00FmUmV6HW8A9qWImZNnQutIRfiQGxS4pX6rED3cER5wUEp5O4Ewp7pyW-Pp6txRcd-p0T6W3PxwSKmuc0djU0Dj2GB3InNZy
VBQ58ONhiKS7jbq80Tm2jNEFdqo4RFjRlo1-vhhEaftlvsVwtOCTeYDedI8SDhKkl0JzkkD7km5RDzk78NZgnmPE0nEIfXI_3QriHB6VT0f08sWEdGmd5pGb
xSAz7Wvs9Gec8kHqKmsjXybErwIKP5AyiMeAp83qgrFxLXIyNKjdytaYoVYDWN-sJyS4000G00H7_HiRHG1td-578wevim40000000000000000000100W
}

