sprite $114 [93x93/16z] {
xPZNWiCe30174as6___UYyCcvjOR7AwNp1Ck6WdSCFnnVFZmuSE73t93vSOVgBGGKox5Hqh9AGQJt-CDgVYSd4nOH-ANkEGOWwaU4b7jtV4xEIpwDT_3eYap
zAjlINaRoGi5ITZzINWF6sen0L7007qs1AGt7lqioZk4VgROGwvwDFfkUpQaDwouX_VS2HRbaDsDAzGzWWWeWA8oodMKMnyM1H6Ikt11yGngneCj3_9K1xaq
eoDcGlRCd73Al_KGuv3tWf4MllLPhmgF82TvHoHLkk0a5qYUhqPSC3CEJ3b8bO71RMOzU4AyI1vytcrZGlR0RoTvckTMH5M5DNfCcFVRNH0pKzPGCnFK2wyH
TnPO2k-fVmVJsyKyWzWEAzYEz4lsad2NwmvdBAQKed56T-JYNeoUU87asZer2o_8Ctdo-Eh8pRhb55FURlhqCZu0iuDgTnWGRwqe7IsjkJ1WTnIYnwi7L7OO
aArjne7LjWbFZeZeQVdbu4_NaStvWN0jbs-bnrQ5NoErHJfZGF0ya-jpp7KGXNEDHy8Xm3mlFc6fEMUyHKwObqNvrempeMrhhm-voqKxTAHLW5o0L03fDtDj
GaSxSYdd9BVc85uTl6v0xWFYpTRbv_vd82Q763SmtoBt764YM9ApouaRied_3hbQHnxoCifJzRefK1voiOw-Sq6HpZ3cO-MgM-etaT8vpjVLMr7wus8HiBis
6Y2rBdx9nihdZmkn-VdnDoyBZ__BnuMjXSN7lxZzw4by9_sOCQpBhJMxtjNbwU9Z8ReZZ6LMOoJKiJD7H9p9qrq-3dcdj556QgqmeBPpbyVL3tJNrQJTb6fh
QLBS-jJ2jdRpk_lDt3RxBPFaC9bnMQbjfnQRpBYCbvYNoOmBDJDbEkFIFtKY-lTCeNjg_OsJVxteU1yq4M6H7cEU_xmVhkXfVZXFAbU58AyhBnvMVd8FD8CN
Q14f72pyvBv8RX2hFEJM1D7rFsI25_acLZ0XLZ23A7Uv6fWm8kx6dE89H9KTaQSSvOdIvGfwN8ticGlCFNIvWTWX1tHe7aV445M9xieLSRVJnJ8gddAnR_8Z
x9BadWHOaKjsZxn3z4SLeg1zl56GepaUGOw8QwouUrJUGtTrKTucxFeIJPWZbkvd1fQmx3ibHLFXZ6Y8gVXEjj-rmjqNp6CC8TuObzDBClaTI_CtbVz4oIcO
yFiHirvpIl56iAVrmuSFlm
}

