sprite $114 [93x93/16z] {
xC610000082W_QaNgG8000000000000000000000000000000000000000000000083PEnlzr5aa3iyNOUJd_L_ljlMyP-tvHumOuYJXsUziqueFCmnWS8SC
-8QOtlyZvJ_ylcp2Fz076UWNziUGtxWimc_yP_OBsef1IYbVrYUdb7fe732BckMS_ITsBdtmcyMSavcia5a7gdPBZ9SjySijiwRMf3hGb2uHy6Iqb06BsYr7
ni5_uf2fme0rvUn-YOd_E1IQOM39BxiW9xfZ89hoPKzuDg4l1few9KlFDxpNK6XqSdYLzpQR9RE5jQ7-_B2bomgSM21RoiqXbNBIB-JjEkcBb5Dxa9upXuAw
HTfCLPYvpqgt_9ZChx-kHEVYjVhIpMJZj62lHMAM4ytg5iTQCfKFbiAMVYNKaK4bPLyYpZJ8IZ6pQbgYq8yVW7ctwufY-Na0wg7Zpki1bqp3BolKmp0Rqo7X
vFNL2zxBAdgkD-HiEJFBxdfYBOa87GisVpnRqiELN-bG_Ypx4UjiUTWkJqm7WVEZ9jB-INxiz6b-xD5TSlQZhhzmzeR2MaJm1rX4PY_o6_VJo_SZhFcOipzf
QfRExH_8t4NMR_Z1Z-95NUT-9Cqsz72ZWeCxGFG7L8fljA3e-lsou7w6FmNtBroAo7ASh8cBWSmLUmmNyTtJ6mlkvyhzqd0_j67Md-jkvM5ZCiCRyjYUFB_8
i_QqOdy5U_2pKikVwIYrPhQPzqDsR0_RWF7dwH3ot2e9Sg_sS8YL3Ffu__8oqO7jrVijxroU9pgDFPBiK7hkMLvcEe6zMljtBC-8JcKFw-syMtbkT7XxIDvf
vSaEO_O9xP7vBlKvp5PFQOyCXu_uP93NQ8ztRG-ZJtUtC9setHxjsXxgoxopBQ6qV2C8bvzYsIDvkiU1oCuApthauNQdFFq_-4rx_AOzljko5GO_tomjlurY
anx8O_a_z0hcfKnlsBDItDwmP-NsznS2pRGTVTX57amLMEyGMivq_Q9CpVQcSlrYQhQdrs-S5YBOJDjFxlG77Kr_GSifrsyADzhZF_Sts_jpVuEylvatxQ3k
n7wcj8Azwmz5thDtvJVjwHlsAEzZkq4SHkZrx76BFObWZptuLZlcYFouMT9W3ohs3h47KvcNxV5y9pNVGU4YbHSf8EzbUomWRt7iqMlsM5I55zd36_yW3CjF
eOClhRWcY_RcMI_s4B3NeL-7WUy7P-fe3sDQciSzsSGUMVZWorWOzxV7Dq_DiSS2z_UmHnwyx1I7xjN17Y8OEVLn3-zdwcvF8FZYZdhIsruTmTYh3t7zxL4E
7NmCeRUnFGm-kXltOCQnjJrr-AH8q6KM_hGzkNdw7NiCeRUbFSenD_hmnU7EWd1tU_Xeo5titLtiQQ_MSF6uamR1KGzNt97bgzGjtCTU2o-lKbSRdkFMBGb2
3rVzMfYktqpKYBnhprh-FkizCZEsX4sSRc3ldU2pKeeHVIJs6dPdAmtdk-0JYeGw3CcDzf366s7SQmNCDzY3_1GySUAA-_PWxFK76pvNjsIEUIABIsNmtXpP
s5wzuJdc7hlu_Feq_nywHUpL6sw1giwmBmjZhuHRZyeSSggk502SSSJ0OQrplAegLgvk58IGSmPPLWeF9E88Oyi-wprWZzNDiH8UB4kT4Uq93PPbAHdvu6t6
62E-S2mUIBoEdc1_OPSCUmBRotSmdO5wmtDaUtTjKEGK-keDJz4AFCvpzdG6eHCWEWEKBP7iOT72mzviy2dK225Bpbbx8_OuMdqkitCO6VPc6nxOtg-Iiohl
LFg4A_Q2hlxmFz1Pu5hBSx0DsWJs7ZD8mUpbqwro3dl3dilUx0qas3XpQRCtx6aiUqOlCEpPZkqDUsbqfhSOPO8rVYHfs4knx0djbn5xWijzPzgZPNs0nFrG
O09x8Ey4gzNBMsnWBrucOAr0XqGhxDdUiCUxiLTlouWzZxJOuc1lZ7kr5el7c1_NNunyK1wBcD-X8ln1VKBnxRbH0CGcB-NwG_dvrurIVB80KH_CNgGqRj_Y
AfJYDZuCVuT6iSVgrqMuSgmoR-mLwrIkYoaJTBHXZpw6OSAiKuh5i3ViMRas0Fw6lT3kqD_fFvUKFsjFo_KDYj3sQ1nx_D4y85unyvUQu8c7lHzIdAJfFfdA
Nymczp3fquQzBzZBh8v9c6PWcUP_tZyNUnRMdcW5NkduFvm8C5LWAwNFwCTQGHuTa9AYdlOXMeKxP4st1Hh47FrPHtceBv2zHuz_QHsXzy2iwRAynwsUFKNh
yB7iwPlouEqNUW41-M_gqoPx_cbx2lQMjKVMdEGLLteHMD9sxXbxbVtiEB6tl3rhrYj5L-a2qY_ufF88Nyn3xqHwH1xAAzDACuuYdQ9FX8BQozkUQOmnKtIr
khLmzCTdzxzWNgxtJ6jMFsNOwuoljyo5uUV3teRoTEr4x84NElTlRrf_VqSAb42dUNJTDxLdQyl36jREzEZwPi_nOfX8dr_BCMDl_m-jEyZheC-7lIuOoEkY
pm9cpltRumBoLaFB9haJD_Z2skCwz2fTuyFUofrSfrAeHxMdptXZNZtHwdZpD79vKz5U2dhSX-Wpf3blEdVEoqnr6feQBFRgomQip-76UNgHtjCHepgjJSNO
EuazU6-xviwkzkB77kbp6aFFgHEj0wksPyuKr1wl6dfSeARekdDOUDNWuygp7o7j4KiT_dJe8TuGV2rDjSjVpd186KDKT85Bfx8sahtjpwTN2BtkmQVdiaST
SGYz_i4txAs4m7ZKYsdrRZBi6KxK--yWsh2t3f3FDidHmzugI86vtax37Et9uUrD40-RnFaKuB2h_TjZnpTqYwxYmzwwbOHGTmIgpiFQ4w_Ou-UyE5Kl3-n-
OmHu-S9f1ljx2_Bg8ClFYMzF6_PDL5R8PLeU95L_Q5pW5hXjyPn1T07HxRb1gzRIvxNLAvxA_91evM6yijT6KQjtbhPcxYpsM5UpLw26XwKjL34LoBOGpDEp
-SbgzfHFQwzIHkY3-fvhaswvBhHtFP6zNfbJ8PDLFcO60cRiGRW-pDHybipfrgjgcK3GxAaV4qX5U_ZxwlRiB5NBHUVR9VhutuNf5Nj5Pz_bKlvHCPNxw-L9
iaKKWhEAF6kd2CMtrt_fIkVUPET_xVsnfjEilV9zpLlijJFieGVxazp-jIS_WfZcxDqksWHoAaLdt-F1Oevx_UsHNyj4OE-saa84zkxCWhtANmovmBZ_s2Do
eJbxD1dDs-Do6py_OM_OGz3UZNbxVll9FTeRzknsOTZ3SI--lLlUj1tP6x47UNEFzeOzlTMRUxCtxDtNcqliZN6FvJbRslFRGlVgzkGvVCozTTtEdjsMoAOV
RhUKQPhuNNkw1DwRFLs4R6RFhtCKVSlUs5jVRa_wsiDLQZ_BxgnR1tlmiPQDxKsjziRUEkxlMLzxk7rhPysSH2l8myzujTjZkUEcqaMa7kodsLktRf_6VTiU
CYtxPCHvFesRg1VmL4y7UnqsPyTp3FZHzFxs34hE1eOzp6IsYRthiBS6-7RsjOT5oziCUrhgpsHD_etYVVxDh2BzUml0i3gmFkRdUNQMDpa902Ezy7XkVTM1
pwaxAp-eE-mPfiuD0htOiDVr983un-qCUvWwT_UdzdT6e8ZM4A75w6RVRM-bPRvGR-e-JdZiUAfu_oC2SITYpLF5UM_sz3bDXwiATKGRZhDhQ6e2UuS-LLpB
DiSbuVd9yKyLZs-F74Q-pgEUqvdjaUXJMj_NNZ24tjdEX5-kJoZ0rp4q7btUqDI8iITRVGUOzV-EBYxzJgME6Nk4zlhNyhwhlu0mnDxXxIdapexHhUFxzm9y
nLfZx_1emyt-xMdNht1ZXu5rVEziWA-d3F35cc6_TtRB50u7Mwt716TZdIBse7pQA7UMQLLv7RwGUDY32EcZRuAexef2vZowFSoTrwb3f-XRR-BNxycPx761
w5ivyWflQIzpL7kYZn6cDXIYRsLvIcrmjRbHxQL78x1e5Mh4GDyAyxptjvzOgqWyU_NwIUl8AeFKzTs1GzQHHw9r85_5iASFxB4-OOKLCqXrBObudOhbfTrP
3nzxt27sGD-xsNEwWhmjOY_C8ZL9uxZ7j9g-eis1X_AwZtjeByYppnrhphe-bvONZl9wwHCAQe-ttIT6VJUSMqfDc3psPTZ3YSEDOaABaGbl3v2kJcCFzLsB
Aor27U-rptoIIyzZ3nVDMYJOt7rC6w81bZbnwkcqAJoLA-8c3rMmc5y16FBEP2zjQGzBVgGKdup1d4rUok9Z0eUzBNUCaDjHdAhJ5rxvEQUjoSCUX5yRHGDi
ovpM7h6LDzmPqxdj6HpHkJ7ihV8io9PeqAEfPw7LqQaX_hfKcZpBpkpLDvlby_cpTCcP2reCvoe6NQOMrOtquQepWglQ7UKX4cEX366VJmHQWVgW2mIMujt-
V8Lmzkffd3UmXx1QpM1nKwPUBDpErC3sjeyznAPI2iJSP0Hy8lRi4jRUzkDU_RrqxzjV5hQOv-rH97lEYxw7YEc8r5iSrfujMBOR37i12BEbDkoDXR8GDTIm
rywm5_-Z9CDU_EC-XhrZF_QCU8T4Fkm57uR7T4ztP6-03wr7NYhx5pe7sF2G3yvYBf3gthhGAH1iE0UqX-CmGnlEecznmpskFPtTdHtsDEBZN_WncxezFQqz
hjYBkFOpOc-suNg9Qy-f6dnC1wRUSBJd6dd7Ya-mgGvK6XvrFot1X6-meAVBMFnfOonCDNn2SS0UpfwCNOQTdHVnxh5fOuV1zZiKZs7lmZlkKSCUHK6MBI0C
v1AnGhYCWU_L99L29WIXmR9peCEG7Wny_AbLClL9wHvMDw7-r1lki2eLE9_Bf_ON_DzZ1QHiSpXBlU4QSsBCivzjaKzjC4nmaexVhj0sy8E6PnZs0gTEsMnp
ZvdkAM0Fhn1r-9nKlU4STLvia1CsjCTUYikhzhoKCcrZ3zyaZxf-vrf983sugIcyrDvzTfssp9mfOEB4bBvnrMBNEn7egdvbmwg5FUoyIYvpTKkVJ-AoCDOe
Lt_9dixPO-dmWTovgRfJC2wRhNNg5zB17dUkhJpmQd3QQWaF4l5QzheDpnXwGi5Gw5exiyUTn-VSeNk7VtMiAWprNDsUhsLFL6Nztkr6uR3rNXx8ujVisSsC
W4zQO0zAnzYX5pduC4_A0dli_yxbk7ohiYNsu0gltBSlAVZcrINriLUFlJjqceH-ONTNQlOKEWglN71UA2GESxvDx1dOMq8bzi1UXvuTE_ZoTfcJIylP_7vR
eDacziI3JXTmd-Y6zOqzo8BQiWSuqJQnbo7q0cALBYP_eHeYmilitTFq5eiAqQknno9C5IgFdeH_r2C_ofrSsMq0MRmeSwvDFVRkBycBozFga9D28XT84TWg
bIUDbqMnjoRrs8ChBsuDOP-E7tpkTY_XdYVsbD-tntYbFVRg8-73enOOvRd5VqO6XxvvUoogmXLxhPcJOObBu4fpx64kbPgzT5yC90gD_TB7rSp9uE6Ts4CH
S4NMZpt65lq5AfR89GlcYKj6VTXJUKLxzL-ZAyKUNfdhfOozMIawlrvkhcopjzaJk89bl3wonxzl4cwCFRI7xOHfUlY7FF05Pq9MYpqiuvVROxZmTkmX3Ez5
UDBl_iRTxIrmfG_-bAmQU_MEx49x85_koRAgFLdWKvVxx1bxvfTxZFQ1N-vnxXjxqc0FN7M8lRHFUSJvjpxhQe-RxFMEFVujpnFj1lqd-bA7p1axzYHVVf5f
HyZb5vxF57lOVIzEkyB-VVbsed6Fq-KtcMbNOEzBM7ksh9H9XDYhBy5ftgSyJ9xrTQ9Rm_SSUyImy9EXuRH359gHbP1bzbfySitd2lOgGyPEgyqdlJ3B0dlI
j5_BS0MxnMk_cAg_kDvZZt3-4Ehp_5oVmDen6gxUH08HWXaFRi8hykGAkdDeyBxauNe3P1AkwHDv_GgBC5xfzMku6dSuLkp-I4CiFuy66yGT59lx7FmGh_J9
dUUO_MTDhCAGR4m7GURTPQOZm7dUNxP3g8FaSeJ0mvdx0KT0St_GiYCE34XEmhHBH1ytokXOI7xKLC_9TYTGeSQ4f7dKq-mHtzLwacMljCNec5Y-LF2ayPCe
oxD6q761V0D9D6bOWs89NZwk8nqQpfSwxXvmBcZ98Li2HiT74huFI4uc4HooICBQ4l5y0dUmA5Z3SqwcGfz1n5BEy4e3J5p3JW0H_oBRjhdKBFiNbuLaeTEX
iCPKnrDA8j8tIzhVDBdG7GpIvy50u7Fo5oab5PMrbAcb14boeJeXOAJGP_X_PFkceVh_8cM_SMd1in0DEC7QHHl-7PJ__Il9VrYwkvulA_qbey7T4aQ-H0ND
OTGDBBx0d9G6bQaWfD4GkEUyO7mTY5YiFDfbqM3C9_hZ8rM-kUpnWLpgVbkbetKOkJJbJRBfZpKJOLgVWQLU-JIbZPBaGCmiV-FVD2_Mv2_i2wPFC91lx4RA
T_XTChp7RdpY-rJ_rnuS4000G300wzzQ2_1jKm0000000000000000000000A
}

