sprite $115 [93x93/16z] {
xTY9Zi8W40RWVovcfkNzdtT3IMogX8fcS_hjUfUVonw2h_ty_Fpy_12hMV68o4D4k1SpOS8tM4laZ1TbV48yk_1YAiBCr32pg1Nto4CKmHgoRDo4fpqpF_9j
9ReS9HZla6DZnPiaCbtwP09C05-UFhyaRGK8xz3C4804O0640A7-aW6XqIUj3B-NNO25S1O059dtwToo3_nkonazFGWt8XrW4JH4T-6CXaI88ilze51FxUx2
kzwAsu69DBnYF8VJ8CUpt8quGOJnYXxX8BmG4KWcPYpBEIP3X95U9bBcewBuN4d3H2Q1Y0YhZZAQFjia4s0HMKllPHYSCPtFm1TeEgFoTJZDTY47Y1kiu8Q0
wMvaQPDm4ZMLMNYaVFPTigrsgHYx3LUCsLxhdk7HgjWKOpxRJJm5O6dusgIpmTIwuEWwEN3l-RnRrE54MNV5gUmrWDEZWCt36GDHj-lxibV7W6QPx_t0Sykj
xemhgLK6BTVqcvs0vV18fxqgdfMweNiKO43cuS0W9_5ggxgsXrEEOmIlhEOduSGTEgux0AYXtvLI102rjplkQ7xWwv-nTEYq1e1ezruJg5waTuXn8EdkmqVz
Tu3Sezqbg6eFZQgZhg-65m3m050Ij6rx-JoSfHk6zntq39yDo_s4zZ4_mrabynpp-OJEUtL-Mym1g8Dp2m90jU85__FtV77tBpM6LTfezu_50nVjLGODtnOF
N1YVO4lT2LUoLrqzvCOHJWrmohfTqtclldwo69_cQAkxNa-eCJpDzV354onbhIdeTAirfYVurG_BSVRtujcUsBHnwnT5LBRQRRPyKNJEDX_mYiMA2G6JS9w5
ExunlH2L_xo4vcyk_WcSyHy_MtePcOT72ZvdMJx_FKO4C1RtmPDc02A25wn01b0LPECVkPH9D_CjUCL0sH_XKWb4er49J9LqdCw5XIFS571kuUV2mgLXYgc-
1J7XS5aIUL0ymWa7Pg1atCzuCbZaQJ7dEg7FYpaaGfefkEEPlBuC1Sqqt2BFr9LmajxX0hoNxWpWNE2JozFdbu34czcz6Uc2z_HbnPIr9T4iIhZ3wcrJ8omW
Yxv8RCA44M8nxniPOPLOdElGnLHL6bMrqb8xDyPdIAp4okhvEZeMp8jxD7vqGvZmxtv-Vlu
}

