sprite $115 [93x93/16z] {
xD750SD00C2mCEm_yF6tp8qqWjtz8m0000000000000000000000000000000000000000000020wQo--mBqGp8cqr9i-ssMQao6x1rRoSUMP4ss_JdMhBqS
98xidO-UeoeIXQjE8QNy-lsVTwTpRz_joS6462IeVFlVdKc4pogWYBe7224kRGWXoFiCL74BDL_QSuj5gChh36xQA3ksPdQ_MPHY1Y7EIs_4y5ZXGDKingLR
vXWDAim0CRel7SAvD41-CGY-78ju4pXGYrurDXvHToIyUXP5U5kTnnluGH-07umgD5kOFPgEVFaw7lu0gO65jme1Rd8zO77UiFIA023x023465-lmLqj0Ytw
Ixan0CtA7geAuAMyEdk4N8NoVeaXVBYuwaif9XS0iUXQZW6GFW3AQdPpW9oRvwDTZ0PeZnkApmjuSxGBJp9ZKEaRXEKnhd9ER7wOAmCELDExMXd6udoUieKY
-eNo9tnTdPrlwXpbH6XSiinp32h7nOAl69o3ddso4W4vEWX-xk4ldZoxuCGDj3axi8VLPPM-VWIv8_INKEshY7m6TPnnn5ilIgZT_wOI1KVi6xt_63u2vO_P
SaHB0t0EvvjgXdNNTWDqHE_wpqoU7y6TO3fI-5Lyf7o4S3akjX0UHLwm1pwooIVRs_HLzki8ez4v_72IlGIUIECRjcS5NOe6zko9FMu30kkpWyhBpi8umHtQ
7kuEA8TVECDyXLT0vEfuzhWD4lpu-k1FCuYUm9woFT5mz9MVPXfm2NlvIpSSEl8yo9NiYSJvmFgSHhoBsHFCXqsUaSxyQlQu4y8nvSr1BcbFutn4VO5-ANS9
UqoOgIEw1yjVG2vhJyBXYcRwO9Fa4glrzUYBHoknG0YgCfscKdPyVO7bFTQdSbXxt0Oc76demxnI7CF_aL-eo27jKHkudPg9FjVZBDF90id9ZuJQfJt-O4Rj
5yX4NpXCtemhhJ8y7WaXtTeJhChZYzGqi_p5GV9cf5QHFKO1ICVs182-Q4_cO_nK8bAABx17T6cFARU7-GYv4-ifWbfrFdiyGcG758VqYQylRG3x0P3JsXFa
CqpiF_ZiONhN7qIEOW_bzhYTgrbfxZ_q87LGwi3UxUK9lGUVpJLBGho6Q6zFwC0MUDxP-uGJKWq5L5hQu_L1-skxFGsgiKr-Ixt_nUteEVHcbVrGCbF17fNf
wcDT_xoQXkLTzMbTU_p1zV6EKsV8xY7hVrJr9o8xs1EfSfhSS5urT9muOwxo0Ab8PNlrGQxbD6_fiZvjsV8OTXu9jSGU_Pazp-W7pOny_TPP96lFzfs7ghne
Jx3V5MLPU-fqXVUNEAsrFMRTNXj0zdXqwG7EwVDA8z3S7Z976h2-rM2T_aGYFDrHXxI4WbrRXZ_FMlWQHv-94_IYjMzKsgBGp946KCCrtqr1-g4e9GpGvS1d
PMSrw6t1pXbXK3R27Esa1jRXPGxlTzk_sv9KxF2SN0Q56mqZ7uo1h-fQNGQbNMNI1_70mzvOyNdf6GsqlsdBsfqdT-0gXgZbAl_HtGHFioEnCRY6F6CqawSS
lOt4eCYZHfmUov7fhBatUwxKXilPKylHxwGpbjiRzhGtUpFPMsk4N04y7l79NgTJJaBbelgGxwsExOde7N8Lz9wLnV61omUZqXaFNACUzhmpUv1oXhtboFP6
dNfiMGrxdzaV6lRimFR6Jrl2qUmDr7ko1p_1JvA6FJuRpN5oDnbMxNd7zc1vSFO29uELENg_ex2jStPvZFPgpsW6J4svHlIfhOC3s5iBlM7FylRqEFQ6FKvM
NTahrAUN6_VGPx5bFOshhO0MyZ1DK_fXcYRhPywvRc_iDYhW_fKZkK7xAdI6OUyNc3nzFIAb2ThXZ-67FKo9rEL83laez_R6kIZOt3ffqc7lHWzP71EvUp40
Xpt8Pr0dToKaTF3hvQlRKugxOfh77z-8Sd5xvAx__1dwkGaiVDGUoDshJ9UElV319Aw-4b9_S9lmezZ-gRkyClmDUogwza-fWQLyDfm0OR2sb4-Jr40Bcijb
wbxjgJr2tiStJ4GqAp3fdYLgtbJfnrvaUooFmGvPCnL54JnLpfxbpMLxdPPQO8_HsjELD67x6YDPrT1ZEhMthDYpNUtna3Uz-VTTtiBEPGy5pTcCqKpb_NNY
r23sE5zrQazs7FUc2cjkpf--qxZ7cIRsRqztasULfXnQLHyAvB6zQztspF9SgvL8fwjjYRPVUKuqMQmtTVNhsiC78Y-XxfhV6zlpwzZZiIhLBjaaD1vkBcEF
vRbMtsDADkpjXkynoG3LFAzYBpQrPzNbyTmbNTBUBBk3L5qU5yxIDEpjFkYbtPOX2GtjuGhsk8jt751JorlNkxMd07JjdxeXR-uvj_2tah922zfw87imgrke
_fqt8RNHDwuDBMqgsukTFBvYfXRLtUB3Xk1ezFds57GPU_3Y3I86MsF3TnzMyLxeCRtR2_lQc_PVKFl6YGlEPm-rx77eJGsMawWRU-YjJCtsNjMtDVI4w3xu
TCtUqgazmHEsJZWXkv4sBjaLZr7ftzwEeCq6EFQQ6LtL7WT5e-_HKzlZ3QBZnuGOnVX5x3NQrbEHHi4tx1sdJtbkQyDUxSG9sHdAqJlRqzFRcwX7MtnNqfwV
2z-_FKwSKylzUmnx5G0l5mvpgGnx4yzPsgJfAzlJ0bwC1fSScBxHbUFu9UOEF4wTIOhGvnpF7go04dtwP2Iob4-gckxp7zsnkU7h22i0VTfRt-g0bO3NrWlh
aSdsG8h8dbSO-0hRsRczI9Ta4Rfb8E8yn_QS5N3iLHZuh8npsiChPR9f9MkoFUJ-ab7iFPlYNjQU5hUgt9xcmuJj8N60_Vpfz7ycoV9IKTNEb3dhprfqTGwe
diWUtHL4iUVoZ9UcBLhMpgFP4yLJH5wsnm6MxkpfJqGcYhqoUrvehxoT_JsQcktLX-rnY3Zkx4q_mRZLthH_jUKozh0soRZPIPFSsnF_zt_Vs_F2UB8TgYt3
tfJfPGZRatJhTxANIhDX0tl3dbWIoTdJ15ctP_u7w8Vj3NkYUNkYicxl1vzQsXlsJ9YyFIcmzvMIDhOtOc-xFUNd0Xx6th07ilTbHx4txDsAdyd_G2l8_ksD
SKy4z-MKQTZRNYdJHh77U3rxU8hguUnP2ThK7XjA6-nLQAVsRWzMnCVifNLx-eez6tlhPVPIJNk-_f5JVNjsDNkyJFETCoVRipVjZRrrJNl47YWPRzhV6tlh
vLlTxzc3WIu9h8HbkJt1SNyH61eyfen2OQEzwIkboVJtYqvT7jfBuvVm5UrDRzehgvJPi5S3xitAzlp9rUB3NirxB-lQynrl8Xhsk3ljBNkfw4qEe5bI7OOz
poyfRh0zJt_u9GdV1_unbzoq854FU_lVZApVbFqVIcNZZzo_5ovaJpBPhaMaOpmpea7gxFysw_xjgJHQCnphSJlZEMMWMUVX7cTtWISyzlMi95pv2O_sb9fz
Ml_9yAdtfwls_sHZpcUfLUXDJPvil9pwgUASEgsxEGlROwuKUmm5NuFGQ_5C-DYXlVflqqZxFdcH4pGky3ODyUqFRD6j7QiD7kBgRxojcy6ntaDKdqGzMnsZ
qAiEPyvhs3FQ4Z_I1NBrs9EqT-xq_RvWsDETNui-KN3l1kOhsUFkzLqpSzBhlNTM6xvsDc7FTzf2Bc8lj7cT1eS7zfFdustvkxyh_pWl3HxsE4AI7kg5tSEU
u2zz-yJq9BiJhcUFVr6Rzf2NEhhRlsKI2EN5Fw1EJqFU1_vL8nyhR1tjr9uisrxw3Db8ggnFwtoWsaFqOFQmXpr-uf5N64ct5rdActimU_O4hTJVhl86Kw9R
6xPXJpXNx9b8fUXBKuN0so9lUtFdguvxh6zxzhJSlPWjnhqExcAWBE3wmcySAmnM57xjFwIykPtQ2soltQfzUzSZtSipQS2mHmk76maRSszxUSEU-1SBG9aw
o_nT_KYNpP0CLpWLI-oW88BWwOjmbMlQ4ofqjXpy68UiezDN3ljOkhgkFL7FkaXfua8gO1D57O-O8_RQPqycVUFs3vw--LfXKcbC7B57avTjf8RkkDJYyca-
_EisU7h3tIHjwAbGrbV95RxLdGanx3K7gRAxOKzj3Vry_am-INrGL9D7d_PcajTEdwYbSdSJf94yriUFkUhmWJls0CW-J4K27R8BQWyOzWh0v6bTOKfUf6xO
GnjxZ0BcdcYWymbG8ThR2vtQGs7mIHji-XUL9i1MqJuU655-CvfY3JahM4EbMtjEzeZ1iBShmrwKGTyFZ62Sbkk3NXyvmCIhs1ls1fXxirU-Fpj0Nzrbmzv6
Ut8qUmCxiBr1xD8UBs2WV_z3he8-QddiR7cSjmSZBkBF21pDdbg6YyXZS31xHbma-DHoFEYjZcx0BBStx9dqGCZPGzRUo9pQeprUCY3RXei6d-Owotgk_O2G
Qw2uHtky1OLJUP11yNvQT_QY78RnCtZE1lAG0SZUSKft0_GtojY6KnerQkl57gM3up2sik5b0zz0lSD1nYk--daCUoERbpDc2FRoYcyCUzfRGk2dbUb_I5kc
QSeSQGGtdEiQtcK5OKQ-NelcZo58e2CgZK2-vUWpHyLiFhVVeFapU9oU23b96tHbWy7xd1_aKqBRdqMGgwJtB-zBqWRBszE5DXZwMpCqjuVqbLp9tjT3U-ff
jmVC8M_F-XZsc9WxCRJ9d4PviiIUtmwWJURayQNNXSoYsKRi_gGvBR5tVsHgE6l1t6jHGprxNT7kSXLKwI7JM-qb-k0wABMS4cUdgJCsc8tJABVLdjxbEvNT
c6d6sMNgH8FPECNU-_RCTjKNbewtGRrHy84wkP8zx3oxcgc3BX1y092nX-Unbzwt1m0xX1wav-2RfHhKezp9g_Oek_gBzb0l6DLxdRFmnMMLHpbzBVQGxX-V
EjrKeSGU9-dQgSawtpTshJlAuRNO4qm-GOIEVCoUEirPEWw-qCmUnzuwRCyVVPNLinUfRtf3vryZdxQBlOdMtUMLRBInXuKc1Lq7dxUpTzENTCCUO9gaYJrr
2hqEUN2IMbQkLXWAxTMat1uCPHLEwFfbtN_mpMmXhuyTTsnlFHYvdKfvaoQS_GQVwvsL0dtKNJtOuzDvRMCFSyUXnwiQhWVXaJsMt9yzFb9kBow_a9w9h6_T
tksmrh77lGWweZNjyLUnFUwI83sZpZcUDvl_QglMjuUL-fhMiyTVnVPeBh2uIgzmab-GqmTojRyzku5AzlX8TjP2yXP8vyILqzKVHAhRKsXEn1Dx2dtB7fyn
jzDc6ahwnXTQDn2LxF5kUxazlHseQey99EzO-XRiP8zTbTlZ8_NjSTfqIETmjbZialQu8sQJGs3BR-PuKNjnNcYnSBpSkSHBselK2OU0pznnENjWUSVL5ovc
Byo7bSV9Ct_wXxN7HxZrFEOTB_fuvSVbgqFRGwOCO0jVkaVNjqHaSYTK3crFzBv-gl7eyZXzh2UGVksXm1uHPfPtI8mQuYOFeSvHFbBW2kIAZx273Lz5W9ey
Hpaejd1Rx6cT7vkEK0Rc8n0wmXzJ_bMCHMumvBWuDySX3w1R_JHtXFvIyP7jNyL7EEu8Lpam6XScGkLiAE92p57bsDYyC1xaL23umhYTuxbufxii-Hc9Z4FE
GCotBeOp2DIGRzqSv2GWBbay1XmyOqPoHwM9qoGNPlPmu26TntHEcgTAdymS0JaOYX2NDJogd0s4ULaN6Equ1c7HvtLtGUMKXEK1yto8PeT8ucYoSbAKyYVD
Gu5U7If0fzyWP_QyhcLcZy7Gt-IIicMJ9L3_yqzc_iwZra-kP6-CGwu1PQ0ruWSpgIfuERUUBrIkWneF_kizSvCepG0GOtHV2faZLAw6BSJZN3h7iFF8WX3Y
_8Vb1IBacY0MHI0l3YC0w1-gF7eV0EAcKt4tbGi3Ig6bpFw7-Csh3t35ZH2_yJyis_1uNNMyYjZE_1SnvF7vBvQty203AZxrppmx_JXdeB0GvzxLHJF86eCG
brufgHyCr4BqUUuhLqBA6G0MuiSpgSTeXgtc1WZXG-92g69je6OnUeDiEi-pHzzXZsC0m4A8iKv2vG9Ei02qy3RG46A5-McC8GRv70Fx9aHtZnxTVSxZ7l_z
H_CN0lwlFJWW0026003swnzQ0H1WsndH-Ey6000000000000000000000000I
}

