sprite $115 [96x96/16z] {
xPc9beCg38R_B114tlzvRo7Ema55dRbxltEwAVb90gOsnT_7cpTlthnvGymYweW84_sMhWPBQTaXMGp2U0wffMzoBwoHklbI53n1Dv5aGOLf34mqVinlWdjG
TDVcyRC7cHGt2DKYC2uYiOuNN8JIfp_CWDG70GAGF_h31125bqt49VWrD01WyOTyYP7qXrtVfxLbiOlU9yPjVK2lJM2RF8YlwiCDrEC-mGTLGn4uKtr2GuGH
gks4DFZ0v_gziKtTJzY1CUWpOK0yW8dx9CAxStpgWp308cv-1ZK7Y70RjmfT-2FYvn_3oqBdXS40Ue7RkDMo24wmcZzvGRVbHNm152VuwQUuW-VwWXyHpwjS
spvS8To2tCONy11gooyLFf8Xx24DlpvFjnSEePZNyc9DYaFaiRwjLJldzXAF5H9ci_FE0aWk9IitYLZVyvX-vaa6jkn9ezFNgevFT2rhDm5BXNq59vVlI9Nl
mwRi4-pkmDlwj5RvdbpoVNs_EiJ19sdKgX74hZXKPbTez1i71zZWKdWlPojz3N5S_sxri9AmWmSmhM1p_LnaVz4pHknCtq_A1Xmkgoy2W5WKMaeX05IFEx8n
q_VWY9YOY3e_Sow0vQA8UJkr5eP3x2OxAPWdJrlwHGl0L1IMKppEMtoeZweF58L4A_eJVTdOrNTbStr6WxhyXzdwaeCDARdJDzlyzsL6Rs7tzwUl8ySMFaFD
vF7-3AF_ICNGCHucnrCygm_Yq6ubsAqQVB7-X2NkLmBREvWmCDKtx22bw5YKLhfTdxNfSwCJwoSOZn1NQAOltxuVkPVhKaIfzCMJfU7VZnFz4PyWHzh4R7Nl
9tSWjyvABgNaP9RQ6tvoV-BHZVbtD9UDfADkOyp0kFedzuUa6gCATc2tyHroJAhwZ_4T_ZVUdtjraXUu2tb-R0dJwVa5Rk9Mde3dwNDc6sHw0Jn7PlOrFX8X
Z30WAq4pG4U_t-CiVgi3nlGJm4MWXM4haEeSw25Flqu3PFGm0SBWeit_c5rV6E2nkGFC0-WHRW_A_ALZH_sPY0cyR3_XFIdygTyWVrIw_fxtbsn9btgJ0gAX
__QzFqCqzlS8iLhEiHh1W_vUTBjB4nW3u4veqj-JrCbFsxUHy0tg7iDXiDre4RipYrqTJzg6q_tkkGMPMB547ycuIJMi98i7_VaGqpOaC9x0mRh_5yp6FnYI
AUC7a8HeBjVZWH5-1s8HrL1HLH4c_DsyUVFc3m
}

