sprite $124 [96x96/16z] {
xPY9ZhCy40HhkZs3_Vul_8k8oD-HNNR1_vtIwCfHMEq1RFDNyURDcpTlthXTn5-ozt6PBiw8FlfsaJvwS4AU_EPaRCa9sqWkasCxzpT-GRzN7FKBxND_DBtm
XuzYhs3MIxzQy04kt_Uxp0kKcVcvFxxetqtY5x9sben_f_6RnSvF_7pTdxRZ9FzhpFnV8-xx4Hzpve-8EFDpqIzdFSZcMEqFv-wr93khKalzhcew0dfUJUly
AWVXbhMJ5YXBo_m4QhlOajooqk2L-RlI0OG2KAiKI_q6FVDneCobVb0-yyagB-z_LGf24eINzUT4oCzyYBRExvXJB8LcxoFVzxj40AGvE2OtSEckFyeuEGWv
07HyatdNxmgLQGAqFHPf6O1DIrIwwSz69Yv1ZjuKgj43N5APz3s_Ib6c6hHHF8ZUutdXblVyBbpX2kWR1z4BNE725RVyBVVAX1pJb2E8aXvrov_jKOPjYmfN
eYI6eHobkEltNcNefGeegc0ab5dh9uEAoWr6c-DVb4zrCdAhKA7XcV-Y-MrZcgep-sTPVtOEF7Bs_xBxIwF7jCpxTytp0L0VrLhsXwJQVFuiUBw9dUnZZCq0
GakUdr760iByZBpY-O_hqCrthjCymxlj9vWBY6QxPUNozIqjurW0fOMysgyi2nweLIxs2rmp7tF9hu_yKIcGColJ0gTF_D_Rtoah7J0t6_4zVqXg7_bjKCvy
gedGj_ojTZxoLnh2pXqhm9dVyZipf_zbF8BPGDLYPVx8DVEPS_4jlvgc_tVabZlDMhl_FMVw_-xpiHoTo_JpmSKOlIxInmZEyBXED-T4oukquEz7vZTY0pA1
BS05b5_-zPp-Oeuy0hQ268RiGC_NVptbLG-qh_frpUy_sHy5j0PKW198tVEVSz7VnrRNsBuqj3QkKt2EyYhch-FDcpT_
}

