sprite $124 [93x93/16z] {
xC610000082W_QaNgG8000000000000000000000000000000000000000000000cBrpKMyKnuAmL3ebvFT_uTrCamlkWWZi29EkVoypIUp47xzBd2C9F8mS
90skQAxUPinqBOEvDZlxIfiYNGLQbmXWlaRm9gjIj2l43oloJAkldpnRMgTUUDWqZQyjhrhH5WtfXGaBsgQzSlJQVPjZscq1BnAzDY7dR6BXh-NNZPuQuirq
YV2XINacsWMwXdg10S97fgFNMoRFj9S_DBcj5SOcNdxenEehD7cwaBsSbfZVOSzrIxkoFP_uBcBFs1vAAKZlPFprLVxwK6JnHF5hIjyJRUznUPy7Co--IlZx
gv8xdfXxdlWqR6_nLLb-bRyAAdZqYUN9zcolx9QGIxSzw2S-3TlBUoMaVdlvtxJ7MWEdsRj-zWehIpe7rF-84VRGaxsBsGFh6u5JvB7-0LVFNZx77kiVufnX
SuOlcRtqwjb3VGTdsgj7xFcy5_MTSivPR-RgvxryihsucZrdpzaRVzvpzbnpZizUgQkutpjgJqCylxdx2Ni-xsdAqzk3YsKlNMJarE399pbdRwGzFZjwFk-D
j8S1zbnpNi5UkLxsahFdyzv9zY8zaxXKzgu_SgRd4kFiENj4UZ8eiO1ZxUsEKBgEFSOI_BPvJYqXpnAKh-DFB5vZU9p-JRNvuTsu-jTuZU5nW8B5tlUxhyI6
TlL477cYi_SukVkhb8z-9Nvu-UmTtzTYNZfxgJoqfypsmCNnEobyn15xjfT2H6-uleCxuMqlyKHvSwcMZjgplGG4VENpO7m5cEtPdktPdktPdktPdkq1AF_1
_uZo1e0NjsTxG92LLKAou3NjsHuAQm_HeT3s1fjZxOU33ThUEc0z0EEOGDiRhqvJS9uzsqEmFWHPai3sJeqTonlut6KK6mR7sxEzGjaJH07MsuaWEtQ_sjxu
xe32ctOuo9_jQK8S_gVz0jiREcOoSAn3rFviRs2j4i3nuNTG1sXxC_VkdlfMcFi7sniHF9QjLORuyjy2zBMCXEtb4UKAeRUvaQnrJpTH-DpusPu6mjtEgMeg
wQL-eTZU3m-SB49TxKKiyttnJjlx8KAxG_3H5GPGfDhsdWj5E8Br0EIAFpfxFmOAdhX2f8PFsDuW2gKyHXHyfKImOm15H23PtX2ACX9btyON2bssDtvvZmpq
RJfR4gFjsHx8EtN0qUKbnb1xjXSFtaqspblVipsAqkEnWYT6sRCzTcuC0u2DduQSyhQzSVLAQ6k5ImhmRU5JXjgpFOOKrp6zAVsDjEUHC-vjbE3k7TJWM7ks
1rKdWbhTjrrX6MpFEmA3HLGWlR2e-349R6_Sb5a_WVjV41XZp_QUlqAaiRtnLpFCBGBmqVGnIAhy2MplH7THb1FTIp1Ej6Txt9kcGb6_26nlSF3OPmB1RuJR
tX0e9bBs2sGvmPxjuLahHEL4UxQdquFo3hxB7qwmPtlQ7KgGTObOPG1FjUTTIMA922HxPpZBoVPypuYoRxQJHSIFrx7dErrXwK_BixqNdUrSwiBf_PxjbReB
3b5cUpWwKnrHn3RutVlGO7k72R8Z9kpPm1Brm0mdISBs7jbp-_XifvxXPD_RWhPt27Hjb2qYK7q2YQxtHTXUB_ilX-IkMWIbNn-ED_Es5xKhUnGgUdkBwB97
sziDEgsWOyoK5Kn_h65xU-7z-Ws0f8Zz3LpPiWVeiTlszaSlljhK0GDmy9mA_HD2VSAXxUqlMV13dpLOLaPRYhzQQNk7nhQo_9gZ5Wt5o-Z6zkeV-CWPAF_X
YBrQZeVFzkAkskE-IrmpWjCqtTveqrI9l7V4FjppsHuuopfqcGzgQxSbhJNcr0CV3P_jbPNeOR6eBidHRfes8QrHIj7bqlxmsHwtQuUoceRCsPrcYlMe4xfL
OUUORNlwP0CXKwTXuKxdBw--MNWNzBktZktjZ9xkcS6LAXxJhGEk_hqYmmVk6Jfj3rKUJOgwOZjuRVe_VtrtmeezOklDGzlhecXRsDo5cUlIKOsvrSiPTrvR
RAzcw7SFONizSBDcfvOtRLQNETeNWmtRqtBwBnRRwm2KMSCo9roLjzBPHLNwvAckB6L6VzLfU_6kHmK1s_9cTngqXJurTcwLCRIz3fRHWuvUMP4tvRG1cz0d
mgTbmlRs3foXewUbj9hJ9l6fByl0Rxs6iBrlASj3jSmQLVqNifVJvEa-fRA9Z6D3f-s5gju9CNizavkGjywxliQD6O8YesXxtx9Crr9NgEXLfMETNDMfJxzD
Y5qdFjk3h3YLoncqZkJ9h4uRNURAGDg5xKKI6VYiFyL8MDCMqZTKtI9yzUxBi3tAmxO-uuYkLa4t3fEgMzGG0EwmPtk4SYcZ9_ktliApnNgVgGPmmlPMsIuN
z7GncXWtkqzzDOjYLxdSPS_snFWbc-Pw87hwQVgFzHMTjYSRBHM78iR0AUqZt_uGgx4lQjwwf0vihwmFPeGuAaWxgSAwg6yVjsTxomvQISXwB-xtXpF_RQ-8
SNIHH8tjwSAlOhNfcXQDUgxJkyTSsnjVon9CqvJlwvPOVUSiPyUw6pxRqyUip2h5wGiVHXg-T7JBLCu_NSwNSO0zszFJLVXKD1jhUFz-cwRsjPMeongJSzKf
LZTixoWR4nvYeZy-xSrXQfXLJSWfJvyl1crf3srXRw78zeu1sJ1yPw_EhKFzz8EFnTXu7rMRj8TdsxEzM7nLLktLJtlrrY8lRCpsylp85ikV2dkoNJzgp_Pq
zhI12McsjxIRPutCBsBFsTC6-DN6F3hMUToSCa-nv-o9Kw8q44iRUNhVV5Hl3VTkHvttd3rjJsTlAG_piQlfzUpvlAVjpV8-nysML-sTtk-vvhotDoUFxu-Q
8kBj6pMojZT-hiNPYwMzc6syoyDd23-8ktuldstFtNg-pzuihyEUs5BpGsiCdYdJizHjOMyUB1lpJF0_teHMPh70DsnzpsiCHQunBEr5UtFwXocjrJHlSFpQ
kktfiYNU_V3sIHFsvFeUkDwintvxNftbTwkpN0oTcAQQvt_veAQPUF_fLxydxYdppWWiQv6SPlAN_toGjtOpwRsZVDYUxOKuBoqjj8ClDdvWBxNjKHQTwoU-
5caNqqrsUxf5UFm2Fk_6rIS-DBshR9iGEx2vy4Kv1ZnkpplXvIL4SUGw1gYxQ_dwlMSLdI4lgbD_jc7VLbnTi-ZGuvdsV0MO2j-KzuwRjwpk2Bf--NLDdVZQ
sUwhBtFhlVnIFs6XYtZ6FIDi3nlTEzC3rwsZYNj-WB8-ylrQzhBCLyYZYhHSevtXBdbS_zGJodxXIVPynmyjv5Ppnx0fnarKLRDKg2JQNd-_hXilGbo7tbEw
X7xaYVS8z9sk4iMzDmLvMjpeglV-dFJzEO_s3AYgvQj5TN3RySjiMZAgZXwUVMzSt-6HkeIeNynKY1U0QBSLUPHPgo6-t8dlhegbhj3XMox8JdKfDySyPgfv
6TRDc-_2zuJVnSfxNtHcCdqpbSWfvvJZRSHiDp6soe4IMYPjhu-YquPlFaiOqwqBPdsUtPPPRA-JkmDs5uPOgm1pxN3NeDyieUfFVmxHyp_8XYHr56BwpbrL
VuvVedOaUhQdwnPTPm9fZPZQbZia2I0-0anD3zZUyV15-fwCUjDCaPD2rv_FQnVy2Mxx4e3MsZ9qJSHEGVs7QxAz7Jpw2PGPP9rcAe5zGtOHD_gtlSCV6XmB
cJ_tkREKuoPXUxkeCtUVRwX0IKyZQdtauzPjJnSgA0mfhx1MFizV2GOEVz2qxUqiL0uktvG8z9OmnVQEXeyTss3swuiEAo5UWUqT3v-sjzzVwTfcTBHaiRt-
lK3yr4VqjmNzzYBPtk6navqZh5QjSxV77fFj7IAq3wrZPhiMmUB1x1Yx2Tix20fwBN_20DRKSLzGKGgIxVqmXVMEA39qGju0R6yR1EjVC6R4ppeQVDiR1rZt
CD2TxMbAmJ5_aSPYUpfjB6Byt8O5QJYsfzj1xXf06GjrXIHEi6TxNAaTGLO9IQXM0-VOiptjBw6K8FdLMnHWfS_WU7ks5_Mx6KvW_g-YS4s-xOqDt_u05VtK
vsDxnsSuDIZiwFriRsoBpYw184TFkjYU1ZjdBmltFDxsnizmHe5I0l5G7JpR6-bFjdOHKV27YBb_69ixszEW555zTZ0wTxQdotr2ZP_zn01tjjUzNGax_36G
1antsfuWrXgrmZvtIC8xCT2UxUa9pk2cE0RMYfxur-m1EC4Ujij6e8Gq5qN4wzCs_orxVmQSyVPIT9Jz0C2P0B3nc_wjx8ahkiVQIuNFQDiWDlB-A_PAdOdn
zXBYuSqE88MyVyKUwpjZxStWiNcJ8lOf_KFsK4-qf_VN5k3OCxbKRtj32DKGu1jpCNnJjUrfm3rR_h3II2I1xVsCBKACWahAnoA3s0mlSlUxxM59ESCULOLH
M8yIItU8YDzdJn-YyVQmCi69Woj4SlRX5zgBMb_9NWt8OgGVnjhkplBhxA6-b3rzmaAtG0BhOqlyEdjbk3qDHOEzznmOqDNGxxN7i-rfEx8p04gGL3jTIi6t
VGTXUuCwF1AR9NA9A7FRq5kFbUJpti3g5yzyN_9Nzdjy2NkwEc7WIMy48lrAU-3PzlIhEIuGXHJztw-qby3NiQTV3l7O1jxutVESesVA-ltf--neWCB1rx9x
bhf_oO0HG7SheSTCspk_as71d_z4tKIejhqXb61z0AeXq_jQne77LeW4jZUMmW7ghcvF5tr5sHiD4EIm0VFwzb9Pz4ads-jVvMF0TxgQqyUIphIdKxWghXmG
vsk8nZElC4Jvxxy0TdYpFMDxOx4zsxCzsxCzsxCzspFrzawxd3qptTwfBsylqWAJNzvURhTtfcJMtjdrvTzVDrZOWWiScdhxOChf4yFR1osdrmHDZWychd1W
Shlfz3bvd_0QBxDLP1lCEQR5KSdfrSCtqwQf_kjCxRQ0bvWFqfWhDAKQqoAzChbPqJgDwRN9TYIuJ1k5PakQLjFhWycY9BpQMfQvuAePxheSCp6dwm1EjndJ
QkHqCNAmEeAL8rDdZ37666ECoRd_c_c1vpyV4zCqrPoMv3fD4z8TdAQ9wGwiFZ-I6RA2KULkoQpM-KFjYftKcd93CdWx53N_x0HulbEgvl2RkkQZteIe_BEh
RwYtMvjmeQsBBNvqvqLMMzceb3Qf5FBv8ux8DNP6j3pENdsElVgpcmrQlj36qxYSFVxm4U65BdIYitUtL5qlRC_Pct8QXhDdUyvUjJrdp_PytdFsF78wUoDn
zcpFDUS8d3rdpsiCjdTuVI_th-zXJCrfUz7cnHOX2kgmrIH4YUUB1JXdx-cmYSEGcpZuUMhYWiVQn4fRJEggPDjxFWXnGKv6PFLGY9SOo7tVzCXfdBtns9xn
oEdi-GQ--t3ssl_QkmiR1s0W089dwqtz5_nXJiI1asPAC8lM9RY9H_LK4TZsHvkPUYrjlKBBsxbYrapnyrkCL1yFtA96s7pgZX-_-PWbJ9ydoyS3dOmQQPGs
rmKpMMYkj34F61aZWUM0o08000000000000000000000000s
}

