sprite $124 [93x93/16z] {
xTY7hgJC4iDnsrKszFk_y1NDnj6oQ82zNvg_27tIJwZEP5peqwTFdpvzgcLSQn7Ewd6zmabZHBoIbh6Us3LMN8nZy6sStpV-lBsq3k4uwXSu2zetVTzgRh_0
HHoKtCKPunUfgf_0KrN2IvdTnxUCbwgxVuVhPJl4kridCx_GySndr5qSulKx4Szmu1AkThRSnMTnzbH5gRQbdiFPSSq52G3gM4_XPNqVIxe0EdfkvkMuH5Bb
f0dYCToR1qeYW78Ap-55yDjO19GVnC5zB9XZiO0dyRO0LPK8TkfH71kPs8a5yHcStY75DLTo6hFoNTo61825hya4K61q3rV4D8Yj_IQEFJVQzt0R7IW4j8vr
MSO80CtlCRg3Cs8AQQ368W3qM02auRdTm2lxHd0pPpMo_y0ety7Rs-O6yltx7WGZXSeTt0qN8c0OGXLGm6WWDKV6EtXX9pZAWQnQWIM06u_X6aB0q0jslF3a
bIDOkhmAQrx6SdVcQq181A5HOAXjU-RMqj__Sbc1plwpExZ2VTj8OPPvuOKKN7TmP4SQu39ILA-Z0HiLAho5zrIekLw_lMaJcViFN8nW0Y01K2BsP2YwXwED
MQUmnw_Vid4J1_5LJqkgJeGPSHlVSu7b9741zV2pVopiiH8-YVFhwzng9qsyZvC7U6qUDzXk0NA_ZJi7EEIqi4SvvbkufCe1tWMK4tVt78k0UWVFrW5UiG1M
jzsb_Jllu6tx20STVn-BEdb_veSum7PYpwd4LsxdqiGFeggxkyGxRnKlzEVnCNZwMP9nAURykZokr_XZ-jh0UTILY6kH0FIok5AjmcjU0Gu1MG1jYoLuJUTZ
GORnMYPUlyTxB7y_tClNiMHRy55ynfV55TnZgKjb16TfNAvmMYthfPR6ittwzEb_
}

