sprite $125 [93x93/16z] {
xC610000082W_QaNgG80000000000000000000000000000000000000000006RlNDJSr94WJ5zAdtZ_5zwTE3bOJ24BUqOncQezDpv3OFrJhUwMmF-Kp2n-
lDpCheSkijHQrn-l-d-Ll1P0Qxb9rI_3pikwbrGkuZy85LEDAy2hAvU4zuTNrhw4J_24RtxObFoTuONuz5NjmcMUL2vZlPgv_7H5rhMHNMFKm-qwfIYNC9-j
TzfgKoclCFBX8BcIuWAtzRefHQnHVVkQpm_3WsHlF_35xWebteDwUtg-j9BYtUb12UVGi7APu229djderiAtpkygUbyaStVlRMrVTRFrye6lI_GiFkHyo--t
5eyFMUV0TbUtxe7FI_HQ96xRrlP56zloXUtgtLtvWIzBz8BHQxUS8ea1UlGSySNqH2-UfUTJwOcUl2VlYPwy9thodhmdUlAUwCbxegTwRxxaFT7Jk2VlYPwy
9thodkZ9U_AUwAdU4prvJ_GqxibxeYVlYPwyf_MSImF1EiiodUvgFd3Wwn8zyr_m6fZMBBJsTijE7iXtTHEzB-BdxPOjctfRjjywVQ3eIQ8dUg8dUg8dUjUN
w8cUw8cUw8cUw8cUw8cUtyikGa_qt1q0IlC_0EdkxqjFzCmZIr_8S7itUgBdaIXZ0jBzRUY9dWFbf13-1lH4pwCy9wJzLNgYvudoWf3-j-Y9Ng2yAY3-0ZtH
imJ7aPc-gmxCtJC1JjjjBZtHy-IfY9jrW9jxObe05Jqk8mZ62KGInzeSUg9dMLhXTFhe0Upfc-Zzqbns6VvSfR7ZXsZuYTw4F3E_SF24VoSzqNCCf_jsf-ET
0Yq_4xr9sGhFKzmZ4arr000PuVxOW0ZH-ox50vju0jtI7E6FxWc8tZS9f48ZMKXVwTODoFwzzEGz-4lzpiyMj3j-ANhV8wFkiCGNp334zzDJpWcaqQXtNkbq
bZ14xzjamuDT_bR7cN1h-H7hYTxaQOO8ajD4eMfXHPWgXYco88DPzgPxd5OKlX29tkIfMOJR0FFFwIby6ZtHuxbAs2kJ53QFdkXPlZgxkdTWJACdUlY2cHqB
p0cVejSgHhvrlrFdpzcKa-c97dnmGJmYZ5YqYPynavxe8UmpEFIVOkZ4JyoW9tfEl3Aw81vxknhcqbFM4i2UWcSPLlYE-bHwglVChPC_dftZio15d-YzuID4
V0c4vTGLWQBN3va0aF_z3-3yc4HladZCHEuNn9kPUoPEyXEz-QtgKxCIyBz5J_GCBGg4dLv1JGuHlHdovzgTtczmYjuSvTCClC6NVucUwFNP7I-2Z-zfS8gU
Xm_Ju-pCFH98e1GWaH7XlRWx-ZeO4xt7StV0cMRrZelpyWwVSXhBK_GI3-EpwEM9M9OeW9teTYBisGQdFUOiUdwgOMnkPvzaoB1F1M2C6nsYzxY2WprnACgG
06ljvsS6MHUznud8gztEllBfe51WelUe_lQlUMKI4fq1y9mUNPheOL-0kRizyyuan3qUkj1bY8Bxjbi_GHMzsCVD7BhPqM91-iWi87BiReAJgnEzOmpjzuMp
YpjVxt2oy_TZf-Z5BgVmeI_PSMP5kvTxnL0E1NfzhKGFBIt34BqWgyLw2a9xi4f0SvJeCLl4kN76no3pPzJZr3ZiXw5Jz7PjAniTPlBqDsf9w34LRhuYUdl5
xflA_IWJ4HnH0EdF59RShxwTnuZv6kYYnmSLBuLaVFcrpv3Xe5U7U33oYLv_r0Er8lnBVmlyC0x3-2n4q6WkUabY5DdsIHFskSCLRIXDqMEJ2ycjPvYmX8Z6
od8JsezXeaTo5cAzvxfKcQY_bUddBmJ6OoM90Q9NRihHwi5wFZRKTQSQDlWM7_01ECccwB6c64zXsj7ei4Xmr9MfzfupIMoVWjj-bmkB7gdK1wg7RlVQQrqF
LT4xFOosCmraauHEqSisJqyUD_qmSx2oFb1Qn_byTKQMctQRehSlzaYcmCt0wMLT7we6EJq_Nz1FNVGEqdGUHvEmPVG8EwP2wBKdv9lPbdmkUYqkxzxikMso
PgEty6gjY5z2hRkFd9p_iTjWBCgBdf6HXQGmBF_aKRCYxWcPPwqzV8Ok81fO8NetHVjbSID4jsx7FHnc2ylxFUoeHgTLGhPcRqYB7XWkUEj4xytwPLiMSDqN
WjwTuJ1-HIpEYruB96d-dhsr9R6TksS9BonujdaccuOrK2kA7iiAQAJqzckrWuJ5bwwI1CysppHImXZDgbBqFWzx3kh4paIHrV-GB4mykIczce-7WzBkAdga
qK9hF-_CRPV6JqGSDNfNaG-lIVHON4gQSNRMbO0uRmYVKVEnii2f5Ltq7fWjcIDWX0Q1nsKyTdextl90sazRHCzmpD9OcoD95jbN_E6TdNcEPBnoRqpH2xPo
99kjNIRep4bn_b9hv-dOsF7Ymw3e9QiGaXGJz9u7Jo7xQip7iqvd0nz4hz-Y3ffZjdiI4FMStIdo9YLoD8Jeh8CleiS7Eh9bv9O7I__7pUSiXBVzbOQUYnul
65WBsC626RFUaolq2klvT79VqUFJG-ZH8qCYfJ2kmW9kB-ba8I54pnicdVI03NjvwepaG2FqxBZIT7uVYHxR2b90mpiMies6txtRolxeKusV3L8MftjNANf1
fz8wz6pPr3A8-jz_ejvdC-iVWUUgBJthq2FU4xr-PooEaXPhuXysaBLPWyJevJ4zUMzSF1yWnGIbjo6miZRqQaP-GFHRULT_AJzzdqwcgexxuo5whOBHyp5w
iVdBco1gjm0Rjm_1Ieg67a6ao3cY7AB7-sJOuk47lAZxplD6RncdbrySEUKzNcHXyvlL-WjXxh-qtEYnwmNndkWDAq_ISqvlSRlHsr-JtNOhjP99NKAlF-uf
ShQAhw2t9J6vcyWhznbe3KvlllVaFKwldNMlTgFtUpLy8VJ-RiMWSO_Jy_edAR4CTqURf1H2RtwrhfoJq_Ewdt2F1XQPe6NUAr_cFTLxd5uXzAn-MkhYbT3p
ppEDHXQIvhFLkhndH_Jya9xVnhnZUaRe3SmG4PRo7fzxuMc4iJvdIw-5PxOvrVUB8-neTZOrEpkW69qXCaAlKdgtYocuoM8jOMPevk2njKZfbTWk2eWUbJsc
btn-RwlaoewUhNVosFux-94agUqjsEZJ4psGhKx1jtReLGy2pqdAMOvJJgDJ_YPwZTj6rhN4iYbQ29dXj_-8xNyVc_L3qLbIqJ0PNh3HazQKsQCrPKO2u938
SRn483VEA3sjvsHf2pkhFxSeAJxVHT6vZdpvAHIjfGwwAlgKo0D_971kCU2L9y3q74Ep9rsEUy88V0Ks-4CeB8M1w94ogmcFpPOVFaFan4QFvBKfrPcz-BiE
24lH8xbvOLcyWOryvsDdxLZFs5j7m0F2cFJiB7PVCNlR1rvvVCyBoKj8gEpF3-cvzHWej8AUs8Slb4tjqLotUt-9tl4BMkY7B7JQUWfVMQdrUisKP0q5qMFH
qKdex9kFTCAELIXhjBZ0NstL6VRqhgJEwrlwBsp1EZhsMQ6aizoKN_s6HxsdZ9eF98byN3XOfPozSEjn9nBxFvJU4KX-PeESlAOTiWD_GQvX0qBoJ-EVckZH
zKRTBo-e-QmyVCMZeL9uMzo4qHia-EOYUYqW3XDqi_HUIftMVrjyuR-oHuEpyVEdwEqhFhhfXRv3i8jdhGZtNmpDFJVRiTpcuASxZASm885JxuHdRkj5CZBh
qwh-LaEErHNy3VH9herroaNF7umqX6Rmzu_rnRFIO3-Y0-CLPhCfUYJhP4DDyxlrcTv9AdkgoNz8FvtadwHwy6PJz7hXoKWUCLYDSuKDfBzir4iIr4MFXquZ
1XYCLrxh-8z8ZV_ACusZeaVoS1AlSE9Bis00A_g-uw-STvx253jFJxzz6IT-4F-U8DBjp6N0I759xYBHux4oQGJpvPGYCpEMCo9d9LTbejSg--Ppb08Amf9c
eEUrdIVt5s6TNtmMFPxSjK7Ap8w-xbBIbY-ItSxJhHvSzFO2lyynE5AT3QhenM7U9V13wucU7umnCJ1GdRMV9SVGhnwosHOzQZwsChr_r4s8ONQDpubeKynf
fIvwt7n1wV6ZpeJF7Dt_e7emqMC2gn9WZqUmJGzBSh_V7IFNuwIGRoHwF2l88Jivofq0xw5hzes1QKVVLmykUapFP-HPMi6Di0ZizegpryQj9tgdvXAu_LeX
mztjG-xkcIWxfJzr1XCzeXTpyYXC-13_n5yPaqMlt-qyBKkKOI6Na-f61T4x_rIgxP8Q7-M7i2U7P9ZeTMGOlyFnsKLE-FN7E_Sn84vYWkYH00ZOqbC_XGzq
26ANPpg6iyW0a8leFP3vS8BAEvmUZ220yDsEUIeJ8Rk9thEoNkLcvX6HluDhX9iHbp-R8udUwyh2-OqVJUc9tXn5fxyosksSJq_qU8Tpj7lIe2DPY-XDKfPM
j98ZgSfCvudUE0paOGbdxWbI_KsGw8rtg85qtnNbaS1GjrFqvYfGHZIRdUXnUMOwuVTMx4IFAyaqWP_arz8tzpdqHC_8NDkvAI84AHnz5ZtHuqiudMGcRDAT
fZsmgVH4ho1j_w47UgPpEomvGlHcN20UTKhS4q11-VDNCyF0xWJHctU1ERI4q--qK3N5koBdRxrRWvEBB-uKlVaDJlZJVm19O4LlUeCptSQdxmUwsw8tjy49
X2zS_R8Y2JlHcnC-MsNOqApiX7H5z5fPj72C5tVvUndyykT_pMBuALD4eiTZ9MB_Rey3uKw5YCHCzs-Z9tgWeSwpFAdylCOGzctqH8-dY1Q9Sb98fqailfkU
w1K4AmB65Mv7gpjTzBv7sQ_F1m4YhVCdYzw4sGNERt4Fe9F7P6Cwblc8tgGbB41moExHrWV8p72tWGV_GkFUDmfVknhJawIXeZV1VY-Ns-Oev7qJelUTSfhy
dqUNO1CLeZU_mPd-P8jxzjowwF45P2IVf38FT9vb5xq9iZWg2OWBwO9upaxq_leA-FJOCVHmp5vLBNfzaVxco_rEqPidYrVuyUKKeZSLO7bIr7MYDrkUPqCe
EYieH6-wp2E7oVc8wqHlFiBoG6V0YTvykNjc9XfbPlWfSg9tVOcU97gY9tgY9tgY9tgY9tgY9tgvNM08rzNenNQ1lhIIyaBqoj9AgeJUkmQ7sffFilU_izTD
4B0Zw-6DOxj6FfwEltz6PokzI0dhfcfl71ysbHi_ASgwNY6XYxLHHKfbRMLlIy_AsfU4AtGKkAHgLsWfS4b-XToOIufb4JuDUdFA1kbg7OnW_AGQooLaALPx
rRnMRqYwSDS-IgaVaahnvOAo3qdBD4cI94cI94cI59KiD_HIaqtr5tfyiEuG5cbE3nniLh7kYLGs9rFOhl5I4zb-cdzGQuaNPd-TS5eBuRHMOvF_EwEouxcO
wsk97xYcFv-VVegzTOYZLWOQjEtu_Ag5_0ah__dAivX0htuhFITTw9-oAhnUtdluSGzkE5dcSLNlaVyhelUstXEzaFVUGFAUwCbxeYVlQTmJFNbFzEGzqPFt
DEw9dhntSMdS4pqmGzbwTdOslc9sLkFUQHKshnlrnPKHzPcL4VBUUGNO3wq3RAaHOEpuOCTZEIlHkuP4J_GqxecUl2TweYTwrvN6lUgsNFX_LdyUlMMzKxso
rf_uBc2z--_AYd-GNbb-ZAfUGVP6qaiyw_A3L0JlmhBwRy7pvMUfQj2xi0p_3BzYoy-Jvx_0hoAMdofBN5h_Qm-E2G000106sJ-rBNO1om00000000000000
00000000000000S
}

