sprite $125 [93x93/16z] {
xPS7plCu34Ida1Ff_WVUOWl9zdo_eErvS2yl4KaRDFwxVFZmuSE77dEB4U8TZxdDU6VtdCKjF6RUo3E3JJp7swWK5Wl-_hHOQ4DkNHD_FVtxv1_vuc2rR710
pX_vC-IgpasRP-NkT4aavUgqpydLAGAW909GfNLANaNGFmqBA-UgXPsK292kf0ZYb5nf0PGitXdmmOGAy2iiW4_AuHKMS6NpWDp4JHT1LzMTJU76s9ShUcrt
qjr92yGDutrv5zouS8hFeiT55PnjkKB6C06Gm48508OYnBloBbHVZijC9xraH8nkL6_A6LsAkXKrvtYCEGoW6WuKAjoJEq-3WCpBe-iAndXEM_BgDNK3zJpH
qtYTwDgJjz56p0WOULqp08KEtAZUayU862c4fqXOrpI5-x02Pqz-cHawG4q-YdfK2vm6ZiaRw04NrEe0iqx8SSaLe2PSUaXwWDFWCiEzdT0LTaBJ96qLKPDB
M_i9xLfJV9N8WYFht9hswtmzIj1ySBa7eP0H8qHxyil0os30SxIedaD02htU0DYJlrui101c_aWJWA1e_SIcl1eAMG2WosbX8QC2HRjoncZZecFSgEiriCQk
7DLuKadPhauJ2qNxSXYlCT3TIPjGuOO-qbfK-XMMzCakbm8hwQhgf8MJyaeHbAkxJC1dsxbEYMkx4kEOlFtiYUwS0l8f-UeEPLTPl0ToBg6LPrWeTre7Omww
ith5TF7yfwBy8o8M_woFtCp-y-GrXx057pDumvZxw0j_O9CXl8URO0y2WB0sk7RsqJ2UZ0Pg0fW5r00mZIUFu1lfcT-HzrWR2yxvpvRxTyAoAN-ROkpB7_eQ
zUropQyJV2j-Z2yI_EluyE73zm
}

