sprite $125 [446x446/16z] {
xDU7QYin48PHG313zlqVEAGA4I7axedFeRfiOR_xtoJ7lm8000000000000000000000000000000000000000000BnzGRgx4J3b-YDBjwFqVvgKZaUMReTw
yZrhFFN4aqyyzOuNLocVT1DPvC-6hRlKhqAzenPFHhojUbdi7nYxzKpFmr5FlNhK4wzJBrexkcmjZwwr6BuwUTKF7CywlihnGFMk8jk7Nkj33AzQV-WVBZgm
VwZUDRGlgrVHSttOE31slderwhNzLt7gWR4ui4ezzPfwwasezo6lKo_LiptrRC_sRC_srBCzzMpFzcpFzjIpFVLiRsHxwjcUUhPdUxPdU-hPddgsPtksPtlg
sPxjnMf2kVhgx5Kk3ho4UZaE8MQlSlhLZGDZunhgNMRSmV1WCpvU3Qdt3Zo60tDne7geTo_geLuDwgcdddhggOTw1Qcdddeno1hrr8k5PwsdNkpBfwgdNiQf
r7jdxqwKf4M188x7QSRq-x_ltcxqJ3d_8H6fFRBsD5fRWf-5GFCfwlNJzVj5psyl-zlGwFbspIaOFT-kdozwVZWeQX2C7eGfeP_05Rqpkkpqeu4a2T6Zrq3d
9G_uHMy_tiiC-LyJlVknyfObu8lU3Zpvnkodw6t3CqSIE_ClUbpLWi_71IMNxxvUSay0vn9krelUxJapuelUateox5o_w3tCPz0PW3vUz7m-6NSxoozwpvTF
etaddJ7g9xa3lkZvmNRc4G0MlRrscYJVgXSzfkDeu8iUTrOsJ517RzjSjP-0YjuUFVVdWp70xNhHGv8IlFDclUZT_OsXJozwWaHo_AAtitoqOjCNtAiNFPKP
oiO9pkZv0NQ-dthwdD7JaZz2f8wvbkWHpToo-UZj2XaBuYM7Btezqvt2dmRt-KMFOmPYcr_qE6PdcINaYzwMO026bQ4NFHD5hXx8ZUopg63HC-hJNvbRqiy-
M_H6-f6QWPRva0z7Rs3NwFcDcJzXXYH-mQ9N1MOMT_f-Hg97pnX_c-fkQFbr5RrvF3-YzvYUthOxdpBtjb_qpElxfFGJpzgBlxdoANh8u7G90SNO4mzmsixe
oMch71217-a1N_IWtVJq1iuYHyylKFIyqOCz2Z3q2b_q5b_fygjqLa_HcxdhyIpnH8M2tba6B5Fq-3glsyGtVJeU9SXi3w9tO_JWdyyT9KHlBlNMwlbN4OxO
eyTuBNgruokd7D5JgKIlE5mYVvGGlOlGfHQdua19W11cet6K43qZzUZZSRip-FIBaozwNA5G2lJ3OOAYjmNlO3lmmzCVlCbwqHFfLKosgm5BStNLRdFXeZTM
UxKJx-1HyGu4qbZoHS_O13pRJsu1VBteqUy3I8Hya7nEloLwAflOZhw5-DvM0J7vP62U4JtkmX0UqLplXCd7RMNqpZ1QIj035vTFzIm2pEZXTM_WbJQJ_SQJ
Btgp3ITyE5CrnCTUlbxq3a_FAgPWUSnGAaQFaqt76IQUNqvJBtf6igbOJf-t99_HOjUjwF7GcFiiujDoIH_IYvuuBpcJE3J0nmsfhnSzuLtFAIhhZNTYeeUT
SoFrNhVv8B_qb5xq_7CAzSpROFJg53KrMC0m6Dnq-kFrwB5NTIuAHiZijlXwqUCwy_NWm9jwqRFghARGkVdv4tqP8f2UeDFfwqKFcj5YS6wMmbmN3VIIUwF1
NfPU-T-5Uhgh5ps-xHN8CrZllR0zkHUzhngdwDjdr-NjrujUdJrvwwwSbfrwqUCkv-N9tsXrVhH0JxVrebVkTQM5L4dCnjoB7W_tYXxqEVlradkiLrjL7ZAe
NI-vL_3-XNh9lVg3-pzJBtggF6T93BrZKvypUZpFMV5gQbfwVkv5JpEpr1Nlh_-HfNTqwUKt1dry6p1W03r5xp84Uh35Uj_ZgHpPjYeflwsxUfgzxSthPLMI
njQrwBhb_7jJCDE2UYBPwDtxUPRFgR5bBLgy4ZvwMhsUanhEFhsinfLpJf6UinMz_N-EGSNy_SkZvyIzQZFE2iTOe_D1lEYz33rDuhbNJVJyHqOOV6v1uHaV
dbxqDAGd_m_FpkD5psywXQb89_RhaKyZc3MB7dYvJ_pG99x3TQpKoxEI1AU6MjJDHqmgUkDZ1fLDU4oPzw2hOr2F6ixeoKa-v-KBlDS1LmYK9thmCWQiI-Rx
mF9LFBn0jA3XpBDn-ThdPuVh0tYF-wVtzQ87V2TX-O3qHZ0LlQyXz87kFF1HoBXs14FrwFclJNlRCFoWU4Rg6JtEw0ag58h0CV0M8ZXtz4h8U1aAlQfKbjqP
UfNKuWjfNY_l0ECmwA0SUNEf5S3bLjeStd2N9Ner5lKLUFImJ8_B4JsZdou9xu8pD-1IgkZTl-5SC0cgqmyjlUlbVUkdMC5xy3tiWZ94pqk-mUFadqtpHOeU
CnXwXf_nrPh0YzvXwz6kVCYG7cPvzAwvBBrQispYwuaFYjuPdXxxyTvpeuSQqHEC4lWmC67fyQwDZkWPoUSTLqFwH5oCpTCSqTl0vuGs52rwHgFhn6INAdfE
7R6Pct-J2fh5YnxlxEIVRnSzdqyEjTz-VluEgs3He_1IhrQf8GSaKAxeKSYSxwhrFsedUuBj5RrLGJUox-XaZE3yYDxyA04UiwENuE06lUWPCvpMR6VqDlBv
3iPHqTli9yn06UBHsyl78iPiP_Is-Z4XxnIzpNgICKBlfeiUBmZxf-D5ZvTmthHxb39wFC7f0yAF5T7RCySoxmS_2KUlRO9J1js6wSxekKiuvOm21Hz7htE2
4-1sJtT6Znl8TLyIlPOf5dbqO1UzVUdd2-2XqMkSu9naruxAYTx8_AQa2mr9EWpowAsEUnES3NRHenLyMeht16NqU4xh5bsz4gBtJC32J2_u8eZUxWdETNRH
spF64-8o71mQlOV2K80G7nMzRNn77GyodJ5N7Rtc1TJzyvtHOpyMtBOqDtgx9fdvQwBNuAS-kkZvVgw0VsZqzepzcA5_HNpqpC6TFeKnZeXUZvyVFbxq-lsu
jnEzBi7-h8jUurFcehS_6kYYrsBumeXUQp2SdtFHwpUq3evUV-Zjxr_RjGlS1e8OWA9Yotl_-vOXu4ZBCFDUsUNyE3oefnu0000000uN0000001eySKB002H
7yhh9b4Dwo-jXsEHEVFxljNJ4SCefkLmlE9uqwRbXrR-g8VbTCnmwHyqT2JRgLTyP-Fop-NhvP_e9TxQzUAmUf7_-gkN3UnUN_LYzNgXtXXsJpsxfvxTSxwd
djrJp-xPFVMSxwbdzzfazwx9xZdVMxzUpBgNn-uTzSY8UFsbuwatMRaaKVwmSXWZ7i0qadhNebweTn5sJptrr5FF-PxTQuXwwicdddhYgIUVUEg9jxvGxzBw
ZIUVUFg9fryCkm000000000000000000000000000Du1
}

