sprite $134 [93x93/16z] {
xPY9ZiCc54Nl0W_U__zm6oCBEIaua-vjpkm372uOOmlyJ_ZovSkNBtAfqLf_a7dyQ56BHVmUwDfwRkXHX4zGFRr7q69BeYJPvJ6Mp44h-25kPp9Y1UKwkWZ-
HDsFHCGL0Y1VH_WZVMHc9Iw8W0b8WFWwp6wy0zjp41gmfjm4_3BKYZVecSR94BxAQOpVJ-8jUyiKLd9n9KSTcRQKgnjcALDUFQUbwY97PB-Vb8g1B194BNEr
L8-V0146ITcwDDrGPlVoe7WklseCI1KVo9o3nfOsUwU7HFvj979KcwCsDZ2JEB4m2qYTS8xaMgjcO8Ep0_HeG1EtoAEgFLgl6NrJ6bRTsMS0INFS2oBBDTQj
MzUbfktrlEfithXtpIUpQzb3UZSpEjr-SCWBren98yaNmGiy4ymMDUkD_DMXRUp9VYqoyyn1O6eiuW8rOsCsADcmHDcFh0-kAG__D5_Kiu4tykLTC8GJRS8j
sFGyjm0II_Road6aFC3RwE2yPYlgdPpSof79ZRpUlSlq85RivR6JHxPYrqn_AYy0w0CzbtcnWNWmTwwT71nS3LFPEYvmi9NlDvxMSABrnFJqHkv5ScPne0RH
W1whvFToUS2BN0ueM1iG3PZ8WvryForCeu6rj2wqzicqn5AEhAY880FeTItNdLm7l1Prd9Gd0sVrlRokrZapC536SfrdwgFRlsJZ-Dc91P_lBUxPe_NHnqw-
tt9N3uGIhLNX1H_SRRabsxn0V_H-xaF-ESf-L_WvlfVB3_0-sZxzz-yjzyptbhXxJDspNyhxlM4JV9yyRkJ6MES_ikl-BNUMRjbd-_6aSNxZ-GtSNBBDBKf9
bnwZ02Kge0Y24G9g69WSJPI9DQFuLLuVyW3yaEiXPqHvaPTixywQYG5DW1Q0ySq0PBnKR5cneyxEJK2uWPnoPWetyo9CkG5gAHPWJNbamvx8VfNBW0GGEB-8
qQqlScKQUvWPh_AXuFNNgvmz0tVuF4_Ykt9Xk3jnIydvc2J0hPmOUBflxK-xWFWiXu498wVx1lNCNeWBceDuBedC3BnD6KUYmXNY6JgEgiA2jJwprULHDbrY
L0hXfx2s7FJp7DgIFSwW-raMneVe2BUWjshYTqAvr8XsdFwtNubQYub_Dr--VFa5
}

