sprite $134 [446x446/16z] {
xC6n00000C2WV_x04wa20000000000000000000000000000000000000000002OlJlHMHtPWG0ioHAI_VxlUzUSkn1AD9wYSILLskOaPB3z_GrX_oIvbXA8
mQGe3IP5QJ93scs0eU5CQ3GQe-KiQ3aBscsTq7O6jDpthiA0lntYRmLj9_LagUqqQpETPf6c4opMUA9bf-dyXpSnLsZzjduhBRiNjnlnScFOhvUjTlyAs2ZG
b11UqHD7NcujTWJuL1h4Ul4dizhpkdioYMKz7cQYN1QFkzGQUgTBRMhJTcUMZ_NeDwK2V1Cw0YnDlIZxVT0EGUjRUW2JsR7n8WXwU8lvU7q0X8bwkEzBw5KD
rCCN8NQkRvSjgL_hDKZb-FZrnm0zKCRb-K3rkdgnSm3wUAfw-doeS7qz_XJqyVJrzFbmqJVLgolerNtqzFa81HCH7adKq-Vhu-tNoyS_anoz0NoAUeT2G-_n
xpJqyb07UknvwEDXlUWYF8uq5Ysunb_oAU1XX6phTGyCWXwJJm2FWy0_i1y1FNQTbzLBIJrinD3xze6umeZsMFJnZgpfrVdI3GI2NXmXyCdZuGbL_R_UiV5q
iPq7nYdrDlFrigs7ft6QvMhu1mQEyebBlyA8m1ca5szImdpzMuTucv_h1Oprrl8ZlLXEOphwU1MVvzjwyRMQhFUVyFK2Xw-NGdWumShdUd_z6gtt9qp9Y2Uz
15xjW6SQDFdwfRqOG0mEgFskUdW4a-70qXFcQnJsTWRZtFfBJr-lFuG1QhYavf1aRpZxK_YDMd_fwUlnnx2T3PVGrqlD6quyXrPuOhVLIuPU52SDAouUpdmz
mYIc9nXwELul_Z_oVBZYnQudwYKeAavvqwmo7cvQHm_ZOHunlVXKBwwcX_dqRpUxYqzVBmJmhDVW4y7JryEDl9-9BXvkMbEl5l3E5zJ4mrsNabul6dhHALD8
Zp4O2RqIryCLwVFrLvxrGXuFHqzFV_NXylZ3qjSBWPLdFHc-k8CUSKO2U9fwk1xgbARYMK-5Zr-KZbwypW0-EXxkLbKleiCtp2_wU4Vmk2Rh1Kpfy3NgFkNw
UfXF14zVhz7E9Bv-8TR3HmhWzVIqJZdNEIRmDMfUwLP5hwg1DsJv4Me-Kefw-ySdSEtgUlq1wjhXWGdegVd5Syfwb3aAu5aFZrB9pdeLfyZOMGzFLE8lnNeL
v-ooivw4Nxn8MM_3T0Ni5FKYS1W3dcGNEEfwfFdG1Fd_qn3NmtYqiGSRC9XuEDRhlkI4iwKmwz7lInbLgUgjryBJw_zH3AYfhgT7EDV0OHx5lqaGqEES5-04
ELyhg4f5Rsj6sU5O3uLCPpqnGVcHwPT2eBDU_J1ZvApNJv_DUbD2XBEUW_NaAd5Kz29mIZIDDYNruaqkXOTZFJKyVRs82_FrsyH3ivxrh6Szt-yTAGMzEiVd
dB9w0-eQKvtr-dH71FIibpYpzQoNRpAEptz506-cd_LmDG9yraF52FXP3vJIvxFUF3oyQvIUzTxoVEndlMrFKw_GCFZQFU9Inkh5Ghw0jtOnDXwEfbxmzVeg
_B7rUxGUhc8Vd_Nevm0R-Qot_GHkafxFMd09VBvcYvfwjNVfyHQhppdtby0vX1_hSIMcwLcFGiwFzVWEi_IiHqBdntfy1UjPpthK6yxJIxBF5mRirlkztjD_
FPLr-jSaFUlbIxriw5blo_FK9poibr_GYwM8wiLQ67hF6fdvSZM-XkVZwUl5Z_IEZD4BwxrCBkWTU8Fqh7SM-4FuSkdbR3th_VatF1ijwtrKnYYz-fcU7p4q
zGwsXfuVCVpYYR8yxwvyLURmH-lMgtmLwqqfuurUAUfPBz-klHoZPxryriCf9JthdLxVqz6ptlnNPwsNIA_Uw8qSczzJ1aeIqBCU25NFhwtBlnltdg-jy_ce
1_aJO35CZu_dpyuI-OJrh9VRyVp9v-ryELFFUad0u_DTzfkkWbq40O_DLn9w2bNaY8AjXr6curcF_orprXlj9_3zdAu3L9C3yQo7-J8NTe5ORu0VJ85Opz_e
RxrMk7RM2vnDVdoxHf_-xKkEtrQx8zRZ-4dySgb_DPWWnzCBwz4gsuyN_hNypR5UtKElRgNdtriN-J6oA-FrsrJ-AJd7UjQpdlLkm6SznthMivvF5QndFUif
FjbIrqk0oEe5ZBvVlzMyW5xSHoyazU8-Ud41lRIUzGR4UhxVkuAUpparzQe8UF9y9QjNvLZFUjQpdlMiPpthMSzw_hYnzQndlLdLnAlKPTDugaNm1RwBse6e
wEMTzG96KY-iPxs9iPxrQlxzdlNgMdfrpOZSS6A-6p_UmztAwfKZeMS-7EjPptg-cx6UzOoN6YKvril7aUKTSMnFS0JU4TRZuns1EtBjYCVQ3klHdcE91nhj
qmvm13WW07U33tKjgnUd45RUqnfx80nqHA8TyU3eeQQjTuIu0t0_aeON8QaNFBr0etq02yeElbuEryklwEK5zQO_Yl7QivxOsXExuSHLlSLR5-sTdAoVS_RF
MaujQ2szVbd0zArUVhoZ6ZlMij22b5voz31VGDUb8n8QmUl0YKzwI76zVkU5HfxmnWxjoEKTwps4zBFvtzUBH8E5E-0wGaRnyHbBM4yarzV3bLalhwyNCPwB
eoVBX_N6hqPGS8GS7bylHkdXag-jbvVI0rP8Jn2lwbjw3KqkbwnUdu-cjsqruWBvUdKJlVY57hRgwwMINbglCPnVPfCUXHFNqzIJnCCbqlMm9tUftLIlfFLY
crwLC1zVx_XtPmjDJshbzSlawm7EXItOmNgvLoyQTs4ylSPKLFduClqjR3qrF5nfMay0hr6hzNJuhgydWDVWkxbUokcjyrrUJyWEyrrVhp4ADJvzFLYEDbv_
zLL9wrL1EqsyoaRXOdemVJnzlk5wrS1hw6dprLYzKiBh9mdbZz7ZT2_E9wit04-KxuTwrSDBSJpSHVRugdwXTsmaTgtFryr-FNxF-dv3zF0Msu5sZWnusoM-
coFqAed7Rmdp5Llls5R6szmLxtRITgSa2bclMde3EXJbIofVaU_b-EtP3sTDZvnijAR8jxDFg2VGbFqsV0Gt9Un4-prBsOxKCuvK3_fu_DRJzTFZ0IIjSdq-
eLdqwpLWfWiLy1is6KA11jmx9q99zji_CK8b5cnbnBLRK2sM-tjxT40000G00EZ_Qk0107MXofr1SmgxuZ2dK9p4tZRCEJoa3MKQZrdZkp80000000000000
0000000000000202
}

