sprite $134 [446x446/16z] {
xC610000082W_QaNgG80000000000000000000000000000000000000000006Rl3FSKLs4uclm94Dx_XU_exDurlz5Od6XJvSmtkwujfma0XKwnO8kS0Lie
2mk1GAHzqrKjuunQUlj610BGgrcWVg4Z2grVqFDOC4FEGQRZQMXlhOeWBhqkHEftKXmluazw5G7zYfKWTUnBhy8qmu8XjJKTMT1p8Dwrk60vPycH3zNUgj0D
5gXzf4TR9Sk2qRgEew2zWkdCGfnScHNLLfbegGiGfz_qAb8l_a0dfDe__IP2uKSBv8VLQV-YjTegJZoMh058RQss_eMEX_ZK7ChIzP6sUnC0J4oHC050RQqz
Ca0Z7-UkJsR69iBq6Y1rChDg_QomsvmWMwl0JaC6hVNUnpQQy6gdcF4DCDFUC51RtzOAvVTtjq5Tgw1irBeXcNQyTyhKkuDHOChAEPVwLz3UrrzLVmWAV91X
8VSoXDuH6GuD1xuFtpz_edkZXWSTt_kG_8bRxKnzmkmdIi6LX5T0mK3wJNzCRqCRrr6XU52-mBKFomjpg0gz1pVkq2SbJ2vdc0pb35xPVwrCnuUhFhTgO5jA
k6QFhzbZZXixUjVmqwVSbzOBJzYpNtpkk6rxlw4LrHfTonMUjsV-MG2e-cwTXojLGWF7rtAOi6S_UV98aifRJGF9hsCDJxF7lux5-ZxPapLy7enDYGVRGq0m
yiziqvWE23Ik2slL8DQU_OH-2TeO5iKR36ig1zLoyVRi5-DlMpwulFcaoIW5lByzp1lbfiVM9xy-_t9cTtim7pvy-JXovDM00Qzzx3tQiJXmzE7HJa-KXFWl
JbFreFgWpiph-zhpisUdOy3EQR-tFVycFk1iddRw97kMxbJ-IQbEH-73x77BFkRff_jA-zf3cBs0wDE3jLWQxMglj2zuJtjMNpzKfTSunXvAmGFsIZlpYBrI
IemzRWTQhIA_kzMS42hp4jetcBVNJi2nzsWouiDq5fHYxA6TuTVPA-t7_HBK46X7QM-g1DahZqfeSLyCB9Iq86uMdQ-L9HtIdjN7b9KUc2EksiFr2V72FxJG
lI-Mnxve0S2Jgm3g4PeikdaE3s3daMXRbcIAqZmhuN-HjtwHtI_QFGisnoNq0C6ditcp_0Dyup5RQu-OcIpCh_qYCufXCdVM_ACiRMFTPW78OijoalWlCgou
xPLY_k3hisU8SWq0pBdiCJ6CE0DFtjcL4eBfxC350ym9x36Zt67-rauUUZHXpmVWdUoLWhA9wI6NUjJGivGPmC-qPv9acG7J0y1AwQWFf0QKUS3Cpx37p6K6
e4mz0CgcGPuCLdSatK-Tp00c9GBW27juuAUPBqx-WTcNdh6xC5yhs-J339HPy3zCvxyVzfZ-mDz_-9yoYMaDOt8G3PgttT9iw4scJgStd0JmhRpnIBEkvasS
88UjHJ2HJ8FnUvzkwFb8secY-k2PtMktCVDE4k4tZxXCsoDpXsUYJpIe9lBFBkaKp1CvVuAQjTLfkWi1mUU58l0KPt2YBIJq24bRdNWufSCf1W-E40b7MNZe
sUT6-AY9q-ACDqsfP4naHiTOUEZbJvtTIvpnmUV3Dw19ucyvqOojJlpchCn4IohYqxrchFZghNue6oQoK6hO3pqst1hJG49x2cSK6XDtScRyRC75mbSxx2eP
gpr7tjtBvRV8czxy7pJJO9cVpZTCXLdBxv0tuJuvaR3YWwdsN7l7pvryvs9ugptErsZ1NEQqdlFhiwSwdJbj2o7VgY_sBWGJDtHMZ9DDgPDlp3CWNQEbaOLn
0JaWRyjb_Znn0PE1yytnHSnRbKFemwzpHBxH5ZDwzwxwR58Cg6LwkYQdHBJbtbQUjJSe1HBJZa9sVOX83vBO7iUKphlAi_QOCj0YxDaE1h-dF3j99Caw33sk
XFBAGzIeekJixiL7NtvvovxLTtnv-ITexQn7R3bbWIDFgcUrftB3XG7aKjBfO-UKvg-s7SKUb-jirLSe0vYMPq5gUtBJteFh5P6Xyfi_6tRMrYQT8xAdmo7s
28coPzagZpRkIe2qzcZENdvzR2I4s9FyzlphuSbIsmkUkuksPKxaUgoi6NiRz65sEuczv3rwpfRRCtmrUsVzyGVIiNVuOQCy_sgPZcAlFg_qU0TtCNVFXzgp
cGZx94q_Sn__sGX-tht4DW1s2ZmyhPtG4pyN4L-CV51tbfhK7bCyvTNfa-D-STaZlDGVEptJU7jCUoF6th7ziVjJyGM6z4-rn0S4-2K_K-WvS4vxZPu677_P
VsBP8qQnuBd_FHDzcBs-VSeBlyXhyT61CkrkwbApBaJnXmwut0G10H8JW8o8smBEfNhPQc-SEwauS519WsFL5GI4h-KOzcJQNao2UbGWuaxBlzHbpozquA6W
Yyl4U1jxy-aafkWtAcG0nGdXQ7jmblcdNlu5xue2_4tkhicCk6RKuvSgAUtnvXtVA00K5y0I_Ag7-KlDR--rC12zNtWyovu3igjRzdmOZve3xxriH_8Cb34P
KYTHC6TubaHIBzxBPD3FbijU0joNS02Ek6Kl4G5zb6LlaNdnC-ko5p8bcghrUtoMFHG7fdU1YmEEOG-ElBVMnyK51uszuWDw3r1yZXLxovw5lTTNPDamOgkz
5NkIn9u_JyoVKU_Hx4sAVFQK9lKnlGsOop2IqLuk6FKFmfnCzhBdWTfrNA2zLL0ALkpveAcEdwXAmjYJPUyIxkCcsfWIa6VRY9RBdZGT7bfvsNEs-zYLgkCU
MbFQM_RWkdEVlrdsaWMUzbRb_DVxCAXaixViDIEeWIvWQUhhM_Qo3Dbfh_G3Dg5PoRBi9P6dJPpKcgtKMc9xA7VW-8wBR7CihvfXGDxjak3UpLpkykBjXw3H
-b3kSWHxF35p4XnyihqpnorusKNvP7i8xUV9JAxlhxB7nxI7rsJEFfSC-wP0NR77BmazqScQh4NcJfu8lVpsB7Z1OXwTBWWDQAvFNcD-U_jGvyi1ckESbptM
1te0TOU-yh8N9gB_KOwzxIa-r9xrG5E8JZZFlybZVdj-5LOVazu_sbxTUyU8zk2z8oPnVOYzT9iLFfm1BsDssUix5OCD8O3f6nQf8g0pvgWvSrtszeiziMcx
gtOwmKtrVA3J2NFKV7FiPs_PgvS_pltaw-PhiQi9DUxtIc_Pu_kGmrJj9Vel5RAENclLYvfDr2RA7b7nyNsEM--XRE3tzXJ_ddjGEWFyxK-qIrlwuzJbwNlS
yK5Z3sKB2B4dOsYlttvCUcn_ywPsSxIECneXp-UWiLUsyUk-kZ8HDQtqmvuEbRzvizgZq6NFnDvkzkWB1b6pDgIFqVzgxDIYxPLjy5jbpdXx5ubKBm-f_ikR
GXfjZzywzcZoreotr-LlvwxHXBtGr8d3ZhKmxc7SHTix-UFpvyeXzkQl3wktViyUMtj_uQPZzFDPLdgAlJNE6T7Vi_Ri-PqyQU-jduxsJd-evhpN355MUp8k
kJXanbhMxEnUC-lDshF72VhDMRII_QhiPc_PanlsUXCmI_l-0D_e60hGDwocz9Qz_NvVGTQU3ZrXdpKx7SqnGrINlJDs0OFQ6I8hpzfh-qzihIS2koa4gVNR
5chjNzG_xinHapWhnRFinJzTv7zlsTi3w6CPKEylrbps-0xqQzf3GLGrhh_0FiUr5p0p6_nKj8rOvNrNWAtLbpg-2Lw5ylwhB-sMy3kjMw_pGtLYllAvAv_P
xFYnpxhrFbiGekQKFzSUUVRYCwSV_trMD--ruqStzZvxjvtgd8AJBbHUyzxK0-zq1O_eRR-qqrtGm-UJuR7sATlUTkgy_P_INYnx5lddHCYZwivBZfSztqfp
i-PrUSjUpx8zvwXESyN8os9lxUXVzS9DnGzrqZI5l6NFh_jEg3RvPmZITOmyyg3hRHhtjuJNLcirdpevVht9Pb_GZAcyBsJ0ikTcp_ctCQpOI_ys55lFhDWJ
l_iBXsVvwpVLDU4dwN1WF_RolZMOYmk_jFxJYdrUF8lCzfoaXDtU6YnDJumJ-aMlJ4-3Yyy3BqvRR-m6f9u0aE2DtSdVjwv7Vbl-Ubj-GEOy9dnOUwJUwba4
o3kwFj24lVGlH5fmFwwz1PlQPX-MlMLlsLkJwylUgtQDM22FFLds7Y-oWGFRM_OeWcLlsHCw6CiUZVzvBtlB7gDS1Q0tmhzKzgRtCjlZW27guyyIuRQzbjaU
t2dBjw8ukFRoJX6L4yiU9xRN9kojs3C3PPh9Nb_rtZMGQNl7cIoEcz31cRtK_FQK71OfxOcpNL9sbZqiUzdcr9Qz_DixBdlBtjmYx4NBP8_wiXSqE9NVtiB9
LH_pJE2ojxhhorwTiRUGSHHxx0tRViZqEfmj1rBRutUV7R9icsEGNFRavlBP1DD36LRnfOuzB7l-51_VQkHnVdihzfoXbdn3PQlUiy2nbxgxphW6qvkoQMwz
PxRdi-20plgojvPUxj2AMailroAm75k8OjbR2uX-2ROl0blKG7jh2T-QJnj7QdIk1lek7L2q4mNR3vJl0qnauJi7G4-3pPt-ELs6qlvGoC3DF_3J1YOEHCDE
BPFlONY-84BUpw9jimVG_l53Tum-_iVjHWieUQCJOQFJQ1UmiMfaJ1uepe6WkGPa7zbWlPxC4JUvq2ufjmx01D85sF0Dc0DnKmsu_aXIJzYGKdVA1E7sC7sW
RBE7k4bQvpvFjoncJtjjofxlEyuUNsqXI3vxzgGGRy-NrFQAFJVZNA_sa77Wl7aNGa-EFKoarAVPWrFPzupsMA-dJWvRh5vcso3s03i7ebijzgh1pbsUhxyk
axSffdiCPVx0T8y1KzV0-P-ZZZyjbFA8lYtTU7k0PW-KoMlWsPjySCwLz7swVgSvVRYHL0l77PYz1anNC4c7pWUUOuyODyg9RnKWSEj0cJWGPq-oJiQ87to-
lPp4srFd5i_IPz1bxtuPSTOvur7VsXuxzcQBAEDmIv-qvxI_qy56rPGzrcnRUFldDcyFoOEHomb-o5uT9d6cJPrzpfvJ5dbhkVapxcaJf-to3VcTFHjyp4ox
mHnbJqRgJQNK15-KFTuX66qYvnXxcgYpvzzSAc7szbpn1yVLhBqwCdNs_CJUe-pn_lOA1zXZavcIBx0ODSWUhfGE2l0iMtYIlMeIKpxi_QK8jST4zYCyAzJm
57kuB9hywsD6ZxNd-epEa_7sr3J8Ss9FCZPp-lOujxqwREZb3px5asFFVWI-CMdlViAli6Vpfb1QsgM-vzhpvlTmunDskY9XzloKrFAlolwclYXpukTmwOsE
1vnFdcUlsOoKc3gillZOos_FBvBKT7kZBNioBb3AZQZHz_6P4wOyX99JhRuFZpqhhr9wT6pLXtUtP-MDJldX7_fyUpXovhHT4L-UCXq0cT87EdJi4JRB4pe4
TVZwB0UsvoEElCoqOQYJzf0sSsB2NXs6HlJk-lY7Xronn-O33suJyfBhqmbzeBpsY37ntBILTsHzGW_12J8dpIDpylBhw_oB9oXf5tlyuDEbt2VbvTStj3wi
3w-rPpzwSBJ9oZk-lj4Hy43i2-pP7vy4VJZoZgnF6-YtSAozu8SFqVJ7DTD14Hq1wTEf2GFiHJwiniQTQQwzXxwXmY6FNSRR8_nE7bSTHvTduJv-q2j546yl
8cTQ6jEnQUCdsdWdU_4B96pEj3GwFA9N_I5O7q_QGrpeCVguWeBU06xZ6hs2Wc1ceWbxvbjnATDIcTu3wBY6-dLwV2u5XLDLnni6dgNfk8fMK3piJ847mjA7
8UKJBD7vnQ8jtY1VU-uTeV9Gkuw0M_A8wTEYHxjUQUfS3UWTaQxZ9jh0T00OqhpBw4BlYdlXGtkhabaXf3Prhw09lJFGuQAQj0HOcgeEbmPwSspxnMd988qt
eBPn3zN6z0cWzh61tciLxEjDQkiwDj24wMFWfcCBUa9aZofEr6HA3wtqQTIkOplQcW3ycZJPndPsgAVpD0J65DfxgxK2Y7_FVQsrzpvxGXLCdulqCOz-q-MB
NwP7gVhDc4SRqySZhUlu7RtLqvzSVui5uuBQJdzDnwzGxLNep0BI-WYc_u-EM4xcc0mBQIC__X3qYa7LhDvMp6ti8cSps9i8Q2iBgMsaG5jbUe25IEixfL9L
xJrYf6wbKgcjzHUcoIO2PefaWLhRavDa1JsL1KHg_q9F_4xNYTvx4n6cLxBWBo1Vr7QcRuklR-G4c3cXjGNgF_vh3mv800004015_qVt8zJc3G0000000000
0000000000000000C
}

