sprite $135 [93x93/16z] {
xC610000082W_QaNgG800000000000000000000000000000000000000000PkzC51l5OJ2iNqYo_Full4swCwqpKOgf4mJnj-T0BlCXomU6x-0xb9O9o_Kl
jU-Kud__AiqU-NpzZaedeX-K-blq0ZsR2G0M4Vl0wnMlG_1wePYPV32ueftmrLafnUlpAH-OgSXl7KvOrUj-RAbK9y0rt6eAhe780FtCXENQNgovy59C1HGp
KQl9CGNTC05OpUinA2Ryr-64jPHwAFnYa6Z2LaVXt_yo4T7FVxHytpCE1RqnW6ZTJBcWL_WJMWL_8dh1og-waKKPR-fEDjMNRcfNNRWmP2oRBvZQffzJLEZj
uD9TAxvY_0CYqY_HGEy3MBlwMShCz5AOMLLBMItoRHenKFELLQGm0zXrN9pLR6MDpdW3TqSybKLzLHlcx5Mc_zIFKcPa_V4_DcnSG6U5pMkCcp20zCFdve_Z
xvp-OFK1neVgwzG7w5lLcSMKZrSUA_ukzITYToe03OSPr01c7Yqm3a4xap-k0ONfAImNG5zW-O1fEEgHlvCdF7_U2RfSuM3BM3XgXnu__EBJqvyvHxPyqeJU
bMVbG3_f-1diMJLcwuRlsCD3UppG9kIKhK_svrMPhHhkj3Su6A75JnP-K7_cd6RhgiyUXcT2iDL_A4A7fJobBGRWdZriiTS67p1ysikFgW-btk0ZQX9kn0oo
rtxmTgISvFe9AMD7mzh3FjuUXcH2Y9yX-N6zHMW4t9WPOg_zuF6jx497GqQTWSoClUo1cJ4W_HKSJ9xN1kVVX1hlOmzRcwMGG-lZKLK_bYlOnHvlpuJinwqy
PVkG7zgNSW9x2BehNTcluA03B8NxGetJsMityQQH2iCnE-de7JP1Edlj5jvK0-aHE-cAxYp7QUqrR-hjyGhb1xfU7fWPXxGNbo4-aPsFrcAndqCD1xGNbw45
1skvmDVNzOshezcBCs4SVPPTNbcVyt1eU-sMTGV4bLAZGMlplUp5cGI7wUaL44rx97wKwIBxfuarxP4UPBAMxtHlfhrcqAmSeybYz2fx71tI0LyrmbxR3fSZ
D5aSBxE7PaExfNqN1TUKFTaUIPjGyeSUqyli4Pe_XrkO6hZPybHxPFaxVTBynAVR6yVpxQ6a3pwlNs2ylVOrD9BsWyVRQyzipPxrX9vcZtYmlFQ3CT1UV6gd
0q6zETmUWK73QJzul3tE7NpIrEoZxA4xoutFX3J0NjDmSMHkS1f6sUjVB38-4_8OU_34mSVUPBrXzi3Bmg1zuAPNqMil3Zv3uZOB3R2NXr7s976deNI4tf0i
bpKJnkIjEb7_uhJP7d7gq6k7u5fxVS5NqauDwI_i4PX1cG63Q9izUDOkNrEdzzex9FtsI9DMdHAqfwQzg5sUl-ASzk9fMixPLUTfBtlL6LS9JkivZptkJp0f
qvvsjx_fqA2dXmhFU5trrleSl30T7F223GVAEU50YzyKh07q3c1fODolf8Io45Jdootq3l1o0-uEIMd2opWbE0dV9_WUbxhaQxPec_QclHQ-VwYGBkqLJ7iF
IotvxDN6Nfm1cDw0nwNcT8alJiLeIi7q7Z37fKO9xUNkgqzQUvwkoSaqMTt2E_98oxJ7sUpHUgOzIMRFQT8niZ4JyJ2cFQN9-aaYIsPFw2ScoUon7zRUjDSE
tKrw1eLpsQDRS0SwBxX3VBWykRtbBZYhkrN5bLonfw6zPNahVKj067jC-sDH6iPxsOkBcxd3P_7yK02_iptAPQySEFQclNXs3sSFlHPULznKiw5uCEK1lWFe
bCJ5ZRlhIUt5J7JQc_PsdYoUzagg7mEQ31WNJcnlmjFU6AOzFvAzQMzOvtDU6w57ipT1cVP6CEtXeJq4d55AH5vxZrTYOmcXix648BPNCYz1MHvmQdajoBiG
HM9xw2XI9zFUj3VjwG5hpcalNa0qMoqjI3Sh4zjh0VExJA-3xuEqouXYUp6JQM_QcqilfxtZ3dFE1PXyuAMNSmaVfhrfRzgRovwdlRdi-PNsIXfxDCby6Lw_
FV0ImdGUU8d1euFcYUrXUGIVLruBtI9fOw-LTqPztUL4sjYpQOzukxsInPxssvlsd3FTCAAberHdhZaVNKKfgMAlvRJoMj1RpdpsZEw067ekp_ko0UNC67jv
08jPgNyefiAKWConbmKkxlKMBuffhmNv7ksXfKPOv6_Qunpkl3x0ZPCDK-kqznSfzGVSaFB6VDCUhAx0EU4jMwOzBhN5xKgfDoYosPlss5j5WY-aZSg2LFQc
FTZZnWcq-8s-QOz_ieT739IdtzmfqnqWzgpaXmTqsCisny-lccMmDLaDF23w-ijuL7ky_0IFhW9Sw06m0Ve6bB4vR4djOVaPZ6sm6DDZr0SVj_uojWddxUsX
T0o5uQy-VPKzdlOUO8syrO7gJ34pzcXvITwJHbw7leAHUI-64jZBskP42UI5O6ZToHtoCjlR1-cl27MVw_6clRWJ81lUe-zjptQt9rj4SFEZtzRU_lFMfQa4
UvtpjBTd9OHjNu_IhC2QzlODFTvOuMB_mVrfhsmTNDECTzeulxrMWWHtdlhn-Fb-zgOzRTSlIIaAki1Q_8CY_s__0swgJkUzxKrxHXTmCM9e9slbIrMJv_2p
lMaFFp6agovVVp1STNcjnSgVVVglFHfpEIn-vBZs-Ccp3B0l9ro-zplD603NMildomhV74iTSFImh017iXVB6wyFNn5r4UNbTjJWovvImn1xM5Pn87lzXUDV
soiWOg_6UiUU1lRuzuDblAm2Z-nDUrTZRA1RUtADoqzx8iA1-PtjJNjNOD_-NrMzLkTc2f0psPjvBxRtJHVg7vo3zywyjqaVWvvexxEx3dLJjUk6aR57M5F0
sLlVO4z4r2yxss4rxhKtdcclDT3Q-mBUpFpfzzwvDkQdlVsEGcIFj4brqjZR-tTFUzPZhuszKg_etlDxqvxUs8C8_WnREqY4yV_WfmUZr6yvjrvslYf9wnM_
jMVkvOF_vn-qNl_atqEFfptIdUs9rojyOwzTrgztQeWzPcUdlHRuTojGCxtQ4xlQAIRq0UlLfflWjjrWr33jxNX1800qysxjdx9S4ZZjjHPSjZLtd6AcFJnc
NDLPG3tmm9Oo7dDSUozOlgURhd3m0SjGkiiur-_5oxcmuMVRpkltvjfPwrz8mTvaoptMpavxhOgg_UirzrgthZbkwI_DptYvlVPGIAUyYjVOmp7lTCMla4Ve
kuq0REZGB3f2xrZs2FmOZBs_N94UUGOQG4SPKzlBa7rbVRNfGlimxSMJdKZ_cDnfBzPNUDrTgvKQfhqK-k9y1lQQGnxPj1VgSsK4j-TiAjWaboJCUzEt-geN
vLPTARKcE6RpIJO1iDfIL0M0gjOM5yfcRpx91k9r3SOKC6DlJzXgG9wKDsClHdpSer1cxE41z0mWLaDScPu2-ig9VFPAaYTsWoroXrqUFCkKzhcp-kXvwxiz
DLYAUoFEtPYU1PRvlFMnW4LLhPHYgigSzPdFqruCBipdhOV83ZLdDd3As2DaavUarM89Oq_wvfr19w6_dFvbBytWi5309BHdxsXlsflsfZq-XxqPUqgJtlLV
bcPErAcNQKzeNwQzQIyzqzxncVOcMl_2cNyAm7S1w7I0xuE7Sw8x8m_iyH9oEdrB22Usnm_iBGyujRmM73Bsq56aTx9dAMDFfxsx85xmH7lJs7lRcfCtsTFC
zh23l7pwGCUnru80EZgzHSrlpsYogQLmoDlZJdkWlT5fRzex0jFUH49x-PyjCD54dNN28UtDcxLCUzFUl1vmtZfc8_DuMNmkWUz19oGkBc9xaigUKWkVVEbN
Jt7pspDgm1lCxVKNbpFPYoVwu-BmczdBTSE85kcsXsdlGa5cU_HMzkBYTYnQJtLT4aVotYZu6AbdrDZZD8mxq7d17H9srljd-YV7jpT1NdkLzc0k89hBYAQz
2ffqtfvehaVRpZnOCkrjilTMbvVo8Y8BetE7CDs2vXrtThnJ4m-li8V5FX6ETc3j3WbsyDyThx1db8FwWi4ViJy8eXtKO5-iUmUQ7KdhgV5ODF3AmoQ6sBwG
LJiM-s9PksE8Fd1JwiWUahUZUDYy7iI-mMs4VS7HE_1jXwtQmTJ3wb9hCdlnP3_6pIwmVMTPiGFHZcNT3Xutqu1WXY7boElpxKdeOk2ESVRuRWFFYF8blkVO
MrvWJvvb3z58I-x4jzn2huizx1Lxn0zARQsztFtrjY2CCVRYLiiIxU3eenvyno1z7DnF77di-RQc57YbqhOrZr_ja2QAens3oj32DQCzb4r3dToH32Mer135
2oJOmVP5-1sTQGxT6KOf3xgfBRMo5zZAa2KQtc9gM7hVWM37k39Opl5yYH-O7ODr9Mzj_FjoB79LnBz_1pSxEkmj6n9C8keNt6ql9-FjITRbLlRp3vlsSePU
EuZWqzxFBKxAHMdwePlj8RjDNdYhFS-xJbNg5zXiZvSBsIzsnoPx7BGDidNOjTjUkmNP5rXkigT1LprRkyNmEtjCMLcssqFUYhEjEbt6sGFl68ou_fWnzZH8
BVb6oyeuUykLFRCS3x47ppQr5vzSqcClRIRavSeGUvOwzDeMSSKWUtp77fX1esa_kFto0VQa9ivwyIySRu-RbumEDHvaBquhpfGHbFe5ZxNtvBgq_U3nzgG6
MIzfvdCyoHu_onwFjXUVr_c3prvd3tnRbJ8l_EyMqEsRCCfUpt792jTloBFjnGrxNZ445txmU7jQipOuutPnuHVPMw8j0xvgX3tnw9nEFDfP2tQqrsv1v7Dv
lZsKzfWaHcjRnKzxy22TP6-uLCLxseiF2EMcFTNqxUrfRUlDv4ZzZhsvFQlVSARqM5rRUV9HxSLbQ86snuBoWnByv23uwD3sqBwafPLdeEFfCue1Wmvjhor3
2xm6IIyrua7b6N1aUp4eWRpiI6qew5oNairUdELYfDG6fiF0jKLwBli1fRL7l58Uj8RoycErmHMq3e0eiJqYq0PvBdGaOBMb26q12UnjIlmjGWV3wWtwYpbJ
siKURPm7BlK6fiCXFYJy-0FQoHunSwyyIBt1XGx8lyKmfatiPgyVAVM6mdH8kFw3Oj35GpJENhjbs415_dvUVs5SC40VOxmzuj-67clz1mCT5jmfJ_bj_04W
6c-l_U1-sBpUuWewCk9rVFtPmh-m1ne4bzgGPqfeVB6gCeOl5kcmDtXv2-IkEmCT7gZNEhW2RG4pWphj4Nz00m1hgNTmeLE0UfyYD8uEUoE1UBsBqMc8YbYK
yJHx76mP1zWyF35F16iDi6S8v5jL62-FrKgzZoleNA3K22z2Wm63Me2XwiIzHYZeV4Zn6bAK0Je2WAZN45VGAG5RVK0n5SvU0hNYDSQLwRoWr4TuTHLGJbYA
Lw-FKD2v4VFw4wQSgHu5MBJKdoWAEZ-ifVvCCLLXx2sEHRMK-YDk0deJnEeQlBgRCEs3YBlNTIZedO0MhwifgimCW9uD06PHzTeomwu5B5Pxy59CFpNIU3wb
gKNLPAoEwKs1r6wy-WT5FXZp4qJKBrIllPY0tXeMArwtK_G2Ny4DT04jV4NqWjVjU346qGIivdK0NXfCBvG6hoDmbLRTDEZr61G5w9O9HAruPc_5H2Xa0XQn
KlDX9WBGPDKmljKqk7RFGKuWObQAxsUj_6xQOmAmY9gzs9kPY310WvWMLL_XK5Nn96iJo3KKYnVtEWJtuiK-WurUmWG0omMxq2-os0NvWB5lh4tm2Mk3rGkk
3Sqesd_jmO400000W21_wq6k7W000000000000000000000000000002
}

