sprite $135 [446x446/16z] {
xC4X0G000CCW__w1RnS2M0400000000000000000000000000000000000000000P-zETDxMTI000n2cWFZ-xtjN0yZfH84Lqun6dhdhiUk6r5Uw_fsjloPM
ZOF-NQ8y3exqnE18t1MdroLqOhTyGmS0-iyZS4BriEMEeYyWjGGTe2i4YBhuLEafj1qd77Jbm3Dtqp004O6oHvsFxGwahm84TlBpdUKiG4yTBm-Y8BXG8SLs
UfNQJhBgY32TSl7FnWl4ga4yrw--QNVYXWrOtMlxJn0l0Msfwaa_rKss_uUsL7O6srtJGyGHa6TDT_hvGNVj26qelkcthLqwrgmUCZdtv4CPNckOq3jnBhLV
JKTCCzQZBQNDwkkbQE4MFLpLt8WFcRtGAIzV3yoPrBC7Rm9YLe-tUFn6JUZhpJUE3KwR5x3gzFYnaE6dFdc8gV25VRqUSpw3BwtwfgKtNW3iYSTQM4gFxz0W
OGcKy2P73SlgWJZtu_iUxyYoUhHXvi9DTlBqzNZ3_4fiXZVwQG12UimfEtsiTsBKfFLeoyJqYUFfw-6pNcZfzOVeyHPzFYxsyNgGuMCywobD7nLgFLeKOJph
GHElNWzrUXVNnNgWBV5X2-YW13rPFgwnJ2ze_NWBHkziAD4BDJqKw2MaIczvFWmhj1wMrwC2xz53AXxN4-bwl3egUFbwWKGyBYXkqBDURURrjFdwhNhufLuy
J2_IzA9mz3YPUbYJZ_MGg1Uei-DC_4YeF7oWqgxenQgvLF6IUlELZJj_Z1xsqUFRLslpuRfUtqTFAlY-XrNr-dFq8aSFmgDdlQupUjRZTL8UFUj1N0yRwCNN
UbrGZrj7Q8Vmr4wT6DJK_WvY_t3NcdfebDWyuwvP3skVEDiZzJvtlOcUzRhrKcCzNxKmtj9wuugUY1SWF56z8Bl7-I5KzJYEzHBZnThaImYi5rMnda-SNYqy
Hi-pvsmoUzQ3Py-dphjE1MZl4hkclGjKzTeWM-DnLjR3i1gqKHw3n-r2HQzHhBVccTDwEDkkPs_5xAKtxWVFl6fXlRL_Vad0qpzthlhZEkjn7Eij4Uivi1x5
DpgjPpt7UkMnNZZMivxrh3TVosFlKxTXLFNQXsoBnu6aNliKF4IF_wH2Ju_pF3rUCkjPpsTEwn78S_02JVAYaogPl8pUdoz4z9uSn2ZM4uYYNhUUzKHYFGVM
knvVAq1HptgUFUjP3_vZv8lEM_JQfppb7hMe7jhd82GptwUaNgFiE7tpVM8LFKpeMS-pPxsYsOEOdlMOprSjGLbGRxQl1Rwzl-RLd1fwwwHt3k9diTvyJHph
wNozGC40Mg_Gpf-Yl_h75KhuMO_JJmP1iPx0uArIglMu51q-wtssmyH-YcUlzdr49qRhjkd3V8y2UfNFCfoQgnI--HwXENjeb9l6Z-m6oUQRxv7h4Fh424xj
YqgHlMxjJAmtKKJPvPxrSaTlhcJh_VJlFUQeviEsUh4O7XyH9NmXevUVV0iKrsoz53m-1jPRGmzfvDQhhs3wAEi9Z9w0dlLYAlXTsTPZXJHrwzNZzK5fw-bP
ZnyVBvZ_B0nK9l5PxtTw94RF67sdPptSTw-C2UZ_lzLa-BdCDoYhroYvVc-5-7c7rqbCrMkdegc7TYufUkyBUTatEZORZmD9lNQt7ZBqUhOUntfdpfp4zBVi
adgUlTTg28UgP3thSUfcRwn7YrMl1qqzJE0Lp5ww7dQwvgpF2JtoucCBOhsfsNkxGKJFitVaX5wif6Sz6ix0yKyIUjRxvzNAyO-4Pxqb-5ZlDNXN9TRHiruV
wD4_WjojjvhUWa_lMOy3vdltUfSNoGNqhCSA2OTPh_YJgRzSXSft4Qdg5Rnz3_Lwyptw_NkfmvVtBXJulRDNWj--0wnPBwa4rBy1p7hLvqug-QTwKBvgGMeD
9NZpFMhgeG1lTYrwhjvyZ_wCmF5YI1GSrXjKqGM-gXFMc-2RLVRi_P2lO_xNM6yTljudVi5IUlxgS2vdhGyMztUXS8G-bjfw70KywusZW6UzSHBjhDS-vITy
y3TsdzLhhPuFvNRpVVfRW-SdKEHxPwt7Vej_txhrE2XO7y_UZK5CnBF7RVaRkmLcRveFiKiW-C88rfEAVrWFgEXPpxDdFGV2UawtdlKoOZth9STwrhCUtYPs
3Dv7G6_wFdNibkzkSyR2Ukr3jiNZQEgrJy5pz9gy7kUnUX3Mivx8wuBLyApdgnPEQEh5jjSi78pn9FKu3kkv6EjPptgEzGHYFUl1UcMndWFhUVPANfq8JcmS
S3xfnSfwsFmUvxbsCQ6dy2H3x9asYERijM6snkEiV9rWFUij5kl5_dhpxM8rlPdXyrMBXjwu7yIUmUmb9tpFt6-SBTOpdlMivzSbMSzyrXEAzQmN3z93__FV
y4F4Nple2D01eoCw7P6T_X0z9ZhI2tP0Ms-vaevbfJN7ouuOxUYZtmg4TyHwVElewkWT6Uu06Hq1gHvXrIDvjpiXgjUeaQjuF4gZ7Jrdntp0NQ-jX_SbDKwE
tf_v7SpDEtBq6kVXUXXR5En8qMCyF6Rs_coej_eDX3oz-Tdhlz83Dxs9Nd2hELSjlEGuTt62IrSjtCFdhh6m7bU5prUSE3-FqzUSE7V4y34G9yCzZBlk2deJ
ZN_5DvhAVcu76p5uVWzyZbgI3vEDjzbpvsX79--v8phjoEv1G2-rSvwCZe5h7nuH9uy0xNY6NYJhpGS5HsJgXVKgOZthySN1IW7ppNT-R5kUAq4lrjNht-fX
zMca-YRq-hfwaQBN5jV3XOgngXxpNTH3h9bnnGMZfwXNFemyQfDwrblZNDeIz2hmwlcift3PcQ-7rByP-JVcSgxfCHvYzU73NNf87KQkvnQzllJeyUprP3tQ
KdL1cQyNQuRuglHe-T0QpcmfqklMcpYNWbQKjz112NgwU5ncbHvjcDzYFQwpLe-tOEAW13rfF2wq_rYlBQ7NPVJ2Uh9uN6j_a9u-Na1NptfSxfFqzF42fq-U
aDRZ7ZYq5EldKNenfoVEntu8HJtkWTCLyURBvjKHqCjU1Nq-hAb7zHNWAVBHuYoWn_NWYmNe8PJ-lL_4gdh7jjWTBpe7CP6Lz12JmQ1vdQ1JBhme3x_KIptn
x3z-p1TbUlnOc6rR72-_Zqgz_AOHk_3r93tSfLVGiJ9VHyhBqzFrugeUkZuUyt4kyo7IzOvjkA5N-zMz4DDst1OdMoyIdXmewr6VhwVoOL8FXFUR_km7869I
BmAujJV4BkczjCjRpfCSz0-9VOB-CLLwMA0bpPGsYx-fW5oy_W0xxbY_QMIreS_7qUy0iMlGXGKBQfSTG8vB5fi_ZWJSk5O3TeaY4HIVG8iXaLsN_JZLvPYE
0_HhgLNp6PFJRqp10pXT9apd809TAdo-TCH7pe4udOCb2O6OYAC-RmxavHm0EvmddGr6pO4qcuFZV_wNFXy0GE8BE__T7XmG0020803w_xePbGA70G000000
0000000000000000000000m
}

