sprite $135 [96x96/16z] {
xPc9SiCW34Ht9I7O___W7hYDnnu776Sofr_lwu64HYKAZhcvkRcvkQ5vbAnDMcarIxWHxs6HJKDQ2SCrF3Ux3NSp8ytCFNuZqZ_fU1KhYpbZb0JwVu25U07c
assnlssXrxu2JkEIMc270N203f3O4lh1S8uYoNTk0iw7ttxVRB-2ugm-iT95ReT-jpLTRESMY4SghOjcVYUmX9AIOmOVkpS_xNTqgeGPLSAntx2-yT3FUHMP
P0T-ueYz7p4DeAYXixed-FAsC3rYAR3wp-AxxOtIGu0aVY3EGlpzaKqIj2JGtOaNeRlt-6sS_iHRDCMuEWlU8bNcoziFn4lOB_C4IBxat-r5lo_v3zMnt_0M
hZRsyrs_nkN_I2PVJhzrmqVy_FTJcaKtv_89Xjg7_RM7qI5EG--SzLldIPdRy7pHv9VRJwWJbnjG6NKFDgMJNbM77InctOc-W9LDvA745byuwGSNzidn_QUT
tH-aubfmghlF1rkyuAVS4wLQfg48poXpF_tW04pc5InM0t3n8Fr-pd-CoL3127f1w0Fv2IIoUgc67FYlrazhUA2SrC-5-lSry2fUg_-YdF-GGyLrFugK4Jbk
G4r-kNzQweV2KV_KsDy-sFy____HtlPJuYVl3oPDLd_R_zdxuIVzynjE-_3zkLwz_zD-cBJdoOydpDlFq_0y231w_B7zUe_aq-FdhZamCu3C13pJWVvrP7BN
8Xu5FYcW_UFVJE--lXJ__9wv6JsHFD5Wgih1utUkxxZzUi7NFy_fzEUD-GCbmnYfN9-Vf1ecX6JJ-G_jSFxZacD6atXjVcLInHJgVm6UzlDFBvp0j0bpwESc
iIBEBb1jEl_SoAn9ZJX9Igh-V7wBdIdQwG7nkXqfdTX2O0-ZQWtuD9RgPBZX2UQbgfFsrXC0QbaY_0SpzsNyt-RZ_pdqKZMW5YVUPda2fhP7DBLcX1kkStDp
S_CD
}

