sprite $204 [96x96/16z] {
xPYBhkCe38P_ss2mG7x_nzsf8pgqj4FIlU_saywDo1_6SKaE-DluykNBbozVY2Mbh3_9EGaJVZ-SibPxHzMS69z2kTIxgKJMEQVy0rMDImSbCwwJoaXHcDvL
RIokPi8bSeqemHxEvUeCKgy5KBu524wIR_OZaA0z0OJx5qrVhGE485KpnIdKJ0aW1eHXNW0XK7mXleJZYzpf61vX9xEFv4ck-P5EJS0tVK1d_I2C2GGxgfLf
CaPr_PKVir6jOeEO4Hv8UES72nwWQddZBqyrP5Nbbtv2LdtIvTq2o8oZTGRDtGqt17S_Smpu3sIk9MXt1r8aCArRMslfFllZtDRQLCm8qas1r1I_XsHbqpq9
lmUnkl57YKKObnWn5EttdhXCp4ouneWnur-t3xPi2x0lt-SKIri_omt20YLLpOmL2KQ3xjgBRYnoRNxGwtensFhp-_RNxkxDgiKibJQ6YnylClUkX20rzywV
-NFKFvZrpNsEIzsxBEMNxGTOBStLlDE6RfgmqtFzHuTSxYvr5pn2tTlr3gycB_8dzundU1waUmIVyBCSt4TVfghU4Km1cntWpUxXdh12Qz4EFrtqfoFHh0aG
JJ4a0CpBTJy1eC4eH0LGktbcDrSWXJaVPPi2plhbW1244WJqeXsbWNg_-SKx0fBfXctz2-OPHvsaDcX7rLQE6u25p_tICyAVkiHpdRr_vYS-eD6U6df59D-q
DUzfgW_uu4pzUQs_kXrRH3VgFNgrbHXlZ_Ndp_fJt2D7OGAEIObYHjtqvycdP_UC5NBdbtxi_2G1Bpj1iEuQSm2Vs3-90vhsoe9dqhGzJ05YTRV_h-Hr0vNk
BqHxVyOhghi-wnjMziylVVbyXBdFVL7S6xrvFkh-_O62vqUOMwAGbHwpJT31C7poUYtnNj9xZnzvN-7BTqTgzv1Rsjp1JzyFGM_68S7eyDtxyrB-BNHZy_wy
sptsRD__KUFooFxg2lO9LaiuwdzLVyI8rR_r_yVqw_c90QQFynlr8y8AAr0xq0nGnWBHQ9_j-SFQv0oe7_vkW9SOUa1aB7zJ87eE990S_bo0eeTV292bFJ8s
r8SAqay_J-FAzs7Gm_49OOEOfJdt8Gg8ucjU5iaSch55nmHyk6SH2o2y31E7FfQ-HoED46tyyp2IZUhiq75OkYRwqd-3rApG-GDMKy5vM6yHE0tfTFoyW-Em
kWYkm3fEpmdleN62heAhK58BQjMSH8W81qJ4ahAMQa79XC-8z6PghJROBF0i5Ac6Tw8MpMcZlWX5NPX-WB-VBr--_0O
}

