sprite $204 [93x93/16z] {
xC610000082W_QaNgG800000000000000000000000000000000000000000002OFRlGbX26WG2Q2SaqVVR_d_kGTUcwbLwEuf3j79fzkWOByiuQg8sBSqkA
2RVvOczvdGO-o3SAxndamHhqpCn9Hhu_zinCxnor3THy2iByU169fAb2RjF0dFbbWgvogGPGCpBoEqXqKq3EqAWwK-Gt4ucqOfWswf7V6msogu4QK_uCT5i7
QQFEo1yb4bL46lNy8CbjM9WV96pkUNd3e8lKuyXq13c7Jfo3r8jRVY0AcINOTQLRbWi3kH46osBcQymoGvNvKdHNUJHtZtmfapbHJnVaumlwLb1rCgLyBYfc
avZdHgJhIvl605J9Q0cwSbOmXQky4RZdCoH8rU2vx8qRKcgdMtZ98BL2EOI21hn_-vmdwYTrOYrF3P_R91vUR3kXWibgjUCF5eMkFUGJeJ3leKezaF9XuRKc
YjSUcecekDyNAZNGb0y8AYflFn2rVcaQf2PWFWGr3hnaSXRqv8NGksqkwv0FPd5zGnTVtxsGLq5STdrOggjvvXS-pcPTyVit-0tP0fKTUiuQ75XJFh7z_esY
U9fjMjF72o-R1sdNMu-ylyalPGt3FbldGDVJlTDWTutkhv7YclXRY9qJ5p4g-VDFULaFLxlDGjZVKkpj0rdhTjUW6-sVkBYc6-dUqEzzOUV4HV2eeNp_x9rT
bkCg38GfGXIrEMJ_kxt_TyYasZweWuaSKu-UwTZuGq98WA768Jp-zdRq5xs5o4I-GZy3kaAilgT7zy-W7pOsN0uFZmUy-9T6qaCVUl6f3GYagnuSNzJl9dW4
AnwR7kDScVx9eIrFiU8dSLXwzKfBj2q7XYS8A_JYaUbTDaR2U3iilXiL4iv6ZxrdEkWyBuOJqcFlcOwOORd5S4fwZ2-60oZHa7TMUY6gqvodzOdF47Eoui4Y
5yWQl4-Txw6zBwVWNBBfDYbFyM6v5bQYQQzZmJPE7vkUlJlVWclfKsbhqWlNm_ZEAosAc_IeHtiLbE2zJY_ZuFIWnuWxXSBD7zDBRxQzzEFw7YiTOiuUNtfA
_FO2aQcsFfGU2jsVJUz7lVe8oUbhiEktbwFaE8VI2tB_LmNqV7OT8729NRD2qFBtkyifl8TUqF8tl2pTNqrmAUditPEe9eInzFZ-NIJUZI_k4raDfJSa6h_1
j-af9Zs3Ot8WKCWowQqOdnpCz2Qza5plBRhrDJqyQ30zldz_t-HCgMSk3xha1waCfSVtJvrpmBVWJDBHhQVxivOAOW0zbFkJSkUHB_dDJoEy9fGxIQaWtvSU
7k7bEqaxTt2_ZlCPXdNiq3ihuzVXVGWTwLNL7vOxgnWQiDRew7RA9sj3CYw6SAvsVP84KXzwhEKxUcAkb_0jt4xvLiFXo_-Akz0BpAhbYfdUNStmk9vqTUew
8pqNjUFoakSiQUDDHOHcUlLIDDrVVaOlhYqmS-euqoxqCiAMBFJMrMlSOthyck1oggwWSQd3m6Ve-Z3wIHQM5nqdqsFNcLokdvQrXY0qAptZAsfvc8Pp28pu
YY9O18R7xycDhXj98D3RR53IHmciFJy-NubuuVucTdmyGXN8HtcGj8N2K-9mQI1kRR7KL78uy47RygzJS5XdYAtFDEKmMNPj7VQcn5NOmfFGWsbsT6cTnKn5
V_I-3anlXYtDOV0Ko4yTSX8pwQapUfn0YCyA7ovkyNhOueiUHy4N5i97Qxt5xAYSbuVYvHk5ZzLsYvaUdD4JweXdehVTOYuIfGFImxdfeHkzQNkJNbIQW9us
Qi5wYxcQ9ixeHIwi_ow4JnVYazRJYZVlzCBK27gpFZJfXId3wr8SZTvKxBGmQTARz20MUbFHLKK6jqxrnbcVzKzlQjAhclJcOiv9RpDHzdaPCtjJUReEJ_Im
ahCzGRBQqDJhGUXTDXJs5XuriAZEycnxLmEzGSQNagekkMfHrPJ65FPOBcsFkv87Uj1SIhcpIYbPuO1Uea311Jqnk9Eu2xcqbFksoY9ui-V4GUY5ED3q88Hk
3Q1YeF75u9dUPgKVeoOCR7NR02LqaBsfJ6zkGO4iTwkom46YSsv1WMHYuvaVo5kTc9wK-qzLvAqbjKalwVqLBUdSzF1EUj0DmylBBssOd-BCzD8R5zaWhvcK
9Y1K0KdNG6Tni1ZXVFGWnkauPCdV8LICVcMJ7XRca5KGjeIa-UsZtwGNKc5s2ItK4sClSb9wyXvwKiXZmc2sX5xFHC-UA6E55wJbYPqcuqIZz8mzuuQmHIyw
feVBfbw0zpnm8LW5_UdPoTPc4Y7QmkUJtiNGB8kqowWbcRf0Z-eGQzBRS9kAJdFzZBFHWmwdf_qcsyY4xoJqUDkpjLcn1ppqd3Jgy77FyyRPk0EyqYtGvzyh
E-2BFZTWChq1IdJGVz-PeuRTDEcXKApP5rz9azvUmaBmUkFBE0czyNa3PNZzyPs37g-atbk9uEs1JuRcXhtG6rkCbTsItWKZ3pGz3JtTCJQKaN5dF26zL7Py
mT0zVUUqFUHz0yDCldFQtZv-4pjF9VKSz70p777k_EKg6T-9w5qjDMTxVLttdr2hjN_OsyW7xdYbnqbgLlp1nqmB1fXt2YlgqiPAx-gNteL4GXUxw3zjMCAQ
x6tyD7fsuoiZ4f4W0-z23sUtFHap6HEsSF-svt_SouDg04kzp-d7lH1Z7tXIoFJsDhuYVV3560RGS_qnGAqlDUohGd5B3_cdXo59CWtxIePKsMaXtYVJ4me5
3zjH-BYaZwUdvCxsauwW9sUYbqVMlVlcmgVjfHh6fv45V9dqkfg3VazNyjyIGYjBpdaHZ76TqtFQ7ITqPHSGjD3UF9v3waO9Fq_RUrqe574I8kQ4PNkH9lAQ
VT7j9hqkwrdA2e97V0Hl1T-owXqNcl5zgkSKeZTos4lvJiBAxjgL7zMt37nNR_IaBGV8YkrXXApaFxF-fV8BK_MsfLvFv8tN0AKLUhtQvvyUDywEZ-dXMxlC
2GyEjg3-JKaLL2Rlk0O8tqT1NTh7-mVyqhkqgNa2Xa1QQg0YbLWe3sWI3s927fLkIADbp_QXqeideBTg2gZt1TaREBgiVhC2NWrRSkf7Rz8BAo9wKXvDHokd
Ee4iMjReQUlQfFZHz71f4LhpPDfCJt-ZBTKDLZgQLkd95Zrx--91wGL44WcXbPwqH3SbRD2hnfpHWLv0R50u9ZsxxFGuUS8ZtR-SSdgSnqimqEkhIM_Tz53f
oUzSvT5lXYPwCeRUf9Tg3Bb2BzN_bx55BvMTaYsJtZQyZ7Lwyijl5WbRz927qflqK6h0kMvxrMyEeZVfIGCzB7KDvhhjLR-vJIyDfJTjhyBRjZtaQg0UefP9
Z-65iD2CuLzw-f1maqBPj_4pXaaF-WHlTRQUoiDNDluroB8iInf0RzBJDijRfoVtRwLzw4rwzYmrmwlP5JonNA4dXYnr7rs9tiVLrfbUczjShH0rs1ujRFdC
sZft8dIkhJEzWYRBMw_ERjiUqyleKY4ww7hEIvkQTqGYjAuCaueRvNiIgHXNHdHit_Kiz7XL4lzJMHwag0PRL3GJu6Pw6hhGmoVJYyOLWUnKQUacEyc2PdfA
zpk3v-nUM-VLkAtqU45d2itqblRDpxRs-RSzU-tPj1A-ZHxXon9QwDbNmZUk7M1wSnVADhqWPJFwI4DteR3dd3l0ah0U28kMilejJCZVIiCMmi_TbmKZZvsN
mz6REvyBJI_FS6P4-hHJ1tBe9_zd9NtSYH-JtZnjPz9xnqbN6PEUGHvEcKkM6qrwRazuB9Zqq90byt2wAfkUzZfMt3MzrxO-j_B3cF5eiHzp1MEMckTPBfP6
Q0CyLZZTgUB-luNI_rJnLFoTw3_fmUVND1PCUWRFwU1BDbBeKEgTw2MNzEpuegElI6L3zx3qK1p3zkpHD1nzmMsXHJ0TPmp-RG-1T8ZFKx9foxX07QVvvhFk
Y2yL2bdczzPxl-6zAW12FptfzPOC-MAtXabllsHrVnF1Ck1h-PCU25z_U0Yxw-QGdeJzbKf_V9B98UyhA9KOtgNRK7f1xhtnfK9x-SRHI-UY5xJG8U8lIKR1
c_HuUucYvwzbJ7fjMS3uKk3Pv-Cso7tWnRZUJ1o3tirQT-xpok-2y3D1IYTuXYmrvQUS93eLnkf9x8GlI_Y9Khxl0O-rGI-yMMauFSPN53zP8ze5tgHdbnRY
zvBJvDJqf1TteCUnefqVj1flXzWLdqalT8F7IdUI9fFFx3TlZAPcGeYUrprWM5LuKIaplqKJjiabNUwadC9hmeR21Zq9xnRH6oNedLMoIbYJQ2vtre8mHfCU
vvTPXGa6rNp_NXA6QjBZJr-oylANLBIUnVcTofB6xnvmIK_2U2K2Or9EORX0Ur0-y8XEUv70BWtXhVJYEUdnxCskeYcG9htXWjZvPKK8avwFKvkC_8euNWBh
VpLrVoLTIXkvR72PFWzAydzSabreyQ1P4gQpQg87GuwpauIcW3IBxo9hK_tRNkGM3S17GXBL9V-jlqZclxMeQZ-RCou1CTYUfyddQvjcksIEKw9SyMXw5p_f
3HPk0-Yvr-KdzAwJNYTDUc8T38ulUrFXbTvNUvj2E0k-Q2XdUzkwZkyLFb3uLePDwzxeiQRYWUbDNTtGuwphbEkDiwoeazwazsPDUXAcVAz9OjqclVTilPpq
9hrsJpuLVT7RFZJj13aMGuizpg_IAhtuuTbfrdgBcLxmHYzIKqw0pz9YpaovtGHsYkg2hSMWG_JVBXCzd8uU31k876r4kP2cxT6xyZJXc-CUAQxGI-vITryu
USo9zg0b1eDcZSXTH_UXsBhGPagzBCMjmaQkRCfdq68_WMGgkGbQx6Fnb51Qoe7I7FWCGumtUb1t0n_uYgloq2tuaRS-9SlJ1bdeihPJVVeeyJKQ2vqOh_MA
Z-WEhXO8kvd7rCzZBFJjHNKmm7YCpR_MUzM0gZfI2dnsRi6ZCLQUzO-mSuLztN6Anr2OFJfsJN1MjvX1zEv4Jv--eb5avsmrLgA3h-Xn6ihHr83yj9AVRA2N
IZNFNU0nFdojBm3ouzBZzrM6dKUvEmpqwCfUzEBtEGtncpoNdUd5ImIDSatqba1Nddvu5thSmPF7RMayvGErey-h0T5xtVOYFMPNUeaSfplNkMvywEkL-jD3
l-S4mmkuENMStBNeRKU4llHYTthnPNhSQde__mfEIrVzqq2neZVIAtW-_tynqaCFLyhJ1Gt-9Fqw5y6oqGlBlsJ8kugD7heCs6nwoUTs-lwE7PMLWHvAFQYV
hhJJY_teuKQvH7V6rx_I44tqgj9p6WofPjDiz2xuSDFZ9xnX6BsWzzQq2TEJCVIWZgSBF31_fJ7qAWZzIOOcOmmzeL75zyZtXM7qWkQSrMuEEIl2plJunMXm
AEvY-54x_nAiz0A0O1SGGXCzUZwZeDv7FNxCwuzD3GPw7MIWHyzdxjGtk3x6gIfsc1yueqVtjhuKZRvNUdDmPSyFlauF4NnbE3sE1YHu5hx8Ixo37e-CT6KK
lQXV3mg-9LyKkOoXno0YNS5uUhXzUGzP-6aPttXw5nvGXzE37CLligTWV4mBhz2hrs2WLuiN7UX5eadmE10uIDp9-0WMNgM7Ui50B_85EpskWJ2yW-tGaLPy
nCf2ZrcPw85PsUdn5OPtj0qwkBNXWmDwSJTw_1x2CHIr3Tzdqujw77YSCQlIU4BRI_frf8Y5ymjLrzFHaw-3mUF0iqfm4i_9Gnvx7_zAJ_XkSOrU_3nwLpsW
vR7riVanFXoF7jsASht7XCV3TfKchWJ4Y71KUhKDuK6u4hmO3gYeP7wnMtqFu-W5IvuprX6FAYr7n6UPzV1I17g1M64LRJK6y0yt_qmqi3CawfqdpVvapowG
9GHY882cKvrESlyBVrTWtPZbbQBZ_YvmzC7ST0lQftTivntux8zzyj4HGKsuUaAsOj4J9TWou29t05pWeprtzfTTqLRDgwVaDXhFdYhOoY5xXXms3h1wXcm0
yqdBW8s1cayWRGYedbLkwnSzJpOCPiyg0RPUe7fUkWq4qGjAXAsHXwhd5MqmK2ygZfIQfWt8LRsemc6h052zh0GRawjtACbX3mrEPVKESXiNr7k8zg2SrNlG
1kUgtaVX0EnH0EvIxrC16nyYUx_C28VT6PoXhDvFX3q9Lqyyse82PFQ1IlPK45bzC2aSh-pwyCgbx8DLEkpfEDN7g4n5q1rs1N3t22cpZr4Yx5cn-ZGYwNO9
V5Lz6hazDp2hpw0tX0EEF-m7_dB0zIRxT9Loc6t0K5z2vI-AByfV-X9A1EpR1j4h8S8cDg2ogXzNPT9jqGPWAFlnfEY07M3ZaVqu8c37sO3Ck_QaLPcYswas
W9DIzcsbH09s8Hj4L5zTAGYxZWr8AZFhLLz6lSfCaMutiS4hlZfrpwJq9aWwNjbTRM26-4NzhU8tCuFTtUQbFJWM000001ZaRxrl5DK00000000000000000
000000002
}

