sprite $204 [446x446/16z] {
xC6n00000C2WV_x04wa200000000000000000000000000000000000000000000OFREPKjINGUY0qQXMCl__xVtdhUhEjAPHcrK5cYFkia7sDiX31HaEFmN
svY2S67X5FW7OXsCy5c54DT3Sg750iHFGFDJ002n0tQ6WiHcp9NJ0ekeObhQ508meKfb8aZxcu982SiSabC7SiiWJC75uuLLC3siE0CDacG9FCcIKWMis90r
GwfIzmxkNjA9ShVDIMEOWIJEKEvswWeOpcqqKPDCCF6kcW_E7KdR691FzJVJQjZEJ1VIf-MEzze5y3dkIDnl7_uCURTj66_lZlUkAfQVsnyTWJSUd4_UhpEz
Ed-pI9BuoL2Hn8Fz_KwJsFx2Gj7rSzhrpVJnP7EEu_ZUUQeF_JtzGxubq9L_fVsBVCt9mNedUHYx-njqUVy0UOyiq2NlFeHFItJz_JsE_5b2pWHFHRGEvIqO
szCbnzoIiJtAUqxwewM39rgXNGgnDo525_YNjA4zJyFpo-ChMoDxp60F0vsvzOqReBBEsCDczePXP6vz76ozsakSlRv4KNsfvJtB7XJcbtT_U-DEo2hFx2ds
ykl3hzXpxENN9rNpgVP0wOgqykvlJqaNFegyszkp8H3o9k-cvrhWw8ySqRFtm9BQw-3a72wlF2MhFN-NvAcRLlOowQEZoAUxGXJJA_70lPdQWJUoX-_ai6Vc
qpVuouHWUtJOowrFjj6X3pBuQQ7snkiNUKvz2UJHVEZWjr1xklw0habxj306VUH7skl8-eKRXM_z1W8mYxVN0IuPsanSD_qWpDvwDWyV0pOliJtkhK-YL_QM
zq-MiSMlnDhJzMENsfIZhhFz0cFjwVhlVT30bVAQ4cAlonDuw_1ntS02smiWLxCliyVsWbjFEsN3f6DSqUjGJbOjizSNlLk_QtwLOzw2hqWppkbZUuaSG2-m
vrZ_54Tdr4if2kVnXGNs13MpWJsCxEsf3qXbpsJ1AdlQQ6nlRrmJSCwUPx_JltdANjykx_hzzeWECymu7VPySxwngyNhzzj3XievQWXi5i_GdxgJtQ-Fjc2_
P_lR6ur3dBwqro5i6a3MDkkkurx_-xmJ7UOuImPxB7ZNKxllzefizYmPrLCeUxFiLwLm4tjbZrOu1deAUqLcUmK3zDMafUpbfkmToitz7ihcqvPt5nYKkyjJ
SjexNlCmUsDztAzobZqbI_RCofwoyvbEEksLlGnJpfgrvBI7nyYRFqP26djcaFVQqqbWBvIwHbJsofw5KLVuobwLAfQzCo2plOAPxHLbh-pL0KDrsDGTA8gb
nzrMTBZnqIUE6-jpDnL9x1r2f3v-9I1v7drbJq5x3SgUojlB7jixk9SzR6mFmVR8DWFvi_QOmvw5ocERXupKPqdipRS9jfPsbZXzbifUF6mUQFN7y40dXRkn
lx8NJ_iTobudWJk1ZxP7TD8KJTLNsQF50hwJyfts1iJRAtiSYdDy81AKFN1a0ZO0C6uGFw3ilLP7h_NA7Xqda1PMJGPzsjpDL7dS-8ZXU4-0l1XzntjoP4zU
EYxI1-rw_FvkazV8qtEwJ67l-CYgv1diF7vz_cQMFKu4pnS_FiqUu-qjgtZgZm-pXsXxN7ga7Q8FAUrPZBob-d21FSjZRxvTC0SgRx6-zU4p8O6zY7ERjeAW
asPbJ-MjryUo5o8FjWQ8lWVQerqCD7cNf2z1foKSHhokZsF31tIUOeyNTZ4YzI69lJpvuANppieUHLwUhozxqhjNwdk6FSfsN7M5ZrTNDZY6Xw-Do67l-4nO
OLk_2dyRKzWxPjYZRkhr8hSy1G-sfsLjbrshlutFiWTU6Zt_Mb3sJgO2CQVYdfuzBBCdeOWCt_hzdjrbpedJqRChkIHyjiPU_77d-XadxKfumRp5CjXZJ9y6
dj7PeTlosqFW6KX6J8_m97jKUydNzLHxTZLbBs1Vb6Ieb3rys1LnsDkU3E4oUvMz3wUMYUaz64OlBPssb3sA1NcjGx4wqCU9hsJDEQ-C7fk0kViTE3RKEdV8
ddyG7JFuTqJj1HnefNnqWJqS4sIrTypXpXxR2qQl33v9np63ettvx1sJE7TxFPVabuZogm7q7U3qleshxQ7iZNkQlsJ6kifloqLwb3rj8D5vi3smB-mX0x--
Ny87pjfhQ-sLFKNjMNjhprhP2vgreFsclVw_sNiMLjl3S-pv-xA_QMolM-O2UvXiNmvxodM7U-FezNz2fZFzHNFOSxKFbioU7t_sq6rqaUAr7sGux3cvkpr_
zlHj-63lNsTpzXXXhxBNk_kzFVxZ-9qzXjghx87zBM_jKGxeTRCHQw-or-LziDUTR58vorwNXm_ssD-smwobx6donaSC-Fgm_t_jaOYsL_kziRpnqNeR466l
iiUtyb3szhksJh7tDdbg3oVjSV6PCXE01vpdL7kJycnmXMYflVpNrcs7gxFwntkGgxCJzeAkpfOzVOtie1iZ31nyk2z6sHlOY_-hfCRNhyp-DIwkjuUozzOU
TEdWQpcnlaTcptxAdhwa8X1dp-vi3yv3Xh4zVMqiYTEhKt0lUmw1xdDbOtlw8h7iBXH_--eU8ipOqtZ150uCrHrWGRUj0ue9UBVr2-w-h7k8wixdZ0_qhwSE
sDr_RHq_P0zbRm68AvsGGyIobo0GhfYNlOHFcIjx_l0noNhosqlpO6F_Qk0u4vZrcV3AJg7WDS-btjKUWfwDQum87vhNNjQVoq_qHF_rGwJivVur3NZQY6VP
Y_ybcsPFovwlQSb_HGepJKnXpwCl_o-uJJGnWptQfU2Mlvx8NUoXVhcqVh4x_fUPzQlBNYPzxVgwMVOe-W9gSjaBq9T87Xzg3-q2VUqxI60lGHK8wceP46Kl
gdOsXdrVsOlNv_-sidUynNoqPTKJY-ITkxQEFUrHMtM5FhP5WM6BaAVwaCBUSGJfQxuCBv9d_kjxO6fxg_GHTXB6oJigUzz04qY7Ev4NOGytiGVpmgPmmQTZ
AkVJPYrAUmKmiRriBp07pcPoJtkwAGvtVdtpJ_rNO7QPFyjYBnIsamBH1X0MHTbJ6mf9080104XHBS4hUy60RG7s5sMF5itlwwC9PI-EtyiTKjyrbzyUsDp0
XBANetwIDg3inO9sbaVEynInby4VT-kmsXXoKXriWhBdEa7j1sRsKmNp69F47ixS7HK_YQ55k5EmiJqExHrnzXJ-JMly2xiMx_MzihUCU7js2MMlxA7iwNxF
cCIUtLcUjwdGtLw-nqROtS1iInFPioA1lQVfAtjbZudjbJqBe-oLlOBerFQKlJfaA7ipiwW2YUn1pZpS7cbnLdkFE4TshiNOsHuqU6KFAUqTn-FqVMmnozv5
b3rcjbVsQhydO63FzhDNSqvXpqbBdUbK47bce-pLUIbEsYkukJrQBgfA8N7fB7jMzbO-SA1A9mZx3eaKexp65DgVo5rXp62lDglzZIxPjKJLimVqzalAKq5G
9UgSlKjFa7KvR-rPaoLclAYKZbkD1FOWpRZQNnTpmjvbfNJSwB6y15U9BjxByPGzrRaEVBuwn0n7CWYmHv-z2_U4hoyF0MNldxvPPk_NGd6DFUsYhS0trbTE
_SRbzdGp5zhJwEqRFhvg2FQsXtNsS7J6qSimRv5cx6PFDtIbla7_FEKChEGsqDxASKUaoHvuMTBWiDUNODBU-h8XydRMjzhUgUmP-m9T4czFfmNxGQptX-di
gIpAKQ5rWkrfroIedU7Pwq2tpbxPWyjU_kWfFvCzkCwQi2kFpfubi4UthfFPCtGFP_NHpjfpoKGwUw3_-60kUnsITXgGi9FsV5caGrx6YSiuQRfa2VFs_Ekc
3Ee4sGEkEBh33lQEB7KpT9WTgxAdxv05OVQmQVGKYBx0x6a1ba_5sqCUURgn8TcR5u5mUpeLo1C-C21x3X6-3-6ylK5tP4zVxmrNzlHZ9qJef_pPKviEUIdr
VJO3NJBq2PS8dprPCYKFjZ-SqETDslfknuNsY7psCAllM98z70jyklTxVObZ6ESuQkV6sJiMVOsZ5x8KJopCtbRsCBJ7jF8Cojspvv2N9tpW3RA7sUn1ss-P
09GxPmyJOpUtFIuvtjlJdaDUPd_T139dpqGUePYGtvzZJxZPVa_XeCrFqhSsZUk_nj7YX11GYFCNvZ3nj_7cMkB-a4AabRUeGT8vsbsc2nnBbdoDDbMnn62N
Dk576afB3d6pXYcWOv0crmVY7kw6yDv34vOUtisTWZ4ayfeZnjYD872p2aCaQ5ArrjCQsDt09vX28KYyXtPBY8ymVGj0koj8t7pCGDYTmIGaizJA3kt-4DEG
UsnhkUlW7DnRd9RC2g121bHJa2I1HGEi_2b4WisvFo1-Yq1hfKw16R42WWI_WIxe5q1Y2RG2H1vqEbm09F90hPS5aG6QlNPNWAngkPXII18PCrU5bEQa8B6S
k3Fb1Gm0IKPQ8s2BAFe-X_cBPC65OUHFLSW2P0Spi0FO1XF9ueo6KlR_zk101W00062Gl_Kzlke80000000000000000000000002
}

