sprite $205 [96x96/16z] {
xPc9ZiEi3eNFiG5Z2V7-ZtiJWff6P48olV_UJ-hcWOzjJ3RyXNpvykNBboyKKTNGK5KX_rzUZMRPJyYMeiedRZs8SyxMoFaGJahyWc2lRWOLuWWf6f9bRvZY
6OovTIq89aYmLZJY0I6lSi5DrDOM53UXkUU05U85Jrx7yQQR-bvK02eWwqi0NLzSNqDOUgVihbw1Cr4BdOSNmhq6p5sm8hZh5pJKFMA6jjutxlfVH7V1X7mS
vCG_LfvtdpX0-TdFiRRCPjy0ZDaw-7bM1dcs0ctsHGMdA05jxO-84eYUSOMuunF4dRWWUCP7J1OWjUcN1JoaryaUhfSt0jG5F4GNkk3I7_0HoTDrTYa-8hhD
bqTMY1FuGrmQ0CAbd-xyqSzKQgCa_kXNprF_ERQvjpOCFo3D__olMXQtIVjgwtVvJO9fyrCRn4vOZ14lOgbLiKDj0E3Kly_cZYvwuWsMMWKlA8r90e-hlziA
SEGaXAa_dljpBJnfqvvcKFTJZmiWjGOCn5g9nbwX-sVPpGrqx7mgzW6yLyWUPlvH5B4WM-hjXMjvk8ETxtwibLi2679_gpt-Ap-rWuPk_OommXf2fJkvZKlH
q0wxuie_pd-i1GrthMJLKZnj_e06ExZbtpdwhKXO_I5Qhg7x1zBz_XEDK4lNGwfAozjgpQyF-vyyZVCljMwjv8oo0C--DLBbPFwV_t-slKnj0JGJn6pQnpNm
6x_NZ4duqVu0sNZRd0K3yhP5oyRK7mxxpri2Et2nWUuLflwC4xHMEpbSokFzMK_zJPOcaLj-sVpI87PohPbuGJ-EYDAO7X_5_ULNujZVOeA6M6twmRyRdf-V
Q5canNFszaMdPo2FPo-MsYbnie8Jlwu81XZCB0LYG7HbUdw8xBgV7pw0ij8pz2yyFpTF-0ZpE3bz_-3wXNs2foUW2tW85sRfEplzdQDNwRMV7X4d2A1540j0
mGZxzUSbhO2eZ7MbHeIgi4haCjuW46NltcI25E1uyw7vjGfIGVEh0C9Z7y9yUcr8S9NsOj5zbBc7ZpPcJvWW_bv6zELliB-m-vNlVIDcHFVOvKU_0DJ-uj4l
VUrSCSTw0zJTFznSElYfUxrx3PW0b4k_7Fil-Q2VJP4dmGfFRgoEOOYvFzWQMt4Bn2qOihSXFq2pBrXKJjoQjfAAXqZA5_VdGT6Oh1U9WjyWiGasShON-Iri
GV01l7e-4fJu_q1H3I4sGb0HuY_covSl_mC
}

