sprite $205 [93x93/16z] {
xPY9qgiW34Q_B0JYmli_xbMwCRG5zSu_Qq_tgeSOWZBW__dnuyUF7p-89GIBCQNaEzjdZ1PKcF0_i5ho3Ya6PLn1xAamKnLcfXrc4GqMqsEpdVLJy9qOX7i9
qn2BNt62S28YiLDwJkvHS1ZI_G324SGz2K002S0C2062-cUzXMwdclYOEn9U2hdBwPjSRcTxnCxkXXq-9GTjTeo87l7WcBnGx66S5C8J6icfFRHBR9id_YOd
7XpRmgLrQY8WjDM2DaQY4ZfwX99n4RJKbKbeU1pYplsiAAvZtRoKjg-Z7l4TAYdd3Po3cKlIKxy_0R28u1Ga8lmu_1kbwUkG-p1frt6ddjm0o0v_ElbWGT1G
7v1wzH1ABL413JRd6tD00nMANAuKQbXthVkqR9-BTeV9sOs-1qpO8Tly2H-nlbm0o5lIvxnQlLlEZXSiXUwPltBMvdpAgw16rohsQl_WrfCpth7M3MZE-gtQ
-dLAl4EuGsiEQ8bvmGCkK977aLnkq3Fm6UyipnRfrKSobBzhz6Ekfk7bOtnjuBm2e3GPO6wWb181LFvkuB6Sxw2W9SJejeQmsggo5ZcMB42p-scvFQfk3UwO
agxAj_fKr78w8g-fvN7PpF19brjVUf7NN9VRmjWZT-3-TaqkTr089UUsch8jkfgeBh7EkToeSjuTH7VgQadpFCVjFK7dxQrK2w5GxIsU_hBEuy78NoDzwevG
K64eJyxLyEzTMomlU1_-wl72LR7zMpuqEBxa2ZumvOLRjt-z1_TlSrmWFA4vhueNjbRTK5-YhIUtptBGbFFyq8UvtELQENVkeTtJAi7cTKefJVkNqBq7jumx
XEAIRon6dOBeJkSwCovMYwRScN6vysWYIWKSXmgZkIB_vIotlxNFEBQIDDcWqvD_QKP_VuYU9xYXWtKt4m7S3Ks1SRdW3Gx0D04vWEnpk-HE6EP5k3K3SIro
oW6Q-Qrz4I1u7AKjjM82X8hS0k0CpGIMigKfDHcMQgX_0i95Jee755wB6PNVneD4wo7Cyf2t7VgGItjWd_WuEwdaxNf8BIUvkmDmnAu0w9JSt0quPe-C7U9x
XrPVcv_OaTJ4tS-xHpcrh7XYP9FvXWaTC4VV28GJK4Y-aKo5lozznzjEWN0M2QbQXmwgKb0jQz3FRO5n3PBGMK5lxddN89Ozs1ZJJYod8KpuQtxy-F4F
}

