sprite $205 [446x446/16z] {
xC6n00000C2WV_x04wa20000000000000000000000000000000000000000000009YzUrkE5aU207nHLwgCqFk_xHxceF1FTz9q0MMLoDoT6GUsQQHF9MIm
wNM2RHeFDl5VYKAOGiboLD3kpJsCcXjRPd2-7XM2bfUOeO8sKpmXMewG92nkb82RvbBDb1LMfgevrQ3aHW3DbrS7D7S8gkekEV-CZutzxwRn0uZkUpGu_9B0
SPRnMO2dVjx2ZDTte9CTxHO0cFv08RgfnZCY1omxmASA0FaLNe7_pV9SFopIy2S2OgLpFXx6XzKQ2mJyPATc9MVPDW9OdG-BZquEABlIamiMnSD3BhelYEVh
nToViIQ3ivYPaGqNRx7mImMQkn0UdCQsVMg7jyHs4_gcS8lhuy5vx9-mBJytHBRuLRlXmVlvyq5u5jyItqt0Cz3kqdXurPf1B-xfxpGDA5zz87Pa8ggfHugH
y2s5juwU7Vdn7VNnrjVZFL0NpqUMr-FbLnKFw-lLv-DuZzGpL3praI7tE3s7r-CZ8-v1UhmlAkAjhrULBtwue-7bzNmlfUPEV7LXqxsitjWMw91IU3nrzOwd
qDpvSgJISnGeFdAWqYjpwaEJNjtYmwaPVbaz8tnryRYUJwxdWH2zgaiMpkUJwT7ZYtTD-TBZcKqleM_cApr8ZtSE2fIUz0eL7tOEJtgEkVMQz7OpyzG9iACx
p-VBwRNLIe_pUQxU2B5RSUf4niHW0Rq0UP5LNRcHDJhvhjehq4L5Ie_x-SLwOrFUoGKbIi_inbdflDw58QskK7nSxsQ-YDMzHyGRZLcBZnsNtQtdCvxbMACh
w7cgdWTkJ8pJPu8UApvKM746zEA9d-NozThi4sU-tlvjrRomHi-lHnkIstK-XnwVep3lnFdhVKUsPFiL-86T3Id5V9FPzLmfTh4iSapYGpKz9QIdqvu6klIa
Dssavyfy8rsB5kafLaZFtcLjdNUfMNiclTScpwm7tfIHX-5nlJQRdXVJanuAwqcF7u-zHESzrDAJdZEz0ZVM7sF7MrokzaRCRVpVpHyGip_-lysyUfuGNIgJ
NlthYjAJ7gGdlGAHde95z5HycWcaTzkl1nkBhnPZsTF3pBzVQZjP3eyde3T1xPajp1TkAcRLmpnww7y6q-Yvz6W0eBC0G0AUz6BfHvBFD_4YVHezzAD10byD
FJ2z_JObqEK27iPp5D1BJOy4khmnmqX2ZmM_huU7wm4z7k0tUqnwwEU2kdhrP_5-FXw8z18A3rzybVIcAJp0tU7_1X_EZxbuqkCb1S1P0CnGVj9pnAe8_fvF
Ul2qd3403hbBp_PoSU4Xx_i3xPnVZpJgUZ-SxdlWF5-ucUr7vjMpZqd0eq5q9-5cIeztU_v-wkiXNG-ap_DtLL-lvUhn7i_dgw-7KteUoCLt2RPywwzQZX_9
xISzOfUnmtWxKQ3s0id22-mo7lEN5AYz0dWPV2FI8_sSmBUcNbqypYUz--TD9EnvlSlKN2yRhonV-v6dwCKwE9zFUldzY-Vf0Nd7SU_20cJ_IzSUrwjH6_m5
f6SVar1wCRuBBrBNr-C9T-trYHIV7KXDFJkI01xcc9pZRSI3zU1t1Kbw_Z2zdgxNRz6JNjB25klhjGGzKdhPnHVNym9wYBGjsAcbpdmUq5lfrZgoyDmJYhn0
xTNfKZvG2dHRWTh3B-bX2RtuOKXFjPU45__PHBKNryC8-qp2YK-r5-lFJd21iHduudVVLNjvUY0Mx9PI_wY7A-TfwUtWeR-4V0PSBrXyzVNmkthuuXajaDwN
Xs77SgbUPtfqUtpPOiTIi_Ri4ZqSwUaV7-AdE1m7LACdFZkO4hMNh-VObDNG8n_ZNqgCF5SF4-W1coyS7sxgRVCnIRPUUsJjyOTuRChjZ5xFrQjVU_7hP9_q
uEDZ_B8U2jIUNwrt20zRFN_LyzrShUV5QcyaJ1VN-md9z40U9yXVCGxe0RrgrrhEw_LFUfrTWic_Jeq2jPUbnyvkdLRblj_DUgezNZ2-gtVaqOv8rbFjOPJI
OJrUVCapfshl1yNHcND4jPUjnojlNyyTsFwr9NJUozRZbSVNdEJQ3BJcpDNZU5oFAwdsylKudli1FLAJwUSzbBxMOb_eOH-FwE56FVkSHzzR1vWUnyDLUj2z
zRllphv-Yj_VuyQwjvwlnpupDczAxETNzbGzwVN3xuWowcfJdUD3_B5JwRMRz9phOKzl6yQD_TTJxUNhlJA1wNc2Nic_OqZNuqvmeeVxzVGtHF_ak9w_DGhS
tTFV42NhyTK725w-dlv-3-_pyddoFPxmUn6glMY7mdt8lQWV6ofwPeJ-RdtzvxL8Bpz4hzIJ0FXBhQu7FIj9UjCKNvTUhKxbm-JfUlOfaLwT1I_UHgpoLF6f
be88wEcfuhCyeJFXgUBIGqBfFKBFTlNqVWnpwtc2Nj9xeI3m2jARyts8fESNuZdkdZi3UC4sul7llrVWlHbhlUyizCwbnuBPzFABhzVLym9wTT_psLrwXVZm
q7VBHrlWxV91Tglptgny72-vpzRNusLotW-iyjRNovy5q2-kbCxnrjVpR3rSsjteT3H8ptPpIR5qPEC5cbbIppuaeVeozcGVKaCFWT_uYAHVKtxeqSeBj9Ds
sRIBJalZwmZO9U19Bz3rEGD0Uj7qDq7WX4VvfUS1l4ZrZG0Xka6VSzx36dhkL_DrXByla5WxhOgUk-t-xrpw-m1WS03v7W_aO3DVsvcWL-62EJeD00wt3Jmn
qkDyF0buqaltGztRClL74ihXEQH7_6QrK-tn1EqAtT1U-ianA51tgZqUu3iwB3FSynzDdL21-LMNz830_ClK-NxvTZmJwo5uUzRl2G3iNu59nxEQjMUMpJS0
DtM8iJaJRuHsc4jlWbXPFKZF_I5wqaCHFNyCdWTAhxAUhvPYUiVdSRFjlvQC6MjhLJsbWfxuyYzpIg_mlLdfIG_I2unrrPxqaXUT2gIdsYkr1fPU_W4zuXhP
WHQpeJwrdadlfScGdlGIbb7s5BxZBRQvzI2zmhK7pPolOMUPUVMqvXpngVLSUYFLVc3O7r3ACdeA9jI3z0BZN2DAUca7fM0HFPKUDAPOq7idMoOVvJeizBy2
jaM3dEjX5hqEkkLdjBh3v7fz1Zsq0dhiBj7DMFXI3pTg9bpapD5Bu1io1_HIpeG7xWwr2cjXIz13H6zikLlFM1yLA3wcTxvlhjBR3hMhyOnrKO7Yethd--Po
FRDR-0gKddiZnLTEp_nq4ael_SmNxuiKlRV76JniKdhpwe4T7S4BdENozSnEyh7HlVZrSt8sojMxSiPl1VGkvxE0tg3XrpdtzRXdoUiiSRvylR49yEqMJz2h
Ldhy2FFrHk3RmFsDdYVeaP6zKF75zJnq1HgfUibu-SKNrqD03-ER4lH8nvGkFexrfPu308BFyVnIBwI9WdeDuL8xhdS-t8flMGYFymLwS7Azq8kt8deklQAb
nyTPlfwnysUk7f-Fgf_wudeXY7GztY5rYgzDfcVfUgNm7EsBuurO6PiM3qF4ludlXWHqCDVdislqGjrEDaIt9E7byqsWPxbwV20NI3jmqDcLnhTSgbSVpt60
BrVFVaElRUD5qZPvOksX71uVTrYpzepfeMBbyOD_Lks13D-oV21uAzPUAuV7-RZVUhN7cxuStv9hJhJYUBmPR_ZS2zOUQGDlzHfy3SvZ-NhntHnlijSCMj0l
LerNxuP_IQ2zw_XzqZk_9MKtsr2xmdpJjidyme0tT46-1byeQ2G-VUJN5cwXeR40NZn0erbcOk616bQwcMr9EuAteby3K7N2v8Mte1yFwZUalXqFQZQRq_59
StK-7W2LZzxN3HpjK52fujQtuqEOfvBSc3BbDyDCYd6OaR6c-NEJoQgDJvcgG9faDqsPFErC002dkG0GCbLTOB0dz28INbLJwDmPbQ-KetE5BD0d3shIYH00
tE4y2kQKEwYcO2v11EGK09XWfZmNlMToxKMb0dSWpUqcEvMXu-zSFK4cJf9Yj0jMg3v35BZ_n4GZ_y3_JjaVsZJp_hSzE1O000006EHlFOfzrGy000000000
00000000000008
}

