sprite $205H [93x93/16z] {
xC610000082W_QaNgG800000000000000000000000000000000000000000PkzEbDpcSIq04o3h07x_1xvtfXKF4aHfMcfH8glE-LSlSQdy6U1YTZ9Rc5fX
TmUrbX-6aGhprqDnL2N1wIZWhoVZZhCbI3iFk-Vyx8mVxLwpvA0V8_3NF74eIJwFch-cYYzOVYoy28Gmd-6zPemfQVfHsvlu0O3Uame0xdwSZr7FT3WnPz0g
r-yJEFaELjwfvRB2hwWKgNQi-eXtQgekC4FSH4mJh_Bhyp5YVzh9FfLxg0ON97q4K2v8TV-iUJBehR7sAwlwXftqpbTVRiCHb1mc52AsbPB2qWp4_zg-gkcj
nQLhRFdzihpBn-bcT4trh20UDBdXcgOLerxqgUfs10PfQoFkyvgUbgglUkApgCQh-OnGtRT8oXRBKfagtoT_37rrmBMn-FRYEvFD6CBs-FoRweF75F5QFfVo
JLXw9ccKEyDN_T8n2f_DExdKSqse1vjdsI9wPP68vmzNXAd_-cpNezNdTNHlgEHAiVJH_fJF4b_M6z4xlUHmhPUDzgNwVAw3Bp4l8ndalYcdcYTUxhZd6YDC
AhqAGpt19tNW6MZnJklaSi7_TzFgYPddq5XdkunwDNgKzwlltZbyxUXnsAknzZl0Tu-U-BS37vVg9e5ve7dA4vUPmmCHYCdvWUfpkQj5T4PQ3dj9giTdSVlP
WO_RPAv7L-X5LEN-FONlzAZNhxwKv_MePtfWUtCwFTPUHogPJgN7sZknlVd8oWP42v9JN-rfkJterHxrFcsUc52FUltgMq2FUXs-QVMers-UNgVJevx0-vDC
1L3BT7hKmxWrmdWzwdMsDoVNerwd-cRMerw7Rs8zwaddY_MPzQWNVBxB9_FgKQ_BfpFhKQ_JFEl4UjJhL9_Bl7hK-uxFulQKUjGBliu1f6drg9UhBxA07lKI
tq9wrClDSoazwkNgMqcFUfbFbzEZNl1XEJtg1P_9UdhKA-9BrHxrj5Rf742QLOzwy3-r1C0YSqxggNVM21FhKQ_64cz1FUe5txfwF9M4zVIe9y6ti1vF9Rsm
iXvF9M4jFUebFbbGZwUIulZcIdhKotowcXxrulYcOpqzwWMVhAT7lV9kdilfKI-g3qlgKQ-ekMFHMGlrYbHTRCL0lPg-Zbr8Zthm6EqMqwEUUYppLjEZNlLO
fI-dnzgpsA5UK8_ZthhVpb8lpaReSdhKY-gho-bHBtQeLwizwWNVgkCUzKe5K5RJezwPK8zwrACUzQX7FH5fsjv_YyWQUjGJRGsUOcYgChSUzRG1vf4iABFg
KKzQbiinWyfyUjGJRVvHhCbaUjJJL7QT0XoWHxsnTX63JA97FOKVZZMPG8zwqiptWotcku7UhqUzVk6PeSKANKIaDJFpdFQm7lMQxQpg_Z4dXNNAxrOzwabB
7db1dW6pdpwcHpr1AhlkKbpoxBJ9CthKKpinYyn-aFlrg9VnekxwVfQgxruzwcKyD3czo83ShKSzjPzidIWItsrwrCjuJNusMsrofnxr11vuykCj6iXzUjGJ
7ErxdV9jz-bHhwMkzsC-qnlqg9VnK5BEyiazUjGJIntl2Zx87NhK4wIt_1g-TeSUzJIrkuluJCRhKK_i8hmyXcAy7lLQBDBB5K7CEqVhKK-l6_HoBKC6wr4F
kMzUEFIrSNhKos_rHP7qWHYbHpr1QdFNzauTgKSzjPXYN9UO28tKervBfNTnyPcEqwEUfDdzvSNNnkbHJzFA-lhYas5wr4DCBwuDelW6w56lKo9NhVamIezw
Qb4XeufF1kbHhwKvouXvYuxHevvWm78XpsRR83tgxJTE4KatVx9TXZ5wrDETxYQj0MZw5jElcqtU3xwZsuFj_L1vtvdFTveCqQDUlC5_7yh49j4iRlvzxg5v
T5rBDQmnfexGervgRZjdSeCBSaWlshArA_Iern_sn3tItfgmxUP1FVYMCNhK2udefOucehQnwDUZyWLXiccPREdfbNlqg2Sb-9e4oo-jNy_KxUvurOvUYvvx
XnxrCWj-QGascXP2VJsCrAEU_bjlqn9xhoOGUcYjgOIUgNp5ifwErADUIthf4ItYl-jXkpz8jjkHh6Stw57FP6_p6kLlFNX0oHHwr8Fih2HC_jQJvcvcjaaz
gaSztTSJl7T8ibuHRQggsohmbvwXVMK6FTPUu6Mzz1H9Syx7zJXh2RoOQhx_9rNjL7hKotYX8uccJQR7zLxWGUCPMuVKZLGqfZKEcMQlXNijWUVjL-HTYR7j
QQsfDeivvnnwtALEg-_Os8nRwX78npjbPOGUzQoh9_0m-5tFT99lYFZjhCL4mo9VGDBiAqs-GCpUDpTjCtlhmSp-qBEXUjHhMK_qzqZS9_64VFFz_zlz4RLR
JaRmL999kJxD1-jHRyXHwjoM1-lnD6wvF69ZptDIhmmyIwrtdQNcpp6uBlnJAFm9CCYunZb8Zth5Hiqws_YVlgHU6pJh5CHwOPGUzSJ759z6InwdHpr4yGqf
lLQ6wL4l9lQG4Si5am5wr1jMVFb51-fHhxG18r_pTsIe7lN4_EhjCaqlEKAFUhdusjLzqsIW7lNoctrntsnbW1xrHlxMnj6AJORhKKyGV5SEUgvbk1xrYjX5
Gr_-A0pMeru-IlPJli0p6Qr7lSnd-gFAQvxwvdWzwWakuPDKnCFrg9Vd6jOk6FCSSeiUzJAVd-JJX7UR7lLAvm_zFUPlMkxKevuqZq2F3ta9xquzwXM1doy_
XIUyE_Meb_dGJXHUuDsiHxsC0Fsi_aJD4zvzUjIBVF55Fl6JXlHholrwr8k9OyJGv92TGyfJUjGhaZJCeB8l8j8ii6EoyvWUzMBmYnWq2OgeHjMb8UyvFUeL
qM29683MzBzfQ40Gfwxvd1xrSldbMEgLQRhod1xr8WBpOq6JCeCUzNBxxCV2xa4zwaKKzY5Ts3sjHxs8j0vWRCbCeqUzY6X3RxWBkvdqg1SLQEOvPcXHTJFg
KIzgi3NWdTQQXjoyUjIBo3lXje0UzJgX7lKM3lKOwb6FUjIZ7lMeHptgKOzwKgikgaSziTVB8SlfKIyk3RAS7lN22xAa7lM2RpqzTixWMqsFUWKUrxQQ7lLA
tVZSP3KzwWKVLjEZNl1vNR9pKgzKcAqsQw5UH7MjzHxrghc7qb9wr1EBArf9ZtfnKOxbzAWNKWvPJuzwwgyjfWlgSTRoYyzDLjEZNl2zJ5RIerxcqvNqg9Vv
wcfwr0i-zxgW7h-TjTUM1NUfgLSq-9RJerwi-x2U7lMY-fRJerxmsI9wr5D0ImI-phX7lRffHG0iCEUaNhHAJqGhw54l3W7M5VLOUnvBlCNqg1TANjVJerv1
LDzAUjJBV4lfKIytpwNqg9UhRmazwedABjy2UjIhvbRJSTpWcrgFUjLJdrGFh5drg1SqcI-gRt8zwjchmpUx7ZjdvlFWcrcFUWBlLD-4UjGBljStVAPpwt6r
_ctrrPuUzQRaMq2FUftcEQ4UzHJGRlNvor6cqgDU743gy4d5X2i6wgabgTGy8rFfKI-Mw9tgcrYFjTVXcrAFUW7IQPwpwb4l5zhvKqdKCoctHmxmsNTwrDDd
L-YTEzM_qQEUXzv4pNCsFTQUg1pWcqcFjPSF8FMRPr-FUg_wq06aVlNbwsGUwqX8KjsPf_wpHp1YDo_uaAHwpTCHloolR1Yytj7xEkU7pJFk4j__a57lxjPv
ZCyb6YVrzcfXYyssGXTuEisPU1dnyVE1wkxrHFL5uYA5PFkj4qCN2VXUIhxZGtVOuuhFTUWY0IUQPvuOvy6PiIY-eNgEiyqpseEJAmMlGPzioOk4atpgd75s
jbikdnDKC-YVA_IJpTC-w-qiFbpxegQv-kJ3wfCZbyT5GpItQ-AlCtm2ppsyUgVqM7pNy_a_VaD-o4VDKwElTqgFiUlvBDLBVIlKt2T39Uwqr1SuuUoifo_c
KqjV2jIWIdoffc06tRkmIgZzO1XVl1n2C_N9n28YkMrcOoRlPaHChtnDH8Nl59h7EY97el92_PjmtdbbarBBqqVxcwfMBVkfy2ENnA4lWde9N-wKgaTEwfx5
8vzRbGjUjDPpxc5t18zy4KS0tXZH6dRdySZd1jGOcKP7wty2YyiWtfarMexVazVBG-ue7YFchoboPlt2I9sDpo5aEJ7Rco5-j6ko_8o5n_PvWPqIuqmg7W2y
RBU0KS0Vf0FjVhxd0RjV3lZ_zk200000105GrV_F3X7us-a00000000000000000000000000000000000000004
}

