sprite $205H [93x93/16z] {
xTZNiTr854DHu5Xq_W7FI69T-ppPBSlzZLe10BzDPsTdPsVqVBtmmtIDTqeSoJH6XLzAlojgZCR-E4RH02yWcZO2zraVqNiKlejKWor6uZ6DmCvi241STNzr
iRCSwI8slV1Q6iI-QXZwejiR4z-D4vl-9f47SCjDTrk0kshJiG2dgO2oDJX-w5Y2cy74HNYC0B08vwOlmX63gt1B4CjmDPRXP2p4yP2vkot1cQqVbKt7G-fm
ioWf9-EbDconr9o9bnAtGZqHzys-qtCQpcuyLh9PUEYPe6eMNetdIhDm5LZ5AijoTnGGiZaubG0oljj1Js_0vRFm03oPbkQruJOFJrYdLNbaUg01byt1qGMG
0442084K9-4bugbkJC9TWSTSCGj7YtYeczDmKp_efS0q7A4sN68fCH67IycDZbPYAWuhgJEpf7PCnW7BbjJbm6nyYmIm2h-q7hTOYOzSXfDco_0KiGn7ozRX
AAt2im6kmga6rk0Le7eDVlb9Lk39JVSLU6lJSGGtl9RVzDgDvmYy4aTXquKUF7AWFQU4QTEtnTvw91wYpCT5xqFN7smywoMu02i0P8_6_dmCfTjTRfUynX1n
8ElnJeM3MUGR1V65pixEpix-1m
}

