sprite $205H [446x446/16z] {
xC6n00000C2WV_x04wa2000000000000000000000000000000000000000009YzErjMNOU1C7pRhVT_tpCVQgCoB17isDhrzrt2vDA778Vnh7XVufiGooa8
qdRR_R333xhvVaI6Zyx3ZyRx9m9c3XxTnwmvduzCgTk4YKxmVPufDPjJQWk-prApSzwhvsjEgxNW-w9Q6byfbp5TUsgjgtp4bL8DBalNztu-zFJOftX1DMws
oRNMDthWsHuMSrJVl3rzNF3LyU9TetbqoooyWGyzfPrbFgMRpSaLFV321RxHFYtKK-IGSNraVpLvhfdMqKgH_GEKXpjVYbgMrunFSAKCcJ9BSVAyTO0vp9iN
-DRh5VbelI_vOc_peMVvykGPYrBL0y_s5JwjBArAVEWL5faxPZBqnXdWVTHzEaQFrbELxsOzmJUAKXUvmBT5h_I0B5e-x3uTSk3Zi7U9xpGzz6ehJzbo7AA7
NhdxSlRheLVbEr4FlTFuwdheAKxc4tnlzIAEvWFlafvRwQ7tcgg97dfZldFrqAkiF0_LGq-kyiLfUkXDM6HkrqFF8pqtqKDlt7rDzD0RypNGOzLIu3jF3xqV
-NIk7de_ynsjXvuJNoSzzDvtdyxMG-yzt-bww8tvPAl1cXEzn9Toi1vwcQ-T7dfEV6tqqClTrqeFlSpNJW-zK4izz3AVEkcXb_bQwA7tt6cjPaxqnkTzqKaF
FKTA9ptqt5aFFRkp7dhkhCUdajnC3xt4rqeFlSJNIW-znATMUkXblivwV2h9ZVJGotliHdhevNtgfuTUe8SUUhkAqddLWbwesna3UetVtqCl7Uqwwg5dTzP3
pvtrq5DZFVJiRdheHMSzzAAp7dhHMG-zYCvww4MfGkXH5FJGwn_qq6EWwDdAiHleeMUzpjbwwEcd7Ag7dbMBZzD3Jn_4H-cXPtsMS_JGipwFpz13JzToW1vw
kXplraFldSu_AV3jqKFFPPKNVllqqDCe7rrxcnvwdpVJo6-77dfMpZNn7NheNMLGplrww2bbratNww7d0i2SMy_NG-yINkNsw_NGAomqv_3DrqDlKFal_NoN
7dfEU3Fuxj93BpNDRBxvUkZDnyjyw_NGooMVnkURzT2BcCY7tZozzNXv0UIrUkZbSi_bGs-YtlhMotUuLWyzJy1BkKqFlSbukVbMwg6d1Nfnlnvw4Glul4uF
FQ_MqpezzDRWXU_LGozIfZLVEptqOhqUUhf1pslqq7EgyHg-vNhqNdJJGq-_XHvwUNVQT0yzzFAkfqsbRltrcg_kHrgXXvvJWHDF1lvCB-xHGs-C9sMkZ_Iy
LWyz_Q2Njdrsxw7dn9SrFz6Bc_NG2p-n-5aj2PNrT8yUUk68hEV3zT1ByLFhFROZlxAcb8rwwEMUUgCd7QM7Nhx0MSzEKWVgeVVOcVNq59-aXrx6otgEq_NG
UzWCz5uqfst7JZtqiim3pLdleNRG6GDw6I-Sb8xKGo_lybWfdUQThCUhr8gtctwlvyrwwFbfAsDMzRn53xruSuBWezyXujrPPODqsHbww7cWbuKU6tdJk_Nu
LDBq-BVGGy-BzT1pvq_ZyZq6z6hXUmpeyGqmz8pUxl3DP_I47dgRVl63Nzlfh8UUk_tI5Nhk-ZjbwENccuzdzERfrMlDhwlosxZkfCUlYkUxkrCFFRVwHN_q
Cb-NVzD0RpwVR_ud6_HopHl_YnHwyXmyepTHRpsVJlZ_FVwvr3FnrkkXPptbQpnlrEC_dptzFuFHMraKfKp0Gs--tdm-fVXcFVGoGXrGEPC6Yjual_day_NG
2ts6uS7rlKiFFMkOxwwAtcr5qQkuTgMTUkY5laZ4NZtqmheOnmOzzERuRHWeUiFCQJpqTXN54-pGsrWKLRDXeEXDyjimKFIcpA3UC53qPlJWIGD5hqxei7SF
53q6Ib7GGu-WXnu3fIZeeOSU0qKFFOeYsswaXrx6iphfePU7favwwEMHgPKUUfcliHvwLcCzzDnA3xtSV0tqqClfh8TUT9uvqOlEgnRqmdP49ptqqeWwwQ6d
DAGMUkZbGNNMGq-DzT2pE-kXfrPww6M-LdhePR_EUkYvbHvwcS-jzD3BVkYXXzucltPww4LdFVIYbnvwpuDfTTn3ptaq7VNGI-caXvxTMGyzeuSUUflut4eF
lSpNJG-zwAg7NkPp1ptqP8tvZjT3Buz0xVJGiuVTrqGFFVEv5lGs1BtNVYVheQSHNmCzz39VZFXEraDlF7dsqaCly_NGGo_KIW-z_BWU-PsfXzvOAkzKZpKd
UY6xqQUIq2jCdeVheJUUFBlfeHTgeyUQip1vbWQAdlQ_l5at9VkhCfudrK0FlLgZeLVNs_y1fBppA3tqAlEapjH3hp1FfftdwQ7dyifpE9UINBeDUeN9C-i9
j4UyIwz-YlVwIKOswhcqKwLHedVQ6ReEMBHmu4ltxeycpzXxsEF8vmgVNWpZgDP3hpvv5cJHMyvd-_hakUTiZ-QpqWDSuWElhgV9zphGAqoUk_MOEptcK_6z
8HM7HxIYFlwGBmzb9nxDvvTyjSaJl4jwzkJxhBoy-UhqmjgX1vyVKO7lrRSRV08UpJTUa6ZuW9AkZuk5YptrFXF5WBWqAC5KvVF4xdj7zUQXwYCYzlng3MVA
UvvEy6dEVNuxbZeUVFkFDV9tUF3bz7jy-FQdZaUipdZaH3x1KWsDH_lHUFXTwpn2t-7Noeu953fwaAB_sHuS2m00000CyhSUm_xg0W000000000000000000
0000000000000000000W
}

