sprite $214 [93x93/16z] {
xPY7akog3aMt4cZ__mUVq2ghobEKQUQzctkTC0ve6MGp12pvyE731r7p63EJJUOS8rpbV_9QpEGJELo_POviGxYPgaYXQjMOw_QftsR5FRTTBQgSutrqafmk
U0SRHtedEGHl8vxaV2zWN2LD80QW3b67K0LCReU285FUSqV7tUIob2jWWEOxTYSTW4ZBNLToCxHS0KXoOeEGqSU068np8HUo3hkwIlesAHDGQR_1sNBX_2fl
jIAOsueRfEHTet79bUoqP9kwFRcfkY-UBgX_XfOBLiGcw_FnuSBSD5lm0Ac0cGcMg62DcIcGjETd0n0H758XW_5GnfZu7mYEn_SvgnfoN76fyEsZxJT7Rlk5
RXg-ITeM9R_z9Qf7kCb32pPo0o3w2y4T7MGn3L_GA-3nGq_gbNF1ZL63QSGacOOR7P3KZNo19XcAmfECe_XYtIpebr4iohwIs-w5s2qlgt70I4UZNNxITt9z
WMQskx5gOo7zGWVzw3ijqMfGEUmdkknXSnKXNBsxsCkjG6laiP9QnNKZjv9BqHSd0CzqG8S2i76LBReud6CZNpOrp2b66Y3aggllvRDgKbpjDrJEn9G6p7Xf
yygM56_AhT3hVPOy0m0DFlGcbov-d9QgURbBpap6gZT_F-UJ4VAIgpgrStuir-AMg_Y50g409EhohOEglFUTQx7xplrKpdsVxgAoBxeVfdJLqoV7kZcdlt87
Kt0dkk9TNdTZS8N82w39ij_SXk9MVjAEXpd9ksoGlezVt-oAD39hqEzfWA7fW9sycjKf_B9yPCunkLX7TW0ftviK-TmknuNyzdHEr4nbCvtRJKIhlxrFHnXp
EuMk39xESgN2__p9_pvfUmRZVC6rHryXITik5LKL2tfBOO6eoiDISRDErG3c1EYGSR12ta-a372st2YGLTkIWKSc9yGKZLKkd7Ne0gL0hKuRCzXZLdfZGr28
j1oAHj7olYgGRSM1wCIqOh57TBjJJ2QspBABtHHYBL_SwR0TCcieE99h3oSxvhLU4mMqyWq5v7POTtfeIZtOM4mNl8VDitr82VvYkcA3-dYLL9mWdjS-ytg0
4FEOFJGTepwJB5uxvX7k7Z5gDxsOeV_B5lf8BiaPhlZV4JMhEbVzArD_Apvy-F3Xmqy
}

