sprite $214 [446x446/16z] {
xDI5RG0n30NGvApG_WCVMHMNkNqlC83XbnyF00000000000000000000000000000EgM8jfp8hPKlXLnQkCo7wovhk-9Ttvft5gSQlbqr7hjMBJJNBTvddUR
-RVJjPUrrlAHoAPTIxO-sxMJsSVoNcmHcOph2ysLqTg4wi7UkIX8ok9Gc9CenFT_uTtk-UsPhYEMM4Y5ac_lpeubVYH0l9q24D4vBGwmDAi83caSu4-IjCKJ
zfLELNOL3dIcBEa7Cqkp8X03aJbvrSQf53yE1r2TRUc8do0Sw5mlMTfpwlrGkhb0YBwGBXzA9iUg9j3_ID-GqB9Lljrt9dDItRSm_K941AyNI7zadXi5LSFz
q6HMFEDRQra8jS5QXokVzLgQ4Mu4D5c1jEzGQrq0drE9nbbndunvU8ciAeBtNNTIrOE50pELExYRpGujYvrK-m68paVIlAKFzmT9pyIbvBGsh9gUEBJ551yz
KtbIn70-0nVH9oMXzAd-9DcUEXBd543tah-PtYfdcYML3rghVbx-b6mXqtgzyY8xnTbPmmUXcLJJUQqGsS70qkUuowhxZ9dO9wTFR2UOD0i-frxxgSi_JTij
G_WSi3q4cdRVheMmJonAO7CLCUFJbdWsottAjpttKp4xvWwWBU4fmFCj3C9bFmMrpycUK6Dt20peihZeqsj245ML_Tqmz9TeI_RuQCl1wRKYz0YFvBFitAn0
M-I9XyTpIhjXUCT2MnZz1eUEJsRZ7li9gppJFGyAslBSWqfkoz6VolubtZ7lvjWasrA_aSTT42B2frJbZVOq4Fl7npyb8iZrsuJEvINvrNJnPKzUjlThlp8_
HX-wJ9kS-q4diFlOuoE66YNFNYFFBDFopuazkfyKgTlaEHjbJT_sjBgzWDdwJ9vgrErk5tkiJpkHnqTzmzZZNjo5FYGwvfl5NhuV-oVPReT3lx5NViHYdPMi
bRhRviaeMkz1OuoJj8WzqHYZei0UrSxo-kRW7B6dkK9412Ns46blLyMUnEMBA8Ns0aG4JoS1sjEWfo5BWJr4wWpLO-_nf-AHuqDvTvRWcVbNWUMWSStaKih5
yUhOcvQLwNcUrBB5h__S2JjJNf37ZYoPKnfnSUn5wYXaZuwuG9_pUMSwboKWidMI-PJYujXR3jeB49mRJIouHUlqilRsfC1UEUWYToBHeFTEUpB5E4czsAkp
YZ9q47e9xxOtsQhXtR4NC7iEFauG9jJsnlQKPeyDOm-YNmZMNVYVkEXM1nFz3sbiBrAgAeqzkfvy75r1vjpu7lM4sb7UUhnY3rGpE1rxGSfxtufipJkTZdey
PG7PArX3jBCdk_O2H11EsTEjES7iE_GIpjjZfXVjJSTZpyWUKHvxd9dWkZojMmsfC9x6S77iJQISA1_tEFZKSuNJjchG2AU9D9fUDUx1weG7Q9vAkSaNrBMg
XxLD8LoKEUKXGaoldHU8t-L2_MF3P8l5txkj4dly70EYBJP9k83aTzxIV4g51tadxM7TqBQ3kvspc8O6q3I-A7FIHV7MjIZncZXJQ4vvxBs5sMlgd1rCXrSp
PE_Hi3YePo3u0HwE2wiyofpqfEpR2ngcFgjaAJY0OeyOgRCmSGvxOYuVId6Oq2CLHntWSy7ki0Ya7ekAiySrWsRoEVGN4bgYaSfhRH3zHUv4EUnIfZbvxTTP
q6cQvAtog1va3ksbxNGkIWsv0Ve8jjSC3bTx2Nlsz9RsPFlcClWhSiwP739YZmO-zRTMrz1Wt7CDzzbCHrUFanQ-nBmY2BT0HFyYaajJoP-zVK4391_s2YTI
0vwUUxCtXy7XF2K-fvnv1chUx9NCWeSzPoTBZvHU1rmhwyxUu0fxOy4mxAMdzWQfsjaQziRPiftZ0VF1XW76-pYJlruikeLygZlT13vlZc1xIisvapxDWEpg
sBKzqGptiYSvU-9gkMT5zeOzzMLFXZrba2sskBONiitvIEJGA8_KYxqWMuHF1RA5x-kpwKUU8H23BkoL7ysuFjkTlO4kFmnxmrwjPz92jmnxYtgT0QAVUoE6
FL6D_ySihl_uFwhiS9mmzMLFfcZBDcPJrk2mP_hsc2DpH8mgmvw_guqKT3aiwhZzzSZY4pdg9qnR2h09eJB8KR34ycLFD8VKVaIz59kaSjREWKxjGVEWiJl6
ehIGfugyFSz5Lr6zFlY4tBqZV-eEahLdZkpDRx0dq_8I4nhQusmbdTf3gC7kN2N-iEI9sZnpghcqrthM8Zaj5gE8u0SHYT5o_d1jy4aeiETgzGBP1fS5diKf
5qrGKbYXob3ILBPtruVt41ScJliT0ph5XR3fhjMfzhSdvhDc10vOrys_wI1TtSUUlZBz02VGAEzuyCFkQK-DKYPUMsX4lUCZVFeEUnFDE_3oi6dg8FRkS8bX
gZ9gIIHz_cEl_uS9frevRo9zhUqbtCtULA_M9V4j-kPxscDvfaxsDkoLppQZrYtO6EvbRp-7YsOHX1E85KnNckqHeZb4FDlRBPJfBdYrF1PHlseJGpcYUyYE
FHE_zaJt2SLKbyTTOWgbGFT1mHgv8ti8XKmahxu-azhsn45btq7igR6y-leYheuzwIBsKDaUdUDggBsIEtMVu2Ns2Wz4gigRI5xbTgpK3Ju4jx6dJyOBv7bb
Qbz_hgOlpJkHfw3B-x5NdxXSsMXCb3lzl66rVtjgrvvTnALLMv1kPy-khcS9TOy6zj8zx2dbpUfCL_MF4Nj6aufBS-Tq2tkfaRsfnVrVIi7tuPcpqN4WDfba
K_3T9lPIer4ljgazc3InPtUmHw7NwUzmPxo1FHYDUfS7NxozFOZk8YYUisYpWWugNH_grHxqAIWyfn7DAZhnd3ocKtkYJv72V3Q5Qq4ij2Vw5DpRtjJmYeeM
9cbzZlYpnmypNMUFuk52K1Zd-XnqO4_FZNk-NWrLtbL4dnBwi5Uk3uMrL0G6KxGleY9ttNJdYcfXvRPSds3NdlYnns2FulL238H6UlyAJq8qV-ZAgRCqqh57
mMdpPQz-BfkUFOKNXTJcZYtxHx5gasvlpoYLvHzUZvlFA6W-eBKWrCiPzi034HVGDi8JUq4aUR4wx5M3poR_aSL9rpYBeBZSJO-wroOCUw_0cOprcUBVGr6-
YOcFJVSEEmvxLU1P1AkD-6r4wVu-_ej2VzHWsZBi4T37Ovd-ZTU9_o9VgSy7-pJirRiVwT2nwD-yQOhrs5XFp2u5zOtsXhrLK4HOxN7UD3bWBtwsFIsijJ3r
x4s_LXNnIzwFFKx54xBsfE2k4pp3ixrvlw4eldvIU2vvyHT_3OYhFSwRoDiBn-tf0T23FJaXZ_MTpsCJLttPtfekJ48DUtg8Jks9QcddF3s7K3AyRGzntTNh
zg27a0upPtrxyVa0RDYsHtap10nxTEdjJR4dT2uozlHldcXc3rtDETkFUuWFnq3sA6-s6_Uar_KUv0LvRAzK7jkBwtxEnbvvTf5RhzQ5x1sJn_RMVKtoJLp_
1yhjbJDgBKNosDuQRlQ7PVqV4SKhp7A6lK9vRC-MBKmQrpc7FPRdszwmfoNopjkBLzWRrzQrK1xRCrlC5llYnvr5QN1rTjYBENbH_Y5dx-YjdXXtHbovPE0e
iN_1CNiXlkskf757O7uSmudO6tS4Nl_Oisb5Uo6-xsvSfQDrQG_x5Dy9to3sYgUSsCVZS-iS5-bC6L3AUch4ANkMjsTQ4EhdIfsuztFh-Jpp_5Bspgy8_H7r
bTVbZUVMOPJB_3nzgS-HkzhZ4tevbPzy7lQc5bCq_YsvzpiZWZx5oHkCpiSv2ZfeP_Q2I473NBnjXnBdYz4d25tOSt1EgoPEtEeTWGYNWQLHyE6273tUR3nr
_8R7yLPnNPha6haYnaViXPxVR3piQUktYaiOcRCUSRpHlsDxqlHh6elSxJj4xTuvRBYwVqpjFdltJj3YGFWJQ_rzHSh_bqiPI9xYu2kBZPQxX-J1hZrnR4zq
3tZwUkBqGcWN57CfzcxptTbfkKwVlhBlugy6t_ABtV6oeKyeRrxvnMvr4tiq-Isnv-MBtK8xljJUJALz7nSPwcTExhJreq-CycRLpEdH7Xz9xLaBCv6-Iccp
99SLDxDJUm4xd5oKLK-UOalve5VUJF_sheLFTPJmCchK8IvYs0kwa3u7-ol37Dep2UtrBLhX6_aKUGtdwItnKFLHgnOk6kaHw66lRVIPXfDCHd5yCtjAzfhh
MwAS33oIrzYUtIdsE7ckJ3Yzo5k9siaZg_rVgzBbWJWLkZEEtrQe5INzpxj7WzFUOefm353SqMopbJsvfxqWRC3Y4O4WyPaAox1NT66zVAd6_YPv5hFahaxE
X-JerfvcaLfzc8aAX0r0KLTbo2jlQbeyshEIsZlgPKycnabLHB16XKuJ1HrzCBEKygRoSrVlPZvdJq85eBRaC3EBtvZPGbHUAEWECkmTkMHKZcNT3NkedpaP
ZROKK3jfbZSLJkt9yU2J-ck_SdSIwY67-waOsNFxKlzjgY_-ciTTGLCT5SgS7enCLg8kahi637jveD4EfqouEs7ZO21F1LfxTLxlnUNN1BuVcM96eSKOjR4v
XwztTBXyuVbV_6AjlFoflHIO6_OSK6k2E-mDU87ioPwPX47v2oEwVF70i3SFUxKOiQT7lfue21-Ag39IyBeFLtULGRV1VUInFZvTJXz-5iqGFXBDW8xj3NlY
z9K3V5l-iCVWoVLGfu-kGxUHUurxFX-zV7uyk9EyWCoSirTxp22vjMV3NlbZprq-mZVipS43qgUzOOylzG-yFxnNgN8txFclcW-SBjRBFwipI1Kcw6F9CF9K
yRHb8ERFdWrxvQTgzjwXqA30wRrQBV2RfhXsH_Bkfa_qWUqfmk9n8YNKZhlPqqVWU7hEDoRbxUajxSbcOICvjBVCP6_4NkP4kM7P7lYe7NSSzsHxsDFWVU0B
GhEl6u1ylZ57TJAV6G7niG8ijcxnizfBS5b2iFVB-qBfAtFYSNRdxIAHYOip5EaJ79EhShu6HynlIvqonGbipy8FaUr1uuHt9av38EwMqLTPKGhihPjika4N
Bq-TslusaSXZ2zkZN8gtdQD5GnYfao9jB_PeYxvjOcx15zBcenGG4MoSaOBOeosquuj8rC7zO2sE3Vg57B1dHVPun_MH1eEBxxoWVs1NhyQUw3UDGY_1yJN_
HMkzD0N0bZrKZ3tk5lpZvO1QhHHwNkSj1gvKusp1zvoz-Aezo0kfLAZ8IQV76RevykaFfykzHVPMDKepTPJPanT6Gd2DMXQdSnQk0oqcR0zdUp3sxF58A_7n
NU7JkgN4dhvWJzXUej1pXcvqBvJROrTbiHUWWX1eoobx-g8ztKXCoUjzmZnnkTOUrrhoi3tKjyUPa_EIkhzPqKmU6YBX4dlJcVg0n3Nqhh4Nv7UNnRpyPKRm
1lUm-VS7UX0E01JR2nfZb528n1Wd5Di3mW6urMey9V0zxLpqLBv1WRqAbDZ3sP-6EPzmygAcl9FfDtxjdVrjfCNxX9DxcIMS6Uh5bpq-laePoVkgmMQynHv4
m5lUPaziSLpXp6U9PNw7FQ5pJ5iQsMDvfi4lVB3jxV7m1DhIq9vGTtRDJFhQsWETTcbhZpjpJu_rf-MGFeYgudLxj9iZzg2gWfVjGLG5XmSIa-0U8Nq52QxG
tge6PVP07ixPqszAJeL_rFQEcSz5kJtUSiGURNdH7W-ed3PfqFEFqcViBxE7L-oXZZqv9Y-5JfYNNypmO4yQszFqMvw4Ji1iTEGtYptemob0w0OyH9_f3UpH
V8Mccztgcp_N7W8XPfdUssVojAJv5KF_zhZjBA_VwEEv9zPJqQUz_1K_Q5fONkVwEFmW27tR2n3WMU0jIKE7S3jiRzgCkYUvp9xGZilM1ppLxFz5-TmKKtbs
RPqBMho5AcMqXNOi1tQCWXqJb3Jv6dN_-lYQRRxc2-hhl4LK5S-t2FqKxnXFjZohIMlYviwXOv0A_7KDrAYf_NzFShQ5i5d3Po6RpKmIUaVJmbXIX8z1lzmn
rCIUmuyJA4B_W58c1Tw7X1y7eFJkZcOgL9le7yoPDlQTGJMHEmgyZ_F70j5ZmfmjswHFSiUh8KwXNOMWw4vZbdxJoU5A10liPH0K2ZeQy3uKUUYod4G5S9mj
oHorG0FnsVcJiwY8FtEKBM-GCnbGMO8mipIhUCgLAL7CEIX0U2W9vXtEimZmpamfysncTk1WPmbt0LHRoc9fRlz6SeZeLy0TFSQPmkxp1Iw7CKlfosABmr9D
AN6yvKaguOP0arc1miM-HyHPHGIebbBnXOZESx8lbW8ikq0OAVHvCAhAoHThoXVwHVe_vmw2ekv-o2c1zgFnY_JDlFDg7_rB-iPAuup7Ea4Oh3dKbdFO-W-p
l_-TMF_Wx___B6OKT4EWw9niyOxPl5EJ7GOTcqj7ikKO22cFjeUBFoNUHXJEoNm4tCc86mfrdkszcV9LSGFzKoOsQvKcK-MfoU2_SaXATbcefVyAEM5mOU5V
jUQeQFEND5K140RDln8wfs_iBwpe7z8tlhw4En3HzHyw_qRrxv-D4pNuNtjm8000000WQ7_gHQe20000000000000000000000000000000000000000O
}

