sprite $214 [446x446/16z] {
xC6n00000C2WV_x04wa20000000000000000000000000000OFRERLbEM0UY3wvIjVh___TSagaA6Mq4Zi1OHYjvOW-3vKNRuBbDJw7_0FW41NuZUXdumDie
T1HCHdcpW04A0D2d6J-YLjWgYYNEmXqA0A89C2Df8PeCVYWq9omWcXYWGZSm3vWgWkME7q22nm3RXpvoCr439aY0Lu4EZoKmEa21Du0pLy0bCCVC0celmjM1
zW0YMNjNfYjj06S0VQFfotDN1IGjNJWx8DuuVgvpmWA1SdAoNh5upVKdrgnJtg1Fl181vYRpY5Bb4GlNXxnNPbNZkgaxAN11UU22BAVlf3kqrWHc2tsajGQp
XHRxn9s7WZaKf3KvcJ-ivEvd3NztJpDRBEqtVsjmJ7Wx-TBj4ylUJh9C_73sH6mVzhSuEw5d9p6FaMRKnDgtY3xity42y7e7hSDUCrl4tQd_K3Xd3y1k_6I5
M_HjwN3w8cQlnNVgpnusHK4jwPDdAe_OWnEZ_kp5xVszGIt9vS6fF7_ssf4-oJniabmvUtPBtlHXDtZhPo-zFZZjNZrx_YcS03YjNZzxMpBgS-RhzRFddyVv
eWTUOGy01cKF00BsN7q9vSNjwMz6PCyqkyjUHszCYJTiTg-rV3zdE7kXGtbRiDdWwKib3pI0Q4t8y_Rq3pTd3_ttEDlbRY5JwyEv1GRm7-t9pTdhN5y8T4c2
wF4KqduX9xfKxysURy-q-9yMdj94Z-pG9xITRAkV8NksnJu9mXSvo_nEndJPw_s4KuBmXK-ooxEdly35sOjtJAPn4_8B3C-UVi0zsVEHto3FsEc-6DlQeEnP
vnYMFVkqI1C-tSA0FOIoPvqFprxx0sqDYZpH2uGFWUpfXbZsx1rDlptg5fdT7YBsFXr61hAdqUpP-uE8FUgM9D7pxVd0s7iaUvQuFSqnwr5yUpxMdjoRFLpJ
mJ15pnu-x3Gk8iyk0d3kx5bzmXJXm_7xMEAn5jwRFUAgxZNo9WwVtpO000DuBvdATTdRwWEZcA8nrKt3uAO1piU1UhFdloWE9EgYwwCt0jFh_sPFZBnqVHJd
YPjHQI1jzcJVdbXxf3JX42HWR_c6EI_f6iCql3XycA1Tm3PwlZsMlIrJD0iVUKwByAGyCa7s-1WWCNL7wPQoTsuchZ7gdovQ86s3u9cE0iSYROlm3vX-H80f
um_oHAC83gLzutJKn0C2ce43mLF9CwIqrzh3-i07QCdiGGFsLWEdxUdKqQEyqHxzedN3vFSBRvJdptl8apshZo3Vbpwdg-PUehPbl4wVS6fxVelm1xu7MtHS
ttXxHTahU_U1ibVPcv_ANh68lR8dPSzIGsVPAtlIVaB09S7FvIADFN1BsuChWhQ3PB77S_PaPNcMcUs9ymh3cyANpPxV72IsL_OePU_07YQrvzS3BeYSckMH
m9wlZslYo4kIFKkHnHvuH25JzHSoHw_Eze2zifTtsYjxairUlVJXjwiwINUOsrur1g872EXGzXv3z2JqANlZWNPW0rZsEXPkPO2waG9nlbGaiTSy1WoP0_qr
1vdt1bcUjwV_p1XxRLvxJcUq4VQW8V2iFKnh3mFiGSCyQa_dpPxSRWzw0IXxJynxq8l0qAiM9B57F2DFdCUFrmScoTv8-YSouiOLK9p-oX-KFVWQ-gs_Sh45
Z_M0HNYIf_MzF7kYQY5YyZcCDsRFbuVuAqaeUy_88wuOV1-mXxTzbRyulHxCNuBP9dFsV7dn2rSai9SwUzVcPMZwAdiNfqNsz9KzD1TXDx3oWk02VSqdXxtU
gje40vtL9-n5sW4fxKax8cgFLu3eaxObxRL31lJpW7EYx0Lw-MbzE5DcpNiIajSHQhmbUphGNeUye3vUgWyvxH7DGMQHP_N9bVh0hFPkMo43EL7uaEoZw-DF
eu2yfwDTzkJkpiLzfqVPwvCNrrVsxkfQoMMlxEcM10T9Pq-oooDUR8_vwzKjwzl367jOR4PwL_Rq2Nl2syYHlNO8OjT6puTSsY59izTEyAoz-97Q2L9c3m5x
GNd3xBLbxRM4zgWR5hS77M5FRf5NzgWZvZtTCDlwWooRFQ8TWh0zSRj2lhQRjkF-yE6Pyp4UY-OZlQU8EEv-iTC-f-btNtLAR3J9lWO29rngC7_kjIUz9Q7Z
hvco5yVlJgW5F-xed1835jxVcZs_LFs9SrsaPOySR4zuNfzkSV8yeARAdjlJGc3p83keTYqHlSKU7x1dCqIOon3zeglPW-nLzgWgj1UHujlJ1-nLzeGEMtjm
xU49UvMzSstPx4JdBh3clVwr5ejSRMyp8HxOYsTFsY6ImfxGW7QAtcdFVnos4w9-wFe89zmZzjU7dDbh9xdK7ZzWkz6gCN_gI7kWlZpssaXx_jMbsKAAbhq_
u4bxKD-UZTv1zYfx66OFHxVb9dg1x0NggtdFVGmEx6qULjd3GJC6N7CQUPuzR2wF9MvFsYaIhxK0uCu_0EWwHASyQqz_1euz7n2WL-3BrreWHqVOtd7wzg0x
r3hd4ojbVlByx9KzZBKd9-J5iuVAtZt7yELDbRtAdes28o-DlSgUPmC7wsSW0Vpv4mRNLDbpvp77tWPnybpP6t6CYBrwHo1IslEpXte_vzbrNE4nCZPxOgRG
u78PcFCJOD8EaK30hxSt_ZD4wtzklTEUECFZ1bnYJ-gJpu_C4ZYk28j_TfOZx67a72-1WNEfxCaBldL0biqU4zgJ-hwM3v1hv17Zz0tvhYIao1v1Ok_VF5_-
5ZzFuFmBblDejVKjS_NTk7Z27ijUganGorxU7qZrZrBswbl5w_SO99UyieU5Vaq3zKisDqSFoJjjvbKGbML-HOfFWi1NF4eWV9Wfsz8yKB_ORS8nqRY9vYFr
YztT-aBFNR_vZ7QnFTmtzMaqUldjoQg_sBr-zcnBWB0ylvTb3dbOqXvvkJtfq3SmqcclMYJmZIq8TxJU80zqMFYEGMd17ZGyeq-kUKRiGwRCdiyK-goy10jK
YLi2_KAkV39DyAE5wUpvFOxBWgnybpsEhrtqcylaeUmza3x5k6U9WrVR8zJI7M0BCdHP_kidY5eaC6OEFlVUd3sRlaw1gW_9g-pv2hJJkoE-ijVskKkVqaFq
9ddIzacQlUR1AABx29ovqW86GSygTOxiYMylZXu24de8u_IKEeiy_-QbtMsFUWNWU-tnINk4HX6mx0NclKVpnsj0HwawdRt-y0clGXvnrrDgJdkG3ddZ_O4N
ibygcCMU0I3D_yi1HkVEWft_vCJsC4TZGErYjjEz6WCz2GW-G6NF1yJ4eRFsC5LhE0Lo-ZAbxC7Ocm68Y7mqYeY0u1nWskm9PmC4vqAcjQSye80cjbSaiYVj
1xWixGSahRssmyhkB4djjJsmiZoBqrtptZA8Ky_ibBsMorxPayJPAtjwxWLduUoKFSgReaVaUsE4__5Ph9myYvoe5dDdpwVG3OdRK_QOp5uXUUqLqB9NqzuZ
frDHsIjxQS9NyYfyPQy_UuWlikHVSacRlVO5tq3xPbfx_afdCu2hWsRvkQU4KuUl_G2NnorQDw3ivSeUfhSdxWicD5Jsvhpgn1lbKSvcR_grr_Q5y8twfhyp
rWsxbGW6jWNEbfiHsRlCrYJsdc-AtLBTj8DkcSmUp9Rg9M_Y6tzaT6PlizE3zYfyrjM9x8a-eKzw-wZi-LigUdReb7kNCeHTPk1ksJunXdVH-k6pTo0IJThk
gbw2Jyscl6wndHpFdhKd2SxlREE2xUIhipTWAG_6NeQXC_BIdjcnVOXdxzXUnAQq3mcYv_rWUMI5McoFVXYGlL0ORTKofpt_5vdRXi0usM5F75VdiuV8a05R
D7KBE1tw5nVQQoVizQrI-_RYC-6HFKx89FPep-wlHw37NZ1xAQ9dnquCiOUpPpF81xEdqqUFi6qaN7bnUppV8TOUHcLFPxTd6obVbPoprMiF6m-zBMMdFMcj
TUf3ZkZjjnBoVt2sv4vx101s0m3ijDUn78DDqHdaXThfk_BjnV7jnPSTD8azE0tDRW_jWyGw1KoaRxmzQJ_FdrTbJp97psS2UyvE0-mbbcSREzvUcykU_eqm
bJwubvY8szjsgB-JENZ0tcPRG5xUz3dt1_rRf5VvBn2q9uTXr2-OpPxwhu15xOMU9cOFxSFfhW2d8TRcTbMtZxTdjgmaZz1l5hU7zF9yVMlRauvEo6XFNsTF
3Ko36kHLzk38owvl_NbF3M1kVIflkUPKHrvUVSeDwzYJZi9NqOTDtoIrHpaf3yokpnO2X6T2dDW98NlYRB4rG0F9o-QlsvxPW4ZsnDaYRMyjjBTUPLAWF-Bg
er5pOcrRl2tuza2nM-mJxsn1vwyL2_EYsb4IHCHi0C4DtrjWt_8acwVn7WDxg2tmTxBg_95cVNzmDaH0u46XAfN9WMQkh4eKNRawtGVaslfKagVEWQkWIrOf
QxgpG7t0P0JgMT6V8gqw2zT33y4QPN1DH0sP70PRdn_eEPAOin1S6JtDz6USXSi3Q1yofJKB-1AqdtJjAu7ZOwW3sfKVaD0WO9mhcW6-5Bq6F7PauOi1H6-1
VtFRKGf0Cs77oq8pmMyAY6P0k4U1YHqAG83fg8cGO0-5w1n8970rbCf3rW0GZ5C0cUy62W3t3wSaxbDNWB-0u1SQ1HyudW8WINIf12VKLS3vG4JP-czxS2m0
0000CCZVUXJxgW40000000000000000000000000000000000000001
}

