sprite $215 [446x446/16z] {
xC610000082W_QaNgG80000000000000000000000000001WTkmiMK4e1W9ekhioiFyDFn_wXSe5vmkSJvKXTX5IwSs15zucdi6-w02TU8xgOcYhYnovJc1l
Tm304u-86bwj8i9v0i1UwN3kYPbPmxjLPhexINlMWLACZN7uh7DhbMYh7O2nGzRm0yQE2jW21r3kcSDloNGNOVST81-xv4-gatJ1fWu0FOS-f9EmYmFaKKDF
AbmmEq3vkbvPBQ-yLEuyGD3poQWo_haeKR8sYHBbyI-V33ITi7sYPpqs_qNAvIIUdUH147IvCXxR1LGwRNUmDhgg2dU1-6UlXZEvHrMjRA4Esn4eLeIM4HBn
wHLFv8eOGx1zeDVIbQFhcyCvIFdIXbfEspv5BMgImebz7qwqg9rMo3ODgbPm6QBz8Ygo5M496yuk6-ER2Fjbe1hJLcurFytKNUK2h0U0lEOgaMsFPWfEqVf2
PTLk-YTZkAFRjJtaURSeseP4tHlJ2EiNSBymsmhTstZ9-iTx0Jfi0t2pl0rjwA6yNI4tEgtKjdRpeD-k4jOrn8sYoh6JhNlGEiOShgIudrr4SLDTimIx2x09
s0EVeF79woxLtWEMh4_mTRL0ccpAA8csyXFevYSlEF7uoUfzKc0RhxnoDiAJEFi95toYaSrzilp4kFl9ykSlOVt9bHCqDSBL9vCSRdt2QJBYWXDZxiJKwCQ9
6v0rBTnwWserJP2OJq_jzF3ozDgNcjRGdjKArXLC2t3UUjJOPthJ6gRWDNdwO3t9vhIY4NfE3nfXmRGT7JzvIPjQ_fVorzFZahTVeTFmoc5FfASkqpDuzJbv
-YGyi-sdr-oUbLs69zjfUjEvswq3R2pwzl7U6x7-s3iJ9SbP70YZ1ClY_LzuepjcAsOgVumXC2MNoJr_p-663ns8m-I4d0js1bwGRyuvovtXNLhAj1umtsE9
tIfpYQS76m24MzFZDh1WDmfzOesh8pUCUss2tSPtojuMfUzkU-tuv2xBiR_m5hsmsKtopfr3zA8Nz1x6f-JYloZkXMvwOdUeLql-ImYjAh5oG8_Nrlj3NtHj
UlsvyHiyR_G22DvPRVudVR01xjqplNx9xdwNsJR6FJYBUsCKtKS-oo_j8IpRAsRZy1trJ1QzWxpJWZl9UD-0xw37lbCyHpr362AP7_TuVd25yQdd2gU6GH80
29-X5m109Wnl3u9DYCeJw4tf8Oj-SvOzN2OGgq7qS3sze7vTvmJJUw6HyVG2FHWlSPktW4pl8W6GC8eU_SNNQlTQxDoB5KvGRmxL07g3LMurd4xvf3XJZ_yN
hkmcQQCdbmweOgl5VDPROYaWoyNq-8XhcHxzeOijZ_CWzRd6hYN72Q9tcUhqI1FeIM7AfowdweO6sviK2QVJ4x8zSfqc7gVgLXg6CdVW4q-4QIgtcaQvix2t
5OgLS_qM2a_cgDpgpUESOJkNIos9ny2d9-SnIqP5ZS_BJewe9VMNjiZPhMHBqL_WYsV3tXBCtK3Vphg39TdT1RwUdQQBNdP7JyEnbZPlQtpeehVeHT-L5jOI
p2yzqAQmDpq0pvl4UTAfHNg8xyAtiuiab9OPTj_r0yJ82jyiYP4bhcjbUwdA6Hz73p6ou9cULEWjUfuhdK8rwkTwpb2djxcbjzNR8k5nnaSPkbDwCJn-nY0y
OoZIYpTUz5ZBwyxeIQXgoIszS3SjUjkYDsSRoTgIvAg_TFqq4xNeBQchKjdUH6zfSnLfsXQibk0go_lMxO2B7WgIRosHiSGrFJcW5ul2rvQdMMLwqLCG1hMe
hAaRJ6GYF1QAww6R8tgxb4nlyagH8AcgsakggjSoZ8lU871cPlzt1pc__g-P9SYYLvfyocSzfm1gkI9LuDBjI2mXUducV5Qc5p3Jz99QFYDJnSp0XuCTbBuF
CSYi2GFKB9-MMP8mMgURkdccDry2pQsoX31F_ctFFaKFcdjaYdMCwDEs1xFSALDv-36Y-DchjpZBzEy_OHxf8KnNEcAdB-Mo58lUh-34yCnC5O2y143LoCLI
k5wsDq_9scPplmWpo_0nUjjJRK_Kc8CcL0jfcMH9FhJvV7_evJyWTYVBc0Ar3oUVVkXzg6YNh7_s5g04KF49UhPxtiqfE92CXATjVnsOFiQigxDkQtlnKDtu
vBtl3TAHhmx3XtYeczABnq8lF1sIyqDj2BxsTkuEZl1H_ZI9dkYWa2KOWqzQsnaTqjicqTDnwIBXcqDlkmKzZAR72OkcG6gHsW1yyLXo1zkBWOJBuM7SrACV
dw0Apx_jpP-ag_Zv6_rN5rbnRiKLDhQ-p85K7HoVzNTetMb7SnARdadlbl0Ods7HkznlcburB4mMFT9W4z7hnaLQz2vGegd2HVWmZzxsbEi-GF0kmoVE3elV
_mYzwBNMeJOlxrHtz7IYtqnt6HsB7dUkojKPhOQmwA4cQUZRooqZTHcVe2AvAJs9DQ7XHTT79UqmFebLoJtfnRgatIuqz6kyVIDMXQFpna-W9zIl3eoldnwS
d2AY9OPMUavCZmU9F81UVWcNn3qs2aoQbgHXSI_SaruGZ847cnNcgozgRwFSWjuSay2qca0OAl_q_CzkvrlveWTQlRdFFSsBNfguU0Dwrw8tAPNm_pBUH_dj
z60p3tZg9SLmBrULpTyLd8v3aI3PZpH9OCcF_lxdDqrsdKpFoGM14wmX7Py4CYtS2QRiBDWzikjSz8QkxA5sakyDdwWrqEF1ikWD37icrPi73FGdpz9ZHwqF
foTLjQJNMZ2J0era_11rUh06UbBLVUaXjbVWgxR07MsQKjANyR5TAlrbf-ZbZXedIsvA3_6Cq9IqS4zRah_3OwAB0vcU0lBdttBqmfxb8PRSaruyfxFq386K
JF6lpUW_1cJ_JQzdkB0ajWpFHOy5lANw-dV8qmPwv5qNlG6UirOG87elqxCa-aPBYKebq3wNddI41TRflhI_oC1-RPNe6SqR3mlL8-8Uxffp2kgIKD7PliIB
p2iW5kdzglcDB9pG0sVhxROd-czf6HAAzEoF4Yhqhf-jxzzD3oVfmIYa5UczPFWqlNnxUjqv1CCpEQGdbj-Kvj1RzD89U0Y7z43q37FfyVwBHK-CjhqmlTSf
FViHMVHdR4_3yfnAlwD0Bq1JmezUDMnybDxAEHbUcHvNezCCUekU7SCp3Ktq0eZvV7hBzgYOMQ17Ca8qaTwoFNQRTNfiimMRNFIahWPwQ7ERxRRNlZL2wdhs
sheIlOBRRAKdX8ZcACEgr6jjtL1nctLw0F_PrB-fB9BMwcorCnaUBLeKw2NJ1FnoX9BZf1TYhSvMrLgcvbrZzhTmHE_tD-kFZ8S4xqfw2ZthfeTXEm8P1zDx
bw9Cpy8Gpod-pp5az6Ojqh0RTpWzGwKqDo5hSNk6I51LqqxuqVGK3N6shtqIxa5l_hbdDMFzI-_VHqXczegLYkEpTV1_fiq_lV9D07LhvaT0qXybICFXsNLs
rlj8vR3tS7hhvFEYfnDl7KZhre5ruyUYDzMRSOnDtkdvxzUoE_FlfFtJqmdqlDuorw_u67fym-FztwCUxyPbZRfK77cEZVVSEo-rDZxsLd7_Dnk7XZQwfxTk
5MVXyVI2ERhH__xqU7dsMdhf-eyy9QDNV2izpdsxMjRt9PjmXT1btkWPeRj7UkrDGqldUlkAL7yRyqkROtf1ZjKRbGoElZ4cnrhVlfpmVSDa-PhwzAB77Qou
xiEQXWVImyol1fjUPjSvXQVG4wi4OEzzp7-noXFfnHbxJWZVS7Y6YGxBdc9x_5NxT0MydERkG7-8xV6jcwPoCtXiU_8Os-EkLWp_6oKyoVRsoVV6f3mMNp8w
rl0SsmlDz1nqDrqgFxapxHxq10UIVkiRvUkWkNyezBVJ76oCgEz_b7YeCVYittkgZO67UAWAFQ-sDsQ1WPLi13ze7cHv3UtqQtioXnxZovQadPqHl2VHuqBd
D7h27yL8pVm9tjNqU9PbVkXn-p6A7WlK-zQml_35RimyBnvBoZzxz6bxTNp0YAfBU_oJfCJE-k7LsodX3lGCJGlF8o8kKqWuHWSrOjTSCMrifsDw-DmUZMIP
PQQ5gQGW4Jegs4oG9tfXmZRPIjx8KatfDL46W9IIQcQnrvnQvinu8ZqsFvQPcVx8VfHPR7ZpwOMdqkD2PRlCKfWlNVJOVRRBD90UPdjA5ytDvzV93e7qDDlR
YDujxCyIFhyakYzwluAs03HDBXQqjqNlZt3Q04qXOT7ZKjbd9KXcTWZEB462iwr0JgziaLhnRxoGLCt-cvmghcE2QbEvEXKzqqCiwr8J1A0_-kCeLJK1GBXE
4iigqnFFz2hB9jUhgnu-VfMXI2zyNkJ69z1pftYUNlH1Zu_n-gJdpFOsL_IKw3K4WoSONxauvPfUG57XsoGeIMhzvUVI3zQIMthjKNZ9RanloS5atS5baukU
XqqsYvx_gkiI9tdmIM_9_z5BfgTXgV_Oi__ZiqkxCthQHMzDz_OrcXQzotPser1l_rv9ROb1lD6BH8_WFGPVTJ4CbEDvFKRqxKj3B5JNzwAtseRabtJHOw4G
PgAtsiykpwOdLNhghYfiHA-CJyBZZA-m5JUxBztXNTyDhzvYJZdlivrw2LmKliqPlYNmGFTVFrZYf6NzJ0EqnZbDOcwa5MFYMk9h7kPRy29flkrrBUv5F_Hs
PwbKCZELVsy6CKjt6ENB8y3UdRYwSEinkqpE8vKwFogbme-vsCMbDCXzoCgky_eAcK0LdDaPZfu494qInglSQh5YYThfg08Ttxxess2fWTxBkwfSNAmkUIWB
dYIb7sp2eZgCMTMVs9MHiBewf0wB26nySXKzxfJKH2zTQGDuMn7Z4Ivkvw4xjMCiFG2uX1u0ZARdtVJuckyusdDor-02UXZsOyf_qHFk8PSJzbq2DqJ6nXGP
Jazeb8tDMZQVZfCJAl21xj0j4Q6EkP1UV7jvw1AtMdRFgw2IAV8DSvGufaTTeeFeOQ3JY3GbzfgtP0nEtwJ1zYgLiYezUZ8yifZlbSTiWsTEQACNahxVzQwl
9pLw_AhHNyo5yrL_spvBBt2P2a087wCdHd75yQJ1P1wzr521fbhB77gYsU7ANjaxw2Hwh_UgT7pAmJ27NZIQJxcJ3FaMOJizIQefj0ggYj1CJwJFR_e_t1y9
N_Vye4vlY5hfITUxz-myuUGVSvVU-G5SqkkVGspPRvc5_Nj_tXdzqkj_UJJA1tnAD5DozH5w0FZ9P-Y9aKFoAZ72DuqUbRW8pLHwt2F-Dol7J4v-5ZtwFVG4
y-c9PlARZgMP7CLqUiI1daoZjsMgtdkMx6HzRVE3Tdg26D5C3-HSU-Xn6nWUHnB_lhDkVKAi-kZH7whGeyMBRdhiaXdUpGutHYDyzV3KJe-VCAlwap7qOY7c
CJp_sepyXJjwSZqziO8NSX_w2D_Jw74l8Dn1FEfib-VHYtPFU3pkik9Xz6JB1VzpG-lB-_OeUh8RmRiplgnIe8Sle8StmxCso_FlFCrY-spTFxq0EY05pVU5
nzPNDZyH2JUd5mH2XaVmxYTHQiT6_DfzwV_OiG_S2i4O1i1nh2JE_IzS-gRUAdIpFaMB3KR_-b9dnF4k5jD_57i9LDyHR9b2VKV4U7fus6BZMnvRO7zSbFla
hJXouNjWzHqLRA70lgVYI7oE2LliuotWqotZ5oP6BdpTyeYblfUmvNBrFLN0rWVFiXDjqP3zIE6sBeZgH-MsS0Zr8wNRUdYedmZOyY7LZoG2gsqo1qLR1L3z
Z9AmPGD3_Om2jXR8VagLRilbMUgdqcrDFDNFAPROX08UKZybqTQ6rQ-ew6xB0MUgNn5XwmEgNz9YEa4mI_sImcsbAFLpEYS8s5m1O4hzcfImzG9B_I4bwPXZ
Oyci_bWHjcxmx15IPT1jBi38adhJsLs5r6CqYC30_Wi64Hhq62dSjW9CzJILGRh3_fGx6LazZPAmJV6edaogp21XluwCp99wiWg7RGzOwkbqa1618_iPE694
wbr_WegmpV98zLTKLWO7ZgyrguVpE8YiBFKNACDjsm1FzPVf80-2pbFPFLxsHHxeeBzCwGuRx3nIwc_Je0_rH5_gJFqrKeMRNUtWaQMUErM6mnxju9xLypNU
MkwSKP9wFYHLqMsQ7PoHfPaqbNJO9-rmo53zNtJ83VOjEpAg9FrTCnca_Q2TkqT4LQb_Xweg8jpTViSE0tUFp5J_36Lck3i6zfTsV5T7kkfxkgeZleFDnCul
6FVyohRkhJqu4000000Gv6yzoDKK0000000000000000000000000000000000000000004
}

