sprite $215 [446x446/16z] {
xC6n00000C2WV_x04wa20000000000000000000000000000WDcxbqLdSHm8m0jlIdh_zvqRS-lK7n6mBInJjPfndoQMF-G4E9rJBNOZ_aGK7B5nmH6V5yMo
ufKYj_662W3OqqdSKTLiQaN1NITK0AiGmFEYZbCNYexZ2gnoeAPBNKsir8AoSy1l1RX9AJ-iis07_jocLzVzTw7XamBWE3hKWSFQ3ZKdAZjt-AE1N_NJbgcv
LwqVvJUEj-wPsEDcB5vdjzasyYOxgAIgbSAnPLdOtcxl4tFlJvhGoLcsDjyby5tzlbQ5btoatX3lJPUpyAB1nNhG6lp_0nvfVnfn7eaFx7oOtqQ0Zd9BvM8j
xGXenE-CU3I2ZWEtw-VhDdZkPtej60cMDF4mOJRXmsdZ0NVr6Wta7ePhYE-3OeFESsUisdeq4DI-6TwHodgjxSc7OFFOLY-kltBdkRz0Brw2-dZxwzNdurtZ
XNgyUw8adlihzNWXK17lhNgy5FNmy1wz-doW-Rv7hpvVCDjtt6k9rwCK7ZpaWnVKunegylLF5LvNZskepzSnqJfwLrFbiW7IEr-LGgqdFMw-KdZIynBDrpT7
qE8ieCVJWTVXov_YSdgS_VLSUb_N1gj_u8JqWi-TTLfFUhmw1V2aDvslWXwUq4CDlONVba4BcAN7rmVr-VBdTgpV4th7u08hLF83PxoNZjO3woKiqPfwFYti
C7R4AQzeljDVUH_9v-FrZY7CsYIErDDhHqRv0Gq-GyyniFD0LTF-LE8pI_jViDnUwiF3LGUhjAGUk8uZRz8hrNmqhGwzX7T2duaNLBscdZsZnudrA4_gsSeR
9nS2pybQUkvhDryygMIy-3iZylcmlXvE9wMm7XRKyoZABdfgFaqfBz9JfCUHdlIa1rylubFhIKz18Rt6yStJA5Lxh_qfkzjnK5HFUbpomdfNIf4ULcuzI2_M
ivNrN7hIazv3Lp2D0zywftXOlFVYm5-UqdhAidgkI2yjUY83wKbFUjAJdlIafqZlmKYlVOtlblOzA-k5jpbVmzU285Ymedfjhz__QL5AwhMdz0RyvNhf8LyF
TXPWIJtjdFPhl3FIIsYx5B_hjM9HFVnUKZOT1rbw21_Aw06HtGkUdwxqOBVp_CdsyXjbiAwWhbxzgS2wunJffU7Lu9CUnyO4-QUSz72LOuNsK-_55l2WbvRm
anxkAc0jlhKkzxBkbNMzVutdQq7AwhKmW_7I_lsEEWlfePqapuupag-T97Xjh7khfPrb51x676OANgndotxzI3lDatXme-JeOH6z-3J253q4QpxkKEezJscz
iLUDhzBpT3rUxkNvl6RlnMLX0RmCFlUQlJS-m-tutIzfrQI7PKw9-de-FI2yEdpIcxR8cCudlOdFLALNjlMu-H8hmI9wTV7uwE_GGr1niULDqvDUmjaXFRIJ
hBIuTr-WdQIiNZlDwBNDvskdAQhNViWQlmJ9hu7RU9oIUcsW7Yti8itNfBVC1y84FMhoLVKmHmyvUfRJUxR_-nwet5MQ3_lg-OpMowwdl_dYUlQ_tblwElgq
nX9wIMjQxcbp7RtwnKfl4psJtj8lme5BhsQj_6fxwy6IzU0KXFyOd-Fs4HJGgpaDvhdw-s2WOViClPpqibx3OWopTVMaPnRosHqzbzx0-zJyjXVh8MmY6wlN
VaXPlVPJnkeP_RDvUksd5DLhlmKUveUL1h_7sNKzxbdSmUEKr6lpzTousGw1ME_c2qgFWvuR0d-MiINrj7Do7jMJdiUvY6V_ztzSUhC_SsA6dX__A_pKWlDN
VDDdJWv-hQrVx-EdOEQXtf4klP_gmwlljTX5lNZGFeDORqAanx6Vz8o3v_IantYn7kS1FRn5ZmkDyK8z85TFlNT93wTlXW6Vz0Q6s-MqF-6dUdxy3E2vUdg-
TuRd7kXnLj2J7dNUZth-k9xqG7Xtz7XOUctmi_LusxogXyjwUZhBwTAZphltlgUxr9Jvp_T0U37G__yWilNqR9tnE87U_wY3WyxHanw2bm_r0ksmzRHpBgJd
m_MaT_irCABt_BuUYkiXzTcwsVZUYqlQ-ue1lS_M0JyB9kgXTsNF2zH_ltTR3pH4CqvOsJVh8NZZSr3S-MS-HewaVyE1_ijdB52HzFIj0z8hsUVwjfsSzrZf
rQXMUabhghDnbQlr2NpvoueM1g__Ld4i--sg3dsh-8hVR8oNVwku5_jMSLmzH_ITy0kzqMCOdlJozqvxcvw7zKxJGoPUFv_qC9lFfkbL_Uk9e_2OR_975lWu
FkJgwQydGd-vj0uV7_jzUbRqxtNpeLrwbVWiLm-BwC5I9q9yHV7Us7lCLmAFO-_iFRUFJ3Wctg774wd81pgYzChmCTuhzFfljWnQRdX7R0mUWZ9HLg_56SDd
Z-DrtAJsTVNQIVnPFiR35BrMGW-qdqpX0sp4iiCIy0hfsPmd31mOno-c-n3IwtXHIhS_ilIiX9wFnEFLvw3dN_RRmPvwFaoFOv5VJDUBrracjj3pC7COp0Br
INpkHNelCSmNQo3yyNhtXki_QRJJ1CZFpLjwHs03ykIayIOzZlK6hrgnrNwp58Fif6VkjVpmz7ob1qSXEtUJtcT6q4clYf-VHdfet-8JWgVwBYvrPJtWtaE6
Xzu2uPDIuYOrvwPUysb9fZiljQGUalGuW0C0x40302Uw1VImi5uBuqj7UhwhdlJWQqTw_fhMYqijgeTtuCLy7kfLU4IaI6zyj5xs5ZxfAP1UNxHSqfEUzBIH
Io__GvJqiFRPr3Y-Tz0e2CxrbVLQUniVJaiswIsRjezUavxqfBSGdzUBzAGNuwsdXyQ1luxFQ-gv1vMynIzOgbeFFHH8J_V9f2UzYxkv0kcDZHRAn2UzqHiK
pH1rrac_h04QAR1CEgbe9ZIYgxreNdot39EnS54F4zQGgpuznwiyeKtV9sEzcOkOS9Cp_J73xDUMtf2jSx9UQmtTUj-UYGpRDxbggw67gNfqi55wusPvheTr
hqDjfXuT3MFrsYGzh7nBmqxvVApUyDuRE4-KsZXvSbn8brPqFCpJmzrB7TJ0cpwxTkIPtgE1XFMfpyTBUgdt4DmfEzVZaU6hWyMV-cEm7Yxr7kWKmb9wxhit
7-l5lSTOT6x1B-bXd1wezTRMi-TwxmZSFHX1Nk_nqgmO9EXHGn14a8jwAAUNFqVckjfx7cv7CPzVxJtIB8iNDv-Dl3v0s100_780uCUFjvz32UzwrVXu0UFU
6nW-S3oIiYhv6QI7eFVoz11utbyKLD4p3DFZaVC3WMvTZUgzrh4clcxGDLLqzHv3y4X2xzN5uydczrxSD3cz5-z6XRkFcwsxzuwVkWXn3A6_zn1gWl1ADPzr
N1z48un-guswUuyvutEv85-irzjxNIEzlKS34Hwy7Xy6lCjXZ5MRVfXu8Ge4FEjOxrBlvUcXKyy-uoLYdzc_z-hYSOooMkzXTk-X65xCzxBUiy9u3gFitNkb
yJZ6gTrxiV1PxV3oV5ZdUWzjslKUWXEtD9y5ZmBgzHxN49TTdy_WbDfwxg2-2sgkxkVVWuublRh1zH-6Oq71c-WPhZ-O0mdpY5yReO6B8nm4U3lv6OBkmya8
VXZnrX2Cq86lZd0GLBeTdtc5g4ohN9XgX7sFRrqUV8TO49LMkqXurU0LTbne_Lej3dolmFO1jBFuVh7Jg8ng_SSfvSQ1RnlxCPfuBJ-EfhnY0BiKBBdFS-0l
YLtFet1gErwV9Gsdp4k0d7ol_XrJW9mKCz5nR4f0fycKk2k0rGlW5FLWYJX5WLK8_5iK0Ekw0NuQ1LvzhrHGVQjK003Fe060zqT1xeTIzobioWPlRsf4TpW0
OCp-22_IRkhB-Dkh_zuU7CW000003FAtliTNNG40000000000000000000000000000000000000001
}

