sprite $215 [96x96/16z] {
xPY9jYef34NFILAGy_y_t6sX2vRqnK9xVkxtxWILpQG1mKTy-VBb2yqzZgCyE8vmD-9pp8-IgH_8UeJXNHWrTIUpbd8yAAKEZUPXs2UQ8Clnqqpm7Doz2UxQ
BtVCefxz82vZkJTgnYqWS97ZPc-110Z0XY_subPruYcLo_fAW0QO0Mw04t203fXFnR17s4Nz0KoYXP_UXd2f0UlZlEe7yMWWy8fKnQw_3ps9DIuH8sl_rBc2
DNLwWlZHpxbtYIMKx8oVUF9FjCAKOqKeqUCd3A2XC_dBSe9Q_Gwx4vGAV899M24PG7StxD1Z95lx2T3CY4tCBYmm9Np6Ue9DYS-eEbukl_aDOe8U4MwOyHC0
PUcFbdnuOwvCDR8Odk0Zv5Yym9UrqSo_8sdrM7tBNuODq8gKziuRhCsU-Ga6Kegd3ThGwH5hVrNyr7kRIWZCs3l-a6nkClSJHCh7LyCTIe69iP2DzYnV-SqR
wwGQVG1Zm0k_OKRonM2VMFeb-t79ehIn0HxXRLYBBgxyrY1EulH45aMRbCmI_QKuF7_HRzumdDoy9wKmImBofsJhTwxvHqQ_oO18u94VfCMgRFij0yrFXDZz
s_DFQt3qCmDtF-3YE3zsPz_VrxUqMOa4bIgjVDS_L_Pr98dXpD_6DNFX_NjjJwLax_dDJsp81EkZ6BtnClzKHPz_Be_5DdQ_1vYqdvzTKxcbocP-Nkp-8SMp
Fj_O7m-LFzuVYrHi_7FGz8YBVl1aEZwKECkyp0S8dgpF3-jQ5jt8zjqNFNpt-Cwuoullhs33rkT3W4PWTJwiElx1ypCaVkhtjTzwAjk299lWvV3ipSz7tjBF
F_dvCTRrD83ye7-Kh6ac6419e1GW31EqDhyNxX_CyOG1eUu_7y982tBbzlq9dA0tlmSGqVnEmEVxawtx7x3xHvcp-pckdeWNc7HC8lgqlltEPWgzTly6i-v_
kfmnZlwsjB0-z2L5Acl_VAVL9YTv-VxJfudctMqs5GEmAbNY6ZvVnwxngcdkLx2qVOINv4TAgeOTU0OfIwpYp8-g6yMmZPVKIMOvmir8jaHivd6K-gYkGRo7
HSdKWdby-x1rDaTjrdD8-9FX3Vpd-VBbovSllm4
}

