sprite $224 [93x93/16z] {
xC750K9H002Wrx7_mFRTrXz0M1G000000000000000000000o3UjFwBbcnX-YtYIpjhPc1_GpcewYp66poEbT6J7J9HS2q4WMZG5jF__myzYzfduD7lqUchD
SZS9Hz9gPXuLbZl1Y72h0BX56JTu4o8hvM6m4k5sYLqtQKTBCpwVS5DWnAaRGCtJZYy5qwdQ5Ee6Qk-6V5LIg3zrkX6e1yiyC5otIoimYoWpmd0xj4dLo38p
P1pIemABMmxuIGp1TygDe1-iWkfnjRSgRedYdS7VpJkQ1tlS806W6uworJbvSSq-KgsS6UHs9gYeLtYvGqsM5wOQBvZImn-PAgkgNPJlX64BywlHtgpur6pL
Kwjx3zJXPQ2x0l92kPrx3BjYlGOK-9Wa_OMZZ0pCHspAfHfG-ct7c2H61CpwCgKlqu16zdEdoLG2SnwWVcByVyjXQgMmj0bTkNPqnGAH4TiFE7VzshKZ3RBC
hjv-oi1oJvM-N0dHTduqvwEYfPGrCq7HrXX3amMasHd5rbNeTFe4Exlueg3nxyXbsacpttRhDo1rviPB-ny3WRFyWJv96irXPGhmvvr6aJi79cWStBk6Z1yu
zkR9-ism-ubpUBk3Ll3ddSPAzhucxsVxG-zhkF30huF7waTx-UB5kF954_cr58f-yPBssVe7u_m3_x5thekkiZmG9aE2hlk_uE-uZvqb-29Dg3BxrwvTLNcS
48xIr-ZNYD-7uSlDAsO8Klca_eT4huAUljR_XumqftIEtoPpm-Cyyp7qM7dx87osLuBca-Xnssd-WOTI2PeFeSUIRV-8bfzLCsI1F88UtwhDZuylid21FuCU
VGlRzFWANo4drbtq08LuqnEeeeiU-6jIzhdnvHTuZPiyJq-q_4S6NtfgvJzIEKkFFwaNZypSL2YI1j4JA_-JmPEUblzBXz3Z0jetcHXUIgFeQVaXWnyzM25y
5-abxBEs-sIdtlHHzApyb2UzCfeUvousPz_cdjD0UYMMNXb7BydVYLsUgAt0y1QzUbw-Oy9ApseT-_xqe80lFLIQhFjyLTzE2Si1FYHlUZ0hnTILNgf40D23
7gr2yBwNfEH3ZtD74qzwIUJaf94yLzpSKaNkz8GI__7qGFJgmbInKxOB5J78B4FfeRoVdl27TTbCO-tbKlST02G7UcKaFRu7wIunpDDEjzIZJwCtjCZADDRR
qg9tHc3pnQSikonw7OzylFKu_SN_bTAYXryIolH2X_gm7sI_-OVGHo_TY1xoRmc5hCXMmtOGm96xy77-7K-Fxge7tYzLOfQxGCdJLNf904YQaru20EcWn-QJ
FnEN2QmdtVHOqz5ZzTDZyqbuhMTfC3qUMm-XfsFfKHTLN9lFZfijk0gF9obOygCdHe_C47poxPZeZk0UJgE3r62uQ3w38xq48-jrI_1JbS3bhkmqmGrcPYh9
arw2cfd1eQaSr6ZOt3eCHAJIiEYZnrQkddIyXEgTg25r96S9mRj2Jq3m75GYynQZauUgJi-gzEBxY2C3PqxXEZ-fDir2JxQuu8NGZBS-Kiyp8y1VYvV5ZJJa
VPx0oHjtr1D_09DjQxF5rRavJIiepGYSSdkDFOUTESqi4P4qgIngUbA-7hEN49Mssu30kHIr77CRCC2nL8BQ32jm3gv_B29YysdbHUdHgfU6nBGPyb6rXqoI
1xFB94oGkHzrj21dLdgiScxWiv3quSZn-Jl9ijwV2a_TGTraDNf83nKgfK45QH7qh7szgzexGs-BRwjBwtAN-QZT74QFKoL1hTPRxaCYUkxZR6LGehja_lHa
lDzNRykU_UbPMdfJfzNyfrmAfOSqI8jU-JXwIxlRZEhnlNDBXUWvDXW-cDwYjwLFqshmhURU9-SGjOcuWkybwSxgAGQc5zv6GJwIFB5xceM9w6MwwcCzjNEw
Za-yLnJ8iVToHLZM-vyEUnrBSCzgczwYXtdeWI_xPCMt8YSdyD7qKkkgb_agywczkreO2KYhnL0j1dEcjutet5cAfvUMFgtBdxAafJ5Bo7FCHEf-BO7e1Kp5
_JGjUdjEdwlblQdfJRk8C7GDNvxUUmAegltnJrK3cfmpfl0szRm8mCoi59QPAR3epJeD7ggbALKYkEZDXsv-WDpn-51wIj6oAZDDioYxqjjceoVGqY65F8rU
UpXH3lM-VQjBdmnlRgom9g9dYIJUe-kmqYypUC-Ba8cz9xagEB0BznzoLHAw8ajgtPoveV6xRrwMwM1-kIx4B0BZHoK7qgiRpynC_v2PcPVzSaEpq0CVp7Lv
i3DL8940LQlmUvptv9_MUvA6wO24rje18b0z81vGxp6z4kkz11zueeLbnkHO0liMd_ZWazX5O9cyvozO9Vlep7OCKopXk__IIzXLxuXQBBvuUbkAaHgp2_YL
7YrwEghKcPy6qzjlJq_7vHj2_3HuTshSd9uEhQqm0pvuqEFMIJmyqz6Lg3w5New7X_49h3w4dWN3CvCqG4BublSSdAS1l-imQXFgFQbgN8mp7Tc2x8h7tVSV
jlWPTUyXDoIZu26nudyRkI64qgkFuoFdT-6Jzy5ZVDA_OBq3topqSbj8VLA2zqPyEinwB4P-UteCRqfyYF3U_94JrW7F_nJIGO-sZGYZ9--odZcaz1XmZjnK
ObaGFHRU0ayTu7MVfV_-cTuTDumG1tY4JvABxazF-xFv_bQ9tffUYPa9WVH6WHANvRsHrbF7KmNGazjv3qPnqoLs6WAsZRYTzwX0tHwLsz7RtUc1WfbRx4G0
lPjjb4HnqozswctfxTczrZDrpf4Cj_LUTayuzSFEkBm7yw-6o7pBUmFYM42Igyxqx5xU8-ivcozWkwJxU0-SSFgcdGYW5-OzoMrXuWo2ppfuP5qYwTblUgZ0
6uRFA87mRgLSWyUIEht8JSgGJwcZ6Dsir__Gv5F2lFJoESqSEFlFcy_fYVGCrTdBhKFzUOi-n7lZwprfrpzGDJDJXRGEiV0_DKAdFARUInW3ZziBsjgMqqph
XrXg_nFgeHDf93waYUYnfAM-waTEBBqpj0_ndniwdfknDry2w7ac3tPkrmTf7kAmR8tGgG4RhDw1Nhq8hR3i-90IVBBbWUqNlJvHsNzRldzk08ZA8OgDYvvJ
9oSEdQaG4QZzILcE3x5r3MVEtQz5pt2Gj1Z-zehL3vrlISBkHqzSfvHfez45qzSSn2g728uHlKfx_LxqB9vU0aL2G-NGAniybru9I3b9ZAXowFMvKA9NRwqi
xusdn-6nVGZ_fwO1z2RtdfpHU7em-Y8T-Xkdfh7qv8pczXxoESaGUbpOQ1twzO7907eTDpwnzoJdSVX0zCPO3p-OdQQ7nEg_yNczbqyBP-YTBZ-nTb_qQzma
UXrdxxdnURsNpsiaFJ6oA1sYk1b4By_hFOHu3qIeSWZswmS7qaE0zmBhlJIGdbAJdWzHtEoWTwzwh_yk89Sdb34Xd3calxB8eLbB4dJ0MtqjFV10z5PVImmz
jJQy5pih_gyVz1J0pUdnkmC2w7KwZp_weT__moFeMHozVdYCXBJeEOmGTONDBdfYm-YjiNMfuLMf7RfC3-cQ5ZtKu9q_fFPBLE-vpenOivBKcl3gmpW_MmmY
KZrtt7kaxZyZqFwIIkKG_KBOZC3ucV01IIU5Df99vL0NFLlqBYUTRlJ6JqfQz0fywQ4iUltYClIbf_r9owB7XCoNdj5VtO5UflrQtlf61Wrw8pEwgZt9JM7c
_Leadv7SSzS1v3EQPQ-a6-_ueG4xViHxBv_JBNVRwQU7FS1x_VJkkTDLFgTvz-T4FYCuRDSNi35XnyrFjZydXiBZlJAdtXEq0rwizrZIr7rtLvMc7hOdF2Xl
YJtbUfj6j_baxIh-OM-o0SrVY7oTnl9UVorazpeVJupuGeJtrfjivd-3stgBr7fxOhpvugqNJsz7m0RxfZTuH-fSxtnsZMQ8FzEYr-y8fogsQ7eSFSbreTCI
pc_ixhVUjMsfzr1wafjAFLANYAQN7nB9JKdOabQcrp-hfTyL1M-kzFfJ5kIcC0czN8iRusDdX_lSJu7SLcWhxEkNFEabBM_61oDxtyXxJC-ywZtUATpa3OtA
4ObjLxstJ-AzX7V1ItWhFZ7sjbVE2IfIB--nfAPneOqBEEgt-mk0wI70Uqv26OYFu0NqRmRGexc7Vj8olf3vpIccwRxqIXmzUS6dR_hLHSy77z9buVKt9R6y
rcNTZHu7px5HJYtEULoYSZTwxBw1oGki4BnxqcEVImG-UyNN7-f42PxSc1xNiV71izz-i1Bdl7XwaaAanln6iBC0UDG6kv_ts7qaXQH_884M4bA0gFVgblJO
Dntr7zLtxDzuUdTPXr9lfB4K9mZWw6_J4-W9qGkh_5YcYZhrexzBOHAY5xUnkE1ORuYUB3DJV4_ExEXl1b_QiQGwMy6LdYNIW3ajFRKNIrNnIwfQIEyodkIg
GkTOrbzUYbmLaeFzQlAeyN9TYAHNtnO-DpG--Rm8q0mfFOcUnTBZsYpMTvVBe4JH2uYS944tlZ6-woy3daaTIo-XmtenyPCoKn_p8NX5f5MTBYUoPOVu6S2k
emo8NimQ-NW90QoYanIlHQ_U7c-tvUF5FOzHsoN52r0rEoAdYW1qCMQ8VrZwgnrLjR-wFvKgdHlGYmhKyLhqIbeQkEmP7poIl-XvfxYI0hJenSpzZTUYbnUz
zsnV54vFKEdVUv3GqSrPlEdbVp2kd1way_CBXEZ5BS14zR8V8pa_o21x73txxfbRiHEvekv5w_7q5Zr4Jsu-DZjMlTUizqBfrPVmeNxLg-B3A-TGUYJvNkbX
akyLyRBk_ZCknI_U2t3xeZV_0iobBuS1c_UtKHOzky54caKlRXdHKdyAaVtfxMdfqqRRoY1wIwMRNloEEqjRG4dcCRFObgHxXbTyqhc4O7fRMlgq8BOxzE-i
gRZ-xt4Jl2WzMdYHS3d-q0oDpCoI1xFB91maBNlC_ZwbEJYR7glMy2oe64ChllQe-fhKITMUOzB20HijUbZq_X2YNWDRUsfMv6H9Wvvy1QNkE1XLR5blcOzo
FzTgZxCbgQN8a92Lp_I9f0W9bSP15tKEw1oVihDCx7NRFz0dmM878BagJzjPPg_Rkui5R3izTn627fn917jz_o5A0Bt9mzS-GUWKLTKcFVsU7bGLeO4pS6fU
fdGtA4Xg7ps4RGJFZQujzD79eK4IFVIuUdnMyDhydnqHUgj61ptw6ls-KukP4uTxdPwxBi3qT1Gzrxw5ZPhghXBlyrEVzmZlyU-xDnVs79pnxd3hDSHOxt6l
f7lXRS5JQjXydGFhtBV5fSjOtaiFW8mPNXUgTYXdcS9y7UCB_FSuGO-z9vHCmYxG4mwd_UCCe5elS4giV3M7s76bRxvEhzwGazVinb8NFVhmqZ03MOy2PvJv
njEJ7k-b13LzQLgO8LsY9sFeIMBhOO9-rgzjF3sSzLw799AUSSOGt6ZOgI3UJWz6GRAbL_JgIu-xgVOSFPERGm08tZle9JKpG_yR_4pJ6-anFg4A9yfwV24R
3IhBFzWUeuFUnK5p0Ac7deX8p_YwKFz-z1ei-Ufik10iTD2xh1vwSl4gi5EHXSc-A8Pt5jkdqBiurqeAMoyoSUaRw6DM7qKl3thSWvLtglg2wO6o3EGC6KIF
lzPVN2M5owZg2w17FoT489eUmzkHmYKxuGkbHtyhz4aOFMnJnKr-dgpPE1X9JwGD0GVqH6GWFH4vaoHGDJDNxDpHD8QCeWVwLfqUNyemUg0RgpXlhbN7MnKV
Wxf4ZpuvIKyg0RQF7f-r2O_ZPhomqtKvq2CiRUynbZ7q-6lriCa9GZo-zfNbqVJwl-PAZvrdQIBbEhv5B__jl2rDfVprf_PDfgCdaVJ-pTwTu4Qen400RPTb
L_d-5_wGlsE635c1uMLF76cQKhCZkwhj6nn9rlyGzzpxXuNQmZaMMyGdlzFx2xAE7LxVfohbdLvRQnwuxzqoFc7SsptBEkXgix_GXR1NdtlEQglDWxAe_nEz
1NN9zFh0-kxAyTk5UdkrYROmSBtq-YdNMS-ESyc9uYk5jQS2BhRTMn-OivPY71nKIunTr_Usb_V-aErBptEELhOEL2qenl5bpqzkxrvFxGcibjdkil5uLUTe
PRPUrd-p2QbQeeypS5MZiEshsks6JjXQFsbi_-DilGplbWqyLMQzRCcfMX9jd0DO7HEFyxF-cwEKzT-QxSYkhtsEBrITw3Ok3kiZ5yQPWBM6WN5Tvbbh5EDi
ebQ96DU4f6hDAKTigLgblDuQr4ArIlHnJaxLAmJe6mCD6sTbpdf0JBUBhJ2xn3WrtnYR63XrWd1gOtXfSz5rykkOViu4uS7QeCIu16Tj4HauMN99rKMpwv2g
RL86pCR16JmbrIRHhtSqLEyIwGuxQcvjngrI-hWU0-iP4ZFSZzKM8ocfdg30k2XpgPwYIMRWLoUY0PufgPuZ9SQb8QZQGMIu0nW_1u1x95bxADt6vHcIjPCa
akdktzvwXgGcjOy86w_2N5BjfVbjmipqhscJOuP9PgGcfTfFKlXu3VsOQJ_DxnE9i_2tD_pBDZi2URpL9sUgps4wnaioUAg-Ylw3a_pF1wd_gA_2W8sNPav9
zTNKllzI4XrZTWCYgJe7YR58xcPjFNf0oi3ZytatSoSb7Mw-FJlXRe17yX3hKf4P0OnTRcO6HAP-BRSC__nwyWRt93MhxwGPoMyuINu3u171YUehYPEOV7kR
uvjDC8kSgJuePu6PJSOntBtfWqlvHtjtG0000880wF_hRgJ24M87U0000000000000000000000000000000000u
}

