sprite $224 [446x446/16z] {
xC6n00000C2WV_x04wa200000000000000000000WDcxr-rMTIG8m3-qbcgft_zzv-999fmeBf3TLhT4rLmFmGZqkS0cUzivWaVQgy4ZDYbA-tpCEmeQIKv5
1K0BJjYfLKsBRwCkRFa95Q0j4y1uT9xC7-XCkNXKkiK3oQc3Ebz63WxLRk8p7eEO0eId5SmdW6SvPVSxI-wjBdRGRYz7Pz_1kWU1EzhfK1OzOEY8bdobil7J
SlFUmM0BPsU_6vnQW4qFyYxlYW3RpszTEntkkiz57NBTftHUfz0DdeMmtOFbZttW-GUoX0O3Izr7vGkNvhjEP-MHRebr8Gya2zc37HvuM8XVdClwNRUpyfLk
YV6WV8LkZSiNXmUIFLxquaVs-bolVCTVZumn-42oz7mYi1xUy3oM4G2-r7zKN1mKjbhzoExUI8y_bnSitlfw-4iFPuzTXu_iwDswn_zsnY9u-7MOctVlk8pE
oshD8zDzFez0X1umqZrsgFdvG8hN7UJGFDP7C5SFzP7Z4gx7a96UZ-pVUthrEnFqsA0sg5VuYIavdfDUZTMh0zUzVWchNsey9ptKdypJgp-1G_Ve5EN7mwjw
gD5wbNRFQFVu92N6y-fUl9v3zrBpuNIliBuUl-vnlTHyP9_YkdTyF2AwPvQLZ-yIuREvUgXVcNJTwm-LdwMGzxpP-vdDrKFts0dTCmCvUuULptz_NFNuWp6f
U_xJ5OyNhrS_r3th5fubiPwDvHT1IZtUFJDIlQ3o1UpBYjtZoLy-EEpAWjrRdu_lYBgNdu_-9lqHTQySarZlpps-U_TAfvU53-sOxkxVwyTgcVLUmcDy6Qfd
lTxumIAndksb1nUz_d1XcVJetRvnFS8NM3sOmvcpIxmUZ6HO3sJkqhnR8DKRJRIUcISVkUh4Le_Cf8yUvkd1JmzTzIBrfe_VJUF7zD2Fkl3qyM3MwEZdyJDw
_PF6qklb7nq0-PlFR-aT5u4Ewv-jz69laaPVUI87HoOzs5SWlMMgPs2tsTXg6UupXWyTdqwbq-jMowBN0gkNDZrUVEBd48le8J6U8KNtRAseV92UHwGN7-b9
ByDRzTB7RfpIX-X5LwyKyPrDH_pzAgOdFZuRuHUWvg8dFGlNixNqf0VfgNlI8ps8q3FX7OBpsGZGOqF253eRoAnt7aLwqek_oQbiqZtfGTtJgLDwqbEaboBI
on_fbQV1BU-HzGdM0yxmTA-wa8HtZ-k9hoJMQzAJNboa9ptfIG_j9mZMC-6DJaEeNX_yyQyxXSy2WlL0yD97DrjYzAGNFvmYFUdfDmpgNjxKVsGLFUdLfydC
9ptK2u7q4kBLwq5IFTnLhmxcfXS-9DIhBoMXNkHW-Usud_GAIO1TY5yXoQo7mZF1Bjoly22j7ifPOknutF5uydPlhbvrIgoUJTH36htg64JgtR1x6EpJ-tpg
tfpY6QmFJXuKg3UHBuKULM0z2k2BrEFTYybR043ytK_fzN7OWFHYxE3oeaTw4NXk6vBUTBo0RKalVC8nWKzw52_J1lFhPSJBpoSzr2xuo5QbDwLv7zekRg8t
zJOrnqkouNAMK3q-L3aFyk3vRnhbF4lh5QVBaxd6QUjbUpquJMz2lhA_Nl6e7Zwj1-cvuTbOCyA6aDw5varvEpbDpxBecGDUb9uvd3jHJcE1UZZHGv9MP3qz
mon9zw9kigmzK9RkxVUNc16k5p1IxkhbBryx977tyXSYGWz4R_dkaLU2c_1Dqsl1UZERBhtyPU3ZRQK7wQbx0PCPCQAwDxy984EgUzccaZzXeEx5LY__eCjt
JthntIlNigKUogKWi7i-UeZ7yn-sN4mEFOSZIAe7TptfmQO5qcFnh1wnPUoZ0_lhIO-iS0v0VYgzvt4wWQ7-2ljH7_ZgsOfwuuVWTVwgVK1-r3_-eXxCqI_q
NVI5OM1WyNdnm3yrOF2phnnVxBvqx4YWvv_poUz3VtHCTT0BkeCbFKpKavvr8KGNzCvqTjJ3J3tKI_r0zmg4_AZ3sKWlVfZXVdJhqXzz1zABlrzLQxzo_oFh
je4wKq_TmsNgAp-gvthmqvEUdOMiIF38nc-fLwvbFxroBPdrK2vd2AzUNfVygDEygeSnEnxarIj1UcJ5-aoFz9MFxdlWqiF8lUWQhoSztg_UjNPuWNhI6pzl
7ZdjH0z-Uj9plUXnFNNlF73J8wyD2PwpdYtwchCF-B_UUBVkrZouwvqVDdIlvJqygqyJSAz5UaEdJQinUlhjh4FpXlJWg2Sz1xmXlIeznz_llN_QD4EGdhhd
qBomxadF0y-GH4z_8f0uN2NA-2S2iR2UzEmxqfEUz22zbv93Jv_uiOAUzEPzw00H6drNCFL38zR_l1Oub2-Wz3mervAnU_a_yKEVruAvUhZ7vxMqvRkN_vEk
rjV3P3r8ppFwbBddMRvxvc2NxTDLdVbIVpOk0dkGVqXi_Lqe-bJnQIFj-IdHc8UtV_Ump_Snw7k8iFatsI2cU_5bY1yjVoDkzGrks5YlwTiJfJSwfub6afw-
DHWBVLi-9ing61xAUSYKvjShQRzm7U-_P2dISsn5VFNMr_Cl7umdgDybknxUreD7CP0Hpx2_dddeLNyywRdYSJu4u7dm8QtUkH_C7FZ834Tl6eN7BAUUV-Br
_1Ej5yM7-g59TjYkz0AccMvLUl5y-V4GfXVFLnDjKDtZGNMTRhArEBtyOmLCU1oUkiUdl0PiIDtpuwiXMr7tneFtPxw6uN4zxDGzpjS7RpswMhYURTyz_d5n
3e_SMCzIw5abOO_AZ1UlLsZWVFBa6LlPBIWqYVNAILphvnXpJ3b9Ohq0lhHuqkF9PfTVpmBr-cIpCqXl955swtSF3gzQ8lrWDf-FjY7pXSy-bSZQZSv1g1uy
cXxF1qkI5jgz9G4jJvgwz_y4mAbx0RT0RwfNS-ZnLDHZy0KdFIF3ATAJtdhZIG-BwIbOM4zfa_N0zChps8rIdeTDPd3tIX7Vs3GaqaDwFUbXtUv93qSzBAod
xhMjzAGdF7xzHruzEy5J-ypowYdvRtr8potntLFKFUb1UggUzAIdI4zwuWk8z8IdDtpIYnvKUYgVzFYe-kt2o6oqGn2lL_wCy8u9g1xHQpVKavxq4AI7K3rr
BrvFUYr8pnRManwU38m4UAZ_3LaoBKXsueml_Ndg_qAMp0kw1I1p6CE7X7YLBE69dyByvPCUsY6HOoDKwaGFXoNTYWZ42z2BBH-1OjqZoYlUePPUlRSUvezU
_XDlFRBzY6V_jiFZznicEEjDVNkAJ7gOT-V2jtja-tjLB_ZPKpoxXs2z5gh7zm3bEtX7AaFty2OfoZ59giTteVp4eMPpkeT-K8-BOLbE3-KGTxtXDt8OxvxR
-RJyIY0Ul_9DrmFJ8qj8zoRfjM0ziXU1tUD9qprarCDV-umftHiF0hj7y0BvvhngwGHWhsHEz-oqUh2qV2D7EAvdUFlxkks5xWrg9htgZUy9FxuXFVzmlMv9
m9Ibv2k1UkFTmvkxqVBgjGnwVnDuTQ-uwbbi4AR7DmUwPBnxPBMbgiVvMhGUoDRYknUFntUe1UkL5_NWfvSVZ-yIdoCdlV6jzIkwTU-IQCklrt1Q3FZeWQrs
aMMqUtor2NXnVEKYouJLR6orCh1QHZo7_K8YlVAHxXK7l7Y-bhvxPNRtsa9wRO8UtjWQfdQFuyK7PE_KlUHuXfuFwXuvDILBwwFkSRpyVEeUik3nrDO5j-yU
6i7Bthvsy-vnlFnyT-mUdv2qGMlqzBbxzyxjcYLEEzbZSkJBTQzV3mDJiQ8VS3ZiETt3ZFkSZpLjHJpEnt_nuDyMlFex1h3LG5Ppc8FCVFnv1pjCK3TbRBxx
1uwpa2LyDOS9o1cCxlx3e2lGnTNmPvTFLyFVgvNJhLa0NinTppwmrG8RICjxu6aF8_z1DrigQ2IsOz2sUiOscjrRn-tMzyCsT3mB7zVs1KJZmV87nxFpiM6F
ymgF3Yl_WVAiNBhutiKVRdx4TZsmVG9hYnyvsa0CjblQMDRTysOR1a0ZILV5N3kR_mJ4ettCNC3uvtRyhkKFo3JDVC8tpm06egTJw4WmTRHc909C7Rjli38X
O6j69RHlEWM6fUKKFD8o1m27Kma1omXd8r7MXbC0MDZPrEqagS1WjlhxDnd2p3wf1fiH1J338GDEECI0768wjyA-_mF3CGyWg5l_RWyE10000004-LiFSZK6
000000000000000000000000000000001
}

