sprite $224 [93x93/16z] {
xPdNWkCW34NlLRFz_p-y1fDeuubSikKfPreQ1mbamX1iVFdoXQBc4TCypyjWlJbDuQP2V8nOJCi9SvZYBhJf6MUFKaKu4D6MpJGzSfcCk8v4rqv-bhcenzpz
UbKzDRCBBYBU_FCblQ-lZDfSfnh42PpM7BjQ1502ZzjKREZhxVuakEfdEN6l6IeW04G1RT8VScwtEHvJwGraRNfidxVkbKyvmz_BBIJbofxqJDH4xpoZtSjf
HCervHnfJoYHDYR9Jxc6xkJxzeQAQGb0D7CJ7iiXUA8gy6K-29m0YHTCtyl5YT-XiCsPbXKUEE0fHurNevxTrWYIClbtS8mAYTkCTdM0scT3L_01egfiDU7b
aFyXjIGMnnzZnOnE_GgG1d6FRARBN1NBdyjbMGgvu8zX8HybMY9gAoeegItS7cO7UwWU3-pDqvtClqX8E_lc6j5tAgBcJOyTsgcl8bbcL7Y42mQq26Uzicfn
WTPk0HBc0qL1xz6j_6NZnVqpK8iW4cQZMBo-jhGZfIWxH28vvhxuZLM14VBsKQqMbnjo2yCR98gN5t8l0cSnotfzvOfjcdKtw1gEjsXc99fZhaToRcGaFK3n
S855xuakMqeOPACJ-HuFDhdG3Kg6F0SaWiNbKbO_1zX8XLaFLw3ccjtksXpBTS2d71tjAZVGyP3BS6URb9yEIqO-ja3cWBk6CoFVSLcUyKae2NCXHJMCnPZV
cD2i5eyLnee26DNYk2ptnJ-jS-QOmuxa75ouGkLTdTkVh2rbHhKcyxc-AaeXztecT0E9tbhFev3FU8_zY9BflbPqSlWUghkrt5c_GLTRYpfsLs93_C2D-KY-
VtzEORXftxRiyiXMh3U5oy9I3kIEorEzawVbzaQKeYl2cnlH7Aq_HfgyND2r8RW9jL5l_aVviu7Ri97N-V_yXwlAgAPClvuBMS47K4JAgXXFV2oN5RPAP9LI
e480k091WFpWO46BRWLWaxfjVyq0OP6yrOkElnxcZ7CcRb8Lm9hSnw6M08cgmDgqrQ4BCccc78A4CkGA4FaekIoEajVpDMNA6tnsadALr-OeoVCroax--ncV
o4wkBsTx9R9iiOk-odaafpxEKXKuiI_sCtAUHgxpcNi4C1iQiliXaNyvQfHeQ6ibECUA4-uIzZDkl_FYEPGuXRgTpWTn6PsMpXJLwJz5BQOvFrUuXVRuyuEB
5L-9bMdEfpB1kuZw8xeajQw2FuQYPkO-eZTJ8Vu_Nxvy-V8B
}

