sprite $225 [93x93/16z] {
xPa7kXih34Rrgu7sl-4tPk0Qyw7OOxyUdvIfEbVK8OJeovSlO3NpKckDmN5Ut4m57sZ5IZUcr68AkWhxyDwoL1LcnWapYwfv-Nd3vKhEMi-WPoK7gvVsge5U
m-B05syEnEFW9JtNYAfq3Rq5oVFNxcfc8W4Hv3mVHv9sVZuSHZdqzhnAl8adEGkH37cNOZu2TE0zD4N7ZnTSa0jFmIdyynYNCh-d9fHIeb3dHJa9JNXKof08
qCnp-K8DpHCtMW0H8PE3LZHDdS_46RjdcEMq0QsNfhMkKRedWKUlo-KUbjMAqeVazLA3wLCGaTt7xN10Rz33Rf8Dt4h4Sa3NaHvNOnijJVuf9JJhB1-ITnTh
anhu1kWYFr6MoMtKkV2s8uiU27RFfD7Ax_i2AUMm-S24SYJArJ44Qr9X5hsTCILatQA6f17kqmTRp5qfdw3o0ShImEBkikG6v2GVej7aXCQYaZM_rNxoApbe
1xfxjJFHonhqkrXJDxUDG-QxwFGAIESpbfCvHz06cyeZdNHkvMIorAHdyAv0kRpIZYJnz44DIUHfWkgknER6f6Rzbkp7OYvdwT29kBO3s0616ga2qvCv9fNB
ASTWaZVOMxfAfeofJ4jCBjyWe_0cJGXIDKUNNwoMbP6vQVFn_8Fqgbm6ZuF5321s0OW9pccTv_BD24MJin-m-W6Pkowz1IUNkoAvyxL-dWp_IoDKyX6QJbpS
eG6UpIrBK0IdSoLMEUaknNOtaMChvsm-rzs7Btax_ynjuMPVtKBNv99yGzdTC0jqSKDEyfcxztuqQCtT5PDwpHid-IoIBugwq5H5rBoN8ryKvKl8N3zGfXmD
VsiX2iwMaIEgMz8bD4itN08_KHxsjo_--NDvlk941Dx-Dr6ButISz_lW0xfCYqFBCA-kJv6iRYqAVOg7_t9Z0Vk7H2Gslisq0SWt5iPk2OHtOSv4skNiNJN3
8acjvBi2Om_B-Rwh8txVfblJCygeZpK68WmvqmHFSZpkxO4oPAgoTVUjLm_tw25dUGXNol5XXypoUIUj5MUH2tg7A4-cXj0tvH9HgPFdNl2673xbdMBt7MNk
Vu3fYFCcvYEXHT5pk4H44NgTjiTTcLv2IXmKPT0pmDfUhXUIOQi__oV1oBJc_IrZkWPhgJ6efRYxtN3tyl2acoy3KM-Y7RMu2kXJm2ogPdPchoh2e7-8Br--
VFa3
}

