sprite $225 [446x446/16z] {
xC6n00000C2WV_x04wa200000000000000000000WDaxrordSHs8_h0MjQptVzzpdPv9VvKO1ndBCjhdEa1Yy4x91DDX3dYXNWN_eBUJeDwFZYQfH029MHoh
CmvrDPFcdSOSsC8uJ03KC7ZLqgoJcSDKbmA1kWL0dfq41rakpRX-S39stw80W5Kk1m1fphqwPGJV4gj3hFuoTmhr151a1TNedrqu74GyTtaiKKlcVfTayOJS
vR4jolRrPUFZGzn3ouFSLXopcp_iviuaS2DvUE2b9EpXJe5dNiZTu1WKpvro3k_k4omLQ6x6Izel1gvlrjuv1g6hv_Sbi_mNVK5-bl1cqhyPBw4sEZShxHSo
GUE72_jT_i-l_c4lu8KlIsWXtcv6RGXj9erMwONVzaF8uA53NW4jKLLMAhG4Rz-ENzZUZ9VqRzQl3-7aAT5XZ-lQ3zzk9drQn6IlNs0qULFjYPyz9fI-I_kA
g_Om8Nims0kch-FxtVRPOsBeGzTkyd5ZZt7lqtaeOkYh13vLIUoNFTgJMEchHAD8xZBkqOkxEoU2lBQz-DdZXI7rTUpSyEofU_RwxV5P0GB8o-mr-YY8FFzn
pzyUiAYzdltAxEcY-XfxbUEULP-_lFsp9ptsLDUtrt5D4_jTv-op1rzzzXqgPTFhdBGeGFeCknF_EgVzfYMeAp38YvqzXq-xGztSTdxFGPzhtSpiSP_5gfkC
HFw-vw_FUp_8mRBPuzsrznf2He_dfMDSvrIbZVp3vxyNKR9d1-lPKpC1nZs7ddE8NcOlbZsTRWzniuVghg_URa-tpPvwdtPYj3mse4xZ7cyd3hqNoXxhKw_i
KUqKvs4dVFFi2cEonqlci8uzXHeOUa5D8jghheMJryh_m7XzeeF7FPxu7upy3POP-9gD5-hOGK1LnsPlLidWFMthyxC7sj-1ZCxUpPHVTDjpZjw4tW4tqPyz
8VFtokDzmBFiCTH2V_OKCvA7Klh21xzp5YzxJ3jx1FHkUktLTUm9ZNiJuORTTeN39tvV-VhRdHWzXXeMBtcSFerWJ-UwuyQ50g1EG3wvKwnYZm40zGAqCmh_
PyElSBc5xIMnkh76jPVsCFwRIjf35iuCNzhpAM8vx6NsfhMPO1Tx6JwalLEoTAudB-rbzDAU2AFF1C8iRK_AMw3FGyfxrhLNFg7Fetn0OjfBUTmN26OlxI6p
vqxQoygfMCWUlhINPoswa3t5oHwdFl7wmZU-mGIUzg19i2W4Zbvc3z7iPVPos6FINXB7NfBsidIclRG7MYaDyBWvTGOBsQDrfOayTrAzuu_utEsL4_G9b1Cy
iuTgi5SqvHNNx4MnTxmY2za3TMZQOs_CqlRIdiXnXWYcdhGmZGw5gptrb7Vquna-QNMehptraeVZEzpqgQvYJxy2zwcJumAYIm1FU_wGkc3-7ctliF0qUrZA
7WuhalO2rKm6OUpvj-KlZydiUHNDYF7Bx7KCPr0e55tRFyCU5h7NDW4E4w2oGlmoUoqFbryfcJtV4S-OsyoUOzMqwy_iEILFXbmPnREpXtA2g14P4ne0j-Wh
5pfW5NievuoN9mChi9f0EKUMjLSwmEYoYQ7l9eEZnuIsLyOc3se0EbXVwG2xsBFBKoi7uMclRbmvF-TaQ9unjtB2nvvnv-toT0oipsFSyxUd4UK1XdSsT81x
zXX8cnNaCJAk8byuVYTxKs5t3lg2NxwgNlPklgRbUSbpVtitPmCgVleGtfv_DCIlTZxCteovYxJdBi-_bRGdtArXqfVsPdKg_ErLtuRa5ACyqViGOqjooZBs
L9dIWvZihPjoAJsiQw_q8GlAizVEqWat6ijUkTwXc7g2X2dsT6DxF1IvrawxFJmfUxDlsPjWpojxc63FRzJZEpsnrRXtraxfGWnH21y-KM8LUnWjJ-TVEPQh
zlJomNlPOt32i23uXuz1xz7xsvi09aJFvJnfVtiS0mzzJxINzj8UNEIffhqH79lOItkYyv31xQQzTdMLnYg7YktGhQ7iSJTthZeO9VQqvtVI8XrtGAEnwhez
R7CtzLB3ta58pof6RmXVPkyi7qnxLRyz3BMNsUlyqIDQrJ2RsRjpXWyNx8cgukEg_kmflR0DfFInSlPADrzcJzGUleOzS_XADx9izae_5midwyFlcFwv2lBU
dhnWjoUc8qSuUxXYZzShVbJ-sb0-h_hd7_3pRxkzOhAdZx376_36l0g_LhMDpB27pDx_WR8zvf8zkSrUZdk4VDmGSiKUlhE7SEEUIPzyPwz_sxUhs9xIrgRi
gVJBSyiUJbkHFbHliYVjLVs_juH6wxOZTylUf8IplM7HquCnP2zKls9HUprVweKYrNxtYVQmkJs3FBxCoJmZUxgYFP2Xj_9Qzk2SlGVRKvBGMYN7Ep9xJlRG
g9kyIe7Z4FoHsIEpvsIl_tIJoUmvs_iYUGncsCliIMVPRAzYCdkNhlTPfzRjPRDj3z_QAvt8K-RMoTx8iidsScvzgZsOvU5pzeRFhUVSkhriVhYlsdTsLdUq
9vqtuwAvYjVGPjxs4B1osiA7umFDLThxt4lGsYQomzowpBDtV89MTOYrHazHkX7tSSyUFd6nH-l6tKjjEl15x2ca2yCVGOxF7ips-e_yj5knvT_loMtPc_Gd
r_cti_RiKVZ4uMzdqnuQZqrlhA9wZ73sybS7007GC-2clVp5Z_or7UWqqbx-qbNQymWVThM7oVPqfrzuzC-4fxqZME5CUphVdjoIzxHtx3dgOHbxWPzZO_-c
NZfOE7jmV92DVzXB5uja3mxFGZasU9BDgi_VmmtsW6dsEEgoxtE8wk3i-OUF6vl-72BiOi__wOdGwPLJDxU7QK_VKtsMFIrT-3_osPvomy4xsZFV4oXYVPue
viWJRM8_U7zxTl9f-JM0FOTKc0gqR6XFLx1to4xoiBazrdUCbtTR0vaz1QNlNddGp5uOVKBllcdslFGTVtAZl4FJtitwPF4FHjfht_iEX_Vr78pyBvMfWLkw
MOOcJoPSAFESu3EbXF2LTwK3P5bxfGEOkdfm_61-G_kTBOXahwY5W_5zD_l7jpx7dXmC7EJ5j8TMMoWTY5hrCN1u8qFb39mzjNAyGmm37YLlMtkmtXenvFkP
EJR7Q7dzrKUNoHu3QQC3W1plaGiba-GPaJPGLtkOq5Qt00QNNwaE-6RF0qvVly3ZCw9poEon2EQrIekGRLQUzXpy6I1tMJaZwbDzYZsbjgBx4qrxFY1QxXXu
sQlgZrKUL1-KFIncJo5HQoRRmrEoPm-W4kxsV8BkZpYuItik5LIWwu25x8bXPiyCT8dGoJf_jCuO9lYyQoXqFDO-MCTUEK5q1e12vDMYY0YWSoWdB9EzQhYR
SrVA6QxPGzgppQuZSFOoU_ZOdKXxxboldEfhJqztFEt9klPKMkWpa1RmllXXQI_Pnru25tl--Z9xQI_j9MalxMcRj9VHmtBsqbvcBxC7XsczLHarF-H_cJhb
_SswzahQEx-v9Ur5dcc0hpsalLDWiESGlbvxcJrDUpdkpHluH4_9Sqxupqb1X84-4CXR_2zyL4EZYRSzUDjBU_wD9jKzUz1aJ0tBWIyBfqEpAI-olRG7n2tO
QS-hNUX8qbwUjXp_XPP8ddAolaNb7K9BiFv9IuPFZl_3FsUsh3salHz-NF6IZ5v7s-M7IQQaOO-oHo-UDyc-jZsUcSIScCcbxCq8vCUx8k0e3xtt1KulaltP
euKJvcWN6NkcsUDOzzlht-orq3tDNfrbZ-hFXUpHGdf_cM0Fhl8KjUVc9Bcb3jsLFQ7t7wnF3D5p2DyzvsztPQ_SRU_zHn-UzbWVn9uyUeFXsUksPpeMUPSy
U4LlqXwy_SRXaprQEFoJxy4CUtB5dXYovs1F7RYtU9UlxN6iMAWQiZTId_ken_dtjST0Nm6ebzpiSR_vXw-wshk0FDkU-jk3PU9E1jlpb-SKlXzL_VPUqsTv
281ehptQtU3sjFx66ZLSi0TLw5MWgjtsQCbGUVxwO2sK_VR6qszFQBDnFUPVE_tjWJQIKiHeZnQChLR-zggVFTwGHpH_Uw3eBQRFtvvy6gYAjpquHCzG2rpi
5GTx8UMnlJvLDdlqRjtsEAGopjw9KUugg3ke7VweBmRPawwf23IrcEpHhlHt57G5wZVwPAmzNjA_cGonHqjjdtB_zFKCBPXf3mR9m-mPv7ccpz-UkjlZv47N
rHSWUvXWBuGyHLjVPg_HFqlgGsQlktFygKHchz4r0VHbzgB8KwsCPlPg37cAok3XsQiMUVxwFjdJRRCNKHxlRVjl77IxxE7FeeBQA4QXzSbksUC3gtPv_lhO
7qHnLaybr7NE7yfPFq0N1rVscrrrsxDhwPm00IqvwGD6YG3wkgSUJcVBM2drh6spHglQRQy6aiTSrISq-zROZ9RqRyPpwxo4NemFcn4rg3oE7wDE07eTA8Ec
EaO3KVqE8p-qTcfeV_c9HMsnR-eOQ4Hg4-ofZj6WrCZ7bSS8r5FsoHo3FUjAV8D-X-KVFoQwEKQt043j9gOs1heJzHl27q3LlO3Mxq2KePlH7G7gDHPsna0t
fbuct3vc01cieerHwFO0YZeKUsMq0-YJgBVYqreA38Sgz9a0G8qB04rgG7uIbo2OmOZYif02fxKoOxYaGUqb0Q3HnINuFtvL4Zg4P9P4HK1bEIpgJ58aVb7x
mGkgK2_IeAgo0H3wme-oJ-AIVxS71m800000Wloj1xbw0G000000000000000000000000000000008
}

