sprite $225 [446x446/16z] {
xDI7RSL034J1qu4VulNVi4a9Cf9p3ZCjBFQDhmS000000000000000000000STbV92xR-59iPRPRszS7o5kBMROsFXezMVHU9TTdsKilsLEEzsCxWvXbvVeY
MNh8Y1Xle8_7rNBz1FN68whZELIpZZwk7oQxgJ7d8nioesOx2_b3PUcUZdkScSprcvmnDLqVRlrAVSCxzgn5Xt4OXCaK1F__m_VeTa_MaboZ6z1PRvHgMHsR
uDATlLBKdERACNZB0OvbQJ_QeIEm7rWs9WhXLjI9seB9MeLtq1COK_mJlyThTfb0nbtyqkpAy2KFfXR5MdY0YEXI-6OcV0FLsJ_b7inC_pFVaOV5pdP10XfF
T3ev8E-sY3TcgonpjcfTBPJ7BvZw3AUG9xPJ6xVGVXEv39caAkUTeV1GuW2DIhXLjziJAA8Itwf60WPbzB7Cg5SKo_21s4jDq24Aiq1og7iiprkvLP_YmHfe
hi67aLF-AlytjHFgW3R9KKF_93tsosRXF8vxkvLi3H0Bsa6xACBQt3_PHaUX_eEHAOe9x_KutZw9Fo9GK5nuvXpaHloPedJ74tJcBXvnZMiSFfk-E8FWyYWS
BVCLNyJGiebVZPV5evAWti6BXrPitq2dbHtRTo1SHizb_a6_Z5m5eviBGEBfKohdcl70IjlVxsFRWM2Pg-p0jcDYcQ-SRGMkyXeWhUQUf8FS-RT6llBgFMwk
Ggz8tdmb-DLucQ_Cn_ECt2tFJwgrsCCLzk8s8YX3dfllUclF0t1cfCXEdZVD_jeRFz98IbuiF03egJqG1c-VYWBauKXdwAWzLplfVehav9dWs2JHJtlaYcTN
SKDkyWWlLsLaR_tcuZ5OaPgyWsKzjUStvo5_MLCYyg3-P7sqT_hTXL66l8_sl3-b2StOaVVHNaYVKHBoRBGXuqxQyu1xKTbyKn77AWtdFNBFnkgJ3EmvyYBw
q35h8LSBwJDErlJYCHJecdDYkiiOyanwuvsud_R6mPR9EsMQl3xQktvBe3TBpsMR7-sT0mcyS-LMMclFWz9u9wyuHrHHUrZrqX98xzBz5y_RTWNj-Qbd7j0S
ukD5qG6mFrn1Utwtyo3B83xOujWkl_RMNzGrWVGkEq1sxQt5xnSNl5bwtZS_sXltJldAtfackCqoGPZgnTRS_y3Vygvnsb9h452CHULNmcImULHDiue_K9Uo
l5UPk6pu0Ej5KE1vBtwKnZBsEgritJu00fLnz9AFqaeRUQ7FUvfVf1GEFIJRR1j9kBET65sz4BpNKK_geC56ruvWZRRq47vRLmbrq11wlI7cazAQtki_2HX9
dvN1aiDUJrG7D4KBUeD2XiOkrOY31Z_AcSBdxIEvJWy30aR05tBsJNY3FJbut0OyrgMANf4nrjCN4VkUlGS7eR0JlIWHAPNq2aGm8cv6UZ5qEZ7ZP7WlAgSN
HQM7qF4HHYjo42w4rLvozcpTq7vFTXiHf6vlAr4G0hoG-8UX1aKIuD53fuHwbovwOA2ymIpP4aYXSslHtouvPSo0kkMDfG4Tt-hs2AFcvuzp_19bikpPfj8b
9pGa6YKjIqO8Oj9edB84BZqlLxJK8ltZ-tsbBK-CfrSkQSc7Pn3mHQ_3s6iKlMUhf6L9cFGyb8b4tPMCH66VdWmUxaLwec-5SZz1tqgIjXmvI97mYT-ht4-w
8oHnZ4TF5htqGHOoFUb1Rz7RHW_tDjH6pXKvuv1Xz1ZbYTgiPMKjV7fRm8AtAdSKteemN2VCpQqrelddnPTa8zDRMlGMFVzfszYMC7XRcRMy5dk9Hq_AqgAt
w9rONL-RETUMpgRpgais4Jqv4Cez1DaNPgQdXv9o1uaUIH9wn0EVq6EXt41wB2JRgNbJEwAB7lIR0MZHUnMWglQhL1L9vOiUz5X3UXrpzqUKkvlA196JEcri
1_IAC9CMmFoHoVj_ZAGHgCkbThWOZ0ELhjA0RazcdG5-hmsSH6-cBDqVtv47W2mjUW7T6RdYXlGyeKTYH-17E0H6dERaiulyxdACADBp-TdbqblHmqJqn1_N
vRAyHn3y08cxg_ppnzqFVjXm7-zjaz3JFN2c2hoTFJEdTN_yNMLnIfmds0uwmV4qY4zdFpmfz8JPurKFmSMSslijUfgWIm4-ecpHeqLDnJT_XHEY9v-UyEbP
z5sJeQA3JU-BFA-3H1swFAyrZVN0XqJ9t2DrJbKqaLo65mAUb5h16-OkzGtWatWFcahQEi-rhP6rCRmeJEizqLpbYgHrfW5hYazp2PFUaqSlmjFsem_7S7es
BX7SBjAJTd7EfSV8tz6N7aZ7P-CEg0fyAFNoJkCp6uXFohpq2kHGQBUcODr6a5ugLD40P7fZfG5UBtnM1eXDZmZFjUkZeHzAJrZq93PlH_S9YTxpCwySW0Tu
FV5v6Ia6FQ7DJ5l_q6mVJkzBM77JHZmXihpNJ1xWzQx5iRpNmHKkx8TaUQy-RigeYl1vLxOyGqM3hQV3QZBAbItKKmoGLBZY21_OmMf9rEhBsoJqHBNzCeCF
J0LHyQHKVFafwK63hgypwD1efXNcg_ZoCzAJ7lJySjmSKvteAScjwCcuk1dh8z3xhCXf8MuIp4U8d0EkkQhw1aAmte0QQxvyFDb3FQs44weTWNcfrmYtrt_v
yVIi315XyaC6r7aFUigO-x0sKpkBdjVsUln7Pj53TQ_73zUBdd9s2caBnozw5fjnViilUh7ROntmNFHg9OJ0IQWu7ErXNCxPNffd3whsXmHdYyuCe6Lirkd3
wPK1ygJx4VTu03eMFNujKlzTajHSfqNlE7x1ziyjQoWA9OVva5qTConwSjZ2uhiSn69HGY-hkbwBdkFKvOwEhAWKFqKFmVQte8TJgk_s8betyvUMVbza8HeV
cklRz71AKzE3dfDyavxj9gGkA0L_Hr4FHUMVebSiQl_yGLvtBj5pmhpqeDeG7vAqtVuFwBUVVLDKNejE6ag3xwlWHM5QUgAdzJrwxs6RuVVMHbfqCXMHxoMT
cchHoxsY9Kf-BSBPNzYBdjo4NdpySte7l-VbBmHwqtcl7X--DqzsUbuv1IjdYIJ6h-xnPnuno3cXzA5d-qN-cn6paOjzRyW0EQT2e3VeIgrwUf9tUoz_yx-a
E47lGrw7WYUJNZuqT6H5SQ9CPw0tPkc6JIynYkL5SGRK2FGMlVYJVgB87a56fsTZphGQaLuE3qdHtWospEEzv-teIO1mL0HpLO68MZ3VS7gBddXev52KNC24
aVGMlKZ8DI-A2dI7qblqSdWFhPeTzSxq5htwi9aFyaDISmDwEAThsreY8SbDMKyF3TVMCJCzQRcsZj20LSuRGWzwKdB3jNKzWkT8YcheIK9lhQrNxOo8X3Ak
-GmRAdP6hDNPsbr9zSuJamZFIvJjrxteoVKTWVvtsOkG53qUxY9_Xdb_9DtUUNgorjOFeXTsp14anqNoY78aVUu7PYroPOcvVYVyTNfzTi83SaQ44GFj_5uq
G7jwBeL-2YNSWlC1z6BQSfqUmllxK8xf-Jexs_W0SZsz0lcbr1JfwnziCdhhv7FeWtYNHl3fhLi75ZrUyX2rRlpWtZd5l-HdqHFwJLVbC-dvvzuo9yHRvZWt
6zThtV1eFvBUkbsLVwiu_vhXN9pBb1Sz9DF9j1eNlVblzByLFOYc4jJaBVotQUIg-F9JqTDJ8dXXH7NpluV8GqKTtsGJpQ3Jl4Mg_iiJNsfeu-aL7vF1nyfA
3teooNjdw-bzvDiJeQU4UTyxgsSayxwvL2iUbBelp_TU5AGnl6W-AVqaNf5mrdnvllTOR-m6CMvU5vMUV0rUP8ZDwZrhOQm6OnWzSEZfOu0hR40bv6MtG8-0
pqPKGQ5ddqaFthjjzT4dEYzwOHEqzeNta4MlP_DQrz-kXKLlN7QBCbGMy54UZVRohs7qd4QlUF177tXUQFJmkVJmYi_GnzKkF7haYq2Hw3A-ziqiJNyhZfNH
eteFcaWQHhY7wtJmH1E1Ii-2zmAySVYkvnUmHrTuKM3IawD51j5SfIa-bwl6QngCjO8U1kxq0ebUn7SzUH6ByBhJamDwJgNNFdBcTdcueJhLZF08tcFHgp0V
cWuSwhCNwACzl8AAfvT4pofk_42vBjWZyiCtMzaV3K9m52HH2S8sX5vyKbYoHvH9LN-Nfw_4FB2zEFJYYaEKAIfi5u8laHvOtkFCcaM0akmR2hOBcsMOz0Pw
xrcOKd-ybViEGL7V-ozMoateUHXRaYJss9URgVmjDJlwMPF2b0-aXt1D84_wg12XnwEz02mgq2CAvans_3Mt-Udb6MIz3EMsz52cuCTYrpuD16yF3Tz__9Z9
t-SrFxqeDVyUEfCIHATdjwGNxjrCP89IRa_FormISyzCHtKTdnwsPBXE5LHtH-PcoG8LUQfb2_H6NniXkYyPXX2g-Yj3LLKC05VH1k54995UjZ9v1-cnvg67
RowjOz5JSEbvh6xHExyvGe8PXjApA_GMFR0EhSTh8wfZ_kht-FJiMm-UeDn2abYl4Jt-jH5BCfXUMVJ84u-Btg9tVK5goKRJsnQzBdkIv0SlvIzw-C6Re1Qz
dtQ5-HAUe-cXHwXUz9u_cDwYvyFfMLbgjLF1wJKAULLs_kbE9Bk4YB4Q-bwou0LyX0D4oHKLGbyQcd-PJsWxq-COfOBUeaSTEyS7Pj6BqXqXESH0N9_DdhVL
xmbjnZzFb20Q9VU1bxT5gutK_EtKIyQWr-YLOqlEc39-jfahMzfgwV4DluGj1B6rhMnjA3iKrjQMdtMNV_lDzqiWvG_MjjhLxNqDhPVGyQrkZ__KBF5JT_Za
eJFSGWiHbCb4c_ImhyJqNDdlBoeI9xoYPjhCNP9n9X_UApuFhzNZosd90xOiPlClplLm4xBEEj4Yn0S7qPf_2eDMGT_JUwJqCE0qDkGV8NG-hF0bNmTFZemx
gEw1odbwyFxXL7PNzvoPEXo4JlHUL0zOK4NF1hmiKLyKCWT2sXwCl_-ybTO2tbrkh5Nqme_zJm0wRavwRxqlKATvVFSZzzYfXOxqH5Lb23roskVxlMwto1bw
Ksb0BqGDTEltM3bBb6sxjzkXf_LKfPltEdni2V12v2AlRyIv0k1o1o9nn24aUX31zLVHXgo153YZ-QrFieRpz28M2pobWbxuAEsVVFOytTVMQPoqGoynbOHt
2zdVE2leIVjmQjIS9ThV-uoJwhnNO6RbHMAcvH8zzCdNjndMXZTXqgked4WFpz3hqSq71ZtKJ9UyehVXzEoBtEl5sPulOz0hwWztgNyBd5iPIozQZsw-wuDE
0AYXLygbP5vHgkXT6H1vi1v9sEe_IMmXrD0RvdY4ZzimOF5Zv-PN9r7cfXV-vJgy9trv_sBU6R7CJq_hwU6PT3QysBbX4deI0fke2YQWvriS9DCJbtfyiO6k
qnDztutowTbNI1IuUWa5Jz2y5vSYuh_mw4LuSKcT7plzrE2W9Jq0x-bfJWz0Itf0Fhqvsna2sK8uI8s1Df4pvkuvlV2VMz6JpDx2WPTlYq-cp49Ro2Nl1Imv
lODQhz2BjIRm9jp4lBtYEzcrrDEBBLj5JvlIYpyMmoPdd9uFOaBmhA67Mdeo3pqv1q_AF98ju1lgFPdQUp7RtBpGb7-u3RUb9yaWFOzEVFTjTjV8YQnduTym
bSVrpR6y5vxin7dKuFcgfwn-BqJDMQ_PY8_OPYWhvvINg9aCzBZuWltkxZsyTYZvJ30_UCRa9SwrV1uzH7h1UCbC5DrzWP-WoJpd_FHAg0A-1NXbPk4Py3qb
7WL6-JJlnUCEi2q9HVFYomSFEPOOd6QTvuo2FGEyBolJoxQSNxuh2MyJE3stQFvVzkr4vRKG1WAm6H8oUVyNlXRlFl_XqErljNwKJSukZ2PGw677UGqTENau
EKoOiqHQcm2o10DsEdqc_s8zEqn7zEJpmtH43pj-E0NFKc5DJ96UklufCncmayE6WyFiriFigeTJ5cG9mjeidAL8DsjhCmHBCQnDG3VB6g1hqQsAIcyJa7LR
CSFQccJgPCMRIR2-n7IpXHDJr_ifMRA-nd1RSUfKplkYXgmZpC0gQnth0DtQp92i8sHWvWmrGv35mzVpDZq4wnZJ0Mlp0MINSfAPA-Id8ZCSSwMbnEKwcQai
pbvsJA7PssSbGjv5CB5w8QjOJ7_N83N0FR9EaG7xa2QI8fdftju8F3B9KYhScbfvTwtOPGHWtSjYqW2F98iiiNuZIPa7wmhC3F_cE3MCbCmhdzJHbcVcKLTY
DwOHJzvBUcGcoRfINhdOhH-XYXoxqmwT3RSdOuVEeoD7H5wD4fZhCuzatOTv4JxW3zCm_8iFsJtW4SAjVI83WlKm_4l-Zt-fHs4wh7sqiQjxDFxpUnZj3ss6
YCoQ13Fsp6aJIbR2zpDgq7PWWykE_VKu2fOcr6Q0Hxv7bZ8pujhDoJPgiGZMgqGu0BDsZmsZEcDNJyKkHmNP7cip0D5bnqV7OqRd0DfJRTRX8YwoRiIuS5nO
rrvdyx-a2FzZpzEFzk101W00062Gl_Kzlke200000000000000000000000000000000W
}

