sprite $228 [96x96/16z] {
xTW5ckD030NXajIIzUv_uCKU37vEPz7_eAb2PauT3eV3uJ1QDstEJjQI-Zf96kpJQkSMIodOOwWNpdUgvG0ZY84dja7wv-4vumuI05kI6o5SXe9j_1XkvZ2a
ngv-tzaVZ_N7S_jmfGyh-kP4d_G95lMdPFPZzXRs9mStfkNzwQ_gPngNHTfZ_PJgIbwgn_ebDHUbr8_rhTgvO4xzLzQVeszPhQwmv_HBwggIb4_eUwiS02-r
hUvRAs0AzUf-oNaJghNzK7BoS0lx9JumrRh-p6MvLvbN0gMLVLT0H7jKTiWWPIlwtXr0o84gQ4_L73DNgWNxVvT35bJGtZxxZ-__Gwhv_hYwKvtLRP1QSlmY
0W0L7tK3U2nRFuttNBbq_NSLxxLOsYTLl2d5uZwbOh9IiRfFIUc0bvIixi_m3-KixayUMHbsd3_SsJ_wtWekc5F_wFF_UFBr2nvSuV4NhJyExMI0BU_R-7Z_
mSR2_iXpzq-iRKL_n9NxCscp_xJxLtzmNtVU7ykzVGCmmDw-JuPXKx13Ahc7I-pXqk0sRmrs2QctlA6bZPsyTOV1VXwtE7-Vm-5mE7m5
}

