sprite $228 [93x93/16z] {
xTW5bkj834RXAwYI_lql-84ppHqOkpBeUtGWz8NC_4CwEpixEujnfpHsbdgWiTkU6RSRKh4ZbuAxMIjtu5C9uE266UQ_1uTuDxXw1zuoW4vgC2TZaaKq8Upt
6FBBy_RWlCT_J_Ot-9J_Ct7dEkuSn87mRt06S1ZVCiZn1-u51Yp3BvbZmTPwVElVWcTolSX3-936pItR4NnAynPUHt2hCgusov_-XvwusPDm6or95K_0KwgH
ELljg_6fChQYbMlneS5hfLY9X-QrnuxZtRpFDTRXfcJBk5Iz3ayPsUtL5Ts-tR40Zm0O0gZ0EweSV1CZ3k4fZGq0Sa95L6zuGApPdWz1T7hD66CES3cCmzlp
TY3aUAPdfcK2GtPvSCdIClbGryBbVCfuLoeMugRcBLUn42TKzcRBbkA4D6oZfzfOYsCbTPMa0Qjni36hPjgvz_-s4_TkvrhMYgSTGW-f3-uiack5D8xWk7Cz
Zt_5qc9EJg8W5kEPZFUdvnDi3LvvvSB2ORpY-bMBUkhrbdyqFfqHP9A36FZ4wlTGzdkWzk2bu85CuiyNQkD-KvCTbJhkyEQbDlRfzzjhGypgsrNo3-ZixEpi
x2S
}

