sprite $228 [93x93/16z] {
xC610000082W_QaNgG800000000000000000000000000000000000000000c3tpmD4U1e4eOm4Zt__0Vza-N-HitmqoJtLKqXuuBhyFF7XPmcr5Wn7pwZ06
x423u2n1UYr_xKwX-kinaxCKAVgwyOh1kFVNWBCUJ1DQNYq8QuR8A_xpwyvZH3WkXaV4KL_Bkp7dTbtWoHuydq4McyWDxS2mdV5obGomc-yuOw5R4Q9dBdVa
VCQj2eWUE_-1XRnItGVR5CgmMLHVTEkbrGBSU-AY1Op2bJTsN-lvSdgEhuwVlz9jwSNcsonS-YKTJz6JwRQ8Y6HY5It8U8u8Pa3lenVMI3zPxD1sP4ZhBVMw
ng4HSZL2jW6eIvFKwLB8bUXofUE5rwkTlHTx72kzei0rXWvRgNKmxnWQvKgtCKul76V5jxMznAazo5UbQLG_leZliPUhg63lemPv-thsR3wnjJslQS_Rtdz6
JNjHtLxtNjj3ONjjpshQixRtbxqxqMuLPu8uJkaqRV7-3_mjyP1CuHl0aIsHcN_F2kTYf_mBOZCqUYCBFVJGGmyzzD133ptPXPnHUhDT1a7lTFXokzrI0_NM
2xktE1q0FVzEmY0z_odGQmW_Gi_gNwo77dhHIMz-WnvwkXd8o_Lyig3tsl1nkztcwPrwlfFP7W2z_LtGV9sUlmzwRmrVR81hqPFzsJS6GCy7qfWQzEoxr7FN
0EZv07ThqBDNGcz0-B2NsjUJRUX61K3F1zBKlfuFbHeV03qV_lRlO_0_YzvLmyz-3z7D9YyU03tP3Ni-YTxrmqiFa-WH7Ztqq2C0uT53xnzVwA570C8J03tq
q2Cy0GYF7dheAJ9pU9z2_rbE1a0lSlce6kFjiguzBqy5G2-MpwgwJhUME140lRXGforhjHE70T3JOXMNQRMprCC0wEM5-gGjNd4G03tbugMHpyxsgkWTwTNh
wCMoAVJG-nM57dijTQ2U5gyy2e1UN6YVCnUhSXG0FTNj9tQLbIyF0w3d--bndSwujQ1t8dofZdUHiRFi1q3FJ-pN78ddrpjgQaBlPFWI4Q5hND-x_omx0T0Z
0E49G7Zqq4ElVw677de483m128yUUkWHWF04G0yzz0XF0CAZXnvw122ylkeN1K1F9IApBcjbPeHq_G3eALOthvfPTEK0w2bCxb6mwA81q2jPbwFAq0K3e5VI
c1hyUWT0JxcShXgwI03qV7lNO_r3Rwrt3PgPyLcPZxQfQmH0RsjNStE8BYaU_f0k400zvRcDchQxf34y07gEbw7pcyVKs03ecOSVZ1_xfKO6G2zilNjwzpGr
AW1wZXVwmLYR6X80FSUhSNunXV4D2O2UwayHmfRi7G0z7m6p0Jv6143l2o2RwADx0FGKXjV0LzKx07h5y9huKXq3eEUVVVjEJ_GDW9xXjVBLqZC0UiL6lURZ
nUmO03sb3thDQt3f4m0zN_LUT86YzWk0Ncvszjl7pkWL03szxfdZQTlF3W7GovUCcpu6bpu1q9CDToyQExCb07hj7tZRADmd07hPiEerlLfx0FHKROUpuz3P
7W2zyhA1qy-NgKC0zF9FdxPAH4QKdHdnKLB3qDaS0Bq_39oAxN7REgC-pYYJL-ceXzxZXwswwLbISjiD9tU-0s_mRms0NZpgRRyXhUsCTQ7g6qmVEci_FVIq
-VXhvXr7sndnrqArA7nHVyK6FVGQDdkvr90cvHthutz2wqeOVt5gbOe_7x2NRdhe-PMUksMi0wFYQyQZNXcbXzxUqLxPhbdvzv4pD2bt6at72mAW9uMrRhBI
tlxzkehvYbhMjd0PzO-BvkClX1yb5fqBW9wYxjrNKdRqOhlZ7vzRIBjruPIUNtilEXC0lOCxVE9xlU9hbiy8kxTsJy_nrefdzUXSci-iUwgRHRI-XdtrEi_h
fRN0FGo0dXQhEA-dkh5HVirG_c3aZCQkmNJiFgsd_1vlVTc83-6gStfriOg30EWf5o-TtEuftSNnjEvxAft9zHgxvQDNZ_HaUcVMl7MX-7o3UaelbaszJ0-z
F8stBgIluN2G7df-fiojf4cQjCwew_JEkcTdojhqq9lo6JrVADUQv3D2TvyeYhlpAJqjNhL1ZttExw_6BLvJyUdKvqBBCrU8slSvETxxphSyeUSZSfovEjj-
lCUv5ksUfZwlDodhjuzKghj7yMi9lHFXOujtV8ael2Q5r-VLWemeEtknpUSvqPkKEuy_ie7kwTBn5sMy8ltt2BtZy8hC-CPkk-5hhxhtUYgH6MQ7NaDu6-a6
t8Q2NfkUVPcwkMBCNIZS0JRiDePsFVIgVj_Tb-XDzOKtyFM-ynczqh3oDQx7wBM7hw_QygbsV-87Uh4PxzeVbgJ-UZpfgkerp_k8VW7GysSSjO-RLUZr35-D
htNSZAu1q9DzIxPn1KwXrpTyD3VpIli5GAzh-3I-5hpe7W2zKZ_vIbCVbUmS03t__AjwBkm1q6ldYvytxHlVoOOkKg4VzgcD0G7GQ-Z55jNmXWH0p_cMq0-M
6HS0FQV84twAQdZe3GqVY_azOrTZH03qdCygfE_eb7NJSHszuU5Bkbz6qIDTH5siKeC2eBT_ktHDUwvgH6PTDXKQ7m0zFslcYElVZvKQ7G0ztnqvNnbN2e2U
3v_xLKEN282U-zK6E_H6XrSS0DQCgmL0ps_Osg7JvGAWvoL5rBg1gndITGEWvwM8o7lPWrhH8pnwwA570CAZXzw_ez13Zm24Hmyzz0X0U08G7Ztqq2C0uGb0
UFJGGuy0X4SFFVG8G7W241uzzEY5Cg1QUw6WLwmFqT1IrAVw4A4NrUvmxLZDFS3G2-zOEB3Q--_H-t9WXT-7rA17tzd-rTvtbfxFmwgqztoct_g0ejywUh-g
q4ClhwkNlqcFVSx5g_oJzJZUGsygLptN4kYT21_BxppFYPwVfWwDlyQmt2lBz8mUr_VCRg2VNMj4RsHu0X0UFVJG8m3XqKCFFG8GNlDSfgygDddj0EZ9pso5
JLuy07etlpBuCNMxR03qDC-nVV7mIHj8TPq0wEbcQzU-tcnNMeS7G2yN4zdLamsa8mAWfpbZkw6BKtgnVT_8MJq2eET3fNQvzlLilRsL3W7GSuBv1Nh5Nkaz
0T3JdBDypsEvlK0ljdfpfbuI03qVAXUzNy-6vBO0wFc7d6_NcssoCG1wplLslKGFlLzSwA6dELDZzVodE1y0FQK93DBJnzleoG3e5VFfhUVl4p_JGqyZzNpI
2ptqq4CFFVJGGmyzzD133ptqq4Fll-pS1wu68GW4O8Q0axd_WLyd_xglfqhqIzskp6Awwq3tzB1pUguIFTEBitA-yfxfvKdlfzu3zMBCArNEDO-vbZxN77N8
AMbeUh7_vyNVzzv9RnRNrZFaj7KIXiJB8IM6VNFelBx9WX9zFhoycFVlA65sDxPEZx_lHERkC2luzT2cG_no-E_lp5He6nhwG5X3ePAseT07kZMKAcuRyjO_
BwXYEm9LS1RETeRAi7Qe4hQbKDyAf0fXMmBRbi2bCc1xogurS4h5RLTKo-u3fKBRLgXZV3wFUbiOUXXkBGJr4BOnw889MvuFdTOheKa2jZ1Ww8fkUqlD684N
jXYyY1oQC6ntgJkIOpLyeHk67Qc6AhmZEuTtHEVm3WprmeIL0y76ZNSWsISxsCs18BKyqc5VEP19hfnS1knx1-3BmedkkJqu4000000Gv6yzoDKU00000000
000000000000000000000000000000004
}

