sprite $314 [93x93/16z] {
xC550G0X002mKwH_O9m8_BPTHm400000000000000000000000000000000000000000000000000Dp3i_r_R5FEyP_VPwdidOjskpWFn3EZeoFn_W-ybtJF
dtPLIXCZ4XdDTyts1lmyiYGRmB-wlOLQ7wXKxL_viY_xLwfwv_aYZ2s8g9dxCY8tDv6p8BO0KjMMW-MgmiIGsW95rMn9avkfaBU3rQA4MIrBxdPaB6t7sNAw
N8KOOjYYQh3ScGJrIHEs8Eg-l5fkocRncC2dewL_bfb_qVASxFULOUjnTFSANEu2F_qBNpwHSfVPuvdhhopOWjX3CvCA_jE3NJL0LHyojRG1zoBcBmkpurea
5FwwQMDiW2EsCzECrXP8-LLbOjyQi0Nr_Ra7GEuwXUmUHGoWBUXU2midDdPsgipczslVcGhnWWwFs4zHeFdzqVQ5KdbTun-W-cxyx5pbdRiScxcCyTQYRJI9
yVQD7-NbZUTfPLL-7UhInYkI4OZvJlZiJDC4jHf1WZPUO5UdAhKhueF4B00buuMpUojbEeZKX65NIx32rI_joj4pdhyhYXt_XNDFAN_kqCjEVkBra-veFxba
lcAS9EzIN0-UO9eOebU3vvmfSzRfuSsLQMi8djU1fvWj0zE6Lqgy33wTiKA2NGEVp5dUCWpA-OjqJZiXJ8cFOOHEYiynvQh2-V3mePFnsNpuxDJW0b2-YC1v
-6JQT3FVUQ1iY3YfQItpJdekvwFB9qYVThaF9rL4bDy8-VWKSqrw-V0WlnRJorcPiqmtl81T5BDRITEO3vuE3_Amc1jYRCPyKrustqKXjQRL-UAcdcOy4i1Q
itF0VebJHCVD06QZD0VpomUTpNoQMwRZ4I8H8FA6weAvhAVvy8X7Vo2lBM6OoNg6R7WS-9c4XgVCr6LXyfJ79vadv9tpRRfIfCBZyvvDopjbcZqxpbHu6Ebc
PzNiDisYisREUHnadvMuo2GBGuvCUCE_86d8sYIpdYJ06otQ0hwCwQAia9X-1NWl-oLHEaN3HVAinu7hdeuFCsmmGru4GRZgu_XoqawPm7gQ3cyS7rAoDPiW
Pq5Mt6JoG1XlkB1yfQvl22_YOrBOAIdP67yW1rzSUEnSnN7pOJsZO3v7yOraXdYnXBcNEtymHFTYez8jA7mVF3XkdCD3NHWDupCdYeTE2UN2M7igykVny-Yp
xEFFUmoTzGEdV5Q2KyvtCy8oLPZrPyau8P-5rrWl2aUjLSXteLDco3WZFGxv9ALhYc5wCUkqogMwtpRffTia_xT6UZ7hh7ohh6xImqZWHCwInM7qw7L39pUw
P87UYmDdhDc6w75Z_9QbvzWyry6hd68-3kMS-3xfhZlj6RRETIZZJDZYD1uwkLNmbgtsvD2cyDOF0q12w1ofOLYtullXo1dETF0QOxryYD_z_T_dSEYC1u3D
Qw1bssH8IIusqzZeYMz_1JSTn8JPGr6KdYNFJf2lGlZUuB6VwKd6HK3HQKzJw77xzhqT6joYXyFfeUh45ohLnBnU_XN9B-R35voH4RT_Dn9sPR5ghPv2xoiG
XdHeip2HT7hrwtK9FRuyUi65F_K4k4ClBMsfMQjhIZ-BFz33cbTofHUBpSoaCsRUJM_l0cE5XVl_2VHMfhdqOgEwvW83p_FUbvAPl4Lwzyzu2JsMN5T7llUs
EusKM1hoTWgzs2yi8sQLgTYZXziFz3u-1Nen9Rfssg9Pz3X2x_u9fzAJYej46W96llUs6vrVu-P9zE8gPz7beNplWIHNV97U2ky7UaZOgrPnYIySSwBtua9H
fBSoMnyu1oHaBK45Evt8YHVx5tWrNw072U89zAhqol9NHlRN0VXszBGqlLiXUk6V5rhYgn4k9DB3KP4pOxSQAzDZ5Zsiy8J05q0REUTT8Mj9feTo9GCydnvZ
CDsf67Pt9I65dfLAEcDd_UHzBN8RfNUxDhqbZnxswF7sB3sctDqIaixhffmnlCNdF3vDR-MVSp7qqakpszSO94M4nEQZ7E8_JP_sub1kUldtCMGb0JxRmdgz
UuZctnmXcHl0aNMLyr_GW3gHC_z9uZdMaxn890NVYR_3hy1zwsCgI2_mItH9Vk2SdrwC5QjiyvhKVrvB_P8XqilaXr2Q9uo8ffV0B_qvPQcx8okrEIE_jpLV
w99UT8qeqaie7-IF4goNkKMh1hq4VebUOOBrocuha-KdAUT-BdMKb_AUBZ_A5KV6JYJyhgph8VNeHRdWEBz8We_JbbngqCldnmCS4n-JtVJMlG1g0TjnvP-i
IXW5rrrTNyCye6d-WwnAW9UIWoiAqUFTYRRjF-8WV1Y7nnFkwh1Az3u-GWA_Ozel7CM70A_fITW90ERuZp9qzI41VzEpG2y6qCXl71_6NXYT9tWTUl10BmJG
m-AdF4q0uKTFsQLLTniyg8VxJvw4m0T-hka50nx5ZoAFXqy-2BtfxVEJ0NmFy0FbgJTwDBqOGCVz1v47S83o2Boc5mNrKNuHoBu3WVYTEBDrM9zU3A3ZyPCI
HGBu38uY6vIp9JFHYoNykF_aAV7i_eNKeUUxtwf-63yUmQuN6UWF72h4jk9dDZ-Y_jsevzEB_1Byb-IxzbuKrGxZntpVDRremAFY9vYFhYDdp40JwhzyTEsz
MCAFzpz11d09vDfxgoXsxFex_kYMglPUd02Z__BLtXixLAgdyMllvJ_X0chVyMll5Nd47CGJzkycghst7q2z0B_sNZ1W1NxjlLZ2L-JNz680FPzVhywEY-Bl
bB_qpeZn4ju5_JB255d2C_5eVWg_fkVnM5CcG5CqlJBl_mBZ1FYs_DfxKH8Cg2n0hxstcO5geRkg78My9odNGYmjVlRTb_aFk438O9Hbw7LFDcQWhe8wzBgZ
3l7a1apJonHeWLytgGkzxR46Fwr2BxvYlFa5UdLVrvtFpnLlIq_AqMj-eTNIz7vkOIiAN8ygpPPy8HI0J02OzLpgZlDusmPCoEAQtWQ_Dzo1ZVJwTvBtv4BV
i82GfTJBB_M5dI68ZTs1r6-o6Q2Nq01rmPjuJvhUBoIX0EGygzNvz5xzfbM8ZXVm_VP4l3ftMgL4dHsIlGk7xr50eDWRks499KFH5TpuvA_UsL8X0OtqhEaD
5u2kx9NrVNenMBoUNqnWkjoB1_nc4pKjJe1zyrvUmPVVmLRqDlWDUczun5H_nGG82-j3lJuxbe360DgliLcLLV0T_nW3bsG38boA0lGIQfoi06eiGwyVBmEe
nxTGexS31de9swYI7cEW0kJISrQXXmHwEKj8gzo4cGcSurP5IuWN1G9eoZwAX3cawMq-ofNlkQ6iIuOeK9CVGy4mZ7jRMQ813LVhKKT9fVt3L4kZfw7Zsttg
X1JKmxoNyGBixbFd251pTsRrg6FIqbjRAhtU845DhnVMetIf4l1xOJrAyjAMaeFOK9GUhmiFLfCUlLB4przOrwB7lTY5wLKTmXQw5vsqbEoLiPCMhpViUk8h
EtjWwNgTTGVmqXEVrgsQz5BrEa0I5HSOUk83vKDRswXh1ltjWmU9QU397w5aYpeA5a9d6AkSWvvyqjQhlmfFVB8rLZcPzKGuy33n6g5JP2fybC_QlkMvQglJ
kNcsc9QUrSxQRADWby_YXFJYmzKBIhuls74DUbgzrxIiaglHWuUCisxMQNFIYoU4kCPIkKiR1w38l4adOxKhbRTrnE3F46YcmKVCiAydXaxdTFLU39xSlOcg
wDwaHJ5HhoKA0CASKRn5hs7cI-XpzXrmkIliCOIWm1f3xuUqOBx95PTN2akY-UQNp7BEk9JvOdiUrSVXvROdwJpX1dQrsCbWlThcIpYRAWscyh9hnKwPQx3A
SgNOoMMLJ3QBptzBYiqMQE2NYPs8VVcEdTsSU7qQDl--UFYC-JLzgTjowSQIBZKpbsvCnDXfS-BJQViIN9R94q_enBE3VC6dy-7JcJCpwDpuTEx12PiPduQ9
ON9yd3MmE2Pju4wQUUfoWNQ4-1BgllcS9nEt0USxKTYypeiXPhAMjTZ06PKCCgiCSvsGphu0DbFqP0AyMlWAdx5u0NZ9x-vreln0Z65azinpbMA6KHZWNGMV
bJjpMfp0Bo9Qv4VK2fe9oNEn2hTeunFg2R6_sk0jcdrA77g2sxL4Nw8KbPALsB2zLlICKg90pBnSr8o2BAigh1pnEtOUekQrSiye0Gvvy1J3v-7N2vVBDVCZ
KPG9ZdfIhSWuFeZwxm-pxRUu4KVGemm_M0iQ3ZBCUFrkrY0bC4eFOzu3GvAPDK7Nxrj71mhn_ECoyR_FOm6psUtNxX6WFdRLyKVXymC2rIAw_KopqvSeLmbN
Fqq0mqptOqUw5IvOa9a8aGoEbFL0HlBXdl-Yt4n5ilw-chalpMwi0RmlLnNSDOhiBltMRmKQwGMwKJjE59B4mn6I514riz__jLrsBOWk3yhTtUuI4Nx-D_3r
iuZTvV_giR-XR7O3FSKNoXzQEcvHrDy6tSE9IWiGVJqw6mcORK7tbtdEkpeufWnxWUUaJNTWwyehasj1nCmzDrQgv6MNBLBLZlUXcwdo1CUr092YQeTmqpis
DBWNlRxfl-R9yekeUl-cZyRC6xtrjiMxHFzkZmve000W081j-dS60GImly9liVwa0G00000000000000000000000000000000000000K
}

