sprite $314 [93x93/16z] {
xPY7ajmm34CDG8t__yCPxVYSyzBEmfkU6CbrpHD4KdNvUtJhrgrRjsu1m8zcKhNr4Pj6RrNy0M3LiJ5NnQfUzLsMMqprLeJzK4hhCTNU7G0ckXUUTbtwnECT
TeaO5I_whn5HhhDRH8Ktl7wLtMEOuLH4nrKsxDoCQzxR8HkSmX6z-Mn5P0Jr8QG_HUZ2E7FR3oWeCLVMSE4rnn2V_LAfxn7LX4SaQ_jO8D7bMY_JE9xcEvRp
du5fNMOPbYUh4DD8da9MpO9vbCekQrJE0VPmMd5Pcm5FFZbx8sU3nw-u3yioWax8ym0d2Oj0yIFUKWgchDbP3k7K_BJW15wjOXp135_332wYU0HNT2kVow7p
5GuSmhsC8ZTwa4YigSFQNpBbm7FmAEJVv732gCI8KRBr_8jKBdIMsuodc9QQN6KoohoKCV7QqvZxsglc4ZuseBxXCnrARBVGrz6nFU4f2G2e1pkhkF0frB73
J-n3j9UDR-P5VUAzKwuFtyJsdDeV1b-ZO-1JpFr5iQTfPLIBtOOjuOqwjqCtyTMCvxbqbXUaS-_rjONdYpvgkafSN1KHiPohZEWd-0ZpPF42NvnD9iiv8wX5
DBcvoWUk5q8Tmvj3_cHujnBzCu9HB4Qv-0BSVAwdOOWsMyASsFx5Gj8bU0_F32DeEv-2UuAUwiOGxVgzVlCpRdFE7VV7ky4mdAGRj6_b-jtVboA6tAOhsnU7
zmY47j7UUuHgJDCSwH6iB6z88o96vLSKGNxwiOv8m_EblhtEyHC3s-lSg1dj2wN7flspOeocvRl5QNElqQkm_3Y1r4F4MzXRjsxTklK5
}

