sprite $314 [446x446/16z] {
xC6n00000C2WV_x04wa2000000000000000000000000000000000000000000000000063spcGxKfu9eWijxb6-__l-usVtAGxHK9HIaAgucnviOyGb8gcv
7eOjyM1CVuj2CcrD4xVWMkmZcTAjXfvB967w98Y16A3FXdo7haeNgTKD5cZGvjoYla0fa47tPP5hKQi3uCpTduyGwCQCu1ydyIO4NFoT-vYxGW3ncJ_3xUr5
uhbZT_zKNYP01E_vCyzgAs1OVpfuSGjywC-v2u37dbbOtjCF3l6sFxiZWaTNk_LHQA9mof-3LwqdBEyF5Rh2-eeU1zcUbbTtpoqlYi2NwwFsyk6hsrEitQTV
pQKliGY-CtZ18gFxA-KLXUzBdrYnzPLShzTJX-KMIuNqMPxriMJBV8i-iSpLqlSLoMFPWV3jjUdqkJRRBqxVPp1H7aq07ka3vAK7JZD7dvFtcJiDrlSUK-JH
JeFrNOrUOkpkzCTtt22QwaxpbDdkAnRQ5N8NYdipmLsYlnMxytvvcbjRnaDFkoCY0E3ekpJkpXlaxRs-NJhCF5NBatmsxgK9tlh-c_JvaeNtNI3ypRRdthpO
Wa_Gv-XTbv0v-nQoDrDUdBS7UUb33NhBqmFiG_TtresZz-dFu-hSmeFbHN2JFaUF8RKtGnzBH8-yv2Link6R5JtYqVfOm5xUq4lPacyq8EoDbPUoBLUdZXu0
etep15CtndP9ozfhFzmM5wsFpxQ02DyonSdO2_tu70RURXIBBnuzTdF3n_8OFKO_jOzO_IhH-rWVeoypOE0zRhllgBlAs6klf4SlFtoqTXY-ul86skE2lCmu
jmrxrSEQzfYQ4yruUx6CFL4pdnPL3EJo2QLN9EpLYzx8viosrmPaJnm1ssivzXXbZvNjCSuUCP9HWq_CZaNkePRoaZAIVoNB2NkzhZrTVOmgJdNazNysKi8N
ozbJYsLGmI7ZlAlZrzwWK6lnXUpfiIUQ9iROGrusj1_sDGqSg6n-i7Zu-Ej-Cs0y7J-jNUNnX_I9IYrx-QNHJjXh1nDIEHfkhtxsyksnQuzcUxdxFVAYPNEH
ijMvbrIzSHAE0YxE_Tb48rxjeUmnrHwsTwBTE6kFDjLUrBJ717lwgx-QGb_XE7kQdczFjoe_tyW0Uud7mVQq5TgV_t_rom1xEHraUy5EbRx-wz1UcpR_RU_u
njtc7mdsYcTFJ-lfpSc-FNw_Ua_sUaLxCTrUsx7tylTfSy_spiVZx_RQ3gJRYuBs-XHx-glo1k2MT7lOtcbxQ7kXxJbx-eIxCtltswFWu9jgxy_HPfIz0ZLK
CNiSFZ7Y-bKBpVR47YTcxwIz27uGpwknlUp7HRYSlH3_cvizIjkBIAzE8UzjUoqzUqG1kDVUQKz9qTC7Wo_EtjOLuhNKdBJ7d0_hS_OE-esumBuyPqyCwk7w
ihVhx7KImrVDNlU7dsI_TjRsDdorlIXcZzwta7ES2yWhPw_l4QE0zWjPzcnlIyQHJjWajhSFmmzropiXR2zVtrFbbRtef7VDZM_ffo7L7hN2rmKYVyNV6_UO
YlOqFEjuap17wzgZ7rBXFU5jJyF0Gyx0BIL0ENlv_d8-2yNPwsT9-1oYX4y1S_OKm_IHi96KqxcIlUCatgkllH0vKDJUcIOTPA-DsOApjzdLlForXC-TJO3Q
zeu5pjMdVzZP4xjAYhxB2ZZpaxQNcx-sXKlk6hOdRjsa1h2r2_axzpFEtXOOh8_shZyk27VsilBNza1-ysdRpfw0J7zQO7lBdRCdOQG-ckRmEuXqA9wzv048
xIh412fdJpFC7z4kCV-GK2vx6iRr9mdo4Wu99RENdxyWpvspfnaNmBHvv-nfcDsVCGndBuAP0n3Y4iwUXXZaZo0YgJ2TFGrItoLsp143SFRI1s2yg09Y7CwU
Pe2_P9mz3PJJv-pf0YsmTcTlGm5_pfwcS84wUm4Ko9-pfu6x_VdnlOm2ZNpyl9P4VzXUWV3f0iNsYhGyXVlJzY8gvC_sD530d-rfADYVsDul1VBdQquDKS2V
iwUXG84wUzKBrDdJz1tA710N1KpsPtlv1OhjrNcvMcB-R2yVKltPNlt-jBsA5w2sjsR-R2_VN_SpokfyJgxmLo1wlcT8zMSTUxvNjgSAjBtw0NHprfz_pjxw
5w3Otjl0K_pvyzO7vi_sAdI5pXzLx7bEf_kplVd--Zr5P7l50eXVTb7uAOJTzhByONjLseA-HnbxldEexq61IqxRqmNgYvOg9nnz7ugSo7xclX1eUs9K5_Bd
x1Le-pwfGSMMVPCXHs2LwFcTkOG-sokornIsPti1KTgUxnzYnjp3sSlVOzBclxDNZKNisPvts_Oy-EP1uUpPNb_OdelJzcpFWyzZJuVFsQEmFMSlwjeZdep7
dWSVhM5xDTdzA71Aj8_jjLz4z2XS-bqjbzNajSOIzkXQ7-sNg0_j1N7wLjQdbxjOz5fZFNl8rRAEF6sFsdUmTxtSrUorHHxY5E5hQzb3sEiBsUl2thBPexYy
u2ljKIbwjiUHFGhRs-fZSNjYvXSVVAZLrcV1QnPztQBbrTUtitBAszFT6Kj0tVjPD1o6BvQ1zHvWwM8P1UJvQI7GvKA0-09vVPc55DFbv_JqIkUXesTzV1Wz
stFqhC_oWk_InsAhxI_Ww3byZjuiUWLz7lBkpWNbHRz7dwFdxlI0fx8-3uY-mRrfVPuErfSo75ZRNdVqhC-NPTRdiN08GfzhiwW-bamUiIOhwYEXKPm-9ozX
gOlvwpM6kVLPNj1tM6Wn4T-dho-o4c9rY3Nq9IoYxC8x7k2bsxDxUXUXjhwKdQ-lhrjUwVRibDnj8gplwQSnntjiVJozCYql0hfcqDk6RT_Sfy2vLeVUDOom
HxGHzju_pUolVswl2NjsDtByQHAoDspl2DEF-C1UV6AFFiAT_N5H7zj_PvzJllhKtD_bpfq-PFSR7BKJzgSXwVVdkBD0pUpVI1nYVyb7jLyaakJPNpvH50k4
E8K1dBens1_nDeQ0qeLfe7XVEeALwz8mDOHGqvnZ6DdcJFaXPm1WG4i2GTo6WU3TWWGhYt-t1mSo000008FyhU_nLGC00000000000000000000000000000
000000000001
}

