sprite $315 [96x96/16z] {
xLW7SiCm33Ct-VyFzwpimEbHIc_Mw8m700wDq_PlSUB4YHCdJfnWLdEF0NTJvh-ZjiWwG8P-BoAHLp8t5HuGDRzVbc_OBNSEbqEVh3vksogxPbKeRR-0DAfo
AGQAgcWacFVd5kYpxKkpakRfe_qEWq27VYgNam9nI4yiEvY-zQD7TcXmywx1cA8gdScE88C8FS80UQjiytl54VrBA22GPLt-BCRal5v20Ma7e0VsHQ0Ow4gw
pQEO7OA02BBgFVx2zA1RlCIz15sVGxEybu3vLbmMz4Nzz2C_RJ8qY3yaA7e5yB9ZVkRzrnW8m8yl8ZxRe3lZC4y2_13uPsJH4J_HbP-86VBVBp1LuRLHMjwJ
j4lGSKjHLOzVjqv_SYTo15TL2YO8HrndNa58xGZ1070-McbGBVUXm33Vm4VWrqxxwqQMxmeaGl2XFG3GXCIR0icLb4Y6UuILJGmlzZS5be6Xyu7VfuOlMRx5
mCnCmBxAFz8q57hG7h_Y_W_olUxVeSd84XIQzUqscKIbT5vT3fAZKbkbwozVg62_yxVcdnT-LA36lWdGNIN8A_qZINV-VxE8pSGDP-jHQbOg7V57Ttr7u9ZZ
nl1Txc9Iu8UHsMjGHByzbylKRny4LST7kxo8m09qwzQ2hYKeks5JGOV-RLluGW2KVLEKynNmcQwswHQIkJUYSag09oEcd1AGh9WkL-b4EcFz-AepcVhIU4G5
sh-1FR4pkyOgZLzE7LxEETYogfpMJpzhbmWJ9ZXgkXwxEg-otnqEPCOTrsjmVBa44eyiG8PzvHpoeMO-O2hCs__6YHCdJlm
}

