sprite $315 [93x93/16z] {
xPY7jfim44IrCshx_p-S8vvBy4h7WqaFDtaThcRLAEddSd5nSN5nSM40cNCc0VjnMkJQkk_fhMGxdJUtcwstMhvuDDNhcGQmcLl9iD19kMvDL7oOUgWhr-6C
THpnIVhitlFR0CNTUTXTtOjKNpXGSbCliHvqToGLthBhOIm532G9czafkp4x-CkyVRP568aswSId4oGMPmXWacCdHB13ZjxY-DnYh-rL75EBAUnLHeReNPmg
BGP_rrhg3csEvuKgDAVtope3E1gW9UFG3YyOvdhJkZpjkPaCMrxUYh7NqxgqcDjKpg6x9u_o94t6x6MH_1vxBczESJoZ7226rt3hSrkU5radkCMqORj_JUIa
OaNUGuIe8eInYdJte0SjRWUVh57VwDJt5dqkchUK-wlUTdQGqrJ2Vjj6qlQYDnBFRpalsHJvmCgB7YG1R5yMWoN8QxgH-qvlmxjGo_AM7h1j-iXv-G1Lq-lo
7PPxN5RQW4hJbKtHkqlRUGJrhTwq5Rg-uRIq1jvFZ8kLjLxVkBYilFJreqJsgbqirkJkRTvuKIuM9MxwSUhOB1JJ4hqyLFU6zHt9oL6tNAbES_qeVML7zFhq
tZn-roUEPuInq-LjIzbTy46lDB72SA2-hlM7EPsiTsKzskjs88vrOLvfJuhd7xYRMkdnbmNMlDlXjotGgkpXIALdl9hqfghPfs-Xzc__4c3xlVtGwBoUsYlj
ORVn_mPozKLr6go-qMh9n0qobzfyqCj2BVkxpsa5wJo64RLt_-xz9P7-GIukBYw-0G
}

