sprite $315 [93x93/16z] {
xC610000082W_QaNgG800000000000000000000000000000000000000000000000000000083PEnCrnt4L2ki8-C3l_yAtNNTcij3EuZ9EaFZlMjErnRyv
GelJluTuHSsC_m_Q5r80016nY8hOyWpx-Jmc8W0VKreGI4HKpMpPWwcf_8WyMMB5elsm783z81pii028HMs9maI8SBZ5OlNcn8MWkZfiHr4mky4j5ZEJNtUf
1S2YouSmbTqvMe1SLdx6O7kJ0h9x9d3zRxlz1timq_TIj8hEThJzkY9qGwCRH5TsJ3RifH8iW7VKhRwOcG3WlUKPPbv5lYEGssCALdkjrbJaWBKk02IYPg_4
gfcqJGgILqOX3PYFuITLxRb2fTAquSwUDe0C87ejv_q0BQ3sC2bFcti196OFo__MNq7wPHqxyQCSjLT-eyhCJox-WrZisVXNg6qb5F3vfRgD4ZH5Ay1R3Khx
5dXZ71JK_CwYLZRYLt-KPr_DzEgCqBwF-mYj-2JprqEGeRcgxXEIn9tFYXhze1dlOtX_Dg4-zdMNTgoMDXbYBZCJfyPSpGjikSMe9G9aBZtdbPTlsHViNy8a
i0sGEwHEtupoZCPOQJ36VF8Kmmm0Cfiyav7M6nHpoQEnWaGmaJp5Q4krKl8oB_Wf9f4dGwxNyXGRGiPZdeQpGVLXs1V9O-lpygIDX0o_vgaZtvziO-iJEtTe
Hr-Xdt-ju4HzqWO39_PbwFHtS5RdoINl07MUZbFqqR1dMFHKTPuUzHf77VhubDM8Jg-2yAQQnynDGwIxZ_gZmOO-VrCQVSnT_00e8sQdXD-IwFG-FNPEA-EL
dfvNUF-VvFtyg_yXF3vzoWoto18H9o171_usVOylFtAzTN8GF0tgNjqReX5ug_9OyYHOdbVdwS7bPovfCYEnRLX_lv54g3woWHeNM6YIx8j1HEgJWMOD7FPQ
l8NT9Hjul-R60aS1E7Tx_ONTi2qr7Db0kz3y4dsZ51zYSjDV_j-MRezQaySO3QS4okk_Nr_hGPC-6QFXnEVbUOAcxPIxxVGH8bycpt-Rc97FQ8GLpdOmHsLU
3ybE6Y4wWnfEVz7ZRuFznPU_z0pV9y_hGz2OaHB4bTwHenKYXZxaBJuV_XnLUlYwx-RdIfIzPq5GwVM3RuQOu4a-sTEeqWku6mBw5kGEJWGjJd_FT_HmxkYK
WDABgfGUMdoSUc-8W-nzKpbxDFN0vtB_w3f1o3UD63ao1wVXwqhFStnqmX8FV54T9sAEe_J8w9J42oqKT9c3Reg8zAdvWe-uc40EkGHvTzLZQYHigpuYVZZj
Cfd4bKXCKKSC_McNoQ9wG_-0YNzZYBvo-UYQ4-nnLdjqiHTJ8V2PjzBXqz1_tWgsehC7HASXQTEYqQDJfoqhTvyAztdH8weBe7HDYvngpyjwNdk-h8z2ahOj
6ZpRw_TNlVUxF-gqrruFkOSpOS6BdBYzxBYkjgsZVjsfYHxuA6VRWi15JcyFjtzwzNdU7iwq1qkvKCtHUtiFhd-_IjDNxFbl7c4FsUVgyVOkPOaVZRZvtATc
8XUgEUKnN3xHNhzfMdhxcptqFo3SdczRQeDXymBt5JTeENiN-ZdsEDisWzzMZhS7P-MPFQ80Uzdtr_qjTwwzZfVjqNRJ6HD2rRGyjFT6Sgxq07kEtFRuR7j4
c_OQ-hMa7f2SkKz7-6bEk3t_8BEpj_5T0kmbtoJoImodpzO9NsIF4cqI-L_v4_RwKtizofudipsPlVQQfRCdyVRmgzhxUzVIOz_yWoRUtDk-mfV__xXheTul
ykBj-GtQTFPmXhtrmnN_Hw0Ljucx5PonzYJXrcpygKkw0u_ihSHCz_9lqCRtMNXg3-qbU_saSxv8Oy_VRZZXp6ntKfmzztczFmdbURVNEJBg_wO9_n_DkdFY
J-CIqTR-7fMzg87QLrfO9YD10vxjaMT_aHFS5Wcd3FxtJV4O2eNRasnxiqfnqOa4Z-Gct6NWvGgbiBubGUabF1mXopMcb23YNEbDQy-MMqmG4fqzG-ar97l-
UV48ahpRJe-ycIcDlO3w2om-AdikAWBynLphxijvrlShesKBndTURCIKdfyofBQtA2Ee-EBV9xdiBMRypUzitCgUB0ynFhHQ4F7-yXFlyEdo1AM0zt4F-5OH
czNvxIscEAvWw01vlepBdbfW_T65W-JrLlQkDfC9lEtF14VL37stlAR9x5r-LrBRxIzU7-W2JcZZA9Mz5KYGlquNS8oyiaTsdnFW7VvYzVb3PhdE6foRyjWA
KFkDFxgY7o2lQc_h83M97Lz_dNQN7xpw-BC6dFSWDUXuVtsd0xWlJFT0tFcp6r8xE3-9zcZeT8OyRqzJsVD0xDZwws_xWtixrWtAdWTye3-lZpeUVtgdD-IL
FGT8xKX_T4z_iUnMMZp8RSy3ET9V9qVlSEOwRNWE1fRGdZuK0JxG7-Zlz7yXn-FKB7lIda1gX_dhz3uuVTtU4jlpa7pENq_-vaFds_E0DS1VaBkovo6p07yn
xigU1tASl_vS7TfXbBqLy67-6dgmkhBdORNZrZ_xNyq516RPSnteGVj7GFyNDBH0ojuAZlCNJzdpiDaN-2jxslP14kUlxCMVFGMdz5VsjgVmPaOj0MLlAq0r
WR-ojncWffJPdirXRtiARqPvxUdOzZoabYO_ovu74fkVTIefzasfGMOkFyjUdgVLV0UgLFRo_6KCn7QVduoMWRAt0dO1oaXbJsQovs7n_XBPuxdiUH3fhvxV
Y_zTsIoDF__iRAKygVDNjPV6dfz1c22HlUgF8MRk3PYop82hF_Phs4A3hnt6GwVjX_Wz95EaiLTxaNuJteoGnbxPy_bfZ2pdjCgUVoiHKsvV12UrXtOMqBly
P9IzNUX7bXRW9u1VPq_AtYQGnVchXRBzzgIT2pIw_iR_kr1a2MXRzXuYL2fxYVxACZ-1fw-nXxAtmn_ZIov7Bdje7_AdEtTmonwMBmXwsk6lpYIjE7iVWSmr
e3LXUCkUj4_YTt09dxGdhTM4xmqWdvz0oEuke9Q68Fu8KpsyzzhTfcYVvq43MW_lUV1bsv7mP-WfqUDVjPaCTIimg0b3y9GXyY4aO-Gvf5Nhic3xm1OIksjH
EtmxuS00ZJ-AMnDKKXUWr2AH0tk0Eia1oBASU8Z9qjcZ9M2E4pc3Dm7gEE0_qBUlB-0o00OlWYAVFIJOJYRlprGeSDKmeJrk0SGy1hzY7DjorYv3o6FmKRt5
ajgUjUy6R2VPQsdWJByqYPcp5zLzry6ao1PKWj_iemucHG0ISnkIGIrd7Mr9jsRO4c5bxmTrmruTZeYXDjPztblPonT1PM-5yitL_Hf3DIr6pP5cUxti8Mch
h6rUB6dlnhcMYF9kpTPQMPqdyxropTSjhxsAJhYTbZH8HIVbxTnucNxE87cl09RPvmpGnEdZzgjhYJeHd76nh7PcVNJAv7jxb7gsixG9GUwHG-RkEZLtzD3K
4tOaltTX6VkMMgRtqQaLdDdWk0FczHXLF7PozjUJ75LyrRFuufD95wWDcLz4slYlTIQQjFXaZBcI9Xxvwc01BJCMduuoNjY4nKV3h5BmSa7doqrgkR4bxzId
5WXfjkmalpW_IDifSxKiDiGOFjDEaGmMDReaVa4rHR9v-awCjpp1opH3dupNOUCcEwcD2uyuI619_AfgTYJB5OfHvOswCg4Jw8EE-XfXD_g6bxTWjF5yxCqY
-6djgDbfFBOy7dWgjC8ZnwOElUsr8XXMdc7C9S11Eq_Cq5ApqpTavL4R4xPbmDT9vXkoGQjlF7tYv4sZJrfo8CiSydnuvk_FO7F8yzMN_mM3_MkPJPyWgpnr
yiQ7ROZoWvX_6LFgKshP85rkKMfp05kInoS2_kA-h2F6YZ4okvDvvFdNlw99_85zT72R2_RwJ3DS15OlZzfim6nn62DTPfYsIV09bAb_8UTkjjJqg_FU7xNV
q2-uZm-9p81TvjmBz3v0qNP2LtJtyKv0Qr1KuRamMlwAAUFtziXzl0kmBewDbA_cqmdyf3rS4hDQpKTzd4U5tZNOwK9t7xy7mBupzYjZvUyuWVq_q5Pm-VXD
S-xNUdzVkVmjvWn60rApPHkVwUNl8IP2G0i608dQyW3RKNVbRqM5cH1MSCogY-EbNge0sV8SCrMbGns2I5LzLdeUHNX1QikBc9a8un_UzVKF8cBEsWPMyxlT
ywjjJF_0Fn1kQGrty0-YVx0tVyehPLS0Oii-x0vLksFPnplg2eZPyXtOZdt7WbY_GA3kx34BuCC2xO0MixeOEz-RcL0xW0B4ScOHwi4hSmLMXNQ2EQ4eSmLO
D299pKoLkOLJ02oYgiTuKnLX0jfv5010n28xyzJa3qJ0vxqLn3-eFVoNy0hzhpqu4000060OT7_gWwnQ3m0000000000000000000000000000000000S
}

