sprite $324 [93x93/16z] {
xDW52kve3030XX2Ix_uNtcwBFVzTO8QYTOjjNm0000000000000000000000000000000000000000000028VzW-314PcNNeVwXJHhxtJHAPMTDpMjUOGqzd
PcolGiJvdyrweEcgp6S6LYAogdlMaymHM1_-2ecidjrwljdLOy8faLcztc2EMBhTY8YgdlL6qtNBRyWHAjS7c9dAxL94rgmFqtLX65MUh8yq_RSeIkJjqNBs
vLH_DATZuvlCT6qF8bpEhdUL_xlyLBlgtSoig_sS1idgwplhl7iy4X5PUVq4e2ks4r4prrI0zVYPLaHKrLnp7HKRaNNfQ_kFlNFHRLpdWN07144Iyli_xy7f
Pj5b6oP18z6KhFdlbzEj_PcZeIws2166pmsyxgT2s6NtMjeZ87S-TJleCx4-Bxcpveq1Vk7Hkgo1aZoFvuGAi-ERttSHwoHp6o0IVPNVzaojDvm0V2Eu-O4V
aQFA4-UR7qayYu5fPuIkCOU6u07MITedK7W1kAXfgj37H8e0BcwVf8lC--A-WmejFREope0FkikFrosyVClCDr2bHLkyvPRAG7ADyeC4eyI2XY8BksQ-nUJx
vrhkoNVOOU4nGLToJz6rEoFmkeCVD1ZmbfxzKomwvF6QlUoA-11SrN8YNI-MKS9uNZQzqFGFPCBpkAysvt84goz_BLHzdE2QnTsJ9gwyQNraNpGq8MlMlsnU
8MsoWtUXmKzfVWVXZ-i8F3i-QDgYIVsuXhdXySV5n3CF-P1KUFNnJVoxoyS5nMy_l_itn__Q-7xVA_1P1tz4v5Rx8i94f-9JcZAno2c1lRLsUBMMVjQ0Pnm-
vCJA8xPsF5BBF2uXyoKNFYqhGnow623Z31VYUUPOyk6njED5jIR8nwUOOz3B7wh10RfGnaX_bgVoJUKqoupPnJBE7aUuVkdbnwo0tNCPafCBrQPtWb5GEtul
eTnRWcbyaqutJJEnptyy2g19GrzzxqJwByhjVgPi8W3-VHUWI6lds2TF4bmuUT23tKDdJ54Pt6y8UOhX9DKZA6C-DK0N2oHtY4kY9T4CaONFSCt6U0Mw_FmB
aUj9spVbPzcztjl_A41AQnkuV6HHIi-QHc_DpJJEMZFJygN7sNcbyTluvSB5vuTcvC9hqkC9aAoxKxtqak7zqgV1UOqxbIu-QAApUtY2Jez1awJxWygbHmbf
irFSW6GbJwvSV9ftI4-QWzVrfr5jSvhVrj5vaf8TlfnRHBNeITg3HIs0rmUVfTYJbiqib9TO3Fsdt3Yd-AvPUXB0wuUFCXvnhaGlRTJZCLFBt3A6Fave6Yh_
Mh11-P0pvbnGqphJB45Sgr3_9yS3Z4oIMG1WGDwKSLLjtOulFIW-L3JE-qUuXNeNY8ri8wdNyLD1O5A5h5D2uoJhEOL8GnV3kMDmORllmbIivVD-e4EpG1lR
bLctNvQZzX_rYe-YiHZjw3cBmODdHD0wbJR5ouPIhUMBpPmF9-fN6nYTQANV0bQZ82AKCqu4JjUZOAYvUpks-0nl_HWd3czM0N5ed7qtBSlu_NlKnIZey9Ae
DIwTEBallOo9P7l3AEBhZfxrOgqw7c-uHEtIysM3RXjDFIKjDV2H-tN6EQSRzHAAJqRKdhSg5A0N6_dXPPqo2r8cKbktSO-ZcC2bXZqyjX3fSrijQTi5TUuO
Ra8Twtpiuzpw6QUvkpgJTLgS4ywdzyW8fDjsBJX76oZgKUFsAAjneSconxyBjqvhgHoN141CT6SLol_tNWXVFsSzegqqvpXb1pv-7A5ORaiCw9Kc-ESArEs8
EiCVa_txtzCTUF5lB5qicYqyK4Y5EhwdCpyW4KAtvOM6y1nG-wf-ikOsk0U8yAJAtn5O6463N6Mo34aFaXkDudTzi3Fia0CTCJsqqU6s3ZtACN7s8EAZp-Gg
Ci17pT4B8yUeYodpqax9fiTt3F2Vbt6Agvx0R-ruZHw6F_45w2KyHswYnNDenaJ4TdExhzfgniJIxfJiOpmyV3QyG6n9dJXeWPln8UGAgk4l0AD_MPWRsBBf
nGFV5UZ5IGBtOwGqWJD2YvVeuuJKndTPLmWjz4AA5qU9li4o__zhDUZvZdFJao24YC-RqiwaXuIxLiG3F3r-RAwD0zCL1zFe4JrnzCQEDr8aSkRG2sOiIQBI
P3_Bod-Y3RBfUHLPPaXwY3YYTtEX5legDSU1sfy2VetUGPbhelbACd29wL5xj0O5SnXWDyRPzEej4ldGWlFfCKNp9kBo9hrAhoNGumAXfGIzendV_Ulicszc
rrx5HI8VMiwZzx_kLujyMo1jDvIdrnvAqBCaUlmWSn8HVSrdDiJmxFP_UBtsyB7o8b6MVTFp-qdslI6y0JKutxG_jDjjf2GaT0mrwL4-FNcsuTFkL9vBCErJ
N--EVxIp9MitqAQ76v4xy3oKfvjCZrnwfHVtykbvsqocbp_JMN_Au2jKFaisBQYyr-aXOzUs2vqhB-x5gxF2XE-fHRxWDOF3Ar-o6nuHpbgTzTAhq8ltciZH
JEXJOlyqsDB-mlcI8_6mOv3STwtgQVHIp3kk1_aAaV-Q7JrtIBJaFMKnFLiySZeWvkZTtH78Rz63PPoOG49agBEppPr42kar_dYR7hawNYnqvbT_V3P4ccTd
-7YJdZVfn54dNv94Bpw50fO_QxFDp9Yy9tXnV0hbSK1QTLUW1AatjLy7GCp-e1VkwTKJO2tXgueLpc3c5R_VGfkKRYrhs5bmXI4sD4wQ5-3CKwlvIlr0C6U_
TQ1XQNfabiYFSeh2qix7dqoFpKa9ITPfASCh9nzRpQVd9PHZdOqoFXYGu5obw9aAKlA497mmG58tCkVBxebJweB6rpVow2cgq3Db6ZycMUQVi3uzpm_3FwN1
epzGnQliXOr3KmA_X1Vwfxsrt8jFfKTcgVnyCoOPfRTmkqvcwVpQoE1YgQNtGVNe3Pv-OUUTK_piMAVI4miqi7t7kFg0-q1LBZqkIS_KrL_bp-J1NEdbqfC2
z5BgpuulSSBFNNMoHUr5CGOPNECXNxELz9b6EVKp3Ef8Zft-9BV_Rm2yXdHwUYOz0OccjG_Yy2NyoFIz4VaRgOajYH_iw6oUuj_FUZbw_mlyhFu6zEmTyC71
irCQvX8RgLaqe_we7Vr21fg7boVKeNSJFUCt0XywV2RV9PPqUdGYFVyxiUfmVlu0Wt67xoO4YMNHemonQuDak7zAEpgK7zdXuHKyG9UVc40yklxaUBlymErm
eg9xqVEFe60Gl_Zy4BqnuhdAon9AqdC9T9n_qlUxB_HBq_HdJdRjtKGyeFuyFi-FN_LCEqw1L-P3VFBIWmFMWVn-C6YlJ8d3cMwmqI9vdhyMFM-Wm_nJZf-I
HpyJ90wvcx39bfIbv-_OiFhZTeUVcH3TDN8nz_-FN3C_jfSUSi4wY1_kyZXQQurPS1Cno-sz80c5bq0lULS6M0Rv9zln2mMTngON6wWEgJ_8yMi5AMVJ2mnq
Y7zQEtwX86fkUg5OTOH_ahHVi0l_m4qlDj11_jaIF3FZZVhLTmAp3l5FVjL0Mq9MgNsIuQtd1Yn3yYUz0j1SFx_f_K8W7jE_4uiTiQG3katF9T3UyvzWDl_g
zqy9TxX9cvupq67hxqH4BF-BYQX7nMrwNg01_3AqwJqsKELDBuVUA7wqwKrmTX0aS_7RzBo8DJn_j3uzJ4ulJg3vzRVdEJksyCgqwKsndGsYb_5FBhYlPL02
hLn_cvvFeDFvvwRd4sYgV-uTWHa6ohGEG6W5UlhXDDP0LNWPV8xUMcKV9r2bvMfFrgCN7yLLmbgrnyi69f2kkG01hNJoETL0jR9_RdfUu47-kUaXvLfP5bk0
XvMWb-LXf9hER_ttjN3U1VCg_3ozgxWsQ4f-cvvFeFFpuulHY-UmLMZJA_o-2YyI-owXQUdfDUXv_voyWUSAxuIFwUK7K9cfWPVozFBvyJJyh0QzCnrhqWRG
q-FfTWBl1lxK-qTlrTxcXoBqpZy4JgBJxM2Y0lISRvVYPqpx34gn1OvOf3RL10nN-Mem5_4Ydgc1bohqf4mIO9rc1LwhqDCwDmXiGGE_wGMb7-IxtK2yHazc
6tRp-L7TXa6A7zpDvrSkW6vwxxrAKeMmc_K14tLPAxYwNr8MDdoRNpwz_5CKEu1wUjCj3ky08tNeQKbmCJyJMlxWR7xnpx-7Fdz3PVv1b7nHiGuULeWUVvGN
iIKCW9jUPe1HmjdtRcBlpkTNmq2v4Ztzc4GWAM6WVFwjcurU_4L_PQoxFfI_k9zle4AuriO4IPYhItoDY0XTQOwO4kZb6gWoYjwvtJB47RpFe8J4oBbYovbl
eBu4hx2hn78s9kKNe77sXhAzAR3dY-oGrsljbg7xk-YHDEJ8Wj-3o1UBUde5uzvk6M8HYtFErCYvDoRrS51rDpMFtjwOrAsB7tvqKmA7tbjRzjlWX-oCsegN
rlRMbYkzLtNFTEwedlLDWVq1ehqvmcjdFJ_TkZLmONqlhtjjUfmLMtPesQ5p7zsBNM0h8Ilis58cfsFUrstjOK-sYR-X7VJk_YvR815Xb6souWqsM-1sV4fG
StaeVfIsOCTVDSGB35fg4EReEMoj6UCwzEpuKgEwmzvp9-3szpBuAl3a-5SMVwUx5Zqyl9B6b_5D9ufsC9TFm7nu4xc2wF2Iw6wLxpxRuV1TWXuVNXP4T2gs
uA5uSY5qlM7Frnw2crMoPx3WGYvRU-oCghXr7edqwezx_addYaiUcnxQuSHnUrKxTRO4UkNxFTJUYa1XyV7XnPUWXnPTinRSlGoDSWiEhuzh2Eq-F2hLgZzF
Kd8Lu_I2DJU_L3QpFEvYO2uwNqSiPYQ289mhfbWlXhdX-q82yCYY2WaM9s5fxNyBsKllGJoeDTyYTpS9x9LRdrbAYPzQ-fOhlOgk4CUfBNQbDrNnRS4gFzys
SV7jnvjjuZFiUsXHv-jpQJ_SR66csgBggGuwSN3PniGp1vVjIpPnyMrRWjtrXosTmfLaU-SptzJgoSflDjqYcwGLvdZesuDUVKVIxoQn9VCyqR0zzCLsP3JJ
24qR7a_rE4CtlkXso0m9QzwXRp_BtYi4kqsVAmQ8tN6BFUZ9L7QnyR7DsFwIRlFyxa5ASpvq9XlUNBqlRtniyuPliOkRfypy_99UkleWPZDFs4ClN7rGSw8f
h-2YasPaJee5he6l0e-NU6xPlFYIy8ncte9wiTLso3BNp6ON6_n8ywuu7nzVopMDPi_EwvTVVB5OxefuyRan_wIkXi-4LXtnl1HBFfCBlXyUFmjFrXdBrxPF
iDftyLAkid1w8R40thBuJB0kEyNotg8h37yGjGkCwsoMmG_ElFpK5QSybAQyw0pWyCSKxJZQyUSVX_nzBRtxByPwffbWwNaaBnKQzafeVFyO2xgoKqielEhb
Pq8Oyoq4leEpa_WkErEiFeqxSW3qi6WGFR0vNMOD1Qmsi02fVNkJCln_qK4W6V08JjZxUIbJL-iqkE__7OVHYD7E5zw5-PanLVODOhDSTlNjqqkOK1ITgfbT
rJGzFmkbobGEdQZQPkVZPonbe4xHcTbc5_Xd8ENJJHHWLliLkytFLEKy5oKMVVRxqUNOnGayBa8Wk-JigTJdp5s0iLGuWo50BFw1UjoTRe74NfAg2DCOjm9z
SWkzChRCBKJDL5o91A17iO4uyCdu3z_eleiYWB5KHFX_4Jxr8guRCMO9JJ9M4AEs05RxbVIFv4jC_uZbI_ef-wKUzZ1R85Nh9RtzeuVq9SFS0hDOBQckL7GP
mRqEEY5iTB_fv5NFBJcLtzVS5kWq6vKUqwnR05ZKCiNSrootuEP2HXcbC8tivtQSOPRUfQWYd5HlM_WKC_ExrFvEr9p6RSlFfsWaDmzJr1-t46ZVcV_QWsC1
0000W47-rdFONNq00000000000000001
}

