sprite $324 [96x96/16z] {
xLc7WiGg23n4G9J__zwtvhehKNBtUkRgfipW02dwyZVXneqRDsxSW8IPf7n2c3B2ht1Zbg8E2kSVYK2MToQXd15J1o9cubBUDV1gvF9AG0YEQvaFaN9b5Acy
Sg-6Y5sZK9IUL5LmqyMkW27Z-nbf__YkG25lIevLWgXAX3wSiRmj077w3dG40lI0B2AKN84TKyMZHxKtL0778jmP9iupU10piJIpHaveI_wYFCrvDVk86gkP
JArTEfJdxgHczUjsCjFvsSlmQHPODNqIbEdfUUK-FEXWDDRgqv5cQGXYOm3SQnZ6s9BPfwAdgTr1K4tdzk13nCm6gfaNpRvIWPdHoY0ux4bZyjfd-BvgjGRT
eC-DRlu11wiVJb2rcbB_zTZGy6tpLo3qNrfExUVPLfEk2KsIf2gzceu0p1m777ZkYNLLvDRzVl2B6Bgs5SL5UXr-hXKV_zU7Kt32BqgdwNNywQZwe8UNsfgr
mvy9lvzWFpdKoqb4ZCMg2W0O7HNP5XoRbu-3A37Z2p9pfsRelwQNeAJgyfDpswr6pjPO0R7E7pJ8wiG8QrCIrUINZyuLgidaaieE2VhyZWBQanTgrUqXdpy1
7H8oZ5460L1hu9Ziyx-c9iyKn4m_2QbQIswHqAgzK9uLoCoK-iqdSJMhu1SXhziNg8mA8FQ1oYykyXd_y5GyAB0sirO5pvyGPCt_QTEOwS6N83yCMsZnQ1_r
1tx-ya3Av_Kv0iLLyEipTEa0BliAVDQ_7WdGzYkDdF7x590t5OhYGjh3eG0XVZ_r_dlYGa4LbgtX0uigf-KZe7z_NoAvvUfp-FTclvZ0yw34npRjQibE3WEv
zu5Sog86uwytqVBt1nU7Rx6Vd3XGouOwN6BceOLSzyHQ2XjZPhZC81topKmkyIyhF1txfHyQ1LNfyPMTztTCFwZEzGjy0E7wAoe_AVwbhqclzt3PQHzIlUW-
xytRYPPB0gIAknDy6AVdRMEXX78GFmT4WnvbZzxtKXcUT8a0YQOt_OBnwNd6mM8phDOczqgbU2zE5W2y5GwvrFDOXWKCP_c2WkpZs3jUrupUG2n5dUMNAC1V
G2gSq-yjW6LYbWFCb173fiHnuyOV
}

