sprite $324 [93x93/16z] {
xPZhclCc38GH4aWokl_hRKtZfn-BcPXi_pMpvurv4OF48Ub_fA---kghhoWpooNEz5zXkLJpIQPLyY_1_tBDj7QfclbBMZxjWFKLOvbz89RwUhdG1sWxMrP6
JRFq3kecdlHib1yysFbbXord0zgmJvy7NzmrxyLYJv-lD-F4okQUdx8bxKgVqSLTrlLK9A_eHkz7kF94h4NNSPjwPAuFngVtVKQ4QwrsHBHw7vMyD-KkBcdH
2bsp5t7tK75BM7PhYaJyEHu-ug15Mo2-xJst68sW8_nsrDZntZbJ6dI4fb7KOeoISW-T0Pkwunvje9SuRengFyPcALMOC7AwGX71O-2I9laGkiJPMOQ-rEwA
ZTELUv2Khs-9gEDyc8Jk72hJoxJHydAsizRy_6QdtoU71bzURTG5Mpv9JmCoSP2G12Nly7H4ladr2ahVqYphCw27zk-flEhSWq4cpnBN9RnOowcqJ4tS5d0u
ezLhMjcIEAGq9d5lBIzi0JEwc8zofl3HcbFxMvoINHEwp8Y4NvfICTEPWqHNOaZOei8NchPbM4I2ZPqpyHOlgFn75TVr9jGbSvGshvDoX-0bdDt4Jhh9coKt
7s6WKfRTijxWkONHi2_vSl3B6khnKRdm0xrLkcA8MCL75tozCf3OJpnPH1ocwYsY5RGwGNWNwqzyrkjeWKwH05x-XDN9d2n5c1BIayWlTqOy5eRBN5wi00yy
nolkw4xPWACydqLYZsy-6S0DN9007bGew7Oqlm8y6ZoUZQwiu0e6LiLXay9unVYwtluDmQ_KCSPdJRY7Ob5nDo6mKQBJt7k9BSm7nkBfcEksmfJ0YOv5nPmm
01Sl5bv0i6LOSD9mkdmkw-tnHiUoZstohiJPVRWOOatN5i49qOkWHXoRS8xmeJwNcKv7s_Q52o5NkkWt-L9TDnxOKtuR6Fd7sQWzrQ3aKsEA6xqF03o4W-Bq
LcIVq6KuVs0wRtio68xfNhRoH3SQaFf6yFqyBtiMklx47-sGrkG6hNi9Hlq0NOT6B4mYDBrDR21iX7TNoRHw2zDy5pt6rMLQYp3dVyGYfNRkCBPz4HVrXKm5
a9_t8AMgcNMacMej2xC-rbTV_GK
}

