sprite $325 [446x446/16z] {
xC4n0G00102mc_w1nG3RSYG0000000000000000000000000000000000000W2ZsxdDDKcG7ml1lvQFxlzrpresD7R8wjo4KKr-idN98-IAWgzrHrhGWbWI9
6uYm6GnX0n4v0o5m22Bd94GEGEJyWiWTRCSf25taPh7pR1z0pQ15kmaGkj2Qi0ij3RlK4h5BBHIxmUN25xaKKO3OQGg-y0LuQpztx_H0ts_9v-aPF-mq6UtG
B7xp6gKhkinkZ1RZUgC_zarQfBEXNRvXM_H9KxHAHpJxeNRW0u-EQOMUjG_um8CFFFZ0UwLvyE033pu37dnffSD7uRswHwm2U1zYqypd0wzNNuPZvznThb_8
J3xm-kNOrm8yfOlaGwyF0j-CQlimy2NYxVdGcsYdWSzOwJLCV_bh2XzuOlUo27nN6O5tmCsnqr3beOENZz7xpmWjCQmCUCS0D_2Xzzpq31e-y3xXDK8k2VBr
FcdTJNoCdYnx05-6tbmx3SCdnJs9Pt-ryzsRqLk9UiNeVTfgCtm1U0O-t_0P2hEjj67uq9knJ-GFdmqlQ_eCUbFFUeO3CdfJHoJsqEaloe-tGeUFqTCNHy-0
n_2vIl8lRuXU_kWPDe1UZbu7NE2bw2aUmyVeIT0pu35yENeBlU03Pzo4ezU_aHvwNBTmsaFll1Rq6BtD7NhBjnZuqFiLoEPsrMlByA4d6fTClxYPuNDUSRPa
euIUfn9PqGk-RlGIJdlzCRwUeRVG-tRxqYjF5PF_lyX3UkWjkL3v2NMZv_-8Zu_LBsbq90VDNl4cfoYXb_CcPxuUUhtHatEWGy_FvzVJ-zR5tQht9V6NBVaN
BHkFlj3hINheRGweejVlhLV3zNPlbBL9Rw7thoBNbpAJzD1JaKiyVLBRzUgDzVGXMpoz4xtbrbE-pJCsUf-7Xzx1yEtmtbwlnioUUXo_DuEU_yJt0hPDJuzQ
w1tXjUihHmkzRdr4Nz38MN72x9LVRrdq_hcXM_4qNsxV-ZHwT_2fdcIhzoNebKElh_NMX_IMLmyzrNXTRndrq5k2iT6puMdG-oVxXTQ7opDyUZL3Z-_VozHR
wA67tXlyvY7qFXbFQk3djMJfLHc6BtRqrfgcL_bw_Nvw_8J7IBs7_NvNlVBfQNA7hz6JQd8Mzm6y0BsgoE5hzBuaS7aVm4lHgpBm6V12BpfhdwZnQFJ4BsQ9
zPNHgxflZVlsgKQlAc946hsd-Vf-FFIgflErLw-SUgzOtgJNVhnylSVybC-Ebw_td9_ofUAfddtR1tvEFdsjTzRR-qtZwqRloC-_vleww3tXrp_bq_3GsmEE
6B_sugqrHS_Wrn8dNhwUPh2VFXUzP_rQS_v4grvPDstowpvmQ0FUOBsrozD-VV1uz1pprtkF_OFHiyrV7qJiq7FvtO67dcQWtq8lo4_fqFFxFM27dcd-pl7G
qzZyL0uzdv_c3ZlqD0u_fKFFxwU4QnseeMVmCmIzF3_qD15-wENxePVlXvx6uuSUVkXvVdmMUlYXP_933p_qze3eFR1f1X0zWn_Vny0153s37thueQUPvOSU
VXMWXnzw6p_qCexQ3_gXXnzwUq3qeZPk1KGFFgayG8_Z9tg60KGFF_HyVkZXftffMyUlq3FuePVjXnv-wEq1qJDiVlG0eeUVb8UUmG-z43_qy5EzjEtZL-WP
lWGDFVpGEmP4xw001X0z__oXn_n97Jbw3605wp5_KWCNdIU0w4a9321wCxyB7ZtyEFKQ0D73J_Iuw8pwELg5tbs0XLwsNxs5NZwV-g6N3pZse8MU1htiHEbn
sQ8nuA7tcOdIuz2faLxG8-Znq-3dw8677dhmeKVGkpzSjA277WTEzYFq63xq27hWeOSUVEWHzC13Z_M23ptq5dgC7czreWVVNRiwUgmLVEY1Xzv9M2duq0EF
mpbw2MMXXnwh11zwu5LmPUXH6gDdgGqzYWEFuKFl5Jxmq0CFFaVG0my-5WO-zC3BgXEyeb16RmGVUDJA_kml5ZpAPJNWGmy-nOCFFFXO1_Z6hG9yh459wU31
1zumFl3Wetawe7NuojmuVE2jkcm4F5fXXwKRseMl9BHq63gbATei3NYqnWvATxHtqb_HMsoBsYDs-FLtaHi2cihYg_lmkkMMoNRugPvo1dGJnLTEFNyd-Nvb
qFDraS-dIJdltTO0Vcg5tMD-bLquVXLGSfGTYr7OoOA4B4c5sW5O7wWHFqrMSVXf8ge2qBzQTL8DVlvLkwi803LvcmPGishLmQPaQm_IuRVFrOicq25O_s_F
Jee0W840XFbtNHEzs4aiyEHwElBbY9SZduv-EFBTc10ErMGysWnp000000000000000000000000M
}

