sprite $325 [93x93/16z] {
xLdPUlCw21GxoBp_yvv6wMxicFozEb_cAedH20-3bdRyZ_722o-y07VyBIUoc7bymKs5yPzdGLQF8xWoFirCwjyIHO1tSP1Or3ucU8gV5xC9mP5S9FSGQcVj
4Q4FXm7RZRwNlKQ4mBLwhzY6Fpn2uNguHHWqk7iwSeJ3LMxlUXYhCNtkur5s8SoEkCdcbhdDsXiOeLVamv9wPkRsXimiAqAF2mK7jhBCUMz6r9cffNrzd4Fg
YCXDlj5aLb7-mEvGlvld_A4LRMcLedNgvyybDnZZ5piNEPohxb6CWIrfFz-iDBLpLGeRQgLmf5HsRAko9HMX6KrTjAettXGW3nruyuEusttAq_4NP-QRAgoI
PAQ97i9tNMWVUYPwsPsoMWRbvXXSv2l82hzG8VfvGNIH-tQhzRIXFZTOv58RuW1qu7Az6rB7_JachiQYIbSyxdqT1vgRMd9iRkGQstZ3p8B7Wbjc6P1lPAHA
GrILM0NUVstPnUfzV2PNOlbezQX7LFIIiruIzg1ZybXGsAUk-_KzQh_vyShY9JrbycwTn0EA4vkZHkmFH9gR_FoU_63bgti8nFVqckdu9MocNEZnkeV8TlIy
POOG8kdCd3IU8rz0_KqFjkKxDcsiJgMFG7oNlKM4dnzzYpsuDYdlw7TeaEzCYbeOiq1Byr_gA7J8EylvKaVn8lcfpqkWrVHr4tMVBF7j0Zr6D0LR02tkRHSM
hdAJgkcze2_TtDga5a0Y_3H4GXlRN6KTWT5XgEUjGSiw_NVdIh7QEivOLuswHghxbkeUwhL03UHkTXuq6gYFu2qlrkWxGYvKj7VhwLUqNRE-wEsxeeOso9eb
mmXycXiVETaQgRV7OZojEZrkGGs7PwqY5xngJthSBvL5dn8yu9fsrjR4hjQA8nnx9lJhFg3ctpYrbGrOjHEB6xXpiMk7GM-PU8FyJCTcu9ooFwewZnvMGk62
S1n2uYjcz07iSOCf4-nuMT-VydWIo1OVSBSxtEC3nl3F_xOmZzzmKyRnHm0a8hw1YBxLuOKNNlWF
}

