sprite $325 [96x96/16z] {
xLdPWgCm3CDdJF3_V-zksiojPZ3TVQlc1YBRid9qklrFlF322o-ymABcxp0L_cVCwcs7QAvFHY7rTxPexdQ3UultowvqbLtRdTXD62bcVW_Jv19xtBY5JXGO
vGWys9rFFJf2j5edRB23p1SHj43l8w5gkLwWBpnS7-CVnTOazQVfMLJuSG0xGIyF7zCuSk08UPJOYQOzAbFxeEwzZo0THcXxd50dyFNCmtdQySX4IT3l2j43
yUChOsG6Ri6rz3qF_SgKYLBzjG2SlcP-lsoPWWfOTq1nWHt87TcXlBoMnv6iY6exKf25V2sFmFGDzYIg0l6-4xYSIHjvE6qMGLj4Z6v87f1X9J-CBaCU3kiX
tNlVCbpl0X5IWAlowrq8wkDcT4gJAHji0D1oVTCoxbE0HorAlMVS-HMcM6tlp7_hVPF3RYG7o1z83DsBzLVJtkNePZ9-k-lFXGOlxcMEvRC7M_yB6R-Df_F0
ET9YwUUjvl-IWGoSILRp5w-qkpwsvu0Je3AGVbzx4FCFE5W_1L-g67I4rXW1VgGGUSXt-WSqzfW_XltPKOJ-TJ_nkNz1_hQUNZX2PFPvXQoZxF44mzQoc16-
dHzwHB_zrCNvPiq_8Ur711lC2Tdh_4Ecdog9ciglvxDp_5CcQEUdy_-GgHf1zrZv4xzuS2hm0t-kbmwBGeJf_zhI8O5Mlkhwu0kbkSq8PNvy2qTe808GeIxT
R3LuCGsQMB0MY11WF3Ovtd_N81iJWbPd1AhTmtRbHOxbsj2i3kE5niNUu5dDUFigUnU3jJA7i47hY5thQpT6lOLqii6NCup2MbzLkDw0kWFvt0oxFZuA3hrY
S7cg05xwu_a2sjvEf21NwVMClVsoGdpk91Dxq4NwTkwvIm5uvdKk05VffJ28wwTEB-L43VzFd7byGUCK5nRRmK51Cpqo-VlbgDOxJrC_jd4p4hCV6-NfqoaO
kI_UP67p_IEBEiXYlo7SJ9Y9QDk8Y5dCVTvhHjjra4uUY72bxMaGpsm_4E6c3BYVZSHyclM55rxu0m
}

