sprite $334 [594x595/16z] {
xC610000082W_QaNgG800000000000000000000000000000000000000000000000000000000000000000000000000000083PEyFjo4qb2AiRQ5hl_yBt
ZhC-SQ9noiA06gdgvDSgkpk2ZwwYORmtaOYevfpB_rLhTNVVVJ_8Nwgrblyhvwmg8jkdA5AaBuHU_Eo_qOkn5s3wJBge3uvgzNs4lDOFjhQdY2JvFaT-Nx8e
4K3IIBrgrctSa195BCshMCiNBC84MBg6gnMneYINkiTLBVcHM14cOiNCLFUrL2DdAuQcVKr5Z5QaoVUrvJUaYZIHAah6vIPthrx_oDszVighku_BLKj1nUA4
ZtfLHKGsB7b9DUVovwIPfOh5wVDCLwJdFGP_NAaYJY-GL6Je7PbIgzyTAkBaWAGnP7bWg2Yj2nx_YsWpLrMtOQAa9OfxcAwqQ6xXoejiCSJozE5n4IzgNL-e
ACb-frFOqrZvTQz3ktC0KoIi_1hp8qy1pbmZd6zFOeeyOPhYKnMCAVBacARuL0LWYZmrvAROkMeeKrH-NbVvHwMgxPsfx05mYddCv7axAqhGiDxwoeSYkw-o
DOW1wibDPArzunGDZ_rZoJx1-cXuHRVdI4i_w-CE3vSd5ghVbIaMgFh80HJr8MMA1QegB_AqbYaMACmJcS9bYb9lu8bCkMvlHPL6diXKsO3eU609iay7dOyI
_qNovCx54L8SANpMmFCflF8OeV3AexIYC4L9FRFig8p252DK-m1n2UAIJg1mWQBojqXHsh50iKmfHoQpG77aUYhtBDwC2qGgz-n1iJT5f8QC25SaWUhYU7G-
8bLwxl6uvoDIUTXGS65c0ZLW83YI70RT6iKcCP7ImJVhU9rQ2PHihQBawKY9XmMA8yhNfpYcTKeRYesfkZr4PH9GHAfiZr2cvOsH-3Dx23eHA2AbJtZhda1H
7DowrZkBQ4hs8NUt3wMa8giWLP-NoYKiJ9hC_3kP9PKjdEHfwLmNCNfHCySoIy8HZbMKSqJia_dFPHPholAZebIDNvBbY1EMQUHWKH_KYQgBu8GLoVxgOxfI
4hmUY_blP1esMyXJF4-sG5B0qq9C2V22stgU1kLfVQRq4RudWLEvcFUIQSXqBW_mlBecJrWc0UyXr0TudeJPttblcSHpX7pxtcPUA42PMVgKcTaArfVltkSi
GQkmeJQJYhmzFZOBNgRglS_tDEQA4ODDIsaz-zDehg3tYkKXFIy1ch0aMTWobIVR0bzE3E7qIwXCk8md5M2Nm42Pzaltoc4VennmiIYeAtrQ48dZFa8IqFCI
uAaNKnRAzsIxXqgyzx81kKTIk30bape8V2qRC_K2_bmkvZuguVAX3GlHQh6G4hzXaP9eyL16phgaM4XbMAJMBr4HAvGEE2WCWjJzYfH4EmiOFk4I2Ya5HMhv
4bNZ0PKcj2RihaMA9IfDwMkhnK5ARzOupx5Ab4xo8x4utVDwhyQvXofH0e0QYPH6ALBRqj9G9KeC03KKAGbIfFgXpPS1G0t_sxYiU-ToZvNAJIO372Hwo7rQ
1negH9dCheaQeqWLbgWXmSPalirAZDCzkKlh88VoFBc2Oav4rrmkaJnFBYcC6i8iwarChqJQv-cTGCOglTSsNoC1-vdt5tDnjyj_Lcf5L4RJ9jVDgqqeKdWa
wntwvehYuDTlkrcI9QSLIsm0p60aOJRNsvfUcXDjvCfJMvcIuFJmVlUpFGVl09Rlk19bbsOuc_660jQtty3qz2S7jtEgX5pRMzKP1pvmEfOtFPzr-msFTxhu
LfRD-89qGfPnHzEJMTyQaSltxuEBbFXHSZlR4rXbpOzA0USpFjFf9oEfgpSvCrmIvaVPaYKAA_M3kdaaVV6plOfDxvs6pwPiKAjHBUxdRQ_Up_GKZ4CtDKnc
VAmnKRguxO6Flrr7b4ulKNZMqnL4RIls3t29dK-KmH8rlqZP9KILzVe7E0REpr4o81F7-XmuH-7DKdm9zkpDtyZ2r8RmjHBlzV2ahDyxm5sKiHEPmdoTUNW_
oXgC8vomPS_lcGjmWecogROdU5OMZb7wqwML0fbUw8-2p_Nm1jpNZr7uxa6emZ2qNDhukmVB1Ycy6Eg5rnj1UBdEzcJq_IXyaA5BnoZyKoij3Oh3c5ZHb99P
IadHyswsbmPwQWBpiaeqnsjX_ZtpX4rFalaNcQBd45-RPNju9B5th1-Zy3SunXiD_Zci-FbH0c6niHQFHr9MYEQnznIevsV-JWa-VoV3H5tUoV15etcEqlSG
m87vUobyVfJYygENRppBej6ynWY0U0h5lv7Wvz__KTO6-Ffh_VwrLHACKVvU2J__ljpPTaMGmeeVpUFdFpo3d_iZtJRvai8DFJzkAiyIvG7sJ6l6g1gQA77t
94TRGi_R6WE9qHmeJ1-jFRTeadTJ3f_Zgoh8P2Not316OQBqL9J7pu-rnm1Hu0CnceVrQbmISDiRFp-2ad3cldop9-6ZETvFt9MeOxnNJ9J58ihPt_p5gTwf
tw7m-V4NvIHHjaOaOJ37MteSl0m_FthUjWHHk6lEODvl_f9zEYHyVlIyBHvHs44oW_a8elH3oSp_IF3pe-S1ea3LZ9To6SpRYJhULi7FZvutW2X6SnpCunDb
2Jz_utbVSR5EUmL6SnpzuXEbWf-_yxm6eYp2nH1XC1_kUfRavy_rq_F6rIYUmu1W7fweO-yHtl6qRI6YT40g2T3cZqsKcw3d1y-BwNfuWXZCH_MZ_j4US4FF
3vwtA57EZdaNel11eABd1yyRG1GtU-2hUd68maWPVlw9XwK_Cl_o2zhmYRZP2xe2S4N04Dg6d_j_AM6Yw2BBk3JUMU7VWfuF82fiqkLM3z-FmaGfUew8mZVk
E4NBB01C58vUWfwt42NnY7AUmNJvvW8c2Zx_DL4Q8-fk9yID19hYzAsf6NeEYS95SxKv8lyu2BidUH_b4tn-4Ev7IJfD5AznHl9e_1rUTtUpfFAQRatsPRhn
SqmK9donQvpSHw2QuD_9uFCcei0V4Vwic1zMGHB-5XX1po5HUAUmuB9dzqn0KV1l9F1v4r7f03YZ2L89Xh-r46K2dmEYklsCEsxsQZ2B1dDeVfGb_1mGrIz6
aIWFHbH2oKMJ-HUPANxUIfIS9uhjW_swZMdx9AgclwI2dxSBnoYs3_2_9HlCza9_5hOFC54IZAWKlLx6Rn_m458FqqYu6ze7_AW1_tqzGQR7smVOzIfj3rHB
jWymKT6OKl-gnT1c-q3tWuf4iZsb_HxR1nhxM2ySKmRSvkuV0w_y7FjO3p3rr28b3aoF3Ib0563gSTN1caoF3QcwVoVF4k9ippL0YJ9sULhw74Uc8dn_mOqb
wjyJvR4Rd06PIfTd66s3cWqfsO5ShxSSbwjBb0OAlF692icKNLmYKkFVpnQdxZzGrQkBb0Rwwtb32dzEh2eN5mc9KYBPuiIrD01Jk4hOXJYxnCid9JvHM4Mk
d5LTWsQsEEk-HsNABlCz0oNg6Yr2bEzxLARqgafXtjuDOulJzvCgbvKAkyPkBQQThDConyeNnHbFiqfZk-UnQIvxWpnVutkk4J5cqnmJ5QUDRjFhXG2hPTFy
t3qk3yQK0AGk_WjvBnYtzhLUoHJsFPEPG67FOzCSLr8fFsTAfc-yt6KcKBQHg1vfBtiWfcmUKcAW8l8Ofdb7gZNCSP-OJzhnINTuITIN1rAYC2NkKyADEa2N
np2_xEnBzXXCYVk4U9C60aMYWFdDPagFICbmn_EqncIjXhsK24mbFqX70sKH8qfyeZ8Wwepv5PcAbCdOFpvyw5tvvmHhlO0fFESwha2vyP-46aaKDh_nJ2KV
LAOaUJ-WU5HSGHlslFaL6OZKWFIirXCe4kM0A61-KvbIz-xMfzQNKnuL-xdFAELAfiGnK-qyZUz3aQXsy_CnJ8czPof9HvvSjdRngDWRd5dh9AOmKkqPNPA1
Fwb996g7HBMRNvQH-HmNAenJW4nEee3vZMTApG5KhJZX2CNB1-r4OOdMQvWIy-zbbkI_QJ8_Q9ZZaQZjdBHCoLEuJ1snKf7jgqJq05E0fW69QZA_8YFA59Rz
BGUQLg1855QkLp2bvfs4krgy83MUA6n-uvbANPbAiaqJYSAIulFpb2Jl9PDj3VaTYMetlsXCOPvuYNCWKLXw2LCMpEz8LC-FACKNo-XsAKya2alo1Kn9kid-
3glUcQXsyvlJyyGuoGR46XLaEoh5vpErwOb8PG0drgXe3Gx9Lp2rYPfXcXgo4xyC4w1bflMYUvwQpEmRbYo5hKqa2alAGAOmM9fIih-KKbALXLaYKTZyC5CK
YSBc5vyf4XN_e4WAcOgqrrk_mO7DhzwLAH9Ljr7IseCfobcZWFcHARhUCFEhkb4dfulGQoLJVKCAowYKlaoHA3Ou97ihKzHEee3vTM2AHF5dN27pSp9ruljw
90gO7vaYKKE-FkDveqZKQMdfonI9ui_Xa-naglNdHv4eO7vaYaGDD3_C58dYPspx-aoMZGBhdqITCZzlOef4SVSWzSmFTY5HGg9-Otv5DggGgFFAVPWYKJnx
nEV8PAgIg3P98LETRuhmdcbsNaZlErdya5hxCaMYM4Yby58UZ2WCU-tdo6HA857SaBO7AbTUPY5HVGELPnBLA1uLaIbm21j9UObFAOM7o62koFrPaIdW9_Jc
Xf3-y4Pw8L5awjfT57iSM0gOua4n-x2zcWbLU53CiwBEJ2cFzGW-cPff9pHdDZrnvEK6OdpJauSmR9knaTxGZ6PhVoPJHNW8G_AR9A3foKCOkZEP6fnukOF0
0ZSzsJ9db-Eqz0bC-VvLxCJofcUmYM8nRMTAs39duElRI2_2bZdlSVNzYb-HcpKu2njdbpEbR9dpa_9hew31oHRdnKnvvYrp9husPRzkuySz-Gxw7FTg9kn5
sE3aHoLJQE6pdCR_UK4C9snnOgPmeE86YWqflF6xHISzawZuJEr5s8vYGwflIA_ATXGRKdsPyYniHx4XrJUa5s4xYWsfDgOSc1-NFHjIlKAwPs4quGsfll-E
Nn7UZcBxe6j8twjoZkBp7p-aO_EZZx1zq1wezgBCkcmVz3K_pyBzEDi7_RuxWnCL5ptR1pXGuRudWmdR1-s12hiVDqzi7-10TPGNvGprMm4qlvUy5XMwI3-N
flczb9bqsJuuAoq0AUx6Uou15YgXYVInQQRqfY95ej3WiL0LRlMwRlQOg39NF3TxxPAZ-obpRZjHlcsKv1fdbVbQHE6FJAYgiBlJgQoIgb9hpGmbKDpiyHlg
yJTx5Dk5tEmnauJEVXHFzRZPUrnlXrPDwLgHX9izNh7bPezRlUTvDSMCktVOJr2S6fx3i5V8QCup67xkiE9QPstb6SnJyn_5YV6GNGzAk_PrQDTKMJRWvf11
YghBhdJPsP5QVbeOf2XHLUaJesZOb2Jpbop97MSbJruDLFA_bO1pm1X5nwRClyha3fFIlXn4xQMaMnSHA7Uxdt6KO_y0rslx5LEqF61yTUbmgp-ji69WRK5H
uaS9CZrT-mGfGw3QaQAI7vMmwTtJzWoD11Pb_aR0zEgITxkmxILKhh4eyNUInKqFkNO6Oz7RzqYKeYKUNKr5Lj7YQXU9GlDnIzipD1Jj8b78CrQtlGA86flD
cQFAOgQ7RSy1KUr1YZB7e-Z0z1PiSkfKejYFGfEnlktLKQv7YK7JgukQ7h3kGScSKh0iGQXTrVRAPTq3tZqemFHMaSDiRcDY5Ez7WPbOLHdsGBHJYQAI7ImF
JCIAaXqNgGafYlVC_JPNQYkqRx5k6prANiA1jcwBgErLn5YXBblOyTLKRjKEWP8Q7JwMpkQuteeciwHJU6A9ojlAafzbGhB44lLJbM2Xa2Mgt6k1xB9Hd04M
APQem4j4jvcYz7ucKQuCXfIZ4hL-aShRF54PbwZrYvHir5NTctAhpSRyjw8ABb5yBOgBMVPhEWXKlUjQBfU4SohVTjp5wNi1lE5EUw9yWUzHzSxMu9U_73tF
jpj9vnTWUjwzpx_AnRv7poktNJ7pVO-UXtT3V4EAAxWoIbtOhwbtNZNZNvAgZt24tBSGKnpgEcS_I-bJx41sfdEEyu1YF3QTK-8FYXUrQpccECZYH6ewK2xF
ilYozHHLdXPMyzxLv2cERoLIGu5wOApmcKWHA7dGvdPyfvD0xVAaZkxuAaMWz25ltXSfYiDQYDGKeChs6DK1Ryy-r9Exnz8NAKe0K0_RyE6DBeLNwDDFuSN7
Zm47awEWstbHIg2EIBLl-QYy4wW3Kktvd2e4we1KUpwdf0AWYDIPamDATmmKaMftFdQXk6MMsdbCk1whC0Uqx_cunoDGHnKEJEDI18c1QsrOcUAWSNHmccA2
QjWcSu2AR4THKXgN84F1xiSgJcNVsw8dy_bBLRUlehJkUsCcPvZ2Iu_574SeXYaSfnYWsfSTdGypHPwmu_7gs55PdivJtezglwZ8cB3xr3ebgkdrNr9D8l_u
vSy74gC-OSVZrZY0zwb_bUds8Kd-LIO1U6feiB1CpUybgFzBihraxbSWfNNlLQ2OfewguvVa4Hst3zRztqepYlQB9oQeVaN-A1yUqiKFUlroyYDeWoM74C0j
S7kX1-PtUwBmABJnn8G-V-Sdxz7HgKH90IFGq_vfVI_LSUwNtWScEmRsGP93UXfeUDprZOTAx03Kkr_MaJYDD3p6gVbGgNsHRdyaoVvMah4uZO-HP0f35LyO
f_4yiJk5LSj2muoZ-FWE5EiKbfSi2nSdWDEO-aIcC5Kgwz6aWAQfF94fJ5LycWBmnFxK-WueqEdOVvfzo8NJkiGjJQ3cpZpAfFcTmoghX68f0vW2s1qB5P83
hkQn13xxDUM9qkyJ5QvNCX-bRrd2AYnF0NhBGEw0hCua_QzTkyYI68O1A3XWFodtl_38mqoDwbULTNO_O5i_fjJ_B41KfMJ4hBOghlrcL1tDYCUGkkKaglt8
LLVbLNrLOENN_PIwPrH4gwBS7ib9LEzbYOmdMU9PHfRj1qrpOcqxNufiy2lkLTM0brE3RUW6EcpmgohLj6-g6j4dgupHeIQkHuDFOFGQ4UHwPNN6CQd9Hz1d
ZdVd_dkqd_c7_dHLOHq_fSjkYSUXWCW3X_Guuj00-nyKoFrKz7gS0NcjliQO9PPSjdMzaUigKMOPSwo6Veu80000000000000000000000000000080x
}

