sprite $334 [124x124/16z] {
xC610000082W_QaNgG80WDirhyLaSXWAetvu_nVUXT6IDdF68B9NqL-JsFwmgjlxHMxolmBL8mkuVWXG6MxwcrZrh2iJfEklSBzXWMe1lluWxAtWm6Fa2ZUL
dvQmI3puzIwyuqEZmfkA1HeVCYVRDbZvwbXYYRVGjJRmiztoJlS9EkvaVIKKjwwlJ_qsQRpgDdAVkxxO6JUZJLt5NqLZbYgaA9oZnt4IBy4Vw3dyMO-fSxIe
kRlfEVovEVXP3_54IoMTM5wlzGnQpZJbrTp-XpN6Sz5IlBdMZUSgMmel02d7hP_IkbslO9E-iVHp-m9AcSbpcGsgyTZHSL0uEh-Df-t0Jfgs_kwk-Fh4YqrR
6x87F-oqR77vRzgxUYf0Z_JXUqcWBUwhiHqtSXtezcYK1EH0IpsT9PNhDXHYPzf5hE4xd-V-JImglJzZT3So_WzG7R1NbQxjbBAdysYzYbpwdw_sq9zPA1-3
Sldg5pjQseQI0k0VAKKtuyYUKdgGDOCNCqsFxgg5YxZQdLhj68KWwMN5tAILuB5yozg-uPTBP4LRDqarqvNehbEsPDsAXzsXMjBiG970zPM46kVpzgYyRmxX
bx9B9MClEriy4YhNkMy-NMMe0g9rlgHERXZkQsgY1J4LGugP8VN4rovOS7IQWNfcMlSo6eyrGnt460cVvuF1Lt8BroSFCRB-MSYfp8-u2Dc-BjGI6Z--n3w8
Crv32oMqJCHv9MavGEIHKGDmFgayJotLyFsXv7ZDnCS-3t2_kOI3q0qeFLX1SZRMKelcCTtnGxlIQ-GPkpPs7rhidplOzxs15varIHma_JYQlhyd2XEvY5gY
ynkNMcStv43pNlWGfc-UL7aBYGEwvGCSX3nWj-htlKxD-dppDzWjLardCcVdVWk92Ptx6cUtwZbzpWvIPgqcTAomZPsIiXetpMlEs0_LXmpOan9lX3wgOxQY
KYkoibgetvCrV2VRr1KeMxVmDJodbws1YJ6fI_33UN0wTs8UXbmaIC2JnC7JxZgTEJqVTtt_m0C-TQvFRXUUQsNgHpp0-NrOEO-VGGxWujMPVZ8bhXn-bI3C
b3wkTLou2yzRpQltG3kZwhrUJUOYP53o4St6P2tamG4wtP85K1CkFyFcjni0OEzXQsUMvHFL0g13TjyRvBB_TakjcZkyQ1_Yh2zlS7cdn1CrejuRuaAkg0Ot
c8FRrSczyUnsTN1lFBlFvcBTOIw2ftDql0jUBmHDSlZyjGY7poDDEPh3KoPelnBqkSq7rKHgyfhA5fvnyIEA7BXA7hy0jAgyH5KSTuIzuTaUGlVOjSyMhu-x
Xodz0CyVT8Qy9I7NTPCAL_vIiXwd_WFoZXPRK1dkfl-Ag8YgcdbaKxcAkF3dbmjIH3KZFdqLZ0oJEMJXuLf4RX8HRb-Fil_aJ_xaJ_u1
}

