sprite $334 [96x96/16z] {
xPS7qkis38JHiRZ_XJEMnlyysn0aAZtnDzM5koGQ9VgR-FBbovSlNrZD8r4_8DrCw8z0FUi8nEypONjgfxkf2c-8cdcWTbpf7hgBX-cXlMEte7K4LONpyrlS
Sl2g2g5B6AfAQG56LJ1TnjQEe5Lbj4HKnO8yc1QnggHBoF3F0RrwWa5UrCo43q_Wro99BUo9dT0Z0xaIntwrFuHDrJo1R8MoG6SS798JCAOT2S3wnNQ-_GFv
btvGm8VLgzldV9UJXDuuWEuRu8_On-TyUkkHRP6VP20gjjtQsxXe-iqGdtlWAfx3erjmyssfjJ7Zrpr0Y306IBRmy7loq8uBUtKD91FvsFksXu_brNKxUMGg
UUP3rFtvzIy8FnDuIBJLex1jkIK9AvXqLqQtrJO1StaPT3jK696u4uTl-WbkCpZfyx6-fn5xE8NOiNwKZ-aT4YaFFOOXiJa2xSKQOteR14uaRXaS5idCMtmO
EMWqzCNr559L8b7bPu4fl8_1eDztHq0kVqk3VbGLj2lGwAAMr35SCgW7-UcG6BwxNg1Ls1taSrXACr9RiknONzXR1tipu6tQjCIH_dEuMZq8UJTmfYUIX_Ba
vSVwjA7vwQ00NBRYr022wQR-1lk70pj-IAL3lEBIUB1F1uq4Cbnem2hEzx-XkJkCtDT_XYb7Xpa-vwrjNSVD-hus_ZK7XqLzeGxnTYxrnAIlmsY5qSZvV43P
TEvcUg-9n2nWbnogP4hDYA7A-KoV5rgZAoQN-H5mlDzFqHZBLQjcxtDuIhLLhiUkxsfRoM7V07EOvlAVVvovkKKl__tw9y__2mpbCzy0JEk8QpFzsnS0Gwux
0E2dmCaJRW96Yp00EUqWsQQJ0qAhIEZ-VZkIsn-4wHPSfQVv5xfDdDTVLlwUujGBH_JxlHMNHfVIBVBQ-8sR1d4rTJatoUzVbUivaAgobQD2QG6ljQ1Q--JC
8iJ2xRyN9nP7SmCQ885iRkCR2PFz9SduLoqcPduPogYwsp7YjH6kGk-mc6SzIAFRgDSFoDZ9H3r9O_fzi7fKHxe9_L6mg9dv0pCpPVeB-FBbDm
}

