sprite $335 [96x96/16z] {
xLddreCw3CEEX_p-BtnFINj7AuRfTpVwqH50iXM5SLZ-9jouSUF6ZHkYvf50FG54-D0VeHwUjGM4VIMYZYTHXjjGbGTKrSm3BurnaNtagqRPaBUf3vSBxAYg
D3tqBnuIthKzgkfaMMAeWhQCHrKqchPU2rO5RVSR3VfipvYV5XYDKYuSfZlxgPbjnjNEpG4AcwljYT0jY_ICZxG-SG1XPkO992NAmc4GgemMdqXx2Mi0TdGm
H_0I58ZVjsLSm0k7vGysdF0FGMRHKGF62mWuwKZw3O16J47McyDf_x9lZzBooQZG1h1hqA3j2MZJ3YE3kuiuw5PzE261rFLZYKnRXuEkViAmtvrXfHEF-P7p
5278xWHm-tsrNpHqVcJuoa5j0mluVdEJNprrVfX5Rl97UJVz3fsRy_MXMFbpwKtmtCRzL_VqzKF2CrQHv3KsupE9H4tdnwAcKzQNNe2oe7GSkZ7Q2n2gAfKP
5BIhdGnIr8fGSlhS6Ei5j0f4WP-D0x5bicsVtKHZAiXxHF_ecmHIjaBYkyjB74J10VjjH9FGCtv-zZIYO01S7qDg2OISN4JyxApneI215wPPt_1FczuLB1B8
SCBUuv-md5dYwFDhuNqa6Wfz_fTDeJt-tkdVaYkqyocSVzgKskFldVh4gtASui-ouyilLu2Tu4UD_gQf0A90Y-otDc4WJwt4vCRK48NOKz2gHdG9T3-kez2x
F-5nXSaMHxPxuwiwZNiS_RdXJQ2T4P1iDL5x55dUeEfOm0FKnoZiRgq6Lxz28Uxr03wzF5rzw442HoEXb-f3Aq5zV-sh1gBoU8BYYt2MdjZ7hhfpghQudD4i
oBdT6WBzmWHNEf2i6gTzRATKKJKwjQHsYlVgcUh5BkEYkgWglUYdzFhDXy9uKmKqaMzxUbN1BhvU29FVDo2BY7oyuRXuJj6e1n0-b7XbaVL0sd8P8r1F01bF
9ERexE_xDqY1-WGoJ7_m5TWmymcpeT8lkuyRDtu1
}

