sprite $335 [124x124/16z] {
xDI54OH04011R87BFs1aozxTlpk6gQb-1G0000000000000000000000000000000000000000000000000000000000000000000000000000000DHrkug8
OJ6cicDCmo8YsbLTLriGKMG_vGxPMFnlNcH79ogwiwvig_e3rDU5T7zQFriMcL9vYvyBovOofRSRXs_lYgMbeSpiczTY9Jq8WuDXWBp_0_-zRftao6EDHzf-
bJNdGyWbPAfols4f9QGnuTMFn4em2Il9u33Dn-eHsKhM9BCIJUymYIfDklTDj7u2IlCcNNVNl-gl_ZdFgrRLKhAZaG1L_VcMmEoqKPZPdsyLgf1azx64AfaJ
xaxNiEyO-cbM9PowZhdlJWnn8tqPLCBfHbUsvbxL-q6bxDHrhDn7sQSVFlGnyRyjUUDPukUgPncLx6dMgI7_sJxUg2IlhQxBpAiN9Yh96-1Cb6x5FVp4K-Cp
q_nirGHCYQUzJfhzQ0Acn1EO9dwgy4o99tm8vu_hUAR44zwS-AqApvJazT3dHEOruIn1AeAY4hTJYH3em2kNHt-q1E99bwTsD2HEISSvUrAOFCJA6NdBdhuo
Ag1DAP6hVjx8XAxYuNbIMPIWL3ZlZwSfoVepF8cf_acuLCaGFAb0KfqebvWw6z0bwrTIWf9cVJNvr7od2YLPdR1ooL-lahhlts991HXu6dt_r4igpC3JwFip
dqkDyd3PLB-zITOwj5FTWF869WBPb3OpZgoAkb75Sto-r9x61PGAeWfYv4ZJrkGJKeuyXDBXYv1oP8HIc19IZZmqq362a79LGSL4oXgOoINlfv-U6xG2aWeg
eAv0wbcxa_b02Qbw4b3uTfAUYvHV1PIGSW65bGQVFsdPUA2aVZ6VQj6IshNk1jGO4Vcd-iy_8iRWHUffwTnlDEaj8lkxoeoX0Y-NtMMz8x9FA6Fm8sMF2b47
9KxP7r06-Kk4VbA8AbwSy52folCDkNR0wK_b84RAjvrvv7OSsIyeGuLUtJgs3qz_AabMPC-OUqxjnT4GfQdMowoug7Y2AJdcmSgvfpL6DbAX_btYmqQqlmCh
1s6Kyjrddjzeu6LcHCI8tvMPjnXzlldSE_0cZ3UeyvTt8oBPHrzj_SsGHlhW85wvinkHp3PblVFzNb7EFCiNej3FgHfKSs_-ND3QuliuOGPdg8zdgHbdNdvl
sE6E7v8iQsnhKSuBL0vemazJuQ-mADe8bGCUoiOZAgzE6ITu0lbKgFIp6wKuWSgOTBeLHE6yjxGeKg10-qSsf7OqgMOxkXqpR-8ikP0wzZCfPrlIcBpB3owa
Uh99QKNZn7uCdgPYsuxMWiOLPqO9WbOcnRyUorCJ3p_vnfuzhUNaHVDe89nG9iM_cZnh7VWmbHjsjHOJ5yuYcu6KJAgerZ8k3JUMB1i-t-UTb75PrDLfELdI
UM_pcFEOQL7y7x0boTppRLwSDvD5nVMEOO0enVf1g3LiHQePNr6iOG7CvLGpBzPi1bQj7fxDjOm0p1_4rrLpuuQU4-tpSfat3lBFGhcS_tDD4ClAvaRK5WCG
eb1VcyAaR8F3A2ABofKHBYb2xN7_eLT45hMMvs38vgsXD_aZvGTQOyzvUc8i63jy9jM_idUkox6ZC12sP8rGtl-1ztOkhfqQJzic7fhTrb_b1Ahuecu4nu2_
S8dUrGNruRqB9jcJwF6NA6pEOsxPa-WbGO78NgWbUur6z8p1n3WGNe8bOGyUqGk24aLHf5QE1k7yimSbQaYHCkw_Slw6UQFnvIHkBWXaxp6pZLfPV7coY2-1
SBIPRPInY1xDH9oWewFUGNzfo6NIcQX_yA1Hx0ILOL0N8sTT5jaeu5ucWLj6YaQm7HI6OR8NlEl2VwXN4hqVmMQaR29ZJcMZiEXvH6H6k8Fq3PCPQAHMsQXk
DuoVu4W_bQujC2mX8pLzSNLaNJphET906drflmxn7TFR4TaeaD_2GHeHDOsHcjH6DHAYylXxQ8xIc2WC-En-HDseFF4Y6aW391TY8zMrDB9HXbRGwtK4I5ya
ocJDhmNdePxlwb3-w0luzkC9qfWeN3DZlhMHZGgypbaPBpvATpHzqXEbUfpaRRJ-1VHuYI18VvGeMVD6JnJkNy4q9WeNJM9hhcDYJ5IS8IeFflDakN7TuxmG
nZFdkafK74nN3r5ERCrrJ8o9yZEgv32DYS8pukwQovZtLuHd5SDfKFy0KTmkL_tDVjVY6p4W_Uoh8l_EPOPrwh2iEJRc_4JvFn7RjHK3wOuNZvECg2PZVWDH
pqmOI8D3dEWWIjOS6_FPY4g7QK1KHGTHikRK5q_ZD57fE8rlmmHpqtnf13wNVyAOg3ogUXamZUzNTTGetJK7HNK-7rKP8Fsy_Sk_eo2-k4PfiuTl1Cz8L5KU
JuVRyYCiJjxY3DwjaunvVp_AtIEtnGPfz49ZT12bpHwegOn4uGVG7QJ1WDz7b3PxZPKeE_Kl0gG1CCdKCyTx9ndp_clci8PSIYznXYXNVuTUfFlNBzuZ4mE8
8Z0cEeE16eE9Sf26H64TTkurqbOF--3xQrHkWs6Yf2FC5HKJbP_mKGZV04HHUrtj8p1HlhlYYTB_XE-DPns8qowIyCSbeJBizS_7WVJYJp-G01P05FjcJnAD
ZV2FOxhuaV78-XqelVtwp71tt5F7MmL-Qw9jX84LhBq8d7u65bOVJ3Z_zabNJi4wrquaIhydoWwfi94eIHDHlLyamqGPIBydoWzFXz-Rw84XN1GmKGdJxuXA
krOorJxWVnGGVuSpyWKHZjFx7pJBE34R76eV59VdmrN18_yDX9z9B_QSx_YS5LFxG2z_TZaNz_Wdt54QvBidmzy-4541X8RxgI6r3wo-LQ3rBenk7xI3cmYz
NMKwsZWKHJVJ18M1frogVO1zL9Fi0RQb9LYV0LE3PS_rOFABze6H7y9WflIMUkfYv2MYA3QdJb8Rgb_qHDJ6b8fKe4sd6b9OdhUe1qiRg6mchdMVfNtjHQqa
bZWPi7OHTRpDGSXKWjKae5gDGp1FBgOCB2TlYL93wWj4hGn5YeTftP323KvAfdpqWYPe7QZ52VQaT4pbMAG23A-6L0THOzheLaDr3umkea0f9M2Ae4Y1mRaC
oeEOA5QcQjog1YvHkdE7Dn0uslB_M5Q_3hDQd0Kn6bTh4o3rgO5DToDl80emDM-fm405vrfDq-34iOwg5Jd1g6gQVrs8Ml_BI4K1pLFJ7EmVQ9Z2kbT1DQIQ
vlZ3B8sDgG3hUpjGgG-czatIs9XAWDJDGDKYehedkHOJKrO0gNk1SX7r7TAyDYAc7215C9QEOV26r8upPP-sKfM48-aO1hSu7iN2L8A5PXf7np1jlx5_NFoQ
VHefOmHAHE6Z8YDXAkjsn-nPps7ph1O_zUV5htqOgRp5Gc5eHLJ_bwTN0gRi1L9-Ax7bzAvtuky4hsq0Kn2fYfiAL3zG8WftE1urW2c4LFfTlxbyWkxXx6zU
hwEPIl1f-_u2rO-gZeeB4dLU_DedaQhevGbmIXNhV4I1i4UDP2hhcvcAnCzOwM3lHgAEYz_Z_cEI_feILVS29QAEBSpQHZ05NiVpZexc_OV38WgBtoYcB6id
uWHKzbhk-ZTv8khhwdPq7SPKLlL1vViuLIxKOLCJXSLl45DURoB3hzA45KyNfFg9wXU_zjaozVjTwnUlLINwTxQmn_n4OV4RKgSygt3a5WK252XTPxc1g1xn
Q_QXFW8E1WSbeh3u3M3AiZfYwB6BYCAnZc3ASpQU-gFc9Af3_0YOuk59HDK20eiVFrEO9xs5oFEkv3g0AOkfUH9HMFmmKoo5AeEI6X45nUz-fYpoF4wsp1UD
dwWxdDvw0rCu8kV5IKHXyHl053Yr0oT_V26YiFXXflh3F3Btp_iwHjL_XXdTWrtlP0g3vH6HaPcH4Uw-p1uY2ejVMnUY457yFLWiVd-oToUsaiGW68I548By
8zvEOA_H_-wF22ovniO5GsCga4VzDAlVc49KE7f_3bE8UfyLrYHdBo8AKK_qOIguNuXweZVB5AASeZMO2kUz_4OVfX2LZLvCPOqq1rkOGbGw-h9C8SeOlbvC
PVzJR0nVOIewzy0OlZzVVZS0Ue4e0ubwCPMSzeEeFrz-c7ffkoon3rE8oaPljdaOKPPOQQOGvV7GXwdiqznpj1TJMNr8wzTg7WuNpHIAvh9C8Kh3JL-sE8Ce
RQQrc0hlbZNEPPb2b7EqCHNEUjtClLcc4CLmr6fC2Dj35dR-m1IYL8gI2TMKifv5PfdQGfH5ffb2bAivcwHlAnHxaBuIc5f4lPzCQ6KzOl_5c9_Br27gNIj-
ryfwJjBim-zQ4KQs5sPg4EL5IgG7J0zhHde6jieouz5VN50X2bEsAdyvavuUKVa71AQ8dlodYlEH7vH-GvaJiU6_panHvixIj4mWEELxOQRw-mdEzIR5L7IZ
1b7-ufVTAEX_F5E3A8epF8TZIfUv9qJsItxR12VDaHLKsmIdbPhj4YrkE4tpJ0t1-OOnNqOV9ASFRz5HX5JsuRTD7Y0g-_2xHjHNgXTzYQ6Uez-Ea0fFjDwY
emYfS9BUT1Hza6NgcexI8PN-x4pfZYAaif-TkQQZw8EiIRyfcwIV9VmTltQH45BPXEfQikilUyc4webjya0_I_R3o3VbLqyV11Eg9xPb9lJ12r5pVu2AFA0F
afVV4zksA7cakloUkEbsZGIx3rn-JroflMOVUmwgqX-Y-o3NxFd4kaMojxGiNQ7i5xlcjlGs30BX8OGVUFy7xhbLnjD3ac8iMzzt5rzPyiAkK6fF4YGguGEL
JZj8L8A9L8uFSB_WLgFqrWZtKmxZ__t68Efl9W4gtl_Wqw3gxYQaaWFF4i3duR37lB2_hG97lVxe1noSkDbRlTuvx17CdTC4r7wSPSe0C12YES6SjoQOC_A0
YOU5Z6K9vhRcQmF5BhEQDKH3826Q4ynN6te0eq8h3LB0Xz4vcol4MSr3SluWHOnAQc5Yy0xyccjYMxWO0Ej8hlQk7c_fhs1d_kEQpMTx46SkSy7s-2Q4G6O7
LxSzmFG6YkrDXkJ9RQFs_O4PeS-r08Y6sG6sX-aj40I1enAsX-cre6JpcRy6LG4uXisQpSdbnYfcX-gcqvBBIOF0buZI9WLy29-YD40lasWbPx1lyCfSJfC2
_LDXinQWhcEsnT2YWeOBj2YQ52rgD-pW9WNUC3gWIT6YJemTkYA8XXOrGvC2MXHDYXR5ei0lMSwM1_aUQ5wpcgEqK82TLveK6rzUAlr_fm39ovg3vW6JS_0d
MnHh0-fOijJtW3stRak7U65omFg06jOiZLB0VdjdpK2y6CjP8r2_cbrH2coDZE5DomJDHVmWMYOa8BbAPjMMbKAiOmRM82c8bG9hx6xmu4kLhVHB2a79EgUG
-fOCbgkTgArMKi3s-dv519ehfefea1I2MkamBMsIml92bgcaUhC7ou9IHLA0eCRY2nCa-DfbwhMI0dRKi_9O0a69UfOTJ40Gr1SyYv8aA8BwHjHAYaCUgJJs
sWcQVR0N5M6A24LTUk9yfSDY6hqtR0ZxnvR4sssACnu5QJcekJzWwqW25G6TI3vIA9AggJKQr10KSQ0WJR5bexD3PBwNCJdF_7wk2PvFDt7GjmgGCFLxwmED
TwgFeyl07x81Y6S-6Q70yrbDeQVt7G_d6vC4iCmQnyFvCj6KM6QXur65QQtR9hV1m-FR0zrwggisJZBzUUeZ7hd_U2gRnxtvgRv1qQRIjLDGWuyVWzX1fwJK
ix91aQRwvrFts293PuyqTMqQrBwRQDBLeWRttp--xH-VzYilvYu3rmKKDUnkpnaKRMeqgbRNk_MxddXazZKeD9MX-uagVflCRxzvl1EYaGrwujJNvNwtZNBa
jxthey7jQazuu7cKgEuVW_jGskFZMuES-W8K4NtWAfTPxf3JaODUD9LXUe7WQ97Jw0bDPRZA1PfJcvxGr7LL9UgHpNe2iSW6LKsifepMyntpgQsgz0GBsgYf
VVu4wla2OVCsAtaYXNTUEs5-VTsglpFrNutJg5ubt5Hdq98DCPssFT6e1k47-Q1if3HVUuADSxpUiLGwXFH4Lphls1RtsnBkGrlLElA8t71XjwDJRObmTpFz
WeYyg20H_OAPkqVL-o2d2Ux2Yeal-0E_-vq5O7QpNudL4zkVUpBZm1__w-UANWToQbK5pGbLONMeYju43PTd3JHSEJO0Cg-imXk6zj1tfzPF_zqYz5_xzslf
WYw73vfxT2l9xVeUXxBKFI9t9C9TbrGIsggxuet7lpC0YEXNx0l-bVZ1HZO_yA_O5_GhWeW-jmS70W000022_ArN6A0Q0000000000000000000000000000
0002
}

