sprite $335 [594x595/16z] {
xDgn4S9030NHMEw_O29oWFMCnlTU1TRU9-Dw2000000000000000000000000000000000000000000000000000000000000000000000000000000009YV
QVV61AoBITWM4x4i9c9Np2eNjhHoLnYJMHcJMJ6xMPKrcPKnMHNcP5JMP5Ncr3-gKLdJlIzu_AhCwSmlf7yi7qlqH4_wQlnhTzceA1_36PIlu1h2_8wYxEuu
ok1E94tjKCh8hkN0lZTkYZAjmqchkfuog0AKCMKWxQW5QnlA8Q0afEraOMquPLHJXxIOG9oHIoE_Fvdy-9JYZ4fYQIING98XZchIwBQNBjAf8fucyXr240Nb
q50C5QL0n-_f8AKAOceWfm88wdv9Dvvl59ewNbMdw-fmb7MsjevMzyNUlQtdgeDG63vbvFulU1sjlHQf6WV9nzbyQDN8MyZyjssZsv8LXo5kBok-XUcUAsum
wutB8Mvn4gnMKGnnatqMsvXJZegxp5BZHd2VQST9Uog7kD7ywHGy5Knnfrccug4Gzvf59fxSJ47AVutnS6ZhkyqIuuNOztwpG4KIdcqAKgxBA-0eCjpnblC7
erkTviCsHPDg24htUzncDvsrFTHV8CNI4WcQVoX4zL-Pdkqha9eQZK0P7B4ZAPOLn-5qK4Jr1sLwN4ZvB-h57KzA2b6xW7fikTkHOabl_vVCdDIO481gT0QQ
L0DGUdpDlgGGDQ7OckDsbme0QbOhr8erO3K9A5TIY0BK6FAUUuZo1vMJSge2eFnB32bQr7J26XC3KVr1vQIywm0e_-h6FgHeKT-SLLG2KFTYYIQ5g7pcgUMm
HHGjQWnPDYbQLEFPiq6JGjId9nUYVXc-eFJj7ewnHukYII4g0TNu0X15Ynf35viKOuyMHPEYHSdW6bgN154wh2PDYg7dtABoy1CbH1cqA0FNYA95sJGfHBbN
4b4CFMlQZ3rQ54qAKH-647KZ67gluaOKBGfHQJ3q67k8kb3g9FtWnGXH_RTHrJUhv6d5KMmyzjX6nK7eSdf4IPJM4iNGK-MRD_9qNTHOVIF5DYhE8a_V5oL4
hRUDKfo4qdGkQlsD5A8URb9rKLfU58z6_PNyJxdJDA8GTLvZ_R_Yrz8ZsHFjjpL7r3XvDE1Y-gz_8mfHXv7nCn25g84e7ZvOvPfbAugjUHw8ukK7F7XmNl2h
wRADTKGXIeMVryLq_2-qd2X0rKMTiSZJSHIRY49K_JF7ytJaf125g48wZiDQr43KN56gfECadXH5asBgHGIY39ggZwY8osb4RNMz-hMeqDMq8dHmEYqa2b7r
yjMtvodXzKKXIhLVoDA7OI3APr-2g9n4BgQXA27gkOrKdSHTKKAKGKkr4OKehlQ6g2Ya2-As5OKeLTDrKTgfHeZwLLebKUljJ10LFqorF3qKIGkhYsfK94Jf
CA-Jdq_IV_rRCn_WHDHm4XNdUHryOcUU7b5zfbZDHN6joaITHfR-EM_mLXX4UNtQZxBqZtdLfZ2YLXULYp5uBOl1tWHHkYfArz8ZIQyk2b5nKTJLz50LbASe
8UhLZoIhf8SIJwr58IeVUzdFg90-oDSkngfCV0aQtxc0A4G5edfUQZvfk9IkeiQzu1iR4QMEOmzHyXPb_THUTFlkI4IzRehlKaUKP2HAA_HAH4aqgMTX8qfo
4QL5MXIYjFUy2IzHOmbHycXIiOngHCbhulYZPkmf3wycrTyqegJlHMafqeYIFYS5gCL4IHzFdLZjx8YITffxCq0XIjgcJGIYveYI3ChgVMOUa99iJUchmchc
m4MKz5chKAyMXIX_KlvdPIEbtuNNtElV6H4bVTCkekqf4PM70Idx4o9gk9dIv0h7ipCFKTMkjHgfUFviY2gYcZ_tejMv45KtPK3AzKo8-kMMVJef6Pw7XpZp
QtGnfQJKpcT1bAKfnVlpA2Q0GfIDARrUxtW6BQAke70mfJY83eT7bAifnOjjAewYHxdyBz7MbE8el8-CA3c_nK7nIfjIJ025A1zJUUrbSCma4ELgAXwkls82
A4Gvcued2IWCG26gW6ecgOXFZfG7ejnDAPwWe300XIYJZqk8dq8J3b0BHFcRYYIKzQPf3GfHJJxMHN4XTEDt9WIYl4p5Ap4c1ABI-CQKeXHs3GfHwviQBQAp
A7zJZJqXAWyxK_wU4ELlojyJelnDgR4dHENHp9I6GI3ApzIGAoT4jJKrPCW9KTs_6iIF4wBSJUKXEqo8yZULXsHY2L6JKOq_sBjl6mO260Q0jNx_WLqxPuaG
ZXCGu3b-4gAcJ0bHJ17rdp15LA0f8Oefeh8ViIr4CKLKbYaX2YgY-YioHHHJ-NEfo1HHqwQ4AAQ8QWzJH8sP4gAO8cegJ17LRqg8OegeuJ1555D4THvwPCep
G5UQ8af7feXYwkyX2YgYwc0g6XHHJ16rtnHHIZ95LBGfeeXYYgX0KqGfoHHHJ1bhe2HJyriHvGygefWYAdiHfege8LH4gSaKKGrXYgXmKqIfoHHHVlYPwh8c
KvOYAjSKKNKmPIYYiaqHjH8LKOfweoAAgVIX56MAAAOCTLcKAJiH5NPZCwBogtgZAgAO8YgmAbD4-K95L79LfeXYoapvLNsXkgnFlpSgefWo4b4hdxb655D4
9PVruKUKDoeZNPPboaRn_g4YYgao4L7lftfH4SLKcOYehr5bgIAAAHCHzHoLXRn9_TPKKZEY79uX2YgYYFfLEaGH1PM1_DWxiNVVI0x4C100Kyxz_xzdvRqe
Nf4eTOUCWC74knlk0qO6e000g0wWFW1yGusg08mD00O703-pOHrWz3DCGNq0-1KkRmF0IHZBINWR00x2oi0z6CerM1Wu1cy3m2K00Bgu0m103pS009WFn0y0
q4Fq000TX0u0C1r86m2WXw0103g8602WWsm102xY9k-028270G0000000000WCpOg2bjB_ldTlbvNMI9wDAENNcka0fP8RrsQbEeKoKY8TCJR6To-Rb46inF
iPsxybma2N9NWKQLIq6dvZSgXH8Wyo9DEtMbQAMM9vcMQpkHAy_55YVJiitbvhGZ1NScWmEsBdcKHHaTTUp8mBmtRCV0r3ViTHzvbeNk8S-po4saYmtkqAcI
LrbsSF8Iyrv0NcV8OsISacEDH_vFZH768-jJ9wtI9jHfFBHfFBHfFBIf1AtI9egK2RLI9kfq2SLI9UfL2Ttw02LwrLTxS20000008CZVUeG5gWK000000000
000000000000000000004
}

