sprite $68 [434x434/16z] {
xC6n00000C2WV_x04wa20000000000000000000000000000000000000000WDaxrsrLUIo8_cCErlk_Rz_SFRuSDf4YXT4ZLNst4LoPp6KCRFtyhF-4-hk2
yDA_brSR_igNNJS8wq7uIRq_FB8-2xVXfOSFVv41zhQnMGSJO480iti2HqqloDRNXmjFc21Z_Tv4iRyj15YGfIU-E54iadsQObKO9Dzj4t0pOjlwgB-cyL6F
m7UtHQaw03wnuQ7Kz6KvKHnDtjGtgnx7XYhKehuhN57Svyttxk8OvQu5NWgF4bOexoVPnQNz373pxu-WA0JyWTz8YDdv0S3ElyuanFY2qk9OoefZ8JPpgXXY
gInrfR8Go_jpYAMm59R2KbWAIs4fB8Kn_mDqYAMk44jbgGjOVWNun0NJ45iEmYSH2x55ooSGo-eRowd0Mud5iMKWl8rO75j6ymPY8SPYXLSGMqFCu3L9D4BC
QuVpFGinLp0sz_hwp4BiHNvLKPq0lAmrXjY8NnYiSwF7GEimWPbFnwyjn7HBAEXkXhPMFD6n43iakWCE4raSqqEV12Ucyd26M1oxQfv8qL5BeHR7ffo7x8xo
u3h7LCVY63iGpugc4ejZFZ9pjMhxTbPMujWvVZup9XMNosDSimfCXPXLbCzBzR3in34VcBkndZZMEi4GB_eDZevguha18TODqb2AjDe0DOBiOBiGauOIOTmr
rEeJ-5vYlcB26CaBXjijVdicTTyGas2WEQREzZl0XHSJOYgoSnkT-GIcaM0Hjmknus7QRC4YXkr1r5SYLyTN4jEPFT-efvVEJ3JCAEy6n5HanG2lTfTMImmn
lH_vYuiCN8WBCHsPpakFSSg4c8Vi2H5uXdG8M8YfBCuOXYZYs5jOY8dZ9b0zRQDuu9iIerEIYQnZbyPCQiZt8QO3CxeJ7LvQ4pKC-rfYVaK7H9gnvVGE3M0X
PYCRsU40qH0JWe2CeHqEd20X9eJ3DWKZUyGqh5yVzo6cJmNq28mzO25sNQ-QS6Q4s3kHjRnmYULkHTp6w9yKSSnlMVE1nJ4zl1QPiFCuDcrKVO7Zc3-kV1Om
GimRsVaJqH0phd9EDZUEwSYc0OjZHYW1sVn62o5cZB4v__Gb2p6ZZysYJuWvapjVi3Ys6WKPoEQrLq9C7kq9sEEO7xYIM0c9OtQk8rPAufYVYuXHMkAO7zSG
yN9p7ACkYzdHa0GBiNf_Kc684MAfC6TWAenZSUoxYAMUb1Z7GYoEXHZ6mfyJVVahnFp5NZ-eXmqn_OAA7_su8QQ6vKt8XeuROiNoTcAKb13p_oZP6xxEWKDC
LWnzsiYw6yG32b_d76A2OlByRNqIyNY_-d68SPgOF7zRdmP9wUtP4c83JL6Rlh4UHvqVOXAxULFK9lgh5F5ux20BCHMOD7jZ5ODxm13JU-8Z5h3-yLbwHoJ4
hbVi2PWBa8MOabEAyOG9LIAoQuY565N5EM15PmiNMOZfYkd0aER-PrfnY3cAAIXKP3enIigTYN52iOrW8Z9ijTk4c3fHtEuPyrMmSNkO67ScrWwZUsAZzqNp
ZUncnEWG4u2v6kmJ8yHEp1GHfnqb1LKoEfA5c3Timbwxpq1eYxSbnY2n3Jv3CGdorcY8OmOnNx4jvJFJr12JYI4HeuGec768XHWxn9Infw58IrIG37tg4MAT
fYWGwppQOIhEFKnY8ORsZjH2QW_B0UbhYOMOtXJN3h5L90R2-H9Y1h5zVwZY_yIg1jhY2B4Gs-1JcYBj0_-WsjbeFh4Ggsx3WnMQ_zLtJ9ofwiH2Z15YZsmF
Qqmz1eZ5CKHYFMIyZ5Y8iUlOavsoUQXvd7QRASJYc42i_uTZlCMnEAOJuyzs-DxtiSmLTSUgwhTfJ2KMn_IvufPOy-WvOcNFxkEOJWoHsCnFq5cbeaEi4tOs
ua1nV68XTcHAPwhuKUkASOpcGJh4w3nHlW3UJuWXNj7StoKj3QxuE1PYLoqiia-iTa9z0h7ScQFjKd3JkvSgn30kQIfvsxrKkLyHSP_-tMyZHSQnPS8TfkPT
t75Cbmn3CPzOYBrECkWyHVwJln2ptlw5tNQVWQ5OY6bJR1yPpxV79HPYombYd7iTnd53RDQVrNB0byuVXuRObP8Xx5hOLFm6bloDfluXsaUsjl7EapYc3nvz
Oezem7X-J4nY8OOisHQ6lWsByouMOfpvViLravt_Nu0gdoGXPeyVwpCcwwyOtzMNRpbIa4bVOge7eGzRnF9Tt0ZNFN21LM_QGUKxJArVA2WJMNNJ_JmHOeva
b8KCxMVYEAjOYEtDDW3jAFtKKJ1-bId4E3rk80Wsq913R40oDHYuyejn_iz12yGaQlbLnjF18uPnGE7zJpjkY7t-hmkJtweTH5RJ8m0BiOyAL0d0GkpZ4s8X
bd9IOie9iH1BEIanvQH4GYpbfCGuTbs9v0HCXN4inE9O75ElYPZFdrTXpa3SovtYyzCLkSemQSJzUmFYs7ePC9_O8nCS2p4k8EOZYsF6tQUJTnB7vkkXxoQE
JG3cMXR7kB2WfSc5x2adX9Wa63KHMHppWLqH16HnR3puJlXlPY7c6_R-phWs8SGCO1Ds6sA-2_EdduIOPO9_CiInCeWPSuvffmCXvW6RFsLCL_J6SxvcSKm0
DXjP79i_IVIF4yVyWMHPvcaMOdv7t3wkxz5elo7c07k4Spiqa8MO1GnvUFKRH9PyAvLMqT3uBKqmzgTzyWinV_As_1cE_HA8TP65c2y4ooOQhqUqBUzA33eb
sHrCPRRyYiZs7iJqaimJ7PRTT5YrmLp63B5jv5utbclNFmWnOS0SPDXdJ1pJWVdCiDjoYFM1AN-lnpbcBH74q-P-nD1AqeTg0vJpl1wve3F6iOONqcAJpWms
6-l8vEguasFwA6siaPhZo5jK0_jR5VDhaWPp7mNm11UT9tlVVHzYI4FKyMTFDg10UEPkC8ZT31d2HixQlVvXIo8MOi8m3etzDYfbAiJSBBlHfTJ5B8eACJ_o
cY72Xaf2p6VcfK9izkesNC1BQOvnp3VhggijNA4RSKp_mIJ0vFL8WFcEwKiY9vbH35nfzciBiPOPEgugRRKgn9oob65Me6rsDCkn46kZpXtXATsQGIp47k7e
cYZOgrKXPiGUxcKdcTo_fYn_YV0rYnyX9Y0RWRROlEAOZsmR0PS1BCJS5KK_b9yrnAGOp0o_Gip91B-K81FB1JAOX4klZ3Xs5BSTXjZy3otCvXN7_C2qRXZ7
PZR8eeo4sEK1wDDwMGWnarfLqUJdmLcLXLWgoy-VXbWAIs4fB8Mbi1IMmd87YvKGIrqXvYVT8yHoarY8fQoSZ26MqjQRE8QziwiIOaPj5YS_kVVjkjhMkObY
k-Ekmdr_k85Y4WUJrFmSo__bn5O3rJiZLFGrMRyyrBU5BoTMtqqiYWLP50ko0AkwVK-CPFpadrkrgIQR1w1uP2wmMDQW60x5Wt9Qua6yqvW-AJynpEgC050p
qnuE0CBhPooUbo-0carHw8XV7dedAlnbhxjk5iYB_tTxS40000310An_Qot0jmq20000000000000000000000000000000002W
}

