sprite $68 [91x91/16z] {
xPW7ZXWj34PTF_3z3_mNy6GMPP7a8JtpakteoHXJwKVmylBoyiA5PYKy8dfhS5CL_iGeQexMUqGJge28bTvRmw0Dtq8bSeam5hKCx6koJsR2qiCBQeksz9v5
rSm7DbB4I-DAfYkjDNefrIXbhw1kbVHnKMsVLflR9vN8fHBfeRGW3i3DnXUXbOX2PKUgRx4hPupgSDu4icCVXxiGgpdWfapYNbRliySsj4DlJBmPcOAQCno1
wvWwCo6IpVIkftgbkbqI7aCuScvJpPvgbDIT4dEUNm4J5Z4WXN9zGnvuD7LrkbqfKV3y8lH0RRVwTgoOSsLzshIzUtxZlecakF1n3kRk5rfIWnPM5RlIJbrV
KnUNo9DLjL2e9-hQvAqlr-8xd_EXsfrKiWPxHCy_Y7wiluAwVr4BM33K7jtDMdJ9UIIG8xLxHkUPVkd1rn_iaLff0kKHdAIPY7lBxYXkjLJLjw1r8b9c9RBf
WGZuGAqW6-66Znuqb_azaMT_JjGZes547Oh6H1qvzu_LVgcREKo9kayrGyvpFIDb9L4YdkK3FSirNuFbTtaX-BX2CgDki-JIRU5tmP-e5QpWkIRhw4PaMGj3
7gcD4XYPv3ICtkEQbFPm3Mct-auewJmv9GmvL1FJ1ZvRhy-tWlDTXWhgxxVjWlOd6cBegYwVGywFEES7ixgwVfoi7uBNz2hoz_BaRgoxepilHtUvX-RvXKEM
2yTrC75T2-hyceGhNBR233k-t9rVIL6_adx_YtJz-lzBF5eW_7kzudYWfFurdhLqfEzEySTtmzuRbaTBHAjjITtHqhQdDpYYjfDQ91dcV3bKKRqw4JUW4kAO
fSQq8rz6eVHRyVBoyl8l
}

