sprite $68 [96x96/16z] {
xPY74lCe38HLLeju_nU-Ss8nSRX6oBN_zpSbpLd4IYEANBcvkRcvkJ5J-KkegImJsNybip7WPghlecg6O6kFvvgkolU9p6nFCdFwKTR8tipC4HngCyU00JT5
xrZpldUxMcpkYE11HC2lsMcTg_fBZh8tMS5xbnLYCG7uuFdzUDJStLHclATi-cd18cmtN-rTtuC1EpJK40pVrO-hNmnxySU2rz-rTvC5yatVNGHHzhY8OrCV
SWM7xiCV3zBbZTvT5XYF8qw32HLr0AwYg04qR0heZvYd6w5oeCy2YcVvM8tgaw6B-W9QfNZuSsevRKhOUdjp-fdYmkFqpXORt5pEvS9CELVwxMDzqS1iOSJ7
3NHkdn5Jjy1RmsfRxH1bncHPwUUMllXLtpOQz48q_vY-z_om_HlazmXRNb3dQc28wId2p5Q9LfE8gQANutVgMIoQFH_RjQZcOFH9VtNvOfnXQYOUIjKAedxv
H9_rln5bfetP-PYPRUex1Nmc459aoW5Tw9lwA1DQYYZ3I17lLWPXKtzeP3i-cB69w3F5-Ae-HUWDCUdl-rFnMslETeZXM_wWyikN_yVJVqBetwXFUmY4d6Zc
vQSTVI6gW3fAVfGFABlwuBbDqDQRYIYoevOOOhi_A27GSURBtjEghuAwtT-61xNrCHaGig6_XAtt_xq3s_VNnprzktxIhVLzVjgfruysHRGpMuI-Z-TR-dtU
7bunOhdYfcgUjxVJjzlw5IbC2lDfLgtpm_DBEHr4DGR6b9NswVa8j34G6H4aVIwZxF7X-L5bRCWD4G5xgHxZyldn-lWm07pnXqDCNmBQEB-RYM7u0nFpoT2z
-mUeY3a0Dn45OrEVCbyFdFvuaFZsVPeUgcJK1SUiltr_fQS_kj7-D-xV_kNxm_ryhJK8hxTgZWYsbeFMUBt2pKvP8di2SMZstwSksBrLE0i6NJXZZa14aFET
TvD5xD0ODaoKSQTl8L_bvkRcvkON
}

