sprite $68P [96x96/16z] {
xPZPkgmi34IJ55MOzt_WVr3izeCp8TrNntMtM_SYn31QnyF3myF3WuTFl3WBScUh8e5m7wq0gNgy5ZP7v8-eZHnncw9cnZl2dr958XoPj2aoOHVS0m19YkIO
CMQr6JmpR09cplhT9i2aFsxurz_t003_Jd-zK0tYuzyhA1NuqGbAiB7U9kZh3KVCPtwSuaVz0JDG1onkKNe_RGAb-Yz2iUMdICKwjZb_JPvQRotIpO6ovmUl
1eZtFqpm3WSw6d1pIk9HFgrHPnaw_1k6T49uVM9lfTGUXZ1yiFdfpGyBO2T1FreCM_UtB8mKkbtysyBqITe0EGp86R-FiLxnhaai-LiPTIaR_2lJSuHTSDYY
t-oB2mQc_NxRxxIV0Np0JvgxxGHhLfuUM94l-qEmDfifishBLFTWVW7Zsq-UOMwvX-xCUZw1XX4_wtz5gPU0oJOlkN3JlxtIuw4zxAITwCWrYx7Sz5SxW5eI
c6w8W0MyjLLevBg_x8wQHdebn6gfyzdd_DKggIrKSV7hKtwbYQgat2pvgVX33ld-KrYOnou-NEJoztqNeMUravhjaItMPmkIxwg_Z8JIkhOslY1tuT1Mc1cs
StWL8stLRwGXsgy7JLIk6mYVygFv-vKH9F7Z9Juplhs-_3t-6Dzsjoj-VtsFOcCq8Gn_tkmn5OCVYguxmXq_I6htHxyzx72M6txjeAjcqco4dD_V1W0fB1Ez
2D7l3WlzplwVpTybWc8qkpHybGc_mooJGwM04abAfJixpP-_QlBKnxjU0YGBp8BDwzFdn_vrjuCY5M_ze-ZTuxfsllOmBv98IcAOOpXmBju_k5cWbFE0BU_y
MBe_WKIS-McvMl2Zzv_N6wGqsiqpOz5lvcT-LgVdxz-_-PVyw_KmVu7Y3f1KhLkZLf44tArHizeKoYJ8kkN8U0FDwVjd7qLLR6XiThD9N9avNFxtTzuaQyqX
-aKU7XuU7lu5
}

