sprite $68P [446x446/16z] {
xC610000082W_QaNgG800000000000000000000000000000000000000000061sxCF8eH060gZ2Q6VLVyCdkEoCiy6lWHz0yTbvKNbXwaKMvCWVY0YJbn8H
-OrmMOa5SmUKS7VJ8az6LStT0J2tC4mMeM0Un0Rb6L9hFxB2aliHiWHdZk83Sgj51780JUONUG6YyKORkHejvWM5UGwwp2wOry46dJScuynBe66Jbs6y8-yo
Z2ygEtXyGevx9q_FkL5bNigS7DvvyuNHbmazTlcYThy_5Wazc6hVO9W50EOB0H1crj_VcN-vJ2h_e0zCo4-3sBKrY1M2pqxlhStC0uNbqTaHtv5sMb9PO5o8
aHL8GSEy6w9OEMsXW_nbCYLU9Rr40VD6414kmtJ-miSTeNS9AnxesEK8TcZ26ha0_dxRb7Z3ZP9szWb_P4VyuTPfT_sgmDcdlG_spaJBSPK7mcWf7VB-BtpF
fDtf9ksho8x2J1FLlyoUnPzB207ohoie5JqkUaNlN_zowzEpfOS5RWjAYju2LSubwN7H-ysozw67fUd9alH-x_UhOWjPqKjNqQjneUZ9-z1RU-dPQ45wVMbw
iZOzlfJtYjw_ghu4lQBNrwQ72UysQ2wz2zTqzgnOO3jIuN-PNj4Z5ZLFK67wz-WLFM85B23WHIR4kz2JbYo67P9oBO2TfaUvw1HsM50kUkV61ShFKOuBuA8N
rkK5z0ZsbBJbIOhU8R7QdW10LOKtYQe2-vmXUNVIcz3hBnpk8Cn4kssgMFIL_6ZfMbBkhKau1OB5VagowLsMNa5vmHG1AXJrx0_JWbjOHI-TdJ8zbQX2AIsf
Bdg-r4QTkVICTFjPW5xj-v37WnqHyJSHFSvwm8dqU65wqfuIt6jEB3yc201KUUUl3Y-LI4yMBhL8MhR9WPHoO4rj4AbzQIQzeWUXqKbgZmKP2RAcUGz5Bo3P
MoSGnU42zPY_w9IneRPzwFs0Hsh7X96yaxLa7tukUesO3oup-4CWg_BVc1DLmmYE-kvyWREynydq_9YfCbXB1FlyPf_iBdf-kHCglC-PTn8RS6trFqZFw6Ni
1ilj4eID4YfwoUq-cEbukHDoRcafQZ_c5HiFv0yA6aB1PpUfa8u09JfBqRZt-6qRHd1iyeo7E_o6NV1EWPE3FWS7wHKz0qNfWNxGONmMgc40cBs52ev6MuaM
EekUWKFqm7vYiWdAz3_nauFmmAteIJGT0GSW2pdLJdSJF6iC2cCO84FqyCRDMZYKKCZzma1iZU475qduC8it_R0ulVZjpZpya-CLCjA75KuPmkPxqYE7dejF
AR_Q2UT5_IZk2qNlnnhiApR4Guwk1FCxjsoXm_aOXUzwaX_mlks5LrK5d1M-K0He4V4xq3kwTmnyT6Fk_IuosZjLAvG6pr_WMv-UZq_TlpG8ahQ5KsmJdsdP
Kast8wadl6gd7sF1cV16xr4rQucadiFwqC5L9JqyxFhgHM_7MbxLqqVXymETVT-YbvDwuhX5T4JZUxxQ9JsLJ8kFZ-4ba3uSZOwtn-bnqGkb3oJGTbJYMKzj
W5SDT-3IYy-xqaIgGZ6p5prpwSt7bv1i5hs4Od6s_FggBnIz-VZYoMRHu-OeiCucC-19xkXUJShyDUxvy7nwLlHcvIv-T2vw5uTUzg0qFzaiUlbBtVETJKKl
7DpcmojwdTe4V9aPRT7B-rfi2IPnIgb9z2v5BpEjzmtjEA_eSHQzCNUX6SbcqPE1tknQf2zEk1cANdxkChy6O4Kl8id2nrdbqw8ttp9wADaiUjAIyN72z0Cy
OIcbw2LtXzCXNqcb9qNF5MaIFKnvrbArT_IR1HuNuI3-efSeVlQPY2pABKyeUZL2l415h-XrBdgBDyQjgaJHAtf5hveRStclw9NtYjxK3i3pLVIgDNLvhxuK
AvJRNv4eb9xmNj7J2KVstBUcy_JutUan9fntTjyQ9xveqHlxGRVvOd_VHNallZ-TsWcHN9MxusLzx_ddsYPi6oCsktofcz2aFMjKz3wbTtkSEUGaWlNB3mLF
FR28q3CxHgtexPzJ5mIk9Nz3Dwftn0m72cwtBthnmmgC3QNBxkAfov4KbvsDkaKld3P4yq_QVEV8S23Fr7lp5JqSjPxS3KFUKyO2ilWDmnX7lgBNvUZf40wc
WFWPAAzomwT_B5USzonwddIq7ipt0TaT8mEOc5W06mbsE6-w7wtv33sy9RqnY56eJnBtaG-vsOn5CoNVV3wzonlJ6w_RU5LzU7q_HqGVyCLcAOHOiQVeZSAk
zS0FuPcqVH5wuChAw7aPOBufFJjAZ_Uj9q-T_I0RtUStf1XpfpUcHuVfwJ3pOhyjW8KNxj67pn4mdpgcBtgXmAckzN3W8GZSFT1Zdkc4pg8NEXOxMiy1uaH3
vs-xvXjWQdXBOD6JuVxtytPpS7ZuEdpp6PrvM0SNlQQ3sU2DUl3W-VZ8DvyuQ-pblUZZpTcrdi_Y3EynpoJdtSjxRgr_y09xAFgPIZBvpkUTE53U2nTQw67W
f1wEc_5_9BitJtalk4TLXupJo_ea43UTVtKaS7DvBqRFzkYn5mJbrEVf2Cms6KVeST4R8vSNE4_kEaSeT8A76L_A0RxrwV50pyiQvEnjtfrSn_a02GyENfzU
-DQt7GX4zFLJntnEn2M7Nj1xHO-65C997ctOoxaDPny_DOphWpA6N7_WKoTqb_S2ZVlSb8_lwE7Rhp4a3tPxVuokZIIzJgsilEVV-UoiRcCCdFZSYcGV6ym-
jYHrsc3rlaqul-CyI2_VUqMFRd6q6pCpVT2Hwm-TDrZ6SlrXy8YVT2Pvh-XvISkDvLSbnpx8y3Tw-01izFqgYvjqJlDUqREhhuXkMtDjz1u-VkpqFU61Is_u
F7BGUqLlpDVzbFFFp_078OQH3ksBdcmNDPkUxxsYfmuztEZTS0veDtecrl_yCFnRcUUzyfvFxvPOqlQUjnd2y07cUwzopf3tmFmH9Ab_ehI1dibXUkIKgMFU
AtgnSM-RmlU6w-Mx_bmsUXq0xv2VatEMz_oSyvFZ7sBKDvJRZtOFoX_tTFPyh-XjSpcv_hXHswO88xrXlbUrbcHwihSuAdwbR6Df7--5Qzs5FxtdqAFfTSvQ
OnXFotQvtoUz3NHsVL_iqFFhdEC-CdrwZQ7Mz-2iCM20UUaOzqplqHiIdbhVIw4NltWZ0_gEppRgVICvhjcE5i4-WkorzThNmg4D3iBVAV2ZjNLsw3cXkxpd
2D4zPN9o0n1zOgSJxr_UywNEAPwKFMK-TKxOprdqtBtKO-g8Svz70YUOT2ZsbFSIpp7840AZWhy3UvmYuDWvXg97yLCyTcBau-uwbksPCqH5x-v-zzfkI3--
5zxypoAEyyjxQMTdHnHy-FmUVECxesxCU-rDwJ72RJV4VMNFhUQCUiu9fZf3bDapmfn8vT8MrtgsqpEYpX3HC_rQsEy2GI7dnOvUwfa7ijVPsP7NcBTe04WG
NgT0hoIdsKYTMtTacoZGP3Z-wl2xPuxzSCSOKDvBw1583_1v8KxSVcPxjmav6MTvBzuQrxpOIHRfdMg1nuPZtthQ79NtlCHzZ6Zih1auRq5s2H3MVUiPj_9U
Ibzg3ZGsxZQix173Gfsf2K_tfKRHkpDVg6A5-uxY1hdAxBwpk3oihzBvdl15RpVFn4ZF6TPyTOU5ddqUGtKszfFtpGdguOwmCteKhY4ddeLIzFo9SoE1Sc0k
xiaXCRo7Mo8eUhxyFFFqispyD_VpJrz5pqy1uuRzFtHkfTbtlg-Yvp_xiXqHxncm2xMel4xczHIfkE3GyqHY_PjC4fuxM_IcFlEPDxL1cMzTz7p9ttlUkZXn
i-Z5n0fjVqSCI7DKz1PGqVkNLK_Bb_ucz7X5UjpBUuzKz8fUqQl8MTwp9Mz9MjfxHM-HSQ_epLDvh-Z9PK7ljVUXDtYlw9NtYbvvh-WLFMc94bLkpuX5vJNq
P35w-TzAdPNt-Fu7fVdqYXxvMq_YcpRHieHLw34plPGUmpBefUwSiJNeCM06VTazwP_mERvhaulUpgLzsNWWETTTRPCKlHzxs4qTUhFX-VUP5hrDR3VHAuvp
amxmKl2PKYgzzckb3ZrhJsfi8J7trOhUFBVCTtBHop-R5Hz59M5nTZrwd4TFmgSYvoT1TFcDzFXEkAVNqkWvKIud6hyRFLBOhlBf4Lnu-VZMfmUp0_GwPS1x
uHmLd47FVjCW5wTteGd9Pb9GNfyUOHOz6PFDV0cSr7FDhjGyYnvRChpyjy2YtZE7NdvSouhDwzFZL7hpuOsY0T_wzDe4Uau-Fo7rNBg_8-4OFSo3DzNb8pt-
NKknSNh9kQ2edB0pCGMgdelI6yK2-_uVdrvkPHEdSaJrflni9wtU1tgBLAdzvTdu-etpLifPZP36PGmgUizqsoP_xPHmFCmHl0rD_hiMlLDZAiZ_ytYM8Q5_
4S3dR_XVb5vFJJPXNmBJGzy9x2PGyf9VN-BXU-BIIwriidqN_4asZsjP6aoMbgVdxmWSwUKs5sRO8B2J60z2tFZhFlZIt-Xy_ZW-YSF3NHo6CXErJn4H3wwB
fZcCDtteB0_NtN-0OZpjYvSB0EYd0DWFAHqQTdbvxurYONOUe9YxZAvsJE3qifcVMA_qE9JyRN-iEC1EMbYAE3ufUd5uh2hZN20aC7r_2UMq-mX5Bnol-4Sw
oW5s0ooDp0Z4elXiLNeD0xq4U0qxwGSBuBXEXPpZcu6dUXIzYwGSYMJOxjajOiKkEMRQ7ob1GNpWABqkozAp6Bq1oi4A9p6hVGh2x9M3GD5GBc5w_Dxq48rd
VeNJBxl4v-8Qz5xHQuBXGYLKEBtP1JXQVf2KjiRhzpwaQ3dkE0Pn_bNyCnMz_EClK3-2CZlLpkfZEUEh-HLEG9dtIBDkh0Tsz5SQunOzVuOE4TaWYeZWgMfd
zKwdbuMLNJH7govKpJbTPTAZOUPD7E3d-au0o9psZaLFVioSZ_9JEjcjhhntaPHK1NnkYGWgkqluHXFQEnOzkM7WlGgABsNwlr6JiqkvHSylaSdFEeev4lPc
75nDoYR45V5dRCoY2k0J3Fv8bVd1R14jegA7p2dw63-7ZMIRYCX_cVmsLrpjqiCpTF0J1fxGOgxe-QCRXAc5HQoxvSvgKZQf6mR3HY4Aa4JXJF-I6YKjf-HA
XBXR_NpJ7W-QHI-fsE9l0OJgJfv2n2oAbvQgQT52cTDm9uMVkmzUTPW_fB8hUldnCovGonEMfcUleDU80OlBdoWMlVcJMMPCH5Vqq9B5cd24A8yU5xs3Ob4W
0CxPkLI5ihzvmeQOLVrp30dabcxtyVVF9hA8tKj5kAMewDdKJlNrTDO4yGBRFXPezr7q5cWvK5kD1_7QzCQs4RL--MlfNQHIwWKQ3rGnujUew5Mn9K55huhm
wnnQBthK5wSdlUZLqVL_Kln6z3gj_ENQT1MzEdhfgxzymaUD7lwtlKHu0thv0z_uaEdU7_wtsuUGk_ZNLwMN_mqPWFIhBa-g_v414CxQ1czjITdbN3s2jiDu
LtTTNgghCxT3VtJogqbRKhWSCXyniro9sU2nAUhThYI5cQC9sIPgIueliVW2m7gVJSoFhW0uPhrBMrG33wFxWyfoYuppmSKZAtuSfkO1dhL59UEL0BUDcIKu
RQuRRqrtIJ1yzCvjKV4zebHcyzLtle6rPONBwkhIrfMjJWzjOV7grcjBI_ghSlgl6fXiukryzAViG_r3VpLk5huFMX-Sw41jXAxYBw1z5hmAdWO0tDB5062N
fpH-h7BVBI9kaN26-DEK1mEiKNi74Vh5rmtO412dYuXkA1-oa_OsmZu_ouoA-H9W-E1EXMLnoMVozvacjjyZ4X5yPQy6QUydkkhNVu7_sfy30G000011_jOB
Z506xG00000000000000000000000000000000000008
}

