sprite $68P [446x446/16z] {
xC-n0G0G0C2m3Vp_BvZj8BcWBOS30000000000000000000000000000000000000000000WJmwk4_DAx8ulR-oTYPAZEXP4OrM6zV__E_lM6UMHqja8Tt3k
BEzL59Quzt0aK06MVjprXxFp-3RDB1xBxvN57xEti5k5BXzT9UdrMG0lZ2_RBU1z7D-mCvol_Cc1Uk037lWOD_D0FV01xwRGC-ZzgIFhQg-VGEyFc21tiJoF
tdAvoZvozrWeRMK6FGzP8ySSauBKdaHFiuxRJXQXDxjmArjcadxVbIm3vwSqDVN1Pdr0xqyCtBi_S0_tpYV7uScXoTI0UsMG7UwH7UunC-0Uz70FUj3Zu6HY
W1xkGG_t71_kaH_k3Ol3z9WNUd3744AlfxOR-ZPwq1jHV1Czw8quhftN1RszqF2uQGY5Nc_TUGDnhsTtFp_evUZwq0q9Gc-bbFuTEnlt0RsUdIIzlVjTqaNw
GQzdf-8K5NgdRZRMp-XKiJ-K8ExzY4xj0O1x9vuDrhhkEswfd_ruoAOtBpWLNMnvc1xqj4Rtdf1q9pteJIt0hH0UfWSzlQDGyUlf2Ne1FYFGyvjbG6yVNu7E
vao9AuQJkKbo4KVZdpIb-OtkyUSzBVYL0RsUdJDHiErvUj3JEnnIz05U6v7Hst7g8_6avOIPuFFkj4uHUjeggZwaeFa1FoqsX5vw_RKayFONYkcDPzEJPROb
rJuzMGjBlHJH6nazt5iNwyVpbFqrwdrwsjqGzqoB7NhPIdKCHRkOXNlxzShPUPE6Vpr21pa-zwuMQT--vYaKQSb4zgbdkXVGIoQbb9qtgZabROgdlIIXfndX
QrQemr4JUcdX5B0B8eFtv2SP0dWXlhTi9CbcqGYVCj9-Y3wGNdxaQ--UQaa1laX-w0NyLl2c0j9Dtz3hB_oomL2EBp0lfCVBMhJ6Dw8oot5Nvda8zn87VBKp
5deapgy3zy92ojY6RQxxX5wLrmfVocwzmXbFURZNBvlbIg_7QkZrPsDNu9EaubY1tW5yQQWmRmfwnQfL7sKtqBiJdwoJnZr1BxfmxwFj0derllFiSAyVryx3
mxs-mFV3mxr-rVE2X-7JW5vzId--MTphLvYFAvsd2JqLfUwdFEYT7ELwyw2d8AtCljFmSE_aKd9_4GczLvXMN_Bpmp3kdQ-wIGozCAj-yjCvUBZt-o_IRcW3
ztfyFRsk1TphyTtH0lJww6jVD02zdbz_lNSaJ-Zn_PxG8q-omZtS8olS8okEKkW9UjyGk8Txq1jZt8KYxnhtdDrfVDurz0fuf_5vrqmHdzBJk0zVsZNqFCQV
ImzwwkXrHOpxXfuNi1NWWhV4F8-UBASFwxTNojVRsEtJUrUUAEvv-OAlH0ZvUPU5VBZdyBRFFr_hq4wNZY_E5FT6NClNLYJqSdouvqygsC-BJfPH732urwet
5bqKe-UeyU6U5z9-L00lrCzxMNIAUtlgwGDucx_ivSCz3sLLNC3HL80leOTxVHMTJB3HSi36lLT3R_saxEOvYJRmEQ_6FUYvUcNh6vHB-Q0t5PGmQbo9V0hb
WvwNK1czQ6IRdNpGYmlObsirTdftX-X1BpwlY2vMZ3NqqekzW4M1Rxjtw2Nr-_yeFjcTodpejULxNK1l7gS7lSyMxZBreJTJUZqy3-NovVIWfu9UFVFrz5uF
fkThd5f8b8IEq8FUtBlOCop_yw_wPKFv1mFvDTS1FNqmxRbI_ZjROB7VvXDlJm_tlD7N1htNENhGqoOzHsHTsey9FNr43tfpsptlHJ_GCtm7t8FUmZrJpmRH
V_t3VbpJcrVHWzvQFLcNTz63tjYbfryxiHuRUYheGIzrp_7vBnNIcmVeuTw2dctzXUunxwsl6EOyDkz1BtHlQa4lNkXKGO_hlSWzr-oNVqx9FdllzHvhBJvo
lg7dNUjxwB7EQPqiwTtl7dzZyDF8Tp6DthUjKkEUznBJM_zzRogb1pqPlItvx7S1lPD_M-U-5c_LdfdzZovQVF3Bw75FcIChfhsQ7lJ6WNlA0lUX5pp7KD3h
RWY4NfZH6thgRmdqtIdKXrxx394kU8v1YqS_eNV5WmowHBqPmOEUooS53n7r3yyAUXRNl3AYVtQMvzOlTSyhgA3j5fwh1xrSFYNolVez6KVVryAxacIDDplY
dikiXrxtYi2cUGNm0lMWLxra-BNN_klNg8yQwENoZO1B3i-wQUb1JslvvkhjgTfxkR4AUD3htj3PlnlNPxsU7lJ61ZtzZlTIgvZreDTSDYlWbo_nvAdoRHhX
qmGrl3bhUeBUp_9fMSaQtfny3z5lEYALbqyfEW-f_0OttAiAMC1hEiSz3waSkppwxxx4lQA21S4fNVEzixYtbY_iJrhSS5lGmxsqXFgMxrl7lRo8yqZqNUEU
X_xnlvj2AXB5lJyuKToxFt0FUhS5zA07FPBYC8KUzA07FUX13teiGR2en2K3z9uoGq1FOzGjw9uyeJVQF_-fQW3tUdZZhXPmh_EcAhxVUW4zhykLMGsZLxV1
oEbb2UZb7VJYM2FGixlOKtevlD_S3lI65KL1LcUBBcy9UZ9wGLenFBLDhV11JtbQlI_d3mNSwsqvZm_tUlFkdqM5U_jjNxF3ZtDlU1Jqsb6kp-1Xz4P5xtvu
Rj-Zw8rpz88Ibsttz0IzmeyAtsFeZMFqheKtLKz-WjvDvdakpt1F5RrUZCFdBhZNMg5v7pxEMafuLuQgQn91xqvudaxZteJUkfuADB6FRNJtY5kf2tgjU3RA
PTFRSlBJ8svAqk84KPvN3y-xKiHk5z_GisufStfbNej2Mazfani9GC_SwypptsUYQ2o05_RXNchMYFWDYy3vnz2RgNl503OyefEheE_dFARuUzpJRfKzf3Ul
Y_G8adZapRXZXkxbOzTu5ykLs60F7dOZV7qhV3gPvH7jmnFeUU91ObNXFa2dS2yUz_oNPa2lEcTG2gyuwtqAlRcabyFpZJwoJzlFtYh01xtWW3SIabBjbdqu
l-VHopFRldXpVZi2AkWcsj1FhA6N2we5kb1mR_DfxkN7fOABwNUR_i1DraT0JuhTmxti8a5MSVifMLtBTybJnBtu8Y6-2CWlA9SfufuqnzG758Oq0-OPTIqt
V0YzrwKtP2ZRV5JVh06z7j-QY1PR1W6zCxToIvAArSvcSe1UY2-F_sq4Ui49MKsi_mkHDy2BSGyScLRj6E3x3n_847e_8D17x9pxkRa1UbxlmhiZzA2NBt2E
OFC3z71lGIH1Tu0U9vrnrOU7rfiCGUz4SjjB9fggce2UvzOd9tLhNjSicU5U2M1ylZQZ0maoxorlOOcXzzxXNk-VnyAt7XxqUdnzw8841Rq0O8CEUWMzE_bT
CB53BukRuU7UUOBIr1rtpK6l1pZ5DqH-sR6fRho4tltPIUyXwg_jtOLH1J0GXi7nVoxzzukxMupiDW0tNmIU_j5nQUyDq6stsNj3vDgmyUozHQdNr3EUyOpd
Q57FjMxlMPscwyx3k5QdUlQUUWPKRt_gkTJLgozPfPvyzMk3HrClrKKwZAPUJQFUkna6L1jMiOwhLmEg3JfQwxXwJwTCRUZTkV9FwvsXxKi-zSIJJptvn9lr
r-Nu1PFsG_9zxKkjRBrVwBBMS-q7xs_8i7RoFItGwxlcsj_6ay_lkPHyzKpCZJR9_G-lQFTKaW_6ppxVv7alxInfsNxH7fdkNcwrVVKU0000000000000000
00000000000000000000W4i
}

