sprite $93H [434x434/16z] {
xDc7RKGn44D1P4BRVy6km0YNbvhfu85VaiEy7m00000000000000000000000000000000000000000000000000000002HdesIkT7QRo-JiPw-5Ogvr3FOK
andCPgTH36OoD-Ax6MmTL-8w5msMoHvp_fCh1fkafoRzWqtAUggaxvFidYoLLyWJKUlQP2dxZQkZTR59QrbDs3qFjC6sJPR6gAcIV7qnHqnU-x-IwXRBiYA7
BE_iSSZqA4p_OYbxgD-Ruv1vnZJkgj6OOp7FcCN4F2aM4od66REOCoPIZ4Wn5hEO695YB6OnCIB5_B5tRskhua0GXi_u7hd_-vtznWXbKxq8cKtr6VEZ37bN
DJ4gHYnYroedavECMCGYbfDX-xlu9vzanDXK_GDFCc9IQtxS8jQFrYAsYFbSIz0YvjVMgjseYAsCbn-qY2sEbv-qYAtFLzyiOlswfZ79B69-5UFFNq7aporc
NyyYvdljq6gaaqyoOchOwJzuvab6J8JBAAirHkn-i9rl3V3YaqHiffZsul8hPfCiOlrI5oz_Al-8MCHGeznOc-8niMHix8Uq5peU58kOI9UNDB0cYn7haz7t
6i7vrytkysuBhbV4-YKiJ3CCi8ZDyVhT0O2lINpo92E6p0tMxbP5h5yYCcXXmHQnLM9qfHyvoOZnrOlYRy-BHQnUBTGkB7uFEXaJN1eDkY6BMB-E4S5QdLgK
iOWDs_xob1-nYFNhCFoc6JsmYFKBkejLrefYnEwkzIkA4VF1_5fqaX53YL3kiEGa8oR2mnNP1ISPiQC23kwD5R5hdKjuYS8KCrWZPeofbHX33ETv8tQHmPv8
m6MnOhU8zKPBzaDT4yGYPhIwOgz-oyNfjn7p1elTB2k-4LEbhquuEUeJZuSI5xo85VrenY9xVMXlMXEn8zWaCdre4RA8rH7pvsoyZeKdTYGZOaPFjCHUgamn
Bay-8hQfY6rslFoWYMD7pEw9O-Ge3k863J7PyCWYLiuRjPTdTdxfEWX6pEnBuuWMOBgC-Q4PieXztLGNiBgGHnIPZbXtVgt_nR-y4aUi-cB4p8ZfuJjN0G3n
H-EG4NFc7J9YsxUMI3dfvzBB2MHRZ5ZTeJJOPtukJVt5GH4XYvWilq5TV9KCcWnvd74hObLJr8bJ7SzO415zqGbPnFHOeS1KGwpDw1qtOhMOlehveoJ8YlOR
CLrsnCn1ekwBnorSiOZfSJF6IFwVrAcIQuiH6rNgALjdYBoGdN56J4HC3riDvfCX0nsn-vfYSu2AoGUNZXsnmkY6Y4dfkYr6J1IY3OgRGRJ7nscBx17hBL7T
rHH7Q-iY6h7-PQmVCVrGRXABM1qnzWwPRejKYOkO8wP6_Swvnv0uRXABs8yDJYMszyKYjXTYG-OO_yfVVtdRgMoBnrLC8dPMQB6j4XitnzV8RvJ37WDnSKH3
B6BLLF7p08UZVUvMNCYQayM8eQygno5dUD-BuN2-61snY2c-OyR-sjZVZNZR6c6DgOSX5Z5hglZP0D-2D6HiZbZ4SCKOnOOOFY0MiRsTCTwEmCb4PALOn7HN
7Avo_ronNCVEbFXdYaKC8RQyAqOCiUInNYnYo3MFyHavXcnyoURF5VS9ObcbEd--yJy8CV5mUSI8oJB4nEfx8SPbCRQsMCGm9ukyRTGPOydxOtb74x5sBzOL
hOd71B68ZLrEY-tFYqMCCx9nOsoHHx4XazwdtuYO5jDN4YtsSK2yZtcOa_k8wRlNNFYy8jpxUKN6X9jY-TnzGQQqQZ6MVEu-OltFtJ_wtPPyVsozMCJGTq9X
-nOo_ogccwBWYvWRCgPzHxF_FUY8CUThjJKOtLkm96F555j_wUzrKq-aBvQx7DMN4t-Gk79p2CHnIx68bRT-O_8zS_pxKaLCRnx9C08chc9Yypwnt5znGC04
wz_wBMBzs_MzXYgyIZ17B6B2o20JEHDxEHF5YFctY429xQ_IZCzTdhqNT-vtNzyytVYpNXjZ7xQ9c2c64klVxtuKeuvOnFpVRH6ZvuAD9Gudm2Bc_N0BnKom
Ahxzi2QVHxF48eOnQDXWVa-EM3rgtff3NLD_CIvY_kzesbxws1-Rp17BRzNYzyEn_8OSCJrXa_lNQZi_zdlG4TEbPspxvG8EsRB4yC0YTlmXPc1l5BGU1DSd
YX5p-z6mZvKaZCjfn0ooSZ_VxE9Zd8X5Z6jY6ADgHqVi5x5YcbtjPPYP3TS2YnX6n8oXDVR708kOcXre01-uji01YzWEO6IcOg3SrQ-8-RMTbTXl8bZ4V3E_
5franA3dHSJMdSogW4NCXqBCAehYZVgfaumOGrXevCkBMyJwDHAvlT5VX8hO7SNOu-gWwLtdYqLCBpVnJMr7FpfYyyNqe7EgnR338h68wQLxTjZO6AW6hebY
4VDN51UiBaRC67lZ7IyVB6BJrpeGljM-VaNC9zCbiFo0HMpnAd0_O17hL_6gsVHoz2BMdtFqb-uF3tV98kQ3_QWPniVi8dRVh9wcsV1aqyMIiKDMF3NnY6bY
4KC3GCb5zxDm4UkNI4t51WB-6R68oTx8RpbYs1RFSHTOn6Ql3axuR5N4Z9KEIwtnq8ZDN55iFeg8BNX7iq9hBmT7RCagy0IlYFcrsYjYVgtsYfXVB7ztB69-
jRY8sCAJOL4tZ5Y_uAeQ_DnEdTim081040nFq7_1plt_DcYcWzK9EZqT000000000000W4W0DmO0001e0iZMAwjHOSfoDcjfMpP6LIzI9oIDwukWlvOw8sB-
M9sNBINfTMgtNYW6cyPWpt1b1ZDP-dDCPZ2JzNg90nkdjkZqH_YDxijgIOzXjVIblG00000000000000000000000000000000200m
}

