sprite $93H [434x434/16z] {
xC610000082W_QaNgG800000000000000000000000000000000000000000000000000000083PjPVSYe4GYAAX4IMy_mrdRA4CapnkL-q07VSF_5V9JOcR
fUAa-jcNLjq85qDhcTfbQAS6rqQqUxpqC7A9MUpoibdsWqfvWMrB7p9Owk6bqplYjgJ1jaKNWKcLcrBIpsHyC6LGsZN90pjDUigay6GXs0Kh1R_a5s_VhtwJ
1HYiazWV5GaiUdoDmAt-WCHgW179n06BLrse_Vv5Lioo0dO79dwCftUzMrnSeST9oJl9eiUj0vN6NHVFbYNc-kQzenb6z0AR_bD4qhgBusPFNcJ5-WBrnKpz
fvZByKUfSVVbXTNsQF9ZR5wk3gaQOSMA97OQiCTRR4iiHarQRE_8rc8MivZ5B6OnYrdCOXQpcCKiPZ6BMSnY5hEOnIncCOjPp68M-sRlJ9GRntaWR3JGBFhz
NtWhCr5Yn2q7PeRU2_t_UsZ7EegV0JOXM7eLCJC0Y4y1WDa_abWJ0pp8SIUIuGxx9n5hOd0cM9ARunz1h8a1mL4KONyliIPcBd6TQqEeDR6wH7HLc15_1x4c
Pk1O5TrUJAo9cNDeCIB23vD__Ycya5WJCwTsyMBnPN0dkSIiYMtZnVZ6KCZ5cjihY3KnS6InjZus-FsUsuarCSHFajiTD68hiIPcKSHLNnA4RIJMn5ZZXL-o
qq3BZiMs4MjY-6vD1JYp752XUei-zX9hOfgNmHyilXpsWDb-Oaqiy6Grc0n0M9ZDn9gOD7XELgl0ffO9t4UidOVpooBA4ECP1ImThcRmczYw02252STpOW84
3t-Xk--xBJoZSkYCML5DR3ilCiBngOXGs8YN4sjY256CLtrJ1dXiYhCcLfVpkMO0V8qrXhsEM1C35ygB-4ePhoBMn8nh3LBct8IiYJrMB4n8SZc0LnDhOe7x
DkwFzWv6100xlzlYho7Mn5odDTt6JORZP1QCrn1hOk2zsuEJ3-l0AKZvwgpONZ4pWFEv7aLmvVPp4rkNcJtV6dmBsJp2_nIm9hRY_ihCDgY9xMoz3_ixYJKn
fuYZmA4GF8b_2B6-swAhYmPVhoWsiPt06B3Yhyo8luLO4ujR2D_stOzReOdzOMB0K_LWkZttUpDQuHAiYLM9UIbp6GMlgaz19UD64tjcO5dDYc4BDwvHQHUd
Dx5d34Kjo8WLjq9RQOpKQc9HTWU6v0zBigYGm2WtdpOnxBBWkkLHoygcieaPnTt6rykhfhA9-PTyXDXGf3XVin7gYzF4wY46Ydl5cyJRP8nQa3Kn_t8__-cR
nU2OXvwR2o7FFD342Y6MlkdrOGF7zQjcVNsjediCDh4dGWoi4mFdLMiI2sQZiifeOaOnQAN9n4RcbJMdLwPG_NMXDR5JGIUc8qOG4Qxtktud5Ih7CQ5NWl70
BZQnFDjRsanVUhhOBSUNrgHCXGcH3h9eOj-5M4Y3RJosT80jXHcFg4fv4RMPh8b5pagryVElKzOOn9iuxkOsdbMZGYxVyRXrk8aP7uKOAEkD8uSHOSBldr_1
U9SEiiS6ludvIKm99oU1QHTlQPORfcVEuskXWmnDx65Ib2lOI4PE09l2XGjcqtHtZ-UeWehwh2O6oZa53ogp5C6ZcPqcHjT1vlbBP4qiIQQWan3J4JPzuIha
4e9gyYIQs8EagAfyfco7Qz-kPPzugVEYgSdqGLfiOjGJIkOd3pmk5GqHaAcqaVs-I8jDJ2T5CQcPAl49O5LaCiXe2Q1eqMbYoWBGn4X1X1Xhm2IoyQ0L2DBn
DB7pxaCrgOaGmwm1qyWWJQhOEf_8cfXCWv6hHMBm9ovrsIm4cNH0R69V1QeqY3Hg43xHdxiOQJvoqjK9sPhO5q5w-zFotbZ8YMe_SG9ZudSoaJKnJrH2p2p9
Tno7jCkJcc9WzHV47rgF9XPgllUpf3Z4OhWcLzS2gedCqbOJox8SHz8At4VAh8VOurs5qQaHQsB8OvPXVWZYW5LHM9QCnOQwbYQc2_TsJYmbnUKGkzZC5oF2
YecOBWOtCLMEZJD_FPP2JEFEM8JrQ685Sqz5xFwGlAp8rT0cBCe5QM9DB0InD7vfp3-styBceEtyTSBXnv7yYAtZN_D4fiofzArDB4aE4ZInmpnCiIf-tpY8
sFmywn6KnqUeY8c0RsBbvHWJCLVJsB4rvtndu1zR4tV4Xfe5psVEAh4cPYB6X5NaX_SRTh7nNXKUzFSm72SnvYb4nRsUJCo_8zR4j7F3tIBOFyOVx-TXAcDH
n9YO1dz2h8b158r68fQjmtiq7P4tqcTSnDXEOasC9MBZXjYyRNUR7odpb_1n0PX_Dx6ECJzg6KUHwOqUZlyuVolDVBk9zJocYHt7dtW_pMVI8muuDngl9DPU
KHFBdTotLl08l3d7h__ldyTwFLOYTeJC_70Uxh_h7YxcCK5iqtgiYSNTUim_Vman9xDNj3U6LlUAyUTg7brNT45C7MwaqHgAsBWjSeszTSMktLFL5ND9VfeY
fkkAcjYUsdtV7tFHbZD-0p7Y0-euYJ7H8mAHXzVkZ_KzwBmwouVqJxp7uMrUvnXZNizh7X13k-SUTFTvw1l_l3swpVIZ8n5Z-HwqxlDGnEm7nBgNQjocHR_E
cwVYSBvjNUVlVMtCUUmtt_yruSvdvzEzLDslwEVMZVSJ6SL3ITDsajXNzYlw7oFMFS4wBQutvcZVmwVDVHFJRTLndnPzkIzddhShbhgucrXEJ90J6Uv_exBU
Toz2p8Kv1FktBLhwcnrYHDF0SwqZM8UOcCPIj3Un91P-etbprBK1CaNQA1OJOaPDQcBwgtt-g86nb1U7UbwBgwGuy8tnQ698Z40rYimEOlrtq2v2JAN1FA4s
iQmSH_gH3H2ZNqT6kSk1A5B1WoBoiveOfR_7sQFwR3wBpA-7J8IOTAdrP-RqSwbi20CWkk_ho3Yl-gTZqkIOcjIQcFRtod93lFg6Jo4R-jCO-JpQilw0M3zV
qHA4wbCza829dEWAaVNp5LSUruUxHrSgP2naHB4Sy26p84Knf8aL7eafD_MnhzCV1vYEnf0XDf0tBqrCIwSaGdX9mU8wtDHW-hWAO3eJLv_5tSHa4d8vVYuC
nQ4vyFXjBlT_NdfUUv5OlrD2l8kC51umGPkasSKkPkHCkEG51E_VAK4JnP0cLdirKWe1SuVOQLvhqZCTtA5Fv-KGwtSZKR-uvTnOL3HGZ72gYsbYMh7s_Z7C
Qe1foKMw5wnz4rjEJ7pCR73z7N_MnEf1fhiij7oSytAxb8bHs9ucLazDu15o1L6yw6_MtvkUJYL2h4QitmTD3KmB8Dz_tJVdcAJZKXRu9zu7tUzSDy0kpyZC
08UPbVTBfnBrnYPM2Z9STgkUdBMQM7NAr-tQzK0gNqDX3cnYzVghnKeaWeD4aHZHn2gA6h5GCqs5ijv7DqysiRhDhXULK6RcrOph2MmJAzbiBsQkUl92Z54W
bahwJQmee9WywyoS0l62GMbYopAE6prUAyFpXoz5DR6Do0R3SOOhVp9iEx4cfWME998E--HX1cV2jMLftiJgik2uLxnB_HbZOKYRsBumqreFi2QsXHchk3Rm
Qc8b8I9mkyaAhxnBXEyYriHq9WmJxbr8k7zpYdNqifhOKftMdAI6HGAwc-Grn9hOE1J8umOFyWkiy5HtJ3dqrSIQsE3TOjWC03mY7C2nE1EyNaYiYKLzVQLv
bLi2cjW6PFNRBOQSCgkiczZFPIwCO26yyZu5parisxAP39mJC0Ivi9XkOflBKmp0pBuQaH2VzCkYcjYwp2dNNenFdIpHrX9Y4_kvdACkFO6PRINMnE2176Vy
0IzpbYrZ4rkVl0ZHRrCI0-ejqFk8DJ5TwK0bq4Z2D6hi8jR4SBPeDZXPY2xXM_OJQsBQdniG8Qc50_R8izWsOfqLUODC5oq08FXR3W3VUqpVDuyrCPHx5Ekz
YtLWJMmTsNfd58BrLfqcjc7LJ3gMSAtpQcBhKQADe9R9_VPNgPgONZIJ0PplW13cVubN4rkFCq6DxcvlEdx2Rd0Fahjx5vjOdPaMHG_tXdpOnDPSkjO6Nari
Kw3jR-LkOkj25PfsbVk9DJ5jspVYQcARg97aEIkkqsfY6wd1dII_e7B7CgqcjbrsCSEdp2ulqL_isCUDGq4CWs45Y13xRtXzSRvk6fg_Ap2-IKyMEocBMSnY
5hEOnIncCOjPp68MivZ5B6OnnIncCOjPp68MivZ5B6OnYrdCOXQpcCLKQuiTrbZixx9OMkoqxcAR8HfKnIf4kuCXfKwC3irIIwnv2_hNs6WjmCsG35fYiUh7
OgbTrU0zzIssQYCSZlOM8qAXNDvQxIt62eb6UfCrzHPaBNKV7xcAwn7KFHT1nQ-Nv4D8LJ2EwFzQ8R9HNOkrV0YQAv4jDtbJ6-8d-BuGHLVZJfnVBn_RL7m4
tqDfR33XcMcJGcO5lZGHycJSwOppoXhmDSGzOJBk0br7_O1TleKCJJBL43-NoGnciWdX4bHhEwJBMKer6UeLlC5EgzTUfzKGGCF49rLpjjcYukFAnbuwZUeI
EkDJowgUewgg-6eF3WG000001FbRJx11jG000000000000000000000000000000002
}

