sprite $93H [96x96/16z] {
xPY7ijiw34GNYyLI-FyFVYynROsdPQIGTrfqt8iEs1lsyV3myF3myF10rIMKm7rqz7KATt7_uhZ4wv-yhH_4LQhxm1soksx-txZ1w85RL3Tkq9suHxTkPHSt
6Lq_wlSF-nz_fCgsIyH-FsMNCbCgMzph3xaolZvPM_rf0fpb8n6GkRdyismfKxB5xUMlAOq0mBAs-ububqy6ShiVaAqaSrRkBdya9kd497G6o6M_V4R22T_l
wLpqquJqLKGkdaf1NlIhPeYOSrIFe-VKHa6ES2xvmubwcO3H9cOOpenPK2tvwQ0PrhU0tJDdCkXOyK-93EJNzMm3D5-XkU8lGK8960sSL0Emvdt1_t4aq0Mz
xWcGdNW7rfe_NtS2BLX2bib2rooxRNwsC5mSwV96_rd6NM0bLGQBhJtbCmKIC0w8I840p_hDnVgLaKOwe1PEUcngdrC22nXDJERRsj6_OA4AwG2Ejo6F5a0p
riU7cSG4Px9xb8-vjWv23ffh_h0WOPA_vKDuKuHgVNu9l21nGanehlgHPo1z8kcZ3UwTtqkPAflxrv-L0FLPtagx_N8HaqXxi_zSGEkpV8wj_dH-DW0b1aBE
dNx85h-paflB9sHRBsmhiDC_eMRv99_zu-F_4rmvFra_pLc_OlInS7wr_pnDtNKtFIDn4Rfxu1xLjnYuIuw-p27y3QbB9F7lyV3myF0_
}

