sprite $AP_205H_Desktop [93x93/16z] {
xTa7RiGu38NXzzXv_mDlaPrcUBA89Mt_qL8_o3G7JVYdz7__n_imdsI_AXLpUNU6tnNP7PWfkeI0EE0EJtoEEQLh5zW6wO1qy3g8RCFZiWMmeJkaY4limjFO
AIMdRlTZ4pnCsk5zw2HkijRdk67e-ihGAJmuT25kaoayY_0ci05NP16s2nywjk3cW6_3Am5imfML-t0Wk0qlspWMBUx3ltnh4U7A3RX6LMPMbNCrxfKsK8bA
NOj7-SUFitGbxkNuY5co3fSAu8iUw_2uBgILhC9PZaiLgt0jWRg8Krn5O43aAjoA4FMGCACQS_ne4Uv5m2MGwg7XA_4XUOXRY8OQbk9ZvYfKYfA409uRjoLZ
tPudlgQbot2v79sPM8OZol2fA5c5NtMERnRYY4ezQCiohCLXMHKHMHM2rJYWdfdX0gp5x-D6N5htuJ3VXcjk70kpk74iMRe9bm2slL1M0djmzQ7lmQKShDY1
gnwwJU7s0kz3XyxWVaiBj6tezXn79sxoFlL4jE1fqOfBqW9l7Jga4u-JBk9pblIX4zfWjU9vrfTtcWPJm0XGgnqpQNTNtbNTxPYBrMVrKPy99glMtwecFifs
8QqDSx43kAw5dZyCp7KSprilZmC0NTDJuO5zoTlEZy5CqdcEuKly-F54qNfxn3mVIAOENXZ8_QlGphazF8TmITi182Uc7kTGkrs5m1d5QvmSqaqyoximqkfh
Zf5ryQbDdAb7_bQDCeoNFvgmxvhGV_30_c1bljlXsPiBQyUB7jnSJDn6P1C_AZjDY3zEDBhvxDgiAZCYtDr-IqTcvkuHMNNyZU6dqIAhghzhxBnW8f8YSfpu
J5M4n3-b__k_Nm4
}

