sprite $AP_205H_Desktop [96x96/16z] {
xTY5bYCx38JXaagILU__m4iUI0SMulR5V0k7SlvoUtZmsClBImmzC0BBg6_wBdt3zNmQ008Mi66uO2a5LfX4QuShV_phne5BZWL30GmvGWagu3YYnjBns_9p
m0qtMhPo-saQGCd1mZqfhlG3xmEFNxBIfxqDv9v-AES0zlJ97mEnhOzG0jZNHuZx-jaEttd-acDd7wcjvpVGTlPLmCw-jstjuu97LLVHjlIzkhkgkZiszACx
702CrMLdz-EY2NRRkNrsuGAxJkrRb-4u46VseucZQZkntmKSiNbUtpjWT90WZJ07kixhimco6EL551X0dTftW1KCLdbL1L1zRj_B6KKB5dXotvjWX0Kj0eJp
tFknBk38Eixhezfm5CqJ--p0WNNXn3wgYKlLFBLlnu7gm8dzEH26YJD_OdyETD6TKTt4sVrvx2aCE_g0EKa7iAL_otDltvGx-sR6dVsKxxsV4hVsaThOppPW
Oz-wRLy_4zQzh-zAM8zD_U8Su68_S5zg3c2nd_VhzZ4GAttJm3tTRmC3GuxdjOXhOy3U1-1gBA1aE52O6jODf60IiUBcDv0XM1ai0HYb15O7DEgkeVKyOAsV
C2oJyfi-7DMae7k9M6NgkMAuC4G0L6BLR53ZvlUsStlLFEdDJSpdQHdMc3HpE4hbs_zhPe6gczsUwyl7jtlNCwzc_G66ykxr02c-xpylti8ISUGjpfd6qoWv
PaNgKVccXgJn_eIra0zC73hgm6HIFPrFV39tllFZky304rmA_0vh9VvS_sOUptsLYJzuQggVEBvlUl4auVUL-ETzZGpIpV2GcPDPqf_tBNNGtMECciOOhGk3
U88nC-kGEkeUbHcESzWt_frzW_-0bvUl
}

