sprite $AP_205H_Desktop [446x446/16z] {
xC6n00000C2WV_x04wa200000000000000000000cBqxst9Lrw4mVEkfzt_VqzSPACM8bYZ5ichzS_VP10mVCctWoAWZLXpa4CIktmyx_B3hzyCEF_3g-S23
3xf-FlH6JXmxCqLV-pQASaBB1xq0xeQhPcaNw84NMDryKhQuuIjUOlUbvGTM4n-vMLotbUO_qtbywBbUyTxgbgjqQJ_J0o_g9wMRhmLw6_d0kw-qaC-w-S2B
zUBgiueenuVUlLMUpsgIrWFlEUdN1rQMXthecPJjF7SrZGHCDuikiOLiBpxmyfsdDVEX9odTURh_QjHZg_U6AlXiG_EYW1VptTU3pDgBZuxpNYhMirOzz19d
M4xLGo_LUUvj87c_Qjz93T23xz4Pbhqj38BUrIhQ-CZiM3tqbEg--lNGY_bqiXvwyPxdtWY-bDwjr00zzCxZIquMlNkg0Nhe1Nndwg4NxtaUguVU7n_tsRbw
w4LyTgOUUZ7VmUTQq8ixpnbww7c_0Nhe1PtdeNheXJUw7ws7dcwfPkYXv_m6wg5tupT03xtW3hAZzT2BJf3PM3tkZB0HUkX9ztmJzD0pcwk7dkSReeTU3nzw
wA7dCqqFFMcg7delYsYy7W_5bOtIGq_cCaiFFMco7dgQfeUU_HezxemOfeUUvvkcXvxDrKFFyscq7lUrJDD3poRheMSsMGyzcwo7datMGyy6wg5Ni8XwzJXJ
DbaFFKtKGs_wzJrgRxuUUXgdXruN7theeMUJzT1hFUP33pskx_raPEiQIJlrqBEdYycvkGYzm_kbzJx7wg6dzIUHpjD3R_rv3jD3JokLW_JGqyf6EaGFlVKa
Ea4FlVKqxNheQJsF6lJG2_4I0-xKGoysIGtSfuUUSfsXRlowzD2xeSj_gK4FlSYXdgzI3prvXEVis_NGKo2GsVxjraClABmw-tezz1JW9VLtwg6dm2xjjr4F
lOeBvchHGo_6o_DrwA4dUnnPo5UlXrxLVKQctNheAS0hvAlNGwyEpvTniHvwzHiz7rcR7deMfg2Iw_JGKosUsKOzzAmOpwnG3xszfUT7kKqFFLbvyUcZUkYL
bvw_shT93psPRIg-UZtqh2v1yPNheMULsQA7tlgCdWRheMU5UkZ5DQ81jOTUN7hodBhybvRJrcKukP6u4M_JGs-zVEIubl-_rs--KAb13ptlup5FrKFFRlIM
FmkgPthwa1vwUg-tNZ0JUgwgw_NGSvNbJb7AvFHCJi_CJEhKGyylugle1SDtcOxe63tqhb-xLANvpPyZ2VJKe8UUj_3xdg_tBxtzsNEN7dehrbloUlsrXvx7
UwktJgazzZdly9JMwwyzQazVUD_rJCjCNmFydtbfwOZQe_Qk3lf2kpzKS4EUK7lKdZk_zVNlePxrrHwrfzUFz9_uSosojQIBLFFn7hNt_3pdEkrS2tfwqTDJ
FNNhSOt1UzcqQmpesPjhjM_tEPklpd9jVUcRYzpGkjaxRRYsJkqjSz7BUFo8B__cegwxagYzYZJfSJUkFgGdzBYNUb_GqqAFtn2XfqILbE7DrUEtiuD_-Spl
rcsXbmdFZ41lRIYzGNeyAqcVrKDFhk_aANCjuHc1wAbsgxTNZsVZgX1F6_JGixhdKYinAlHu9ZnwKX7VMjrwl0kb26-N7deQzHuYzEhvt1YqKm-zN_d-FTvz
MOzNhuUUhH_uhG0FFTxvZ5x4brVG4UzRHy_MQvItMwOzUkZ55YlczlbW2z7BywtSm3rww7aH7yaFfNKRMQSUUcRhUSoQzT0prUAXLwzNpoThq4Eln6zN2z6h
zrD32z6hyLD32z6BKq3NfOTUxDVQGlJYIEi-KdyBqOiZLuVkmxFrqFDHGmlHeuNeLRHgc1vwlasJzT2J1kgXfz-WH-rfiXvw4dhe3GbwwFLdiXvwDbaFFPke
Xvu_phD9UkZTj6MO7dgQg8UUlZ9P3prDraDFa_NGauRfeUVzfkcXPxz43prfc1vwtWyzhX2XryGtJWyzcwo7datJGyytOvGUUhhJip5ww7c-MNhe-PPCFjU2
dWtKGq-JzT2JfkcXPtFrqFDym_JGytoQe8UUbngcXrx0XrwtNZpziVUreEVv1kcX5_2Dq4DF4-vhGI_ccwQ7dkURe8TUp8TUMg-_ynoeXvu6_6uTlRkpAKFk
Qq7l-pJl-Epeuptq55mSEb8FlO1lXXvw6dTV2tgceFhGo_PXX_89lOBQw-UpHD1hvJjE3xs0wkJxMj2JCdp7wQ6NvqClnjkoSFI4JsVeSSYW35-iHxIp-9Ja
Yzf7jkeb-JQqZ-ABnv_aStYDUXIVdl3P4QL7xRsCMWa-wzQZ-9JaUzmsyAGDQqQ6Jmrw59y_MdjUVU2bz5GvmeVLrrjwz9tNSIdDLzqk-FAZUyxd_Xkyb5uz
dxUAtvhHMddmwPBC9LSlZjuZlJ8_pnVhMGqUVfzwfqBqjg-2bGczGh_epMmVQGjyKiNetbdTJK9LxO1F-l7u6je0dy_ZyNLC7Bx-vF48Tl211zy3F88UVkW1
QDK13pxu-lNGisSPgGTU_0FrmbyDWMSVqTCbrRUuaO9bMyHdbU7kN1skHpOise5wwENhsnu7FDNXpIy-IYyU4Ne3bckqZjJheQUFwEaJUkXPcnvydrsgihbT
9oTQJjmv8chGqnmzzZZd7x2Zfu99aROT-HuzIgzUJ-XzM4yRzE2RioVHgCVbXP67VE1fm_Ga-3vpmyAiZjg7sZjn9uaKb5v_yM4NbzxG_HQsUZflFuceGy-s
t5LDwQ57nvdS6KAl0AzF3xvYFTkdb-V3JbQWLyId0ZxmOht-ueClrhFJz8ZwzC89P_p0YmRfANhuydZrHmnvcW8zz7msF0gxZ0yyqxVKoiMJXY_62uPA6DQD
2huVBfhUfrebzC1hyIle7y1huxCVye7NnrUnbl7oeIQ-WfQ2rwLNq5RmclYgNZ87Nfm6kG8-yEeD2q-iWRTLiESDdU35aHhVy0ZU_FVZWZTV3ppQpWAW-i2Z
-b8ppmmmxym2tGwN-_hnc0rMMlIi9V21Xnvyu34pkz8zl_0nk-WnFy_3keeUS_kNwh4w9iEyiZw2H-qnIwofx4HpPf1hV8zlN9yzAtzdxVam5nEYjva-0_Rh
ewSvlw66NYQ7jSpWsoAxOOhuxGXswDbOFVniQn243a2RQeUXQQ0TWe4Qb4vqlXPrkViXdQZjlTWhINRvyqtyKDuDCljdUt0i00000338tteC-wi300000000
00000000000W
}

