sprite $ALE [96x96/16z] {
xTS5kWDH24FX0CENc_qlkEukF2r_tKx71QzhhRNMMhCok227oem99soeLE8OfJGKSKfn_CxoZK8KSMZIGAMGS2X5L3B9_dw_-ztlVlUxducLoEqR2tNz81rB
IQmn8-hwkN3IZyhfGm-Uz1VA-i5C-d4_3MLzCe89iqtVjzF7I_gsZ0MNyIIPopWNa2pfmzPtPe0jxnomxPDUVqzql_lTxtxtl_7ysgG9XIYUlY5EKII753X6
bPfmAZZAfE5ZM0vTDZWLv8Tk8Dv5AUCAlh_Mk1ItLwFttDvmXFIbVI_etu7tv1VtpU_0BzLQQtC
}

