sprite $ALE [446x446/16z] {
xC6n00000C2WV_x04wa200000000000000000000000000000000000000000000000000000000003WTkvgCMuW1iFexVpl_y35aD9rGsDhrPwl3Iiq9siA
32tx4pc2dNHY1x3FJl3mjU697RqcFD7ZruKdUC5tnGc9JkAxo4xdw7NPyPkCn--_niCt6OzU9nw_oNZqGe_UTNZgrnCzUfcc9thqwD4JFNhqw8cUwD6ZHq_q
H8yUFNgYHuyUFT4JFNhqw8cUwD6ZHq_qkgCdUlJeqHCzqQD7ZvxeYHuzUlH4ZnuzUg8dUlJeqHCzqQD7ZvxeqQD7J_H4ZnuzUg8dUlJeqHEzzkY97Zrwz4HF
zEZHeoTweaUF7ZtHwu-Uw6KzbFUClU_DrUYTrpjNkH2_CKVlgl9lwD7BD3rwwqNqwD5hmLiPh4TlRT2xZenU7anIR6ReqLjLRmtKe_Vmo2WzUdcjbnbwz2f9
fkhHAuzkqAk5tYdbJxqCED-ZLqIAvApR7hton93R7htSqik0snwz0b8i9-ZHowfjqtiOVFntOVGouNoFtZg87ZrwfvPrKEvVZzuwR8mUlRpezSBdHs_e7Ssj
DyRexS1RnyzBuLeFtVW4ZkVgM9axDtfrO9LkpELmhkvdwUqxPidXCtFBg7RB_Csnq3lbfbVrrXWzUlMv8_JevI-crVTjFVkzXjtU6pk-lAcNjvGTStOHPzzS
7kReYHuzUlH4J_JeqQCdUg97ZnuzqQD7ZvxeYHuzUlH4J_JeqQCdUlJeqHCzqQD7ZvxeYHuzUlH4hprweaUF7ZtH4prwzEY9dkZHeqTFzEZHeoTweaUF7ZtH
4prwzEY97Zrwz4HFzEZHeoTweaUF7ZtHwu-UwD6ZHq_qH8yUFNgYfz1pqvkkHsyQdmqdFdhgN_3Wsr3RUkT2FsMt7huDjQrrqW38xYmzWhNxNkCqf8BNm2Tw
y2RomSC7hyCF7Zvu7NxiyB7hz6C745rDaYH9aYJ9TGzqFO3e0C9hzsE73zxvVF3mmUlWWuSFNWEVWWzUWvxIltRqPYyTlju_Uz7FHs_m5n4y7mWzVBF-n24z
IqPlm8hHeoTwzFP5pstlkkYvxT6ZrnyzUlJeqQD7J_IQeoTwRqUF7ZtHeqTFaYH9aYH9aYH9aYH9aYH9aYH9aYH9aYH9aYH9aYH9aYH9aYH9agJl
}

