sprite $ALE [93x93/16z] {
xTVLOGDH34JHUUBfl-3GZnbNOHqpNIy3_ginnXXZM5QF41nPnJwEGqcwIWSDqh1FIK4NPnsz3lGv6jAaeqzH9pxnYJzfuXDVHuzOQtN5fG8VIl31gsernTrh
7SQZRxAaX1t6qwmfhYcUHt7lYaTbrlgSoR9AWJI4eC8Tvl1qXqH7t02emXVi3TIWxu_Y_s0DdVZ49pxnYN_HUQYIYYx1EZdtJ-zHfmCQx6Cu9XuzRE6743rB
6WRGYfVarhoHhFF8sbWl1YwGOc0B9QzzM1kdIkAYHMwCbryKc-FNOGkDw_3rnXZZ5G
}

