sprite $AppMaker [93x93/16z] {
xTS5OWCn34JHaMN1tF_0XN2SBQki7wQNPS2FhkkwhkiwAGjhphfohdPfLxgGKyfoneAZhi4impL304i743bhyI0dG5AWPDRYHWuWc3l7Qd4CsTtle85YVEqM
ZxfonMjRSQtBFdcQr-EDg_b5feMu9fTIg_19fjj5dgJMu48wbeAK4joElvNva69NSfRWSNJoOdzfz5VXehSDd4igTbayjlz86Q_2TIjPyBNVZpS-3iaduEFY
i_-1DzuuL3u7nr81_cJrk8H-oLQnSREtuaCtmXPkfByHXzo6JTnv8kShyDVajACICR0lw2MuacFhlH8SGVgGYuQJZX9yfwy5gd1eBBJ-j1EknXLbsJMEO6aJ
bqcfRbYIkl3Vwxhk7W
}

