sprite $AppMaker [446x446/16z] {
xC6n00000C2WV_x04wa200000000000000000000000000000000000000000000000000000000001cxpwo6rPYA0eEE7hO_tv_pg6FrNOJX5nt2kLIPlhM
vNZYHh0JJ_3ujTbfD9v6uscqdfhmH4-TUAA73nwzkY4TqgjRqW4zUFGQeWUFdkWTY9x7Up5QpHwWnsujiKPwW1wyjKCMetOzUFj4oIFqw6KnUheUlAn6orc_
7hnyR1PwhqLFzEXbifvlBVGEvZidlTeOtQkd5SEe_rhmhKQhsHFrB6F8c6KC-1QpvMYkdbhqH4_qwD6Z9thqwD5hI_JeYPxeqQD7J_H4ZnuzUg8d_rBxbveU
FT6ZHu-Uw8aUFNhqH4_qwD6Z9thqwD4JFT7RZvxeYHuzUlbi0_J8hHgWXsxL03rsY-RgiKioG0_U8dhdoy46wy5B1kl1ImRhmKi6wy5B1kl1I-ZTXrUVYbuZ
tfcBlKEFth4BfdSSh_soz_NerPSsM0zU5Rq6l3Q-VJrwDLUFtkxF-XVEHA_hbP7_Zzx3NtfPrgn7xnNe3Rv6FNhv6htqwD7RvslMeqSlrvcEwz7BTRBpTse3
xttqSfqjn-_KDzQxpjUhLyjcwrrtTFfExU7DryjylRLVlRFUTKlf_nb4RpzwzEYruD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUlVFHeqUF7Zrw
zEZHkpxOy_JeNQ_qB3rwrsizIO_UzM8Ph4VlUZSzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7
ZnuzUlJeqQD7ZnuzUZLEZrxj2dJhqLj7ZnuzUlJeqQD7Zruru3NfqQjcFNhxjp_r13rw-z6ZHuyUFNhqyakpzEZDNq94pz9PHv7QYHuzUlJeqQD7ZnuzUlJe
qQD7ZnuzUlJeqQD7ZnuzUaaoKuzUVgzRZzvXYlbwzKvw-LkZzEZb7z7xeaBlXDvDV7VSgVmhUWqlFNelz20yUg-NnxnjqjkfxONNhvUvUlszlnwzlBiUlNed
FNerI8zUxU0rwD4x0Lxq3kXjy6tWdTEZburT2D2RnxV_yXwbHozpzV3bFZrwoLcyGNhuShCUlUJW1TCxpvU3UFJEyoKD5qblgznIpTMZL_GQ-EZngnghXw_c
wj6hiNhygiRgyQknUlYgfke1hA9tSsVfw9slJsw-dkZHeqTFzEZHeoTweaUF7ZtH4prwzEY97ZrwzF3H4xsDwDt4fnpGuxTHzoEUXaGFNWEVwC7hv1CzUFYI
7zkZ0m8000W6OFrRQm6-LTY1l0DzykxqoVCdRwZFdK9n5m00000000000000000000000000000001G
}

