sprite $AppMaker [446x446/16z] {
xC610000082W_QaNgG8000000000000000000000000000000000000000000000000000000000061sxIkteHW6eYWnO07tl-3qdb1fj6W1StuJrujN9Ff0
QXvvSMGEI2-OvouK1ccaaJjHcBInt8qSqiDpFmeS78zS6cWUY_cGKqWFFczId7peaROk5lpIA3glV96l3DADriUB_0jYVHZt8yrNw7gca3t8keuOtN_e4VA5
TTM3R4BHNq-8zOZr-h0U0S3YJrZyQROUmQASXsl4_PySyWdyyM4wM8yqwe6gl_p9wg_MCLQF5lDmhtUSaQzygXv5bXqqtqBzC9kfHvfredp7wjbDpDGZhnDf
redoFHsfHr7_5iNolSNGsoRg4HRr_Chh4NZipU1rZwo-vyJY-FAhkEUaVCiNnoMaB6j3zKYBGlUYBcJ5eJTLZ_a2ikfGvGkPgqVmV62enW_fMkzkcupM8wWP
KFpDJEi_6UTxdAtVidSVsehhC1Y5bH_9Mdx_1xwz-fO9nZB7mzxJLZij7tBAG7X1Zz0ZzD133pr23ptqqFDDKHJeROtGGu_G8_JGGmyzGe_Gkn5wkIigqDEk
wEIhr8GUUkYXH-YXXnvwX1wXXnvww15wX1vwwA57wBq_z0WzzD13Zz0ZzD13JvBxx6z9wBqhUKHcdoypMmYzD-IPVKdP7BsjAR8lB4FeRSkpBoxZ93tinjBH
gq_HYmhqgbFsiXfwjNclB8LUALvnGgyGhpoXjmylMxnGPXzhwDMaN7wIRMevyg5NKXlit5Oa7_mSlVfrCyeU5a9lUHgExUkktWHwouiHhuvFw5MENjOU4JNq
2WzPidglYbxTRAIgL-P0hsmqlFvjsD5RMZwnRihRl-Uw_G11RsLFR5cV_H_Ox0C1Uclo-wEd_d_ftXTfw2qixezUzl-htNDFeRUkTlzKklzBDoSNlPh6pJ-l
ftiJNgA7NdjHx-QcyrFrLDQrG2-iOB_ttUZfKPdgzVo59puShdVfKPlAzImcp_VErzEZEfNhcQBzUo7xdlNqg4-LUlEThtSzTbIZXvwsw5qbUkWzjgGAFVIk
nvxGGmyzzD133ptqq4CFFVJGGmyzzD133ptqq4CFFVJGGmyzzD2h3ptqq4CFFVJGGm-zwrvVH0-zyHKqT_uyfFVheJV_tUlwKdhewV5KxzT3R_wRlxwG7dfw
F9U-k1vwwA677dheeOSUUkYXXnvwwA677dheeOSUUkYXXnvwwA677dheeOSUUkYXXnvwwA677dheeOSUUkYXXnvwwA677dheeOSUUkYXXrxgE3tqV9hW_Nhe
MVHVIZjG3ptp_2ct0_JGc-X4FVJGGmyzzD2x3jRZBdDshXvtUBo-b1vwfWAyKZtqnjjIwzPlixFrk2SyUkYXXnvwwA6dQ2rqf1vwCNoH4_JG6xUT7wI7tcYG
wF4UO7T33ptqq4CFFVJGGmyzzD133ptqq4CFFVJGGmyzzD133ptqvEsdN0VgeHVPVodZ8_Hi3vwswAdrFygFqDCMlMkBNkj_AJz1ptQDNhsUzxyLdw2dJQDN
hvVzRwK-G6y3dso7dlhGH-YPol6sw4KVye_GiqkLTfUzIQ-Tg3VdLzI47RDtRlDwFhNVys8zzD9kTR8UUcrcjzTAxgwANdlssDzpveG1lPBYwJNDdpzcyM72
qLkKXWtxrFIbF_qGQUYjB9y_eD2l6jbajzB4rq3lwQCGsUtSfrRdBlHMvhtooH7ZwAMXLxLjkrj1Kry0lOaJEDL-_ZJqrgR-rxmIhpjw1QTyPVi-_Gql3Rtb
PQyQlyZXCwEtFFM_bovRa3p7QwBe5TJwKBQN0Rtb-4aDlJg-iHRJ_TldIw5NnbUU6tf5gPmlx5WzfiyDlSgYrvKoz6hpx4KrsQ5wZ5-wsPbw7BnacA6tASLQ
EvUXjpErp2Lo6GCTUZkIF5hcBxyd_sanqA6tEPdfXN_ia_K8FVJGGu_GGmyzz0WzGWyzzD0Zz0WzzD13Zz133ptqPEU6djkUI0LwpVP4tXVfARSldJHiypLw
yEs_cSpAEuyqhuxQN_5osHgyFufLY_3-A6N73Xz5rSk3wwDSTWoqFv8ToqTU_UBk-i0xRzz7pHRcE_qetTQcbdrB56ubUNba7z-FxS610000080WV-j1hfu0
000000000000000000000000000008
}

