sprite $BLE [93x93/16z] {
xTT7ZY0X38LXc_mexd_U4KyrwyOIxkX_RNsL0_9bHL4KHL4KHRdsargsqzfnsaX6Em5e9NzSQG2C-ZZV7-qOQh4Be9OzgHQycyOBXWMtdKO5r6MQ-U61r-I8
joSvuekw5qxT2wVkXw-PtF31VR-Bfvc9FqBzAgxFUh8GV_MBkFIrzV_ur9lugs_yjQ_YrB6UrxwCIrkCzdMSEcqFNFf-G5LyyB7nx87Jfkw1qwP-6wSzntew
zRiuRTqF4VMxE6tPEFLq4zUvRUAAw-yMXGhnRKETFXQJjXDEsmsVAauuRI-SjXTEsmal-gV_pyKL7oYsvROOQgQLPKUtu0eqEQrQ5_y5w5bFTYDre8eOzTDe
6qjjuAYUh3JJa-JN5qLH5Fq3
}

