sprite $BLE [96x96/16z] {
xTT9ZYmn28JX420IBEv_tJTqNC18fbVyQ-kBcYiJTstRjctRjcsRVN7LPu9-6dbT6BfPPfZAHMgHsHsGp0_NUQQWrPSnT9nbQlFfIlCyMaNlyMZt-NvfcFVN
rs6_TDWl7VPBX_tIORzqqZySUEwhq7Vdm6FVwWXzSE2nVwgEqCUfgjS-1-OUFpWmzlg30tEV7mxCVlvFZNv_EM0Oyxt-TMJ49y-14Pyy1zxxvBNA3mSU--HH
vU30Ov_yZ_ypCE0hw5jL-VlNHq6V_EZ_bsFE9p_fEqPznwZl6FKTexvZriVwm_UdBBhFDz7ACgJrS1oz8aDncGGVJIU9pF2h8ZC5xRwyxYFVJColCi7ljctR
jcr_0G
}

