sprite $BLE [93x93/16z] {
xC610000082W_QaNgG800000000000000000000000000000000000000000000000000000000000000000000009WTCp2XA0PX80G9SV-5_m1lWU-bju5S
ZTQ_HdC9rNhwUdFs7hPKhyx9NYMkRi99zZQnQjqjWKf_yaA8w-Gvoo7gQhmi2x-9Tu6dpml4vV9oXEhTq_iXzipe2ZFZx8TKolCSlHBrXQV2-IoDo_Gfe67n
zUUct8neWq1aUSFRqYOrcqk0CQEKPAUHTIeL9qz17wdIq7oc5ZaDYmkWHkAxV2KQF_doMQoPsJdqCykGWyNmu0pw3X6nxGrxBkYL1uXE488V0zKo68Q-KgEJ
HVJlx2lkShW8RE_7thsao7B6G1GMIHBOoR__zNfyHR-x3qtudfXLJJz2zHJAzCIN1lNwy-__NU_wHxskgAUUUkgffvvwwgcdddhggQUUUkgffvvwwgcdddhg
gQUUUkgfTnVhgVUaM4-zas8zzKwAzTGxATPJxwHOJxsJOZtrJehrr3ifrbFlf5XFlPDYFVLEYlNKEodMK--aM4-zas8zzKwAzTGxATPJxwHOJxsJOZtrJehr
r3ifrbFlf5XFlPDYFVLEYlNKEodMK--aM4-zas8zzKwAzTGxATPJxwH7Jxq7u-FrrBj2yV5wwiq0VEhzGF8XFPvFlS_doia7z00-zR0zhwq7yAc7BGfjFPnF
lSydBoYyg0VmgOUjAcmzW4yzxB_kMm_bK-_pkR8KFg9t0Npg0V-sNNfS-zJxVExd7OMb1_Afz_daHRxtzUOvAy-btYVqGBxtzUuVw9vw9D_M0_3KG_bUrhkV
7y1J3-NRUa3prCFujXw0fnx6j_M0iQaUnhVrWEQfX_5jFG1FFOnlwm5ZKpsER-a1pLCFv5jw09vw8DyVUi3OL8_a--EP701FFOXl1y1J3-33yTJZ-7WyzJW-
7ayzZe_7Ku_Zu_7K0_bmFFL8FXfFFPGFnbEFvMFnr8FvK3prQ3uIJpsS3yHJZ-VZyDJZ-JWyzV3SJwsUUdVlv5Jl1jzogiStZ-DJZyVZ-DJ3noR8fnxSF9HF
FHWFvLEF7PiidtfaysW-zKWycayzS6pYVEfnpUFvrEFmU3xrqB79ywd7Do_FUW3mgSVWxUrBW4yzR6pkpMU0JpskUKiFu5CFmzjw09zwsDZSUW2VUbZpjXx0
fnw6j_K0FlMmiRdr03xriEPjFO1FFGnlwm5ywc5ZS-i1VEfXpTjw09zw05x3DGtrhjDxoKQzk_-Ab7U8ji7BUZ2UUf_FzKlN4zNpSgbwrzDxDLYzkVxQYzrU
otyolwgdtlKil1VrWEQfzoF9lAy7uAc7PUjnUBoUUXU6n-kfznHVqr1lvydKwgcNgTLJBrEhfrwcLa-zJAsUUfbMFVMUJAsUUfbQFVKojNhgPMhrrClKwgcN
QTLJxydKwgcNgTLJBrEhfrwcLa-zJAsUUfbQFVKojNhgPMhrrClKwgcNgTLJBrEhfrwcLa-zJAsUUfbQFVKojNhgPMhrrClKwgcNwTLJRzHJJptrr5DFFVNK
KqyzzTHJJptrr5FlFtRhnCOI60O1A48MWluRNXtpxmRM9Ay3ouRaVwJsxKsEs9wnrzrUwhT7jD7YuUvvJlktnStROxeVFbPV9zrTdSgJkiSRz3ddE5tzh9le
GpU7pmTzobmSlGmQAIyglaoYKjxm7kRY6StItWnACMzKkZoXbIh7f3yxfPOBrpTVG_MQl1FhHZAQAH-cRI2YclD1KzIQYT2DpWUBDRkBq6xopKFiG-MRq4_v
9MasaPmZbmSebKGSGKuVuHJqNTvYr5tUPd9wc5Zgni_2WSRthxdPo3TtYr7oujKDJaTAApT7F5opoDtRl_RWG0O0001WaB_rFRvg2G000000000000000000
00000000000000000000000008
}

