sprite $BlueDotKit [446x446/16z] {
xC6n00000C2WV_x04wa2000000000000000000000000000000000000000000000000000000000000002OlVjGRXp7eZ2yGHNkV-_xl-w62QWsrBPX2eS2
mNDs9qVLDpz8krhYTelhZ6wskvIUri_bsS_XwO_F2Dwwa9MtFzyMfqZyVzoFRuVN4LVTBXSC3inyyVOpXvTVI21w2VwFTjplcY_25mpkgCSkUc6z8rlWWc6z
EyPdlU32UDOxUTQpNj2jegYb6QqN4GNrpTOpj5ubr4y65GlCUW7KaK766sUz2Egr4M-PzG9gnaZhwJTCHx-005W1q7gHVEwMMTqo8CXC-DoGifvoNzB14zgp
NXky2T3jVI8tgDS6d7g2MYzubYFhwsNJ6m34UffHFANI9pVUNXle0Qt7ytdPwCRQUvUVzQ2ZezgEjzS6EZ_hFPsORQ-sroRoirxNNJMy0-qD1qXQRy9owEkw
yVR6_Qptweg18_Frzjec-bdlWntLfcdlkR-otl4zdPdozde_h3SbFAhKxRMzwcUz-cW79MXlf3-izqfu40ZQa_5PZshBp92qDtvyOhs3uMLcYjeRxm_h7SGJ
jZVELzOR79sTihtnupEjDx3gy0JjwKvFw_qzo9IrDxvnFkjruKdQEvwVzGxWgTiRpyzw8tYGAMXFo6Szkl04xKakVjRhyHPfh-rhFkjLXoTeJy5dlHvFrDwa
qnFh3HoRWlO4VDRhofEqDvClhJTGdg2zENpM-m9FqPw0ptezdgmz0P_rEZnTUn8-wrM79sflDX_HPhs6fsfFmMSzEZnvUzE-wuBrEZnXU_Fhsq1FWATfJr3V
tVKwF65xYlYujrwrGEJjQVZkh4TBJz-UXk_6UdJbITiJyTrNhojFr9vMZmtq11SzONjwlltrwF34xSduxgZNoYClrbvRY--6UdHuwlQ4VFVJoouzVNkwi_D-
UXsUlZqX7tVJe-6jtPu-FhsU_ei5VNjIlWtq1Ed9sjFVkEpVNbwzlSPt9xtgqfEtXqeFLF49z0JdfhuzW4ZHqCI7G4zoRkhrbF6bBZvUcZezjLvRWD2l_LFM
ubEdTveU0H1mZVYOaHxYzEHwFH-XcQ0zWPugFRrU4kWckV8Xq1Ea9zLh8uH-alWGw6dIq-jLwc-Yvxb5m99wsTAJw_NBBEs2XQOyE5EeT_wo_XZRwxNqb7gP
oQzhrTqeFcLwGZs0wWS81PDsSLrcmlHaUb2VZxpHqIbCJwANoVUuAOqlM6Qwz2HwutKAjjxHAS3JwL73GtXq1gjCTt3ErilycGYfYY-sRuzZUbDheZHZUxqy
fZTNWjmyFj71oMGzwj18YLvkgrSAFUheICLzo-PwELFl9G04yH6Rwj7IcwRtOZtalXS-GNfpzJAhLk5hIyPclHd1p1wnfHxrntAQ7ZLXvEpxbftrEAudcEJm
t5Al9klzbZFYxOSdiQzUpTBZMUxnUFppdu_7uuU2ESrjUxsSevTKj__BjVq8aDpnQmRDPKzptOjcTuHlhbxkg3UplJwzQ6njZubylcjfU3Fqdl5UupjHpthv
rR7P5iBurhzjKLpsvkXH7zRmkjNuyhIlrwttzRdPzhZ9bK-lLnFqHjDhUXo8J_kDQklbG7flklBHFcDaAxsiFvOJz0RIaznsZkkngLvDq4kD7ZLlk-anJuzw
Yvxro7NrAlLwMAz4Ubn9pthAjpFifLVJxZcHwUNvDvtMYrbwJ6ZFUWCdvyolrjjGjsUz_C65xr7pzDmU-ReUzRpZwRt_RNpMUyZkEFNlNxTUFGHuWlQiLpNA
5ulfMM-Sxn5r5JthrUFnmUxGiOdskcSzwhF5uz7i3eR76zgpNjlZZpMw9VMiDpxhMS_NFRTdlRoedlNqsrBFUhxkkJthOJth_NZMgrfPJ_yZ8wnN5zQpNkeK
zJ-knUtfz5BOddyijNpNRSzwwD_7OBr4fgV_s06tHyccRy_ldLMcfzVp-zP5qzzo-ZCZKX8VMZthjN6odZzjXubwGZozdlLOMo_Oy-IiHVKuzJij_dpE9SVc
dyzPK_GohtpLy-TIJ-NJVowrszFbSlPdmljv3AbBJw_dPw6a3az_o-dd4B7eSuZIpm0Rq4kMnAlOKY-dFtyF6Px-MzH-UcAXmzC_DjZFdUKiF3ztDkS_ypdH
uUaFJZzldPFm_Bnr17h7ywEcZhtrMdn7zQRoGKdqOlFsYgDw4_tOzHEfsqB5Tr1l7X-KQCc-UjdYEwGtoo-5Rs3OM2y4Ucq83atP7QT-8Jiw9Ne5WZDJTC-Y
N-ZY4-WD7A2GbNMFz0XTV0gz1eY-kdxSGg_59z5huu_z-kjvtaT5xAzNIhsF_uW_Vgt7s__W98H79rAzjgPsk_G8oKxLEnMFfHRI-0Hw_cWvkLxiffTBfaTe
uzkcFMf5lf36LqAzzPztgL-8unFeEJrzUseztt02eOvl1xsiFnTtqMlrdQcNYMIISpC4UiBuz7f4AF5YxWY1dkRIfzTB0cbwHApc5xhbkNfgl8hv4xGdE3lL
UWqlGeOdkU5OM2-hySdrCW22d3xQkKamw_yHCSClGXzVwVMIaE6f3avUZo-aQ_79srELbzNIq_25G4zmTchR2u3KfHUABQuNdAWNN0qFWPxaxDJgfK1FTcxg
zVHy-lRqwUslHylZUkrHDzThyPM-FKHuXFMuN7ioFBsUda_VdlxOt5-lNVg4xGdrSWCzGNtQzlGNlVtrUZvjUreywsdRa-1PBxBnATlJtB5OBsXymlO4UDRh
-7JjpSPBwptnwTeJu5clvvErDnUlmde3Tvw2zYRW4TORu1Eq9yIpNg5fJubdlQWsINioFElr-SdQq-DPhrYjFNeywpsFZc-LzgWEptfVyx5GUrHRM6-4hn2q
fyLpUnsVe3q1dlNQiXeVWlQaTjQBgZO4xUdkLwpNN_pUsnxrZ6UzSRxYVUtHdPhMEt1w2jgJXcUzAAeDJNlZU1dMU-7q5BId2yzwVNudjqTrUDPxARywiRsF
_wYmtXI_FAKzPeLdlQ0wFq5xAZlhHNtqqxO77zcjDxi_HEtrTaHORpfVGGhQW-hihAVnAwQtrzbLM4_fHqvh3qhRdVK2wXXWqnkWatLdlTy1ljWUTPATzO2W
-W5ve3s0waS8PxqMu9FWZze3wcbaY6SzYFmz5UH0Uvz0GuL-rki1-z7sXsP2G437zfOJqthT2Vhb6FkJujnPhnKulgKEJEi14JKWk5vprciBuCTo6U-UzTfY
c12oOg5PhoqY-2qZB9IRzSONLvprh6SzwrdFUjQpdlMiPpthMSzwrhEUzQndFUjP3oxEPptSdjjxuoi98kAQXg_ZSVqN4bVSBktnuYkvxhavGuyhskaF4VrW
JdoyQrDUIOFZ2fk6Hx375O1jBthhNpC8k1qV05la1zpDZscBu6sBcTSJBh48_jiU70W000002FAt7kJg1m0000000000000000000000000000008
}

