sprite $BlueDotKit [93x93/16z] {
xC610000082W_QaNgG8000000000000000000000000000000000000000000000000000000000000009YzUr5I7SV101ohVbKKsU__l3lqKOs6fdiF43bn
ZFwzpgqB-29P3WsUB-KoIQllmRgkSf5_CwNNdPriLugmrr-6jwjbZU8ZFZCe0NYotR9U8nB8HwjSlOlWwyU0oZL2j7xn1U2js_aHMdP5x6TS9cMrHpp5WY5O
TWHNmpE-DQRocCuBLgk-VLSWBzSAoRR9iYzao-UfOTbv7QwcVxdYAykkUFizdOzsFOkrB1SBxzOZiHznSjvP158FGomOTXMbtXjwj0oGDtf0wl58UaYzrxAc
th59lG80p1wHfWe08sEb7W6YglMVjE-f_qI_44jPHYh4r2C2YxOdKqK06a4mzGgOjRPNeyAWr3jNZyNataYjAZYd15ElWFLN6BtxLsk_4ylnJJJrmD9-YAeA
C-CkykTFikgFt2f7zj3K8zRwE5EA000zvgO78i8jB5hhOwqU0vXw17qeE65N-rNF0nPvy9VkWAdtiDYvt9Dw5e3b7h3szKizt5TCLOQnlAXdW91Qxzelbv9w
NVI-jKmNUK_FWczhg23UB_LKz5lL4UtKim3tFrgGUg6H-rc_MiECq3D0hNT-9VN2KchpL9E8qhFS5w0WzO82ULZjWlKULq1bIhs0qDrhQWh1UXP0gjSuIkhj
377rION9qa7Fyby_tUUNUj2xkkkkTrz_LIZrtawHkuM8-kkPN_FoIxttKj0yUeoUXNNVz9bwv8KdgiVg4RZkc5vIprUy2iZ1UlVB7vVKUoc5gqyEHCVgMQ3r
dTKlzI0-Dj0fUlVjitBglTurgu3EqoF07qX9lUV2TuLtafxbt_9JIhqdGjmi0ZfT3_p2ufTwHNpKf5FrB91cGUezjUHPuPslP-NtrEANUgYETxhUuwqNAQdt
11w31j8Z_9KlzGhkxaWFfETl70bIx-Vykxw01jAp-32LUZz5V9Ste1v9_NNda7f5V5uPKezGVwk-r6F7wwiNpvTwudYZwZcVKkhzDt2ySVMSJqhgUL0ThwjU
F5_gmV7wwiNpfHwQuuskvtofznKInnjVp_Xiy4mzTRmhw17Qds19lS9-X-KAUdxNHP5wy7kRLz4ZjWlkm_Lyt0HTI8_41yzFrYis0Z1TIW-sLlC7w_cjQQ4h
wJbVnIVh-SHoCJrYcrpAv-h1NWAYo-aH-zBteNhMVd15FLZJvq_LyqNlWdg-z7sc7cpHeslgaVLz-KWzKfjOhgf7tZi_JuzzqRkedbr_3P-dHxReNLaFlctu
BBtYy-PrzSZw1pvDZwtfqANre5PydwLdIuRGjVK8rly_ISz7bclh-To9Jz8hrKhlydhMHAHyZbxnhTuHUgkgzj83QfV1fQp3wi57bYFqM5LNibnaS84TjJkU
NX7hcmVfmVxnFa6FbQ-87VaxdXwisHoZPwrJkU_WKcc92zbHwIFgUUdrr_FYK-daXnfRV8HLjd-2PJmzN_MEqpC-bJxverSbBDijwpAYNl6D-Z5wnjSnxIkw
1KPu6L8Fjb4_L8-mIc-z5eYtqZAYdgzwX-bPm2ozqhuYCR4pLOVK8niu0_NEZqJVxHnLZwtqfj8Z6pkdrsjVuUvwi3FpSSj75f_fnSyiIXtr06RHRoUiSrT2
s_CfJQvdBQQR7bXKsqzHaOw0QgrpOZqllKvwa5hRxwcLUm7QSbwcrXDRzNheWRNzDLM0ZlUgQMOzKjiknEj1Qdikmltc5fvP3xPTYDTZRK-d2deLNoqJwza5
6grdTkVwsTmohvvDd1Ii1wdjrIWwpItpwi5ABrOFsjv8vRctVAONtZWHgyTMUAUNdqrai-eLs-o5wedXdSvdhPDdrRF66QedRKSgugTEAPFgMUECr9EsBuX_
eu7cr2ksC8Jf6TumrMTNvvnwgBPLZzA3uGt3Px-NEwMUBNjnUeOt3fzQwvnHpnfBc1wt7x9j9qwUzWodrBChCqgFwuCSW580l2QemLCdJwXdkps9qeEs-m35
yn8W1zzkAHFgmHfda9vyhxjYUOCFePydKffGZwrnnkZnDxpo49omz8dTB9jFhzrIW_HG7_3sy4caNfjGpvQz83tvlMrwjiEt3JQspATdorw0tcFfeVoSu-TE
kzKvdHv7wkbV-gO5Xy-TzXxVT7gse8VeVLF1htfwyCfd7NrIFGtGUwhqBDlHkmQUKuziAnIWz_kgT_xOQMFBd7eIeiUjWrv5uDWocnvgc1wqXrxZE3qji-dP
uXAXrxherS2nvLUzr9DEUZX0B_Lg7xqcSNgOJCysGW5wQ2FhuV_gfHwtRzc2z1JTzL9FNz3RuduzCFKqGg-sxy7UqhDmsDlhF9dUdoSLe8VQ7X9JUat2tbwN
oVHQJpq4b5wedgRUpthSVWXsubbwrrxgINkMRmlHwrzxgVV8XwrTfVPIhm5tTcXl17rhB_MWxPTiWDjjxPrmb9wKvVcadWK0ZEvKFVrDB_KYahMNUbbxMNiv
SpvcgfapzNA_btfPUrbxUPSwFdf2xUKxH56HhBrVykT9ZQtN_xtr_BsMVdhzVwybzRXrYlRNIpqSFhIa7iVzBlN8Gmln4thvEOQ0dF4vXjH3wftp-JqEqQlZ
DaxwstTTvMTdfVN86P-TpS-jzvyuytFh9V8x8theCHqpSkOtVl31M_NylXOE-BQTZiN7aITgXEbD-ZrbnsuNydlAx8a5wSc00wSFBVFfBN5wyMEd11zcCv-U
H7wxAicXVJE_6vTZlvTQZnnPydkfAVWxuUk16_NyJlYbMkkCqICPhcyIdhvFbcUXI3Uy_dTQyXmYQ8i8dtCEKPu1fcFXKPtu331xcm41Uc5ybUSykZHUhqZ0
wOd1V4pddPwOvyv2ny53iyOvfvxj-2BrZAz_sympdvVQuRnrI0tOAiHDd9XMpwxEA3qBZt5OFYO_BTzEagexzCAwPsN7YxtHCgtUOiqbJi_2zKKxAxpuYPCd
rhFhCroF8ESMdf-LFwsURzWZzIpG-goTaAN7n3cnNh7s4gjdOQbFqAc0UiJcwNdrl7LsqID0z2zumbtiVAi-jLwnIpHUpmAfzPUgg_f05t-NR6ezs_9f5pqB
M5Jl2LL5kj7vk-frThtIle9EUXO0OCXN60pqbFEPHShaUlOEkuJgdH-rnZcx7gfj6cRIOvjPfjShQfk6YVJWsuN9zMnkgOZNozBhhsUR1fv7pzvTu6LgFGki
-ARHizAZ-VNydGQPHizMycL-FIy-nIHwjf3JX-ZPnSfpwA5QwNs8dXLVmnHwOWFdn-ZPsAd7we6xfBPR194fu-fvyV61UYoYFTB-P0kDS1bORx5sWwFqO7Iz
z7GBZc1WFRAbFaJlVBosXKSmh9xVB-kkvtYoCeDZ_wFsD4B3g_4DgsV5fpX2RxtXhQ3mSAVT0kJ6LmRLyy553j23TCA3zhb7PdmOLyy6buh-UgogWcvRlOOb
FjYsRHrNptjdTprHrHvutFhzydkvlVPbM3tVz1sX9ntxPkcYnuFh5HlO-A9wrlgnTCdWUdx335VKyxxvcNe-TrvHpnvxfO_LAs9yrzE3Uj_yI3r_fw_nvVGC
ZvUFrVDjGyMrz23MDCf7wosmoULQUjpy9ildwldIfxYG7bTVz3vOptTzJN0PFJZUP-lvqjVuAdg6rxYatjtWUGKzg6_JKyysxSOtk9xZwVALr2ismbKUNi_n
AFM-xHiQTzQBnqizhxx6lVNYyL9lAUfye-evNiMIUdTyudnzzUBnKcyXv-kh5u-NUhxjgz9RBnulzRnvAWRKu_epNkfPoFb6qmCRdc99lRzi71HZwK4SB_N-
kcrlZ87q8Es9VLxg5MuMmJ1wg4_XfTvI_AN247e-hpIX9VMUt3cqoXX03_y-75cMr7j-zAo2q_NuNpmigVTC2dltF5SFuezaIRqd0sqMmNbwWDcrAcL9lQT3
Vj7pMNfUU9NBadelXBXPgk0KFQ__IcL9lNUxP-LZzSpk_S9BFIi_oy5waDfsZIkfPpjtou5wO6rjvmuzzMplO14SemUkRMVXfPu5tiEgeBEUrLtKYfTw2y7u
pA-ddjbPXCgIUf7jimdGJGzSMrpJJ3qBQlCeeuSU87SpqhAaNb147uxG2zPZTRjMcPQufDwswTtBMnbHUbPs7WqVLb9l-_OQLs54w86ji2tQfUvIRrd0xRzH
PUpKOx6IjaWlkzIxXRNU2me3x-W1-FwpQjSvC_LkiRdUKqtm1Js0hGqVLdQfPo78uvcoAendzC0iMetEmw2bTrBFuXE-fxPQHGGUgxClFG0iehKzfifXKsRg
MRpvFKPLz6R6R2S8rz__LW6M8vDw5e81lXjbq4bbbtecgFLrmrgLSIPSwbaARClzP5HbZ24bzIpbYr3gt-1401giMwQU1m14FN-c5WP0vJIrrDlpDDQoN2of
btgfbtgfbtgfbtgfbtgfbtgfbtgfbtgfbtgfbtgfnoFfKUgz5jWbVtRAJMzN2n7wJBrrEJdsE6JV2u6BuP7iFYwVP83dRQTNynxywnNV6b0uwmZFk_2sypgK
g_6LhmiE0VMx2TEfJsJThFHs5TycA5V1etKBMRDekqLMnZdXTPMlHx1t1BXbNN65s5EMW8iDifsUW86VjwjbfQ0gFZl2NQx2-V5iuJap4dGLibp9hYnn8PoM
_xK_1mG00100WFnVxGLG3ugkHcFv8m000000000000000000000000000000W0G
}

