sprite $BlueDotKit [96x96/16z] {
xTW54kGw38HXkor5ggw-_tKVBDjXMCvVDFWDJsoLlxMtjxUtjxUtjxfUwPlYI2XTCQsNjUDREH2oE-jMrcjJzqoEyEFD9fJrwYSVvX71y5OVzwkdH6OcIOc1
9_sMOdZ3_oNGB2ZwKxv9QVXSuaCj97_2hoasOF3_ByHsspVH4ui-MYfk-g60hVc0A-iTF-JOyc5alUw73Di-6bdF-2E_vwEH5tsJOzz7Krpogm97VBZiYf_4
CH-XUjutsRBVC8jHndBFPsBHdoQR5Mheysd7DxLb7pxD8wS-Api-4pFV8ac6OvQh3Etua8r-ItsAZZ7vET-9mNTzKs0eyvpF67nNLw3FTSwNztwJvBMQFkVe
KplZGwttymF_xGEWZtx6DwBpcoJKMcfTUuSop_W--F7Hhz_uYQxW6J-ozrDIr5AhwqjF-fIaQ2sqvljjVmnTyPrzvytFTupeYbk-gUlsznFgVL1Z3LsCCtwH
zRxjF7t8xls_XReIVQPooWyEFcABH_3sySMv_lSF-Zc_C4OVyAGa1cQvwadVrJf_kynoqY-Cuxu9ftrNM_QFB4yct_KBy-ZwAeGwPB7hGtviVMZoI-jpbnrQ
dpClxY-IxO1Frej-8TkkJ-7w_ewqRRzr_6c_f7pBDnBtzjUXNFT3MU_E1q1nsNVAdvXlX1XptwcepyndmgdqzjLldbBWmVbI2uhCY60cfVJwz7oiMaHcAiFn
z7nilEFVvjjKosgJZUVsGvGkY_NymdnugkMdzlRszlOl
}

