sprite $NavKit [446x446/16z] {
xC410G0020AWgl-VTGWm1G00000000000000000000000000000000000000000000000000000000000B3VOR--aYI6GI20qjj8eFiVU7AEU0TLERr_noQK
89Ep8lsi4FBM2jIQJqd8lu353xu6k6BrreafPBX3Tay8UR8oRnqPP20KVuDoRmLhdL46eRzN90hZ9ZbGsrxLBhpjE5B2EoYG06YrSQkK3Dfs390UWCFjAtB2
Eu1yfTx6po2_yoytIgaE9eGN7vwrJKB25kVXDhtNQaqAxw24mdCRiwJuDF1l4-f3Ok0H_DxihXWrMihmjC1SIvZDa93Y8P3tyFHRnebjHnFIa_xfCMjk7fGl
hMUKyQk7AXjzUXfEpv_fZZz1R9YC_vpD-QJ7f-Zaw2_SV8T_icNlFdJTLe8O39Cpg_R-3tnh71WUO8ysQ4EPHBirxSilhomZvo0KDfwbjttO1Nxlix_9xm0P
lIm7HcKzbl3U5ZUFdNdfw9rFqijFl0dVDjFRzVJqzRRvjN7SkdIE1krPRm3J-DYhFUkTxuiV_dtsRSzw0tMZwBLfpthyII-Adi2Pq-sjw8sUxRaz2BVdzePm
UpvpZjRj-NvlhYTplsUzuVTQ_3wdg9x-CuQOFRdDRkrPRojyfRpNwFQwFriVyR8RzTcwpvpjFzSoHaICCVbSIuFxFUkjVgQiJtlMM_yyPvFshBSUNw9BUzPR
ZuzesPxrk91Uj_QiXrn8hrjxrkD2UWtQizvYV42JzgotVd0X6hTdlNby6pgtPxrvV4Jhzgp7QNgTsxFUF3wYTNlMc_z9LvtRizxyu0AqRyzws2RfTMtFUlE3
oyRExLbl7bz2eZthSNAtqBqzwo6h7Y7IdlKuIQzxUzQhyH4oxLaFMqbFfpthPKbFepthrVWsIBLdFHOyXVQiLw-T2P7sh5VZswZIdlLgV0cvzgp7hRpgDM_F
UZK-Gh0zws4hwUcqPpsMz7JQinwsafvEUzRZUGAYxLaFcT1ipthpwRTdFRTNv_Qiv_Qiv_RSdlNSdlNSdlNSdjkpdjkpdjkp7a-XhplxUBtyTujVIVdKqDlr
lshmV7bS_-pSkVOJ6cYvUfMu-62zFA__jy0tBetuU4mldFfwFA_NZhN_wKm9l3FbzUO_mTV6Oh3xQ0p87CSrJKzVRx_UDvQ-ltzsDbwveAZgpH7-j3w5xNok
NbxNd_Fj_UsE11whnzBFqacIOpyRxnW9F5UFnrLt9Zm5lRtQ2RpzRBq9diHjkFMoi8dKPxtvYNz7ircldbWq-Qmtnsl-xDLwu_fX0ordlOedSDjdlRNtA7lo
MOy5JwO-w_6uxereD-lj7uq9tRLRRtmGlVtzE1lpMQ_YdSphzvYj-QoNn-VHv5qFUJNcizvHRWlUzO3HzwxTUdjvF_D3ho-VzNX-u5Kz3AcdVIJZrqW-MsyK
cA9N-BApNKI-BO9yiDvUyQeU3urB9nbP5kHtw0rKlSBNL-zbL_sUgZUAIj4hV6nkLqS-_jHoiEeHbUz0oqLE5i_KmtZ7gtgL-Ko1yig2ZzJ3E5zuKptaKV0q
oflpwRzB_SyI-44Fp356KWElBfwcLrVr9CQyCLfF1w-ErfCviTG5hIUHNlopBBDUmqMXmtyhW66zzkdXRIK-wxLEBwR_ihUUzUQqj5xd4sVCRQtN-cKFPQ6Y
PxqGrhCUK6SzbPSzO1vVq7fTLd4cxLblChTdFRVdCsU3KulrVCVWk_MqtcH-fynwViRWvtj5A5IUxrclyaLQJuAl-aMar2SZh3SVhQVBHrXFzWETOJtX-0Zh
zToT-60ztVXeFTtu0jRJFRZGUhhNpe2kdlLeFLq-mdg21nVhwST7VANUiVTSBiKNtwNNVpiNuYEirsi7RlC5hDTjUVkMdTPhj_rkV049FUiXieuYUjRZ93th
DTh0lVZuPNhS1V0EubPyn9VfWKTxl3DlVZRt-_J0_UozdJSVz17AUjytblIi9xGewLbFChw0zNJZe_NanXTVM4zmBEbPJsZbLSzwSl7HUfgBWcSzgVZ2UiBn
4TPJ7SDwmYF-Rky-LWK8OG2AJeYe-VyFVhsj7n8Gpi7jr3jrfNgerqOzrEkd7kgffvvwjMj_3cEDlApUN-oP5zTZZslgxR-e3-DOlKP4pe-0UMSzyZtVkhCU
4VLcN5gFKLNpqdh4hbfnPprYLLLUMezvSJs6UZ_KGptKwwGUwgcdddgeXthggQSUwg7U3_LG3_MQgOTwwgcd7kgXddhggOTwgAUUUkgXddhggOTwgAUUUkgX
7kgffvvwgAUUUkgX7kgffvvwg8Twwgcd7kgffvvwg8Twwgcd7kgXddhggOTwwgcdNZptCdDfFdSoQt3MpshwCCwSzfzvsniH-z1PdrMrysb4hghQSUhzMIkZ
2sFNiQ-Dh0-h2VLXF6TajMF4kP-FNMqu_g6HSxLXZdZEYZOy_mK0000000000000000000000000000000000000hm
}

