sprite $NavKit [446x446/16z] {
xC4n0G0020EWKxL_u2q8y0K000000000000000000000000000000000000000000000000000000000001msnTspWF7TIK6We9aWEo-_tr_3bfnlRJy4blg
GdfnKw5cDC5cWudy_WJV9v5xyFI36Vmu8eAd2MG5PCNW1vFntZZG-pE17yyvVNXrB3Q9dq3oTR9oFh_0S69kUPMtmdjV7mJ8wzaBP0S632TJ_0qRA90z40sl
4YBsykoazxu-217JxUKPUyYNQAO28IIcFU1xoaiCcFD6J7sZx6LBhmzQNDlUum-oW77ZfkrLTSlVh5aObfxj5NVhyX_7_Z3CdksXXBTZ5MdFxLLvLT-iHqxR
ouyiHnw3sxCzbFI-YW_ozlB2zjQba1-OPC_j1Gxf5HvpxRczrjxgzcplb-3s5W5xRaz_tlCpfv8zjnVdLWmOlDVYzXvDUjBjUP_JyzxSCuOwTlgCGSLUrRSE
FTzpU_tnxFh8uVRS7YEBlyUwhe_YBa6tftkdB5bnU_htEJ4TjyUOPy_jCKwav_QcsIFo1MAaFRV74-aDiEVspiSNT7j3xKLsa4FjkRq-Fiorv_OOmlRS7gdw
edMtru-TklRS7ZZLdjlhu-DKUswlhm_ZxRczH3uXvjjpUu4cFRSdQ8y2zjmU0xBst1u9tVTsT7iaTEsvFRAHDzcUswlnCMJikRsewOdOStjL7uNikJqI9Jst
fsEFkIFSdfWzbFG4xBcz6XzLxBcz6X_qxBaz5dbkJyXU2DjpUqIHDzkUswlnQTfpUqGcwFP4xR6Kv_Q4x8MWFRVNu_Pip-tPdjjpUxOdWDjpUxRdzcpFxRaz
stDxjkVsRC_j1VuY5UNP7lv5Jv_jdV__GMYGbxU7FTUCZvUrLpw0ZZxRmu6ye3rUrLxYJNsfBq_VtliV8q9FdhwzFg3WYqYxqxS7DFhCN7ju1iTZUm5PVRO7
G5UVxUdgipr0Lf_j0QhwR2_Gavo9xILqzTaU8AlFzW1PVRQ7b-4qR0yGrcTxilfiBm1PVRQ78uaTdApFzb0WTd2mFjlBKXu3EnXwwuR0FyJLxQ7-ZqDxeHLV
Oji1NDbUeFw7AByNihSLS9_sWgKzCbJiOViKtCHUdGfBeMFj1R0z0tUnLzkh_snwU1NSm1u_Qw_-6SRBg-3owptoQNkabhmABhxNGZvlZv6Jbtk1hGMNjCVo
Jx6Z_hlKAA-2AzeBxgZjxOXW15NAgq3RNazjJm7RQzeJb5U1svl7Lbd_OAkulN54LRVyHHKORc_wmBdiA4Edsnl68Rpb0uVytDxiz9OlxS7jJI8I9RsYRwez
jnSblI_rkRrPbFHKxRczvHEsFU7s9e63lIO-kBsnzjQsFRWzjmUtv_QytjiwVTkUT7i_0gyOlDxRclIytXk6y4wPsuiySyQGRcyOMz7tLDv6jpSC57rFvO5k
RsHyrT-wRaV2xKqZbE-KkRty9VRSdc_ZkZroUmdIxSd61xezMNsWsvj9fEqrxOd7HxUdk-PBkZrPVQ3Rqrqr1DtU3y7lr-Bs0cXclRkq9q2Scld06xKdmPcn
atHxu_KrZonkR_BWcMZIStjpI1w9PjPpUvFj4OqyjpVP7d5xUm4DWeLCfVUbzZDd7r_Sp1vb1qu6QdftiqUPSRFN5yhsxaTDp_PKpnfeUr9WhozjJuj0IS_s
T4WqivxjILmFHDYURdoaxSck6c1xmWykONkIH9EUxOr_GMRQdYhOGDjJ9K7RqoN2zdvllovkA8QXA0hk3FqN_26q3YTNcl7huCY4UkgffnxggQUUUfkWddwF
rIEv7ZMZNclzjyOnVH6zzqYkHqskXthgeHxggQUUUgY7UkgffnxgePvwg9T3FTH3FVLG3_NKKqyzr4CzzTHJ3_LGJptKGxrpgOTwgAUUUkgX7kgfXtgefvvw
wg4UwgcdddgeXthgeHxgdKazr4CzzTHJ3_LGJptKGptrr5CFzL1FFVNKGptKKw_sNR3tn7iW7-fHJwZNUW1RBs3psNfX-SIB-pRGvdXn6v2winq000000000
0000000000000000000000000000V04
}

