sprite $NavKit [96x96/16z] {
xTS5akP028RX3mRfll-5DyNyRco4LPvOwHit_AbQQwsrraZjYU9AnXXAsCo5duZXR7nZ1FQSu1OPNd2SwDBMiK1mGieuxzlDvbEiXR5WHKxav_iyXfmMVsKV
SMefvYLz6IUewUEKvwg-H5vHrKVqgQxFiVbrVUWOgEpJaD8-1BLz_ELzklODELtPb-ctBwEKOrMVvxnPWUPeLPzyBWpRv7sVmOhwDgV7g2LzcTDuJl8v1IcY
jNsTZgKFydm7liAwFfYY3-8qVxAY7wAVeoLD52iewP_2tNyZ3dsSX8f-_VK3-WgqfQ-PvFvA-Zavhu3Mzs4vElUnehzQv0lxLDaFVqpVDzEalvTARP-jja__
HB_xtUz-z_D_P1C-b37kYHwAiKDhhRKV
}

