sprite $ZoneKit [446x446/16z] {
xC6n00000C2WV_x04wa20000000000000000000000000000000000000000002OlJl9Rf1PWYWyZSZzx_SrVz-OaQ8I0jqxT-6JdpYMS24-ohyrdK7N38WT
Vluz5UALyic_bvn33LwTNtxedJEGhwfzwUbxNi9krbFgLoyTWbtCvyjoGt2hdclnRALcO9NYtQAtFtIxT0fsBvyTulC3eseyQjQZj-F19_U6dXyRDUlHj-6X
H-WHUl2XXzuyiTAhrEXj_eS8lVqvg5vFBzTJuwat--yvsPM4NhuwlAJUbEFDg7DF2thNV8DUxKjPymezfLQQfzUxYVgwUQOUfKwzcMVYmPTQIHEEOdZpG3pu
r7kf7Zxrtee3NsebJJZA3rtWjTuxUxtKKCltNM3NVPNlPZlyTbSYzFP3Zz0ZzD133pr23ptqq2Fq23tqq4EFq2Fqq4CFFK9FZeJUVew6NX_TFY1wyg64tl5y
CFGMxRhyqFFnXDwXl15w2tXTVkZPjNpesRLyw7arzCxZwTZAHg_cKUdBUkZfyFf6xznmUmw1dZO6YzxEgRTq6FIwfefUyr1r-4ZepSc4NhhWemVMJtFqSdZM
dUSvUlfmqqjK3xtygPVdGmyzzEQythnA3ptqq4DluLlhqOiMVTwEqBjHxrE-URWUUZEoVcm6lJlr0g677dheeOSUUkYXXnvwwFKz5HezzD2RTJpqactZeHTD
aYOSUfMXXnvwwA677dheeOSUUkYXXnvwwA677dheeOUURWkzNmlGrG6Y9zNoeITLyw5tV-WLuQ677dfwXHvwash_wEZDBQ5dzD1R3Jtqq4CFFVJGGmyzz7Ii
n-lvxnNgwM27z48FGPF_LPkUZdP2B_NiIF_KKJtqb1gw7UD3RtlezYwVZPvIGxTZVEXj3ztUvZFlERsYfpaGd_Vi49zZAt6jPN_e-thegLWFFQU6xjXAwAM7
ZXvwlET4Zyzx7NfSQq4lhuSUUkYXXnxlMlIYQotTUbmfqvcUUvrJJzFZVmod_ZkB7dheJMxcWONG2_8Lxob3BxMKpkcn4zuN5UobHYywz1XUG8_x60hk8K9l
51pw0XvwgL6WXnxlMj3ZpcVqPZJI7B13ZsijwA677dheeOSUUckXXnvw_sxlk-FpUkX9ktOIUiVuYf_7W9xgz7YALBCUUbhKcq4lpBUAXrwQhm4FlGde1V3G
omhEp6pBeHTpt7l46tfvlaKyzF9ypNhehU6XbwjP3xrzFFI2tOE77dhepJOUUj6QzT1RnaClMxCUUhjuw8LxC1vw_gr7wA4N_y67ug7dlpLDeMT_m7SlENeV
VR7G8yvOz3x-sJOzz7Ip7dh-eM_GGy_zUkYXXnvwwA4tBNhe3NheeVTfMhZEYTwpBrEhGm-z_C_jXzxeuiH3xoOzpV64NZBlZjFeBVpIVKT3psiJGWyzzEJU
FxBeZVzMyv7GMplBXTu2NzDnqFCSokZLpbM73eAUpZzWsgVmq1kV7gxHsplvx9xbqHlPnoPidyL3R_nZEhEkq0ldnGQzNhv1hvPFWrultw1NwpU3NYtVeDVB
D-ZL-isWr-etWrwhtmnwYodx2G-z_VPFEVG8FVJGGu_GwmizGWyzzD0Zz0WzzD13Zz133ptqVAiUU7RHFJSa_xk07NvDTr3P8JxQ7_ejUtkmo_3P-tpWXVZs
DsYHKqEtw_bKyjlcXswtypLke5xKKzjdfWAy39_xRrwiurDgw2hNgxzbxxhOGkwRGx-UtwudN_S5UkxMwtohfMqzr-7PpQSUUaRlI8GUV2Rq23r2ZtSjX1wX
Xzuk7w57qyj7BzyPyOOT0TSfjLBd4DIziMLYUfLyNx4ZS7hnfXGlElHQl9bMlUJG_RxNi6QQ-Rxa9Qm-lFpGVLNf46QQ-Rvx25DGUkYzzrr6xDfVUQeTmgZs
Nb7kTFrlUt0i00000338tth_6Ae1000000000000000000000000000000000008
}

