sprite $ZoneKit [93x93/16z] {
xC610000082W_QaNgG80000000000000000000000000000000000000000009Yzyz1ksDYX881xXFB_7_nwiJSn9OjOYZYvazveX-DPbkMAfp307O1CWoWY
CwigCzna57INzHMtl_G0v839612ra91H071tGC-fyyYiVv8PKmHwrXzndQFEC_FV-ppZRO6AgEy4T82y-bF2XWnrMTznD8m_owPk2-e7VCoWl-BMjXTkhWzP
Fm6vE-gryDvXsw8MXXn1edx6xYulgsNWqAYVyG7ZviInqvfskdeTuKE6dfMyTNmQJJlTwvZmkpBe-rx9EYJHCFny2f9wuiZ_QGWcfqSmE3tYWzCZeV8Khx5m
wDIeiN3ejBejPB8zClcaXMZNIOlR3K7M4R2R4lKQwBA7UNCCeRUUrw8zpOPlUR0zjDcxMtmXu-t9CsosFV69itj-iRsqOJFKYNcF1AnarxsMK1cWRqHvhoVZ
NHMxt1UVzpHdrYkWgsACUYpGJUwDltYqQXew1or3IJUvEzOstc5aUYk0UxYxGsLXQ7o94rUyEyzP2BBhL0CDwP7s-BHfIoxT48qw1arR2kc7M7OLet7vRHQ2
7dd7-doJF8BeEbOPUCoRV8yMUOzxlHmz0oqbXwjiXPX7rs9pW-VNpQXiXzZNQDBHivmnBd97a5stHQwtHupsLcYFq1wXFTgZFTeZj4TexncqHsYFq1xjqHxj
4TeZj4Txj4TxXFPKSHPJfRthCRX7r5aomW6blGjHH5OZwLS9f3tpse23zlO3pzg36-tjnJnh6-bAUnj1rbO2jBSBzTfDEktjGQCk89JsDe2wXZ3Q6tR8M_NH
tdvvwGwesfk_chl7_i6JzZHg8HpIWS9ZgpxQKz_vccd5wizfhn5iNYQlwy0CsjlrYJEkss-Ufj9U5xw4jmF5bh6Jzl1DdatwChIdST5UHIxnqLvp4xZiAndj
TH_rVDQNeZtztMMqmdy0-glF_qsblTxX3ATcaVp45wEzqo_ZYPV-xJFwD3g7JjhJ_4qDLeVOR-8BfRqdDEzEd7uxSkwvEA4zbxFs_5T3BsYlyIGUihyzmHvx
jAUdxPaynRQSjj1UddXowNKTIdizh3ha1SnFoAEzPYoMzfwXS8y__GLwGtjiRqNb1DliiRtzxBV7zcYFxT4UswCzjiVsQ8_jnLnxR4zyxbrgjYV8ROziixtz
8BR9OtlxCMnucpxR6mxRepssHtjiZ_RO7jkZFRP7UsoFzjWUswCzjaTxR8_jqHxR6mZRKtpa5vMpi3rznF_9Qt__W9o0xUaZyeF4Gzw7xJtomopws5w3l07w
s9v6Vfm0snkKtig3xPsp5n-XnHxRUwXy07talv4pi3t8Hy1YZ-tH7jlR3EsnFRP7UsoFzjWUswCzjgURkByzzLnUSpsjFNriGpVPW_UyczgplfBGSUqzSXkF
BVRCUrvYXwYLnB3sD3U23VPGjUBMzlPUp6eFm-nvqxl5hHPMVMnFs-rvLOi-P5scZyUzLTvAsBibh8JEEkVCJVIVSrhMJ_Y9du8JM-Brtdl5d1dnj0v8amtm
NWlgWD2c3HLa0xpFwLqxFUeGwOVjMJNPiwn3LDfXUwX3GfisL91ss9xN8MbTzdnIUtXWow_TzgAEUTcUFxV7wxr0hxrw0hhQYm7jhVBwYStss9xcHd2jlHkV
jN2E8UeOtDWUvnYyhRris13d69glzvegZadtMl3O1BhljMGTuN_H-vowXHlVvvIxpJ5mZg5hIv0TS8v1lUjKGwCXFRRN5fztFTToB8_jxT0NrhGbboxOtefw
Wxn5tu3dEQTVCHphIsjwbjgchMD039XZE3vYkPrPWxAiGndLdaRkGs-sZc45o1C_0vnZQ5X3P3FMxt4TmpfwSkriZ9cTvThP-MSjNBV-3SKcL6YFzrhO7ksn
FTfZUsoFzjXU7xJ7zjWUxR6zVhJ57jkBepbKKJps4ClDptTWUokFTK7ONXvixzIHPmMBuRs0xVM-HKeRfzhxqsDxnyFYuxhqGaNONgy-j4pszSjZUwk-nq5y
czEBXyhxiBtrYY3ots19xx43g2omlPRx7w7VnbN8XR2zqyV1npUNSclOtdgQ4X3HBtz-IzZUofVuldPuRzZUUdaEN9KUs-kFBqQan_QEB-13vzXZU-lz5SXs
s5x_s7dP2w7PNYU8OUcnlJM-4QSiRE_un4MdsMDxWadfiRsLnw1J5hQtWlkcn_OKxd3eWRwuPtfippoVlrWL3REd_R0zYrg-nJ6mFSlwWkjliytqJobdUned
FWCFosUuNGpRmubFmKCknLuCsujQY7V-ro0VWErfhQI-OTxb0x0zdFW0KQqjzjWUxR6zSVPut2kROe_jQQs4JB77ziHh0MFiiJsnVEE2WVPQMJDw-xq32Vcq
FThJD_KbvEFsQ0_lVGPtGDxJ3jexOFFUH6HaEaxyjFH1Uo4Na8rlUA4zo-NuTTqF2-sT9ouzZV3MhqPxVkK3AiZMmnxjMVqVlp2zDDfh8AxRerX-KcYlTvVg
LJTL2xJNWULL-zINMGdQQzwfXLbVX_OqBzcjoEe_lQKzGLsW3tj-HcXFOhi-zKql8AUzTRRLRSCay5VIQ6_Rs5c1zb5pNzsq9rwhFvKcT77NFcxIdaOj961o
6eD7xP17U-kHQIN37ITmzwnQSQMzJVNjnrLeRqzz-t4Hsjk1-QJoQ6_5ixQI4A6zRI1g8m6XlPqOQXjGeRtDs9xXCrr5Q6y_wFSNRYAqTms6QCqE9a9xLm94
P5PMrlj_o7105cZl6XGdaGNQ6mdj4TeZj4Txj4TxXFO8xHr3UuJs2EtH7ktH7g4zsgCzsaDS-HmMMHVBkBMjkKatsGmnRrb3PSXQIQXS0zsT6lGGbp-4J9PW
tXu_KJ-nInzHRtfm7msBRqZVohUq1dcxzL5UGtsBl463vxhIETnDPGIeGzAw5g-coRrH-FBm-mXvBIEUJrjtke8OiV1aBQPbn4Cz1yDEtTBcfRUIsfDULSXj
iHXudQhPb8nblO0Ea3T87-e5GaziQCQHpmy6dliILItngLSD7ZenyrIhNW9D0sUbpJj-OC30UJ8PgvT8pDiDeSFjLPUzShiXY3e2TbEYovxNQ-Gj6V8zhzIB
eCDUFuJsQ0zrMuWEi4SQpZddGNkQTLD8D4mqVGhY8cCFVCIwPeYkXxXAJtmPjoJ7VDShMSz1qpnlwiYdwcpqzAotFPKqSYUuZ9wVnRadiYSivOkfpp5gTXLZ
MLD781lx337g4DU6BSrzliTLxWtQYa6EaRVYOnTVe6suGunv4SKA9iexRiQjPp6PsyYTu2eJGBIz_SDYIdWhwj_yPUZWrRFfsl4sYt3850oU_rK7o20KdbsV
z620UrQwErH6OVWNfZ8CDRXxLRe3_9IElxS71m800000WlQdNgGg0000000000000000000000000000000000200G
}

