sprite $ZoneKit [96x96/16z] {
xTY9SkiW38LX7IGGv_qVk8k72GDEYwUHxyhNVVlhmOu3oDgsRTksQJRv0HJt35ag92jaBRkN_dk9dsh2GkOdnqfoVb9fdBUe_V3leN8mDehlsRNnIMpoTFou
SduTii96n_4liWHJMIiyk3Iex0SMmNbSZ_AGIPD0HXP81r92LIRvR_eO1FVDEN6DwyFvX8VrdIoAWJhfGVr2wjEhssBwZn3AuV5lFQIlZs_RS0TC92BwnYfD
_cJzrmFxi_lxKgi4zzTsN_ENDA2Fwb-gUBslFJ93rT_PXvC5b_h-nBbVICSqd_1BVSqdslfJhw9d3YbgVC13bYRpO5VwNazyxYiFPVeQKUC37cmShn9t_UJv
V9OsMY7Zq-Q7Fxl-zOcx7rzXVLM52FGaH_IFiVVZmuc7tFy1hQfLSHBs_EBL_SxdBzIAU_gcRI8aj_ITxELImlia_SxvbPCbkg_itqOsaIQHeVFpMQ67hI_I
dUiBgUSKSipwg6zD-21aVTSLpcgENL-h3TBUVtWTXxvLqbN2gFUhO9Y_hLZ9aAKqpGylxrfusrPRy74_KjcOVg_ma-j2x_L-lDu7RvB6Mq2M1Rjuccm-dwNb
L_8gt-HvFWvJo0L8a2kW1lcNRTkslGC
}

