sprite $Airwave [96x96/16z] {
xTW5blC840FXQacj5z__m3ypPD-ClUmlJ9N4R7F2xNQxtMwtcvohY9_rkD13_E1n78zUv7sBx-Kup6NqECftBis3ZuDlwJYur77exj_zP-x-5d1GkoA6YkdW
6XLOJLk_hg-km8iwxdXHWmhDVlekfXfUrq-SJtsce-AKXEbqIF2UwLVJJ_rjeBDwVy5XZSgQQQjNzTMs_jXN1UiIT-XxK1UcmAlwoKpsOnyNt4KjgaOTqeMf
PbxLNy4K1nKIfeO61rYZ2fvCF_VyU_Sz2DdO7ZD2884i43hPRyZ4mrGi2SjAInpDAYVxYJ99e60bardur6yvssSp4L1GulXpVvcDJ_VTIGm5gkaG9sJiMVPa
VpwU1-RB8sPuRvZ_xVGlWmSCOp1OC3QoaS3pyH4ZsNvXtsLg7AEQXIopCzX35bNAa8wCmqlxaMDs5dbdiJBs66z89f4sH2kZb_ULsDDq96NPhMqoDaI99KF6
ULL_Ojb6bjYTXMMzumrXPMap6VgY_dFpbq-VT__kVtfyqjFVs-CXhlCu-jCN7htCyVFWqEFFFVu3ocNCFuf-Wqlq-M0-Fwazemj-lPyUPZlff_o9nShB2yUX
qtq_SK7_gVFznn_WV-bskztU0W
}

