sprite $Airwave [446x446/16z] {
xDX7iXuX3811K54WxdzWvpmxM-0NklT__8ROlW40000000000000000000000000000000000000000000000000000000000EYZ5EsEYBbsFNAEw8VRpTod
a6j4EsQim-t8sK-DktqUETe18_SLp6Z5-joti7fnlBNl8VihZiSAq-Pd9iz7lCmr2x7oaQyL6VjtSqJqLeWUOwxzcz5AzFoztPbmzD_FP1dry-QCzi2H_SLi
1I8VxtWA8si7NvyNPqsYTgX4tXnvpFrJwRkjTfMrBzg_seytkyNIDmlduTdkClXMtSIPezt0gDjrpkkh7dNtBUlnJgTHjl3rl5wFMLKlygyE7wXdsxBwQwj7
gFUa7kgXddhggOTwgAUUUkgXddhggOTwgAUUUkgX7khLKm_rr5DFFTH3FVNKKm_rKEz9FTH3lVlKGptrr5CFzU8ZUsUYxB2gOr5holz_SjS9pYgyYmfnTx_H
sk_TUsqXu1JB4iPJJfdO3JDkQEMtiY2nh7grkMdrm-4gUpezhzTGQi7RMdxkrcjM9IDdeuHXnnAJHNtifRqUBZxI5Dkp7ayl06A_q4FrAR5K-7vwgALC3DWM
p0Nfcfu_c9uCIUpfIVpPuA-iKi4SeOPLhpcr8pRRnLxJgoqzLSpn8K54P4XuQgz9FMb7uh7fBHCdAhj9ZvWGLe1H2DBhFdKQVqDdJXLGwasgOa-lpCmywX9y
1IkPIGM2SAgeBwbJCoxqqWmTJwO78Yl6VqDlx5XCV7JYAmah72H7fXVr5ZtgSG6zNkzT3tUtPDosz1X9W3ZR5DKbh7JQYpDmIRcIEiNWY-Acnu0Ou_a3FNOf
jOkd2psSGnAdz2fdc1Ap7NiYKbWP0_eplQ1qfaD91ktfoIIq9upovonYiMDF18C0WDsDFPkQIJjO7OIL5jUoLxhGJAcx7NigO_GOqPlp7gwoVl3pFpDSOMJQ
gqwGD4iz3X9hUlFmiBcZnq0oxX8aVhR3MIobaXybLKgENK-NedWqlJaL4OOtrdjbn0nyuaGJE1Y8S5w1rNqoGzDRok33cCQ6tgkgIYzra1jffpxL9Qo541MN
2_QWNjCJwV0mnZUkKeTEeFOv8e8DcToa8rAb5cfcQ7f8KvZcgJqzSUL4X90Z5REXSQg1A7-553KzaQoV39Q_qGl3ar8dSP92RRh8ARrggfG4BcSqrAn0zc1w
CJ3aALPmFz9RBnoBCgyBFRrrk-uLPZF7Nk-f23QLVwLNxXuK811PNM-5Lm2MTbOAGMJV7xXeUhuUn_fERs0dNlIqvHDmk0Mh2HnLg_L4q6B7thV4gIhRqMC2
EX2pNEZrioAODhtAtQF32RIEFH4u5eejlKDp9wQ8imKub1Vr2CXzwYoBgOkEFPMn-aO0sj6pae31k_H-N6N9VOAllP8wENlfsDiirTMqfNSuOI0XKtER9K2_
HQqks8CEElPKwxdBIM8RUWovoyI7p-m4K0tQnP60pp3wYfxtSoqwPZgs-pj4b2ggbEGiyVojLpqEJ1mrxTe3wMdmw0fmHm_wUWsPDjKKz3hloafIcbQ_Vfvp
VS0hqjZImxSMTzzCigasehtwUi6kVlqyfuvOhfbkw4dkL5G72i7WDB99dL_fTUpb-jY5o8QUvaxybrScgPNgiVvZlF1hUYlva7qnhz_VMplZp_xLngvuY7dT
4khtzrfDh-arlQRNQdgjfhTHqsirlLRJQtfDh-crcbwhwQtLz5fDhzNqcbxJQtgjfjTgUdirlLRJQpMzfjVqcbwhwUMVmkW_C_rlmoBHsn9vLTZRcNTaurFp
zAN0_BthTY2Z4JUx66rgBPhUJl82GSwVWqEv-d4DEtnwiy3r2u9nshEkl-Q0irfTFZTNrlHs0iLzUiF7gCZB9vCzQwuIGe_NNeHUihbHquFFWbuDnPl3dp1M
6Z6c7tLqDaC-CnY0cgnbGYzmtQlfCMnAhwRNnUrFm-eVMn9lDeTHV1hnuhrpJmKLVzO25FH6hVnn79lU0BMYTwXAFfGp1raD3bD8vZmPfeB2DoVZpKclwLKo
t3Vf6VJ-DlBSCJxPo5meTQ6tCXP1_8kQdYL3-3izTkD3ByuYfhq0afoB2BsSwDsUz9gUSUAodlSMz032fpN31nAcFNLsk3Zql2ITkXmrMpMz4HQcz90lwH5c
0vXR3H004MUE4JbhAP_Wtf_qcjuPQRVfsLJDhFYza_8DFLOCkenutGwzfiSK5R_JOz_VpZag6oUYt-Xjbl3UzExGOwJzGgzYo9GU2ZwC6cF7Zo1wzlH8cnZh
TkfiUfnI-9rpJYO-Vx5I2yvaTlGgSq4ludLphTxq6Eexz72pV170DIpg39wOjn87CTx9dKqFNFyhUbvdjFnHPDhRh_UuAlD_lTRIz4OWv0rw48eFWvXQ-EbQ
IopkCTnThpSzUBrkqXlhz0y2E-d576tvvJgdaJintWs-faSOAJqViYKzcDTfOySfv1w3rqj1VU1NgF4-lgPd9VHGhkZffmJrTsHtz_US6kLYl7-XkkaTVfSU
WC0YxaV8lVKl3q4iZ3VKz2plqWEO4xwWN3_NelIuJeqHwD7qThhCQkRElZaI3vCM_aJvrLsVALCljfV6fjVw5z5hDRrMqsjwJQ_fjPfUg-arlQRNz5fDh-ar
lQRNz9gUlIK6iMmCc-8ljT2sdxtxPyTK_yNqBCutNr6fmTw6LCFqmuPNVyT_baSEUnYrK4xD-h8VczrZwkQl50UdaZZ_jzBJtvWqlTdAemnQ9-KThxK_HAT7
ewc5INwpM7y6L-y4os-Ruk3y_UBytqtlvJ9akVPGuafF_OcB6PMjwMcpLbjwmxtfCVeyTdHvTNd9CqteYRz4uwioit2jjsNeRNAbzn9wkFlYHr6XDrnUkFi3
w1NxZFqqz57Bt-5seRVm1qkTh2tyosEV-alUTQMd3yj06tgGbwZxBwQNbmSsYrUym6ay2aqT1b_eYJ_kyTD3krMNaAxyJg_0zs1wpbXRZi1vfRm1f1DIEM42
FVnpr8BA_f5hcerBCFaczdZ5wCdqnfkHd-VK7Neamk5seMV9w4DF_R6mlOqzXy6Rusj3RvZjsVHYUlUZRAPdu-2sb5HO1v2XXx_D_WpmYbxuMmOz3gG_wAdq
77U2V7I-f1SFeSSH_nwxcLxmshESsV20-aHF_IKCtDtSpPajKK3lo6dzu5TwY7FEuDXuSknzZdXxZmZq87CIyvaU0uVFsf-1j1hIrJg026d_P84TlJn80G-c
ToGHKpRJSo1WX1xFeYVqrFzAZqZx5djMV6ymRHzxf807qtkFt8YYca6H2DcQw15y3f65_nTwEf6TlHFOSTXwtZk8FKe6nMVEUsEmnh-X9zzmP22XTvuoG6_X
h_DU5BxhSywHCltC0hjppfXUdivdnXvHD-OQfJShPdfahH1wubzomhEcHxFClNLiwIL5PK-c5tyOKkd5wweoXdaQ9EWj_6MzP_lOUuFxsuuzlM3h5K-cP-TN
R9mJ3ePiY5G8FN11PEtljFSBlN4WyLTjOu-cdhlUunIm37ho6N363teO5z_rmn-ViD_eqMOTlyKUDHuSUmVln49FldJ37lJcN1bV_7t4HYpEMZ8Z8uF8dUZv
WjxmJfVOE_Bfz1m8q9FZtIyhyRa-TeOCVvyGNpxujxwtNhYNAJszEojvuRdqG6NG0nUkm86UFA2mzkSTS-HVw84zz_JWCu0_UTwJx_Rbn-9wLq3e7GczNFfp
v-bKXMteCJaAFHGIUnG_8FR-1PBF5I0R__mak-d_F-tS1uhpC120qHaXnjBz3_ptagLjiQmuy1uiVPi-L9BO_aKzr5DFFVLGJptrr4Czr5DFFVLG3_NKKqyz
r5DFFVLG3_KsKW_rr5DFFTH3FVNKKm_rw1VKozY3cdzLd9B_w_LuCUh5yV2Jzc0i6_DwN8FtScWPVTKEkd_fj72EZ7DoxfryvF5_nEEiO-_ae-R2eqQVE_FH
n_odnLavvebTb3F37UVr-Q3YIhInUAdBCHzKYwkGDURgKsAVZyPL_QXZFkgnn37V6jLpBLhLc6_KkfrqDqOkt4ltOlG8-SJRdO_HOgcikP6PjrgDkGMLiLxR
qO-ZnoMorRmMe-Ubx-MCUGt6g9vnhTQhZkMewXbRv7B47W00002PlVRgBJFEe_KwvXCSfzztfDLuqO_Qo7hPQnJentosKHcyxfKq9_Av3L4-MzxUVDIyZufF
eSyxwS69svQEskiOgsxeiMvMpuojCckiM3lTlZtQ3OvD6Hz5tUB4rxyq-PYtU49JrXV-3FfDHYsFpx_XoMq6hNrwwQIDsupPEB7zUbHNYqKyddJ_a8ruihRi
aM-UoxnVZjUjfrxKvzxh98_xZ5ZMb-UUUcdkgRTXxc7ktOMvfrxx8P_wzVaJb7ftrE8cr7DjYxc7kRUVkOUvfvwvfvwvP-wHTTpHn-gHjnJd0G0000000000
00000000000000000000001y1m
}

