sprite $Airwave [93x93/16z] {
xTW5WgDQ54NHepSm_m6taVRImDT-goI-Wnl-vPPbMPPbuJNmX6xxDRRvjS_FwUqIdpg_r6VVX6jesmS_qhuJ9xmOopwupcttNnUV_qvynLUyGo11PYeEaG8r
D067GAMPqIDnDJxYHOeA7MA8P80Q76Zus90dAhx74pRM0CCQBXnex8VYOmrndoo4gYXVWap1OGLDmWVYcazy33c7uCHiZSmdH3E0vh4PcW3kbtZW0XqUKrr0
3Ky0ZSq7uYP0Gu84c9016JG02JpUS8zZhQ4hFaBHM6rab3ARm2qPz5IyHL4H31XLOOd8ijdmL3noKGiCK2l54M_1wSau-ct8aQ91pDAAMFPKNA1X2nJkwoiS
GOHXc7_OeYX0_793WiSzK8H47YzAnskI-AwuXgYX2XxgVYyIAch8iIgai9IyCnuhHXJOqN6l536c8iUgaS-tiF2-k1ERau6P7FSA1oNyvKM529l7uh8Do-JS
xyL1JIksLJFal3z-uBTR7ly9aBWZGO1hUxxYLvugQjzm6VvwnhpjDrxLllqwfFf-NU6iJoNz_drNkGc_eQv1_4imVLg8ix8_BpZ7-txhqsxxRfooxSLpkj_E
hcmlltZ6ovk5i_4NrzlJyPVX5BqCVxTbMPQF
}

