sprite $ArubaOS [93x93/16z] {
xTS5ikGm30RXbapwRT__kilCgNWVwfi957MOUD9IIYcbvEK8vsSrT4etljSbnH6IuljwbHg7bD3WMw76CIuvNvbad3DKlryMZnVFUCOpdl6CjmxKrYhKZqDj
hHdGEq0RtS1xBzVZjdS5BUr00I5YQIqeUnU8xaLki_ZrE7r6WCION-AYRMD80nTGXmku7f-ZRaDhhF4blkSEMAqjQWTCTDNhST-AtT3Iuajyrh6iR6dN3t4N
M8_ByRx6c4AorObfDkFZRl5OOwom2RGEC2_7Pq3RfWyzNtil9_RUiZMWBslg8_3Heb-Ecm66sSVPKW1x1mp0m8e3NlofN4GPptZ6Cvxnyv-A3_MHIvMQSKOD
3RxJTL3Opyix99hn4_CZZAUYzjzenaqU-htABIP5gx_KXbIueocCt-aAxWXLVdBgfX4g_5x8xyN_w0d7xIzuS2cbz1O
}

