sprite $ArubaOS [446x446/16z] {
xDYvZGCm3031c6J__LvwjbC-431JWXRwc3q0000000000000000000000000000000000000000000000000000000000A2Y5RKLBZC6a3cTC4RBaOERC1OW
ddnNyP1EmBjul1oFh8VZ8PvyP_4O6MbcP3SYVhT9zU-zhCe9r4-_xdWvYlZmSZprefwgHxMkztOy6ZVVRJlreYrUvGhQTipnrhFxn5DlCH_zzIhNq5qlNwwd
tXv2FVNKKm_rr5DFFTH3FVNKKm_rK4yzzTH3FVNKKm_rK4yzzTH3FTHhfXxggQUUUgY7UkgffnxgePvwwgc7UkgffnxgePvwwgc7UgYdddhgePvwwgc7UgYd
ddhgeHxggQUUUgYdddhgeHxggQUUUgY7UfFKGptrr5CFzL1FFVNKGxsgF_RDQsjk88J1rqZp_g-RdX1hDEoixLIilwurW0_VmMKBmFpYmVpXfSZ39Xw_ICpA
-5Zj0J360CB4CwF9flGulakTSHI2Kv1RxwF7S8JIdJq6gd0UA_IZfnsa6geuHIzLr_PqKc1fTwTd315uYTxOdpqEen9UHteS9JqLhj4ROMgNWuy0cBd51y00
Chu7FSz872UUf-SZF5VOMKj6fyRjeOVxwVdQzQR9PaTwVDrRESsyIKzFK-lQL0SYpSvdzhxrT8F6ENhUFIQPw4LU8Ma1-RSrlUpfInguGiz7I6q_PKgRIk-X
nyWxWjz4BsldFmKzOPRNEG-zRExjzDGDirwjMB09gS--zBIb-T-zvpr-KORhUalQew6cPsjwp8cBxE2Tz5JXQhEafnK4_JDxXsPQ6ZVTxs5EJs5HpPNBtvIU
zjlEdWeyIq_XmTUkJsgvYZ5dVUWDrlHmbPva2AczHKyhFFHc81RUMNeQ4BRs7htCaNdPXPuYYBmihEc1b-aDokf3xR57BqMqVNKsDlehpWbwaaiIYBQkEVqh
yDteOLYjRPoWTnYIf19tqSjSR4MFOu-U7DZEqKjywJgLz6ZWPUvUinTZ8KCZ1qV8iw1NNwOKT_FXOUXsBTsAtYWxc0ii2xXJOKrlV_ReOH2lhsOUUbZJ6o5c
E3ebxxhsO44Z5rYh8pt3a_C2YXU2MlbgUcQ0c19VSShq5bvlUZe-rIFgJQ0CZurEFqaN1zRbw3tqoZUQ78289_4gxFZsciVWu-fTPYIWNZIaLn1TuE8bUbpL
pdbCLYDuFF3cMWGbijFiZRA3bk_EyA6avpFNRq8hTaNYsj3pDsmeMqObLC930Q-kdVXKu3evq73sAgRBSUAYmPkVWWYxNkiH1I3ZFVJgEtJERnz2qS2NOnb8
-NhuEPooMBnEzFXDrUPf2MasVSDeKeacQsEVcF-8FhPptyWDm30K1Mi0zx-lIuVMuETGirkfSU8peAoPtnUzTnRrzgc7UkgffnxgePvwwgc7UgYdddhgePvw
wgc7UgYdddhgeHxggQUUUgYdddhgeHxggQUUUgY7UkgffnxggQUUUgY7Ua7gePvwwgc7UgYdddhgeHxggQUUUgYdddhgeHxggQUUUgY7UkgffnxggQUUUgY7
UkgffnxgePvwwgc7UkgffrvDnx1UhsEe7nwkfzxS-IVW_j1ShsTnlZHypDgPJwNpiNZazSjqaichdeLl5Xi_whVbxpPz3DFRir9_TFKHL5UTg1TOdnmwvxg2
dfVpYVTiFMRtfb2UoNjq_CHJJxpqzYHmPp90l4NJWNvC7pApsu_qmyXJVMG6hSkQpW80002epENg3KnrNR7mo1NlFbV3um_wUrsuVWOllp-raq-yV3xnv1Cl
de_f3tkvaBUoHIVDy2s-MNxoqz-R-RnxEq--m2UMo2TUu3VnIKzPFcleN_McBtjq-XoOUkz_dB9wWUDIp-8C_3eMf-6pETLJ3_Kor4CzBuh8QzHJJptrr5CF
zKBKGxqyzL0l3m0000000000000000000000000000000000-08
}

