sprite $Central [96x96/16z] {
xTE7eTX020JHWJq4st_1plRFKNA-Ly1SX7_OjctRjcrQLr7mWCONgWTvstrSPEo3kyOTN6RPkhVz2Ivqt3j0-U1ASl_x_TtV_TrN0YabP488f0m0vVb-sW7j
SLC3SgJ75YpF-NxrBEXc-QQVJCEKytH_rXheoPwRVhUJS7QTxQVNSjAsavj-UR6iyjb-USP5TrWimpBff8VnZ7Moxu8QkbdVDjwakrrfmVIvVbH2LcZ14bab
YAeIMO3MNpk_kvzLGbKLMG8fwZDMbG2o4gXyPt-vk-df3jb1TVIucvbs0Us6iDxPTm5q0vffga4EcA86miln_dvQ0EqPP3bl-bCkMCEiy_sHaEcvwSyCCBDc
tjzd-kP-J7fkxYSjqjtjV7zVdXdQCob3-QRFSfG1LzWpx-eJKf2IY0IK408oGPa9PAAK_k7vtVtTttrvEE_f_OPzNBfzYpkMFSTLscxkaQzqy93gAYluayHJ
k8B6JpeuJNxEmLdZ8tY2R9tU_l2qmyS5W_uqkS_tzRIweF-iq_qrppluARPjsxQF
}

