sprite $Central [93x93/16z] {
xDS7gg0X3811bP3W_I-yz2q_Itk9j1dm19yjQmW00000000000000000000000000000000000000000000000000000002mk_6gt8dCggpMPMMSDUrarHr1
LUmrPqVUKUHPGwBkD6gctyxx0XMhNTnNoFONxxv3xjKfxtloYUVoFFSreYrUVNwrSLhndQJFoAXGSTO08YUUlXXvJx-8whyxHoT9_d_DTH-zsciKsNluTlqH
xwnPx6mzA_4e7jyFVdJkXLZpYCQH_TJRHuzTVV_xy_heaNqJUxu-Ufo9UhcUStMkdvcxE9a_CU_71KAz3_LG3_NKKqyzr4EzRkgXddhggOTwgAUUUkgX7kfz
gOTwgDT0FTH3lH7gePvwwgc7UgYdddhgeHxggQUUUh_OEnDSntKTY9eaG13Q_tvxI9Yhb4BXMlp_pNLwj2NP3PqKuo5n4zgZFTgZFK9xXFPeZ_PeZz0UeRtx
q1wXFK9xj4Txj4TeJv_8jI0waRgjM2V5QEXOxeFsUeX58ejKZpVSxRqn1-bdVySUYRjdNq0ZCTfh8J4IMsTs014s_VhR4EmValO60EDnCpcg0Utfm1b46qWO
JdiKzhosLpkQkr3Qw-1pRdLlR-rYHzcxyG9nsklmviYszd3ww-p9jzb3ITWdQEy0d42C3MOft2C2QkV1-rwuFpO0zj5tv8PFeJtnfuNdFCgriI7g0U6nc-zx
wLVifIzROIEzqabxEUMXlipWFajobZs3LXoHEttz6sYlMJX5dt-Mzd3wvUXzBstLlfy3D0SQxPtoofpaJExj2TYpczb3UxW7VVNlbKxQavpYgV6cFJzwtyFX
wDE_HWhjjGhd_9jyKpcxxtkI0npxPuTMwQIzZCiyVB72HZNzTlTzp-qt7WC7p4teJ3BjtGLV_dC6PNV6q3pV6n5mjeYoixkcIDex08pPpbxudFxXqh_E6KLK
mzzZIti7mAJbWe4D8EMshtE6wrKKpYBuDw0z1M4v-LjxETVDwvpG7tO7Acz0UpXdi2HRUwtxU_5a9BQuDXXhj7TQECCIc5-m1ordrpbT7rZWVJmy9BLi3jgx
ZOug7Y6BlMo2kUrVvtHuvQpHLDgxYu-Aq4yR1WUSfzSvSNEmjEAqTr0uAtorLycoW-mbWGUP9I6qTm-BxGoY3VXxOc2wMBMrPxbG4aPxtSAPw6AliYLGPl6j
iBOdxzdJiS5fx_Y8Cy7vnxm5oX1Sda92LtieDo2dDec3qabxa2OKkjf3EPXS4_peGqXbJzJ7kxrFLU9WUm_jOPZgTVjFHk11OxYPELo7XlvudNJOUrlnQWhQ
ku50bZ1GlhixYqSb2BHksmFtay3kQAzHE45fDPqQu5kyaYCxUyMMXrH7KKPxZS89Hp9b61mDYSTOy6pQsNDTYd2ZTD8UlFpBHAAzkdQAWRwKlhSN9cNAwcpl
eJsB9vlLyf3rmEMZLU5RN-Fn8roNA0NWBgzssNph2rRJtf-2s6_a-lEWFK9xDRH7Q8_G7ktH7kqHsYEqHtkqHtk4zcYFzcYFq1wXFTgZFTeZj4TexmJQ8xId
vWzCvZfRoKRHNDHb4x-13kLumJKxH3TTSZtj9M8HytlgfYbf13BYwoieZwK8cDWO4ICaEm0mtfwDhstung2zUgoU_B6VGNilTmC8bwUzbMblRBzabFPgqjv2
P8W1sJxGFnk4zbxJXCIqXwpsGhhsaD1hHMBN6BG7ybRykfczuMrxI5m0zd9cRqVC6Oo8cQWxsSirVNjW275Go-oLsCoL_i8ylcPINWqJ-R3dKjYxBF5b4x9-
Bxrycl_SHpOhirUYiJvcJ2mCxPM3C4veRsAW1bSQ5cwhekVv1xDNukMZKC2Ux-pbx_gzFT_Omo_i5OfCm3wp1qYKXcvbBs1i9tlOfzg5Ii2BYzchP_SyUwuG
lhOzZSAULG_qP_OG0q5dsVFNDBeqAoVsAMg2pH0oUm0-nQQJFNWEGJzxrRz1CzNuQ5Lc3y7QLziRyON1cnB8QTkp_RDXOlxLcRt2ptVs40Tx2WyaEwwS_Zo_
7Fl2wJE6GtVPeprfshiiSWEDxCLlgckPQ2nDsYvxj7VrxCqS-B4z96ppNq7CXVz_zcXFCtnsNZbHNbquP_VGJlRulXVXhn-6zY1T_Uo5QtaUO-YobJtQk-Jh
1zh3_xQoRqyln5DgalQaaJsUCVY5eBrvu79KETDEkGU9KM7CtiATi_NOseCe-ELdsJFOFxINU9qzslDUzj2GDUn95VuO9I7C7W0Fb6va3ry2thZEQQaF2sUD
RhB7EqJDxE4TtiFiGUs6vXfdzihIYUaGESWUp7V3diQQVi-aoGG2oko1Y0Tk-bXMynWAzdGYO6zDy67bh0LRm3845FM-yv__L5A4UpvVNy3U6rhOW_3rxn1v
jOWZ7B8Nx_n7xOcF3o1xWDNsn5lsCFu6ERRou6hwHOAVnktO0mEToecAfoZPtqKEsfk8txONEtkNjxCtTJWKIG3MCdk0Hen9XCjfzYw9jZsidVXXYxM7C7i5
OXvFt6q6weCCfJz09Ux5MlK7TXKhzNDmRZeR9xZQ_9F_dZr4tau9VhPp1xbYmZ001UCeSiJzBznTHRlxr1XGPwxmS00KmetrK0_rr5DFFTH3FVNKKm_rr5DF
FTH3lSlKGptKKqyzzL0FzTHJJptKKqyzzL0FzTHJJptKGptrr5CFzTHJJptKGptrr5CFzL1FFVNKGptrr5FlMAC7MLPlTzSZJlNAheCTemEpRhrRtKidw_Xj
rbq8EJgmwvQxoCU6p-Xb53m05Rqqq3ykSpVc8ugd9O_EVEBLFcZ4SRBNk0ypZvEeUVK_ondZFWQl-Xa_zl67lLPrGUPSftQd1ywY1vUplRCKUnz_MNMl84se
ZzUVZnnreZSVEKUbjOysPDI_YZHpp_lUwackSOV8VNJHhjvSUTo7dIl6ZUA-WDBD6QF1NCM8qGG0000WPhjHWbYPkrrMV30sTVl9pyRZ7x3og_jBY6VQLMpz
P-xFRZ9XxSzkhMH-UekNPLC-yIhCyHFaT_ygO5tOA5TfhctjhFdXC-TJQ_ULarDORtXVddbb-8Xtd38IUU6l7jPBBlfvuI8Y6vxsci_OSyvQlzW_lOo8mYk-
-tXIrdlkDlFwoKNgPJnTh-naPwTgzujKxyCdcL-lfzuSwfazzSmUPkyBp9vwEv-sBzHJxqtKKqyzzTHJJptKKqyzzTHJZ_LAS_n_00000000000000000000
000000000000000007u1
}

