sprite $Central [93x93/16z] {
xTC7gkj858JXElcKzh_V6oIupWRKFVDIVyuk-1s5KSkoBCkoo1nu9Cb9sd57EL7UnPkbcCD9ktkYCCrzBEcOHaXSAnhc-R_YAxxYAnuEm2CKyEFY4NOiet4Z
1UWkEkX0n_wWzcKqdjb7iked7iW6Aje7uxHee3kltZcR3g56ZSLjoze4tLtuYQTcmxyMob2yEeA13gMX2qf79uB7uYDneGFPw41Gb6G1JJA4jYy3SSXn9JZk
wdv7v6TPX__akFnym_kT_Vv-VVrxd8mNsIYI4aoWBVd5dMG0S2OWr5FnR86Y2a2GYZQW2t1AR09q4P3jN9on3nsEgAeZdaTypmhjVDoF8HDHGlk9RwG1GQqw
7U_SXmGGXMnUtZaTQ7wHit7VCXBL-pi7kFt4OHJzhj9bgumJSLYcmIC2we250cw01k2c0S1TuikVT8Ik-8glkDp5WubfZ8rhIWOcqRvl1TarHPEDEzQS9GKF
nAPGmMz2_GN3iEHBhUFjZEUQBQC7c-6LecE4i_2IiGRZWPTqEDxrKW_7tncCYxsb-Ciiox9y0W
}

