sprite $RAP_3 [93x93/16z] {
xTU7Rkim38LXaeVp_HyuovLIGF2zienYwklA_Bte52QwRzksRTksRTisPgQ_ulMI4MuAELyE2zGy8ZD1i-8TplhAp70tCtqnC_V8hA-i4fgZ5NtDsghL8FkM
4H7AQKwMq8X5y4Das5ELD8KhwBAiFunxoS9kcMG5ce9AkafBfqSHT17A5buvIShlnlbbOWeMuYmu2DEeyavStbKcvlSD6kIT-E-YGCPuhSS1fYy6nWdZrRYq
TgiFw-xByR4buE7yNumBnjV8ylbl9wNpvUbgdC4jAJ8yTa3fMbn0dRGRGzpknbdEud8dtWYVnNrrd_TRt9hjHiEhSGBtUB-5YO_5rL74xVWuY-UFBCS9E7sW
gLoDSulrDj-9ZtKUxgp7nxhmSKjQUpa-4ZH2DCfQYpSiRqnqDtxD_VYEwp28Tbm6PRYft8bxWNw1PnsoVeJoObmggHF_L1EfI4rAAuzF7oid4MTfJtywbXgK
a7SyD0Lfdrs48JxHzdRJtsKaWfY4IDfNQ5X4LSZ5ZrpjRMGbbDcO1O2gGby0Y1f04lKTAvwCer-ZftjadJYkiWFS_a7FniMY9Jx3fuhVzBYkRYzn1R8m5JVB
UWbNOVed5krhuJI1gmtQBF4g4veYfjxEaYdm2hh0VdOby_zso-UC2gOhM3tx0NKpLNIgPjy3chCREHwkVuwYcmhJJSmYWav4cEdlRTls1
}

