sprite $RAP_108 [93x93/16z] {
xPW7Skqe44Ll4A7tl-6froeL9UF1OdBG-T_s2t209Wj_8IylBoylBoyl5DP8lqDkvX-vrDRwIMkr7E8fz--KrxX8Trmq_JwvBA3rLW-B7C7oKLeFWpRn6_67
PSFy6-qgu0SiEBytTZaYbDaXGBnUuEiBmD6uxNOw1QTS-SBVlMZHiOEptdmW5u0Q3HlqC2uMSkAaXNU2Kc7XXByY9v7GLFITYdCU6D3bD6xaH3CUmcXfco5c
IC9HdtTdoSctCOsVnwM4iKaFFAG6iKaBRgIaRJrTW80Q-drjb6nR_7xm6i-8ZXdPbh80VYS_dihRj9no18coxcNw762Fu3nexmCpxNVqLAwKtnPp-rxMiFF3
bMVDg0Nr0IVor054SYLZjESJTDwd1tDJDkHJpojDw_AYRyZf3yA7_4C16O0pMDTNoPRSk66UVKXHC8PycdXxyX422Y8CILEeTkLqmbbE3RcSRCflN7AApZ9-
TrYOVErGGhSEPR8bFwxPmP-6efAzeRWvYLA-CqD9yZwBvk96CaRRMLlyOLgexkz7iWrvHJBPXd6HPtizdpUBkRNxEz50jaJAlhcziHCjUfxoQeC-VkS9Pptn
_hnpImdjdBX8uWaacVNPEIkIU4RAU_nPfrnld7BdwJOk61H0J6oSpz53k46Egn4zwsjuxqva9EcaRdBd2qntejtRd1PoJSaVeJW3m_JCydjyQjJD6NTkHp_8
HO1jOwYKtazxqnmM2jHuaPCYrxdU_BEwHYO6r2BwGInnZMmYs2EYO8aZUhc4RX7Hwo5YXd9fCP93DQ9puMPMOw3I8-cjrbAEfEJpheWisVTMzsKtbhc6-SXf
ejLYpdD9lsLLfkGBYNktu_KImKGdYuTJBRIScQssf2Vn4prfIUth0SysPUoPxokZ_1w3HYoXc6079YB-9RoylFm2
}

