sprite $RAP_3 [96x96/16z] {
xTY7SeKu38LXwQYUzt_XXJIMU9Z1bsIhl_J2JzDrYYpBiYpBiYpBigZy8XGtNPdX1iWrm3opkZlaDcrsDNdehioC2Dz5HBv5-MSXToLJTWhp64FdtNwS8KYv
2MmPA63sVkpkRWRezuE2tECCcHVqYU-SPxUFobWo3qovgUaoJLapDtZUn4P5oBIct9KqcLRKfts5RQ0N6-5PN_VsPdzpOwF9lXu7hZ3JkOVDs1_pEdnquem7
VRFnupDxqiVturN3qC-N-thaBp-51tsO30p30Z7T7rkgb_jap_R7Qw6g63xvS_tDTPzyq1_U7VlzlB-pd-_BST0ANFMB-WFpSpspHVpc_4k-tXzZ0jEv_lpw
CsxrPFtKSzxaUN_SmPW_nAE-m4o_wf0VxulQ5nKPEVtfxm-AZGxrP_tHR_TN7_8TFF9DkEd3VlDSi6oUTBg-tZVMASvTLbj7XpFPt9I_-0kYDkqugDvJT4gK
jBU1HibgRkALno-QAH-ioGw2I36NG40JARbhaZu_5VMLroIhN5jDpg0P6KYoCRl-Du-3Py0zCgkwUUYkgipmQ3AE0zFxVNYIv-IX-zimOUAlmgOWFWALuORn
i8x_JbJpJJSPSaTzZ5-OoYtmugP3Ra6pIPSP826tGPAiWDm3Jx9aYXKtdNbS_eiRqDoqooorg3wDJtwggkQNIbTv5UnZ_7dMLJdCrd_AiYn_
}

