sprite $RAP_109 [91x91/16z] {
xTW7SiCe60NWLsZ__I-y5XvDY8UmiBteSnVmWeiemH_YyNWy7e_7WvATKh8buez1vz9QV6Wr9-7tI3Mwrch9EQUKSiwbrXPTpSHlmdA5bcpD2frAkzADSpcY
PM65gKLKuWnRj0I0mw7x5OVdhX4-JIwaG4E4T5qDc11fe5ybG4Y7sJKoi15D0OuWjgMeUDCYcXngxsf12jqY-er43M6Jem13RNACXW6EXRt-fXB2b30NiVzv
0BQnWpPxN_P4mvaSnXP6mHb7mXP51hptYSWsUulVqmVgmdbd2hQayBnxKh-VVOJru4lnzn1Pl9-PkD7kBwCT_Apv0jp6E6ZCVbThsz44E6RR06RPlAC3MseG
y8L3r4WUlW4JgDlH-Cx2-aZlpOuMapwk3vNTw0R07IuI0FBzX280-klpCC-YH-w90aLHwAdcRAmyZoO02YByHqIxqsSqf27Q7Nz7h_MEfYY0-hszLlVrDOBz
oVt2muXryZN66DrpFcap-loKeVdRJfawZY7h4vsNtkHWUD9bEl2DV-h-G5eShXNMW-gejOEfW2-OJ0MKX-IxMcn6fyai0_O3cXqb6FLldtOL6I297IHxY-qb
pk4wn97-zeKPMW2Ii8FIoNAoX6UVDVlr4m_E64oNuhht1zIY_jc60oHec5_H1ZZskePFjab3j2RHvbTqYdgukUka7wD5T8hGuPOKWB6EDd2q9LLspsw6i8uM
L7joIiIloYrwXr4Ysj20k7tiq9i0j8XgBFaADZhLY6ZPn0oLUtd2XVaAnu8YCj7T3Iwrv6I9dPnogRsW5GrjwpAxHC9tTAuj9cf9n7Srl9vm9tfFStdBELd4
X2FlpOhdqcfeTRJxVrTTVMalyQ5TwilzHdgh22u7tgdsAQOILfXig-CRVi8tNMmd4_z4ZyVZ5m
}

