sprite $RAP_155 [91x91/16z] {
xTO5pjum48JXcTaOzluNhgnQSZ46RV7t-p7a2GC-MBVRK_ozyk0eLVTQtcf_4FQZUoRUOtO_i8kdbMNc1RjfSPZYXitIuY3c2PlbnOL8B_iq_n7wqfU-zANP
GZnDsUV4O5hTP7iJIilqrViuMaQCQ8gYXppiABfB8raCFQ2HAOGU3WcGOsm1T1EDa0JsRJ26PgCfGlsrVnT5WmIRIocEHgS1iB4MIJUGVLdhwsKTl_59CJID
-3eQ__gz4Upsa1buvDDNiaAFrsDh6t883PgPIChCY4Xwd1p5l-jYuTANllIbBwr5EcEpnv_5_oLiHgzOgRgmMrvQYCKpzYjU7_4jFTKhJie-B-CifbpUoadu
0ALoKZfTUI4hb5vvKd4kq3XfWKRniyhIQgm7PNp4RhVR9m
}

