sprite $RAP_155 [91x91/16z] {
xC610000082W_QaNgG800000000000000000083PiQzR2u8G1g1W2TdqN_3BuURliU1qiFAIPYQS8rvRYIAfav0iP3osSQbF9Tx6jb3iiwaGVnQeFf-8-BAo
r2QO4R6Wzg7AJOng9s8CbsmtmZR5E-8fj9dTIFKD5ZxaCG0K-uPgQ-pqUnMbhRDFAPDJzJUqpOnzWOWFDg4fOvuij-a03J-g8Ri-0uvUGLA6ao5hSciq_NZs
7yujCi5qPyBK8XDSHp2dxXu8B-XVmj0Y2pSrSj5F6l-fqCIb4Vshh5i41lP5mNhRvS3NHPfFuXZ3lBDWNcT4_ygmfBcHQHkxsooey8HnaT4sieqCzfqTx-pT
YMw4DXG5KDvpb___usfIkenCEh4kX8bwRg9j5e_4uPdD66G_8_KxilSBCcJ8a253XWmPCcJ8a253XWmPCcJ8a253XWmPCcJ8a253XWmPCcJ8a253XWmPCcJ8
a253XWmPCcJ8a253XWmPCcJ8a253XWmPCcJ8a253XWmPCcJ8a253XWmPCcJ8a253XWmPCcJ8a253XWmPCcJ8a253XWmPCcJ8a253Xgpw8-CZ_KYzBHcowl59
kklzo93r-E-SeuRiPA_hrP1Tq25UZuOi1rjAtKo6R0aihpHaru5rTuzFqdUH8Qj3gVb0xSJU4Tcv9TRrvUrTtq26R49O0_vkCcIrNZNTUQ4XEwbJx0Nds0nP
NcEzHfsR8LjF1uTPdPaXoyMY2krl8KDMwG5MP8PiFHqNITG4ilMaOf4PibmiDxkO35cdOdigC4DsWrZG4hArL2YMco5RJ2nsR1QG8GiNylKh0BArn9Sey_QG
BQK3iHURncl8aCKRidmbG1OktpohPORihYARkyOwdmnPJmLnGvaX2uhidZ93TaEHPMi2ilkAR2wpW0nPl6JpCil9a7LGP2VskCZMQw6sqtCj6RBj_FJAse0i
xnVpr4hRoF9Ag7vaszFTuv___SMdrpggO6HvlrZF1T97TxUy6edVrv4XwtbfBvD56pDawUQcnpfPj3535cxAnZWawwu___xziTvVgstETMJ8NWxvFTmcJHpt
a26hyKZtIxBwAjcuW0pPN3mraVLobNL0Xcob3CQexPXihhAwWGpPXF5WE2Ahxkvw9kkFt4o6R3iY-oVr1BBdlSYG7KyvqDEBxqg6RFG1sQXt8aEsLO-kwcU3
7lEBzvCXcnNcr_lDo93D37tKJdqV6RAnG5RZaMF7wycGDJ9aTvnZH9Plowu_au-iNf3rqylxvslQOxoDp5NfcMoVNBXsunsa-y7M_KaRTISPigVKJdRZs0yZ
h9R8Te9JJp4YYpPcCraTuVJquhtZ68qMhgSnE5K7Sw5MJo_--D72nkGZS-SBClUNpN4N9pBtIfkH82VBsqKMJD3n_vZtm-mwUQl85bBvrYnl55aotTJxpnI7
h2wSZx6HcVKKMR24W_cWtupC3DxzOsVmDaz-8VCq2cJ1SZwvOf7TP_PTJrP2LYCpcvkfQycGRUqfWMayYnFPzMPX0yZMqzbJYiS8TZsGVV-pm3iJGvQPhHTQ
ZK1x3xBShB_QJdKiXYmnMwwq7gaOil1WU4cWnZ7oUf3bXVQwV-pfiu4OiipiDKKTVMmBWYn5czFTzKXFnPMN6B8qDTQJWI7xThJuDv7bgVwwL_oBo4vAVmsi
jZZ8Jai5FM90XYnATt-crQVz4hApKzqJLsqd1jbLgKUs2uBiPmOPCcJ8a253XWmPCcJ8a253XWmPCcJ8a253XWmPCcJ8a253XWmPCcJ8a253XWmPCcJ8a253
XWmPCcJ8a253XWmPCcJ8a253XWmPCcJ8a253XWmPCcJ8a253XWmPCcJ8a253XWmPCcJ8a253XWmPCcJ8a253XWmPCcJ8a253XWmPCcJ8a253zWUxTMB3C1I3
01HRGZRxBrmTlTi1WlXl0Y9C4dXgnLP6zye68MXRsQbiuMdYAciz52pjwsESGjwFNCghRBrVBDG3Oj3w9xa-BYxkOqRhaJLYrBncTiAx7UeOPsSXHw_jowKs
ScJ0oFJ1worv0PapcuAFefuQMQWdUiOU0Aap4yjmOzj8GxsmxHeJaMTaThBraRWGQFMohCjFR3zlB56ltcmNhgi-mwe1dCwqxCikRFI1mEdisLhNjNHpjAUn
pyu-xLp9lu04JcTEjX5kJcDskFAnBE2ujNCVEGx4C100HmG8Ilz_yEQSRhQ7gohuxj2JHNVKwgBYU4BKR15OhrrCQFavC4P4dNe7Yvy28xBc-LJcyGT6dCiu
_Wa00000niuwvXLP6sluv3zhNOwP0tDJ9djIOiqc7cEz8XmLxMUN_XSMDReT5ibM0zjpN-jTe-AxLR6lRDH54n-FuliQbsjMKqAhpBRT9rKPVUd8HARSMcJH
hSj4VtAqQwRInRlUpDXNTNeoNEiZPhTdZ6Ip1ZngM2ypIt3HGoDXMaTYobSS5JyqJdQZEsbarTptbN6q10000000000000000000000000000C0z
}

