sprite $RAP_155 [96x96/16z] {
xTW52YKn48JXaWXr_mElkuPcijhV4opyuuhlQQsDkNve3g5kvy16aPAiuHyQAubHaYmSM0agLlRfm8M2f33odBDnQCUL_iAXcV4R-ztlVlUxttrAjiGxVVeL
oQ_mGlzZbhOVxtysqxJvRF_p86W_sfU9pz1whl-nzf7Cv_eolc8zrl_O8j__GNwmJm0MO16I283c8_ttALAW08Z0XJueK38eyr8VW05Gb_ea3L87yr_OVmYG
09_RV-xl__UFt_ldd_ldp_ldVq25wzUzw-_z-uU-V-j-zxlV_UxVVpzv__rg_RNloaP5Cd5W9YXnigT_Okx4gD7EWIsKUQwVcCR_PgoYWHChPGi74XSbmayf
6mVgvw5a5oKuu9GPHrG4d6kjjPS
}

