sprite $RAP_108 [96x96/16z] {
xPVj4gCm24MvboGJtl-5Tw3PagchBUF-zFIxnICXrAXyyF3myF3myF3m08Nim94Twdq_sFgOSzfVvXoZAVwJlx-jSpZl7KszwOUgGjeSNOcFNzgOKmMQlzHH
Hov0HfJHyPfFkM05AAHCDsDCe102Yd0zvnsG247CH8rXKyEiV_swdaMndab_GtWkAYMQJKI2u3S_iC8BO1fbSUdFQevQyNjk3Jdn0n9uQ2Rq2zFWsftqn_EE
XsfX05V1F4-fKfucr9-xEa97eK0HMwHPAvHVYjGcm6OCMldpKGh2eZz9G3qzNY8t-WPid4pZWfMaZj3z84byhWNvRh42IvEcrdEpJ1xxld33tzn_gCt7dEBO
rAYqCjN9X3zYjfySLFuqtSvi2NAI8S4DVyeIrUDMbSC3c0r4FJ_rOe2wdo21pDM5z7VA42dVxGEkMIlu3xLWh2iWLFHOeBeVWQGg_6vNRdu4TJyqmAUVOEQV
ORVgatugIFoF-e31rZ_mTuYPttgM0MxKFtinoPv5KEx_Gu5k_h-EaN1E_y1hvZCkiYeStq0dTPGTvcSwgFftZZjGrNzK5ONrvO1k5KdznZHKraTg6dFv9V_z
FTn_StsFlDDUND_hfnfrVuRcilqTaaGCkdH-cEr_pGfaoG-fqgmNpfzLwkVdMiXbd5vTi33cGWDXk_eYvU1YgUU6jRo-M-RTdrTt0HbR_0vj0aj-vYVznm2H
VeNndW7Yt0_DwsML4jDcPFxD7rNaB3IdiFVN3fe8ploo_8WpDn-jTieFj6asNoMosI3VGFTC8g5ulOOphHncDXelXpez9k8HcV5QRpQs20xVtEReJGbapgIs
iNxisEBDUDqs_P2XQqwOXz4rcrA_iAQsFiPCXey81SED0sV5Frvp1O1hfMqlkZCMtMcj-MCjoboBHR-k3wRTXN85eifRdks5Ebpeny1MU6n9-Sx3myF37m
}

