sprite $RAP_3 [446x446/16z] {
xC4X0G000CCW__w1ds4UM0O000000000000000000000000000000000000000000000000000000000000000000000000000000000000009ozErbor6UY
ABxGueRo_T_t6teaw595SKsgdCavc__GRGBnimIUvz-YOj2TQpZ2zdRhUWpfQNZdgW-c5PvVrL54apJlhSPkYvct_H1ftXTuEoXdKk2L3hpt2JqTWgyMNkFf
-V5er4WlLYaK4IghfkMG--AjU_DrLPA-EEWsUBFubO-rlseqzVoqODo59dVOlA3tmJao8kkwLJ-A4vezRARUnMvV3D6BZIc-ksPwYiBbwp7rq6CCB3heQRyU
2oTtNFJGGmyzzD13xxbyFEfnO_8n-T2Rw5Nc4thj9nzwdFdGO_9nlrLXFlHY7X9wh9teCOpir6FOJ3xM4FIOVEXT3xtIeLSszCH0DiTREZdneOSUUfpjqKDl
V-F_LTD3R_nR0JtqnkVfRVNGq_X2uOVU_ccttmyzaouV4BtzTkVqBaidUiFf7VJGqt0B8_GoyVBzqCjVDAMZiFRoeUTFl4lIsg-7tffZwrDewFavCqaM7thv
U6ctGoyTB_oRQlEmqNi9G8OyUbbuYgiPVEXbuHaPVEWbuALl1BqzUFvcXDvtw8MVilZGC_5ylZ12Bm7FsrY-7dhprWEkhNhe-NZvcqFFdopvVEZbu_by2Y_q
yWzr_Xq2lVqN6Plqq4l0ixVgV-8RFSLzAMFoeUTF4fylNm-zoD9JMA7dJxtyBQENVzRpozARw2LElVrww2csyg6NTu3HGq-RzD2B53rZy-WbJJrTVJvxgnvw
_fkby_K2lLF69uKI-D3Blwn8rqFFNpYDoLT13xqZdoAYe1vwyUUl6KjdtaKdUefBpNVIGy-wdIhgeQVbZT3pzVAVXno7zArww8rNz6QKrKDFKKuFlKELzT0R
1VJGCwvrjkfnpUcngv8UZ_VEx1Nrq8jtqaDlr9fxC_pG6yNqq9j_lfbQ1jxtwg4tJbNIutqj6kVKMe_tb5sGHYzrwLJMMyhGs_zkt0Zq-1p3XLHNZyyGHUpK
Gs_iqaDl9Ef5YXvwIjGRTVNupWYXn_UrbDJZkvBGovyY-Tj5Rp-VTdyrDNfAm4EFxyOjgiVtKgFdy-tV8dh-JD7jUEZnMoZe-R_RvUFLqkCtm4PTFNv_Ryil
1mkzX8EUYXU1tYADOzg1Xrx-xFEteQrww1tBtW9wgNp9FxUFNYwVuaeoyD5Bv1joR-dZeUStF3-PxEXzlvyiS_Io-CvTe3DMJVHI-TOYO_XuwEtq6_fHHEX7
O-JPeUUduRTfxEWPVZlnqFCRHegaqClt2oFqibAg7NhvPTAXbvyoJtVevPS-xT3BBvCDlVmKsQ5NF_JoGmyzzD133ptqq4CFFVJGGmyzzD133ptqq4CFFVJG
GmyzzD133ptqvh9uCVJsWksGHCzFyrGY8NefczqcY5x-ZCitHCzlfhHXxE3DnD1B_FNEkIFqKXxjpLq9lRlnl6dq_HCGlSk7_Qpd-FDzBRVepNchNiI5RQ7t
sW6v87PHxmkF6j6RXupRPkg50LXUpmUurIuYH-ySUiPnqDof5pBuJBt-C-ypjJIzTMtqV8ERyDBqSlnc3ptNRglUcl5X3zPbZNvvzFJ1qVzKx_mNT7gWiD2B
kKfFqfkMtlgUlz8xgki8zUTVZfi-_CjARrs6Nd-yzShdv-XDzTVpyURSgNTSP4zwQqOzKC-nM-h5dST2AxtbAVXPUg_ZwQINqWTw2q1Rho_Uwi71MK_xzDOx
zXWz7q-dA_xuV6F-2-ZBwzGxfjyihEVZoNmMr4_Mxg4t_ysIIXHTx25wwoCptwQGmLTPpyTJp18P1wARdcRfz6GzpGRfaNgpKLyOOvltli-cBGRQQUxDtgr6
6WtqD5zFFxhxnnRqevbLVRrIeq-uj2bytbFHKVUPUlxSkoOcXUATKeGaFG3lh1LgDih-UkO0rNHyqLTFKjHCwc9dFZA8ydKSed4zMRT-WtJbEYsYKjHCBUpy
8JTUJg9fdOQ8NkdqgEdNRdmw3gQnNzlHIT9fVFq0dx2qTBp-h75Yu3A6Y-hvQOoanPFNnP-zZRPfVZaLtU-8mEztjNPNqR_vKdNt3BzpxxidBA55akA9pGR5
OrDnmI15IBDMak8SCTrOJFFS55-B9AdB6aaiZekGLEoCTFxl2tsweV-s1mS4000G3C3wjzO2VDi000000000000000000000000002W
}

