sprite $RAP_108 [445x445/16z] {
xC6n00000C2WV_x04wa2000000000000000000000000000000000000000000000000000000000000083PkvDr1tKO1i0BhUptVzyxJxsVUzG0Qk94sfo9
1Zl_WOw0ClWzJMiptRepz55jjiEQjNNKymGPZmSduXalXZCTptXnEz_7Cruy73cUyK8V1Pxnuejv4CzuCIEFu1al9kK-dl72UCORprqyuyK9UCRBpoB2Crtb
TnNhlcLPMmrekNgA29jGaDJs6jjnlHIcj4jSqpFUd50xwt4xk3ZZtGcCPppZDIhEUdrhivvhMpNycN0k45vRnBbs4HkqSQnTxD36QNRy4oDlZkyeVWJv6ncL
h0I_XxLn95q4EwRZd--B7-cY78_U4k_nI1l6Gwtr-QBvpAAqaKFe2Zm0-0WFq_7UlbjriXtG20zLByVXPIcq21wfxJIzgEqQuXsaHtfjY7UUtZkxXdZ7wRtj
inyUwUeakzPukIiUwP7CNGEyK_JUTDZqIVfHUhp19dYykRFi-kFbENW3f_cQZvVZfpZOtuvdFjv03i7BNdZMU_C-0hhYaJU83h3hZuU_i_EczyuEM1blz5XU
uzKpbCtmOa-x0ey5oE_WlRhaA5uQZqIBT_tSl5lgrIrTiECYUZpZyTdYUz6dyP9KG--HjzKJDZIEL_pWZ_7FQgWG6V_4D8_nCZLwnVVq8IJ1czAi3mYgyNpu
a_5uTiV3IyHwNpjYTdEykcbaot2yC5u3kmQRdl6CPxpETfdRtkVnExt-UDdQZhInAzxMsHilJybNyDo9MpQUyOpdJlo8nNZksNWxxaAwdZcMDx0_7j1S3rNE
m0EQww6EyHwDyOndFDQySeQ_WfVduhMw4W8RVrCyVV1JKX_ZNNVZMR1huu54m6Sy0Ps0ptXQEPcVyQHsKZtZQUdqUiRJq-dvZ8SgZzeDBdP_fNlWyIuUdCcX
KUwkarU_FnumfFSeXcQbUE2S4CQxDFSJy8ntzSOAFEFTFS9ApsUyLE0bYLuljyNBfqCcNshFOpm17T5hW6UyeK6C9xGJ36CyqeFGRhwUySPtTtezu-5jn1_g
kpuMB_qGFFmKjTtrqNZfnjFlwRYU7izu-KW4UCRJsurlUiPBnOOtNuzqxgSAn6xgeCOZqHytqWZFU7nOuorjbza7ptXyOED56xpy8fxnCXVTz8p7xOndlF6n
ZNVnzJ6P7TVZTP-2T_7O7Kp60yaHU7WCZskGNmhmZ4VcxjtV2CNFwu3nU0VtyUYqbyEnbNnIWF7oOJpcLAzKYvVRuYMP0ef7TgVba6H558_NlJiUpwWTmF7m
tr_cLJmUut6zufSbtijt-V9TIJGPptYlE3LUCZo8yBpRv7ZrzuNer_6CL_msFyR3EdZ6oyAZteK21VItyOnNP00F3V2CL-utoIYBuXcFRrhWUCO3pNfR7cZE
mCCKl9kh08zihsCylWwiXMSy_9d_Bj4KptWl8psEvxU4-CSKnl6AVId18tf-IsWmWtZ5XaVmPZn9DrvjqmxFU1KPwZj2ePtn1YQNlvEEufSDy8oNVV2Cbodv
z1YFNzlCPpzqE_wvpMGL-BNDSRq-dvWstlrZ5GG7cXXlwwE4Z5T7YOSdy7nythf7nlAwVLYpJoXWFEFvF2p6yncGZ9SYF6vdlFvd_JEUJvRgCzsY4vxnzEUO
_bRdFa4u9cpCf7JZAVJqTe0EpvUZuSEb0CzuEZrW6fxneBIxZXU-pzFh3G-q_OR7UnYmK-gHTO_f-SgLrsRT5_mLuodrn6COJwg72GCOJwIdj_DrqgVfGMfd
l741w6veFBqUD7R6cw_7RsEyww-FtTJZurnVws3rSHuUKia7IEs0C_00dLuzrbTM2EED1zUJa_6Cbnewu-KGNbwCdExwVLxkXfUqUxtVywlAdV7KaTFn64_F
bscy5TjGmXbF7ocTyVGHm1clGToryOpdnzXDtbR83k4Dx8y7TDRZ3SGkU4KZw8w7EWVZmNZ6CvvtcyOh6l43bkPuIUmwycNkZRTzZDS_ORp7uvQDPxo-ZrII
jB4LNj8dUdtfNdC67lwNpV32UEti0EEj6UF5QNXRFdBU-3vlVxmKsrLNNfFhvPvut-wcl8fbYtQDXrNmqdYVSdsCnotrtVgrlbgBurtICruiW8TluQNnVXAx
ZqSSXRtwiZJFuC5uC_1m4m_66s-fdZVE9SSRfYJlAEo9T_4yYsAyWPBADk88lCldSryB3_-cw7D3lOtnOdkyE09lwyyoxe6NPCFRVDFxUM9cut5AOhUVti0_
zHoyyGtn7BmOs24jW0UjNN-z_dYn3HxNwuHdEzBVJdYPP-e1M1Rl9yOu2o_O-pohuU7td6h7zRY87eylojiwHwy_NZ2yRVNwun6wVVMY7Hvjw5GzzCEBK-nu
lztmk5r_9wBN5Yz-ikkjMJH5ckxrF2-eNLk_eYlIz_Ali10xqduhEQ975-4Yd82BZE3n-llV6GQNgHUgz9A9S89wfC6LyEAvRXiwNZXVhhZwPF7dQj44o4Z5
ecITj72-K4kwY85bEpROjpbE5uFItVeRcOgcTjrR7AorbTurY7YV1htjyfzvjTA8M1oG5jYTxrQDCGzGNrgKMTrk_EOB8JvPKB_xXF41P8BpArbQxv72OY3Y
DdWU6BkL7KzSJBPOuPfuJnOLzpDh1JmhwZrTKIoSl9UryVAHT97hhoSgfuDSVprXCVtSU5R5IqrQkV4qmEils632cfNIGCruD0tCZCVI1yruF3egupd6Cvxr
ZDSOptXzzJnViL0rGMEyP_MYQ_IJfG_jACvCYnEsX7CHju6UOppRMSzuOZtRzTUpdVbCnzEw-ztjUFgrvlvuWtbYRidzsXuS2m00000CyhVUEuXg00000000
00000000000000000000008
}

