sprite $RAP_109 [434x434/16z] {
xC610000082W_QaNgG80000000000000000000000000000000000000000000000000000000000000c1qxqOqU1e40p4mOWT__XVya-kMswxMozo7xwmNf
tYWsv3OJMEaFPsLlDi4t4RbzLUL4PhNVKhw2lSI45UcIejnFAv80xF4cqAM8oF9e6I69X3t617VbgZnNPeOSThi9e2lBYwNa1Emw4rsABEyI8H5scGckpF9-
cNAxmAnM-IJXX7LCbFAETUp_j_otUlpsDJP5M6E2ebmfj7BipEhtN_KuTjJcXgBPYRaONjw2IoHXzoBfaYwT6rArWPoel6ZEzMUqtG3e7d79It2OsUHnmOG4
s9C1a8vVobmEFKjNlc4g0bsHMRh4UNwT5M-xyb3BDclMyEojFGxOkm7TxLMm4L6TbT3jOy0xfvh3HWETNmk9xxWA4xIvWQK3zedWCVhI29tRkwpwZg8bRHIC
TZM4VJXGvPH6RH7JyQLBGzW8LFuAjw_HDFp1uRQmS3Gt0KxY2kocuFstx3zx1ULOcndYSAx1ia8JrzGghXcR-2XTQjm-G__9-ximHYgOOArbmoRkfR0DQjnF
stZ5Vhhi3ZVYv305gniOG5Yrx9guJN59nVgtF7o6V-oTY_AREW_4lMiOoFi_y7TDfzaQSwB4ebX_xRaqOQXZyKEoaC7yIGm49BGhilZ0LaWakZanxQQwsOwV
a2NkQuV3RObfICQcNXOV6CjynDJbrl1UjgY5inChPGr-ASrTgZi1Y0coDNJMiI84CKMs11x4zgBYHCJOjmfX1x6TfKN6ScDYsar55dOesqupOQ1CG4owASW2
niNLC4HJgbH_YvXsf2zi8UCYTaDEXMVq-Rl4diW8asrXjDhEGw3SWbW1hCO54Son_XR4xDSjQpmNMqiqObeRGBXH3Ayht61IOcg1df51NGpr_q8nv8tknFG7
pqMn03AIHNAn7MflDUIDxiGi-M6fJp6aaorYZX0pv8tEnFG7BSJKoJP42eexxCHKRtE0SSyYiX5J9sEKr5uZ1iLSaI583Y0cOT0YgWNSOuJ5_ka70FY8FyfW
OkNJZW0ugfi6gW7lPQmqI5hlVXki9Kuz6Bk3AHeazNC_zCbdnzW_kHRNCHdDPo7MtTCrb4okzUAyLubTfoNAdN3O_awq82iP8FfVBxQ6WB-5uYR7fjM2zjIS
Mcmkdr5VnHbj4WlmPrZS46GOExQtblbKHMm6iY34rkZ4iCSeLCc5PMXYPOkHUXpCpl9LPJRrBLX3f1wKSbjiBI68BJFTC9jdfqQAy488OfiG2wvOn53YAqIT
Qlz9nDO0n934Pgq3xp-As1g0c2JtuTFxBHWniD4y1ZN2GNg_nOeJgAqu2x3Q2Z69BUTMrwbgm2eAiQb6xIIs_IB64CJYHyKoFp4SJXdHE_F0gxmp3vP8FdQz
2I19TL-ImCKrkML-OhY6Lks9nBrco98OMFz9Rq1BObAakjgxx9wMn7YD1LrSBbbf4lFdfU8LHJaaiG6y_9d1brY4t0di35U_H1fo46zYESK77h4wsAtbHkTC
QtfYr2Du80m0HfZsDOj7mc6DXv68OT3WWWQ13J063PaGWoCIOptMLyUFi3ibYqrlv37J-zZkHumjBpCpZY4MnSVqbilHKP4TNZPcpAXuHkmyy_W2s1VXb2Cp
Z_xTL7bRCpiEPdSp-fSCafW26zL05XRrgVLx0TCcqiUyppYsWxvTy46MnCwFDGOsam_zAJ4lOBT35fCOUxB5H0nZJsDghufF3BKd3W3cXOor9tI8nPbiOUrg
i5-Cn5-xOWnYMXV5A68q0RCsbyHs8JOWAaBO3f0usO2eAFUOXl6n0XxB00p3Cy-FCmzq1u9yR5s3s2sRL6AvDCHeO89iFB5SQ80I4qV7HGmdbWiD-9JRsRQQ
n3PtR_1lDedvEyFrxUfQTqbCVC73oOOqbiHyNKnRTY6Mn70viIJ64ms8NHwv1qyKYLXdUkoZ1uNGtS7VVS-xZ3Z4rW-8LVjHRTy-1v04IhED-Enig6TYG6BB
06BrgGvB7joEI7IssOWbCPo7c8ww1vMoNPk7REjZONiw6BeSdbW1ku9n6DFjxS4zsaP3o3LqES0pVqChDj1Zsl2X7dpY-QTi0pjSf7NtLOBY4-jx0Hl7mNEl
voVgDXtpMc8SJIo9yM0ZbPXw5XJJSwCViN94B8cfFxr04Y9FK4gfusGSx6D93BNZOon5YFtvfcxgje9JOXMkFfR42bcEYCbdLsBfO-OQbP7O4ysDVIo9GNUe
7n5B7yE9lYA6Bh5Ab08QYTcx6v8OwvaucDXB9iXQ3SGC_GtkOwpdud1YU6dSbddO-nkOM5-3CmyjPjc9LGEnGJwMn0hu7CeSYCNtCTHpmO6OxWm3CKD_u-QA
86cTS7cN6ANcqHAZDDAlKjdxczTZAjg9IPAX-rvSLypP5XNEQ_UlWcoxGUq-YKd5lZSxKzo8fO_rZ-aviKeA7PBaB-YMyy7VnvAOBiRNRYDSYU4HyZuFMr5H
huhEYIaUTZOP6ZTqEV2zLAnTqJQGAR6-Fr8SpE30XYv78BQCl8kRfkG0GEiXPppo3bDzKi9GfRhsIGa5WW74afX3Tc0CYaaCzKIuonD_XYv796Qw9Th_2NDx
ms1FG3wZsLETuCdr9EQmketlcR0ciREd8hnEX5pbQCSzdSpkOhcIcB-J-IzsbQlrUHrT_xCWVQn_UBrTB7tCS_rA_mRJnt0iWvDLNB7ehAtNUf8oo2l-pWkB
3ZxXl-0zIyJrxjVMT7zaziPozVJ5IcoaMrYy1cx4abYX0TcObf9O7nb67MY7Tj075fzOuQ5WVial7O1PPrpW_5P3V_alceiHo7ZasVaUJKYCS466preO2IpV
LMkxDC8toFjkciJyaD7bRoSnHsGLHWTp01RldUjmHKOOHZ05vaMCPKvjVWQWDioil2gy3VRNJASSgfKPM9s1bJKeCHpfeyYep72AYxNQ8wAXtu5zZ8OIbQbo
H18zN0D_JiNE6zS2JRVGK0OsnBcUg-5ufsBNQM5HYMsp4gC3CHKxhL4Uf3NmSYMMnDJD-h83Is8EuvWmi_Fo6CVu24DiKzC_cMenv85zVVr3ZT0ltUTzt5yx
6b4S58lO9iHyHPxZOh4fYVaB87a8gtTrdONW6wpv0_0tDmeiTss6EuBZBPkJ9sWIyrSIcqpO0n5RItpfCcAHBg41gZ2FWMtVmomqq7zu7RNL1CZwVGzA3ETb
nJA7pWkBIm1YCiKNbLYiKVjDOWn2J3FZC0_MCjGunj8b5kV1MZJ_pAD-tzNOl20BS4Fj75f-9B4IWTYZX1T3s8hPhCXuyfXiDCunUsypNaXPRZwf1Ptvp4Wd
7YQx4bFrBK20v5vhRJY-W2xpwVWIcW7cMjGE1YUsohavhz0CP6ZidKtKg1YiM82jCOHwq-TyWbZGEJNdrTg6Ty-28aXn1yAtlDW9_p4g0RmeOB7prLURB70K
Oo1RhygxqNxrroDE1NNrBMc3V9yO2VS2AWCLI1UllErTOfASUWtNaIOXDdY5GTjN_zWV9blak4ZuFJ4I7g6VeUQDre6Hy7DY3caazYQEnBY8Vc1SbOZV4UFG
4jaQA5FKF6gJwGfOmY2A4giV4vCsv1SC4Wlm2585RYV97fJI8YnX49x4O4mZAHQ8YqLpCaXbqHG6tOZfL_jRoxXBs0_cPEl7nEfTYQcBXNEodV86vWc9QLGK
uoIr3vCkRhyD9gObXgS5adQ4kYbpQSn2WI4vT2HcJnt50Ao14aMzOh6K5o57-ZfY-ljsmy98OySEGnYybfX-DGQFhSJI8iXY45Eh675vagSs1266FMRQqLgt
8m2neC2qXg_8-ldXlzcx3-JMUHW8mDmTx02u_u7_NYmyIeeyiWoNprDUJSBPY06hkoIsNJSoIeFUZkN_7FFwi5LYstMZvGsETmJb3PlsX9qIs-mXKG9xKyeR
mWidXcLJnlYGo5usCOiIs8T4blQQYK7v2O7D6yiNJCpYJGC39HUsdxBKubmP-oN6iYv4vLPWbEnLurgf2Q5Sql-xczXnFCRRmE2v49mCqKB4oyKLkRv9rh8G
VZ3dmKVkfU8yiOgA6jZA94Y8usL07jjZ5KOkHScCauXGVhl-LsFbjwZZulfNvVFlvfMEzU_5S66y0D2pu7HQk79Y6HatVukRnM0i9axARxdoM-nyXXeOpBFI
A5GRPHYzqIApufYmoCgDeolJxEiTsudrpmoAdC3gwaiLFTi7UVvAc4yrLY4q7sbLDbPOv8GRCFe0DFyoEMOYPrfc1lESSJkSSRWHJHgbo9cmxNNR_i_P_2lT
7vTGEUTwUcYKHyu9kmERIXojs3okWp_xAXc0SJs0YbmJ6Zlc_rkz0mlP-24grxdhsYuID7dagX3khIs5fe4TBscXt18X6I-Q1ut83GS6nR1e-vJP7RrXPHwv
Hp8ye9i404gHEuut38gMaV6-PbMKvm-uoym0d18LpUGUkIzakATHqJ2oEAia0fK_514k5uqOnv56kNj4vC-uuPHPXR3c6wIEWoBoCDUV35lqbyZ3mksyWKzW
NE3YJPOqUJOHfumBrQfVj4SSxG2aV3eNWN46Hf-738-xUWHMQkthHBZue9x8tl9cjpgUlP9BHZI_XUQuA--116XINY0a4XYdwdQBCAyxxaPJASXF4X7kPYql
1dtzzr40QPAxvmd2NRfetXBUBJ4R5m90qYJfpjvF8WbWNEQZ4wjWV_5DiZznF8jQzefV_PynAvN7L_TdZALe_UfUUQ0KhLzx4rM1Jc_oyTL_13rq-OGPJdNz
NScTxk4xFmoQLV8vHMw8ZQA_8efJ9--jrVeOnWxQuYLttRpSeyYdYCArV8cBLd3iKNHQqbITIzKjpu_ZkbNNPzNfyg9zNu5kUwcsVLcdmdNVbyRuHlODx66H
VGcZ3NfU9jRuXbYHrmdhVw3sEA-aohW2OmFNw5TUH9uWXEQ7DET2Irm2gl44g7PIVhcywkOPMnYV1dLEJSRVsuDZ0W00009Wz2yjXMzRymK0000000000000
00000000000003
}

