sprite $RAP_109 [96x96/16z] {
xTZfVeCu30JmcH6sfVT_uGL3wb_ZXQ1Dznl_jZdLyS4DhZqUZyVZyNWyIEBFoKfjpUE7Uwjb4V4rBjL7x65yq8hm1MknQRMO20oKbhgFo2l_QxflsGjnJgNN
4CXh4RxW8zQ8M9153pS050IGW8v7Z5z2MDM8WYIFrWEeun462JJ0ZaU8nwFI3RHek9iFG152WeNZmCjyOhU4vsPdWOITS9w_4-5Xk4tX00aCl_C540E19Hfk
Ar5nGZWHaLcw1faHz_JI5afCFv5L4njP1DAMn2OGtWTjkZiz1bXKtCHe9uSIRQRo5Q1ekEMqLFQYaqxTr8TAhQPP6AyEep0yiQYcV9cTlCddbtbLqDkScE6T
n_tyvJNRKzxq0MsJogzX0BWPQIS36dKjY7lcJVq8kvoX5ihaKniUdSNazPcwP3v_vviTWTfU7Uk_wPlyUNgqHKCGO2D_gCbyTXXHU_vcv8-oRBvsdF8XZ7ne
by-VrvMURptps_aHvkKBZR_DjFuaytVeBjPFTgdyUQGsDs0wdTNy_a5srkAeys1c_qPjfhZt1aUTnpU7QZFDxuP4_icXsiOGjCLFmbF7NzcARmT8hMo5uLN8
PFxv0LwfVvgDhcGewlztVgNS-Pj7vbATgsEbJXyWS-VSTzKewVDp3-BR5GW2T779yyK50CVLKN_rRqE-hqI3X6wwkeFK7uaN4oE810yZEbxb_zIqgCYm2A4J
p_Cfx6euSahiE-bF-NqKBPouJRNi3JI1d_89B1uke1JXXkAn3rOUqHPyeAs-OULtxkTO3-LeAbeHhs-UDM73tZFXYdhrT8FC-nqo4UFkM6aU6o_23trQ46tU
IdGapTphmcapQxZWSNc7yd1nTvBXVtTZ89zVeudaSPXTbgMiwaixr9UoMekE0pDN7xPZUdp9YIkithhHlQD_RsorZ06stTsRhO_7u_4F
}

