sprite $3_party_firewall [446x446/16z] {
xTs7Ykmu40LGKr0K2Ft_xswUPhR3YtRfjTuvfCrzfw_BcWLBFhO000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000095NYjK1zgvkp8jziS2uFi38EBOKDMQ3YjS1PbE0_UIOJUf5WDabZyr4pZuZpXmyunSrErMi3x2H
d1z6nLMoNazVVVwzuYhrwLDsBA-YQN6jvm56HTDlrNdi8iPj8jfkqN5y4dqtjAY6dxLLTlv0-QIeQboDuYF0DgFNMDwjgbWL8COjm0wozrOIu_xQhqK16dGD
GtNVgEFksypk0CSMscyaTsr5-wyH6zqwe_r_WEfPUzKVO9zbhzglbrptNQRsJfls_kyoj7ToU_6MxMclj7TZzhIdFUsvSvezxMbFU-wSsZDxsjEUEwVsp9xs
jEVEgJspfptjkNDgp-nfJtlQS-SqUzhJdlRSESsUzZoDgxtEJppXINZx68xvZzMxKCRHP-pJNin_HFTUtLWNOAVzUzLxXCdZLjcn9i1nR3HykMpZSVOENtRz
l1jkmu-nvDI1xa_hF_4Z6ykh9yT8Z6WCaCSkRWS8nPg3VM9qNJzn5s07qNFuwAUJod9HW37_4yS-OjwC2xq-eZDRFdziUaHdpauLwmCu6lS7PQmDyEFBgmDM
HwmFiA4OYw_xR0gmgSWQOrvcZCeulY2YQiphZCgCOrznhJS8q0K00000000Yg-PLiZ8M1uXl2J3cHKPLHCFJajVbprWS8DQ-xNzKNFMWQOVAnKyrZMXuBAVv
QS8Oiqkj3f2hdqYDXl9QBxvS721oDgfeAAylV3O7EExLR5MNb3Vok4pKUFMk-PZD0UfbWBemGDRyaEUNLz7rk7ok2H2t0F6ylEpw1aOqR9xiUTVymr_itlyt
sWB4Hu2ATzoudF-5xzrA_7ZzPCFR_Xk-xkPDz54FuMz_fNNR-V80P_x7AexMyFdu5vh4N1BWcYCkudOfjeOVztyUtUVBh0jmujMIdQFtUBdS0XpT0TQTEfRd
t3hxip-Ufndj0M8y2n2T0KuRzlxijq_y562q1nZn_-_oUEFsZYQFvsd6gW3n8qSCQY-UpTvxjcVsthuzizT_-OpLxSrtdhqmUzQzJxHdtTEUTS-wP_QiUzgp
xcdFkcVTCtlMFUrPzyoUTS-wP_QiUzgpxbdth7lMFRDdtTEUTS-wPzspxiLsinVzJyAlVfXxWsUfrxzhFXQqjy4-XiLRUEvchp_0NPdP7k0jz-_Lhxb_hxe3
v0MlB_yTzyxEDG4ssRVUEdpn-76ZDy1_7tVkVstTcH5pmPaHzIHJyw4LvwZPDdstpufLBxl_qdajrHhWx1DeAhhUJPlF0sIqd7Np661s1SXn-gZ4m-cdLuYi
yUASicmACBuXG4H3TpDFNOnQZLWTu5WVu5th6x5tWFxZSNCiZfvZxSlsepN0kxxiVlpsvrAFkEZmqORkuXSEa0q1hlkrB2BhiXzWL6N4rmBKTG5gVO0l_q8B
0000000000000000000000000000000000000000000000000000000000000000003m9m
}

