sprite $3_party_firewall [96x96/16z] {
xTG5Za0n28JXdrHecVkVTptsoYRhoXVl97NWDokbb59AAQMKKafB60yiprwZXJBRWA6Kyt8cDquM6ve6YQR9YuqWPJAsa-hYnUOcfquCKlQdvw_vctYnBdjs
t8FK35vkn-YdgGcctHEkpYlCq2a6W2qbTkCzIflhD8rxmzV11_SipJfNhksdK0D2oqyA0rFuQMaTrT78k626aR1O48kCgR-iOar6359T3t7ArsL-9oSZEgcM
p9_lz_Fdzy_U_w-U__F_JrCdum4pdyJ28VRB_ZzJUvr23TXfzbI_MgUjbVGVFmtZNa-oERXd8yiQdw2KKaeffTm2
}

