sprite $aruba_firewall [93x93/16z] {
xTs7bgqs30LGP2_v__yuFN4ACsaWFPYzLqjzdEk3fcBVumK0000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000008CQDeZl0U7LrkMusu_C0SzqitrhWo5KWHty0S_VVPLJEtNc0bubL9wFdxjd2v5swUh5AZNTENiuuRX8p
z_HzN5v9W3LUMDwCeX7F-F2Vtsk-xtFVh7f5kwSy3J3A0pnVLBwUo9DFVQLVJEIxFdREFNazzyeiB6_VAySxh9_CeyZONVK4Y1tW-KRrhPX_-iWLrP-8Pi7T
KhoOrRTBzWM87U3noZyBH9wr5-K1uZLVSMRzj9-KMVkXyptjpVhsOWVGdlQqfptjQKzxsjEUzhIdFUrfJtlQqvxsjASzxMbFUzhJdlQqfptjQKzxsjEUzhId
FUrfJtlQqvxsjAUzSjrFmX_P4o33BfJ_89PTA1TFmcpRFhV_lduBslD5x-xBlPds0Pk5xNpUs-HR0wmuthJrUTPUhJj07kyGMRXwu-p4XiO0ppTNsUhDqvEc
HcE0vylrinnnt2X6xffw0-Jn8hb-bJTQlucU0Ba3EE7nFpkzV_ux1tJELMP6Su2Cusrczycc8yi2_4Vwczq1ydYhCJFNRJBdYFu0hnQtUK20GW000000011p
hhlCERvuWDm1hZVckjiSqVjaqnn7Ru0SKV1Uz_NlDHzV9S1yy1DXAzi3H7E05GKFqvQkNdk0kGf5GNc5gvUhL1IKL_P8QAwAJHnZN-RZ0FEe2B2YFS3ptW4-
vgxlBC3i3f1nt6m7kCWeVC0xzhLE_c7NJj78-XMOnpNswwaBdqtxmFVgdGGOHucyykL6ONdxSgCxm3oshW3rRnv-_VN6_fHJ622xtZ1-l-0dlbrwxBNgEUee
_dp1zPDH7k2H1rMTBrxvJhNH7k2oCPv7WVChnXSBiAzutNrGdNrVSJG5sEqr1SZBRiGu2kt5sm6ElW1Hlm9vxUpLBzxwqkrTE7llRy_iQS_iQS_icRt-zioU
ZvncJtjcJtjcp-oPFREdFREdFRDdzioUsTEUsTEUsJDxsZDxsZDxPi_icJtjcRsIvpdDtcXipxFKZtaIVjVLjv4YdhwFeNyFKVyMdgideNxBvDwGrRr_RtJl
tulwFN0NoDwzitilgxsp5smaBzgttXrWzcsSpojlrsmuCI7Zx1254kjdqNPenRKlTwxUqqhsFonSkzbzO4mU5ycgeugESS5PIGyFiCkxkhwyCtt4_EqwyM60
SMU2cNzxJbbLW75S9bQjQ3waS8tkGmhdSQ6eBg-tlj4TO3xspUup-WESAGrmjTbzsurL8zi3n4sVKk_s-PT5xG56OO3hnPWpRuizHtpx0MBEkMuovupF4m00
000000000000000000000000000000000000000000000000000000000000000007mF
}

