sprite $aruba_firewall [93x93/16z] {
xTG5ZWL128HXe83xttWrEWqjgq_gYy-VL8nfUNX4H4H4H4H4XeBsIGv4O1IfRGgLNOZsitkNTeL9ARLBcZyndjgaMnxdEBgJ-85hiQmcD5m4eMM2R4DMV96s
wMWZFSShQvz5JzELPVWWFgu6nqclTshrJMgVFdC1kVSUEmJU_iQEhJySte-ZIJSypd4BASLFN8ic3kySAMsAOIOAQVE4CXLFlXNwf8jqHuY8Y8XU0G
}

