sprite $big_box_retail [96x96/16z] {
xT873eGm34JHLDjp_milPQiHVLkaUPAi5ZwG93I0Y8Y8Y8Y8AAPbCPoZM76sRtc9dk-79GBs1rcT-Eb-M_iJi_FcVeMJthm_oMdiVXPpthm_MPm_kfzHCM-j
Fyzo62bamY03M-i_bdk6C3AT_t5TwYylAuWR-bXslb-Nw7B_NVl3VlJUsi-OiFZ6lbhjA6IOjOVwphwE3wJ7OutrKwSYtsTwRnyJx-rRwGZgVPQNFiytTohA
C7ElhVFLt17KOPRSQVbyURxdlx_zyws8jvQfPz01y9W6SrFnM3O1kxz9Fq5Ic4T4T04
}

