sprite $big_box_retail [93x93/16z] {
xTK5YWL134NHqYHl_nkUah7Vxfe3X62NfgtCyoYbb59AAQMKSc6GDsimXgsBinb0RuzRzsdJEEDJsFFAxtFFIJxvBUC-VdAtkIq-VB8tkEUhRqkaFZ8IfrxE
L0nfWHGOYKi1I9kf44sJXvrnMq1zWU4uU83qnzsaE0qOZczqMxQFQpoYITncSU6GYEI9kjDsyVYt8vJzBd7oYKYUgFk6SRHi62UNYEI9cAS-q4Gu9Y9vekmt
UA03jqNZGWbGPjstZ7C2b5dt5znpaT14IADvGDIToivvCa81RWT-uawmlMXUJ2dr1G
}

