sprite $big_box_retail [446x446/16z] {
xC6n00000C2WV_x04wa20000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0000WDcxRoo7GYY8Wd7lVyCAvJtDTtNZCHng78-Hj9sonh1yXOUF7ZvuztgYHuyUFNhqjBhTEhOUFNhqwD6Z9thqwD6ZHq_qwD6ZHuyUFNhqwD4JFNePrsGz
UXdQXtgYHo-3eqTFzEWDmAFdhnPwRJ-dTRCMqIj6J_JeqQD7ZvwSzynQtCwQSz9pnq2F7ZrwVk_9_HwzaNnE36OjeaUF7ZrwzEZHeqUFdinQw8KUFNSCz4IF
7Zr_SzBp_vphpsbTzEZHeqUFdXV1inSN5TTBhrzpjVJwqTkoNhQyM7h5jTBhHs_BUbdvKkdHerVTYFtDMgPiMyfuz2hjM8yUFNhqwAqjUlJe_HazUlJeqQD7
ZnuzUaxhzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwAJH7ZruwpT2ZbrfrFNefLjQZ5thqdZHEZzv0F7hqwD6Zz_ezl_xCzEZHeqUF7Zrw
zEZHeqUF7ZrwzEZHeqUF7ZqtH6w8wD6ZHuyUFNhqwD6ZHuyUFRCMUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZvuR8dhqwD6ZHuyUFNhqwD6ZHu-UMGizUlJe
qQD7ZnuzUlJeqQD7ZnuzUlJeqQD7pmtHHlJeqQD7ZnuzUlJeqQD7ZnuzinPwzEZHeqUF7ZrwzEZHeqUF7hsiKezUdw-lbsFfvGkzrQPJUtHG10000a7eV_q3
csD7g41vZtNxsB9zBBp7qdtomd_ked_iAm00000000000000000000000000000E
}

