sprite $brand_office [446x446/16z] {
xTn9ZYCv343H40Y8uFqFt5srodaCsIo5tqjxAoVmGTFpyHa0000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000083HuZYFCMUscFDiG2AhJnnd4FL4Fl7kbO-HrMqS3OnUz_0ngrqUlqHLlmFrjgMUUddFlwNrr9l7NKtr
r6kd7khrK0_rzg0UwgcdddgejnNrc5trOk4D-sH4ZguFrCJnMqGsVJPeh8hdazGn6cuuCdEUZSSOHulnrGq3000m8c8-a8WOnqN4p7euEUCQSrSFQWxVmTjO
nkwJD-kHXSdRM0vVFEzX-EhX6RqMXY-BdUyu6LUuuynOONvmuCg3AqxBUX8Ng9TZzOdpPh-fjUAqVUkfTynxrbClr3DxwgdNIZtrx3trp9vwwgcddhsddjbJ
JptrrBFtp9vwwgcdddhsdjbJJptrr5FFtZDxwgcdddhgXNfcJptrLb9FlHWhF3znh1JrP9ntiNgLIzII4sz_S5sY7khrK0_rUgY7UZtKGxqUwg5UC_Ko_Xfd
B_F5YUFfoDENUdB-uF0UW_SOr5DFFVLyhcKZPayzzTHJpzvJp-offvvwwjbxwfazzTHJJprxJpspfvvwwgbdxwbdzjHJJptrx3trp9vwwgcddhsddjbJJxsA
5Lv-0sobnVzgNg8UwlLG3_Lwg8TwFTH3lHxgeLutzJ9ddh_cuXEVhlLamN6NgUSN_JVZFGRrr5FFU-jcJptr_Z7ggMVlgMVsr5DFFVNiFVNCddhggQUUlQUU
sLDFFVNKi_VCddhggQUUUlQUsLDFFVNKKq-zc5ahCUyMUSpQbNuZwmR8s3aUiV4NOfd7pTNDC8pUnmpVh9iXTxxZHBsFgPVLGJsFMZng6NKpnE51fz7hUgNC
wDbyudqiPktBEtnZVJ_jnh4A0000000000000000000000000000000000000FmF
}

