sprite $brand_office [96x96/16z] {
xTC5jiCm44DH7yD8sl-2FqCzPORebWslb9JzpCpCpCpCpCpQ6ADllFQBvBLTNA0_H03SSALuaJxAPlqf-bsnzPz1kO1sxCpzWST3BuUYJj8EFwD6dr3i2V8G
5OVtqmWKUm_RSF-N-m3Y_nOK4VDO7WAFw9_ac7xCACQ-ePkTN-wxFsOKHu8yz53d5sUIcEKX-VZvudw_Jh_fKg9iGbrCktA_R8HBQULCPcRs3W
}

