sprite $cloud_outline [93x93/16z] {
xTG7ZiH024HHglxzpxn1oTb8c9rDl8bqHi8TVzSOOumnnXXZ31cm3gq6R4MT0Epz-WBy2L0KULbIuENlqkpYyW9jm-LtnQYojdSji6kkhuwFJInhLrQN3RO2
uWXEcqsabZ80q7b_ccLU7RBZZ2wQYOnH5AKpXQBApikZJEIfbGciPFCwtTqpaebd18uJ1a3na75oGprXbEvNPuwtNn-y3nkPfkSoBsWxMg5Tq0c_Q74HlT0B
5jy7_QM8enF-kZetXxZDyQJGjxPZ3nGTZ4zRiU8HoPTdDBSK8JAAQxfsw3-A3cECCSPu1m
}

