sprite $cloud_outline [96x96/16z] {
xTL7biD030DHlghxttbMpgQ3Mfna_8qoqChrbqH4H4H4H4G0qAvVX0TqwrbAXzFinVgpektnN2mTWWxf5ullK-xsQJEEz-3z4vAgfG9eZy7IPYplFI_DaBgx
gTMxVIwWEq3UMRz-dmvq8FwzEo2rGDP6i9xFyfUAaVm3w1i0hML8UsvICmKejHTiAiSAf7ObJT_C2SXeFjRURDwgaHlW7yolqNn6y-UV7nbz_h5V7lc0wb3y
WJ8GF_03w7FmCIxsQL4j7hlOer7_N4H4H7m1
}

