sprite $cloud_filled [446x446/16z] {
xTq9hkj630J0r-JzpvmzKVR8-2CQTAekGC2DfaRozlNP0000000000000000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000o0-gVv9aRbpoJUD8zT-eF3Njq3YIwdzHcPpMzK8BgRuX1nj-QXxfksfYslrvfFeLbMFJvWgeTfU1QJSAI7hq
vUpByVuvgjnN1tRcT7wokzJSjB_cHt-ZEh2Yf-DJl4icfrt7NVg86fkcVfVqAJFJBYMywdCo4zubmXjiGvyMuPqqDqryVLnDRKtnzHDcfZcxz3Ccfecl-Y4p
qouHtiFnzPCYl9DcfbqyOJbgPjf5U4SzECt9fKPVpdvUXFTGVDK3xCsZyimqyVM8rwUvz2MfhbyacTwRbtfbclAbxds8e8VKtRsfVBdzAP3gAJyExJdPtRfR
0QRdp4xhppx_vzgRC-gh9-N3Z_-PBCEypTcHpTaXl17Art_1vkAHnU5HcyDZStXaSNZKvjCccyDZyzwaDeV7vht9vkgn-RrOihXwrERguSmYFOjJUgedFOVE
BUcHxBxiKRKxFIghqwDstwkZUnRe-xh7wkwHrUcn-cwTMfqUqdkHgrz-iUpGARvKdqH9JdnlkZ6dDcT7FYyxySbEVFquDZ_9f3PlJR8vF5Q7n-RmoERms1mU
sNohmEQRTB9vRx9vRvBDUnFXAL_w7QZ5rQCsLuyihXxPN3tUKpsaHnO_8wCMLu_QV6PXy-9au-94UWwTrNj9hv4UqfFUghizik_GWlIarqXl5-aXFTpklKXw
I8-ItekaXuVKVBqZFQH7BVv46Vd_V9hJufIUpy7ZEoWi_kebMVpjFHR_n1Mr-0SZMF_xSgetNpxyI9dghIqVYtzPbVXLOtlp7RkJnVyTXN_ISD6xz2GNFV49
Rpu-_6MfvhqdFk69pzeSZu_oF_dkynOyTR4r5yHdQzgUjkQbXocUzIcxy_bH-Rh8J-_kIFKijTiVeEYiKCbTahg594UJ0m00000000000000000000000000
0000000000000000000000000Bu7
}

