sprite $cloud_outline [446x446/16z] {
xTqvSY9H44LHutkr_mMtrP6EXa9w97h1EQw09Fxjh9uOhXK0000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000030-MzdM6WSvoCxipJC7-M83biQ9zs8JLkSfzq83Llkfzo8JbDm-pYZm_GhECuPbfZ7hTEAdUUzD0B6_x8LECvl7YCn
Jxp7RXqObhc7Tl4xZPzsqE_96Nvqh-WJ5UyNzmtS8_HSjSlt2no-ViyypiTkcfidNkHH7hcTVh5uiGSAJ0lC4o-v3Ta33-ShZnT_iCUdXGQAbr_a9_-lhdZF
p1SRPllsZtFXzJ3YHVFTc1OTA5uqtyOPltkzXLyMYMdoRHzdT9fysySPdIRVzd4-E4s-CxxzY_F67uaMZhQytlsNV6qlmyrfbk_kQo1tZ_FxQVATUzOkC_VZ
kNQU-xP-cTwD9z-VV3cvUjLlvVXscdndgDUMxviuiNZvVmctVFUZt8xNV9urzHvFyaxrJcEym9KiRAPPli0BKizhpdFzJBhgXOupxwDfbkztxrgzjbc-xzjH
L-zQefvuweNQoMVprCklddm5Vof6FPTEyTJBFJlvh9vwLiy9gPS_8HTEHsJrmaSqIkkfDoh_G2NVKCyt9stNKsyq_hQdth1wyhsideZLzGHKJx-rUiYdtr_P
VltMPoR7wxSohhMUzJiZdq--xNJHuVej3EchP_tsuza-coUVMCNluYbEP_kAorc-LxIJJpols5rBH_FtaN66U9RlDUtaguvd-TuydkNhZITVynzON3kRurc-
WdRgfNSOzUIhZcVv6kFnvlKitteyr7Ff54yz0eSlddgDrBiAg1UwE-hHN0_rrBi2K4-zaWidwgbteLu5zL2FqriFzTIxK0zNpWN-cHFrnDklXthKlHuGh-PK
h__IALv9FlNoZu1wuXLSEicVV44zzVhoYPT_67nG4iT7p8aN_7X7zezyFn_7nngBLx1yhfi5-SIJptSGNLjiddo--F9L-SJp1Mw-RNqzdysJp-QDC_JhEzjp
zDizMFd4cpdXIQHFTB-VTgDsddHdPMXohcvZPVOVjl1izvwxVjfzeEKKjFjGPptnHcCzvKPZFUs6FxNadgk69PVt9G000000000000000000000000000000
0000000000000000000000000C0_
}

