sprite $cloud_filled [96x96/16z] {
xTC54WCn04BH3Dp_pFMMTISrtdZahwRyZeY8Y8Y8Y8W0Bu3UiCRtnkymDewo6LkWUczy2x038-FScPVHyGqeelp62-1cB4-CZQzz9-0wPGbk1qzUpFdtzy5z
uEeBp7t2r1PJNKeF3mLFNZmlH-2vVQdQnvVt-ULzy6Wmzyt75-RpMxhWoGjCUJ6zUm4CzSeY8YBY3
}

