sprite $computer_monitor_outline [93x93/16z] {
xTs7Zkis48RH0Oa1Xk__mEdRqXFxbrV0ERUWthBwF1JbegtR00000000000000000000000000000000000000000000000000000000OEsdODN5Tizv6hht
XKFNvydeYqOmCtPCLzpg4yBiojfpxag-piQZa_5E62sUVFzypflfnp7dgrq9QoBN9wolOp6h0ZhMZjtXjNCd_tuwktPEzAg4FS6rSq_sjCeEZaUVDrDX5i-E
RJXdLGQnOxppEnPswkJK-T5ZJMX4vjBHS-QhfxfYmyawRq9_xQe0eaEopviAOcvSZyxMcxelzRfG3_NIr4CzzTHJ3_LGBqqzr5DFFVLG3_NIr4CzzTHJ3_LG
Bqqzr5DFFVLG3_NIr4CzzTHJ3_LGBqqzr5DFFVLG3_NIr4CzzTHJ3_LGBqqzr5DFFVLG3_NIr4CzzTHJ3_LGBqqzr5DFFVLG3_NIr4CzzTHJ3_LGBqqzr5DF
FVLG3_NIr4CzzTHJ3_LGBqqzr5DFFVLG3_NIr4CzzTHJ3_LGBqqzr5DFFVLG3_NIr4CzzTHJ3_LGBqqzr5DFFVLG3_NIr4CzzTHJ3_LGBqqzr5DFFVLG3_No
r4CzzTHJ3_LGBqyzr5DFFVLG3_Nor4CzzTHJ3_LGBqyzr5DFFVLG3_Nor4CzzTHJ3_LGBqyzr5DFFVLG3_Nor4CzzTHJ3_LGBqyzr5DFFVLG3_Nor4EzFFLG
Jptrr9j2lLTGxrGG4wbNvysg74wutgu0iajSNx3ffDFrPbK8Qq8piazy-DYfyzEQzF2nSWjSnuQF_27Uazrsia_m27_Kcrr5S3mc-j0mVVSxl7q-zAe46vQV
TUfgvCrCrzFGSpxCYgtC7wPxFG7zqIvwMkeJHrV99zxb-UXLTyr7voygGvXTQQiZ_PXUTO6TwAVThW_cpzpzjRLxdeBUgrvY_MG_y9lVAWa0000005YxhxLM
FOboSwxNBU2TNyUVG3_jxl4MFVRSzksnz9oN6_aYRzoMJxpyuYdUlROkxFFPpEmBzSm37uXapVdmWZUixfx_FNpqo_SDsprExdperZmwV4Plkbx0pTdk_x1l
-vOxtr1oB9qtlfbhknT-u37_dMyKpRVPBSm3zy9NxuRV807ryjH3lJprKEycr5DllzZ_gCTvDtFcXR_E0_NKUp7rrFkEr4CzzTHJJptrw6zdrSy000000000
00000000000000000000000000000000-14
}

