sprite $computer_monitor_outline [446x446/16z] {
xC6n00000C2WV_x04wa20000000000000000000000000000000000000000000000000000001WTkuWYO0e2ABW-i_z3spPEu3gA97l050P03CrdIybSWHN
wGGFtvgTuE7RmXCyV5juWeVl8Twbdc5JTW1_UWNe-kODuk5hmrD0BuA7pqCFduSUlUNe9V3qLthqF77YWqTFzEZHeoTweXU8dkZHeqTFz4IF7ZrweaUF7Zrw
z4IF7ZrweYTwzEZH4prwzEZHeoTwzEZH4ptHeqUFdkZHeqUF7ZtHeqUFdkY97Zrwz4IF7ZrwzEY97ZrwzEZH4prwzEY9dkZHeqTFzEZHeqUFdkZHeqTFz4IF
7ZrweaUF7Zrwz4IF7ZrweYTwzEZH4prwzEZHeoTwzEZH4ptHeqUFdkZHeqUF7ZtHeqUFdkY97Zrwz4IF7ZrwzEY97Zrwz4HFzEZHeoTwzEZHeqTFzEZHeqUF
dkZHeqTFz4IF7ZrweaUF7Zrwz4IF7ZrweYTwzEZH4prwzEZHeoTwzEZH4ptHeqUFdkZHeqUF7ZtHeqUFdkY97Zrwz4IF7ZrwzEY97Zrwz4HFzEZHeoTwzEZH
eqTFzEZX2qSF7ZrwIJvuz2PwIJvuv_BWyz3RVV1vwE63Tvq9Nz-yP-9Nj-sPyFLDUn9fyF31o_F1mqSlpySE7xmy7pn-x9RysFK3ecF8JP8aIP8aIP8a-VQV
t18WEtxiydpm-C7Byy731o_F1uyUl3oVjWUarxqUlkhfw6MNmmTlgjOp6prwJl5BZnw-H0yteqUF7ZtHeqUF7ZrwzFQZHuyUFNhqw8aUFNhqwD4JlUdM7XmG
0020803w_xePbG8d0G0000000000000000000000000000000000000000m
}

