sprite $computer_monitor_outline [93x93/16z] {
xTX5OWD134HHSLJtlt3MYTcjDjPR3lnXb6L4H4Ia7WDCZYdCQ3lMxem11HpK3Qqo8l0Z_oH2XZJqOA-O33bC5VIBuumppZZZZ3FEEEECCyuuupOTt_-fkFyZ
LmeTFg00s_XZmUK8YnpWN_u3oNNYaZWfrzkTSLG2BaiCVNRSaa38IOtLkE-Ceq_2QhpFajT0H4I_
}

