sprite $desktop_workstation [93x93/16z] {
xTs7al8w4e1HjKhLrNh_1zuqWzd0fWisI9ppvnm-sjZ2Csh_3G0000000000000000000000000000000000000000000000000000000000000000000000
0000013zrQ9TWZxg33dQoOXHyomrefs8dlDCsTjfo9gdgefs3YBdwSxAHyuBv2dv6FCADThh4JKFbQzM5nqx7JThz6Yl5NtKUSD7rCdFJ7t-odOQpthZz3-X
dSM1Cy-VxcWdSQtNssdofEacvezgvnadrrClrJk1UgYdddhgeHxgdKazr5DFFVLG3_LEe1xggTUVyDvwwaNM4xA_iPvwaVCfrTzOJxsQpydtrLDlp2NhgQUU
8-TuNptrsdWkNyORwwdN8fymegbdhGNrr5DFFTH3lNEfXthggQSUwg7Uwwc7UkhrgruXmgkpiOFll3CYUkPSNsP_JRs-q5r9CN9keh9_sJrbFMlkepAUhnVp
ENLPlJ4ta_tfUYsVh1SNrHirTrFzwNenwhd7p_zRJxn3nhFrMZpZgglrCRUKNx7MqciUAdEiB7FUZI-e5tblDoBQsY96pLyL-zSRksrJTSytzgzNHxpORH-z
ZDthZJtYFVutzTthvVnHiU7c9kDRweqjzyVOl5wlOsbY8_5bzNBBVQ4or5juSnhrhgMUUkgf5_q9yTPwwlMicd_uGuqJwgctp7kPKs-1UyhEgAVU-EPwPc-y
hvvwKIi_xpddh7ecteWtrbElnSW_R7JNUzPQr5DFFVNKKqyzzTHJJptrr5DlFUgffvvwwgcdddhggQUUUkgffvvwwgcdddhggQUUUkgffvvwv_mtnuBrr8iy
_eZbwgdN8clEZBNggNU8YDQMgwVUGJtrr5DFFVNKKqyzzTHJJptrr5DFFVNK6rdPrwodtfX_KMF5Ukf5pR-gKC-T4UgffvvwwgcdtYRKEwYdddhggQUUUkf5
n9Brr8kHMLMP8nQhfrvapR_u-IpxClNKEzhTPQnIJxt8-SygrgYdNjJy5rMnGZtrekOZsJ-_ddenvcFv-VNK6pLlwg_cONnwFVKYvqtsQ36oZfZnwVNKgt_U
6N7Sl-UpwwbtD9ZzN_x_vgVNKo_dZtpGfUApwwbNntR0Tx5MFVKo7WraNwAUUhLDFRCt5gvdzcgHUkezQD3dZumrwhbYg6WtaQlLSxL-v8kSorsjModxMIgB
dikiSwhNnhofp95PyoRRfzTJBt8-Ll7nzTHhlHx76-tpwwdNndnan0hrr8jH3-Arja0zzHuTF6kq1Ugfz_1st8osG3tr3Z7gPaHhYzHJxn3zRzf3wddxFVNK
KqyzzTHJJptrr5DFFVNKYwtg7V-glUl5_TxyZTo3x5slvTpmq9dVKc_C_OOlQluOkzUB-IjZkz6hldkzLhlbYr77lsZxUcFUP6yxEEBLQDlNQpblAdkihkUy
gVO5zQBcNIwkvg7wplKEOsvfjAth7KRD_MGiMq--ZBPxlKElVUFjNwz5xjIlHZjiNU_Gj-bN6UrhwXtwoDeWtOZMlglU8HRN3klLOvLwg8TwXuW-djCZr7kB
aLKrdr9LEKAzjxmeMlCbCjIxLCyh5alKMsAXj3BKMo_U8TMxIDHykHhgNIFd2QghTuKn3rNZALarRuPw5uXyvRd6kFzkeTxvUhtqM1TvuV2fDruyAqU-klQK
AxwoNiuV-UfXhhZqm9_dFq3wvzQBL_z_Lh_sZ7cSVbeNxUEyVd4oBtseZdcJ4UtreizVsJwsNesNkNRs8kSXn-lbl1cVMEyqlLsYpsjKg7U2d9SOxPlgLMyx
vSjePc_LV1NDx9rar7gJP_OEFUlik_FDtedwo7cE6hrzgd6QQ1UB_c7_30000000000000000000000000000000000000000000000000000E3F
}

