sprite $desktop_workstation [446x446/16z] {
xC6n00000C2WV_x04wa20000000000000000000000000000000000000000000000000000000000000000000000000000PkU-4IE7WI2AnjNtF_26MEz4
WIpm_LI-dnpCp9_AzSt6q054jniG7Zvu-_dOuQEtdq-X1-z-FdfpRVlqu7to1nZr3JUXrplRu6iUBRssoTAZ9thqwD4JFT7R6ZtHeqUFdkZHeqUF7ZtHevSF
TAyUlNom6_NevSFHeoTwEw8dUlIcMO_UM37OQw57J_JeqQCdUWNH4prwzEY9NcVqH8yUFIT4SZgR4sgy6O5krQZ7RjMe1szLh0SlAVwl1LvI_2WKUCczwxsP
FNgXrxlNacChqBiOxzWdvpzVRqxehNfpcbvQzE2jtgWtlT6RWohIywD7RuxK2prwzEZHeqTlovqoUXlqsixtwFNVZA17ZnuzUlJeqLlHizwZPw-57ZrwzEZH
eqUF7ZrwzEZHAuuUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6RGZrwKwf7RtsOcJOzUYjwzEZHeqUF7ZrwzEZHeqUF7ZrwzEXT-17eEMEWvtIM
7ZrwzEZHeqUF7ZrwzEZHeqUF7hqabNhqiYhJevTlAzAZbnzhqQENdzMXHoy_hq6FNdxLy_NevKWzUdcw7htllF9D9NhqrYiNwj5RhzgdH--d7uhUJZrwz8OU
FNhqAg97ptyjrdjzUlGodNijzDPh9oVhEMEWHu-UitLwSvuUlHbw5-G-9xr_v9i2FNe_zvlfqAEt-kcRqFFuFNhqwD6ZHuyUFNhqwD6ZH--fVFJepVFr_Ega
bmFnpjTx41yzVCaxzNAQtXolDpcseNT7zF1Deru_7pryqwk7RshryCtKwl6RMZr-CvLw16TLfwSwFT6ZHozNHA_HRaMlaMv5hnWleTU8jw9NYKUl7ozfrgCN
UhruzFRZbTrGf7VnkEbjxUfftwMNT-jjc6UdNkXrp9RUxDVRS5tsDGk6pNeRejVCHw-VR-Wryj7hvnjwlNn3hvTlwDNwpT1pKFcbFJWG0000013aRpt8rGu0
0000000000000000000000000000000000000000000000000004
}

