sprite $desktop_workstation [93x93/16z] {
xTO5Ki1038NXPAFl_WV6fGPiXnJDDrRzwqB_MskjjTPQumqgCm8xJaKIjkLLTO7GJYILK33j-7syuv8BNXmViV0IxmlA2s_4XytITLona8Tn1N8EaAiuwu8S
nHd1yoV3pfrpnQ1f6MVZJDCY9qvBJLonaCLnugNQ-CxNnpjkbV6ztnhdGS_wRX7bg-AS0EIYk4D6vaNnZ9UH-dXWS82kYGy0q8lYn6RZDzpdSIu-O3IBuUVY
50YVb1WdusI9IJ4-_PVB2xM_q2Em4bmNPy1jmP5rSO5C_QSAb7RoWxWYrm2X8u7S0fJU9Rupw93wZj0_q5fhhTq2
}

