sprite $DVR [96x96/16z] {
xTG5iiGm38DXnPgCxViVU9cXw8UhhpZq5nDyAn4H4H4H4H4Hg_4cxbc5U262LiEJUDBJKCKJJznHnj9-fjyd8VROJt3GIBQHliKaVcp4oQ75exhtqnEt6lTQ
NJySL-rwreRwdCGE2UBY-kORET2td2GUNm_9-pDV_V-73_Mnjc_9B-ttn43VOcq__FxdRDUpeU_hKoLngntAt1yAveSztAaVNsNzwThW_Da3PPXuOjbHnCBn
h6TuZGp32zQz1l4ZH4H4H4Is
}

