sprite $DVR [446x446/16z] {
xTr9TlCg483HWGPLiFy5lzbBWvEO7oeoEVUEbVOxPQj1Sdy8000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000002oxK2UNeu_dSu8QgTVj3AOl2_9rsfnT3pKUqI-eX_2R-nvLlq88jkRydhHzoAgyvL-Uw9sDchZ
KVksD7nppXcFC7hgSSj_EAltDociLpvwBEnqggSUwfLH3_LGhu9wN6_oTUlbUVhNDdoB7dcDCbwnNZlHXfKVyMN_wolvSlN-rjgH3T_Y-awgjqFqHsArNbm_
2VMgrfolZk_rZ9fwPYyMwrrF2VLMzKToyLlaSRCNnyORhN-BXT6xwtZlhzne5UlVukTy-RhdMgnBY8d9KwyYNkih5kAfT_k2nrmuMB-ZdkLuyToBvyVDNgIU
UjVrJBxu-2MftZunzS8vr7hqtfSVOkRdBTGhk1y__gNUC7qPdwuOnP0tNw2UFSxn7Cee7dt5RVMyxOqxcREvhznTp-mj79zF7n7UNiyUv_LcTlkylLwsysmQ
lV7uOFPSZ6iC_oBsZjwR-SrTtvktxopPDPNlKc_LM2ctrSkfhMDdFVMMhmZrfNhnpA-XtkQtlJUBc-VlrijsejppjZVENgx6_l6tSCIGVSyBvvXZjlOBt18V
Pzbvg1udr_EeXjaQwjMT9JjtzjJBasTFFRDtZd6FitxsKhtIg-hrH-ltr_F2UNuz2-1ZShNqZrj7zQDn7IzyjtHwQkju_1wSwfMCtcXg-8RKQzSOrClDzPOs
RkejxBEivykL0uomfcnExAsN4tivjwqfim3-SO-OsxpVLiyUvxWVcNEry_vwRfXzgp6vVN-TUkvLZ_vEHdyJ-SFsrbAlMQ-NmtozVsbzC7sUrx9BzXLZlD7G
EpqhQPU-PBovyebyNRrT-feS9k_7V5szNR9lDFM4ClNMHKMyKKazUoqryKQUIxrVLiKRlKwz4TTF3gedtaYzHUfnyZFXEVlp63Z_ir16v06VGyJaKtMEh4Vq
W-kXtXhrSZWjo3a34iN3H_n6lUWbQANrpXq-zNhxdU4JBtk1hFpsjFzLV__ePSJBwbN_BRVs8zkRNgIzrpdi_zhAKJdWnIW_7L1FFDCdtgXL8VeRusVmHX7j
80Pl5Dds8REV0G00000000000000000000000000000000000000000000000000000000000000000000000000_WC
}

