sprite $DVR [446x446/16z] {
xTtfZgEw5WLWxsranFi_y9shh2lIXoRW53xzVNypALcrpBH5bTS000000000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000023kGFcykhIste7MMetoET6sUz6gx8x8Rrct8MXHHXjNFDOwyQh96i8Jt-6osPQu1qlxI7nr
p0QMwBk2hGmItn-nb7iHRVHlktnWSHRV6cEh5sK0sj3orQ7lJgmZjtojlpaZjqor3B3sznv9-POom8TsMPIl3KolZ49TUtfJ_67iIM-RCJr2UYVe7hg7xkcU
z7IFYCX_YuYvkaTcrYzPQ-P3knTjFb5-fRRVLFyokhgN6S_hNgn_fxd9kcw_AyfhaLb_8UDftMlRZ9Rhiwgjl9JrhsGygtlhDgDsD7HrR3sHNPUfUwFIMow-
HTPZ-QJknPm3vzU7_6lPYtei7hNFMTiwcrRBIx7zr_jlaVL8FEruBsPpz0NhYRSu6LyurpBArP6ku_Z2kPPHufPfrJW8J_V6MEwPsyc3y7HlX6WtZUF5GNYw
Dq1zV-6Cb-tBRw_2YuTqpyAPkOilC_x_jFKkuT2z6xs_SERk34h6xgXg_nBTkt-FixwtdSlpUpQXUxT_ktXp9pCll4BthbhVNZZhV-N9y6h6ZtVFeNhM_ydh
B_Xyzw9EvzO_pQnVykhpFz-zPPlEkjnug1wrovEdOkAdkxTiCwg_EbI_U68ipp_zUlTSMs-N5iukhpqxrhDd3CorzAzHFvlU_kFQyH-HbNDvlN2kSJMzA0Vs
wUtZQp4ulQxzsGjdxAftBUpecGvChwlBRFO_Jw_avzFR6vgUYqCNqWlfFUKsGliqBgGjlG4tkP7U90jdaTxK2wVjtdpweRfzpkb4FrJ_Wz9pQxTz7EL8bTxe
g-gVFy_PHOJq1bnL7toDeUz1BTBxrDVAUYA-E7hoqfS1wGsOupm892uy-QFNznogxyiN9vxyerD95ivz877YsJyubMJXxEgtEBVIciOTDm1_ldnnOPnJzuOE
m1-tAKwc7Retz53zL1nnCkuiJ-XUNMRM3zKlU15UPlaMcVkuCyextJELjBUMIxBMU95FPaHavhve-RfwfPgbViDIhibTU0Stk8eihuHPwZT4kLNMlNpYtLLN
2-T1U6VY2oldUSl0yBeSqJrxBIr6XjVbuxfNeavlSFEwV53tE7zdu_dkT2MyBf_RFMA2kwiEOELyGlU8FBYV_upTarzESeT78ZDhbzcZcw9xHEH_nVJ_mOr9
kySZkbU7fSVuQTookvp2BCjRJw-M-KYl3wwEPQUbZhnhUfJ2T3zmtNgncUxtRTkujPDOn_wyTHFVCD6smJlrRLHyrErBZF-8TObo5wAsxKiRkbVqPMrBlGLj
tGsuZT6sCUZXJHeVQvHEV9gtlumn1BLymd9_VgnBV70Fzqwq9SednRAqzJhQijGo2m000000000000000000000000000000000000000000000000000000
00000000000000000000-2S
}

