sprite $government_building [96x96/16z] {
xPO9igKm24KbK1Vk_ZVSLXoZhU_x4tlCUQCIJr60m_1hw7GwdKvAMhmQwuq7qDQFr_qXE_m5Vx7vh_cxdzWHVz_y4mMfVVqhwFuAaY58XaDVi5jmH-kvqMnt
s0ZoVqWxku2awxPj7B5c-Y0ZdM-KQAV7pTvg_KKfl4s9SAbnKglrTfDba5Bh3yPbB96eJp_Travgq_UxtjUsE97wvlNEoFjuPO6G6oYN9DAagloMktXBFDRA
0caYe5r2kbCc7ZJrMwGl-fNVmxxkrxJ3cUx057xaBsg9cEk60pA5cN_g_Ue76llFDFQd0utznWFfxVp_hlgdb-SdmOiN_gJvH6oGiOUV_FD1Z1FR8rHx741n
GMwCxI_u4MPwU86cPch1aRX-hyjiSzZ9FvmmhZVXEu8_6uC7_i_pyxw_-rFmY4ip_pf5-Tld_zRIxzErAUL8plmxVkD6SQ1pZ-xz-zBPlLzuvJy_SyhYHn6u
zIVID6EbNtXcyuUgnlW5ygDVXecJ7sQ6_1saZMn-dvTPZJ-j_SLKXZ_QBoU_YeZbRsV8IDlyppJrb_sDFxw_ylRy_7FzDLL5_evyGR07VZ8cYlhl7-UA-i-x
vZ3t_fWe_Hj5_WMblmIhVqE75JDdB636Z_bFEnr0i0X4E82y8ABm32lcdmX_H5u-LD3f_
}

