sprite $headquarter [447x446/16z] {
xDitieGm48R1MBh_VP_tTdUerS-K-alnT0HJcdicIP8aIP8aIP8aIP8aIP8aIP8aIPAayL1nrtpqdhjmptC1mdlhmAxvy8tQdldeNSx73v_m2Hy-uSk7J_Y4
3ny-VC8dVFZmuHC-uSCdVCA73ny-uHC-VFZm2H-d1GLKwG645_2Zb_OJFdfvF-73nm-Vy8N39tnQyMhnuHC-VFZm2P_muSE7J_ZmuSE73v_muSE7Zzw2Lukl
NGlUxEtr-7M-1i2Erv0aIP8aZNv1Yz0XPFSUF7xq-B4hHeyVFNxqQj7ZHmyVlLBu-D73HuyVll-ZXmyVFtpuIcTPlkGCt-yFdkUhFmQz61-_-bCtv9luNfgD
-V3DRVZmuSE73ny-VFZmuSE73ny-VFZmuSE73ny-VFZmuSE73ny-VFZmuSE73z-uDA4Z20zWNK_m00RrH8zVJa_q-CNqH8zVZa_q-1tbCt4e7zn13zzxCRxV
Rm1V8x_IvV6zrviFNzIlS75ydpeDtzoD3n--sPeFN-rWVFZ6tdpuyCrT-V3XmuSF7pvy-F3XmuSF7pvy-F3XmuSF7pvy-F3XmuSFNptXmuSFd_0r29_muSE7
J_Y4x-BmuSCd4mSJ1tpuyE73XmyVFdpuyE73XmyVFdpuyE73XmyVFdpuyE73XmyVFdpuyE73XmyVFdpuyE73XmyVFdpuyE73XmyVFdpuyE73XmyVFdpuyE73
XmyVFdpuyE73XmyVFdpuyE73XmyVFdpuyE73XmyVFdpuyE73XmyVFdpuyE73XmyVFdpuyE73XmyVFdpuyE73Lqlu3ePF-8GF7pvymeSF7pvy-8GF7pvy9Wu6
HlZmuSE73ny-VFZmuSE73ny-VFZmuSE73ny-VFZmuSE73ny-VFZmuSE73ny-VFZmuSE73ny-VFZmoVe-uLiSFk73Xm-Vy0aVFdpuX0-VNzP-MUF3XmyVFdpu
yE73XmyVFdpuyE73XmyVFdpuyE73XmyVFdpuyE73XmyVFdpuyE73XmyVld7Ir1nFlVNKcq-zzHJJ4pu5z8HF-F09d_3X2_Z9Tn--bdxq2duoSf21BRrbtRS7
nm800000W_ojPx6hkW400000000000000000000000000000000000004
}

