sprite $headquarter [93x93/16z] {
xPS5qkim4CQQPTt_m0-3qzzbhZMqNq41y-xDw7Iqz7zX9JUN1_w_IEozvLsk_eSYtLU5tiZDZyXDv4x57c0taiTkZ_nwkQJkzj0STY_Be7O2Sf4wE8soyzt5
oPnjJyxWpBOL0DU997KXg2KaeEVF9zRgwavkRyFFaniW3v5tkKN-eu3AcO9ifCqlGsumSjhueP4J_ezaBAUOlawrX01o-GPhZnozyfq7rMp5lBP1fJaN-FNo
uVFbUcCvDG9G2uVJEXwINqzRNZOIWDjCahPEjGI7zPUzAvugx_8kx_8k7qOCq64cY671oIK8hB-ywsBnB7dAY0CcCq5A8naGSz8lx8fz43bWhK4Kv19qCuZa
CmVH-hNe5Q_bjNjBFxR4vN8hxi1uEzm7_ISlRi_SPfBtm7OREfrEf_CR
}

