sprite $headquarter [96x96/16z] {
xTU5RaOn241X205wtl-1PstMt-NAb2_Av5mt-HjA2PFENNPW81yKz4_rgwzl3BG3qpUocSObAHinBhFj-dfkqxwS-qtzjcjVJEMSclnm5la8jsLr7fOgJtEU
qEHPobDiqUgRwk2W1o3c4438amAmgvTOm-UWG2xfw-Fzjac_-khP0RJyr20FHk3mTuUZomtE1lJcBI6w1iIK40SW3wU3lyrR2sWqNRl_3LmkKx3rnpV8wtrT
t_Vb_Uf7B3y_XxpHtyIjVilhzuTywFwGrFdp-_hLhtxrgsyw97ruuFl2W3R7-CRdroRstpzrVYxlL_ylNrzkGzA78S0EGCx10UQO_-tygRvt0U53emz3WX-0
d4C0NFnJxVbaBtq1xCRwxjbv_KLj7x9KAQMKLm
}

