sprite $hospital [96x96/16z] {
xTO55Y8n383X9gIH-rzuHxeXl58ONStt1EsFLigV9QMKKaeffPGIg4LKBaPMwKdv-du9xkuBbwl1omsuBFl5sRnzfgVxbJvWEzt7yW7zINsKYE5D_o62h_tX
o1wR14Pl-YJowFhTo3heQmdUz155X13xlfRWS5-QWtt04Y1iwWz7HaWZDVQ9P48K-pJq75XjxDll-m6LnXX6y5iVXaIzNpVFBu3DyuktzwE_hkzxkzBBJayx
-p2BkuhtHMccslvjD1E3rk-7Tdt_aogMINk_F_lABHp7OUlx1-BmXwMk3yOqKVQpI3NQrg_sd8cgD17j-rDjqlemlwtDVLrkh_tgp_nJ-hwy--_hjtRrAqvQ
dn2Hl0_yiYzLMU2pZnDQ-u8JrgvVn9Sp_x_3jlc5jj2mLDQ-Nt0s9VtwvlaBxUb-7Vx4zGTOctfBNvGRgzVtuxD4jlQpd_tig_A8cFIpLlpvQZoaN1eGtO9A
KtKBWVAdIYcbz0C
}

