sprite $hospital_clinic [93x93/16z] {
xC610000082W_QaNgG800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
06RlF5ISvu40g6MrHU__m7-DQVSbjho-o8OPGhcs1nacLL8U083MQCi0zSWQOTAM07rSG2xf3tgEf-e3YN49wUthW8whQ5y7xC7smCV_v6cMsyDUw6bijJti
UJkDFjWUzZhsQE-6q1xG7j0UzcYFze3seDVjPSqUbA_xNdwFoTltWHvZP6y5DFwL9sq18AgwTi8-00000000eEOFmBGLO5txOhAt0gnhNqp-g0yqnrEmzbom
vmsmTokmXxtm-vAVxM4ljTqMYHrxjATFM0Ur1jh37kq1xQs4ze3sQ0zxj8SzsgCzxD6U-8OypXxjQMxeQdkqXptQmnxj0UtLeJtiqHxsQ8_sH5zuRhY-a9lR
eptFz_WQUxI7FTh37kq1xIs5ze3sraDxsACzsbDL__-I6xvzIx5NWDSvQGzxj8SzsWFQkoUqHtkYvkymbNFsHFlxeLsliKTxOZ4-4IudxFNFGzFr0dkqfpds
I9srfx4_rAHgZ_OsUQVqgVntqNC7CrdH7krf_iQfYt5iQA_Pept_ZRF3R1mZf6AFzcGSPI8-ZN6GNh57UpPUXF-PE16VxWxDRMZ57kszvAJj7cSTypUSxuVA
DbGAzcWlzgylVmbkX_5zt_qbMElsQC_tIyfBN_2IWZtQcxSNsAj2UxI7FTh37lTxsACzsiCUxM6F-psWFTh3NW7Q0-xtxWxjqHxsQ0zxtEy1xLqFwrhiEdkq
brtUOJbjRrDZAc_erwufOptd6tAyi3FhEVUcHYlOeptzZRNK4kCWTZzxx6FeNzh7m1wYMBU7Q1Jt4D5UwpczLsiVYOcXK_PeRxg-w6qIyOcX9NliMy_TBShp
zDWPMjstJdiRsj-ZxIJIFy297tps9UrXZ_QmHtlOeptQmnxjOO_sWFOMG7j0UxGdFNANCBsVFTeJpt4CrvlPepsDSPZijx97UvfZ1bzbZ_RgyaRgVUpHdez9
GXROexrgUXjs5tkqPoyb6RQ3RvxZ9lPeJs8BIevdUXDxjBVPyvbrr7elUxJNPvuOzWNsQAzgJvvhZ_QmHtj0UoLe3tkq1xH7UzYZFUpH7krXZ_QmHtlOeptQ
mnxjOO_sWFPe3tkqXptQeptiqHxsQ0zxj4TxsACzxD4Uq1xjOO_si4Txj8SzsiCUxM6FzcWFUxI7FTe3sgCzxD4UzcYFzjocyJnXBsmQZnrxs2imOQy2zh27
FUnXhtwcDKZTddp9dcBh1xsgpxuKkKlx0NIF2hqTH3qgs9_bWLIuuV_vkpqu5W00000Ov6yzXztL1G000000000000000000000000000000000000000000
00G
}

