sprite $hospital [446x446/16z] {
xC6n00000C2WV_x04wa200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001WTkvT
ItKO1iDeY_p-3tpAh5EHY0ZdP_QtfkHcxU4UlA7wjBKpTg5-gcWzUlZeYLvIz4IFtcrd5ptHeqUFdkY97Zrwz4IFtjZvvyEtsct7uxVXx3kJ94cIL0zitHKy
VFJmqHCzUlJeqQD7pysXHuyUFNhqwD6ZHq_qwD6ZHu_UawFde-JfSRt-gwRrwhDIx8w-gVUQrQlF2yEhojJBtsUoxcct7ZrwLNluwD6ZHuzUybuD-Nghrruz
UlJeqQlN-sgN7hq-tX4zUaVqwD5x_GKzzprwxdlqtFVMBhtLBVE-DpkDd7qnrt7sxFlUSOerC8s0ekzxoh_loNrlV-vxDcuOrQi_COcDRVv-BtyKTKGlR1XL
z0AdaQz7h-WbZYDVZrxHeqVlxXxtVM7-yPppzVGMlS1vqAEtNw-ElwBtSNRye4UF7ZrwzEZHeqUF7ZrwzEZHeqUF7ht6jvUDInYP1xrwLzVkQ6WUzEf4NRoZ
aNdGgrDryOxexTEhBjxH_VEWLsTxdXwz-bYlJaUF7hrRzUZT_cBlibvxZUTvn-Rn_coJUXF_z5_NUx_muNcixZncF-feFcBbwEsVHr-lzvHJUNfFdSU63whg
VPbwy_FOhrTd2j7RFu_vZndpzKRcaQz7htvUZrxDwLqRJUDSMNhNhkpD56FqwD6ZHuyUFNhqwD6ZHuyUFNhq6YVewz7RVrGIFNhqLhGUlUs_O-ZhqLlVqbi3
UlJMq2_0wDKtzDOtVdqvC8zXlPYZS5fs_KjmNClDjtPsn_k0UGGTppbUm3p2ZgMcj_RehR-ajuAEXEzlbvAtISDF_ORewCpLziwLhxT_7dsz_eSSqVkKxPx7
zHFV-4OhV9Uv_Zpg_3pi4MYFG7hqwD6ZHuyUFNhqwDN97gT7hoxrA3rwTRNdwD6hN3rwrUWXUlIgrHuzUlJerHFqw5q3UQWUlNMgP3rwwpVrwD6ZHuyUFNhq
wD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuzUjVGgKOzUM0szo8PMHy_oBC_oB6_H
2yPRYrumtbg_lBvKl5G_ZophUh-xl32wV-t1iG00003087_hKUohLW00000000000000000000000000000000000000G
}

