sprite $hospital_clinic [446x446/16z] {
xC6n00000C2WV_x04wa20000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
001WzkuYos4OYgBWDC_xtsypaoqfShvErss6o50ZS_qos5OnTFK1uQtgfz2ZTnQVwC6ZHq_qw6szqQCdUjUDdkY97Zrwz4HFjzKJFNpJHfWVlcaZr4_i94cI
dAbIBauxUFpWuOD7ZnuzVFJeqHEzKj6ZjvMD7hqwqHEzywCdUlJeqQD7ZnuzUdblEJrwb_VeqQD7R_teqQD7ZnuzUlJevPKibs_VfROUlUJoUmazUg9tLlJe
qQD7ZnuzUg97xxr7f9Vtrzv_tchhqTlokiVilVU_qBENMlHcHeyUFNhvlG6ztK77zUXbhowzx7GLFNhPhrql-uthqSkXMlLog74zUjr-xtjO1WOTqAENexLE
QxuUlHnlXbxAwT7B_z2Zbs9wz7As7ht1FMoj2DVKexVpGdhqwD6ZHuyUFNhqwD6ZHuyUFT7hZnuzUg97ZnuzUlJeqQD7ptajz9nJHi_vdFISI-qw1hc6oFLx
7HERhqTlcu1N_jfPrwsFystzUlJU6xTppmZFlgH7ZnuzUlJeYTu2qQD7ZnuzUg97BuShfqSlBTNIevUsAkdHoxfwzDBSodhqKaMFNdeQrHCzUYqaTVNe5PWE
lPalfKTFzDQB7ZrwzEZH4prwzEZHeqUF7ZrwzEZHeqUF7ZrweaUF7ZrwzEZHeqUF7ZrwzEZHeqTFzEZHeqUF7ZrwzEZHeqUF7ZrwzEY97ZrwzEZHepVIvEdG
erSgUg97xpRJ4JryDvkEJbkf5V7mLPlEVNjmB000000moDzw3hkh3m00000000000000000000000000000000000000000000W
}

