sprite $hospital [93x93/16z] {
xTK5SkH0341HCTp_mck8Hrv3qgbmebSm_CSaDtoUrbfhhRNMMiCzU5-QUmxlofsBnJl73Og-SrmL2ZjyV_8iXhUWVDuRumptzArnWdkIC8vsy2gEY5TnseDh
aNjo4O-mYxZbdi4LJAKIEXmFf-9n4nSevpYvHuGxdk86nG8kEK6nqs7XM9tY9b34OCH87E55alS82aRuuE-2uKcwtD0NJgZA3GzOOVBW437pu13fS7plHyN9
5meBzeMyKpp2PYdhbzqcdlYQkCLCOI8nyosUSfvPJ7wAayUCe1gdEATEB140qdMISXt7_-CMEec0VQFYzKNWDSum6OoxFGx3sg2amVZzOQ7tYKVux7525ucl
Y7FoHDUuykGHHxku51cskFF40xQ6dECOEVDQMWA7XeXhuQh6wJglbHEG9aCJMZ-ifz_jtYAnuNUFKvgiFDuzpecFPpyotl6EAzxWP5p9BawuqktPcMrni1nH
yH4A6-81iE4110UjjTR-0G
}

