sprite $hospital_clinic [93x93/16z] {
xTQ5ZWKX38NX6gLz_nVUSCa4rWLOk-UBZVxZGZyB00000000U4PxrPp5tlrEjy5JziQL1ZqPbsJQYLyPMy3lew-oV1z_FMxwDb-9qpjqPvpvN9p3ZyL5emgV
YNCqVYZkDSBBdpddxBNnLk7QzblwbB8X7bcRzF4IYpx5rkDPgF4OxqIX9lnK7F6gJKpnearkY5jsIXVFcv3rE757mvYWV-9zBjhnWRZdHRV7EPrl9Eg1k55N
_raSSSJ7gl9Yt5RYan7VymlDLWQxCb8cHlyV000y
}

