sprite $hotel [446x446/16z] {
xC6n00000C2WV_x04wa20000000000000000000000000020sJcFx6o240Pk9JtkVzq_Hzvu8d9grT91RbF0bsTDy75oqJD3oGBBdnbOb8CgGsOxQoXBIS0Q
ruSjUx6dZs5FzN-d1THteFan-OxNNcXL7eFpkQZMQQ7AeG-ENBR8G8yzrI-ScQ4i9G7dS_7wzcAFyqSjVIUW_WB3FlwEpLveLNROurYZzKwBF8S-E7BP8WCz
zbJ_OSbS7gWi9G7hF-Ym5tpsvlLL8xDN7Gpjuqxi3G90ebWT_lhkarofjkq1uva0j1IanDf74ldskJoNIN85Rn9Pvo4bGaVWLkv1fgvbVdg1h7jG-zHD34Sj
VLvCzkYezCnHCtpK0Q1ZJ2AlGqz58CUEYxp79Q6hBVndZJx2CzKqd5MV7z1I4LmhDGsj9cW5JAk8ZjoipGOqj3OxT1GwQxC1khhPaPkrUMjCQ5hAz6T67o6B
FXewJQj1KqKCKyABQpFw-9vocRLvRKfSNM78r0SczgWfOWyUUwxXYpr_RiMUgv_zbKRiTMeVKou_yEp5NZdiPN5sNBd8uxq9RFR6IuttyaHPPi_GQ9NHuyqP
yLSQp2iC-zk851tFKbFYzEjE4hJsx45R5UqbUJmddCbjlvvFqNBxdt--ZWvp7sMIq4_8bhdcxCrU_OEJkJsJXtyh5xSQiBUNoxj79TKWM-Ogl6m8qkDd96Ul
ERVtJerrxH7Q0h_gZBkv-vF9sKokUBlN5b67kbKI7FqQMHpEX5XQ35BxK901q75b-HuQ80zVsPs30W0W6020J-WVM0cmxIx1VG8000000000081ntjF1JAlF
nTwTfDjjX00OdGBxNt36wMmPwXMtEJL-7wwZFtqib5TE_40x0VFMYTqRg3SwnsyWN-IzS_e6wkLwlShtpQTUgkVFFVNykQVUdpwyTwwdNhr-FVNsBw5U_opS
Ghqwy-3YyJMwDrAl_lMK8zxvpVblg_V-HpqwFZe-ElNKe-EZuwDJZu-EZuvFFJe-EZuwzTIZuwFZerEFZuwFZayzEZuwFZhrr1k_sn6vD4Az-RivytUCeZT2
lV6xLT4RCR-5UXUNaCqdPA-UUYUMCPskfrxxqU-FK6_-Md6iZL3lwZgFcjUhhNhgPIFUgzVpvzxRrbEldq-zcYzaoNc-rWJrOkSVEVhrucmz_xuNpGdpMwXN
uqLMKUDurHoXNjtwBymndb7gjVxSYVhDcSQBtWZrgYfVOdDSjdJgnI_FqpwT2VrBg4V7HyT7fnuV7HyTdthgyT7nqV6fHyT7nqUdddfqV7HyTEhnqV7HyQb7
nqV7HwUUUdHyT7nqwl55DSwr4QbULitssbPaLNz2_nRzUdRZxe-OrxCRzzRMWOnfFRjnkoFgz6vSzM9zksh_5khbpNfnT8HwKGkBRTzsHw0DZtO4seshdjsu
wiLNRXNtLyxzVsgn6zVND7mBfJL1lHW_-8gwDoBKw-Ih-MBRc4wm6xVtw9x-6lqHqUolNXpuSkcl2zQ14Vb_EhjnFq-tV_ZKKu-FZe-EJpqwFZe-ElNKe-EZ
uwDJZu-EZuvFFJe-EZuwzTIZuwFZerEFZuwFZayzEZuwFZhrl7qvVdUoyk64_eWuKC-RpsiZCjHhhHse7zuw4DcvXNgDNHlT4NLuX7fXLv8zPIzUpsxSiXjt
iPxTkEhPhce_fth-ogcUVsgn6tVuDOtO_vg6tRZz2T4QeLwq_xnfFFgbpSQ-u1RrYxEtNbUz-PEFQateZr3lUS5wy5IonkjrMxV8L2zY-CtVY5ZuRB1wT7nq
V7JgyT7nqV6ffnuV7HyTdtfqV7HyTEfzt56FZuwFZayzEZuwFZhrrAFZe-EZKuylRzxsh4wzl7jEwTIBoeLpHgTUBfq3ElLoxKnrwaKkdfbElQZSFEhDVBbx
lhMUUkgbUkhrptVMKq-zt3-dTEez_Sc36vjEwTIBYlyv__p9__d1VpP-y4E7TEerVe7UlBlrr8k_sAS34G000010_jQBp73NUw_UU_NUUw_UU_NUg_VUU_NU
g_TUlVVUg_TUlVVUg_TUlVVglVTUlVVglLVllVVglLVllVVglLVllNhllLVllNhlrNlllNhlrNlllNhlrNkltdllrNkltdlrtdkltdlrtdkltdlrtglttdlr
tgltNhtttgltNhtttgltNhttwjMhLqzxTcq0C0W0GB14zXyuPQIAuNShFCv1AevSHApK3lFkIBwOwi7KKwzDFCIJJptr6fCleHxg5Q8Uwk6Tx27NTJoLuOz1
lQDK2_xMnRj8vVkHouc5aNy600000000000000006m
}

