sprite $hotel [93x93/16z] {
xTM7Rgqm381X9zxWzt_TErncH4VeRlDf8EUW_wn4m3Sr34DvPEKjL8EMjtLckCUYmXc5mDaqmoqrmjfKp0MEE8AXLq7MAI9CQFtqIE8HuS88gIBh735htjEX
Jh6IxKTQBJyyph6O2RhhQxkfEwIzFYDqAjFQRkeEqDGHkZt42NQIAmQR4gb0juYOhpxv11kCcv-yneH5PpljQG4-RcmAgzLkR4Qa_E8CEydlpsMFuthd5pTK
kb0UVGcxsdubjsNnAzGHHx-YZyUvByw8MCyWbRh2LNUyusSitoG-uYY98IqJDTFDU3aSaNQgwuHl4g-FJ3VZG9O44ZyoZQtu_l4Hhwb0UcIw6rT_K7FHFDbf
ylBQ4ygdCyblSq9j_-JjLFRfPXmm5KYFJE-_MqPyn54JGw97fdTyGDDNZ0Fr_YnZAuvukVOcSVLhMbuV5t-ClZvkRlGVkyl_gonNTIzl49UyrkNWq_A8vi-E
Z_Y8Z_Y8a-pKNMNXRfAMDTslpIqhXXRxsn5ecByXQ8Y_7OKMwrkH0js6uIy
}

