sprite $hotel [446x446/16z] {
xC610000082W_QaNgG80000000000000000000000000002OVJD1aIm8WQWY0e5n_-lElgKpbSpFqjw-xm2F9aApxEszGMb18ULuSWvEbmuGLk-aoh0c0fLw
D0WfnaYNOKqah6MboMelk4xQ09AGUgBUQ-GiNqwaPVcSB5--u3eH0x-1z-1rhXCnE7iYGOCNQI86i2KIZNglSPs8mTWJYVC7eRM3DikN4wcFH2DvomOjtrYp
UlNBvsJvyWNNYHZu1tZRNkSwQOEp9nBm3yBgdH0Pm9P8D1Ql5xtnitoxHC9QLfgXvOD6J7jWIoGQsLizQ7DsgZapRWKv6vW8isUTmGJCv7wecZaGV4G0PgPw
vkL3SDch_-TKrLiicxaZXR79nTrCBtgZo6iNljO0tFrZhw834Rn61E2o1uWZxoPiFN16Sduqm1EWiaSFlRB1WWU4oyT5KL1UcLUsM4nv2KL1UJLHey6vbZUF
PtZJMA1-9E3ouK7FKwG7tjhwyi4oZoSaKHDrUBsJ9hS0FKU0DdWjJZ-UfpxlsUhm-eqEaxkWQBhWKB_HXYalur4JSWODNiopcV6e2Ja3bdiLSsrclEZQpA1-
A1HpRMOyYaBkzohcsSoWPlCosk3LsRnCDBNNuFNzQNn7k4EEKUveQ0_pnsIPj-MDQI_XJMSS6hpS4NEqPD3azVfrvdpiPQB9YuhsvkXKxcdoelwHfy_HKZNG
pYsX1O_nd2t-IkrPVNkSeyM32rxZ3SJJxMbo0bpHUxS7Lz4rPzHu9NjTBcEnZ8E966v-jk3lVpmnnDFjwH-AWFxmyYcl_UENGOuxjwT8WUJ-VYH_lYUnU6lQ
2rVvWNhSzsond77kB-pqQDbxSUw4ouBZtkq5J3A6fzhRU4zF3EIzo_i7lUF77cpp-bcvrm-zyRWXGzoqFRWyma7Ys6jRhyjLbbtEAE9-PmlWku5L0mwz9XlK
uTSFeRtJF4pkXQliKPCJJCgzdzc3SmA0GI00OFVwjrm7PM8YINSSTCPB000000000000eFUwZ3_ziNTlkuwZG015GQL2yFy_F2zpoQYLs1smwUIi_TmgqLbo
hZhbo4kB-5wxFgwlvzuJjFATvRYdN7y2V35kggy_0RusnkQBhuzxYl9rrJvkQ_F5dsLvzEeOdZfTU_Ikh6qx0RtvOjVx9dhpjLsV6EZDrsFFLotqvkjPo_EY
ZUdezVorg2iwFCPl57cw_lLwt_p_ItgV5JrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHenVviYZ7rKqZwELRVvdt
M5qmehqnWbxqSLoRtwILwqVGgtr-5SgO635p2dfjVWzH7-UgvR7vKz2BwILavqUqnIFevHWJLywg4MsSh5Tw3xM9PIphHlJp8-ZjUkZpsH4_G8zU_6mzpvoL
tbjBgERN5lSwFw8yHA_swRVxTPmi5u-WL_BqTJDzyPNv4PNU_slpAv_xn1AwgLFGAstsaI-rJVXFdOBUyVVxhPQ3eaql_8v-VWIznsgygfmffaSSduBU9qVl
aw97ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUZMYFIqZoa578-9WnCGfw6KVhsjH3ZeQqIyQGMz-
iMtj4uiBDkx6jHlt_8ZOjXlNRjnQdhHl1BswO3VkZIEItcDXD-xMxCQbPpVk-kp6fUUPqqR_yhdlMdnYo3_YRXfPw3sM7_LfFUXDVisrRxsktRY_LDl4y-OD
wtLdT-FQZNjyzyGz8-WTtpIqd2doHR5WH2s5tYT7xwEYHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyU
FNerydcrdAdcY-Ao4VIYZTSTF_hHBn_Hiz9xRrjE_9bR1-YrCMOV-_wv6pzisyctjbJDdu9UxTERhkgkJLVqOkUMkSSHjipPy4ZFTbLwDXjxvgJdNOjF3Erd
tqt3RjnOFO9U7QVAzRU0cZy5lHBjbZkuZPo_WvjlgT_PIjkp7DGMte3n-9joUez5P7jUHYs7rOCHvRY8Td0AUjyKFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6Z
HuyUFNfV5prwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHgt5VTQaUlMXzt5Rl6SlqwEMulHvBzEZLDdQK2_JerJxsrARrwDMnhJQhHw-FVUMS7hqSEwjJUlJ6rlgC
7hqszXOJUlJ6vl9zFNenDjVVrwENs_Ng8Zrw6S_huw5uKeuJ_wgDnsAD7hqiB-fdtkZ7gIV5Te4UlNAJNj2ZjorwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF
7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF
7ZrwzEZHenTjN9fwrgli-hW-NUENz-2fNy2NusF35-EsrChYshWlHLbQ7NSchth_vEBhuywKPMNZrjJf_MRqH4_fFQVtd5i-x-c3lsjH-fxJUvQ9Yqz-8eBd
jtM_hPTIeurBKs_nLtjmG0000040oF_JW1bLF0000000000000000802
}

