sprite $house [96x96/16z] {
xTK7RWKn28HXG22O-nyuTLU652VMOrFzfRTV7gVHLzgsRTisZITAbJ2rO1nAZmrGwY20YYWWUHCUkVJqXOXpNmA0EG2zeCzs75q1E7VtDO1uVbqS26thZwkX
GvhGq4zNKxuLeKrzJR6U2Rcl3i1IgM52xWC8eInFCBwv7qfLdI2tz2dc9xGwORtFGad7XDnFcYVKVly41S1KpIVG2aj7wfyWaNut-oTefC_jds3fLwf_0diw
H_y4INUpZ3-SeEcVQ_-4V3Vz4-gFPVy4dLpUyWHT-9LTfgydS7vN_mG9097O_Cl7v_4Pg030wzrNFEaxXYY1Ajs75ZRj2s3Z4-NeXxuoASpwYg1JGFFxgd_Q
bpz-F_l-SV7vuVRC0MdlasDmwk-J-acflLzTtjzzDNzc9lrz3WmXxNq3mWu1R-yxZ4w6kBIl5_TtV_TtV_SPqBM-BVN90ULdjHzC_CQZ18mMS638_VS9hM07
Jlg9VWWjOZdH8EzX-dEsRRi7
}

