sprite $house [93x93/16z] {
xPK5bXqn30GbMvRLzpzmO23zFWqgx5gcsXgZ_DiC1eF1m2PKVWQEYP07Mg-IGA1_0oX2QW3m13bGf_UKgmC884g-t01qdJvucfmZ4jDuQsTyYdmQaSPd05gQ
V1eHnahXoD-LJogJ1nhZxyYhWpEO4qyvE29vyPIRa8HuoWEkGZBYALUMVOhlvPhy08tZTXm5vTdnDURjanlFtw-dIhhAGJf_-HX-EBu4jsHslB4YFTwvxRBZ
jL-_PtGdllB7wV6DGt8ZlduO4lxVE_7-AYbnysPaV3p76n_e9XLWF9Tf8R95ML7XTuZ5OxpZYGsx1dvWF8i-6omU0EhsDfi1eFpM4thffW2Cpr0NUKkwXi0d
3jY_AH_o8Gzq-qwrXlHDP20XoNAfFHPSq-MFvCk7NCtxZ5ksN0Ea9yiTy3RZGCcLTt0m0lMwVCY7VCY7F62dvFsCt85oGgwdBXSDm6VYGTwTa01KZbC2Am_o
JvYSmjeAlrVR1uhyVGm6Wwy
}

