sprite $house [446x446/16z] {
xC6n00000C2WV_x04wa200000000000000000000000000000000000000000000PkzE4Xp1GI00dk7_3vxxzEvM8b4T76iL3YUIzyDLFwhUKEps-i7RxySk
pvUwAj3BywMY32_FjtSKquk46TuCNzLMFdfx3xBq5jyGePVRJE6b-ORk1g3tYs_klHk7NW1lp8zUm6wCZrx0xba_UbLh-UZzoEbvFde_ozWDFte7yAxTzKBl
aDtByQDNly1xs8_UB-qUcfxqFaUPvADtBdZpVlJEsSsFJthdyERvw9spc_UZ5x0Rs_te1V36-EW5xCRyw0NinlZevV3oXnTw0RkByQDNf_3cuqVlbDry_EYj
UiOylPnTFdxqWdZv-D7Bs-NZHozWbuuVlLpmyl6ZbxFBnuzU3YyVFtevktpyw8Niyl6ZbyURZn-zpXQ-e5wdAkz7htih7xsn5VBxJ2zdbuyVlHnUFdxqqdRp
yQFNgShxqUlUoaUlkxVoqUlkfNxqkdi17xrVV7UP7xrd5iplpv_ithsEZru7BfgG7xryvVteuQF7ZrwUZnu_Uda-UlpeuQFNDUn7J_peYT_UViLlSRlyBZIB
3vxTRt6ZuXVeyrK_UEBdAcht4xoF_E29dwafVW4yVAOcFy7ByHKyyJCryQNm-9cQ-E3nywovRmhUQZzu-DZnEuA7prcJ7po7JtO7uYTu-9B1umSF7po7bu8N
Y9_WYLy8Zv-fANxNyFYPckAt1q_yJ4tnOtVA3vxuFOudVhOyVEnoVe9dzvl7usTgYjzRUE9dQk9ZD-873zzzF7wsF7opTlXgDHu_KvFVQZnyU-turK8yVFln
73xtsebVxSKJlpfGRwf7rbsvIkCjuikilB8rWBU2BxFqeZTYjrElhklLMhog-thq0ekdHuzUkYLwT_4Mw_rbi_HgbLu_eqSlqEuolUZwitQtwbczmxyJRPFU
XqlPh4UltzEZr_JeqQD7ZnuzUlJeqQD7ZnuzUkkA7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUFNZsjHy-x
xT2h5_NeLVtPRz3R_mwFzEQB7Zrwg_cQtaQ-_NhqcjvUlgQtbw-Rtbg-VaAFNWVmw0tMMJjwytMCZjx-eaUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF
7ZrwzEZHopuHXLvMB-0sHaWlG3S6I2z7b_UZbyFByz7BuUNvwENiydpq3k15-UZHerTrWOyUFNhrZ-lHAtgNz3w4oEhH2pC4zUZbBmjwzEZHeqUF7ZrwzEZH
eqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZH
eqUF7ZrwzEZHe_TUqVlguTklLs_hqQDNz5Rp3Uh1EwvNc_NerGAzt7ZPprT3Ul0YUbLVIg--j5uFVl1stQ_6TqKF7Zry0JruIJzwzE1bQaWFNgWMwy7h7hX4
tiB3rmDy8Jo0Cm5Fq06ySCSSk__QWsC10000W47-rgFOLwq00000000000000000000000000002
}

