sprite $Indoor_AP [96x96/16z] {
xPc7bgKu34IhL4xw_m_U03hCI_Dam-RbpdGoziN8gLlWNylDpStDZQdKrllu7H-_qtkhHSRBvjBwy9ypHYl2ISgc3azlhTQoKsjhVGpte1TY5MkxkBSYuZFK
yNXTQ_Q-zykGmx9L7i8qrTr79QOfmzqR9kdkeu00PJ1n-v002PIEOaKn0MYu3sA6uTwvYKo2PD0X-ranW3PvW-vUWNK_Ylj0IjdrW77MRpoQDcGCxq10MUx7
JeJ8ygb3F6BV_K4mtXyWgq739x_9G4jwzuwvX-y9udL-uiqZ4NGlINW6GCdmYRZ79w9HJmAqNoUn3hdtBmb_nHNaZc-u2z3lO8remsypD2wVzpCw-6tw4019
h19jt4iIlfpp0rXy0D26OHvgWza4hTVyoFpDEyuJXlmgDp0FTo82sVBLSe2qmnZ1PFGjQY_xCUN_4pU8uGK0ROEOXRQJ-MDrAo0cKS3O0HA_1PZaiG5J_nMI
3PJH_yK9IktOf5yA5iCl0aZyzZ0Tk1X_8lSB5yZyE1SVKv357rVZF-S7Tp0BWpXXa_tXF9D-1PX5mSJ-Lg_ucVcxDroZ-9ZmS_ktm56_-aZFNvqzlvZuu-ff
V_GmyUSa4Sv6XnjOWHin0xFJMJkdVZySNjBLPr5v0Mqa9s2oE-NaExoxudp12j4c0f1j4ElXETh8FPbU7R2p_SydUFbwVzOAgmOm-VC_6HzxYmx3NL6tZm_t
aA9v6Y1Azfg0W3tvAoI2nC7MgANhN-xQb0SI4Vw8p-6Ny0CpqBqYOJnsuJ7B5Z410Qi_YgN7Xn_8CFUE3NjC_W0a68aP61xpDR0ZErEGKkC69dlqXooAxD5F
AHesP4GYqDxyJFpixdq-lTe8HlpV-lzQ309rB2HOjQLZ3G3n1j-BhGr_YtqM8_VHX1pLuVi3hy2zbOyaVpwY5h6CjQVyVor5aaagfRP8p2UFcK7Lx-ylUXDn
5LEyVl6TU04Z8_wntDpStFmA
}

