sprite $Indoor_AP [446x446/16z] {
xC6n00000C2WV_x04wa2000000000000000000000000000000000000002OlNFHSTr6WYW0ubn0_V__ktbwSCS5Md8les6tw-pcHSGqcqT5YvBbXC9nYIY0
VMtcql0Fnty1_n0Ru91j5qbxg-7G01nxi6n1TTesJg8vX0e63HnL04BmMba9Gh2wIk3biZRWqDsLY5qYQ7SwUvnlp7YmU0XMznxiDXwiReC3d0YyWav9UMFx
WqpzENS4rGRis17K7Vj7vuxo2yUdkgF9zGK-pPtBsPQ6jNvC_BhMIU_udTSO46NXvCYajxpsAqjVUKGNQ1e_hc_7nz_mgeL_MkAy1MtH5-KxLkWOlyibCSQp
B6bXtY8lqXOkj4Z3j4MXcxxBkOj0PcTaMf2MyGMp5gvq8otN_NMIzzlCYxo_qHQPG6PJUjuDGrgqOsb1MXwjLwx3q4sUvk6BNClARdZPCK_9rwhhw-DL6SZ1
dX61j2nqDM-H6YuKJWDvyU3bb998sftsz5LIUtLzhmiuSNMhFNBsnWjxCttrvPsBYCspforSgh-ol8XDxS5wUq1TVPEHTywUSWY5vJNFda9DVKn6tJXxYOae
9wz_zkhhcuwuV_REzL5QdjgBJjbJQeKF6Mx2NhLhBOdvg2XFzKN5x6aDSoYqTfx84tqHDREdz_xdr0bVua2hcRtyUaGVULMpfzGF7zbXKYbxH4jzEiessKFj
vIU6Dj5JVUoOlP26Tk7J8MRMpjWjUxe_w1W-P8GPVSIMsGjKNdvPgXuz1HxkzigUZ6-1lYxHK_RCtlfZktxqb0soPtj4tUpf_g2_FcHmo_J5tTcBXBtQdtoh
nyPTzb1xWSZRO76gO4_rnVtPYrWlBxZ1thRx6UwmHwK3_8PbOU79ctXOOozORqywtDeUEZATArQbZsNsjEFroyG3s5NVkRpyv4XtQxuUepqHI-MflYtjpSV5
-4uiW5Xc3-bq2UCxR7pMgVP8s4kIIbfoE7bxkuSF6TKjziuVe4PQv7R1ZVR2zfxurYqdsPCNtMoFBUqTFsSluFfFJtn1n8_Rm_QcCwT32E5sUx6zFIAnOrY7
g2Bntcjt39jlsETZ8Yql3uDvo_twOdDxl1WJYBl6gB-dPgfaxm7__gyvryhUtHvH1azL_e2olSCZkWtRCsnjJywzdY1QSrvn7Nj3KNzjtPtlrzdPtfWGRHaJ
PdlZ0ZSOX0zAdgutLUmDeQs-wnLJs9xjHTZU1jXUOMpFzWhSMBUzRM-lgptlzvGeQ8_PWVXf6puAs9FX04C8eZMJYalOYoU8JmSYQjbJZEtPNltxZRwxRdks
fwD9x5-Rm9XHrTvuHHGdMoerx35UGzVWATC9A_Ej5gLhyXJAsSFsfDHEsHkTvVMtPtlKjOVj_N3um6SjGTvUWUTcVSwvgJtozk93ztkKo5wGarTVNua7KSuF
928C4TlOImp5sDuzs9wnFNytmlPyTprlRxo43zdkdMoHDzmnzBzMbY-pXhqnEklBbqa5U-C2V80yrLV07cEK3P_jXUtPtixONYdykMTxLCWUZULfcTaRVDIr
Hto6lZYnj-CrEnBoEkeZojXJZEtPNi-1s9vlxzcUiJtRs-Gd1yOfdx3Rgvaz6jxXozLOCNlZ4hIJfr0lU-CYKPXnaGBPixs4lUFZicTxpfxj7JtjsHwLxJbx
sDvanq01Uq53URaZD6hO-xZlHZ0oDHQm9vXjxLcUxTcUxTcUxTaU5uZ2S86gzcXrXozVNqbxuogqagVGsjw8aepBKC_Uk0wzv2cjxOsswwRjASwUxJbxpfxj
4GMXjJsyOtZWtVgDUBT-tHz4LMXqfIm5H6iWeguzOtlxOtksPtksvtlhlhVUUxkNVyu6tvrDu6ijlbBcU-lLzVaUW-_lsPwpPtlE7eNjENk7xwtFe8mzx_UK
A6YF8VZUUg7dracvQ-QFOC_dnJaR1n6S_Aai-G8fy3jbWgdmEsLvRC_Piprdpxy9JxlppKoDszh3lof-WKBPyw-AAmMpnxX6UNd-JVWy_arusxCz2jkplSFs
R6y7R0_Rg_TVxFP-JuaozbIVhxMKj1VGyf7rV8rgBtQofnZRsn_RiptRiptRiprQRXOIPHQqnpWZMf2ur5B0tZYdfJobX3sjojzAqZBPnruaxTKFNxxCclPi
JxD7ONlENdoIFTkpFTixNyJnZk416sSl7pwY0OnJea3sP2o9vBNKTp9Z-pwv_egeJBxC3UnbrW5ZUtxsqlOyORPdUxPNyBlmH74IfPQortkddYYraZrwxzMp
fLB3NlEBdDbIZwtiHTeUqGJgsYDjRpIENl_isHu5x7dbB68FdxMKjAVXetdq4gMglR9RXa_QhHUnvojb2h6nFQRsWYb1z88f4NNitOLlCTYUxONjENi5i3tB
gx9oqdYheCmhBcbl2DtrSNfXWYhs61EYBMC2a-tUnalvcD8zUSh69-YsTxtYxHPEg6FFzfGkzcpl2DjJxjmRsvxjyMdovXKpcQdzzF5SZ7VhH45x4SsJfr3c
ovpx3efVVqBynlYpuQT2l-TNadQzUCUlVq5RTd_gsJU9VdqXBSDhr9azucx6GABtY9gqF61WUpy_hF4zLhz-GrlaHPK_OUeFYwTLaKlsXeJnzbaYzjV7VxNF
qwYDwzaRedCj5xu4VyJ-zbY_rNjCYKRjYZrvaNIyIfxgspHwyv4jlyh2KrTY9jaIh3l2A7D_uVNGM7sTXQSZWPIhNxyZ7IyQetJ8nzkJlbRPMpl8StjiREzO
PkzHlquCwUoXzj11FXgNPU_Os1uokBmzbHMX_ItAdiH5tdn1zlJmtjdUiSGUpw-KpXPaJyOfxyqAU-mRFJssa48IzcGAndtPGrgozdQCdZ8Dtv8bw6hsM9Cz
5enxld0Isy7PUKkijnVgAgHXgCxpx8sL0zV9gH6-YFm-YhUofxA6N8yPCSdUOdlmz5A9tgRXKtsygokTlU-sXbnE8qBqZNUoz-vn29C3UtzxfBDsqTwpFfst
B-3H8Y-wdZtIoyXHm9uCChrGfkmHb-5P-ILx-Js47DQDz4rSNRCNAYz2Fwo-JpdZIzxbx24jYzQa-cjdtjx3H20TITSyfs-wHf-tr5ytbIElZwIzUKVCMXwW
xxtU7aMYf-4xRiZUYtuGDo5aivUVaZhsZdDV_tVsUAURn7kVTqD2NdLziZ_8sDEh0U-T_2Up9pLSdGzYRyxqgIoIsTDkpgTTifRAdafFoAkSFcGkSlPIqpvh
oBUGE9HBXEyuFK_8PIyzxVfMBBKtFv299lg6bBxKtltTA4mcefe-Gf3I-S5fPvcz-l82rNTYhs7s3Y6AS2XyLlOu1AA7llxPOvAyklhczkYMlKCXYkixcDYB
cjcBYJtgojCIpfykYfhPO_ORZagKun0cZnT5rUoXqGicLPVKfp3vsXLP4VVRqp6VbLmH3a6UC2BxIQZESzsGxKPhcDVRHv_M8oAOc8dp5kqckFYYwot40nB5
rk6O4SfuWFYCDrh6l8N5RoNg5A8m75Ec-dYh1PbHQM5DDzfoNYLH6jxn1sCWHWcUMhut81CwjEMvOvvRYESNeHqp1Y4S6NdrurU_F6XSdFfJNDZ-LJOCOBAe
-luKw5LEj8BZdAX1ifB-_evAwle7JqklMZxfmVVtf-1Xrpg4bJe3LdSM-80IWoG4-xlRuRh1-GDGsN5GyMd0iGBkNWCKWb2yXAvNoR6O-6YEGZXr2b1Ht9Sv
GwqCgZT3RNK6O6Dl4ASOIYVE03k9WwY5LrBuHnfH2Q-bh7Lc095Ox-FDGF0lItnz4SJjcFT54i33rGRI31540EV_ZdN57-t1WG00002087_h3IQe7W000000
0000000000000000000000000G
}

