sprite $Indoor_AP [93x93/16z] {
xTX7OhCm40NWLzJc_WV-Yy7TOGJEacz5VHa4aXLXlzFfT3fHakrIR5iYVWDTQX_nmUYjc3XAvIbstCI3NeNTMCUrmbei4Wz8kTHslM9dllhbhcPbhRRKq8Lf
RKyzBF_p6p558sBuiaNGW0H8e0akcz1z4u1xn10cA28AO8CMP2sRNZTvFtFPX0MWH8IHueWXp8VJlZwkaEdhHTAEojUYa2ZtnviAVshEYcqZ6cw891p4NOqW
jlZr0Xe_XDFlXPNa2s-093mYNyCXlWriG4rQFSA0RRmYG1CoFf8DQBDTrjCaiHUvblOpny0N-cQZr-Y0R9lOmxQrlh7aVHuBzrhRndDLVA74I1kD_s47_fU-
iX46v0lCkj-WYEmpf_yJfgqtP1zwXF05HZ0xgGjYrltw22KTLDxNBlGYwQAAk5U20vMFSDRxZnjHad1wWKbUQEadIG-J5zmNxgI7bsLiu0ApxfUtZV3hmBCl
d8_XBGcNL_jQnLFXt1SkBpGHVjnSE5UOmgialFn2coVVERN256h1v5FyklltD9mxHqNDTNz7VDVzHvHioENX7Zh2sI_HSP647_ubKlOR7A73uSwUV8HnM3Pl
6T_Ek2Bh1CTdN2L6DgeTdt6LwDdy_BWQBPi3KvAmYoHnUzm2775yyf_zhyW80VihfoIkTn-PCWaeZQWLqCPpRwan05buGiBDg4ri3MhlVq0sqA9dVSnu-iWb
q8PRkOQxLSY4z1pETCcbnm285G7x5Yu3DhI6syzNjeqkzBwmyRHU8u02I41Spv3sOuixxmZhEpKVrqDemckvVWgdkLRLaEfBxRH_N6mnzBYffUu1JANtxJKe
lrRE5Z4ulQpO183cftK_Fwq80gmHqJ398o9w8IRGFI96mRmobbLWSpkuzlYlOX-tM8nMYyMdKCcrzLXqum2jTQq-ht0Rnz6bzV5nRRvQ-1Max79XYyIMq-bq
-Wi
}

