sprite $IP_appliance [96x96/16z] {
xPY7Skmm24MlG0ZTpFx_xxwwKSPf6DRfFbDTE2wWYWmd9oSdqYsFOYVgh67OGoV9aMQIzBPBFnK5P92E25blaQUJXe11DbInE9Wqb6bXj922EeC3hw8aRi0u
lvp_zBTkpo87-GUVPnxZLtBwCv1sY7_IuwwaxZTIN-eDHi4VMRPFpliJ7Ugat-fNqbwxkz_eTyx4Q97sTr9Vxywjue-JkuIKgdyR7gSuxnVI40PesJz8H3Xd
pRzzjpZ5UV-a8sQGal4dahjgBEzVSJ6Tr8G_FvDpphH_sxU4GJtjjyH4TD8hxs-9zt_B_p_fRra_bg-VLNU9-d_3zjkI_ao9Qg7_oQJOET-o_--alkNuHGxK
_PZqjnn_eMyuVrZfYvDRzqimVzEwFqxnfB_n_5cg_cs5nycj--6SRxb-WV8b-jkk7nt7-D6Vfvtx0mVxJx-7gmLzo_qza0Db6jdtJCPI9ESRazIwtX0X98TA
ooB6VVzM9giOTj6T5OPWBqqqY-0uJkukLnn0MqSN1NGTt3N07euI-hQ9qil2hiRrDByia43jYcoEEW1qkw80cZqSfMdtl7g8AhxvI-soiEtLzYR-kvlzq7l-
6Tewt5uLV55EJdu3
}

