sprite $IP_appliance [446x446/16z] {
xC4n0G00004m-fTMmhajNm00000000000000000000000000003GiNTkItAaC10j1OHG_Vy7x_rcUtAxlO5hKyF9cFVfwDE8b43Y57qwScEkLQTehJN6vq5N
zu5Qep-v67cVgieHhTbbrNsoAlloc_VngfgTjplKaj_w4nwgwBpmKA_bbr_2Gza97hZwHa-nyEeCtNL_fDK3NzH7u7AESPsWCKRc-W1VZGxmraSvQrn7AKRs
39ufyftZDEkRuDcklb8phbCrgvdp7FUNohWELcGhV544pN-rSDRE9PNBOldvEvTH1f_KseDN-dxG-mDuQFM8dVawR18yot-7rYkFu6dgvARuZ2WQvEob4Xiq
odrB6JfkedJ_PHCttwr1USPsxQlGybvyANCQV_7ZNcyV8xFpXMMofoC3YZAs1UFzm4dAdiRq2bGlGkVgzjdGC4w7yqLKHr6-vHQhPDI-ajYE7bhszBHfGTDt
S_aUEmozX1xqe0Szw44FUj237lIWXw07FUX13thGWnxqe0Szw44FUj237lIW1xs31JteGGzwq8CUWjvuIW6zpczph81UuqdbDQ1dyC23m-g3tkhx00Rqiky3
2j2BkX_NWbxZnrLgGg_ncrGBUjjwXfzN3UXrVaCJUfijI-KFrjxd4w2NzvCZld9dx8HUFFoOoCv_1xqbK-W72ge3UliiIpu-sXvw-weirnFQPboWD_-71pfg
Jwo6NjIkTV3yFuNUshNqdizHe3SUionwyItexIXmHgD7UQ2dKwzdK_OAw1a4i0t61Ne69SSD_njwPk-UwNKFlQr9is6v4thQzncyv0azWsBnXbmJUYu5Jgty
huiFUaDOTeEi0NgkLHPjN2Rq_Cvazs-zq8krePrdk-s5dd-se8qBzCokaUttJj1RiivXK761dhDbqL6WeFU6blh6_BC6wCtQrKJt_6LWw8bWPM5SeBV9ilXT
C8EUBktx6nVenL8tt_sD2_I6HPL5LynNG6_RYVRpncL2x-aRd3kDL43Fu0Rdxjjjq4kVkAa_ruJUXhC5B-C2FI_BeWySeRVXAp8gTq9ls5aMNGA2dhzbqRaC
z0nkS6vAPg2dTnR_h05wqp1RqFNpWfv1qya6um8zPGgCiuO1lHST7zx61Nh-baLtfK5FM9PEYmzwPRxqzAyCUlwMHRSLGi_VikYvnz1BzxYff_10BzmjYwug
G2_aNk9lNEP1zFpFPFV_sFhJwszPTA0_bfws0PsCoz7qHW_BegF5qVIwM1PTN3YOtcopzFJSunFfwRAllwQ8dGVGwsfPT7Ne07hjgopwwkbnz7IBUaVZSW2z
zfP5DxCVG6_35JlR2sO7qfiRckAwjANqfzS_Mz0Nzm-Wrx_AegVm74PlTBGi-gZeB7hnUjzeVqxRdvx_cUokHkqZwEas_kR6vG1w_Qiikjnv3BqfnzSqhhWS
Gw-pPT7Z0m-XDwgpPT6lVfn1RxMsB7eWvHdqMcSBEdRcUVIktffTwB7sM7lzKtNjlmwW9_k_-nVBJipt6iERP-Lx-aPB_rfB741FtybgVq1x3Bsht-BZZ45N
2FiVCPnxjjw_IfPdtMkPt6ln47VAQXvzdpDxBxqy-oxrFLhVfHu7qEkx-EXZw7yhKE_Q9z7J_T_-ed-lV-oCpz8xIz_wQ4MFcH5nCpF2yQo1UIrTNmdUx9Nz
wJ6dh9WHo8p0fyHypc8-fwhLTwwoC9UwbsL9PiBFjZFXLpIYntiC-bYhFptUGk4TekXo9diFw8d-xpQM1NfNEXYNNVqNl7tfFu-w9lJ4fN9JyUviB-EY0yJi
Iu_trjS5lKvjAR54HGzwefdT-amMUhg1ttyi4lHqrj3h1YVqGhW2ut60qFCtBZemGC_VkEXD6NhQrlbFrO6UZa_-sGBqzErErwOJwDaR5rs4XPv_Mue-086U
_SDWUZU6dlyK7hqPGy_0kEohia1FNzloBt12JzzMzhSiqDF6nT-oG4yllWvL5kZfEw_-BUhGqoro_fO5UlgSrh1F5dh-pUowDmrw_iP5JzM1dlyvROZz5teR
lZYlbosXfuEM_vaizBHnyRSiqDDclSF14FHqekn_ZGnw-klpRr67dlx-N2mBzFoDY_xVqFCtBlfVGy_Vk2nHB82UUpExtdAXvt_1JFzgeEVVbg8BdD3pdyAZ
BGlq_6TtwWKFFVkvntgpXPx_EMt8fGSz_tAddbqCFVzpMb7WX9whST45JkZjpPrpvG_z4rT9eRTXEJohWDwknVUyvWMzJHdOyreNzBOe6oyzw8tgk_IWTwt6
bWLwLpqDBwzjWjvy6DyAwBKqBlkhBD2Bh0VXnGMzlOgH3sbS5_GGz3e8Uj237lIW1pq4FUX13thGWnxqe0Szw44FUj237lIW1pte8UX13thGWnxqe0Szw44F
Uj237lIW1pteGQ_Wr9ZU3QUNzCRbfNhLCepAbrv-nwm5w4rBUZgeeo6QEnqqNzWMD8tf3R-uu1kTrcMcgCQXaozelHiO29pti0qCXCxNuuB2qLBfk8wc-TVp
vXCKx7htiCndv0T4gPQU_-93m-3n_ntlNX0tAnfyHl29wQ9fxwjOVNgyORW72BtwW3UjD-SlyQ7u4bwwvwG4J_sMH8q-d_NEE9pT5Ay4-CTEekTSObIvCpx2
ftX4ebeuh2zLCyv35sE9EVFTyDsrSfn4S6JM4wFAdtotfEO9-e1Rh-i-MJTg43PrseT4xjJFRg7PjZw4QhJDTj2CnkLPx4fB1UQpSdIkqYxODI-p7og1hfl6
pAew1rjLfK3NKn7ZL-NFxTe5gYun38RXX0o4GFQ_tIleyTFmzRVoFWnUJMtiUF6VkpqI0000000000000FYAGVPf6G_8VmfFyH-wgvPbscSf_iTtvIZ_KRpN
kNsXUg8-bP4zubhzVTb1l5eRlkgPL0RlFtilUiZj725EtEYf-BpqbJRqLDevKknvYj4BAJ-ZDr4RHg_4qIlNHg_j1AmzHkzIppr6J-3po8lHKnUlYzCdx20X
TZnQUzxpqeBlAUG_G0u3huGltQJDjrpS_CEEux70VX2B7ftVxSa00030pPSllGpxoR0CHDQwopUKeJSbm_w3zqZP5tBFAyWOVlw3zr0EeZuC_VGzABAdNFvh
eclBTn1uzLG8QsRZVqzjButHmqD6hnurUfnx6sP0xZdtu1lk5wE7OaDJ3FFGvxOoFelgLHNs7_ngFMZPozBrfgIzE0000000000000000000000000000000
_W8
}

