sprite $IP_appliance [446x446/16z] {
xC4n0G00102mc_vzGGtRyW000000000000000000000000000000n2_DtftaohNZO1WSK_jVS2r0rHs03_Bd3CuD4N-ODtiA7S407K1q0Ddnk_0KEtpm-AtR
uOE73nw-SFS22Cj98MmdYBATBDZzLxyo7Z-zulk72ju3FdZfLE391Tu7lcQF-CejujEXuNlK83xz6Jvuyg573z_JWaUFtf_U6pvw-qKF7ZrwMlFWGe-UeaUF
7ZrwzEZHeqUF7ZrwzEZHeqTFqQD7ZnuzUlJeqQD7ZnuzUlJeqQEdwBtObqnl-u0m7xqk7xsPB1-zeKVl1H-zUL8nFNhq-dZq-dWpPJrwGo-sNg-gH-y-Zbu9
Zzw3NUK5Fdg1tVRqlkC5pgINuQDtvqYFtjTZwNNmxdE7NWfl_sHwAJvwTuBqw7q_d5u6Zzx-yxuk7xrp0dpq5hAZH-zgWLu6x-vXwCNkZwQtbDjxlQ4NkxgT
ta9g1Jvwx_7eRV_TxFBHEt-Gtj1R22moVFJEAV3HsyUZH-zgY5u0R-DncDxxeXV2-zuKlNqyUlJkjkW5y9QUkD1xN_GoUD-7ZzuTKNRuw9qJuAEtYKUFteVs
w0Nmhlw6teTmGiD7xvm07xqrF7hqlZH9Bu17R-4fIuIFtede3Rq0tfTEwNNuwAtWqQFtlLbw2tZFzERdzQQbT-Wjf17Yw-ljuz6ZjypNrolZqLjuojBZetUI
UlC3UW6yXRxffVdwUcKyUWiF7p4-UkU4-NvGRy9wz1Rm0dnzlNqyUlJs-Vfw0RnzlVaflUdh7NhNlyZo_O9U7u_UBEW5-7v1x_mbUaClLZ-Wju3NuACNA7ev
F7fcZnuzUfvpUhr7ptijtkVqFgVF6EZvVCzdwu6YvtijRyjtolfwliz9hu_NryloqVCRehwUt-_vxImzUk_nx8oWHy--5hkIwDbJHi-EGFivwTcDczEpbvfU
WCzEUFSnk0k57Ztt4Ba3Z9xxznwKko_fkNUMNc3q8dhkMwSt0JnwfU4RUW6-XVRe5V3exVEzrwCtBJnwvw_HepS1F7g5uHjw0RwzjkXD2u_U-Mlqw4qBZzu9
wj7RvtkEHw-2Hs-Vxx4UlUdWqRi3Ax_BGcyweqVlZYo4H-yEZHwzXJxe1VZezP-ut7ZqKiCtz69y-otG2-3HMmYF7htxV7eflg6tc5zdzEZT0RRmwDqHqgFt
_MHwARwX5-RRFvRU4pnwx_dU7qelX4VlZhAiHsywUFJkC0Duz3x7IO_U_cdqpZoel1wzGw_8Hw_FTtvUZnwzKyQZLyQZT-ZHUuD7xvJnw9qK7hsxNjZHK_Je
qQD7ZnuzUlJeqQD7ZnuzUlJeANhqwD6ZHuyUFNhqwD6ZHuyUFNhq53rwzEZHeqUF7Zrw_OZeqKloYOYUsTil2U6Zf-Z1wsqbfQSz_xdt-pDw6ZHwXeyUlZTu
-0Gp-1xWuQkdWaycW-yJ7hvK7jDjbzte6Du_tZA_PWupOK0PZFg4XmyUFdZV_U3XOySFtit7ZXyxVkmM0D41H8SHsh_QiuiiXu4O2e1hpUlxNtUOAL4aOrVj
c_GJWxmN0000000008nhtVqkHa9X_MVbzK-cUlIHi_Nuc2-y-Z_dGtbySO9vquiTf1VVnyyRN_swbLUTG7hIEpZfIIzkBvxqF7F6HE5vtzDhsR1NKbyV0020
aH0zSzJVIMbhOdHriR8_0KPMmnpHqyrXf7NDePCflOEI7j8x2kc9Bmfpj7z1P4T_c_mKH5VTwuMFMS83000000000000000000201m
}

