sprite $k_12_school [93x93/16z] {
xDp50OGm443HmJ99_mMlLB22mtl8ZTF7BJO300000000000000000000000000000000000000000000G3zFx8SXwomvnLwOscovq-P7Nzjy9VPYqvklnYue
RGc1UgYt6VLGJxqolPKVPdcOUkhDNHRrK4yzzTH3FTHJJptrK8-YddgeXtgpg8TwgAUUUkgX7kgffvvwgAVUCFG_3b-yZOituL5FFVNKGptKKo_ZjDJB8KvA
lNg0NoMfDmr_EcKyzpbH3_NKGptKGptrK0_rK4yzr4CzzTHJ3_LGJptKGxqdUzUXupmFmme96dx_1_xt-B3EPXgg3K1-0-lWNEII5YrR_GWiwflHwr_KCn2l
GNYlco3Cd_sjTJE4cgFUkXs2YtfRY7p6c3t1NYE8HO0Geju6aaxhHO3GFhkHqJT0cFrwVf9Iwvlzorvq-ArK5wmdBL_fMZu_eFoFIaiuxzwvcZHxB-5c1nOF
vhcgaJMvnWeFomD3rBiVQyho4Roba4EMpyd5O5c-9o-midmFJcwrMzRCf_HmBL6MJsPFqYcpDvGDse0yIpWVvyH6r5cMJvMzfy5-E5iciwUyHSBvuCfRp1mS
bULp2ISLpmklzP1mgifdZyjf1IexwhcLFLa-8vWzWHnX_g8gyDND7YoSidokojvaBmUNS6gtx2DcJzBP_k3AdWvskev4QBTiqEm9pY3V_2wPyfRGBfaETdx6
xCdonHSlfkwH6Pa__8T_Swzvv6RKSBlqs-PkO7U2odtbIL_BwbvRT1SIaZWTDD3Nx-wJSTFchTbytJ0OVIkzE7rjB85nqmZzL7XivZVAEcHADZQgSVh8beqv
QzpinLoVBEoXkK2KSPe0jt-jq9KDCW-Ha5mm4feyFlluIfSVwWvfZ5wzGUg6M0JBHwmwyTkH5o78grcDI6Cmte0gzQTw8hSJWhoIrCgoR4GwvysUBKQWQrr2
SQYtshudp_2ZvGSVh6E7Nqt08KKwWK7RZadG5JlKCQc1ZtWGp1wXLW7VaiSlfk4xYPkVXBOJ-PQFN-ujp3dMqRFzbo13KSxJPQz08qkmV4mHncSFV7WSJOTZ
mfIdB2sGCWIFHX1EzkmbO_PUhDbBOFO04MQP3pxtkBCNtDdZrrFvPa_Su-SjkDbxFlVuwnu_D-URFN4F1s22WELJt0DcZo2TVBCdxl4EIF37KCv9lpV2DtlY
7ZVPvvizvPnyoyUlyefxyxjbm03QvmHc3tptccu9AExTMSZsSS-Xd9DIMEMVwXNtgCsE-PKzvPnKoySNJd6FKUNZzt_NFYUp7ohVx8bxtBo5xnQLStAgVFCz
oiKzak7cvopAEUUbimd2AUuHAdICNJBbdDJTCk08Vw889t3lyQTnBH95zQNrosgzWyxj2peM3_leIVYszq_2Hw-tOB3WNaTkSs27xIhUt6iJHGVMViXYCI8Q
i71UH_ikq9t-CtwzKrMdboJBDwXBDy1MXV-C_Fa6cFLw4uNkak7Oik1Hjo_zldVtzIxAW5o7HFIy60_2PVWLh9lF3E5SRPFSkt7aBeRG5slvTs0aoctu973l
-ckq4IIkdTRnWp9xEU8O_e7Vo1Cda8JMRQUDCdjjM1S_Ke9hHOWpOT2BBgsSOS4ABZBu1SG1Non1vX4SQX_ha1SuUTjZ9du1zfg0RRW7HwI13eyD38geK0CV
2c37zllWXuo9h3w9SZhoyAo53xg7HTMHkeMzXcPlddkuC1iW6CYWCCpULRVVsRkZPGXYA0Z3Agc9y_vFx1A0jd5ighvs2_Ydqp_ix67qveCSUNA-_oHbwPxk
zUsUdEwSedlesJtqE2Vdr3sxXnxdH4_tE2Twd9DpwfxT4yvvHdGFFRk77kVad6BtqEESwEaUvpmid5Cuf-xPFVGuf-wXP_V6l6vAmwV9EOE7MyPPSxGxf-xD
05tuG6Yxrt0rRqkjJdgSSmJ5st8d8jtRUvFTG_1nplpOpBEQw77EMVke9TSRv-m_D_ExmzczXeO7oMuQo3bxLg_MTTFBgc3vT6z7QcDVPWNQoJat9BYnV88l
lnGuPvwvzwnRmHN7EJTUnwjng-qUUfnpegTxwDazpddaoSavTS_keSSvqTCzpebU7ix9ENNFxg77ET7JFSw97kVadBgdUtQFSt9EtKFFxg77EJcdxjazz3Yd
xkaUvqIFSt9EtRDxw75Ez7GFFRl7EJcdxkcUtUESJaxTqpsxXnxdv9owP_VGuvpewHxdH8zpSaxTitlZp_8PlV7JlA7NyJclCqxEhhodTzLFtwokqVuv7zMz
VdehUiFxeOTUpc3U4pqdv-CDtCFe7dhepVFerRnZUjNwdHWlZ3DiGFmqcltFqjYVg_xh1uRwzVVmwZyuuNjgrwwk9811003omYFIVyFtVUuhx4m1SG_xnLrz
VJddlQvOvjkMTI7vuvmpNXXr8IDQ00000016Pz7RMBrbxyuxlUsClkRfRfbw9f-GmUkew6fiS--MMJb7j5KMpdjM-tIsLxGsQZQMSKq000000EH-7tNFFq3C
svvvvqEaYBz_8M9mdK-WzrxIUwAE75ls-GWxx_RGoQwuRRNUmnpnI00000000000000000000000000000209m
}

