sprite $k_12_school [96x96/16z] {
xTK73Yin20HG43Puxd_WNyDMh9KLyYjFDQDajXZ7zDkLKaefpOwKiWsSS7v_ayqd-e-L2VtLdxk-V_vyZW_lBwOFgNxkZm3jpuH27Lae16ZF00W51A0K7KO1
HQSK76_iLvh0qEYcOL0ImOWlcWNWyALbKVHeqNF4epYkGyloiaUUy3HoW3nSiTrE4HvmdU9e_ZOKUbaEFqc63uC1dlWbrIFpQBQQ04z6Z87hLmpYaUpHRHgZ
kZsmURz2mcY-cmnzeT-U-ndWu5F6_NlGW-LEw8y6Sg3pPc5zR_sy4UnNP9oyejv-KEyVq9_9Ve0Ox1Gr7EdMFsxzf70-QR8dHd6aE6eKUVMJt4vhtfDRrEP7
LDo_hlhdgb_qf7Dkl-AA4_lzxs8te7dzyVcJssyP_TLV_TNFd-sF6P71CGbYp_rZ-aCzz3DYGly9bZLCQmOMqPfkQphz9xY_G-Y9uXtZTz-_AwMKhm
}

