sprite $k_12_school [446x446/16z] {
xC6n00000C2WV_x04wa200000000000000000000000000000000000000000000O7Rk9Bjj68YYwBYu_mLdd3v4-FbLoNt7Gwk0W-lU4jvg_h9hGV3s-C7R
pmSF7xtzqHCzqQD7ZvxeqNleiQ8dUlJeqHCzqQD7ZvxeqQD7J_H4ZnuzUg8dUlJeqHCzUlJeYPuy6vSUFNgY9thqwD4JFMt6qsOyRSRJDmXp-wsOV0hH4ptH
eoTweYTwz4HFz4IFdkY97ZtH4ptHe-Tu7admyBNqrC4JFS73Lz8JF7pqw7rY-9vTJTFN4prwyF3Hw-l1mqUFNZzwGo_DLrb7zEZ1mzVLemSF7prw_V3LyEZb
Ln0zUl3mbVJeRSQZDzlqj41FzF31oqIF7Zm_TPRqyAt34psVV0KzqSC7ZrunUdqyVFJeHV0IToXCO6XWy7QzkL5gQ6JkfC-wFt5kbXfQcBjVRsuN6neO7E3R
ZJSJ6veOl4ilZpUHeLFORVdRL0Ll9g-NtsrVxohfJMHeNg_F5nYsH6-cmVUvFmFDSMyDxUjTOJrwzCxVEp_qUxmtpsd3zz24tgDxcFFTqllJTvyNz7QTUVwt
Z-kVqxleqNlmrAUjHwymXbwFZnuzUdc-F1uzUlGA_rwWLplwQUlHEvys2_Je1GRGw_3HeqSlpvV7eqUFNk31zEZH2mWiqgENnwENvwD7ZrwCBu_NrwDt7ht0
eTx4IwmLEUWTpyQTcJLwuvdmmHFjwyqS_7ynFFISBuytB-BDU0LOu4IFzUZHM_pAPthNVw5tqTjxuqTUBy_djftSWURvt7ILEyyydrlc0iUPxO-MY-mxTXhF
p0qubFJwjwkchuBThrUuApY0TxZR_NgYrucUw7MY9tgTw8bU9tgYrucUw7MY9tgTw8bU9tgYrucUw7MY9tgTw8bU9tgYrucUw7MY9tgbwEMRHxe2qGlOvVpe
vUtoVlJoU7a-UdcyndxfpHJuwCNmydpqwD6RAV3HeqTlOj5xMoyrYrvUhpAD7Zrw3usZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyU
FNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUlPSxNViJzaplUEcFqgCNU6GWUlJepJOzUlJeqVDz3z-rM0_V
-SBrZpXyvmlNzdnzQGyE10000004-LiFSlK600000000000000000000000000000000000000000000000000000004
}

