sprite $laptop [446x446/16z] {
xTm7gkmu48PHGw42xN_1Cozt3Y-uqO_FMO7eJog7U_6s7W000000000000000000000000000000000000000000000000000000000000000000002gni5L
fQRh-GLTUUd6J2NWLJj6zCoaKkBDEnYcfdpY6PvlZSqUTMoZe_ATfwlQE7zswfov-ICTbVARrBrjncbyHYppCXuTSVZknwCIVfXwiCKO0QEp7RrNKwa2bqYl
_yBbuT6Zr0kWddhggQUUUgWNG3trr5DFFVLGBu1wwgcdddhgeLu0zTHJJptrr4Ez0Egffvvwwgc7UWjG3_K2gAUUUkgffnxg1L1FFVNKKqyzr0kWddhggQUU
UgWNG3trr5DFFVLGBu1wwgcdddhgeLu6zTHJJptrr4Ez3Egffvvwwgc7UXdKKqyzzTHJ3_KogAUUUkgffnxgPL1FFVNKKqyzrCkWddhggQUUUgYNGJtrr5DF
FVLGBuDwwgcdddhgeLu6zTHJJptrr4Ez3Egffvvwwgc7UXdKKqyzzTHJ3_KogAUUUkgffnxgPL1FFVNKKqyzrCkWddhggQUUUgYNGJtrr5DFFVLGBuLwwgcd
ddhgePvwwgcdddhggQUUUkgffvvwwgcdddfJh1jzgXUxHFLgMzPuSVWCpfcmnjxkSlGwOP6pDkuDfH4n8EIx_xD4J8Zx-SGRAGizhLIyc2tTyvUkRQCwQKFt
F3FguEb6pvEEsMktY1dpj-YWHvjRLFBSf9VkzweTmnNFyNF5S_oUJCt-YNcf5v-QFROpr5ZwvdEyQCTOTthswvNHQqxFUkkUYbfnUevtznHZjHbLVpervUlA
cPhSRlPo9VupVhAQiLFJk1f_zhT7vhaHVRlYviN3Y-dfTcMrrrEcfkbfQkx_AvgQfkU2KzEBCw_6JCyoDJzn6NAxulXzVfzuSUPsnQFV2hSh_khd_n_agtsd
9cF7VBNtrAJscstzqOFdqQ_YFdj0xNFuneTlLzoyr1xFazk-sEFwzEcnQNXsu4TlgU2pnzZXe2G_w_aUtPWddM1ibwewm4vlMsgcwV1FaHpyUn0TlVmw-ZUG
jZE7_oY8Ue7nJZfuShRFyLJ7NZdgsErEzzqfyI9tNe_QCW00000000000000000000000000000000000000000000000000000000000F0_
}

