sprite $laptop [93x93/16z] {
xTT5La1144FHj9Ha_njcZeLJEEGElxoMMU5vPcPcPhOZ9-902x8do89oc0iJAtWXL6Eg6q8Nfl8xueuxxhZZZZlkkEEEEruo7ZoOMKm8gnbduZOtXCinEPCa
--oPa-oDb-rcOEwyzdkm3zvZ5Mk9DmDYVsTy9VfcBtj3qrO-dNRP-2Z1_MH2ZIiju5mbwabyDxKBDAM-U69fR_iCFvUPcPaz
}

