sprite $laptop [96x96/16z] {
xTSvZWH024DHoo21xt_XYMThIbJIYr-CFY84hy_CpCpCidgbYfYnrRNIKc3K2YonXGcLMAFYOcH6vMVrtNVVVVVTTzzzzzrtF-_w4pNMIiGar1axfSAeTA5Z
Vg6AQzd31Ia5RfIQ-0zBHTn9AV6ta1BNsAhXj8Kvz6ljNaY17rA9sVwHBoKF0E21qXyhJm3KYSGlZ1a1n05YnypCpEmB
}

