sprite $layer2_switch_B [96x96/16z] {
xPY74jmm24H122nkyl-_cvwzejp8C2ZLR-gwl9LxeJ-BYukB2nQD8qpdaE4vZbCDvfyPSVmpGaiEzo6KWFLCWReR9U7Xljf5xWUbuUNW12D8OUwh1GPH7buD
xyZjVU0kVv6_cV9ElnWAjlX9KH3rnmlg_IY8-TC5zNuKLFbP9hgX8EFlsXwJ_Hpbi1z2EU7l5FR3r-Y1DY7Gn_tGlwT17_07z0fzm1_KX_pndHFsGz_R1DCT
XZxWNvtfTAT1lyTF7RQo_KCpfSUtp8-2Ud--87z_gFUl2xZtl1y5S4p8D3FtV5dV7lB--ljFig3UZu9TVXJK-Tj4Hq7AtuGslZ-GcCcMzn_ehMrvVuDUwjy_
u_gGFwuF-UFwg1_wpg-KVN_9-pCTDEZZVhKtq1rMwCD-LZFJFj6gde-CdHiWu4T1kH-WO9EVKL3b7_072-9-5FGTVg0cM_t4VzV_iOCe3w_ywaufi3gl1g2K
Pomt_y084fYxhFUWIrvlj4BSVQZ4CNS_Q0qFps9q2ZaymJ2c6Yxq1eX8xeanyvu0dURs0J2HtPCypLGap3m7smzqIeX8Y7yOyhpfYlHrnzizKW88iQUdmm0u
Mm1eZemaz7zoyGa
}

