sprite $layer3_switch [96x96/16z] {
xTW5pkD038PXuzVu_XTUJUJA8vKogPVp_jZ0upA4Ehkwkhgw4hL3wHGVnTdZLD13l6nnDXpXntP2ox5kXmPi4KhdGeJJXopvimFuuza7dOuZxECM-dQzVBW0
-7ZhoZlUyNQyn_RHvxSyeFr-yIFjzejtZ6_jzvDd1nkWxNxov60oGFfz6_pkZm7zFXjJ-gJIx6VfLt--ptPFog-5-gqlkEVbA-vPX-ylpd-N3tbs_RFt-6uv
8FtYtLfyoW7f5y_Qu-U0z8kd9Zy7f5zycry3H8h_sXVNz6l0nAUla7E-ODzTQ1h0d7mzvoaWotxoJ9K1YeZDaizoyh9VV3cnTok-1gpwnLVRpkSM3mEMV04W
mlKzbaOsB9vNYWEouWiUilALIF6GBFZiUDnzldxaOGFdmtuEsF-PqzZ3Y_SMAtuDc9NRu6-G5_oAFm-e1IAo_td1B_WF0zAjVqPS_9gVa173Yi_bTlzNeFd6
QzLFI4ZWCp_FokStLlxw-RbuhW5zp__56sf0cr_y_Fe8QVAJd_qSqEB3Nxq_WVyDxwy0rv6Kppgo9Z-pygU5l-hz_-Lp-SpzliBkli3xVG5iz_E_RfyKiE4F
djlz7E3Gv9lz700Kt-wJ9j_lPvhyWhzsV4-DLuxlzH-VT7gVHyY2kBmpRx6T7M173a1hHFYP2Og8ZUd0WD6ssjW9J0TYnAasewEfBQT2RLrTNLrT_G
}

