sprite $layer2_switch_B [446x446/16z] {
xC6n00000C2WV_x04wa200000000000000000000000000000020sRiJtSPn80Z3E1lbvli_xnvUp1KgSBnXPFxHNtFW7WZwt6LAoeZNJIwNRoCt-dR1zFWE
TBVhfeEcIzykde45l8-T6GrCTFkHD2pWphG_tzYPaEqC-XlFTCZVU2RarZGXw_LLmkLxj_EJz3MIf4Vp-3BUkTX9Nov9m_ed1tQTz2MJeoP2uVNL0xhhkRpc
-ScWd9CnbsQtOV15l0-T5mZUSUJB_iVOe7XgykxacMJtuHiBRgWxVO33S-KPrkYPhJ_T3uxDPEFXoqCziw_U0AythQV7HsP2q3iUFPDjgpE01QS5PN4kMnnO
d2lY5r-URdI_-0PBpqnwg48tP3spvMaQuZt_c8-cPm1wHZrcr5DFFVNKIzsZ7ZBr8-fH9-yUzMYftqFMKw_K0-DLaVNKAxAUUgKU9gavwc5I1r4FpKVMKw_K
OoJ7VEgXfqyzI597KG_DfnwwFDL3Jvzww9MdUkZoL0zTdkgX-TH3bwTwwEbJ3xtoL0zTdkgXorCzD9zwwF9K3przwg5NdkgXorCzT7cgX-PJ3rsUwYrFdHZr
G7Ppr0FZLQatdVqiM5sS5VNcayyOlNlKcqy-O_JkKMy-zvZPgr9l6XpEx5LQlIfd3wetZqqmUdxlfQPGz5gzcf9cy7czbve3kLptNajgdLvEnbFlmIhykUIB
uZE6LKy-pqzyliV5wpfAgqV7u-jPcsGzQvEiPssIzQnDijxLQZDz0Jrh4w5dRPBrN6sIzQnDifwrITQpDibwrYPPpzeawrcRP3rhawndRPBrh4sodhL9rhCs
oNeNg4trwiIi7Jtt04kTcxZ_tZgzrDbPfjVg5LRFVMTJ1U5pp-S3FAnUgrTOlURggTSKFPjpvckMdgkMvEq_e5w7eNVFCZklri_7ou-_S7hUAJkEUbqdfi_0
ymbHEb-IFYC-dKqZebutcayz7fzw_F9KZr-UweNCfnwLJpr-UQeNCfzwL3xr-EMfNiXywb7vrEENfteXywb7vLEFNvxgXSod7e1FFK1vgWSkp_cGr4EMP_s8
Uhpoh5h4vmvkv-VPWr1l8xxu__UUppPw_-CerCkkUgNUuoIxwfLwvtRM-ViNgvTTzKgzfyip3U5JRoxFq5xmg5ucFSxBLTNhJ7OKFlNkIV8wEzzBpKzy9xny
wk7BKxtp4_SXiZpLEo7kl-VqgGVWKmyGztnsvQaUe3pL8vMdUkZfKm_DfnwwFDL3ywc7Ba_rqDEd7dhwr4FpgRSyIPqMzTOcTMhK0-DLgVUszaB1c_dyIVXF
-DKBejvyyZbwfTvKU-7ebNfBtjQGUacYtjkvSVP0UbdnigJiWkSRFy1hJj-s4w_t07fhtxEn2PvlcKFmjNfr5CJDCfynv1DuvyNdUzyEJpq2Nlovbhqdpvyf
ipRToQOw93o-dfD7rXFFtHEPU7mzLvjaFMkJhETgawpdv97rn2FhkTeawxdQ9EjPcsGzLvjaFIUFh2SUMS_L9bdFoIFhNG1FlJenQo_qt0CiLGNmS_-z7V2g
bkcrUeNLSz_PL47utFFv00-hr-eLLgz1Ukfb2TxvUkhDVAtUo_Zwitojtdy9Hozl7pggrnIy7mURJhTwh-9Bhujw2M3orDjW-j99Burwntpfh4v_GTJh7FCX
ebuNaqyzFfzw2OvFFVxqgSVdKwyRpQSUaqyzFfzw7G2VUlZfKu_Ffnw_FDNZJvzwV3xrac_7vxjnenxWeEXywdMZ-THZygd7vrCl0V2fHtu5ZtfyFlMEevvw
hubwJTPJBr6FV53geG-AUi6dtkpNtAYNXaMz3XbFlRlQsNJg6VNKKq-znm7hgJVKKs_Zg6S6Ly_azzaZVwPipj6R9FbTB_qWucsbr_qHFRFfXppJXyeyggXD
A-7MgBWyIC1wViRLUz7gmEhq70tmgbEza8VFowgR5msFFj_xwcM0Xy-LGPuOFlMocrv_cC_Ul6rxV8_vn8iVBx_r5kiTVy3C09oPyGwVkH5gwVQ1ezJk5iXn
3iSleU3rTAIEtvZFI1Wj8LzkKuBf-7iwpXq3htCxYeiL1DuFFWLlXmbfZMLmjm_1VE9rfuKwIZ2BBMp4Io8MUD6ME7xWE_RvRSriHWTwcyXq6fZeXtxEul9p
TC1wIMSuTjpytQvzv4eCX40OtbONtF-wB-Te11Fi-JzvNL931oV9acwhXtha8v4l1G0000000020S9EyNNH3GkuB-HYK9VvkPOdy0pat2_yaiYHy197P6xPM
5ibsAyGQ68VblPCok-tBgdMAXTCOnuvbj_XPrzXy1xldtLE_-5aNxTetTjvtyjvTf7jhl7lEStMFjQVvxjtcsek3d7kHPTu_PPcwTUjF8ati8Rh1zlMVzvQw
vs_CZEC0fDKRj1Jz3KkEyixTcaLBFWZ5PXf9Q8LeU1oGBmm0041XRxmq4H9p8MWy3Cw6oCKGA8j6GfO6GbAil8cQhP6lthsGEZwy3tw4o3gwrw-POgBmZH0s
pe8h2ccZUne9sVFEoRcdHWZTk_Y_Uelc5JGVrNZUkpn9MJBozNxYqtak6t8KQ2Qa_m4_v5VG9YSEaNeXnmS00000000000000000081x
}

