sprite $layer3 [612x792/16z] {
xTtPajfQ3u3HEm5dqli_xJ-S34g5X6q4mdHxhTj0qIK-l8dna7C000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000083JvK3ovRWSK2Am
SNya0fkNpuN2L2OnaGbCPaXCP18JcS9KXiH49Z6HSV0XpqV6y83DW3yCzrzpaM6mttt8o2Hc60mFrJoOdgYHC3rFC-7wG51EJuoCFuQ7QKk6KHhCJJPZ9kFJ
QZJiE4UpCKS--cmaPZgcoEajfsCry17437q6ZJ0YtdD0f_myD1Osz7Ca5bzyaX5nVhy1nZSQcwQnqDW40umV6P76XX8hHZHDOs546Xigh1YHneOIAqOqJMDX
H1eRAgmOaSQ64Yj6D4rZOKGQ6ogi69767XKhHZHDOw4nZGqLLZJMfx7OHcFJD1OQwz5ORAUn3et5FJGsJMEXCOqzNbX6oLn4fZ6DDH9RD1OQUup6ygV6-f5f
J6E_xIVARphKcCRwYMrgB3JMfR6yQgmLcSOqjYWdog96ZMciaTYgiNva6jDOtcWiDQQnvoHstLXvC3ADQImrDajZkMmiDVO8ZUMDneh6sZIM6fkbiTpOM6gi
nxwBN3PMx8Djq5Ws6akDQMoBgcL3OyLn5nfxM1GZqfZ6q5YNnZIcCOrf38rfJ6CQqvZ6q9Z6DAOnZVNxU8V6uejFrvZ6xjDfBBRIcCPwluc7nZIciOzDOw4n
ZMdiiz2OnZIcCJIcCOtvVwN6D8Rz_1hJMFFtIerTqTYhVXC_RcCQYvSqTkZjcCRY1Ot5iHlJM6XiciPYkB7mdLzZCTfOQ4nZ_wEnQHgBiSOYDAQnBuOQYv_b
KHhJM2uYcseiZzEOndgHHUdTT-b0ZMbi4TbCOtcanZJMYonA9x53DQQnNcHH6WlbiHhJs2AoWSRoO8rfh1TPb4PYnsfCOxt8eZGMocCrfh5MPFt6ydYDQQmN
MPH6OiTgJ6EzoA8q5ifZDQQnHcJjnlAGZMci5rcKEnBJcCQki-Wt5bTIOnhR4bc_iTIOnlurTWvlQanZpSYsBfGQqrWZijv2gJ6DhGCfZSG-OsCQYoyMZJql
iWSl_HDVVPp6D1RVB1hhHTP_zd97y4TfJ6FHQAmTsUExFoBAnsXCOwjZnHgXD1RANcFn4HhJM3GQQqIsU5wtiNZ_nZJME09r4KidiNvZyUwDQMnv26etb_v2
MROT-_7UZMbiUGngbdPa_MTiQYpUkJ6DHQEnVZBzivkQcyBvnZJMJ-pXIa-N7pNgQBpe-pMciRZohFVxSgNHHlyFdszCOxE9hIExbB98R22omSOqrcoZANvo
llpQbXViL_P-ZMainhOgbzyuFp6nZ2ixDAQnwSHAH3cTBziYonoCRF_6DDOex9Qen2xbPcJviFZPEpMciRYIZxdwChQAB0SQYnqQqzXqOgKIk-bKhpSNsVwD
QQnHs5gjb3VL2uvKzXwDQIn66ijARBbQvbXZiKDZ6fjEh5HZjzJhpKIsVsCQQnUsThviS8ui4vNjtPZ6Oh2nopR3ZSKEZMcibzXSOzEHxTcOnXg5JJGsNTb-
ZMaitgAnqtXZCTwOnjuoiPBpaUtJcCPYnFsDdL_nP-tHcCRYK8t5wnlJMBnfOp7brOrfBCOyrbZCUMrZ6elz6oiQQz9ODXBJcBLolZ7Vntpd7suiDRQYiRot
iJ-wVvTz5_R1Pcyl_tXXuurfh8o_b_SaLZIsuFVAHcD-4tTips1aVqmcjl_nOngRZ-nykUbyYap7A3eEzW6h4onF4TddM6ldZ2pFuZqDLFr6voLfR3wok1tP
-KjYpdthStxbLwUHQrquXzUr25PNkJiDLFrErxlGs7naSVCYPESehgdYkZqJ5-nyqkkvDfHht9NlVzLyrVjVHr5Zyv6j4uhYMfqFS3tOCl9whZdiskdbzLKt
HZHAOtlSzIEAUq2qkCz86Nazzx9nJwxo-ghdHZJFlGKRZJM2N3r5O-vV-QF6mp_mFL8rrhyHxznswKf-olk9QsprZaMZiUxQwfxr6ej6OZSykx7SgJ6DTIlB
HMFjXN9HMRUnWH4nCS1dDTRVtN5NOtc0nZJMIgmyhx7Shp6DDIlBhOt5jTcVdtxr3mCZOcw0zPvr6nl-6NrWH0CqrcoWaTYIncxIM3GIQrIcCOqzLa1SqvZ6
He-Uq9Z6-dktkbioZMbisL0ZCerfhFr3aCRMDBQkulv0ufh6DDOwQA8HsP4QqrWZCOqrQ6pHmwAnNcKQqrYs6bj7TiJ6DBPEJ6Dz6bkKq6jiNPd6D9OBdOUM
mpMciNLY6klJMFDWdjw3oy4RqrYkDHzTZjEOnhObfh4-ZVKIo_RZos4RqrXkqdw2nZIM6fkbiToe-HIDQIotwZr7OnfBZStIMCuqLexUcCPolB4yTcCQIutD
qbXEDbOqDarZgJ7x-Qyr6ejxQ4nZSMzZ4HhJcCRGcCOqfZ6DQGoDQKnZzbreR5THZ4XZ6aDZzzAOnen8Onf3OnepG8rfJ6DeJ6CQqvZ6DAOnZMbCOnf3OnhJ
cCOqfZ4qfZ6DjMu6lhq-ZMciGhgZiT3OB8r558qjQAnpC_3GM9V6ObDZeR5P6WkDDMYiB1iBZMdimSWMZON6PcaiDDQciNAZiKLX6jFOVP55QIIcCOsLpOs5
nZJMjBuP-8qMDQQnVcHHUebfJ6DbGsEXCOqzP7apy4LX6jDO9x8exSGqfh5oix6YCOtrnHqSQwsnuSXIOnhhqPZ6naqNfZ6DvNHY6jDOQanZuyOBqvW1ZYUc
CGFKcCR6ZHUcCGCSJqnZ1gWnZOqRBqnZ1ZYUcCOCK6CQUt5ads54dDzjW7ScfZ6DkHuiVxpV1CSBqvW9jXERdz0vFmMDvTjjnafYX9PAC_GPD4ICnn1DPnV6
Q3Z6Q3RcM4xv6qQJJPmMavJOnvoCJwijlCyhVyoEHMIS9eQYiPBCZCIoK4usOfED-T2QwSl78JB3-2EVoLpBoIffApOrs-AJfh6nx_tbs859R7x6v33B9JdB
SadU3SkbmaGcCP5939afJ6GAGs5_v21qbY-aCe4XCu410000000000000000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0000003y5m
}

