sprite $layer2_switch_A [96x96/16z] {
xTX7cgCX30PX2I4UkF-1s_PAE63-miDgg0chvltQESW_wtGwdKxPwq9krtIhRR6QP9u_Vj1vjTuFvYcVxxh9Klc-C3kgTrvMqzhg_DfHMIvDhw7QN7veTW5q
TWtERxtP1LJ0iVFSLzlhb-AR_U8x_HG3mAS3rCS3qES3rES3wxvAdxzNkW7kMoaIfJB8gHzyKObym2lrWpVvcWP_pOUy1mzyo2EVyyZdFFI3B_wUIXGyzgqC
ijuFdlhY0pz9f1OQy6F0z3LvZ_ine082FXZ0FX_WFX_W_dp0YotxCP2-lJ-nDJyoas4M0y07nG3m-G3t-G3t-S3llhrNkW7k9_ShxqyC-m5g_sPXK4B--0su
faVM_nyyzeCVvy437_B8vppoEG_zu8kz9rqMFFNJbVSdmU_npOFVSFr46sxVTPyDS9yDS9yES9yFS3y64lFvwyi67qJEQslf5zyclhIMDtr_65zWWl3np2u0
FrtvGC_N2zzHjvgLuveV9rKk32pNy-DoNTIpN4nj8PN_gTFfTBe1
}

