sprite $layer2_switch_A [446x446/16z] {
xC6n00000C2WV_x04wa200000000000000000000000000000000001Wzkv3nt4S2C8mOgF8zt_VoySB760DBg7sF_vhi8WRkFhKDTBOfhv5Z37ZapA_JPBn
cKdmTEEp4-jIF-TEm3CxW-vC4_JW6VJWcQ3n3Ber3HhFaF7o6LzSlh2lbsybSmR8fzs_GkFJxZy9YIylBDNv0wtKXD96horJFWJUvCIpEk39yxm6uyb7hasF
3dZov0juz3m-ulqWUUDkYdW7vpTdQGQYbtaZ3f_52JX8ZfxNBRXAT_ZKyp21yTGBHS-pN3trr8jztXtrr7DHwgcddb6lB-ePzVgJ-YFgSUr-IzJ3fMebwW57
RoNgiLB_ITG3ZjvAr0DbrCQd7YQr9Ue1Psybwe67hw8UMA-Y7ffFFKXomASUW4yzR7cgXvu-zT1ywg7BKptqzAc7vbCFNPxgeQTFFJIVUkZoL0yzVUgX-TH3
bwTwwEbJ3ysd7heyrQDFdtfyFlNuvSdNS_huUlAfTvxKOubwGBgLg7SpLOrywjLl0U2jHBsjzzBKc-TywgNgv_Yg8r5lcvnWz2hgRRN7qIlrzjqQC7fHBtL1
RrH3l6fPUBnlV5Ezr9OmRXcYNchFF4b6v-JnzQvDpEcodiLJx_87nJDgtF_oDORZoUlFmUJHzSxnWi1JZuiNzSAlJRwUjKdMipR9UjOcMS_Q9EjPcsGzQvEi
PssIzQnDifwrITQpDibwrYPPpzeawrcRP3rhawndRPBrh4sodhL9rhCsqNhdU2EvdtcUyIMUUga7avkZ5_LI1U2xF7bylOL7uFiAJxtKuyaTlQYNekfDd_cS
wiWDlQbUYggNgTxawCtjRr0l7BtSmFEgfV-EBnWzxnXMCjOVLw-BRynhKM-6CNdgzLzvFdESV8KeannVdGL4FG2VUfQdxmXiY7ho-KxuXgX7dJxrvFFJbqrH
3przwiddZXyzKS_fSwShzTnbJZrtU5HFFdSsReXwlEbJJpwVfj6OP8oHg4USlh7Me1wEBxMY7eqlDzRWqnFp3dljg7V8Dpf7RqMz8xuclU7dre_v-lLgYte7
VEspjwBU0LzcH-9UIOT9lvxxb9qd_NWpXtpgpMp7YyEdtioQlBuCzyOzpjhQbZPzwgtG-TG3bATwdEbJ3ysd7YGPFWFCwUFfoQTUVuRFdNNwrEj93lZK0vId
UjZoL0_DfnxwjbqzzFIfnx_oL8z_vQaUlppvUlBnzRpoLEyyevwAUfUJUZBgNKth8_xKIrK0axUYtdxmmy3R-VmKoZdVg8QeTscxXcg9UdljSVHggfUYwaMz
tDYlPRm9dZj-17pDwMuxOLHdrBktKyExuBdB7E2MRtuPTtWCuKUTKUygtafk_ZfOf3iR8rzRTrVnGS2BUjp9o_msUjOcMS_Q9EjPcsGzQvEiPssIzQnDifwr
ITQpDibwrYPPpzeawrcRP3rhawndRPBrh4sodhL9rhCsoNhM9bdFsYJhMPlVNY_rJEw_7JJgfHvD0nvUhnzlvPfUV7fYwl7aZbvySccAgXUV6fngoBYX5v_O
dMh91RtujFo0zBBXsPmSlRdXgTV2bqiRDgaNZDxCM7zUlRxfcwV9N56lYMzUZ7fvsvizzOwdRmAY7frFlV3urEDFdtfyFlN2urEFFttgyVdK2uzFFVxqgSVd
KoyyFlNuqwSUdq-zyFZKuq-VUdm-zSBZKuy_VUhn-TGBZqyz_lIfn-TJBqG-zLO0M_2eTx1H0o3gHJtqeiZLgTuawwaNzT2B8d_VKo_gaHSLx_VGYoBZgJT3
h4trLjBmVrJFgAUUUkgffnuWwerfr7igwaKzzIXHJprNTIEUvKE-piEaddglhqkyl5sXg_VwGGhtj7Bq1dfb5gUjuEWvV9xVUO5FlBTjfo7VmU41Ba-yS1Se
tfXlbxpA9ru0QnoJ4V6-vikS9f2pElBj6Li2MQb-6LiO9zgATFy9RRqZLkOASSr3kZz3NBTPUFA99vzuh_EPS2-LJUZNNDeHnyzmRtbC9Y_96CCaanhj9ZhH
3fuadyQM-Dhch-t1iG00003087_hIUoiLW0000000000000000000000000000000000004
}

