sprite $layer2_switch_A [93x93/16z] {
xTXL4YCn34LHSLlxN_2WgiBjF9KpwFklqupqJxJRxNQYQFAcp96Td6cUPpTxnnx6XCO-vhfc7jIAZyp9dX-0ZSvAfhHndGnx3ketplTwP52_8tqTpi0qYblO
vt2Fi8_X4gK3EAXZEAf3EAxZEAxZEDzG_b1ST1ZNSBhayJn5yR8Zw98ywiqrBrkMxdFS1d3O1d3OXl6o5R0HNEDfjkAkoF6Y9VTp-IxvGxhWILIw4X200pg2
0pgEupgEptLMxkEbb_2OXtCNBztfDLuwZCyh7SDH7S9X7S5nVH7ESbzST1mteKiMZrrq56UFcECXC5wsqrNwKDaeNZRJMLesW8CsWCCsWCCsYfSTAlVnWzt1
FPxcTCdBXd5-0nShUzLkeSTM7z0-3kWuZkeuZklz6zTwl7HUZrTiIYjn81G_FlSRoZAfNwRIIPnfRTipURBRKfgsvko0yUYkksKEflDaP8vmjCYoWT_dI57s
XBSuqCAO_e5skztkAm
}

