sprite $layer2_switch_B [93x93/16z] {
xTa7RYCn38LXKY8flMpkVzw56zqjFo8z-L450P_fIPac7zLVV_trb_gOTD6ViXsrPblR0vXXdSm7WENm0RXKQXDOpDxJfjE9iJeeGwhrnUYQ1wxIX2y-NEju
O2nmgUTlYAlR--4zmjvlyaYTm2cTmrcTmccTmNdzZV3MBxFK2xYvdjXnEwlX7j4bqpju9_6qG-MONcLfatZQzsjf4pXb4pXj4pXjatZQRfVrEpQ7UzokdU1f
itYxW-lfw4ruF7NJozxYD9VwMvz36Pt7UPt7rxhI-CC_ayjDhU49tCTxf5x3HPlSpLEdyMoXKpYjCpYlypYlyxZg6NLLRDBohs9RNrfuzOzeWsTsUtGj__c_
xJ7dRGAdRHBdRVuqvqhORtk2xhbyXqiBpMzMkoYwojxeDEUBOrx22Pt72Pt7EPt7URr-m_NsUEhjdV3iw-CDq3e-4F8emCks0YQF2jH73s3vwQEes_fRTs1Q
WMy1Z6S60EOWcyYll9gXqZHvAktcPDRavwT--lIgdP-TFQy-B_QUp5yp5Nd91SxsDZfEzfwilHoQ6ovNjjd3VW4zstFvEkd4lh5PnjaBeOP3KSBzDTjmnzNc
iqQk_jKc7uTYi_HSwcRoN9dyZlxw3m
}

