sprite $layer3_switch [446x446/16z] {
xDU5pIum2030Xf10zn_ukVpknjUxi06-NWq0000000000000000000000000000000000000829od7Y9TM4og_g7FKrtlI0gyt9IL_kNtYUfNED5rZvLLyQQ
B7iVhNDmxlOcnwwxeVHVLEzVw8ffoUlz3nsJDnuv-TIarXJtvQwFiE_MQuRQjrLbn3f2P5QFxRwwv-WwIbIFJ5--wxypUldtkEHrnZfKtCfV3llpAjR9wZjx
TwAiED8hSTnoIRPv_mU-zzjX55qC_qOqYZgfsHUWmZzdke3euypNlEwdgrLzjd_RxhhYFI-Zi_zIXJUl8-zVyyAR7vN-lJd74z_PlYCodgvz_JSkFkbtZL_z
mtU-j4HrPyz-k3tCN-j1StMlfNE-G8qtxwNzUd9brfozDtJ-QlIqSUcjzpnw2j_P-StUrM1rEhkPNijci9vRSc-dr_7KycEqVDDmDYw6im_UqOZF6-kT_Nh1
uqXyNVHkqdibUPtuziPwwLEo5dZD-CvN3v7qF8x4rxkUf9UJn_caT_R1utpIwrERd4zwVPB7-QJN1u_pIQz7RUO9m2Uz3idZwPDU7ppE9xq-jSdvfDSdUPnF
UdtmE9_q-jGcttbAhq_oUFgarm8l8lqju9FUbsippEzS8q1vIk_xjMdRWzusG7bAxzjuOUcxzH60JtfVhiqjwMsWFANtxThSiXueJ-bzkJP_eGVAKtfVhSrV
w87obDvNQtEY1yfJUb-hpOaUA4_fVQqs9teDobDwUKQkpMTw-NyF-wQUz2oInaHlaZvle2UzZ9VrPdpnJJtfUQhDYTwqQx-f9xqnIzvSRnlHAdjgpeoNzMPy
_XqzwMKZ0xz-R_JOSqhF8ZbCzNBwE9xqwcUukzk6z3QpCGpWIK-_ybbwqgCZFUb9JthIavxqf2SzwKbFUjAJdlIaP_-Q3dfyATBpU7tSValFF5wQ8oB2fOU2
0oR6nlN6GKPwJ0_n6TQpQA8dlSEndXzTzAGNLCz2UjAJdlHqtODw1IyWFUqvfUSRrjly3-f9B-Rpcv-rn7oAzQJdDflV_fpJPbEkf-OSz2aA7bcW9ps0KA3d
HxsUz6By4JsFQZtfSGP_us6rUjBZ3lxMe-hrf1VZmteUbNhISv-chrullLQygoUzRSB7z3XU-FQsdlJoGHsbUlFQ75k5dlGcwQlMowzIeYUzV62zN6_o6YLw
qik7rihrB5BoolIab_a2wd6yGZtfPJv7UX0lVAlLarxcCw27arUi9xtC5q2FuVbMhYUzpET0Z-BLwqalyndGWxLPhoUzp0VqGF8gzQJ7-R8UsMrMwqaFbsVM
uxLPhoUzp1S1z41j5kf9ZvPdraDuzNhIu-Lv_sxLG6rMwqaFfY__RuwJLwydFSuNzsqasctMwqcFbwUDCGmaxxDwqkFl-oYUzFYOkTbCZ_DnFAPd7ZvCUkaA
zRAU9JwhnyjwUNKnfFTW5JxH0-chnCjw-PLZIE_18GpeCRvvRiCtfFTeRzBpNxnX7lbVWPrdHVBoQJKcTwuQFrtFVtKaBL8S2zENyUPZgHJIlmLyI-fb0P_S
NwYGpyXZHbf5oXueppNrV7OepEE8t8QyF7bjPkkqYlmKCNw47W-FyISen9klOXo9RsazVg_q2l_T_VpNRpkiJNv__f-an_5uUUv-NhV_pdKwmUCtUHy_He_Z
yVJj_wMx0pgeJRxqyKFqE1xdyzilvjfPydXvhg_7yVXJfTpT-nFWyV9SNu_ZSRxpDX-0nyjpKJsEnySJtcG07Y_FzVNgyT9kylPqJe27ozCMrUDuV3pXJVW0
7Y_FHVKu7Xz_wCtv43nUdklgSJn-A6z_EoV1u-Mvg1x7u-FdxU-7uF7qZKNrE1wVQse6cg6WF1VK-ppUVkDwzUMveXu_LVduIthxzk7qBQh7arTVdFp0SRu5
z01USprUdklfVHvlJthL5pvGAIlg-L4yCUpnwNzJp-Ae7bjFpu_wSUFP-mFB2bjDpuzFJF3iJP9NExQ07iRZUeQp1zPLmBU2dldnGJs-v-JHumjRI2z-dDvO
g3ajFgztle9t-Pzfph50StwSB-WdPNbrurF9MqgFy_7D0T23uUDu2-Xzc2_29eTdEjU-vV68-jfSHM_Ev-FDCV9PsNnnPkEzySZ9Mr0ly_bMC31y-_Q16P7m
5jJZVFLVC_X7y79jBgZ7-Uh3Tzd7yM9iQ-fzdi_YETyHzldQN5UldYy_zpE-yy1yl3PNrUDy7Ey9ttdoxuHvRQwhn_autfmFVALVK9iBwd4-ZdVtowt9-NXj
hgzNpvUVyxokHxdhlDiXFbwRw-jnFlwCk_j_0K_VjpWu7w_DXVKu7yVBFEvxIWdWmxMviXxdutZp67ZchQ_DjVKu7yURny1P-dXjBgZ7-UgJn_buydnRKe_p
rUFnykJ9MrAFyzNN9ayVnrjIZ_FL9u_pyTtcwdgSpypi3RoYyhHVBCDoybRNu_U_6_7F6GMroTENLs7fIVJJLTFXdztWUT3aLV7DLs6HTfjhwd6-CF1JnGaU
By_vAYmItffwd2yCtBYIr2PFttmL5kabrzJZV0xkfe6Jn_dImgQew-k1Wafw58-N9zIpIBMveXxd6zj4ZzKcJn_JsuRk8lKuvcbZdlHWyZWVluDRk6tIkxyh
1dTFH7YyF7NtH3v03zOcJr-zdlHuyZXVlPxqE1ulpm_fII_ZbNopD4bVkPxqvdWHJu26kyt_QqpuglMaDq-UFGzNEE2hrfCUhitSZ8YlNazwy-FzoXVWjard
mbUb9prSc-nhYinNh2SzNfjPZ_1LwacFrEPS3vHdhPxqU6rcFPI-IZtfyThCUf2lJ4zwqzf4Ugmy2_Mansipwz7qbUb9ZzTcrkDyPNhIuxMPzJXVYPxq9hK9
zJXVXPxq9hL9zJXVWPxq9hN9zV3EytqzwKrga-lnzBsh9xsOr2RNutp7UthIonDRkTwShrPFUcu5UeoFwqaF90_fSJwk9ps01_G0Nx6UzDmAz01VePxqmhO2
FSp7zQG7y8hrjX65UjBBU5oFybNhISzdO_PRUcO-ctVrf4Sc3EjP762WdlJGEDKpFxheII-mNlnmFUb9JthIuxkMyK4zwGKOjmthRHPaXlG-DrIFpq_Navxq
f2SzwKbFUjAJdlIa9ptfIKzwqfEUzAGdFUb9JthIavxqf2Sz6n73eDw8FwyglOd34GFfZQBRTaklvZxvCUPwy__aNzMJNaoD_8N_SdnJJtfsrulnejuuxZCw
w4alyytr_6Yb9xriaVLoyZerfwvxENrPRueNNzMJdXs9xwbUnhElwaalUuo9tkH_PYEzUhv88XCzW2UzRwOlwpN0anxWIteDyAG7oZFf0JpfDKXVqWDuqlis
Nz9hW2SzK9v93-19hq7w7lK8dlHQy3teCJpfDIZFkFzj0ppfWVIb0NZIQy3N04zwb2_wu4cFypN2anxdQuGdFSuNVV2an_aQuKcFypN2anxdYpvuqkDyxV2a
n_audlHkUmE-w8CdFSxN24zwd0_WjTFJqaOtlFsw7w9DUY_mDSBRzbjVFU-tjZ77qn6Qdrbx7xuO7TlfRATtDRmcZqPu6pX0EhKwNrhspgkxzYsFvcnzVFnI
-5uyFBxrc-l5Qb3qlFVwSlWqVcj-OTblqzDBSxK_jQ_v-QNUV9YzTJkeE_DuYbx_Cyo5bZx9QDvAVatuX9UYrpbyyvsByAwz-KB5Do-actT_MwEjo_o8N5ld
EHFV_iDRyqnupO_7bPPxzrDhzh-MxBU_pF-tP-yu4iGW441728do_I-yqNRKqMICtxk1_wOu9-tI_3SxzflpLs_piEkwUCnqtRHoC-Unh02kyof9No39UJNh
7ki7i_QlHNfTF-j1RIrroDJMc87qsgI1_YpLSuvBSw-Ud7ljpIXSe5q_anmbEPT8ycl9O5Nr9QhgymK0000000000000000000000000000000000000W3y
}

