sprite $outdoor_AP [93x93/16z] {
xTC7alGg301X8K2ext_WZQfTK-DiNlpv9bHk4sGPR9gcQPeqbvppov_ASydOa1wdA-1hGEMPhtIH5Ubfl7YanyUp0pN9y7YaBT9ZuzeYFJeUwQQBakPSFkMd
yMH0-yreTNxeatWCzcywDxwuUskGk_YpmTO6UDKaN_nyFDMWoy6coW_hplvIl15yVR3L-xIaFfxtuzu-GHnkFtqLgALnWjVq6gzVLLYRlWQjE6ULpRWQVLeA
K3DWMTEHN1riAnxJrotRDJcUv1o3kX7lqv814waGxNDrNOahNcJ9uc5Gv3p7Lk8IoriEOD9IOk5dPLY9zofGfCRyNv10D-BTJOhmfSaLVX0lnAL3rh7nMFOd
qB7nl7WJeEIHSGEo11zvvZ608Y4FZCS0BgLK8RZbE_7-9dk51RiPZm5yfHbg_b0Qj7jn1S_IUTbRWNOhdY79EiFafvvlncL3mIKOFZYk82516HjFaBgbZumB
g8HySEg9gt5V19qZVRpL3tOode_gdhfuyEruTukwgM6gigGjb8FuCQFAPUqVZS_uZC_uZC_uZ1icPpX5BYiW9oJ8SbdYrD8hBZSKg78aGv4x39eUhPicShUE
smwW9RafEmUgFA3LjjKi8qtJz0u
}

