sprite $outdoor_AP [96x96/16z] {
xTc7SYiX34PXqFneTDx_WTCJ4itYB5voAsUQw-ScS2l_GRlTRhVRMGogQtH6wRfU7GWT1LgZMpaihlgr0P6GTRxoKtpTptehgLM-0cYrBFJpIFedlPhKNj8r
l-lMyHRqBFbNHzASboB2tQ_uNTVNuxGFTCflx_LJqaYgtzgyhxoFAEdLymAeN_rsqs_Wpu4EHrA0ouCpkGxyw8zJUIIB0t9E5pRsBR9k0M4E8JkH0j30FxZv
1hJYq6PMZGtyhDTuESKc-9ShnS0FvS5wWPqe4ndeoA-MbnXOgRM2oanE7FWf0xmQBzKft-1R_sr91I-LMRyE_JwLpvU1PjD-7VXfAfy3bKL-digVyWLutxiY
LlXvAljviDAtlFz8ScXwpIxuVIfJ1hrsbv-cCkK1n7Ea2qpv6jwzleMqT0CpVX0sVWljJvRVxUl4DGHQwkVF2q4izVDv1bhkEwsa1x3OzyyljknMclFp6gzy
L_Q9vxZXYqWVh6_MnfyFn_wfAcZy-VQ2doPvqB_bRt_xsz_-zhVFZ_e6Dl7TTBx09xwxpoVGn6yFypde31_bpW92zQRUW5hkpVc-iAN_OEHKBcOQPrP-LRlT
xX4
}

