sprite $outdoor_AP [446x446/16z] {
xC6n00000C2WV_x04wa200000000000000000000000000000000000000000000002OdJj9cns5WG2ubkv_tnxM_Vs3rIQ1Uf4NA44ugTbVHAJ2wK3OqMEN
v6E7ZrrUZnqzTdazUFJOvVNOqMENrsDtlnwxNXvw0RlBzE1rqzExl1uyUknsw7c-emSlh-VGf8Skh-VCfATuUJrqzE3bzTZHOvVMWzTzWHww05vOJ-_eUSBB
wx6ZvypCw-aTFNPvFNRquDscnwv-pY8zTfb_EPoZftVrF4VeiQjXjkkngofwmGJiudhi5j1bzD1LWEu2FRtBwh6h0DqzUkpkrsDtlnwx6K9UZzq2X8oUDmbl
8z1BsIr0YEYnMu50ho9utN-wNlqgDzfzlbxzFcTzaT3TVxnUFKcWB0_iwDNhUfKg7hrwbh3TgtJqAehtiXszcuj7B_SJpGLszFRY3ORUdWlqAbMykZDdw4Ni
Ec2Npwbwx1RuXVGgWrV_2R-dpsbhwRwsY-Fb_V9w3wU4LtMCNgNmwgDoX5uftZ3RzUPsyAfgarxMxciyV7EzmLGBtkJXc-ZL2NZkuZNG2zjrZ2ulcDURqSrN
5vJB0yRqydZzRw9sURzJz1hUJpbLhzVOTOVjyduvlVrurVZUrbjbrnsmI-SilMvu2_W2UbcyQdn3lRnTTyOkdpFq-dsyHul4DzVh9SLBL8zUByVh5Dv-lu1U
m2vGFNeTmFkYUlW6UXt0MwP7hzDsNP-jrr6z7ZpC56--EdhvxvX__WA_yUtNU_1rmc5uzBwZgOhfqGl_5RRnJVNWqVkEfOxMerS3l8_NwmLwGRi5UlH2U0lq
wANm5kZHIza5zEW5y1ReqGlOBT2ZbyBxUe3zUlI-i0leqSiKBwz7RsuNqAENmSlhqPlZ1VJe1Um2UlG2U2azUdExwWlqw3sWEqoFNjMrUlG6TX4zUdEy6_Je
3Um2tp7GcnDqK8zUm2wWHo-05z2ZDyOBwz4Bs0NqwENmkWDwz0PsOJrwURpk7NhqNjlhk1wzLxUw_c_erGAxd5yLlGLuIKjw2_2IJQItm2vuZj9RW1VJAteB
x69wLVGMuCNqYju2l9XUqHlO1VGcVlG2cnJcezTz1X-zY5tUZrvWS-OJVcrDRxOr-TknqHiqBwttpA_fFR0Bw3tpenV06umuvADtydr8wGqs9AatvwFNlLbl
paVlWdNI6pnEi7nvFdhqw0Nuw0KMckIZHu_UzNpqVWuzUWj2xoe-UllvwD6ZTnSVlQP7xu3Gkv6FtfplVZrwHOyUlTWJtt5yz2ue7prwz8uDlG0VFNhqzlFH
eqVlVZvwz1w47htyUziByEXTozVqxkLhUlVwDRtZCzZ4U_JeqQENnwCtpyrwz3gFHo_05yMZDq_MZjuzeKUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF
7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF
7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7Zrwvi-77hqoVZJqwD73jtjuUePt-TBBXHwzOqR7PtBFVFd1wTNDUFIA7hvD
HmO-rTE-NHSSlQ97RzDXWQ-kniDNJWfykyu9V5MtN6NqRk0hU8_ugYuv7lXTaA_m11u_UFWcU08F7pn-8pk1nuyTm26TiEF7ZYA3lzk3Om400020GVxMezXN
ZG000000000000000000000008
}

