sprite $PLC [125x124/16z] {
xTs9YkCu481XGK4NUly7dllq7ELGQc4dtyUrHt0hipzfHvQquya100000000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000aJa_WSnOazJy1SHeo_aRoFKVKn3BcuBHCFyAbjzFGIx_vGUn_9SVz3-e8iP-vVXhit-D-Jp3
w0OHsVweok82juvALDqcidc17A8IrHVTgEOF8IfH_N5FjEPjY4fKGrIY4fMeHDKYAb69IbIY4fMeH2KgKObALA8IbQX49IfHYKfKeXALg4GbAb69IbIY4fMe
H2KgKObALA9w-useHDNtTl1aKObALA8ILSn_YhFleVZnnIMgeqkokaR_4erhD2xnl57D_yZgFTG_lnz4FOp-9RhNE7y9KSqTKVM7qRz4ungDIzmlAb69AkiF
p3egKOcgSNDNHYKgKSr_UxseH2KgKObALA8IbQX49IfHPV6ZLqPbHlr5eXgD9rMDg3pxUygeQXkZgbcb82fHYKfKejg_dkh-zrJ7O-pTK_MZifug3t_lsryx
AlDKyrUlF4ybAb69IbIY4fMeH2KgKObALA8IbQX49IfHMKyLYwCoesuzbMT_dlrPfM2LmXMZ4fMeH2KgwwciKJUb47RJ-FPddig-l_rHYKfKeXALg4GbAb69
IbIY4fMeH2KgKObALDPJcL6tdchUx7mgp_wiKh1AGLIY4fMeH6KzLJ6CzZrLVnXtkwVoxM_-H-pxzZTz-pDFPPxgHb69IbIY4fMeH2KgKObALA8IbQX49IfH
YKfKTYYldr6F5SDeF_UQrbFbDPxzvTsU_OLdVrOfMAMmFYfHYQgkQeYg8gg66qHbFTNwgEg1t3gg_UkfxAQfXv93LEQf7evg5r69gazKeXALg4HLJ6c8IbGR
teEeH2KgKObAL4sY4fMexZ-Z7lUOKHULPt_zg4HbbOAeH2KgKObALCxyx4SbAgSJNoigyrJcgKJrzXjHzQCIrTl1xQCIbQX49IfHYKfKeXALg4GbAb7bONQl
6vMeH9M7EUCYAZFgTHMYcZyKKNdsjo4gKLcb82fHYKfKecfpJ-MUIbI-_VMZ4fLvglj79IfHYKfKeXALg4GbAb69oWFbM1oLg2nzYN7lg4HbaPweH6L6VKDK
elBihrU5gAnI49MeH2KgKOdAFTNDelBjpxS_KPcd4fMeH2KgKObALA8IbQX49IfHYKfKeX9LNOIeHFLFZI1kCwDkHbrKdls9wlwh5AnIYFmSU8n5H2Mg-EM3
inQH6I6g_n5Lpf_oz8lJFPLxgYAJarNDNuHlVxxz5R_xgbG-Expq5b6PfzeVrJogNbk_L5IYElrHbMS-PaKbgdWWgdE35vMevb6UV-cCLbIY4bNESwyLbQYE
ucPHYKfKeZAb82fHzIS_StHlrCseMq_rwDnd7PLdVzPJ5KtzxsrOfM2LGXtBcGlNhnQLg4PyooeUk_yAKOdgVsB4etVrEKGbgWKY3zSMbQZwudDNcJ549Qfz
H2KgKObAL4UzIuZAMGerKHqvzKLKeXALgDOJbQX49IfHYKfKeXALg4GbAb4vz4nK3ZsB3L69og5deX9L_z0pKObg_Q5dJQ8ILSu3KObgpw5dvubALB4rgkCE
Yep6UsXSOkarlbuYOySmoccXZ4j6bHkYYhBX-ZraDUBvXCCO9uRneb5bzSbOluUexmDdFOp-0GIRXt7g9YPUyTTVbZ-mVW-DitCkDenuz82EUXZnUb75WjEK
7Z_3fnv6F7wDt3sCSMuODpZqR75Kirz4d3ifRFymejLbFOp61yE53ZrR7rNCVX7pJ17ptOUHlM6SF_IhxFBe1eUUzQAg_mYY7zLi1B5q6Fssi_dH_zaD3ZrR
6jNi_zUCzuag5mmZ6iDO65LSxT0pKVK_gKGruZ0KKVcaMdhesHtkgS8zrGsYQhZjjx-BH7MLRt-YoduGOy4mOlim6e_QdZggaGkcwXf1N6mOqPZyB8RnIb6D
1GyLiX74mc74Wc7a8q4q9h2VFAgO_UK1sNw2UgngmJ3otOSn6d-Y-_VzvSvzVp5dUnLIB5ZhiNqOTPdz1MepNdNVNyol6kib8_khqg9uusUkiNKOenv6lFA-
l_Ya-HxYlzUOJpYCSNeOzltP-63VdwX4PTzVGLJs_OdAlZzHYIf59IfHYKfKed9F9IfHNMxVdwZCKwMeH7MzVN-Y4jLet569IbHrLOwy5jNLzls9IbJzVN-Y
4bMVg4IrZQX49IfHYKfKeXALg28_2r69wYBx_aGbAl-_Fr7PzoSg-_v49Ihx_aHbtv-eh54NbQZifX6Lg4GbAb6vfnALgEpx4vLzVwAoxqzKehBlJrJs_OdA
lZzHYQe-nrjKeh96NLIY4fMeH2KgKObALA8IbQX49IfHYKfKeXALg9OGbQX2LABwAguRbQX4bQ8IrPhrJJb_2569wj14TYym8ru-Ab55z8-BYlbF4CsmZo2x
T_f74CtRiYF8xftT4Oo6MS8ll_vj5Oocd0NSJ_K-h2362f4vFu7C61i10000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000007m4
}

