sprite $PLC [96x96/16z] {
xPU7ZkGW38Pnm_pl_y9d1H2wb2r9kCgtEpDEyIVBJat_9Ol5Oh5OB1QYxoD3Np23tFK2IGUif8vxwi1wHD2HpoCS0j3OFi6llyjFDCDFGKtCcQfVFAX-CUd-
72jpzNkWDTy3sVpi0U_zX81-zcjR5txBrlqEmAiVWMtvX40tlo2Gh_XPWxJtIwoKwjU0YGMyXRJvgOQFwY-ZVWFqPlrIIl53_JdMzlv7g5x2dqhG-by2_f8_
1mU_nagj_XniKXvXv0UlzMV-V6j-3STyPn-Va_tyWL_aS7rutfyTUx-8V3vVs_NdtlLJpQpLRpKKy1Qs-YsW6tuHslM_HAZx_ZC2_gu_oinPRXu_d_iPqltN
ywMRynt-CT-Nwq-Skj_StSRzHKxlBpVcEyTFDFnF-yDQbLpzNJhyp-PBGAu_TkM_VtmECGD-vNzsVf5KZ_EL__tdDn7gVY9wwAUvpuS5EjDFGDxv5Txz6Rdx
7Thz3cdvLC3Dpm2TrQzEEt-_FzQm-Id2vXV0Mxu2kVaDq3C_SVfY_TRyL4RzW7nIF-RtVwO_YT5KFqcQt1_xg_lFId_X--dyztV254PLPFbzZDBhB1QBnMAn
M2n-
}

