sprite $PLC [124x124/16z] {
xPc9ZjqW34Mn0MF__mzNIExSK35l8uAsuwFjtGHyz2oofnz640H140H140H1473U1mzcKjk9KWBDMfqZfhUdPYq1Cqfpo2G17cRbF_RfT2Ig8DdWJXlTQUeE
Tow5Thgfurkg2F-UnTOHhqWY0ZTPfxbx78bzX95pTxNEj-xc5VcfkmrkHPKFt2ITF7KdwHHtqoKrtrU7AkKZTtdTdKNoWdkfvsAMx-gvTUHbjzIhkurLtdId
tA6Ps_Unkw-fNH9XvEbrVjwzl-ThQ-s7dTVA9-SrJuIHStVHZcyXviaLQC6DVGlNRogbBFHyoGq-MMkox5uunjRTN4e-qNFYbB98FU4Mot1lxJdS2-Ur1JUV
wda7xhVlr_u3zxQUSyuykcy_hucmLoyqk8j86Tot7sFLJF7ZYVlcdelvJpKpskjcjOB_lRVde5Hwujxtx4_CTAb8z5-zTw3M-9HRp7JgpjahUe8R-_JRaQZo
WRkPLQ-8bB_s2To2yneIcNXgZtgkUU8cCrElw0dkhttgoU3sv6vFRwurnRz1ml_sSykG6jAbU_h-MgDQ4YfIhSdTdjoDX97NisDFxw-rpUjy__6jURyxpci_
m1rhZGwwUQERuVPJ_XmrkoKfGfST_Yu8U2Tf5q4G144G144G144G_08
}

