sprite $printer [93x93/16z] {
xC610000082W_QaNgG800000000000000000000000000000000000000000000000000000cBqxobOR1m8WgbP_zD7-DpnV4oU1yD0S7caDj_02R4eb0zZM
tmU8BemzC3Eh3PavnvCWibOtAiSJ86hr96Dy0Qxkz2Uyj-M7NDqvM1zvg-Ou3V8kQgC-yewSF7rWgSeUrEyxDcv0zVrqDt_Rj_4Ro8RkBg8UdVfGpGTtFhT_
qfljzt3y2Ub5_m5MusTmmhHKNyLdugmuROYXZdXVahsx738dtJlnOHuogElX_EwqDqTdyg4zzeooxuAzUR0zzg8EjgSzzhHtBDfZJtliQKzxq1vxscDFUzfZ
JtliQOyzxMcFFUsnfptjGNliQOyzxMcFFUsnfptsjASzzhJ7dlQq1-sTXVROqnvxsjCUjCUUzjZJdlROqnvxscDFUzfZJtliQKzxqDu-x6bFUz0UUzfZJtkn
pMKlMdFjPyO-ep-PMVkiVwasl7u_CxErmSXQZq3DlkxMbw1oTEJ9xb1nyeBRQ9VVJdZ8Lld5dZnKVFYqIHzvpdsnVg7o3gZggQ-UEI4Zvg_-ejsyMTmz_Psu
HWEYdfQ7g6PpP-wC9bIljwksPdBawhJ-wTvCWAX6yUNclY0RJLPrS7hUihLxJGgYpNGLqjkdkdp3odrxo7xsnZRihNcmFIU-FCuUejXh0NldmnvxxB777djW
Zptss6EFFR377dliiSSUU-onnnvxO8yzzjXZZxtu0FwlzYBh4yYJxNcaIvviprD1uc1x7eLLx9qCUwtGNdg6rS7segHthhqnwoFSLHnhxp7v0SoJVsi1U-on
nnvxx86zHx377djWZptss6EFFR377dliiSSUUt6kFG_7hN6iFV5L76aFMLKPWpsmnnxO0tjWZpsm1_R0tXzW3-o1FVR07jW3U-mXCZDEjcVGvydsp5Xve3su
dlCDk9OQx3M6lHc7mTx5hDEOx1tyv5Nss6Dl3_ROOuyzzjXZZptssClUi7VmZwMpphN7Nh2dFVR-4zhJ7dlQOqzxx6bFU-nfZptjiQSzxR6dFVQqfptsj3VN
kVQqTzcRNUnDxMtVV5an_YhNC2hj7MTlh1-4zdOFjzhSWhrIUni3ljj38ogqzmIHDzDLYwapjRTriAl6NwTsz6alryLiS4Zh8hMt8Qz60-ffVThBjVfyPhdT
evhQU-BpofLUBtshSiQChUsyzZ9cR6wPjNwcejMGlAXDrd7jhThczYQo9ipr8lgtzpBcQ4D-XhrudRqSZPZQss8UUs3QgtdiaMalO_GZjVSCbQCdMThRc3JR
aLcblVjKPSPeJkG-nxMNkKzqLlTHrvJbm9wzY9ZVlyKt_CV0NcIzXtpzVmpirNeN-UhssClrFkBWzjZB5xV7NgqtSd1xsgk3ssDllhWzzgBUcDwBssDlp7gJ
kupnglROkvYPxzZyrk9wpbQmfptjiQSzzhIdFMYlFzfZJtliQKzxq1vxscDFUzfZJtliQOyzxMcFlPWpllyLsdCFqH6uXmYkfNu_xY62UuYqvnuYzfptt4F4
tYrnzZr4xY6Q-OQNUuZypja5zhIdFVQqnvxsj0VjjKHxvwCzzhJ7dlQqjnxPOoz6P_AXFVPgTARkh5k9M3_8vXFdhJsiYpnjZ64Ue6yMUt-WsYznbWyl6HJV
HMN4w4HaFRXS5tMxsjcCsMBBh7fuqHbYtL2hMcmRI_xIrvuSDs2kCwXn1qITN1xoP7cOpVEhoT438gknko_3GrIrLFTSTuYPrKbXRQwKZeZPXWZg_caF3WG0
00001FbR3tAr1W00000000000000000000000000000G
}

