sprite $printer [96x96/16z] {
xTS5ZiKm38HXWpBntF_2ArgkGdvTzAUAcxyCaP-cb59AAJeYIGQEmL9vaZ52qkIO1g4oec2ed79scG5TJhM5iSvsSn__er_zwbTVMxmY6LFlre5Fyi6a9YET
K3cdpk4fDOPAYhDdBzPOKCSVYwJEVB_wQhjqgm_kmbRViSj_nFclFhea-abUVLNvCVUFOuKVznjN8D67pxHKtsN6_rSVsJv7VMLehj_OPG0CjnTOwziB1sao
e9tlhFJtHZXUnL8_yAhfoVoYuKfxrFn5UKqVr1UxzaNph-ghNT5VS_y0_MgfwtjptnakOnPqEGOo-X3P9S63Oz4aHsr4vLmffJm1
}

