sprite $printer [446x446/16z] {
xC6n00000C2WV_x04wa20000000000000000000000000000000000000000000000000000083PjuyhoM4WY8BdNFyDtlj84XI5d1VVWa95woRdoowXM9GZ
YAx3Znr0UEjyxFZ1mmTlWGyUFdZuuAteqUiT3LxlTFJC1-_UZWr8htX4UcRqrCDdB-Ucf6TCJxqNvnGzBvpqwD6ZHuyUFNhqwD6ZHuyUFNgYHuyUFNhqwD6Z
HuyUFNhqwD6ZHq_qPgCdUlJeqQD7ZnuzUlJeqQD7ZnuzUlH4ZnuzUlJeqQD7ZnuzUlJeqQD7ZvxeDKMF7ZrwzEY97ZrwzEZbouIE83f-gtQ2nmyUlYKyLTk9
7hvQF7hmy1sQIdloiHjP5JpBOdSgUlZyPKbl2WyVFIk3DwmtFma-UlIySD8JFNhqwD6Z9thqwD6ZHuyUFNhqw8aUFNhqwD4JFNhqwD6ZHuyUFNhqt27ThUVk
zc8zU0czwkXLH8yUFNhqwD7pVMyuUfzZrwGdUlJeqQD7J_JeqQD7Zrv_zEZHeqUFdkZHeqUF7ZrDBOqUFHtO6JtHeoTweYTwz4HFzEY9dkY97ZtH4ptHesTl
nNhm4dgkIg9Nl3LwhiOLlRhefIrwnNW9FNhqwD6ZHuzUGVJeqQD7ZnuzUd_uzqbwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqSlzEZH6peHlHay
UlH2x-J2KdOaUkDuwzFGoxvweVS2tX0VlUojbz0xkAXiTQZrQlHkgb-FNl6fw1KVYrxnkUWL7unUySdezPwDNk_fwFMUZzw_pQFNIkSVee4wzF9E3-ZHosir
wz7BtNhqycRqw3qHFNhqH8-Upvo-CT3pMmkzuUZHeqUF7ZrwzEZHeqUF7ZtHeqUF7ZrwzEZHeqUF7ZrwzEZHSrsBt4D4xmK-UgwbfaUF7ZrweaVFPqxV6EZv
hONUOFJeqQD7ZnuzUlJeqQD7ZvxeDKQF7ZrReKUFNeo9RsX8UgcU4L_wyEXjB7XWE7m5mQE7RoSymSC7ZzyAdk3Xsy0E83j-x0W2-TyU70W000002FAt7kJg
3000000000000000000000000000000W
}

