sprite $RAP [93x93/16z] {
xTW7ggHG48NXodNE_ZSy7Gp8woiT44RmeqWl_6Q5AqENo-LoqQpA23VzyF_CFMB_dvnSeIipt4n7HJMFo6fm4Z9c9Agg0N8BwEwgoiowwGR0BG2aoH08NOyp
CgVj3As7ftBJB1a9qbuVlNb4PDPJPaRuY_FbX8mqItvYfCe0QVA3_GBfyXkCxvTcos-QAGF-ywuNQsV3a9yaU_zg_oBszWu_tYz-PDp8u-9Awc5n8UsuEEX7
nkEuU1yPB-PnyMGT6U_Zud5at8cJneqyQLn9FMTSI3jf7FJJnkEuUB-EN_4yBbudZjT9u_a_nQyuNyVL8wlnq9LXtzmjHkhVS85_TFgdyIHaAveFO2ShxjFD
f_9Fdb3bzZTMKuKfqyHjb1a4Rn1llxWKcntNPpgLWPJxn1I_ZmFDctWlRjk5dkHD6KDX7QAo3bnWA058mj_vp2NfCdEGY3AvpKBlP99-6osIfPkuxrxdQRVJ
p2Eh6W1VhNbLPNY0X6rkvjsuUlD35LFIIHt7BS45fkKnTpFJcPcv_rrUwun8i0UtVozbT8Qfl4Czii65xIzObgjyogAVUp_wroG1GkKxJgQCgKbCL-UxFNVP
5-1TrvkBnMgU1N9zd7PvWJDqJRUBsyhdcwN16TBaFJhjpNkwHdVM_X77_8XYayFoWFhxrSlbShdy0m
}

