sprite $RAP [96x96/16z] {
xPW53kmu44JTfAgw_uLt4cqKvKUsXlpHJyFm6iBTli9YiLWitCqcsgaD4bKPxa-5ClV80YWnseZG3H9xhF07jjTcPkwRCwj0wi8eW4lq1t7-yLa8R4bG6fGC
oNuiV8y5KftIhcsqKG4-hixCJteh0LLTGOdjKqeOjAS-zgSuDV-Gnlt_41-jGFYy09DyQW4ZVuFmgP_ArYK_zqFrH_jBcEfFSQe_9ljTckstoNwVwRV9_ZRV
7rFzLFxHVgZ-Q7y9VxG_f_ivrH_J_VgZ_JxVRqF_yljClytsB_-OtzQ__DNncsS1v34Q2dzr_UcVMrWKTGVfB_Yxrxy17HGLK4AWTbZ-cX_IDLvf1qG3Mprk
scwfunl62_ktbF9kBrS1fp-tcuLSl4KOxfzBmlMj15Ss9T3ScnstqExFfWtwKtwNODT1Oj7RutR_kMqtnkFca5ITuti_RaagQyVy3U26DhW3rF-Zjw147vnV
tUCwTezU8DtERMZajyHLVEIQSP2PTHygYXLkdb9s_NQkxaGzCxyrZwnhHhJkSFLCfBs6UHwPePTJQGV-oV1wL75KkiJqD_MbowhJBu98zvVKKT26FvF5kOGh
eZyAjdCkhnscFPTDWhf24YSaTM6yJepNkp4awjRCrmAvHsJMXSm8TxSsYSLYiLZy1m
}

