sprite $RAP [93x93/16z] {
xC610000082W_QaNgG80000000000000000000000000000000000020sRSN9EbL40h0SeewuFutV4twtVFcfdzqXYyRI8aIKFDRbL94Jz3MKaJf_G4tYa66
zZV93YSYqyQkVyZDx1h9zYS80ELWktvY9DfyXDw_mOSzaggGzYj1LMtmeR_3s6QZtaCk2r8s2-V6oqhxtXJMDXLw_t_iFhNAWicn_mXbuU1zdLgDEiYyTJMl
oJ72AIi5Bywv0RBIgsnmNMNz82Ph1Y_EDjmeNffX1TTmqJRzU5m-U76-inrrXoDs6MWxt_LNSfsnsipdlADun0VMynXQEbX_O3IIHbelqnUUzbnBtK00Rdpe
VvbVz7kEbepVV1zHwAKryhwWU0UhK7d_CsCj5_odamc33YH_PnZz539zloO6-nrfcOJXJ739hQSm3ildHWuGoF3T-QujamQ2zsLgNIQtkWtdt1XBLzOIYJza
Z7O8kSkjj5bJ8rM3MxB2IPe6lhJ-VInSxLApULB9Q1m0WMoEQP0Taomza_Pw0bKeTxRpLyJAThnKZ91s9B4fjikOkk-3dPxmp7k06yzqXvsqL-4CqHERQDz0
Bd1-b5y0vF9Sj7z3PnWsZUNDWXd6ZR7ZZY8pb2tHfLUyNw7bqEYUGM7-oB6MNaBHcTwr54qVEeG_lGNzfgLGhyHvn2RLQhcxYFKhB5Ot5KaPl8fU_k1LvgoY
a_6jrgBPn-iQxnWAF3bwy4gTOR3agIyMtYahaXsznl0kTH5cHm_znbjPhD_oMdnP_LRTZAXJXk0x5EIF71F-PggBIVcBhqnmliP-1osaeeUbhyBNjR8a6hmB
NzYlK9VXAte1yFhoBVmd2jD_egzsFGuvFz5Nkrv73HKzMFPxr9NEE66WvIjYHqIlBhZaJtf9dqNnXhsYXvR8iigMEbtFVuzg-FG_zkxZne4WXg8Wki5n-IUy
jxtAi_M5UWciASYC8SVluN2T7ZqzU9nyq6k8dkYv6NwjddPwgwD7h-YvDw9FJqLlIVGqwHb4ITCpY4AF7ZrwzCv9po0AFNgYvqGdFITRwD4JlM-BdaU1qJF2
rwUdiTDR7JrwWvu1J7gf_pXwz4JF7PtqF8seNyy09ZrwzEY9dj5rUeQVwT4JlVNHexVJSw8pGyyzWVIyzkXvxNdjZJ0zZUk_Wvx50_JeYLv8zAnieMTj13rw
eXSHFNf5pxgaFZtDD3tHeqUF7Zrwz8vWFQlABdhM9T6Z9tgVZXuzUlGgJK_9UgeqFT6ZHuyUFNhqZZGzrKdFeha-FT6ZHuyUFNhqHguUlNE6wMaawsbFqnCz
UlJeqQD7h-ZTaybrUlHKz9P4JvDUGrvxyjfho6jFNdiUg16YPsCBlRxeQPp1Ug9tJ_JeqHCzUlJeqQD7xvhqwD6Zz-lHqqwF7ZrweaUF7Zrwz4Il8NgYP_oI
7Zrwz9AZ9thqwD6ZHq-J7Zrwz4IF7ZrwzEY9tiUZ9thqwD6ZHq_qwD6ZHu-UwD6ZHuyUFNhqwD6ZzyVUdMWtgyD00FRew8n6x__25qxZs_XFIOdB5iZthzsN
gMHZ3DaSpEz-MJcmJteOcNEWBwblgHkEyEMJtlzYh_HWvkuabIyGINSpb4FmAwPdHZ92sKaH9CtAtdYOz6IRz4bdIBa0fHHq09TDpvHLsEhJ4J9oSIBTSCdq
VAFqp1cHgucWsmNIs_x30qufroQ93bmfFSJA7nv6AhT3EYwJdcdDAIUCeToOWdwHz9ZVi7XqKkv22iVvxtG5vVzK5WJdNmxcHlNjUmyBwJXvUfQhLBunyXNY
mFpsHZICM6V2i07LrKBFd1uY5pzM1-QETHhSycg-5SJzKu7x0LhkpXUgCTnmrlIOtm9RTimWtSpYFZsqwVcFwLbzQYxHSChq40itplbJJ4Vz1ERMNfjUVKF6
h0wA3LQ9RS_IioNccB_FHveGq5LxxHl2FBHR0UPkwLakM7hmoD-4rH3IoYArvpNslQQWQjBRgsyAAsPN4GyXDEbrr5wJdl8PqS-J7hXOwJrjcH8PJNfJjOU_
rXv_QTuIiLfwORk59woKNT1H2YTg3ylKNk7tKygdH9pXaKizxyXBBp1o6WrDB2kEUsrwqyBVFZsqzH9OuFsq9cAnXUUSK-d5zB7BackWo1tI0xDXYyzLz3oz
jERpyEPCCSjzNiHzNiAyscCfpiW9zEKxM62dy5YwM4pFxjhQcAgzOheBg22QRmER1JolSSsgFPO1N2iFVxPzUXxP81QRhDJ6X9XJUmCmWYYLDqzP1ArKnWWl
PNRjZRZozCMRx-8McAsm9GSy-jCv8PhQwuOclJ8plLOutcupxcCtGN_vjgOda_uT6PTfCyoHS3zWoYVIMw_yk75wfcp85nlmfe_7G4dXjMWLLlwAIeMN6vTI
ZgdqmgYE_8wN7ll3QwjtVksDp6kVWYspucZkQ9woKYRJcnocmzuvFUyeFEKZKVUz3AnPRgkcfyS14SRbouzD6MoSNlWYinN9wpls-qs-8dRQ9CVoU0moLN_X
nx-Ce8e_jGtZzEID37gfd16EiZrZaBXxgZtgq9BbPrkdzwVZF7_wjGCetm3C6xsi_SMVFRoUeppu_TE0HJvGuFtIi_8QHCVFBL0PZ3Uwb-slAVhtrpVUkC5G
lRIy9yTVB-4fswOd_FqOZrP-11luYADGRaWS-SX6CyRkpkxfkN5wtOrppfSCjw-yOg3SdsB0aPlZwV1DEszwnediC30uoTe6ZqcP6jJ-wZ_zB1xxSAz_KVnn
h5UmkUxylGGZ7n7zvsfywwlayQUvPWpoP8ZkQPmTDJrGUH51Dm0TMohBCTCpOrvBpBqEdXqNO6ruAj-S3EK5AKZ3_Cldk7tjTToOuseH6Z1h9kU7IG_cZ5nT
tE5BufisEFHtms_XoGwIdgtKAyKlLk5EUGNkMEMtO7C54QIxFTdLGnnWt8Fv8j5f42Fwm536Nzl0-0i-OWmqoWLem4hA1ilUjGSZ_zuCEN0Re1m2QbsksMO3
EwS7fxANRf5XK0xgrcPNwQw-m_qayRVe94NGtGhAcm7S6R7Kf9fbAu_b3cFq3EDcAEyDPav6wF1zi_htHmOlJZ63D0FAUU0hnEmbAvjHVkCBqKaHxYZd1UjQ
e0Whss7lif6LAp0Z8pfEInmqlQ0PofN0Piy4v2XRGdJSAkhC-czlgAZP7Q_uH1hAfPbJpmQJiZsBsVU7-e0vVrwP0CekJ3EYAnzJ-w-jxChrqXpu0rHlUjjN
dvUF9rCzErWpK52VCM_khJ6ix0tEh4X3YOavouSnDbWOwxiDgkZuwJX2GIiVSAfZJNeBSFTIJUp9ATU56bsBvO2OFn7zaWbYygn3e1mGecDLONVRFsIIbKC2
ExQ8dmi08vzU0ke7FoQT9jBTxAojqibuutKCkF8tgdiRpmEpjqSGRxIaDqqfaJJ3u7sxf3afAUS9BqTdFO_Xwnjltzp-mOhhRKrEbL-bYE31HqMukVVkoWt3
MoqmzD1jboS7PZ1WlyuAZEpkaTopau9utxFA_HHixxrXMBSbjlSPMUXBS9nbMq0_jTTwkLlzZPwaxjw-lIvCokN4MwyqmHdAbQZ-rkk-tpYLQz0vTcJ1oD3b
hdfsEzK6HoglGAGPJhjwA-KPIOhpdq-16Sc8F8y8acvMhWAt4FFDrTM-Sb5MBsFK6xN8WRkZV3GNXySW3wakvarVDFg1WGrucBQgMs8TfqC-uAEw3F8bLw2R
Y15zP6L17_R5oIeQi_fVWvNR5vIjVA1XSw1HBk-_zk101W00062Gl_KzlkeC000000000000000000000000000000000000W
}

