sprite $rogue_AP [93x93/16z] {
xTU73kiW30LGR3mk___3JwJk9X88lvshqNtgOcBKyb_b2gdMSXOnsS8Tm9bk07J3hW1WPHX2pmREWG-pXyTFvpAE0jXTzFE66hHiubpEehduXNEL7eVAMGmc
HoejqTMn55sm5O1R3s2dSNZS0NowU06CLjPS09kq2T35XZ8WiuNxycvH-1pkBrMeqtdNlRwEE9h20IxB-MNuXLyuYQ41i9gFQti4DHSdjDTO9XxsCvQ8U_kC
fE7IlfE6Ou1B4ivj44_2jMEeRCUjt6vR4dvW57tbvnDfk4TZqMzh8gujK0jJ4vT5kcL4nwtpxJ6IS6g3Q19UV81J5iwZmhFmef-sPuvS6zW9-72yqD-14uzm
eWoSMjEFbkAO07KVxun_b5wF3ki-pXudfhqT_XgtUpXYe9H2LLHLZhlUUhPnRwtNh9-JpD6mZPDmORmkGZmYeMtyMQlHusBLt8k8_7RYrrusbrpyndfyHJeU
cz43ISOPiSkpyQZRD1gRYqSZex6fU93Fnd8EpYP5deryxlHgARC5dstasvEDTd4V_f7GdC55rktHF73EEYm6fMl6Rl5MHrSK-E_u1ttXZhfiqooki6LSu6Kg
TNrTo25bBWRdLTiNtWkjF1t5IZNaMChYBwtcyx99-MMvSkNAbHy
}

