sprite $rogue_AP [446x446/16z] {
xC610000082W_QaNgG80000000000020sRKJN4LY60Z3TabLylqlFFl2BkIPzv9srty2o9SOwF2yZ6FcG58a44jBy4U8jtEGwcSY5jhnpyiGuwqSL9SnOqsi
ozJOHiPRniUg9f_nBjD2lCiGhtEfkezByCpNNBNbGolhKOfNETJ3k60J-V3rLctzig4QkyZLaxXw4tbqzlTyQRbUVmPOh-9JKtbqMczXrlFaj9xrj8bUnlRv
5mCw8y1nZrNBpYPogN5FodpuiCSkOXmYtn2XxbF6wnoqnvPdvvxAfVQOL-ZWkQIsM3Iey-yQXprsVAep0DmcgqR_Lh2UzQndFUjPprblGTPprbkHzPprh6Sz
wrdFUivwrhEUzQndFUjPpthMivwpdlMiPpthMG-dT0MefzNVjBAtNmQG9uAhWV44WWcgXYOYHaVLvAIvVadL-ARwGNMAc1CFNfqbmGVlo74ONfqhfl4EdERm
iPwqqxEM_ikO_U67Xsx4qoxNO66iF-5bfEekZSKJCoVTCMJYteyZySISU4C43kHBrNN4hFkzvtx2k6yic7mxUyit38_3xzPJTHb7pKt4SBs0wZ8CEdg8yNgH
WsQd6dXRwdN73QOSFSOfz0AQyScNJuR8RBtWZCF7IxmyZLxEE7oDTp51Br0NJRYH5Kwa5nmmEbaDXX5wgBznW5wUIYzu_7lQnWQSg8V3_rx8vdj7B0pzHoOu
_0SVsm-Ce3t-tCC-m2GzzhQkSeylpVY4DxzRglxsIv14B0ya6J5HhpyyvWVh7RavUb_PknCLsOqO2iCk3eZZzt_WxAj9pMXk7slQv1U4rSIN-LgrgrnFraDl
eVU-WHvwwA677dheeOSUUkYXXnvwwA677dheeOSUUkYXXnvwwA677dheeOSUUkYXXnvwwA677dheeOSUUkYXXzvwe1vwakhNS5ML_lnFwztrq9FAFlyZVDeb
ePVJoykTdqH24BryNEW-17mlFVJain-staOFFUdyQkJzqCldtJugxeTUtcuVjRvN3xrL6vg1vXEzaSJRHtsV7dgrGKcd7thvM3u3eM_HGs-Bb-T3Bz_bXQAc
zT1JY2xFXru-y_AD9thvpCjd7thvqMOuDAQ7dizqM4DwwDMP3y_eeQVpdEH3Bp_Sp8S6zD3pUKzutQw7NfrtHTsjXvwINlbn9thvrCiFND3Bfrv-u89UFFK6
UpxqigatctpevMSByyc7NZxryh5kqqElRjVJNNheBT-kvxlqqDDvV-WcFVJgmNhedGFXU_JGquZUUguUUgTkqKFFpzL3RtrIZLvL5z_TOu6E3xrSm_ddIvQs
Vlt7PlNG--Shv5QRA8_geLVDdihxdVCMdmRrqDFrGVSU6zL3hxsfuvQ9FAU7djj3H6qUQ_uSnlJGKsylGlrZlPxIGy-zHhQ-qXPFwA6tPr7piS7SGwy_nEWz
fWVd7dh7atCFlMVa7dh_atwFKOl6z5Xh2SmOnlNGoy_Mv_NGysgrYDMVhAy1FVRtjYvghb9Fxk-Xzz8EaTNSOgWvFSwrzBTTEu_Dwt6chDHGwHwWqB0Uvpaj
zKub_V5O-RrEut8Qj-fYidqiK7-PrgEEWIeKQeZMS_MetwlZ6_IedQNocRfr7xVfeQVvr4Cl5nvFFVHoeV7KG-_-vEEEGEu8NC_LutvE7NDwt8tBlTJSIvrF
FVJcrwhhcDVZUmny2uLleLWpUkWT7kpqq8k7vp8FlNXeBlFGouUcyD1x-4U3qSk7vl3GouVccatqyY4FZZRHo_EDDPlevGCzzD133ptqq4CFFVJGGozNb88U
UkZHSg9Npz13JrMbunBAxp18LH9w5xt4UhJhBhthUuHUIa_UREWiPq-_r-Ozw8MwjyfsVBLBPI_q8dhQDtLAwcdlYbweRi7Hv5jRlLFe1VJqqVMPSgxXh64z
z0xbAaysibazz69jfxvP3xt38Rp3-POJlUMFw-paq29PnVJGwu_aLsLEuIfHZOdUTTtnqzEp5S2xDfqk2RsNz5JD3meviRMWp45hzFOe5V0hTGiZX5wmpcIV
44lLj-lp2xtmrdcjZNRvCpdlx7Vq5dg1rEjbXAhihLn9NwvdGIzmxg6V4alIls_tTrL95xdkbCDXFVJspMV-FMTC3xrytQJgdDT3xpph1R_kEWrwznMcw_xg
sq8lyQTLRPhFh9slhqKlq7HgyzUkB9xMltFUpDO3UqFQTeLMCl4kJRONUZySvVFVnt3bpEXbbJ_u7SXxFFJweVA_ZpOl1TBlqn-1LB-zjljFHwyF-ghVIev_
q4jaJkir--oj8n3etPr-SYZnq9jFlyhOePVtizQFe1_9G2_G1EOQNFJc_5nR3GtSpebUOixTd-ADwA7taicgGEAX5uzoWqMExCwZDpNvouzMq9kVFEntWcuC
z08Bby6r5VJcHozxL_H6z5vRUuvD4z2R7xt44W-z-UOplgY9tdpwvHjDzERJpoaxzERzAeM7tZnVm0wz0RvepH5waw7Azdhe3KR5I_xGUvSPdzvM3ptLm4eB
UcE9bziQGc_Uph7qGsz-Xs-fSjDszEOF9rKo_T3Bn_97GWhueJUwBtjM-4GPUlC7uWFfXzxuQ2LuaXgzLBo28W-cdz5B5kFbZmQYbzy9SeMhzz2RMzGivIkc
qSj7kUymEdb0xqw4WL8mz48DOBxvH6ymyVh3dOLUN4ygbTBpxatwNL-xq7j5JxukEM-kASjUMA1g_8_HwpTn2YzuBRLA_Wgzo7HSsqNDxFBsPSEfq4jistbf
UqmbwQTLWPkDqLFhZ4f-wZ5ogpWt-biJvz1YUkZbj-VAytheMR79_xGUUXLTl8dheQUn2cPL_biep1ZcYacKVPVHEpHOmRpaNEgXDtuEMfktePVZk_M4MZFD
qUitQBuic0tLtTfksg7NJmaDfLwnEnlHyz1LLRKPRA8Nx8tGG-_J73_hINhedUZHSgBtGKxuKNherTICOVChGIysdB26Pkj2BwCdZ-0TSW0FlMl86xnmh4hW
eNSDbUsitVuzjNaFUayFzFA17dheeOSUUkYXXnvwwA677dheeOSUUkYXXnvwwA677dheeOUUVsQtFcmi040GW2e9XFqdlhJh_QUAlWsC1L7RuBet6Azxrxqh
u4RtklTmx1dZArXyE8Mx7eExrpMI_49x3oTh9avTlgly-mdCrmg8VEYRx4wdYB7bpkM3ty2LCVTkCkI4g1U-B4RA3L7lQnwlbBa3QmJLmctDKz8TCRkYDVnE
q0EMdtsWmsuD_8vGiLf-HpKV_HwnO_6i3fd8_Fw1yWUe1EsFH7O5QKZ-29K1yXT48W19VmML0l8oGkM0bq55uMtUO4sleQuub7TWrr2tVaI50Y_n1ciektTT
sPfo916rG8DIMkU8hYsw0SO0qBNEUMeFZWK000001lbRxnj5DG000000000000000000000000000000008
}

