sprite $rogue_AP [446x446/16z] {
xC6n00000C2WV_x04wa2000000000000WDcxa_IsaIKAezE8tF-2twHQM_1B5oy3JEZyrOmeWOcZu8VEycLTwoFgNhyPkJzRjrP_jY-e-cVdlGrsz--uJhmD
U5KtuU5BuDKzUFW2UFSSD5Ib-EZL6gvYFqNmvdTR1N-AwDNdlmtrmNggJzSxdu-UwD6ZHuyUFPKp1jTQwBbIHizLQde7lmzyVUxTMNnzpfCH2k15-azuwgEV
2DI77ERHeqUF7Zrwz4HlD7gYTsFqH8yUFNhqw8aUFNhqwD6ZHuyUFNgYHuyUFNhqgdfzjxhhMNqRn7FX2DQpCtVypDrzDRoZOuSFtbqrlAE3TtJmyC6ZbyVh
vznZw03VGNXFl4Fqo2FF3RlJzFQN-ZozNa_LMxsnrgFn7dvlVP9l7g-VeRU_u2VfzJfLBx3Yq-_dhVKKlNs-nunUFqTlVz6FmpjVxto-_3BedV-BDi_NMuyu
Rgadw-sl_0bwYzuPqUinlldLFrzldQzN2RqFMK1_QxrrejvwuMryOxt-a8LVl0rwMr_x8MleHUynqNj-z7uTFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyU
FNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqw5MVfqUllwu-MuzURxJoqSlRvG7fpTFb_UZbxKRzwENjydxqfktc_UZDutNTgqUl-hLkrAFNBtUR7hqE
T8yUlUfCD-ZHwpvMZrxdcjQZrz56zUZrkNhqEjsS7htgU5DwzFeTJUhHc-UZDsytpqUF7hty3IDwURpvuQENnylpqPl0eqUlJzQZrs_KezVJUlHcyEZHguFr
wFMxzEXLp_FHIzK7wD6ZHo_2H-yil3f0ZvxPeqTlipfOZrx_glh7_rzvsRmUlTeqtdZPk1wzlPVjVhT9FNhhtss-R5AFtlxEtdpPH-hHMviaz-lH-shZ1-lH
MvilEqIFtlf4FNhhovwlHs_HeqVF9sS-Hotqd37GMmyyMwTNcw_S_uPpUlIwmrUfrwbwxX3Dwtck9NWJDwz7Rzzbxr7Dxflqw5rNlLLv6jVpdFJyAPHWzEfW
FNhhJNhqwW0zUdvd13rwzEZbkX-FNfwF7hrQv-hHMwdepVFLmNhqraNqSWtZqSjs3nuzUlJMA1wzT9DuzE8Duj7BDuX7Bz_9UlJM81wzV8DuzF8Dsj7BDu57
ZzvyzEZHeqUF7ZrwzEZHgsVgqQFdavCUFNfVx-gyNe2KthNIM_Ko8qdl6Ybys58Rsw7tIXl34fcz2rPw8RoytiPsCdhqydoryQkiwMNmydhhHZrww_lgqLkt
wj5RCRtr1ZrwzN_sQWmlfqTlVoOgOFUMsQFN6oEHqyi0qhjsMLyKi0lmqTimIV2zi3LwsthxUxJUWzTDBulNzThuNTX7zUZj2-mB1hP4RwSTXiWOrRGUlQxV
-jADrmxeqTlViRtMwin6ydhqUhrQ3UdHo_jrzumUlJnVZ-avMrzzKTQkLaIFNlK_oruEwOis7YsZjzVFGYc_-jNtsSEZjy-tiTk3rxytyEXjjFyKMMBmhhTB
R-3lNG_OxKGlxzVl-5fwKtmrQKSlxnUtepV8rmDuzCRyvktevGyVKtRqviUl0dZqnlnoPuZqxlMBpHsz-PE7oE3H6pzwIHvfqfl_-AmK7htvyGlOqHjf48zU
laaxUlacyUZbozlH6onkHs-o0JnwytorJjOpUtsodgEMEblF6SEdwj5x_jcwQotrSNhq-johrFHgw0OHlNnzxjrPUdKj5F6ZDs-NVQACtlmZPQdfepS_U1b0
UlDpb-AZDu-NuwCtRvVpepU95m0FH2_eC7hoG2-046AdDuJtbg-cDu9NxtdkXLv0AZ8w-n-Vrw3qzijSSjxt-sApz09ulM6NkiJM_unU0A_xSe-dJpege4Vl
1woA7spitO-dD_28s7c_LPpUUgqRzUYjrxjBZzwAT8SUlPLgN8_UIfRNerTJU6jDwlcRI_FLZ1wzEn-qeBVVx4EqUtZqzgj1lNLXHo-uKwVmCgkdb-HBR8VU
VZsarwVfqQD7ZnuzUevQd37G2oxWvFCzUZcys7RexJU3jrQzGO_U2k45jaFlpEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7Zrw5a-F7htvwD4x
ltgKNjCx9SFNz8oUDIIYr-keBBp-bT7Ro2hyr5g6LVV12w6twllnTHrxpEApi-lS9Hk-Uj3ehQvlvLS3U9FL4NmMYwz-h1-ufkgd7wxysNgYNjNpx1wxogg3
bsQ5zIrRJmaUFdXtrV0UE7tmJ1yyuyUENwzZmxSs0uYE7pk0I_zh3mu4000000JvMmzozGK0000000000000000000000000000004
}

