sprite $router [446x446/16z] {
xD67gLWn3010OGjBtd_WzD2Itry3xbQu-3G0000000000000000000000000WF53_bK_hFnh_12FnCXSLTK_xF_h7tvtZdWCPgxzGRrongqOCrVr_gokp37Y
1kIgxlrLtRKoBaNsFb9bN8APrVjulNB4gPXLlS_ITLuW8_VfEkDupAnzYQwSSIIoUb-dQyPHMFjolUBh65dx7ckE-1BMT_REHC5v5MUY82b2Vly7_fVPP-eR
j-LG2N9JizwbSsqEEWYSfE_ioFrlKH5H_rjkrDyx1RWZ8pFK4JyUGAlPY8ZZ-eoukOVOKO_BDUAgcUDHzSir7QujcnszrcKELv5xXItgyIr-svanOrZrKX6E
cVxSpemnxrXIp2EcrT-kk_W9dShyVKbCs03ks4_eh75YFrMWjVFiM7pnCOxOkRB7VNrkQGv0nm0OfuKlZPJwiIK6paRCrEUMPeHzL05dIs2WFdV4OwNrHiV9
uakmGEteoPdpjwRJk-Mt2ozSbhog1jahtlGZVftxJXgK-OxHd1dljuX-rdpkI4nq9Xvr6sqF6hBXMT2EzGUynMzk_xcRby6Rrp5FSVhVfjX-ZCTvIwoCgIkK
_vcVoxOcOvCmO38G9XhOS_UQsYOavlU7kdlFdsGK9en2CTxkFMptAtExy853F57rktVH85eeU2_j6rzhodJGOAvF5Wnbr8Vd12KJy8d_yjRJcBrRq1-BMytg
At3tK7aCV1eLMq_UmkySU3Z2H7lQRwqyQnHjOeovtx5V2I-KS6pAncVn2_4vSy47U1iVlV8QKPjKln7mLOFdhACtFZvn9huAsZGsF6flRxy8dt4rTZq4V8_V
jckY2WZT9WUV_n9y6iJx17WZu0zWsh1kIpUyzxGv_esd2LOVzyQU5kOK7TZ8_Ziz668kFd_oatI-Djj_qcjAbATWwMzuRsWJwRNRyjpLPpnj2cgp_OaUMPuF
VbvayL5j8Ztw4Ejp6q_vi3QH7bu7VzikJ_sGa56xpJ_JOylJ7zgv33ey73AaHvUdFR9pCO37rEO9lO_BKnu8pvdTvWazkZpnUlHnYru8KPidzFZon7iTyh17
Ui7KvZazlZprOG_xZBODKjJc6RtJwkDjREKHtkItcwDTfOVuYAgfZ0-7c2NEqIxJGtaQyuxBneYt4g3Dg_Im-fJt92piATuCOOtIQ0bwY8_m5Bg-EwaTc06y
Y_HGdiuNJdrl6gkmlINeOOq4UR6t9tXpiDueCzeTUas3zIpd2UuSx7kG03Hdz31EEalMA5zy-W5_gAgsbgN7ZnVViwC-lbdwzkoRvxSixKgwYlPrwNLrrquG
3pzyzOl_9TRNfDVjRzTtO_A6L7wqCAx10tmBqUilzmI-oesBtl2c_oEs8Btk_umGHc2bHFvnkhaxL1-TNhxotFrrOyFaPLkMaIWzmCUcbuVdtfxhJhnmJTDp
MufUTy_JqwB7dHOtfE5-h_fwbzvlqEkj9oeFwANT6LgpzEGQydluxENkBytIwsfcflqMF2Ei7wLNFIm-jymFlPBq_WwavxNftXFoBdTUTlEKI01VJnIifUWf
_DZrodEz-PGb2cxKhJ7mOLdq33tOkp7WjMRrsixx4wvdvQdmzrwZ9y3YkZRb_YFEKQxX1039wgFJcrXv6A_MTWueFGu-FhqyF4on0nVDzrdtvMbKUdbjOgpM
QIUQdb1zXDfZL1wEXvVwaBCs0Zu2FH8yB3ufj-eHvCcbTr-R68cbDWtyQyNgOzAZLXwsdMtXME9IK_BaqIF3QwtEnsa7bXvJdiQYTr-Rc56bRn4eFKBr4MgF
LtcucbGvulH6m4UWHuM7GYfIUY2R2V8aq9kiJOpMsB4RxDIdLb-Edi4yEg57h3milZez2q-UI0-l1gy4wH7W4HOKVYHGd3Hv8ht4xri7UWHj4bOKQWocsEpg
UwNeDO-86DfEwH4g3n85r3dmH8yeJwI74H5f4A37XjUqW3e9Hq8epnGz3D8ZQ1Ep_fRF67gG5-2RJ8zGUHXV_hGiA4jpDv0dWHuPNjDO_AXQM6_0WUeZq2De
izPfcT7wAeFEaq2FM7ceJckhPQ0uUVASI8y0Zx2R8aVGx4HvJgH7qIPcxGsx1gY1MNtpw54g3-DBqpDSbhdod4cF3w_9qdk60U8aotCMFOusCKilVEoU2ZlF
QVJubOVgR4j5yOoJByyfz3ZmCBRm-peDPnPVdbFeWJPV_GDDkQqhpj4ewI1FUv-UlHBm25kgmikU-XZ3DOiFSv_U_SfJ7p5CRZv0MtRP2yrzr2yy8KyIlJmy
psxTZBbd-FnUr2BVG1kPNi-pq5kDdHNVxLdSM0MwCUczCl1GDVpUO9b-ocxEn1U1NXfU6pTSCqhGqniVRyzqdWHwMNWjO17BxggawY4dmZjQ1X-9NazErwmy
1Nwau5uTSMSRw1U3tglJl_0UwdN1fiMJbOVhddeoUNhvc42J3J0omsHhqhCyl81T0PzUFWOMJ9hGrsnRSWUmTdxdxelISpsz2Sdj-7n9UY7foZFGvfhqNE0s
KlBKvSxAi9bAmKFdsCBqx0U5f3hL9LlEaTOc3EngzB0lpSiJwTcAzFmTRRRMrwA7MyA4F6iqdG7qxcgpDQb3BozFNv4URDrIsgnMUmbvbdXl2_18Q1FelKfq
BNbv8kmLMqxDQxDCpwa9dLJPCjY9ElBtsHUaX-BConFfoOBqajh4wBBqf46IyeI_RJLwMMrYvBKaFPE4LEhG6nVevNfhqNmo7keJNZyXpphqFA7DmidB4-dP
UlGieSt2oQi5XseKe9VHvfFmIU9CSHrwH6tMbwSLg3s2DalAim0zUEv1q6PLUHBCoQL7q6PXULQhFO8sAykp63sgDklB4_xYmlJG9JTYtuFXsU3zQaLw2Ez-
XYomZDrDQ55wTanAj2z4Prsy5AA7SxUcF6NUrMiTUWnunrYW0RcVq7Bqx9YOaChqZf1oz6BJWuLxcxDYxUdkMkhj5n2U5DenHEKTmvW6psgUb5cKyIP6OrRb
hVrqDa1oK_7vbmGZOmwykazd4PzRBjg-5_L8vaIRDUZzuYT4pR7oQh-l1V7Pxu9NhVO8rLSK7Wp6iNZjUQFWgrzvICyAV8w18Cygy4f-2eLGVJMrMP4U3Lzz
UBAyEUKQFdkwDijytGvSDg7wQbPUVNhvwXErEscNqoqTbNJbOMnjUcZpFBx-ydjXVtQsf-3nl_63l-7BoxExhqdFBQbDZ1VxfgiyFbkMdciE7cOiJs-y-Mqx
lYuzxmbjblcEm0OwlrzzjZ8zILHUKNgImrU9dcOg3wFBDIteSw2NagSNePU7XojCWQOpKNq5wEMqUGRRrpnh62sBhvuvy_3m3K05VXTAMfwoCZt9Q1DpLAEN
hpvRbvxThpniMgJgxm13V32oov-r6CBBFqahzitKY0z_HBp0EQUWFtA3D8hyziJyRv6ortauz5xdqTCR22ly-_8Tb9wiFirucaDFKZUSXwTmmwl4qksKnTsR
4POvDICRq6OIkBHbahV2_IULdRVkoStf6fOlrxPIHdv5jhYpXeiJwENnIHgUG6Utg3f3ilWIuqwXbvUdWJQBBdkeJasEW2MqIQNdahPD6E54Oy4T7yOyZYE6
9KQTHI-Fp_wVNxWGrfOrTtmO4P74eFFfkJREnKDNlbACtG-ZDaqdq5F3wkEFZxQrelIMIk3aIcRGQuYFxoPfAozymOTdhSsXX_YKtTMDjbe6LmqTu4sZzudg
Cy8X9_6mZAxDQVG-WcyGsWAY6-ZQd4cFBy-0tLu1TTAqEPKUl_gK8QOYLuZQd4kFZyzHd0MwJfOsvz8ZoPF_M9qtmPIdJG8zGlKHEZfcZDAto0kqUPcUYCW5
UdHyKU1Jmn9WTueshzBJ4H4nz08zhZoLCAtPNQUpj7bE3yVChj93V4POKhor2keaLDwhNw079j1JUbnyw2HjY-QOh4x1bUWoFODvT4AFYiyuN_Ix-cbUny-k
Ng276WyveqV75uIEavAfVOkyeF8OzDZuPC7Iuw_FWfL7eKV0Lx7qKF52q2Q17XCV3WalwpXU_qERBsaaUcHy0nhnTUEJPffYjycYnyKdLSI9I_HXi-3rHgF7
nMVmMQb2nKUeF08z8hv2fOSxTYTK7e4U2nzEvbh59mHu17eSVBYGh1vzrnNgq6rIwH7nuLHUFWEkcB3c4UWHy6aGjWlSADY2e4q2FGA-aVXuzvexzaC8bKUW
Hy0dHxNImuiEGkKHw17m1UprAiH16FVXyUdHy1bidWe45-j9tIO6nlKEFHO-YHKRplngROGr3t-YNw27sAKHy1KkFMmx3u8suMUqNQ07I5wjSV3X6DI9v-TT
XoVfcGT99Yr3hxyI_v1xx_ECHOzPEDTkDzyAAwgglRKKlTODlZWkWIy_VwDLYXtP9Hkq-KwG7aQajuknD3qDwBiBHIBhJkWsUVJoiIoz0HlrqiMdANhI5gA7
-1BUh5XwEFiEIOnFRmHwy_1fuhG9Ik-XxeJAMuCUudlrvCmDQULYoIyWbHlmnDwYPsEOfF59VjKec97Sh_QiDWt69aNFauSWujTs6LhIcpYusJrFLvMyciSz
Ufu_m-hIWHqcIhGiwSxBIQKzxj1pS3hfhgqLJS3gpQdiaQA7OymqpcXLOqHy0uOeGO_t5HoQkELgxWnINSV8qNEQtAAED_CtuwnN7WbwCAc4OGIShkNtx66i
UJ4kqACRmHu53-_dKDOBZwlq_63PpQBwFXrTGjBK07oNw26yQDG9LTsTd2vC0mRh2Zs49xGxRVKZECXaV4ZlE_2arGrVA7B0Av_G8siJJMxj2S4XSsxr8Jr2
vH5kiiJInyU7z3uFBzfZSdnKdaYFhyq7msi6DMB4waDwdwyyRVN3lpt45mFfyU6LVgQNLykXH7aYFRusiVwVMNryUGAzpshJ6-HnZMSGyVqdFGyYl09x1OBX
c9tdlzEZQfDGrGMgZxhlY_ZNFeQeJGAyZG_2ETjyBZoC7f0X17b2IDeKmiGeiMldFp3YLvu6OJ9MmwUVnHT2dOgFZXqOOygJ-2IT0AzYzHcX-jYLvuJAgudl
60HyL7Ww20rObSwJjVZ9XxIfKK2Rl7qVovuQdwWyOogv0ZwMU3Jey6GGuLM8y0PNsDhKep8ytlmzZ5bz8QIpCJpmUtxyO3Kl6Znu6WHuLP-sOvmap-1DkQES
DNdpU2ZbWP4GBXXziV65h_a9LXaC8zV_S2RX3KioNPl6Q6Jh7rfpzAanjJni_9cTDSYsvn4kqruuPAOqjpNnt0KJDacUCQ_JnBFr7IVnqvXH7sA9ozlsd3T0
6k_30tQ4ZKBzSpCAFpc2m6vR4uU9ma-4uCnTU6UdlyXFskUZ3kmIf-cx_Bvw33noZmbtnC_ugRHFHGpO_NoGjwDdenOcNrDc_XHedvnXzDiNOErgjZunmJIe
GDcz9ytTVMB2ZRFO0RexHwyxUlmOembpR_4u3sJGeQoYmmnhxsItdvWORkzLXDe8GCThDBS_CJS9cXqGlZEtFp7XRYeYLqGfgkRmoWndRd_6SJaHCTpTL1Mh
HLNLt1rCUPfmGjtjXqU4C3vQiICMSNm-CKUPEwB-SNOsKPax7Xzbr-PcHtt4Hup9ARiTjK5cLnRTLcXuOsG7ZxVc9cAOj8zaHzGy9jQSwOVHxOZv17HkxNlP
HJX6n3rNBjAYR8Jc7WbJkfaivieTDRCumsPMeTnsDQgfsh_yr_-s1mSq000G0C1C_z1YWFyPKm4000000000000000000000000000000000000000000000
001G
}

