sprite $router [93x93/16z] {
xTY7ckic40NWwU3tV-5SJMJEyeqKs9Akazocydj4aLdeByYJ9qzOH5M4VzorwA-H7Yu_9OiF6EcXFq1hExKMRgfctlfvnFYRzEzGf8Fe-J3-3PgpwgPq4Oci
NhzgMnOzzTtq09xd-SjbjuccrkUFYgDu-O9zjAhHR1TAobNhv5s0ODU3yNbTZYQXOb_fNaVDkasYsiVJL5rH-pVi9hyKlzQLrW5qTOYF4bElOvRtwBoTviHX
9tvxUhypfTpTwCGFlLyyg-ysYfK9AGISkCnOtcmOmoDQ68q0HonykckPZaQn6BeO3rmLvxtSjYWyqBL3zx0tpX6mcJ0UsqxXJ4MlEEmpRLswe73e5QyswNh0
H4wsgllvEoLUxNpcli3h1B7K4yyaNksSNBfg5QShVSQ7lRYtVBeCvACU4_xHvkcf5xCJVpM2FkE1yQqOWMqnI_kujEMm4SrKtFAup1DwCHXJFEsMJgRYPnHl
n1oCjkXFs7iuTBxjKNmsR2BH4S5L2D7G4uy_Vh4exCr0nsqtkAJzSdj7xzVL8-TQeQ_nUCtXsv4rfMtXEj_KxnjZYY_mmzNzXGY_escNDg-ubON8tZ9dCLem
Kg6R8-CYHzwsOvOiPYXq2GHu87BQQDGvzOKFdLSufnrufIwc0qzVk7n4Agvy15_eUAMkUZGZ8QEHApvEKXWwhDt2zGBOCkC2lHIsM5bKcsd62VhSfCiLhbtO
9nwDAV4BdUydSxq4jb3YUL9FlEYbhFN2XPEeEFGoYXUBYrxiWbVTn_HSb6x59Yyuz9q5UhtCSJCnlN4I9kZJJmphEBxEVTXAmCdahRkECTvfAxrMqLwTJpmR
xk9fPVydBYqTqJdn_7khvJXjnceXxT0Jh_PwjL0BhRhymgziNBsLTbrx_lyT6xhMGwzYSz-owyB1YrvitRNhFagNsd5b7whnLxVzWYUzrHqs__BE7_WQw-kz
l_MUPTFgItndrnBbfU_u01Ox1qxmZspcPdfc_CkPVY1imuSiz7CHy-YP5gPC_veyUVBaoPCdlm4
}

