sprite $router [446x446/16z] {
xDG53S1G04F1y0V_VWS2njZapi9Bs_y40000000000000000000000000Dgifw1jwG5q2saeMctdr82AzXQmG-ao0h9wbbatQd96ADsd_QHJKBhx0rBRssf_
YTdb3r0x_Loc0ntPkxDT1NOT2CDtBJll_xvddazKsbtA7oXaNo-2En_b3gpfK1s8Iui5mG1EOJ7X_QRe-LQVvnkwW2VQrjWbFDlWyOV1klQKOvVxpFF-Rd45
vs-2bzh0s2s-6cbZx2hsPJHuTRcPEiOtThaj3TwdUbgV7GPZLzqVQspm3YnDlh2c-8-WkGR7ZzkQEhHGiNfZfvU-tERWrTcbWSzVXm_SaeAIpFEDtLhiaiDN
u6vWg_Blt0UlUlZG8gSGlFJmYU1ngIOR7xpYHZ8VlvcQuEByCmmUaBnaly4RFbulxk-KfUcHuK3jeEU2_MPipl3ayR3LPtZoU4NEv1cUS3OelE7ZzO35PtWI
HQS0yHi-FddLlyGtOxC0FU32GghWv6azT8iFdwC7hzR_w95yxVCDtjek_Rzww_Bmd7kUjVPUpszY-6wFpOtUyBbrUsnkzGA6voHFwDq-kjJe6MDpfsVoJVWk
ZqsXTtruJlBKoY_q0j8tOrFe1V3Ds1Hw-1wFdhcordDw6hw-g5TBwUc7ajSRMmLUYrnPwwsBRNNDs3ogfnzy_vf7htJiTu_MRGqVUXrYOQ4d7evTzIJlkDuI
mHq-_lwzMLZegSTVEQjDzFRFi9QbjnQrjR-e1pr7BKDFr1nSBewFNeOUNPN-fi-oU_vQoonUx_bRXSzEgFrw_bdVgVUlzWhYYzPx_bsade_tWgyhMK_C_L2z
vpyBk7Da9KzlpyFg-NZahIy_UZwVhySqLqbwkl5mlSTfBlLTGtjwbb__xMiDlQUUwhM0rhB3r-vxFMS-ROw1Uxtzit6ThVKRUejxXTVc52_qhFUMZw6NorT6
p-OkrUPhXTxkkSfegu4Xb18zdqy_Gka9TG0lE7pb7xKuFV4uPcpkzIenUa3wQ3sTlBpmsREUusjCJ-FvWoWqUZvVmzb3nkQ_Aa5Fjmka3z03aaVpyT43-00z
02_npcSSilpXsO2UFJRpzNIlFb-1sGEI9r_FOT43XYUGFGAFFtRoqGE79w1dZCteSujk54WVe0SaZnwTl1x1n-jflFpmyUUh5Xi8tFU0iHcafsS4Tl9KE-pf
wUJ1vvRywEa8gEo9FLDButXhHUjn9qyvtJQD23s11snCo9a57PwjDzdG0vA7XO-F7ZmyXPxu3J6X1-25w9LeaJbvjZ7WX1uoDda-h4DwU9xG0v8tUYeEGFO8
F5wFlUqnqxE1x05ZCq6FRx0smnF87fCydW-B7ZuyJ-XHUBmUt1uuF8zcRu-7lhWpzDYJvn4zFdby-80FgDdXUIfx11wlnpV73yyJUdiyUeSYFcX1JvvdicSa
pwgqxF73yuGUWSVl47_RuuVd2JrWRARfBLUlgjhVSqRlJVE0Ninjx-MNtz5xgM7ovT_stZ_WWXxGkzYZN3tZKWhNCouuNi_2SswKj9vrmR5wVcFcjJIgT-tb
sbt1UluhaTG3VaGp87m6ddyfd1xms_bvUlJV9YX8pxfWdozsSEgBhqSLEJbrbSkNhwVnIk21UZvV2xumlNhNLkihVnYzKq_XytM47e37wGtVPWhQU7L73vcT
_HjwFjvwhkX1uUjyFGClIiyVdfMWv-FbwscIH3sDbwUdBoXSpy2BqIlZaW0z3gyDl9WpP_-1Q-feFGClxlsUveiwT1x0Y_ginH-U5QFdNoEW1po3bRvGlNUt
Xw_KA-E67ghduyMKlhnGFG0lKQypzG2yJBv8FG0lr2zH3y1BJH-WH_SDuCNo1UWDdhZKC3qIBpzzm5O0UW1UA5-mNX-f-j1rLJkb-OBq-bHzGvBi2jNhF3sa
-qYzxZm-flj0lHwzVrMSNf-jRBrErXkzcib9rsHlJYqQB-iTG-pxzGeujB2_WmBYyHNmXW7-xJrWRkRnvNvt5g1ByriPUlDDXehxa7g-mQVnqlHo-FWvEp-L
b9wy-Od0VBpvQTpy7mYSduIFILw87i6NZmVePVmIKPTJBnes5-T_2IN_5_ZgyUeFyxMtl96yN3t_DvzPFVyfNBnyFVwl3l1wROpDWBzqTP2llbZlCP8dlZRW
dn2zvEldc_MU5tWnVnI-DbsvV25wUcm6J4un4Go-33qZUV7tFSsNf6VWvVzLSSqNf6UDpNmzpPUafvCNe6UqfVc2z3HUifxFb_T-hmsyN3tDLn6VjTJ9F-XV
iV-uL5rvVw-UnilzrwLza6_LDJr_UGSlHO_z9s2KtjBLHly_ghTyFIvx_WNtB_sxVFB_U0AJq-3BmOCil8jXxtl0gpL0p-hDYTx3wVbyArsldDxUNmj_vkpt
UYj0Z-ZjxTVVUCVm-lKApDeClMMCJKRF_xVTArBl_c2uzMuzO7_okdiOlGBuulIAxcw3TKHlNU4hePSRFX-lro6z7Ly7x4vGVvjy7DExaBw6zKxFXgB7vbfz
Ie_dAq2F3HyyDWzcZ-SZyP0EuR5vBdie7w_7J0TsR1xD7i-7uM5tPd9i7iyUSF8aeyVpWMDJP4zy3YVqsFHre5vZOrDaRzVFqdeyNmF7SPoF6fiYU_jkj9xa
As9V8lIA6PioU_jcf1xErv5wpUAjTKQFuEFrU3uMJsUlDfq8FPAFmUF3X-Aj1UW1V10UhmVW0Ta3-02zABxUu3MIFPYlS_JgLAybaWTaZ-Dhuo2U7huMU43s
23u-UhmUW0Ta3-G3yNY-0iOca3sChmBqHBi07f0zZAz3i-Vtky5hC7iS7u_7ym790xA7y7M-7d1W0REd-RBr-6aXyA3iWNmy7iy7Z4qoUvel00_GS_5wqTd3
-4gyUyhHQs1iejdJV9dHy_aA69kR1xIdH_7rZ-ZrgTEc3fyOMy9a6NoaNYZV1kzLMjSVrrkQmkVJ0oYMpyDxmxSyFM2WmydZgmxelRfPrdgbjzuyIU5w-U7p
Vn3sNwiBlRs9-qO6nilNEvj-yLVZ73xWhXVEv-7vUheq7n6zR3u33zJJVB-Av__zqJg0n-cjUg5NW5vE-DuyHorVxzNELcBq_2gNx_NBmzDxlRa6NfgUVnMz
MdoGePOlHy_OtR_rr-QhDb-lgUNlwArUgu7afV1XYx_G4u-cRlV3fzUkTtfWMx-iLzZQtw5NIY_VZrjPwXdv0C_PCpj5h8KUt9DeQlZqmls5UYkxwZwVrcik
81seT_-ID8FMQxCVVcxEx6n7Rv9dR3AqijQRiNdWrbVSy1HwvDYiNzIxFwrQw06D06UXuTleHOpDkVVLHYzgR4xwj1xVWh_sy6tqkB49s0NeaSFpV_HcR09y
uD8RlPYnENpLkchmtXMuYIsB79l0sfC-KH5ZSuuk-MDp-FAJDtpvUCF77vJMZnUuepUJLv_06xv9tjTU-OnDli1KN4bUVGHl-D3kqHg-6ZoKhr2-iJjLnMq3
YaVhJVp4kl1BRlYwaPN9VaVlQ4n0lD7ZRoFWE1uw_lKChBQfqOEsPV1k5CzNOyTLKH-EdDdYLkrDSHjq0A_OuCtjJwzRV5zJpUIl6-b9uutUv_UgpxsW1Z2x
cSbVNsmaD7ZZrr0JV8rVZHt2nsyWy9EymmTi8lQJl5Fz0S02w2Q0F65NJ-pGquCkubduMJtvymNvvQVwTTMXk8qTS4_ojxpjgd60yiVN061-OpTy_CYSoexT
L3RTL6LFpAdqs4rboqsbqqtboqsb7r6cofUBIjsaS6Rb_BFmFxS7nm800000W_oj9x6pMW4000000000000000000000000000000000000000000000000G
}

