sprite $scan_gun [93x93/16z] {
xTPLekCm38LXWItfx7_10ufBlisJrC7yPSWN1chhwkhgwkgAHKHLHRYNrUa1F0gt8ItqSBmjhEpFX7mEOQOZ5XqM-NMDTm2cz2OU0Q2Y3s3IQHA80ZxXHESf
yAVYuuRpLWyUIJlsvlgvWEinTE1hembdGFarXoVk7JY_NTEpX0lm7ZTOubR6wGotAiw92ybuz9ETYSy2pW_yTJlqPBq33oXPt7CXn-Z0PU4ljU2qyAGUvJVh
kGTdMJtcfOphcdt1FRzz7z0Ud0EtBEUeZWVqtVQyS5JnaRYTu5B1_JtEoN8Pduy3b1mTEA_dGhPmpn4TAP4quNO_ASmuuiIfZi-5nxlJlW1Km_rGP9iXRyF9
WNWE63dzBRW4NhF76RRXgaXV4gfVjfmFBnsu0kdesCPfkIQSIWM2yqM-RA4Ja1ekI3sWEww0KJ45GdRSO0eubHC08p1UySWvgYS1OCUNNOzznptjfkQEjzcf
xVYiYkTQOFmjkFrIN3-7enctLrp-5dpkE7yCvsxSFuUF0sUHp-6gokjgg1MFXSl7S4wRj1TNnFRfxyJ7NuGBm6UxL3rWYgGl8e7PYXk0d7fVRpfZ1n1hBA7q
ztTrTVKT
}

