sprite $scan_gun [446x446/16z] {
xC6n00000C2WV_x04wa2000000000000000000000000000000000000000000000020sRcF9DUL68g20uqkzh_Vx-spOei02NMU3LH5fIp1O7vQBGZQEaPe
-nIvBKGaHn3SA24vWkY6_T0HH3SAo0uVkrb0DPpsb9zw3_WcVEpkjegcZtExdo7TnABmgh76bU6jNH_UtZtGsxeDU8ktGc_lPk3LfRsm7NgBTqHlyGkAtk9N
53qlgO7eYTvCz4HlFdebUlJeqQD7J_HMH8zUJcnKZrvERqYFNfhgrwENlhhrwAMppNhqSfOUlWlmaiOH0xsqrwP7BulrVF5beBVMeoTwzEgKViRNW4UlJcn0
Zrx-ZXuzUlJaUuyUFNf5Zzwgw8aUFNhqwD6ZHuyUFNgYTtdqH8_UgxSVvJ8zUlbmb-lHomjjrgENC_Lq_23p5dhqwD4hUlJk6JtHe_SwN-CDtFW6hhKCwD4R
kCv9RzNbVdhqD72IzEYLw5qJFT5R5prwHMyYUlHoTptHevU3tKUFNewtMOzURg97Bn_g_VNevOYUnlHo1prweJSJFNhxl_VePRCUlP7_U-ruzEerl6rwnhFq
w8cUuVgOdkZHCrftQmGzUg97ZnuzUWiEquY1dkWDH4_qwEMjzEZbYGxgJU7HorFTSiH0B--lHozNwT6hU-c97Zrwz8eUlRRerHtrwDKHlElrw1ttgyLwRkYa
Hq_qNevUhj6ZbslqH8zU6l3swD7BW1wz5hvvFNeDJUdHgm4yUlJeJVBLkNhqCgXN4thqQeiUlJ6-6jAZLmDuU_JerPmUlQfnlEDw-6g2hsf0ZrwFNyteqVko
1he1FNe3qQDtMVJWqUkDNhRgqUiQxz7Bv79ZEw5tp-TSwT0bo4wzDEdXop_rwJNXqSk0NbxNevUBzDAbXo__gK7lF3nwMQs7RqXl00_VW5vErAEN4RqkF7mJ
Ucru-ERqSheUlGpeDUBncz7hmQEN0RsquU5RhOUlLMy03z-PUlblbG4yV0DwFNZuqgOtWOTlIgywmZUZLptn6z23L_JKg3U0fpQz2JnrwOtWQLQlDeHl2azZ
UjMGXlIg9OteLLVgrwk-rAnNhQbLhvfJerwrfpQzcaWzUdMlFDJ5Mu-Uw8aUFNhqH8yUFNgrEtgY9thqwD4JFT6ZHu-UwD4BlIUY9tgYHo_qwEs8dkXfiPxe
qOD7J_HQeoTweaUF7ZtHeqUFdkY97Zrwz4HFzEZHeoTwzEZH4ptHevVayKYoJuzUylYxRDEZz_XFMQL7Bu__bKrwz1vVj4YFNhxKonuzUe-lMgD7Br_hXHwz
hT4JFT7pcpDRzFpVswpdMiiUFNfVycML7hryWRT5ZzwNVAc5UcRhVz2bQe4UlOF1eoTw7gzAZvxeNHezqHCzUlJeYPxczKHFzEY57ZtH6uwUwD7BfzQZLxkY
bmLw-0RqH8_UHZnyprZaYwxKKmvn9DVfwKMFBDAZbxV1y-RBOZrwo_3m7NIUJvzTZrvTbPv5MMM7hpRewKcLk-BfEHHoN_LhUt0i0000033edp_mHAe00000
0000000000000000000001W
}

