sprite $scan_gun [96x96/16z] {
xTPdmgCm38JXaI9BcliVU0jsgiCsYsqVxvzK7Zes_j_EpixEpiv4pPfxVCczcKgbRPwSYgQeo8AzZF2jo1pVDC5Ykb4n7H0T-sHOIfACFKDRaWqhDQPYFmdc
eX_uLaR-vNvYIr-JuITM6ijBSgeL-i4twTY_bSRn9Ms-SDlcnp4-QdpTzxUlVDsNWUtuNkMBtTEh7rL-G_0XlVaDAmcfmpVUIm6fTVxC33-hVD_RCSDIdV7Z
_Fjb7hobK5Bg_CO0ahViwdFLp-4d87hhuSRMTNz-35VwxQrlco_BVkpwMUvhzlp-3IchldTdCtjPwFk33-kDWN5yl-f7TtJdUw1Y0fHCVSmuhjiYt_XQeiRl
42pvLCZwzEVRmh6-DXbxjvQIre-FplUT91iM2xuTo3Svc8BLahHvX4mQd3Gi9qcsTxwJ3GL9aZ7xIJfg2fAJJmQgQfDMnOyq9zzHMNlsXTHYF_zftvvzFTwN
Vzn7QVOCsh_cwwkV_wOlSgWlbyjbtCxblW2u7EpBpG-K9js728xo5VVySDzHs-_reznFjfVfMstETE-JPlSW1RKflzRkRwhJ-982y8Wm_F-TdPrz1W
}

