sprite $server_PBX [96x96/16z] {
xTM7aaDX10LWns1u_mVUaYeziYlLb-aovxOVT7TZ3AXVmGHq4ujhATN18zpa8ZMFC2gpgsyBYxyMIOHKxWLKOwLdzl83H4ZfRfnA426SW0uWLQIUluTfdwVA
t_Fnx_cCZ0wbIZs_SEAUDDztWFPPgdISdrYH6_DLCZh0ilIftrUpO-ydLLg_R_Vv_D3loqZeY5HfdSzFkb_amlp7Hyt_UhwQBtveoeyLQSeN-w6cytsF0o-r
vEV-RSX__FoVV8i5nukU7yW2p_SzJdI9xZ3_kML_BIt-nxWXl-JbyZtrRzBGlqdJ_kAm3-hVoP_yoMTSJ-lvLUZERtq_7tX-lABz_3ZLQ1MzcZ766Dy
}

