sprite $server_PBX [93x93/16z] {
xTPLOiD034LHqOoa_I-u538KHdOLrFaqt3Pv8NXffI3z0M4ZLX-W376eFaWnt3RtplWdxkuMhNTtXY7itY643ktHEa54SuDXvWqYD79zSmt6JISwBB4UuARu
7FrqWMoAQviGMCB9YNXSO4XkFELfaUE9-nlK-XGiSJ_05nkqymJ1okJ4ta4H5lgkGMSCbkHuWbviq8OJi8O7AOCsF-3KUERJaZheuyN53YWZtlr0CkB01pLe
ojTS_g3rY-lsJujc3ifwW3Ley1VN_dSe0u3yTtpwYmiQXUCH3nHd-w881oc3IaOSvGl31_BsHE_GYbUyubs6gLim7eEnkEamStkTGMbO3ySZikEtLqefvHq
}

