sprite $server_PBX [93x93/16z] {
xC610000082W_QaNgG800000000000000000000009WTCx7L90nXc0AI4VqNlFlkku0VWZk8F7nX-CqXAG7wOU6PbCxLTvH9zH0AyiFW4LGFe-fPuA6e7acX
UpBfkH3Uxgg7SlCdUZpbEdw31-_6Zru2SV86KxhAcqpUv7L3ncC3rNzGQIwlqEHjAupb5QFIH-BRVVapUMh-dG4JVTgH-wS_FEInfF03m-hBDPScOLTzKOiI
fzjV7wjklEbriOvTSONLuiAFdj-bJqQjb-iIuRDmbYxIA5G_Ikyo3TrPqCPGBWzdRdnGaCd6kVERZCNsTXucmkFU4ai_KYoABtVircUFJVR2ujp2qdwGXRtQ
QeyTzivUEDWZ_xDpPqbseq0OHaao0kBkVy4zlFLmBHHMqqh9vtEzrt1gnB-uqDQvs56nriltwXL_SYV6YLTCxthZhdd-27hNwtSz69FqAdxnzPElc5x57ttv
ELSKrACt7gn7hs_MetVfeDJFFRzpTdeLyLhCStymq9kN6dtNpKqdNZ6zcN6bjgjJhvXURy-C7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZv_xsHcnJc-XNJkrxk
kNfbNGQzKdpMk5P9zAnnw-jPuzABExxsw7aAXLxSz3ldxFIkDdFRaSaQZzwurAurRZ_nYkavvxmpUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQENFVlFlyGkXkY7
hxT7MJrhtBvQuywHKLJFtRZpkNVZMkFEzwznhN63dlivIsQDMpXB-5bHpnetDgznwMqzhCctturhZUjktCjbj2triR0RqUWvfRutUlJeqQD7ZnuzUlJeqQD7
ZnuzUlJeqRF6lLAqJVL5GUzwSzSQzxCgg-gv6zSQrzsu1RB6VVUcpDsuzAnnwLd2knjt_bzhN7fRrhZllnlNtRZqvhXKj2sv6zSfzKz5ZnuzUlJeqQD7Znuz
UlJeqQD7ZnuzUlJeHHxMw-hHMwznPqO1FNerrhZqt8rBx_mQjvWUlVfhN7hMkBvpVbe1FNf5xiQbPurBhutvtBjnwRMUuxYCzYLwHOh5lo_HUrZqgaQF7Zrw
zEZHeqUF7ZrwzEZHeqUF7hteqGzVWfurBhrzmvRzQrnwxiQbvsvSQrnw-xF6zRKtA-hHQ-x6jSQbTq-HP_7eLIp6ecwDwvJwM_JeqQD7ZnuzUlJeqQD7Znuz
UlJeqQD7pnetCyUFNp8MUlGgNwywHz1pD-v_7BsOrhZMk4_86fUUDIuzQrnwyVurhZLkBFJerUKRTTUuJifo7lVDXfvJQdhqwD6ZHuyUFNhqwD6ZHuyUFNhq
wD6ZHoyNnOFrh74_WvwxSM_ABND9pngtOjQuqKfdZNi4Fzl3yfspnNZIDqxF47tdguzdZVkjoF571TuhQzm5NjNSZPlZi5pZqNj-z4HFz4IFdkY97ZtH4xqy
T-a0lPgpp7NPIaPlWLVvkmQz-9ngj4TdbVJah9BgHQ_JytEFNkLldRtzeEpqYay2PnxzhPZq2byHE4S_VdPi1BtxYaNBKvf1xt7bEtuZzTpwazynUaclQFJe
qQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJe
qQFt6Qzg_Xfwxs_GUt2pqxibNtpqPj0h6BtIqQCtw3suR6_BttlqVEavvtJEIOyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqCbvK_yNqFlDLVQnn7noz6w97Znuz
UlJeqQD7ZnuzUlJezVopdk-g_-sTYlPxUt0i00000338tteEkwiB00000000000000000000000000000000000000002
}

