sprite $smartphone_iphone [446x446/16z] {
xC610000082W_QaNgG8000000000000000000000000000000000001WzkvijsqWXWAeG83WpFz_SFTDJer6gJR2vwBlKN9qoOdiElU8YCIPMVOBjwogSMQg
AdSm19Vpklm7eKJMcDTcL7x0Jo9gp5kaaiRMsiqxPLC1sQrgryXF8iQyNqQIUKTYp7jcd5S_2y_uLBnrwaDyYZVEpVFwKNgIg2TocN5oCggsJKzujtfQ5P7r
FzCJtkNFgR8-UFPqNgc8MznKszi7RqJSvO7hHZvu8xfSdKJT-sGN-Mu-U2DYkLboFFczJxB1Mebw3n-yZ1OFWWBSryJeSQ2B_CVgWpUopP2eM2GRhPDylD5K
hz7z76bsFZ_ALQ_NiChSN3MlqwXGlgXkFupu--scUjdlaaFrVgGwZWlLQxP4Glc-PxHyS9ZAzpNHgdhhSwTZPpKTGRaU6HwpLFIzS8Cpsvwsmk0SqVU-CpYp
yOrdSCRIAqPdxdh_Phqx8upEFQTFxV3uQaigBhxu_jbn-4JERSdx30vhB-Q6xFCLnsi_RiaTPq_EhSaTH_MBw-KEMsXZzbny-Tg7bkpNlILVMs_iM8Gultj1
Rw-r7pMtfPOTzIfU-JbPnTcV5591xqv7xiWQOzIx_bN6vNSVlNNY_TbtyjDha6Fqx3rwkaTFztIF7ZrwzEZPUxf7J_VewHuzUlJesNlqT4_twEaUFNhqwDbx
z7IFdkxHqprwzEZHi_TqZvxkqTCzUlJeqRFtwEaUFTtJFNhqwD6pz-Zf7ZtTewTxzEZHesVlqTCztQEdU_JeqQDdxz7JFNgwftlqwD6ZHy_UqprwkaTFz-ZH
eqVFtgEdUxf7J_VeqQD7pzwZftlqT8-Uxj6ZHu-UlQTxz7IFdkxHeqUFdhr7J_VewPxkqQD7ZvwzHq_twEaUFTsZHuyUFNkFdkxf7ZtTeqUF7ZrxZvxkqTCz
tQD7ZnuzUlQUxj7JFNgwHuyUFNhs7ZtTqprwkaUF7ZrwzXuztQEdU_HqZnuzUlJiFTsZftlqT8yUFNhqx3rwkbUDzNGlvy_aedjjorTBlz2BxtmPz5ecCbTs
zfxedkYUw1uzeIVsdkYUxedk2JrwOk-9xedkwPxG4tfYx-cUw9xe7ZsX9_RU1T4zqJtHFNf2J-mzqJtT4zqJUX51Bnf_2vNsNiTatuzhqRsOFnEwr_cJhdJl
0_4fS_JeqRFtwEaUFTsZftlqwD6ZP-_HqptTewTxzEZHesVlqTCzUhgdU_JeqQD7pzxJFNgwHq_twD6ZHy_UewTxkaTFz-ZHeqVFtgEdU_HqZvxkqQD7Zvwz
ftlqT2--fw6UxaNM_9hAwAP7Bsh-pCXMUlGYvvyPqKZFtikvJaKRFTsB-P2HNVHqBsg-IJJHqxsORvDDzEZbV9lHONRGMm_Euxx8V6MzvK2zIU_e_56GC_Hc
73QTStdbxiqyP2YlC-Wr-VRh1BsYzoFLxymPzTf_12lcgOill3ovQmxyqUQnrLlNUoolc3fkTCOukdghkTyYZMxVHxviCFRxBhuyb6_aidEItZXo-aGUUQoe
LrzxI-InBtv7rhT4Wx7HCDdrPn2r7fmlFpf7DDtONwkjVDMfUWRdupEHQ7RP_bPyoviuQZqobAyJNpvC3ELhD8HYs7e_4gFRyIt-ViCftyp65wnyCtiiFTNx
cPoT-7AetdgFDEAB-MTgMSVi7DbWJgpcfjdPetqvtbwer0DVD1ZnvkQpjp5KTC0BS6tuOanBx_bPxjP-aHFUbdS_Pzp8Rcp4mrTtySlwrnkp9STypBZUBrQz
qxnj_syhC-92kgWnvuURXs-EgeXhMhUYszOyZppNXdbgvjFK4po9d7TFRi0pFQ_CzgcfVlVos_JwXqJKl4NwRppRR_ildv9ZtAnts-pCp_luZTfCno_7NKRc
H_0aiguTeUD_9wOAPerBu6gFqabyJPwPY3XCxdDxS2030000CCZV-XvVzG4000000000000000000000000000000001
}

