sprite $smartphone_android [93x93/16z] {
xTH5OWCn44JHaXhh_WSspSOifyD9lytm7nPUrrfhRLhaNH4wtfaEFXC3TKeoJU_p92ceCZ8d7fEiruLqF3M2d2X9Hd6VDIC7LcRnmIGDQq4ljCVLunpc6xlw
eBBsEgygc-jpagCIJrmmtoWkaBCI3onyKRpZ7UzunplUyOvtlEFZy-9JK8j_i8vtV7nYFFbolGUkZdTSJ3uuFawESqfIBbRLuucZAIV7Gf1q0B8vrKSfFidj
w7bod3UI2c1kBdPx8r9mnK9lLZ5Gu4mi3T9GC4d5YfCeyNNTI4LDBEvvEEae6a7ILUvJvzQkCZwLYlSO6lcex8Blq5fhUm
}

