sprite $smartphone_android [96x96/16z] {
xTW5ZiKm40JHQOtiKTt_mCiSbBrPx2Vuc0fZNCJCp9GR5FEosD4LKrGSw5Dve5AnGGqeJULRxEfGCQf0SQ11Yp49EJyHsugAOngT0K762Hr65yzYIQnjamB5
W4vzw3ohI_gXZUC2v5H_c_jBxhlllllkk-----uNkhGVYclxuVuuzwNu1VkNZs_kkv-wj5_GFxsVZ-xV0UZrgwb-WuzzBVlZpw-IvN0Tsl9_n13ePux5HSMG
3ff_2hjDK1D_EfPGEioZ6DM0ffrw1pB6DUxL1kufPgYpgyMqR7r3K_nSPcQt
}

