sprite $smartphone_iphone [93x93/16z] {
xTG5OZGn241X227mxd_WNwjPfzxohOwzyP7RjDPQCuyyAjQKbvd9EIvr6a3uFCeNaAFSJd0zjrz0jPvW5rUVAXM-ju_NGmeKN2wose6Pf5mXM8LuR1i-rnql
RCDkE-BAWx6DrqfyR5lko_tlrvdv2l7DDuftlECTxtZ7EzxnZdTycDJYhwpZ7TStZ2TNr_lPql6Ek-kRnGDItoYk0BQFBCMJAPi4zYqV8BTRX6nqXPsRxNe3
J2vIc58Gf5uparGenANw0fCIWpGvOmIu51cGRkCecm6ub6bmLWvvYU6H79VBvBsrrjfl
}

