sprite $smartphone_iphone [96x96/16z] {
xPXLTWH130Fzx0Rf_WSES-81TtXLtxjb69Pz8K888JmItDRfO0x6OWa7T-XBpPESaLVl86TT7oHs5Z0M2lYH__RwYYPX-mpIgzi9Em0uIlv173q9IdwyMMpW
aMalyUA2tgvdy8cyaNtojk8H_mf_pfJ_1VBBBx_yyiill_po3qRLN-2N-UMNt-qFN5-wlyalV_XN-Xra_q9_9uaaw2hdLxa__s4r5vmVkEBzeFLSq9EOj08v
LcFIzUZNGLYHkLyWSBVzUW64vVXWGVysKyLC01y3_38-kGMwhUBHHq9t-vq88SGr
}

