sprite $smartphone_android [446x446/16z] {
xC610000082W_QaNgG80000000000000000000000000000000000000c9qxpMqR1W8mwim0W-7z3znzDvFOAME9oFlGtugWnyrouKEA1tPPbZAhlpOUzUzh
bNdvlnHPuxYg_cSQekjnS5q9uWt5XEuWG1XtbZrEL0MHsvliThluQMAtoVgf7EUiayrhHOr9ff_Job6xdnsl7zgwrHDULMOyiioi6jEUurDFwV9SR-cAqwpe
yxsdgfhS5Af9DPjsXvTrm-nJd_M0b_qAdw9FVBghVl7eeZhry8wwWmzUdlm6EowJu9trbKO-S_1Kz0Q7WfpVf7gBOPqzMTnLcmpglDxwbDkiIDaltgcfrniD
jBWe9ylH9elyHRtLrsVrxC75rAkz1fiFVMEpfv4cttmbwjZkZkrwcnt1m-JxMKoddicttvEe7TUBS6RvNXXoUvLRFeTeUl-CujxjjYsTcov1kVEfqrEmT7wf
TlsshBogNZs4is-h5WmK6z_QirlqkBcqT2xGMpc2UznUnzB3iaFBYclTNgtySmujzU0VAbYf5_Isq9ilrFHYOxtyy6zQBfliU_DrWzu3pfmhfmkzfQVkU2ZU
XTxY1r1zMvLhF-qKlHKzycUBwUts0EZHMnyzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7Znuz
UlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7Znuz
UlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7Znuz
UlI2tiuFeCVFWjv-xNplzBBtnQFtnQygut9ez4IFdkY9dkZH4ptH4prweYTwz4HFz4IFdkY9dkZH4ptHeqUFdkY97ZtH4ptHeoTwefT9RrUzwZ6wWrxjY3U-
rK5lIxoFo-UNhkZvbJbwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZH
eqSllhIb7hsi7b-ht4sFNlJuMLTifKSlnvzrRAH7ByUOyEsXHw_7F_L1UlIUNkmogSPLTVU5L-ZHUygNcppcSLqlkF3TUlJorIQFTj8Cx-ryz6xQbPxoVhuQ
atB1XMT_WjvugzvyZlIOL8_NevT7wZtHk-K9n1Pwyp-H7rwlbgwSDIR5ofKpwDKjnvQdDyoGc7vYMAcNas7nmSe5nvQ9tdpfh1KNdj_wnomc0_X-ljbBaHnN
vOeBExJCDuzQzgPillFL_LU-l53JUySH7Fs-Bwd7xuBUygzmiYOpxxtEMuuj-Nv3enTSsy9vtNZNfv3LNwhSODHjMK_s3xUzIp5st43YQicmT8xSxB15hpQS
V35xUshfpFrslRvibSbNfjxayBt99X9jrvklGoFtdNfslj6nxrfXvnkr4zv8UZdsuOl-vuiBrOHl1xo1xckz2L_qzRgf65lmHS--y5LE-BR1KvsVBtiyisvg
_5tdASVNV80f-jHF9nlUNNnTvxctUkK_PYl7lrLUJb7r5LxmUlKXZSxppRivdh8d3weoZgIhSIEUSipgEcO9pQeUa-f5F4UNkU43cxZTS9XIZTDr-qwiF3TU
47gngFFQ5PvNgnwdxAR3awBstl7uDJj-1wsPYgoJd5K2nflAwZvKhlzpsW6iwaFaQiqxLaL4rWFBY7U2q-Vsu4060000O92_zJs-wWq00000000000000000
00000000000008
}

