sprite $spectrum_monitor [96x96/16z] {
xTO5OiCm38LXWMtvtV_0ep23dL7rRUNs3wb05pddd7FEEUVOK2RH7W4ibZ1asc4GAXCGQHCZKYdBj4cXL2hXB_IzBwadxNHfRtvRRlH3h-iFcjioyECxvNrU
30SF5dTSxuV5_Ek0P_Elr_kq7ExjzV_6_IzXlr_kx_PL-ojNvfDFpgS1iJt6i0Vc4rqs0_c1-Kn0Cpm1I4_iVzZEZvJYlWgC6pcBrEuRfgnkFo15vDW0Oe9M
dS-4sVv7gZYVb_gRduxCN_yhpsZwrYMJxVVBlxTUiEzzWZtRZp2Lg_Xydo9kaFDzOWrNwVxwbolkQrWZbVgSiSxgz0r1U4aIOes-86ukU39vAkE_W5ZweowE
-uoPp6VxbjPbJ2TxYavIRAE_pZddt3i
}

