sprite $spectrum_monitor [93x93/16z] {
xTS5akmm34LHoI3fxN_17p911IffUrYdgF5Ms3PzdX122264499QYq8NCY3rTGQXSsPCBGJfOiCpDM5KEbF0rCRaQyOZpZ8hDCWB__xnbgVP-1al_FlVVa8Z
NcUP1YbFqjlxnUDugPD4BjOGRw8DyGPVESuqulxnYd40LXW_VYhwIz4z5G7KuNC0vJJkM-Ddd2R7JqKRcmmWzJui2J9k5YfrZZDFpOJCVUE2Vso0VvGxnWjK
O39Gg41l3dFaXpd_mR3Xj3ui9EWuG8jju_KgxZVKRwadHcJZLl15_B4nllOruX7FIEyNPsZNkFzCItxeTfoAuQby4VSuFSCNMzwkBSvLRKzoZtW2JFSCjKFS
BD4H1Q_YBYPeMt4dvEr8jABGkt4-b51eKMr3-6RyLA5czLIYLuGGGlWB
}

