sprite $spectrum_monitor [93x93/16z] {
xC610000082W_QaNgG800000000000000000000000000000000000000000000000000000000000000000000000000000WDcx3-t4TXYCmlhHifRy_Wyy
tTDd3WR79UnzUqlxq14Gd3ir8hd7VoDtsPPvPBsCCZO4zBlfADssIbrpHo46Z_5RX4SE7doZyU8VKUvtyLJ-BEVsdyZZPpvRNzHMXemwxft7HjVDTAE-JUFR
Z5xAxejobuTztez7oas-QF70PPDA_LRPurPKZ1wvqM-nWLFM4Qb-IplSXi8UYZikleEU6prqRw_iiFQiB_8DldBYmhdqTeyUUiK8FVIuSgB7xA57wAs8lKVC
7dheeOSUUu-OlHPwwA57x3tqc3tqq4EFs7leCNleeOUUUhDjOk-fH6Vbok_clMda6xkzqEn5VsKSNil-bRm_lOoUHslOyFa3QUGRkw67tW5x3xsZzrxPU-yP
Us_iVKutxdCkq2EUvqIFsKCFFVI8lJSkPe_GGmyzzDXxp1wXXnvwwB7tc3r23ptqq0iZPczPw15wwB7tq6Fsq2Fqq6FleSVieUUTZJzCFVIDlPIUbs57Y5hE
APHPUwzmydcC7cTdENs9dc-YXzvjyEonztputhizUblWv7EdNobce_aUVMESV9R6txB7FaAxzNJyupqwUU_HwymUAGxMezA-SYVgKMHREGVkFV9INCRiqG8z
Ge_Es7l4x15ww15xZvWzz0WzOkyHiuSUoQD-pcLNAR9-AhI97ddMRwNRVrEfhU8xx3rImxl-GaNzKMhzx97NN_9Bl5RigwU-pd_rKIjrwTmgc-gfT6SNoJkx
3NrbzlNIQ_db5RQLBtEEGQlFCLmFLEjQh-NlvmoH3Jz3P3FE4CNTUbutqUFq9NheRRdtLBXo_faVilVi0JsTyJCZhYSgxx_NeZtrJAKpsUZZbnhvncu37Z5O
N3ZFrwFoTvBhCKrV_dYFb7UJ-7xFb57-1U-QBxI37gaqkqiHpmlc-NhKI7JtblG3NzU2dg_GAqReeOSUUu-zn-oH7jVpXNgaalLJHMfwhgjAqvFdrp-kqiDk
HE7Jznvvrb6L4sSFl5QUg0TUApHFZvHrQEdpzXwLEhZKWRF7wBLYkXu7JzBZI-qluxByvLyjKLkQf4VH2FJqCsNUz7pItgCsG6vFwwczhPWqUzImx4czd_z6
pjL3BqPyXwWDNseVFNdfocLNwTQLXhonbZhq-cRF9kZ5c__V4zt-crQ_4lvalM9TlSVpUoVhSG9iqDvReOUUdxptJjRZoldoFtL0hwEdNhxYKt_YXvx0EtBl
qVlSU-YrYGhT-ysbt6Rsq6icRbSrwB1jzD0pHMRAxiapqsqZFVJwO--Xn-oXXnvwwB7tq6Fsq4CFFVJOUymUeRScz8YzXnwpXnvwwA77taEFsKCFFVJGO--X
n-oXHrmvfuPUrg_PWQ4NzMkouqBFuk35XvxNYpU-S-ZbkSE7dg8DdzjfeMTUpxrsecVrO3xqFEkn5q_qB6ehupG_z9JrfwB8pWazywolMEXeFVWEreFF3zQ3
hvokrz8B-gMVhzTIlfoUpj6xJYKo6RtZz5gIkyThvBApzGWzzD13Zz0ZzD133pr23ptqtAE-QU6EtbiaZpgbSA4tDfMiqyeYz0QcEhTqz8PLwkooe3Ueo3g_
47eZYhgaG6z0NdyktxQEtOTUvmjcqbrlsYyFA5FeFLjq3CFWLpS6UiCUAuHiIehcbqBlkRBXbGNZxilrTBIUwhTYnQfDFQ6N_5W7xzvvwxzcpTu7texYw6TP
OitzN3rpuSsYOUSBoj7tE7tDZQOyzm1rtAFFCzTUhj7pfhV9aOwme_KMtLagUporbx9PeMUZyTpcXPvo0ppqmXxBuqGyPgzL1fwEFrxF9_UqdiaZdoxSx6Yz
fHLx9ZsTJGazGWyzdkDeCNk4tccXH_AoDBTNxsDxS2m00000CCZVUlSSgWC0000000000000000000000000000000000000008
}

