sprite $Stadium [96x96/16z] {
xC610000082W_QaNgG8006x7JDGZnM4WZAohwlrVUBz6do1cQOPXUiz9vOxDRxae77N-KvAX5f69JPaHOJha5yd38i4h8SF6GpGs298CDrCDXggPWqZi4y9-
QYkwiqFNya1THvosVarwEGUYrz2RyEoQHc6ARnCVj1xGtkkT9IHGzDflC9Qkzy3N6Y17-SbLSBaoFQiA8vR2CPTUgFaJLiW2AY6rytYxGf247QugJ33Lt3sP
xcv6glI4LR5M8WuIVkuxoBQZjwzaHE9zEBFvN-uKYPF8EWdiTiUYFeE1p0JNp_D0-92kICWagMTusNSxNQr3ZFZg_o1agFcUuqQ-9Wxmk82IsR7Jm9RGpg7E
_AqGq2kT7S_L0i7H8Z2hRdH9FkLca5_vjlEBaqGjKS4IC0_bIrt-Kgg0FWLKjWbsykjrusB9xTvg1tXFLyVV-XTJeUjyaM28o9-s9OMJjRwKCgxXdQuW2QBz
Ra2TpZm8o0oFmtGbGHOiPhw0n7ZnjeqFRUw5WB0Hp3tN87F9YHy4wfRs8q02UwdXfZg6I6cCeURJamULjIfTQGGclf74QCF54ls0wbWk9UgTEEnsTG1RJjBw
JcrfbkMkHZ_hAHlFp-eNlpp8hzV0kiAee-p01qYJgFWl3pLMgxByd_afcFv0F9MYRCg3_wZyGvTVasQTyacR_Nbj3u_TQGxg3fpoUtS8VLfwqy_ufH6LCny_
6PuLZkZBG3lutnBBUmzNepKg_FXgBOxrdpTOG7QZUTgM5daszPhVaYwh0SXTc4RI9_RS84tdwr6obeZtHsTOx-q1V_92pTpZ9NSp7HFtAV-vPhxznNpzRVdV
_ikZ5wBWkCaFljIlUbTb0Y0-mq--qxZWpwFZOd8m-do8bflg9L_9Otz-mRzqe7N9Kz8_o0yU1uFq3_7FOKccV8GlISRfeh0Fy1qJVcvUe8_urv2MH3U83_aZ
m2x-_GfCaucVj_ZYrPp9MthFcjiDVylNhyr6NMOtk-n-VVrZlWph-VTxlc69Rcv0d3KB0eR7FitasN_WMW2G9G3W9cJeRVRz1gjxHra-8Hdh2MhkRcQgGtx4
_TQtllK7
}

