sprite $Stadium [446x446/16z] {
xC610000082W_QaNgG8000000000000000000000000000000000000000000000000000000000000000000000000000000000OFRCH4bn60QYgsv9rVx_
3zu3Yd0JXV669EJDr34dECzgo_OQiGFWG4G--GWEm0xy-W0x842FV-X8cuQEPFp3GU3_cjmnWxk7JhHUw4IwExkMvAuCf4Tacmz51Fa3Zpk6WpH9xKD81urJ
GdN7Z1uTih5dhePpj13tb6H4jgMY23wGk6CufcHRF5A40xkoixXwJ2ucJDDf-mANRRqedB0lhRXKMp_7ZkQxp7NQ2EX8k7ly-uITmL3LUVdTqw-w3dJRMj2-
GHmZVwgh3VYhrnfU9vx_3jj0vWzjvhQtXiRtmp8pWoGCG1l8ZlRCO039o4orjr06iKLr24bl55gwy_f2m3hQymjxDzSMT4_zuuqKtLfSwfqpgYThYVhPoqjx
Zp3I8wSwL3fi6-gcn-L87vvpsHimi4ra0usCCLHKftRz84lsPDtivSX8hiHK1UPw1O9P7cO4lGsmQg_DPWzjmC49MHeEMsNLLPS8mgxRlvZBdgdwchTpoy1g
1wrqMvUwb2h1SddlWlgJx6Ul3MJTtjLjVqeLWRGDLPqoYATreDUlm7xsolKUxOHmF-2AmbY1G7YM3oKws6C7UwMrLYyx9GDzF4OLN7fY5lfe6vtULhNdyzjB
Utvygz7XqnPRTXfDVzJ2YNFOgrTnlRqnQhG0boYmiDe9XSQWO0_gPSzBzgOrn2liGQaHTmLxh3QTzb5xFZQp2iXj7P4frGS-tLxsiYUhvWAgWr2-CXbOXhjN
aPaEBzWhIQbtf_tjvVJuRsxm5mAr07_st9taiEiTiPMxyddigMwl_ekNMMpseWzLOg5r9mMdFY9L9tZCRG_LlQXTsBlO0gkGdmkgkykJbAXU7iG7xMNTtlHO
C8QMbfz_s3iFDGUL6mfRPVGfx__0APjbcs3yus7SBafkTuE3pgZBSfCnPUiemB543FD1w3Nies3F0WOoiidzzMuJkx3jv4h0I-VesJtGumv3wro2UkQ8_p3_
m4jNn2OyPipHK_lzlo_quiz_G6aDpWhyw5v-Kv6mUuBNSaSUH9Z1LgnJvjUxvuRyvF9LQOq_BbyoPZQBHZwOFYr011tGoKuZuhCztLjCg9xFQD7Cp4H4UfOa
PTYGVR6DzBjW9vwhNsw0TpWZog_qYoqTwlTfC6dD5u8jxXxsrS4TlB_teCaLlxubA47fPvzwoyVqONwLsAi8Zm853BIBvqFKR_rh5Jj12X_TUA8UbGn07k12
2nSNcNlwILk_F9wODd1iFBEq0QUU-CesdJNvDV7ZGCJyDLfdmpTh_6pF7Pa57__A_QKCRGqtUxbMlWYtYk7UT0fWpub77guAsS9Pp5laA_TTwiPXHX_dAXap
u8iilnvNGsQzB15liup9TMzzqZU5grIDkb3ZEclaOm0-R2IbMMqzOFvwhPyR7rFLliNjGxw-8Un3shV4mNX-y2YFzCalrj9MFavdWzT-kK4yz1vsw6IFNBgT
TqMfvKCi2u-C1MjkIAQah9r9ALF1I_kZKa5xEFwL0oeMxXzeTMDl5JrGtVJLqvu3QWdj02d-eyP4yfHO3-eOTUGa1uU5kPc2c3z03sJjnCnsJaYZkhDrswJb
DF9iV-DYAw0uT1IvP8IRwHefsW1wE6idecRURcbYpwQ2YNE1T19v-gP3sO2kYxQy0RmGwUZo1FGWyupF095SjMuqfv2dbKpYgl6ajA68rNwcCgFD3q7FOEnv
5vrcc4h_VihsKv9jGdWiPCEHQqFGPJGtbTYDNXo2dj3efQXPHEuPFz0f6ioUagSVRh64R58uxi2i9ECYjPTXEdg-7xrVKLbwVQvRn6dTceNKWosMa6t5jA9r
JEDkA22H74QFTr3RLa6POjSrNFisooAUXnvzUkNZraf367HhysRvKJGNFMxSY38YpURIiraMiKEvCmfusxwBBZEHa44cW19PPVeuUWbDRjtCRaL2DyAopunn
87TwpmMfBfzQ8yDqb1zeH6t6qGjuTem69DArbVlPipE0tGb_KjgL-nZGiHDOKZSJFTuFAp6A7c-8gn-aHwcUzqEON7oySj97qUDwBenWTVyi9G6cHWoWbq29
4zgMW0uuUdO8UaptTlzmCpJ59K0QVAHIGWdVEHgO1ofsWD59NiRH0sp0LVIFwmJ68XfoiVrczD2d61Yq1khXWNdENiRH6tXGo85Twgnmxudc0JwVT3u4DJv7
cEoiXzUy3teS5kU_kzwgVk-p2GYHs7Y3NlfkxB8PRUFRtt2aEO0UW0Kr2wAh4_NSFRvCkDF0yr0SkmoJpjCvZ9vCG0zH8c_SOwspgTS-BiVZqzx13WJMUPcu
n5xqSXozr57qhYP7jXcqwPMJJp1Y_1F44p0cw4m4H3KTFK7ejQ4QUFNa1PoIY1YW_ubh7TA470q8FRiDFVcKR_Jabt2bulsrHjmAIM9-yfjrQ_sw1d11mUU1
V0m0-KDQH8iWknIM5_vwv4Jm_2t-PFAmLDZsryPePi_u83mTQ6ncTqjCpVBmakZ_r_6g6PfznqD4zKMazLc7qTk0H2D141FLmtEc4X7vkJDuQjDbvh8-69p3
E9Aj2MRmJKPFFFky94YPgOqdOcOUZsbLoLyyd8nMaFiSUQLxIAQWfsqDiOQkqNTgQ0OeYRsVfA8Z7RMUYCMgoJT7zphQdscTshBzOtVYcLTUkgl8RQoYVw9V
5janFcUWrzQU5n2MOKwQWE7SiuKNBmfmPVlbTnQvwRlhuJQdH6xDHfAzcOyw5dz2Ezz4oVmnsLw0wrZeQSE6IDs57YPpYKwKe27cBn2ZsiXdfjBcAkZOi-9L
RU2NFkxlrMFAikTY6g3EyfC0Kxw216Z6AIqV7V_BV_Di3AVtf8ANJJQS6IT9C5LhcJDi_1Qn_Bb5jE-_N_uyqVz80pVJopDTj4-2eaUEAIjV4RhzR15_VGov
_9Bc_nEJJu6NjeX_IEGYqz3pZkTHx8aC6q_mjUsErtJfbULEymQM3dNxdnmzSTJClBKMGp3c-kxWgajzzHjFhbkYHwpQNKv7BN79PMkmo6MMr5c4UVFkO04P
7z0ZE82U9eY6qKvC4MzxRyRFIMyFaH_BW_TReoexSkNIyZxevVMoN5rPi7H3qD-UPlsrcdzGwcuIhGU-0wQRY9vTDqcyitmMRSDyohtpKXPUqkvB9T5IY-de
yL3G0brcSdrp1mVRuq5qFkerCrq3vM0aPgCNYbvkdtmPksA7bnSICMkCKtWxiyHSz5Bm41cbOPGeRPYl8ZnOHEUgnqpqKcdrBZ8mbn5jhosY8C1Erxh7FFGI
BOZayn7ryZQYe6-8JD-Kd8TUW0LOVCVwkmbfWCvqm5yJqAEhQC3UuClR2jZ0dc52mHj7ZyzV4iIMRozorIbCLm3UyUXb2DjDL2MSAzqxM3BxTwzxJe-rX6pD
aWDDc6ylVBnUXWg8uG-WXnCCbWCdtHjBtuu9bv_KTPySGpg8q2sIY2_VsumXxSywAyTGfGdIk_pOYtkAHbx3ptDYVYzpeo193BG-dwA-VGQcIPtx7KUYvssT
FRM1iNYdVFeHM_0LrKpr8z6pYw_4FBNjsOHxYhHCs35nC7gNYjG6TXb-0bMaj_gvLiCVZ5vfOW1kw2aig54Ngar03ypbpzxowLEGTzna3deN3H1-1NAAHsTz
ul7eWTK41BjJ-kEVmsgHqFXCwYY1r0aBtq_sR7APXbwFFVq4P1TsqOb0pa2lN_KRezl2JxSXz38RlMtRCn5-fuWdMBO-2xsgVjpcF4KTFFhJqEkVVXdCtpiD
pUedp4QlsaoSG4yHCP0ldOiU6Pe4IezEIwKyxjFHgnmEWfsdbAw0OcdEHeybZUlopbD4F3i3e2-N1w17zds5dm1AqJg0tLpqU4bIk9w42UB2zqMFPwmotUGa
JAftyz5ZzcTju5xah8M_wbP9cuOUip_h58n_JlrO9EXYw8d4NFIgMEJLNajvMn85kuS0PKv2ZvxIO12Dohl6KZnOzzxzqUCX1RRe-VqFkYgWF7akUZm30bXK
taNdCWSBjkQZnqK1W816tsXaH52sUJnwo-f7FY7uDUqJClgADtGy7hqou8gFRNGHUI7p170bw3jzA7eSG3nsHv-PIdNddBBapTxtHuyt7t91im7lBsBcUBN7
U91-FdfSnFREHWHpEUyve1CFFURDtXozd8WUxy2F71Y9UsT25LKpyuYuQROnK3gENfkB7ZUlMuvjMBFPb2gVewbldqmDBEYdH8_RCJamKtmXLNSm0vuEXxUl
mV0ZFwxGvHkW1sBmW_iN_iFUUIYtpGDX45Vdk_T_uL-qwOGJ_V9PpeKWh5jDfgOHwqMXsWsL3uW_VSW7Qlu6eWHOOcurU_cHAUf1HjG3ayJS57jqPw-Mmwbt
IO3aG3VLtl3CNirUne05pIKVnJpVNj9UfK8rB2FEJOIIv1PehnQYv5my5spS7UMwlViE3S2rn9a9ypZIxILVN64-tPkPYZmuLtPx2KJq-o1zMcWRcjncxVQU
W5ZuxklLggMvcQcmr4ZhzkwX6omtpBS7_awPkRcft62wCQu2OO7s2g0tM7_Z-7zSVo7qphWg7Eksrt14VNjDjzTqUssls-lsccwlwVRQNhVNxJNTNjkJXTjh
UxnoUssls-lsccvlHRgzfjjhUzrUjzTqUqstr_QwlMwlwVOQNRYznbwnlRRNxNLxJRVNzhgzRe_6idHxuB4QtTwBsklsccwlxO5MRazKb9bVrfxJkksHOVye
HNSJuRQtK7k4E80tZp0p5TeP5T07h6P2tLuDbdwgiQdAzk1tQ7m9tX7T7keRY1r8jrUPNWu-S3VFV-63E5AghzjZn1JGxHKWY3dmklQwlT0nZMvlVNjUOC-w
lKb4WJs9NyZ2xRKzdTmUDfQpLp3mLl6QKD3SzfoPHSqC3lnuUrhoNud92n_kVmI9Y4LOx8RNUNGpnrNiaPVOGrBm17ltaAYgg1gUmj__bD3OuSlO4vHKOuVu
BcGlXnym7b9lR_gmo-Ir06UcJrUnHwWPTV9atxAQlINQG_o6YZO_OTtUsSU5GDbv6TBjdG1vtNBbSUxSsUrPuOXpd3ftTdkAk_IgujDkxymRy-2IQphfihez
hXvjZIFSxPtt6hhwlv7ds0EzG7k4-XT7KHm1px77FxyzHXpHwctG1dHrU_dWuGBolExyMA1lfVOmNnwe_FY_ezJjLQD_o9FQ2plYtEsLGfR8Atrz4BZRAuGi
UMb6iRumwlOgPyranr9TdtEtLm9ff6NKrmUbRkzVlEJOwPJNnlxp_FJ7jqTsrllFnEDFb2VQMxyz4kJoQizzLKVtReyzaLSBwRq-SBTNCcbkE9svkTs0yMBs
yhShddK-F_iOnXw9lsNjMMQlleBpRo0xufud_BKzsjrDkVqeYE_tr_PO4VT0QS8X9V7NzlBrRiDb_hjQ8TJsFe74ui2q5-kHFl2dtFOUGEfHDsdLRputuDps
qkLk_aSpYJ_w_oXLsmjPsXw9HoIJvkay_Z-PKDlR8J5452yqzSlV4S2axTqWnSCnCXgJKSGZe4mlRO_eqz6Pw2x_uTfmvHfxkfuzLaV4X3cpQ4tUW9kyO7kq
gokOCwVjFtTWJ2zaZrWHZm5aN0qsn2V0L6WPUpI-3Kis43Ak22dYC-0kjCQwn-DxY7eo1iRZid3wAM9G9lh6-wxbulQ8s3m-1wxZsf0uyeiG_f91MiGUPyrj
-5MoozVi12Ipw4BsIDIHNx0pZLLW0o85daoZTEbrZuZL43c0ZBKWCO_8WPiABzSUYvhZQnUeFDRZU7SsdqTDQ15xz2OEyIKykLcup1IQ0nDceelQ8o8MiqWv
tgTVYVmCbEDkAioNMlUOHTMVkGmS9fF5eRivD0DmTn6PtXw9c3k0U0ONfl6Zu6HZdQ1qfZrbLZEFfq6oILcOP8UTxarLXM-Sz1wRvu6hhAukFoF5jy66tp0H
AHafsL2_0VoTEXEcyGgm680e0hQZdAEsWqZesJAxDuXO7BWfqtX5Y5ZCrpLdoapZnI4nnq8PueQ9ZEOuaQhx4ZEbT70FPb9Mkwf2c0aJZPmEqIyocUA6cyXp
rXfYLbLtdwNDtLI5UNoNXeWukMrLZR-V7Absbcn8HDGTZZUA6jjmkAk8d11QGtn3TCFyZMTSmj_HDtXZJA6X7JvYVo9yWDxvhpqu4000060OT7_gAmoWMW80
00000000000000000000S
}

