sprite $Stadium [446x446/16z] {
xC6n00000C2WV_x04wa200000000000000000000000000000000000000000000000000000000000000000000000000000020sRkN14Pn68gYOtd_2-wQ
zB_T5VEuAABkMq1iwK3uEUIF66ECCRNF6X2jDXdWgTaiIBd4b8qsr4r3pNX7uIHKJa7PSaJb55HEGTroG-a-6ogVJmbOG7Yz4l2cjjJwaPlqjXybOKQtRmAf
1ynzVBBQU_No8YQdWAevFQQK6akdtb30y_hcw5sexzLoQvpUMmMFwpdLM-rwVy-B_8ugwTBBntmZ870PDq0lA7uQNOp2w_4NXcFj1kdbpFiCirCl1-Jfr9lb
LoTH3-03wO9poNbw_ohscm4_cTfqlVpSz4lzFfWLehTcwQt5yF5s_C4bqgDd1lZXTXHAhjSvCy2Fm0jAZxx8wkDqRLSX7s-NeNIi0wEEZtKuzNuxjFPwBEZs
r-0NZ1xhLLSolQY1_NR7nTU017hzVi0oecbyTnIwA3vYq5AlV-_ZdXxKlAIFwf_sOrPWrk10gqCHF42lvWVGAnWlrwkN9T7Z-MuxaQwNoUNzuFdIvwvy_c_C
Zkc4MpEEjzPNw5r-nj2cj_dEfVZYn-R0-K6kjyXpgVmq0C7RZuc_0vNNkzFmODSZ-R9L3q0783rW_jdg2KPlDn6ez5oly-Rvv-CYVDUlJnjkA0RxNggNhnG9
z0xmeBiecyemlSixEd17ve0lqlka0q5f0_GkbhaP5kMxS6FscjmmlSkrLXrz7e0NBFsELp3rwoM2FnqLq3iOxSHjW1wyqksuupbUFkkbtiTFgWVegKVmRJwd
NM-zGk-WwpbUDEkLiF1wwrQzjNAzdEzWhE31ym2zu9e-v-lSzTQFl5nlNzvLlzlruWKQluxUKOTolKzahj6fTytlPhryVMT-kTwl5_GgQ5Qk5zW56_5KlLC_
M2-ru_Kg232Vr8_K0w_4stu_2-WTJHhKEvW5hbTq0fT0hvxHg-VrwZj2tzRWzSvgJ4ydAyWylQBr-3SlrFU6ngj2zR8Y3ua7CLuWhaqulVs0jsoYDIkHthvU
Icy_MgvNCxCfBFegO_GEvXyKC3xvGuW2z7RZ19jVlJ2dj_oJLz9cl_1CJxlK-wWf_8-T3qfuL_8dTYrwyJLFddLdg8dbFzS1wacMKV1e_Op0izA-rt32QlsA
uKdTathhK0yGcmBPzjxEcuxB0Dmim-2a8D7BhqTZk3c4UN60Nl2Of05jzlzPythK-wpMmDojjsWz_vBy7xctLbOlAeHdc_ytTgHUpfVJpGViqojm0rImyPnp
hGQtiOIutc7xGpe1swxMfSixqdQdJBby0Mx3NUhOJa3gtzq-yqZf17pc-HxsbxW2adhx3sNi1EJr2gEJRzshjzPpT0ekIe-tqs_ThxSUijDl4Nhh2Je1rsBq
riBjz5kStjBkeJ_mZTgwzqVjj8FqS3xjQg5w-VrKK_iiLe_tquxNMuNuUQ70wtdoIJsnuVLuF-rulTiU3sbN2zSxc9I0IPDuFNPPX7IyNhuaIRjQlNe-UW2Q
0ki9cDi5hS_qSZyNFwnlqlFHUz22VZq1AwY-GI-feAJx0Zr_FmkKY-X1WALSfruEE54GA93KW_q6859ryNfvfLC9-N9ulQZY-OP15IFrShz-ntpc8_Humgg1
Bm8SgJVkjSRy7FlryXIL6NFfryjJWyExyNfvf6lLowFSWnTh2ufilNfvbCFrw2Z7w_4PegRUFdFSrCiDUJVralIBgPUdGKqz8hrcwXdrr5DFFQEUKKyzzTGp
wgcdddf6FQEUUkgfPzGpwgcdddf6FVNKKy-ePzHJJptrZ7f6FVNKKy-efnxy6KOzevvwwgbdrCF7Lu-lOY2YUlNp4CEen-dbci67g4VY-QOhzUhbUkgffvvw
wgcdddhggLTtwvLwRRlUVBrdGGViUgE-EgCTKxtgryk_SqSypQntwkMPfzUo5QZNt_HgvbDl9L6lUzURnATUSNerG4yzbayzljtgpSTR1V2fb-BnV7n3v-ln
hIx4JpsuqJoVUdoRY-9JZyFZ-TJZMyppgLT0Xr4-zNWy_lFLgw2v89zwF1u_Y7hzVQtRnr6ligRcVEg1U3oVUY0UFrofH_QI7rEz2NYhDdbPGvliQdKDNEg1
TZnVgPTk_gr-wg7RFZ-7KYzeMpzVgGVQyNpg9GthzwjIBsbLlvzwpNRvnDGRy1lhVIRhzJUdtwy6wdNsPRxVVBtYy52_NKRfzJTZFk30DL3LQyVEkqRhpRVB
0Qk6w-MbJmUioNfvqVFzQg1UNkvCm7q6w955pWUiONfLWDralwe1UabTCmNFytLwUIs_c61zaLu59SnF1MdMksk-4ZuzG-M8zWoPdO1ygx3vICX7EGNNhnZf
D9HDmX3EAAUYQY82RXhAfcEJcQajP2xsF9jvpqxcZbcRNQX-QrUE2G008020zM_jr03OxcLe0G0000000000000000000001
}

