sprite $surveillance_camera [93x93/16z] {
xD450S0m0C2mC_WNV9o5SL897P8200000000000000000000000000000000WF6fGepZl1xduzZMkQw7X7N1jlftitSUoh74AX2bYu9Y_l-3NtutkCoEtRlo
Y9q-DrHsaX4qIND0rF4tDUNyHDJn2JdX0XLUn-Uas-O8Fng6E41PNay5O9iYKCS9jUq5Al8ufnAsEt9wLPbPdn_WVW6eG7wK243KCKv0oElz2Y_XsGKmjYVo
Uc5_uCq5kbC0AdwVKTfVT1TeRNY1AcOfjmy0qGIWOHiWSFpYWoROtm6AQBnUStwxPj0KSC8QWDnSmKkfkprWRmKekL3MCE3y5BE4dG6lFGCOQRs2VG7F6b12
akarmAFsgC6BF0aukm1qhmoCv4BPTuZSgOGafGxx5eXz5BmkphGJzisWoVJAZG1T2SbXFuUyNi8QDbNmma_b0dz-jVO25SWFIft5yyecK7NWnjDpOzS5C5Bg
HdDUGe9jW99aX0DSfU1545vlmm1KxIpMC431Aqdcza8ybpSH2dI5FPxp9b1RXzfPUAvgufLIJrj1Z720Chq-WAaDpa_jB2JO88Ec_FG01QXsbY7d9q3afpTH
y09KEmiFNja4AaZJuu77iZqYQcVXsQO9LEEMFGDAI1gt9DYc2LJjB0f0bIJRe8IaSSk92bxjBEi1d6e25OJNMyA04eHChmLuvloKdtQx66110ADnoxa1ZCOj
9ojuZLlkh-1rSSBs0VwjCKxPNiAs0kSb915NoGM-2VHN2KAW6jFREO0f1ynC86gFmwCsWGf4x1mB0AERG8LVfk25CZ1YU0b9UDRSFGO2li4OfvWunYdK12fm
sHYkq1Ydm6m5AEuTmC26eYPGH6PW_W56rlrAIAYnGPfwO53BcwVL1Bg-7I9LWXZSI5Os3JM1-l6BMvIGyAwlBjWmDCQ9RkvaFdq92HhOKmb90tkhQHHy1ZGr
90MlcEMoHMWEcPuK_DJzq_DBI06jrXa0yHpynFSHR-W00UsV7a0VW4gfJu0OuvpzFg82KCa5ZN5AgQyFG37lVSHXQ8oJa0igGKWkJ6W2TMZ_z0IYLV2I2oeX
NISND8OBlHGb1N-DND0OPsL0Sa5Zd8kVKnUOq0JQFwSkYCVa91Uq2NJ0SpNZnpZtkZZTUAJW9HVK0yDtlyC8fE3tbmi2X8ANND0U4RNWhdzCRdJtkm9GXoRs
j4XhVGkkpg-u07I-wKd1AsQHWdygPX78InLygfrbrHZdZqfrcuPAIAZdOnQ1kCO1eXQxFGMWEht1cq0JWwCM1J05MqQk5kkwGED7wkfkIr09oMqLM6xYAY6L
BQEMZsbh31Us2b-Uu9623ri5ShL0KG2QInkfLvoVy9yuFSII4h70ZvHla7hhR5BnhJy-1Q3pnf4Ha_S4QHD0q-GzOrEp5eSXkXv54y_E5sZASF2ARrpxLfRE
RuDUFJqMEM2qHvksX-xiqwPVxUm3VF9J4reSrftVaDUkjGcWSO2QRIT6UxIdQmDcDGlXsG16IJ9D6Ie_VOc2brBNbA6IP9TC6QgcZlrVApS29Sbs2K1LGchQ
cmjJfWpjlO1_18_PoFGKWCOdBkBHdyputvyyVe59cxQ1Txp-UC8kGJNuE5u0R4z0F1OvL6_p9BP-BB9Ly3Az0SEiUDSI4d83qzDRMVnK5SlbMaybf9n-R_8A
Vdu0W-DfqhKdw7BJg_0Fv4FgFoUNuNYFnoA1oQQNzc_mwpypV8cf4cc-0yI2olXSWLiPwc6VB73BeShu484xF0Epe1zili2jS9dUW2XxW8BNshQszNjq2Sc7
HSjhUZc6bf2GuzJE0e4xjGRlTSEbDOt0nRWz8jca--uoTJ6xX5HDj7mNqnizHXrTkiXnrtLgy2bDe5YGBXebSEULa7hJkqS0q_HoZAl18y_IHNXhhnUpzeZq
TqZRyUzut_mqc3qKHyPsxllHPV6k-UcpKy1cOvozwTrcwL1-Ryntm_FhdqycegtPIfq_l_JjTgpqwTh4RLUJRBa9j77Vm1kFJA6H2-mKKk1wzvqBekMv-ti7
AFWcsqUStzW6h5bZdBtx9cQ-voV99ennyalz-bysl-rp7y0U9IJK5zmtF9e9vw6ScXw_2Aq2s-rO0QBUwFY-uVKe1R_V8c94litb-Q9VFtZxbiT6xhi_lnX-
UebHOvozKkTclc4J8OhFZ8BVRn6nPyqtldfLeOTe0bqa5wXqNzb4yhM50X0AVa4tAZ7fPnD14SLdCW1rN5HUxfb-UjaKUWPj0kMpVHX-UWOcJEGLl6EfN03j
BsqcKOJEtge4qUId-UTgvizTviBpytL9Cjvefq8Nd_aKDh2c6_MMCzA8N3GhX23sYD2cjwGmVUTrPOYrZUb8kbLp_cQGzSNdV3HOWDTwxKe7PxJpeLjj-Isr
pvzVi9e4ESpq-49F-fAndkSLF8guagVB1RxJWNTBkSAr1drP4EcroG5eEPwB21SeUFJxDV76faVE2k6PJI8BIaZnw4e6rq8-7w0FO5ZJMz2OZYA6BPkYqaJu
GWyVro7RFIBylTnziU-jrAbXMNQsuFmZqvradKjDp9GBwvzye-CwlWcqRsVfhsJ7RHS9zc4YAwdEFp8xRjcRDAWMyZVEm6JYoMOX46ESdUcTjxKjI9AD3a2F
18ZHGBw4rD_B_hrqtpIljxZGmyTrV1Cekf38eusMETERprbIWsyMWZVs5s37BT6cQwaUjFdKcIWcuZf-ZBCFYSwZvKR7tCFs-ZkfbrHqRk08WBoN-tGjuVMc
K-U5dZuYN57SE1-tXEVncBJRsLwSfB39kAvNy1bWA-DDj4mhzVcsTrxewKsFh-wpgIv4Vtw9-zdUrmezsLHW-2PUOgzXum1vkJ3VzhxK1Ch7TK2UvhlWnoyA
RBqopUvdU-Up9cZ565_T__MHFygvOEjT1RkbxPqNUaZJE__8uVxtGHJ8Uad1xcXxpQFj7NXDShohmmPNxwg4sKrjxxpGmyTrvn-Pjo14PXsLT1_tVDjhtgnT
4DUr7vbNR03S0ViNiht6fpIsGJh0dWgZaUsTYofVyPpuBmB68jix5rM1rxINBZiysLwlimCBg_lfnY7RwqKnqLz4xA4e-eFBzdg0M3IU3aIkslufs_i5416n
92e7_ByV-v_jt4S103080q3_hf4197S2EbyjmztfAWJWymu0m1G0000000000000000000000000000006uF003t1m000000000000000000000000000000
000000000BSn
}

