sprite $surveillance_camera [446x446/16z] {
xC4n0G0030AWU-iVM5Du0Jy5000000000000000000000000000000000DU4lRj8Soi8mY2uxliVsCniqJyvYZ9i1-BBqcjX4UxRoHd22_kn2_l1omB2I_F1
2mF2omB2A_FHI_l1YmAQduMgVlIw9mXwuICWlT-pDloa5yhF_4WI1fHUs4zwQJ_fTG5TSDRzfDVtezS7XDVdezU-1mRUZnFmerTRe8uBVJ_fzG7TITRtarxV
JtfzGEdr3u0kEFk0qkllJtfxFtZyw2q07HVmIQzv0Gfl_n0IFGkKtc21mXCWlO4VF7xEUfCRG8ykwC_YtFHdSGfGUbC_wV6JtXxG1IS_wUqlGEbv20dUe3zw
0E4jBc3eyNDSsFj9pmsWzYu_G9WVVYdwe_TeG7h93qCoF_mkz6S4QFZnCm0DFduPG2D0ViO2DVoC1Nhqr_x9dm3GuqBsfuTazKTFW9CVZXyz2tJmSyq1wV6Z
Pt_2kqoGdlq9pmAbTo4WF7xq-5t-ytWCNdfTG7eMA3n-5-hnW-S2PgW7a9x-uF6xxAHEi9sU0EbPeF04UBaUFteMA3n-Xzxa024z_S6x551w_7fw5gXh5W72
c_GdFNxmRYK8Ju13FO3q-Etm-D5p0pYyYnCWFGU87PxzIG_WJezVLOzVdmzWMO-Vqpg-XpowPmRnyRlX3E8B-6NvOfsRmUhaTyCPw06C7SREm8zUvJu2UCVx
9D0R-S73Hs_m22EyurM6qflwISy2bTuaGEdfJtfxG7fEWF06_T7Z1szq0KgF7xpz0gKdG7hx0mGy-vEU_Nd-Tox0uxVNUtahoG9Tu0bGUlex0ps0qXkT0AMd
F-dnc-2v08N7BundWVxqpP-F_tsObsqdm3A3_EYL0U6r0BrnstajV8TU5j2jtfyjIthdAVMwVkV7UJQysX72ktxzvgTz9GyxFnjUjh-txDrRiiCW38FXPsN_
2-uEQlWpch4LytvCyNUK4dgJ4ltuBZlb7LUVq1lT4lqTduZUO3yL8ruFz6LF-thX3GsWZaOkdc1tsgtaa-_uV_FFtMuXNtl7VxTDETSh7snizBXVhuN4v8_h
yVprF-rJx9w5-xN1YmWWZnxrQx2G63yUFUwd1dZ0Borw7B3TGWBvm1fQvkzeuW0-e8S1nvpsHUjnm7vFtqbyuF5tpD_LX8bwclSn2BwC43wmWeO115FbwUaP
weSc2jBpF_z9xMvQK_H6Nq35fqZIyrz0c-abR3gdvuzN3xXVd-x73I8EouRxALoFjzbMMFqkdEl7As_q-D3O_1rKv7gRFyaAM5VaU1j0znlJSSM3FzdyoSjN
b-JHs_pfQ3XlTxZU1b3UJuRepm1uwsVu7XWQxLmztXMCnolpBH77sm3A_CaGrGFefVkH2g2oRqka23tU7Qh7yyUtH0BHInS4UEPed_i5uu6K4Bt7aEp3alLK
Um4L_nuO7ct-0uaRmFFeySfyIoG1l7G_6ZtkLndyhwZLkxiiyje0hwe8y8BrwWQwe_toPd3rz4xlCKHxyMvQ8Q27ytUxSLgz-bG3u34_TjkYrJlhCkoH8Ta0
BrklxWdlqKbKBWq0Nh1UxNUYnzFovbHjzVoRSbsC_Q46e0TseXO_NF7vf9xv3PlEQAVQSRt7WETBTg8TrwkxtFOx-bUFlokM-_tQkuC3W60W08BzT-tf2nP9
Pagu1G3r7gpN_m6eZATU_mMfj9rw_L5v64-z_a79i9rwkt2yZxTJ3_LCTz1wv8DLhv-jUdPAwgc7UW7rK0_rr5DFFTHJJptrr5CFzTHJJptKGxs0UgZNKG_r
K4yzzTH3FVNwF_EYddevzTH3FVMUY8TwZ1mFyTGx6m_r6BaTshdEYNgefnxgeHxggOTwg8Twwg4Uwbsb7kgXddgeXtgefnxgeHvZn-E1TW00000000000000
000000000000000000000000000R
}

