sprite $surveillance_camera [93x93/16z] {
xPTR5kKg20L1LAZv3_ZUViPrclEXQVgT-ZReIYLib9_6myF3G-jTvGSn06QJ7u71c80tgISm4Hs0M_t1GpxH0w9BASvLq08OXMuR8OlcfMudutMpGhSAAg_e
28WAjuCfYIAt2atUOVxzRZikYIgtaGwUt9hS1PT4Sjlb7Yg9jsvL2YXqcnueT6iCsKIFtJf9LPdR1hBBSZlqe6MTkvrwqBAEQ7FBxM3AEIiGZ_xyEhUvPPMw
3KmIHMwLa5laGAmlljnEoKHDo7SmIRIecR0SE_zUpyUU-f2VzE8WM2ZK1e5UhEPN5VBA2reQ18Dmz_Z4taCARA_Kyybhq-qWzFpgiXa4SUfVZDWC-OwV3W9E
ttGRs9b_KM8p28nOQzfkWsXxGU3qjIPsVUAs4VADk37sv1QcGVOsyJJst8fSIDwKjKP1RqTknzEE0x_QtF7Oqs95Rj3MZkqwx1NBq8vRltzvquQda1_CAy82
FyyL--8si6y2iNTeIr2qEyL5B80GMMWFW94k9UV5HMocFzJcDDccw_lY5HZpxoh-57TBH5dnTuIKOCJ8g9IzymEUuWKqXlofF3myF3py3m
}

