sprite $tablet [446x446/16z] {
xC610000082W_QaNgG800000000000000000000000000000000000000000c5txC84aYA4eo0SXCVa7VDuRx9bLTpqs0L5ZDCqkA5KzAwegN5zBgfzTJIVW
tfMQPsDJOJVFtZfNq-sruvTUgyQlvpcXYHjlStKTNirpJXLuY-kxy9xVDA-UtUNNUDDLbPUlgllvkRhwiLb9rdobfkPQllpYq73V4FqZOEuy6-iSCKTVeTS_
u2M7VB7MVHjBvvnPSjjpitBGfTYNtNfrrZYvwjQhmnRelkdMgzEMiCazjzwSDr8ThLS7NgXrot5d-iJhT2vvTER8GMlp9MdEkMFhx3E_ZNhn9kOYpVErS_7o
UhUUkKmvDwmjTUXgdRvChtFKOBVf6Smb-dg3pO5kzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZbfFeolJchE_JERq9lSKtFpKVl_qJlPQ97Zvxt7Zqx
9ptVUtFGxt5AlNmmUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7
ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7
ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7
ZnuzUlJeqQD7ZnuzWnaoGszlwQyFJdfxRxxGMrZgdT_qKZmlzoH_suwUwD4JFT4JFNgY9tgYHq_qH8yUFNgY9tf9TK9lPTNFkwReBIpFnoRqDl-VSnyVlJC6
yq_uNZm6lQ57ZnuzUlJehOyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwEMa-ZAzPuxg3htpcz1RNDFRNEXjY1uz
UlJeMJhfrKiJqFEzDzjorkAKcXuzUlJeqQD7ZnuzUlJeqQENTwtKevVgULVNEZrwRzaxhznOO1W6YW11GlS_y2lfyUPtXKZMtC0OkZUeOELuxJq7kE2eqDgh
a9V9HlRMdl8xPXjxQuzv8dInj_QK3tInjvyj8HzXNS7csqErFLsmY5HL9Lnapowm1rrcBr5JoLLYpxVPuvYMyqpbM9GVU90zvYTnXRt4a1d36Sgve6hfaQLd
d8zIJGKk6dN2US2Qg20kQJerOvNwZEHWc5KvfRD-gfv230O-kgB-KsZugEA3OUMUgUoqhNWcHnvduq9zWHVguiWO3lChd5KSn72WOzDqa3p5U33efZ3Feio7
XpuEQKQISGFE2TKFQF10MSaobeXe1jKWWrKRE1QZ3w3p174BSFw09Vn-AEKZPjm3dRDGt0HMNcUW78CPvQo-bRUTdn5N0dahNYdhRyWg-tP_1k9oG6T7p1Tr
2oWx6s7nizej040r0IXHzxSzE10000004EHllS44rGC00000000000000000000000000008
}

