sprite $tablet [93x93/16z] {
xTX5WiGm34JHaacg-rzuzaCjDGJhhPCV1Xk78Y8YrkT3ezjJQMVEGbad6RuUSP9Xg6baT6GCqb7Z-VtfPA_kU2lio4B5ODGMhfXSfMj_cxXRsYZ7Qzg1ucvf
krnGnHLNN7755LTSSSKLDyRduZ1yC8xJnks3SQFhFlzON77lQVDWO__88-tMTul7UalS_xZCu_NuO6JZzQa_8pj-i63OwvEMMB_Vk-ttusaeiI1dPfsso0MK
wraBTIENZu6dM7lCS2eYyWK
}

