sprite $tv_outline [446x446/16z] {
xTo9Sgiu441HMjNLAlt_3q_g0Sw-J6BBs3u7pxuunNrg45cMGm8000000000000000000000000000000000000000000000000000000000Y2UjnMRv4h5g
xH0dAxDwxsFqJMLLPLNRF7ojjjfEI_Kd-mchQjSC6DN7DvwhhbhibcLztRXONxkMg-gRyRLgotMq6d_GQzDsiJjmgfEsgStujNwD1HWvpgplQfiobQUmLvrw
BMl_aFfkd575CbdqCLFVLPwqU669vSFNIs__MRpGygIVZ4bwMwPgVHnBVQOzgpV614TSVZdEYumRZaTUQMpsNgklhnVqLQtUdgPsZHkMoeXb5T7M8pUzrkDH
OzM_8pVRoNa-MrdZfLXcg1zlLkADLfi-xb1jMhpsrVcfyQpFoDVEkTfRhaVMff-CO-cxskqV-zbspJdZwTX5jocdwHkvgve-WVl-dfLlvrx4nHP3ZvbBBvOf
uYFrmXyxxJ8-C7MMjObBhos752s_F7uK99RTp7nzkR0uz-C1egPDinmxyIwm8fRBglE_4JdhlkK2Iu-OL2ykS84b-fmraPSOdDIS3Nk-tYwW7dd3zMZggQUU
UgXt8EgXddhggOTwg3U1UgYdddhgeHxggQUUUgXtAEgXddhggOTwg3U3UgYdddhgeHxggQUUUgYdddhggQSUwgcdddgeXtepg8Twwgcd7kgXddhggOTwwgcd
ddhgePvwwgc7UgWtWtgefvvwwg4Uwgcdddgefvvwwgcd7kgffvvwg8TwCwY7UkgffnxgePvwwgc7Ukgffvvwwg6UUkgfXtgeDuDwgAUUUkgX7kgffvvwgAUU
UkgffnxggQUUUgY7UZEeXthggQSUwg6UUkgfXthggQUUUkgXddhggOTwg3U3UgYdddhgeHxggQUUUgYdddhggQSUwgcdddgeXtepg8Twwgcd7kgXddhggOTw
wgcdddhgePvwwgc7UgWtbtge5rc_aw7UjRNnQnNgtM2yNQbtNJd-GhthgjkhfvvwhdjzEP1ym7fHu_TYEP2QNA-M8yZ-IzMM8wavYo8EDdZYjvOZYJvf8WoF
oYvu0UyNhbVd7vtKh8cMPx_i4sENqzwfv3lxhNFCsoBdSX3nePQPBTuvNhoSk0TjrzioHNkIws_rKl_8UDBVgnVM_zUJR764PmvjwlEflE3ooQhyTzIOh2ht
u_9RZMXpFslLnhEClxNANQ_j6CVKQpzoryvHD78yQxCV3lSVzMkRslJTk6LzLxjicv_sR3Nz4yRHnwj-dqozoXgFhjTs9hB5UwrVuybhz4_6IX_VeKup-5gF
pNES6pdpBlS6YRThVLnVVwbU6RjFjuKF6MyNDIQgaspFufNlFv4LBxLd-IRxV6sPBB9VPYLLxk835_aqP7maJowzO2kM-QBw7nhjsYPkuPF87opNFvUjjbn7
onhVUB-HtTp9bm34oVkmFsiNozL4PAs_xjxClMy7thHwytqwXElD4_Jy9DtyX__B11FgpJjXiV1jlSUZ7kgXddgeXtgefnxgeHwnox4xn5V14wtbUjId-kZx
QzVxyz_izQbiwz6Myx6ESeqoMprflrolmcLMzJwkhVVgcVd3X4GxHhUt4IlR5mc9Q5dZo7hL9vFKakjzt8BAV1rGkUhZXlJA9jiwBclSecw8_kb2ry_czqFq
SGF6_vgNlVvfp-9isadM_zjUzchnYEbQ_z7goYVRdZcUZalRtcN_YHFrauLP4LRTcuMMhHtYh4HxkG6r0blsR-xd3dS_4F7TVN7F1rbsNmpAGp-JYlXwKrfn
z_7gytAtCNsYLOrFt7k-keTRx_XiWFJbllLxkUH7g_vmY-zzkemxkdDkZrHlmggREqBZKQvxlKz8D_cxz-j1ljIhPzpV1hO_nfQXMjpT9qgUn7B_BlCW1G00
0000000000000000000000000000000000000000000000000E0_
}

