sprite $tv_outline [93x93/16z] {
xTX5WiH028LXU5Xn_mjFh9ratFdMdRziHTCFrrfhhJKnLHK1c9bUZfa14LKrPQfXv8qnYGXtDzEPg4nqPcRk4J4cUKFhzJDjtS3boomK6vYNDrK1D5Eeu2ax
XmOWCrt9141zSyX1XHpq4JnHnOC-WdMyupiwtl6ETxpZ7UzunplUSV4B--YuvvMtn0STu2jq99BB9QqO4hSHqHRkjb0L4PI3jjGNm2F39jjWdBNZGTSy4rHX
l_vzRB_NopObupJnwcITi-zsCa0x-FW_1Ku_V1D0GAzInpyUFZOEdTzth2xFjxw8AVZDOOjSZKAkXibRolFdCM-EzruGiYxlU6Lx_aPUl8jNrbzpMb7wVrfh
hRKd
}

