sprite $tv_outline [96x96/16z] {
xTXLbWCX54NHvpB_2JTanKDLkz-T_uF42kWT00000DYhAZFStKnLHOIPQGypYuYgchb7P5Mvq9fKhzMK6GSp4vbPGwyfBLKx4vtcSvpGNkSqx5ok7PTBRDr2
2zRnx4OSyGojROUoXJv6rxhFz36g_suVVVJHHnzzzD577ttqqKTV8Y_iu_lQL_8j_MYb7No5Td7NUeR53qqPz7ZSdi87CzD1XjLOsKuhqUM7JCJsgNt_73-7
hYvQy-tJl-aarNfQZldM_K4oRM2TdUEoLwgPBbOxQIRqTiV-lX_Lb-FDqPJPVNKFPAP2xy3grS-fKAQtqEoXqktuIRzv3QhcKJsalhw-dDhs8lNL_H1wAV5I
-Z40003W2G
}

