sprite $university [96x96/16z] {
xTQ7Qi1020RWMwW_tFk_RdTh21xDq4u_LgQOtwpoIwMKKaeffPG6jnA808mIfJ5u05HYz9VIJS0r9FhtQ1ZYFuIwgJhSXw2fQ5AUzbEjx3e40hgnAI1wOzm-
qTlRFMzB-xe2elSOWdsVU0-X0tHWE3xHkm-18TsZY_NBk1vECI3wTIl-5try23gqk7wg0C8xWB6i0D2P-dlpYR6ynUMieO-_p8dtPSmfc-Xrj17rAUjd_i7r
wo0J7ygVR4Fh2nOEzRz2-YwcQZgMJwicWTOV0VapjCm8kFyvll-Vdqzy_npRV-QV-LT0J80kpZdVb-UJxJ4syEO7LJw39zRo6jToJnfyn9t_XoDQ-ObIIkaH
}

