sprite $university [93x93/16z] {
xTRdWWCX20HWH50dsVT_tMlfmH_i7dkLxq_wH4TIw5zBAQMKKagfDA6zy01weLq880s3QGUdN05gVDtzt0WFQ7JTW3wzJP3dCXI3O-j-FjgekWUQ7Sf64QfP
PbpnYb7dzwD6JA1_HtwsMtiMaNNRAIgVg9iTynzKjrK7T5lTkdq9KHjkfhp8LmWWA-iEQz2Uqf0dgdVNpOFm5zzX79VbW9F3iXnXYRSLFb4edxs5TpvfR-6L
pphuZ5Qgju5vMswZ4taBlpjuSiXmfmmleZFT4wvJSlzxDUS9nrodCu6K6V64bwc6SWtdwCxrbuHdU8PdkBAnvjVVwjTm6Z3M_M-nsbq14gpItrMg0ssaS63Q
QElAKqhf5G
}

