sprite $university [93x93/16z] {
xDU72SKm38P1uI0Zxp_mwxqCe7173Pqa_ZySUm4000000000000000000000000000000000000000000000000000000000000000000000000000000000
m1ZH53chvXODCMgTLKOxRBLkveXUo5eFpTQJN3TDrrFoNcKq8tclQaGlalUg6iIFCTSV6Pr8NkLyVPhHXEJTnZAhO_nS5Af-ViyM92z_RsaqO3NppqSzidCl
kH73C0n00GSUfFU_SBVrmltB48F7PV-TYKMH4jtGDuCDmosVQkkRmUw0nP0VeR1NTdTRvGVpwxFrof8EA6_5pFBDKDwAaK9-XCBNUh2VRyOR-wh4HYa_bBVY
Qjkxc2ZyGbeq1yfRCQA6HYXlHSJGY51OSTutWwBsVznPrLFLNF5g81qCqRVS5I8TKDuSDVrgFL3UFGkqOY-Wl1P38zYlEOIHdwgvT8lnvCSRUxPqG7ahnbmN
U3U0WeFIuOc0Wkb0ZdImz5VlTqD1Tn_mm-7hB4ACT90EMj2D_E3y9kQOT-6we77GtXlhAnsWu524a1-XaBynmHiBs3Sp3Yh8alqQS3WsGZhalv2R2I9aTF2J
xNcYWQ3y20L9ewSz_MEAsTRrxQH3Y52uMzomM_3s4GgvOobLivxy2jfUGW7vnGPYAJ-KLnpHfVAIIZaqRHAk7rzF9n0RNC-bWnw_JOhoMWwDf8CyNT91fCFv
ddm6r0SR4tj1vG_bZLcshiSLDOQvNi5ldrPkVqCFRomtmojJEPX2zV0oI1fjh7i5Npf8iyLtAiXfehmWNztI7z-CDwQ0S9jiJApnW2cPZV98X_F9W3bqpmAn
_YTbvfzyCvV5uNBU6EdW7_pDIYFAuvknT4c7itK5DtWgzMNwQPfeldt4V3OMt-MTlVlQZHs4mZ2AGA1jPTx_TK-V55y1al5miZxvzazRcTwY_WSN1XVsU6_5
RBpT-Th5UE_DpgwjEEbrAFngTdPfZLw7mf3UGhx8gITwZ-dP-jEUoxt73derzOLlMlsoegNTAwsdUF-5UukpGklhj7gBDj3JfNLLqZUf3bzGbBUJG-hhh5VI
G4-z97el73rwzEZHeqUF7ZrwzEZH4prwzEZHeqUF7ZrwzEZHeqUF7ZrweaUF7ZrwzEZHeqUF7ZrwzEZHeqTFzEZHeqUF7ZrwzEYLLRMzzCgwSfegrrZNiPTU
BApLARjZOHlfhIzA6cpMZjxzV7aQZzxzVDDuzEv_eyzwJ4Rl_lUApCUhwT6BYPDUB6illLZM-1kKlq-Yv9HJllf8ETMzz4R_BFD77JrNoZ4mS4_PeZSNZa6z
AFVhqQkpUfaUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUlQkYHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhq
wD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHu_UKJRMezVsq_Df6kcfTxHohnwzN8TFIkru5j7M5CzlsBzud6fzdMVH1Zh-rLOLCVmHRZcEr-znRdgtHP47piSsv9kT
xL5DtUMWjzz9xxso7z_iR8zAIhloqQjfhDpsufkTxL2yuutuHSGcV9Ex7UJYtMwqNEhFzklQY84W1W2W_lZwRzYHAJRgPxS4iNwBMkAi00000000IYBnX39M
8ZqUiNOgFUxeEvaIDuoTowgHbkpj6ccPdAl4IRXQ62kH6i_mhByF0000000000000000000000000000001m0G
}

