sprite $video_game_console [446x446/16z] {
xDstcjmm38NHGXNu_k_hRDCvAO2NS_xMtaLnFknGapIMI98aIP8aIP8aIP8aIP8aIP8aIP8aIP8aIP8arOEDXiWXPDVW1uyVkoO-UFZWzVF1w-TJuOFNfKSF
7xn-FNgnS-45pwONF9nUy7HwQUD5ZnuzUhj4J_JeqQD7ZvxeqQD7h-ZPlRRi7Znwz8eUFNhqTe-UwD6ZHq_q4g8dUYuPwD4JFNeniqMl8NgYH-_NlpVoq4Al
FfUdHwzczEZrHA-srADNzCv7p_BHeoTw3qTlY1uzUlJeqHCzUlJekTopUsj5RuH5h-ZHepUZTq_qHCy3NtqeKezUVIfFZrxDalNe5JrwHOyUlLfMJ_JeqQDN
r-WfGa_qwD6Z1u-UwDqSFT6ZHuzUNQMdJVJerTPwzEZHWqTFzEZHexTbz4IF7ZrwHS_kDKHl2poxHy_kqPkzY1wzaQP7R-oWvrD4OqJg-TAF-T_IzEZDwD4J
lSJeYPvlUQH7J_JeqQDt-pn5w8aUFNhquD4JFNhqw8aUFNhqxh_S4ptBbwBdWoYHUlJEtt-l3uzUVIbEZrxjeKUlwD7RBtgYHuyUFHVhTazsZvxTepU2yvTp
Y1wz6JrwzEY9thhH4prwzEZj7JtHeqUFdkZHeqUF7ZtHeqUF7ZrweaTlfEdH6rle-Tg14Qld2rl6YDEZDwD7R-leYHuzUlJeqHCzUlJeYHuyUlJeqHCzXvPy
FNhqw0rwTgyXUjbyz8gUtPFTesVtwBrUz4IF7ZrweaUF7htxNmeMFNgp-RkUrQDtvUyRKNfMRrOdndL7Rz2Z9tgDqHCzUlJeuQCN7pqLFNgEBVH4pw657Zrw
z4JloUY9dWi6UlJeqHCzXvOwPfMZHs_IpGBqw4syK3vwnq-hX9TdwHs_QltTetVykjNrw1s_gTRMetVyjbfPZruTlszbFNh7dxf3J_Je7LVeBSj7xsZHepSs
rxDwsNhqjZwsq3leqHEzVunUxQtdrDB2Hw-2zUYDDVNWvUlHEyztnyOFqQDNn--h03tlA8jyLncz-ZrUcfxtuivgSJrwumHUknwzSGAlNyz7B-l4OrwN7htP
2RisFNgp7-m2zEZDwWUxBZrwqNFfuOk97ZtVB6xtH6_vw8aUFNhqyD6ZDyBqLFJeERRGspXweaUF7ZryzE3He-U1ZvxeERJGeqUFtbxHKz6ZHu-Uw3cqqAE7
Zzx3qVCIaTqJFNhqwD6Z9thqwD6ZHuzUqQFNCvrU9G-dL_3mDKscLmrpJmp6rzPvFS73ruGdUFYwz0GFNnUUel44Zr-07Jzs_D2Dj-t1WG00002087_hGQw6
000000000000000000000000000000000000000W
}

