sprite $video_game_console [96x96/16z] {
xTW5ZiL030FGHiaeu_iVU7c_FwM2SKaQBzChPLrO3ipCp4nql4yF1TzGfutp1gI_Jm8sx0UmL052uFUDVQpuFknxxPjW_nFPttTW45_VoI7nNuV4ct6qXjDV
_4Jx-y_E4PZQ_Zu_2lejz_BTwFB8o0eea0y-H3wuf2VV1RvNlibygtmJ-7Q4pnsdAhXNF-Xh2iuvdroSik1ieQ-e7tBCddwJ-AtmK-RdJdvp-fhwv1o-pZza
FWhV9Rw_zsrxtmGwePrzlvnllMtcCzp_b_0vd_lxBko7r_xK-RtmGzNF-_hMZFqlz1dPvJ-T_Vs6L5rVRUe3KS-jzWRUtDteGrnlvZzXRuXzfyyVgEgDladz
A7nHmN5CkFyvME9w8Aye8FgCcQOWQcK_lo7bzQFtGLzUGCLbGbKG-kUVjlVpOVtpxVC_dxUrGpySe8U_ItHqIN_MyKKGpq9FybVBpCpCpCmd
}

