sprite $video_game_console [93x93/16z] {
xTa7MWKX30JW5y8kpFqFRDVn4sBBO6NixLTysTbskSdEpaxnQKn0MqEGbkSxqAS1UjPsmEEl9F6A5g-ffl6-3dSW-X9GadXPZ5imeu0bO1BHch8P5r-CZqOo
7Vx2HkCSvJ8EdAFBy1RX1reQFt54-9d7QHXn_jPKkFeJvJdUf7X39Pwi5ZPNX7iQTs2EGu2N0BTSRx5S0jmKU1bmhYZVN1n5FUx35ietokQYMXVY-TxYPZxW
x9nKpeKugzMR4UU2DCt5EUT7akOQyRuMTm7kSnme4Xphy3B5JOxxEjpgPSd_d97Z_Mjm-PpNjJYBMzWjR4L6sefZSLi_5kmi61tU1rnrx1yNTnNX7areFe17
hQ0vLkGr8xulmetsJORFIuxFpUzIk29XRn6NdLdK2EyPVDnOUCbFTU1o4ZVQR2vTRvb9ooN-0m-q9TKYlDxYuOmgj_wnN5PUGBEVV5tHzVZwQxdhyO9u5FET
su3U9kb0-vdtB1YlqvGFCZixEpixrm
}

