sprite $VPN [93x93/16z] {
xC610000082W_QaNgG800000000000000000000000000000000000000000WDaxspN7SHK8su00t_y5dwyvJ-zwfkDqAiBOsQhTVvsCOxq62OJmYP8nVFkx
OWnRBYvAr3noUo3teR9SKfIEYDoUACClPuMK-lPpvQK0qkfoUr5-2HzAoOWDKReklQB4Drnn0NwSxN2rsH-bpvUOJp-HOKk3A7zCP9ZkFYfcdjVndzJ8RqaS
1UGwlW_bSyXoeYYDxz3PSokIRuqmnj8fEiqSRwrreityQ7ZX-cgCc03z0d762vK9mKRw-UP7hvawnuJh5v-KnCHmJJtxijUSydBCJTQaBsMYnhRJZB4su9-a
tX_fq8fSQT7QXHfPOoMM9qT-T9jQjXJA-VWegpGGpzEiZsvpVbhPTlYMEj5jZcM-9CzOUT9jfXRb0MgU3qe3XDUFZv94uU7ESzPbA0VWWTRN7pSG7ewFSKFT
OZwrt4TpwYkp1xlPrIW_rneiItmd8ps_sGKfETyKVDPUEpM05Sj4V0JmZhHZ2QWvnNTIqJAEDZTcfzyCkTj3GqLNw3mrtqdJQuXJPbsPMHQzswKfW_rcl_5H
sPcoYaaXEsEzqNfr9mf0qHjqEME-AHcFqNHzVAU86jtFliFPJagYUzun1WtlZrssZTtxpmyTPtoAx-wNMFmwishLDtI1uY0vBUGp_sNZXQCg-sFUCIe1Al3S
rxlE-kQYERJ6ZyJsczAjVi4NdNDl_O-mWFlUuSVzosyhhb1LAL6zwiH75JzqN7-WH_CI2uQe3TWjJscSFRQ7od4VduNVjvSTAAt7vzkHHkMmZOjawqhkyKXM
TPbwvoc0owhTf98Qowl7PzjsDZw9ufsz_edFyfINHcZ-sOTKF4jNdbeyxVLFV99_TkULCRzbg7_V1D4gpmaRC6ZT4H--b0Zzld6JJpMzq4SUDQNetgoPdbJG
suzgsaEFAXCy_qD4LcPyNZIZuhUVMcLwSc0kqnw-BULevhtIKk_wpv7amOhFSjfoq0-tA4VH1kPrThMzEFjXnt-TvJZZU1_7Q-drBrj6JQqZCEZ8xAhu7YeU
CFYdqzFZM32aTCKim7MW8UkdLx9v2UnjGFb6Q4rsVtgQbVJysMf3vj0pu0CtfxSt0o_9mGCVW1RC_tHw8GNHdjPE_BlVVZDwf3SwR8_qR2wzpO1eblI0-zlZ
jJdq772jf8TkW04H0nBlwKPwxoIFd-L8P58wrQ2oIz8xphNuar6LMKSWZn-YGNhO2OdIKHs7UUY0DX99JtyugZPlVyyEjezy8JsmZT21mKHbSrEiZIpf7PSb
ZEDHnOkVN1xKciL2Ud03PTS7VyXvC-o-g4mi4Y_e9Bt5TgEgtxrADMt-EPTCCyyyg8KdFMHKXutCWjTmIcx7YeNq2aPLJYdQ3Y6zMISYAqfaBQV38xr507YG
B02tINguzOLElGa7pbwI7dYsBbqAHdIoroIznVAiq-GZShBN9Br50cWP0Kbq-1wWajxKqv7fGvTYQKmVNRM_ox-CsxerligDX_qbBJWWE6xPGqp4OxkTmaLk
sfT6vcthLQAh1pWXuz9mKd7Qn3TokxEyxu1-_s5yYUtcIfkqU-eT3TD3UWslN--vJxJtTR-xZkqZb3AZlgMdu_Puzv-ulr8R5k_D4vzl7wFGoyOBHTM-jksK
FcuaJy1vjlJ_hAcqrwsoHtAzP0I0hw0JKyjIDmescHhwgt_9E-OVNFPMsTgOC6cqI-BTk2-0R_SdooG-u-rsuxtQIy4SRqDwjVzbmCMzYQqXNkYP-81GwVBM
5_s9bdgpxtyjObLHhU7qj77EjazwBo5ULEiL2x_-P5b_Xg7_LLFz-mjug8ddQQulXVrVQzzxIV2Xi-oD5lfzKF_hNd07EFgRJZUqeqHyL_y-m-VJ0rn9--oF
RosEclnG__jIUkkHyDeaY5x8Xz73Yqlw9pxIwuyNy7cNzFhJPBZnanw-QEWFTKWFtr_eZnb83tpmksG9W22zXdeau3UG7h3WwuuPI0-VSwvVcpH8JyhgaV0M
lQJNNuzK47EINiUqX-TxI0z_wFkJPQJNNu-4xtEGNdyz4bwSqKzlNVMNP5qRw07pJOFizJDSKKvl5VrDifv0xySZ04nxPNK1W2hfoHvTFS2iEZHTBubhqHCz
a5oCNYpTyYlH4tqYkHIzqKxFhaDlrHzeRQTtgJCubw6dFvFqqxjGo1JN-F6h_bXNeUSNgKRjfoVwWjPBq4jPRemlf1AUo5Vm9xNuQc-_NlQIVFxFboUntIer
-FRqx1NfSa-DwVJa1sZMCdpvJcqVwQq_uo9JyP5U0JpvSKnn2NgaTs1HHw3b0lH8JmxigH0VwStscy37M-cHtgiqrad6HtfpJMy5lj5AZ_G057ECZ_IccXv2
l80UwI4W8EHIG8_q80ujnaTwk0J4C67TGdhp7AU0rEK2z4XlHJrk6ptIMs4JwgT7UWBJ4y1eY-YHNW5tc1xfrVk_Jw17Uafwf4Tw-99plJ4zqXFIe-sH7ctl
DgBjaHwkkzaUwJ5Y8BtrEhaMqbjlJ8zPwlL-UmoaXs-oQZyzqYlOMyVlPv3UETjqSqi2_N_Mvq9w83s5RNQ6B23BOpLkVJrdlKXFruvQwdxn74E_U8P8aA-q
YFJmmvJIP7gaTmn3yC_tY-VM1UzHq2_sZ91NFhmIHGqz71_GbwTJfBVyj8ELN1uU-vJf0UI6IO_q07ozy4WFnoS77sc6HteOc-l28xqzdLj5wQItnoCD6mka
LrjXTW-tINfB0ptIgoqmapjuJj8JuEzloio4z0fASuzjSrfHqXQ3z2hBugleoSGt09CUO9nJta0Of5SmxLKlMuALy6LbrVKJNv9UZUFSwoFeaTxQGu_q0BTO
5V6HNdsqLp_naTuvNNAlJe_qS0FjfyUzzTEQYPDUVRHNF_6HtbdDuQzDZ_JWbMa_FTAJqvg9arvTYhhUTP9UGQpUJu_qy4KB_C5-UgHtNdSvqgkEzkeZFj8x
jUVETUcH7h2-kICzqfC6UgG74AcS-4Zlr1QvfFURHEsL_xoiwu2ipwKxr5FfsIl3e1U1Pv4Re8dq8CayUeWoBi5FDq0pwQsAgO7UNhBqAxhfoLtfUJyysUvA
R-sc5_tqR0D5Ugdjz7oZvqGrkk59R3TTjKW_FM-dbxtqS7nBFxsKYoHEjd0VF_i_2YeZv5LLxCx-U0I-lg5NcVO6aYbhL04zTD3w7MSgwG49ZeiaMc8XFU0h
lKCmWENJ8BsuXklSWFbtaDwuHBf5a8ph83tPwiO0V8P83t2TjXG8yD-a1wuN-jDaIdelqRCBk4xREKxIGnACSe5u0VbMweVHWt9Ktkyu3M9kdqKliVLUUvei
5FhXuoFWQG9M1CHQ3TCUvc_xLUy3izK3uQbopVRjhVxfet_Y0xQf2aFLRWUK2kRtfRaU2OtnSxc_0gGWlRL9-B99jyynle6L6FLlqU8EiA2meqa6t4fjp52V
Bl22WjJUQ67R7FvkI6-yW8FVneV0IodpNVNn0bx2wtBVEI-tRSOWUFkqXnzT2RtpQXFmVeMrINYyWfz-63SqFnt0YGGyNgxVNy2FFsGCqnl9ncy7JgrWRnjN
_QKbji_HA0YOQ_LkZbm_1b-YfYDbKt_zb2kvVOQiRk67gzvdVuJrfTMj7UhfwOI0wRvA85njg4r2zkW-V_8BAqWs0kgoUVkW6QyltTAtlQ4UkTrE6Qu5csnj
n_PmYUhmMsceojnp81TFar7zjKculwRmWUn_PAX-9uQNab9uRLB_jZg5BzxxBqdr9yjqnCmEavJczfUYS9zQR4UEZhEapvjhZOt7GNuT56NvPnR7oYoSrbVO
ewygV1W9T0YbW54jYAD7GLq0vNdAg7f1JGuLsv6YtFA8hx2mO5J3m-S-oX8kcC5Nc_w_VrD6JhHohZPZ_28QqrUU_dqDZiKRLaxvz--qKS-fHc7vwBo8mUsn
ASr7yuxbp4Ja3j7yOtWqFNaCDkRLJ8SSsIM1O1kagGUZcZhj8T73vUWhrw76OLHkqr8kSRp_11tRflBODyOarwbFgdq7YyiApbrQ0gCAr438EzTXBL82NMjd
zlEBDoPOqlDdgmsPGY-jeDac5osZjjh5Tx7UP7gCzXGmJc396LUYHtfu3-bwUgHd03q4ZhD0wOsL_7Y6rsgBHODvwe8tfnr435WZkugJrqnp0kVAeKr4cvVJ
eVBOfVciKOt3pIQ3jeYeSRWnAjD6rOxoqB9ZIo7xRaSMapfjTpRzeOLpYm5tQQEqSx0_hBEGu66Y2OrEul60szJY9zVzmcY6wV7eKEY3F-JSnsHBjw_JOFb6
KHAb-r6L_u-gvwwWStR5TcQ6PoQBgIUCwdvOVnzLdnQT59NS4r_zgEe1FgPPYZhifTJNtEFmA07WGTAOR-2K-EDHrO8BJJqbICbuCAe-_Ke5NfEIF6jKH-ml
bHEQKr0M2RICG2JcNuKkRhIxETBTgD8Y_jqU70i000003FAtdiJEwWO00000000000000000000000000000004
}

