sprite $VPN [93x93/16z] {
xPY7iYGX24M1YyZz_m_Ur6-iMbjhhT7DVLwOV0Pei_nnF3myF3mO09EVW9RaHHOzh0wI6SLB9CaugNSo_ILKJzBb5D7Bd8nZxjI-JCag9oX3JpqIErhSVUoG
RP8c8umfkpXZMYxV3rnbZAw7hXw1KV8XCs9KC4JuJP8aMGUvGsQ0HNegIQRrsHUrod9_iyeClGSJh6RHrSilBNalkSp975-68BxFtgvdTVxvnloRZQNLwrRQ
kYLlXN9wroDKn5bbIov9Y5ZVV0jPaxHDkP5PUMiNdcIgRCh5IAR_-BqMcKdc73ApTfCUSwN75Qw2QSUQlG0cP05rqgGHnC98L6co1bWdfPtsTQOiq0kDLHP6
wC6x5c9okammneQytPt0t9GpPKemoWSZkHbCH_BoGR385B1nbnikz2QVjFcP0BZ9FxG6s4sE5oPBz79h7mHqteBVawCbhC1XkK6x-qVbqj3JSdJoloToXVLP
D11oiBMOTEpAzTMy3P33yYPLGC_B1PWLHS_8hvkEuBPSOPrylobsdRxTdfQt3CxBWNRdJRcN5uDsRXS3UNdXCiVP6CWR-jOq5_JfDAUDsmLjdtA6_9QbnVwY
A6WoeH3pLVzIliwoiXKF5baZMEPRq_4hcWnVeJ8NZWgwd2ovHjMkiai71UOhsD91X6NAFamRjHIsvpV0QAiOP5JIzjqro2BtxJbOPOyaH3IfauE57PJHxOow
8v4TZ37OwOBHDg8xN89ATCKA8EcoHs42mHmTe8Ni4kJez0F5JVQnKY0Y3myF3vy1
}

