sprite $VPN [446x446/16z] {
xC6n00000C2WV_x04wa20000000000000000000000000000000000000000083PktF4vd4WYCA1eiBz3pn_DFj07iCFO0clGczDzgScpKtQbKmo2Y9Sfw1q
jO3IrG9ALmkeNIkWTiryqXK3YjVlfzsSf8TFkzgJCEAj_HuVimZmE3xn0Fs567Hodi8dtlw_PCwtFAVzn0DU2qmCqEi2FUsWQUOZtZm7-CI3_pGVyUGJxrVa
0yDtjr1FFBw4cJJMVPzusyg89r-jNlthH3pvnDjVpPsUV8wUV1_QI_KGlEAQwbKNTVJaS_GAjftYENpgbV69v_3r3m1Rsj6JJps-kdf3FV4AwhlTTFZKS_Y0
tgddw05yJWHMo9NDFtE1NbzNvrKshzH7RsaoQIjV9b6Fw6htk-Jd1htiQMlcETEtVhuzNSsxg8VD18-N_LthrylxdAtJhpVgzVALg4TqbNkS6-ARDwrVRzuz
M6_oZVhHuvTaVrSdVqozxoPCL-Tum4rVwas_IIu-hpSkq9iM9PV-u_K6lu9pMrBlFPzwYrrLJxsXthu_gXum9cLw0UeKwAcdddhgkTzJB-fL7Z6efvvw-y-K
3VOyfte1QgBNCjJZkyfVHrIFlsgg7dvndSARtvMa7jnLwlFDieIdtjZLrNmXGxsdjXMhejuyH27roheAb55lNrU1CkhjwofGHhrzNGMgg3UcU7obeTvQzZLL
lTwUekTOKfOz3IsOZVJcuQFDrqnr2lJ0uKjzklLogHrmnsMNNY9VhLuYNrhr4laWFRvi8X-4nzTDvFiSlL6M2L-1tbYhss37l_xo4NgZCp-frtJklS6ENu-J
JVWflN6jtcZHc-CvV4sNBK_WsGRrvjFNgPUrfLPlx4-1dcrGZnc-Vhtn2QdHcokeL_gXo3Vh3VNKsvuVqLElQ8lVhwUUUb5FFU10LRsACnRggQTUrIPVlHJe
gLVpWUHrUkgDY_NKKw_kyeXw-LWzzTJBwozvhDuucwna87dzU_Ay5gWtj-D6K3t2RXxr7hlicR21VZ_H0FKcPC3-JpqCRnxrdhRmcMZ1V0lhhzu4Z-LJZzzg
ydm5UDESNloyuM7vdcd7MsEJzmNVXwsFUdCOW4-zzNnP1U1J3y03-DJZzJAcoRFqr9jue7pgWNWydthBoV-s2A2dtlhe1PXMzNRfOR-Z7gy7_D8iwe5uF9zw
YqcBddfpXM1xI_LulOMPxT9JRvpNKo_VDWYdfnu_GJzoWw1wwgct0b-dfzwuKayzzTHJBsrwwZbxpfvwpfvw7k-fzwhJKozNdIbJpoj4NjzJJptrrkzAobXE
Cvxtb0qCp_ivrz7vgFSIp-SOdXIV09lZHOs2foyNVW6FUb_NU56ZfnxF5shqrEFvNf-2v_krB9PNZ-3BvETAHy_tAGk6fnxFzrGyzV9U9W2UUWZVtdytrUFF
kG1uwY5yRUUcrSiRdIVZgJVKK-zqrCkxxoDhf1umUl3mUK-PUkUZNjG3TdlGZayzVlJuuLDl7lNK6y_NKszyffvw09zwwdbrjafFlJdCt3ZgFL8lOy_mgSUE
tduzzTHJZp_LgHwDnm-VUkl93NhEtdYoddhZ2ZtrqgUd7Z1ywgtXNQ2d7d2g4z9JZny-zVZTddhpvBlv8RnlvlJgDzkTrqlnYrUzr_463FMYtX6y0ADNfHVr
SgMUUkeb_i-v4FN6cT5JxoJVK2z_vEIT4Lrd_jG3GkZnVEgfDzHBMGjoiPvwwgLWmJzIJptrqhNXLEzNr5DFlOBT1uzthruMzTAery-d7X2tGAZ2Wbu1ddf5
IMiNlbt-C_JKIsx1u_N8ykhnVFlrSW5UWTwDVAdLMrtmVhuihiP3z5PN_2eyVlZusaatO2OhS9jUVweUcLulBHwenuzzejunllN2D-FrwusBxVXpJlpBvdAy
CQhrniLu_NhzW8VtF-UtsFLu1SE7LgsbkrlF7DORHZtruePJlONHC-h9nnPJhw-XIQ9UPrCJzNPrDKGP_JgxcadqGxfAb96lhgl9TZxn0fPHZ-zg2kgeXxOr
ESCdNhZRzUK3kWhhJRvXqAwkro6UmXDlyZq0Rw6G0RiwhpFKe_Jusos9grFglRC5zUJZkwgUUaCzGE_j3nJKGQ9UxjHJpwYddl-rg1VrFDupwdccR8LFl8rT
zGgHLuYI3NZgXRey2vHHBvbqrRkIgF1TXTv7D07mV6vlp_sSulMqzH2UUaGXzRgwUW9FlkAdB-KZ2edNsTMTTl91bNWy_OhV6KO_kbA_dUzMzbjxS2m00000
CCZVUWpxgmS00000000000000000000000000000W
}

