sprite $Warehouse [93x93/16z] {
xTC7SiKW30HG2L3P-nyutPP_GUCXFT6RzkiQM46_J2cbb59AAQMKKfW-IrF01dq25WVS06YZZzMtL1uEk31zb2OEsE33wS0wVO2tfJOw6XQVhUknocGtwnqE
pdjOxj2p_owqUxQqrNPPJYneeTs5eunsJuzqOcr9l3Y-URinqffKiznkZ7HEVMSzQNUbGuNlW7QYtOR3cnoSTWEIjIlRhvJf7DWX0K9JFS8xVNHuEnzUuJn1
BmosSxJhV-JX0pC-Ne8CuVOJuoIymLNkKfzS6OF9nc19kCnFlsFChbKmfE5jtj2OLHmK_3_3Axp2fR_IB5pxFLVXexyQ4HwIy8dBy23qgezDfwa-xcCAFFdy
tocbF08
}

