sprite $Warehouse [96x96/16z] {
xTG7biCm20HGXE71tF_0srSbYKcHl9MVtaPOuD3_ab9AAQMKKaeffIIcJ4TXmoiJEa1H1rnvCm36jDPxwjQlL6WLVWkKBf3hSlF409ntLHOSH5megqyq-wQD
dccsrDzEr13lYqpiOQ3StJinm9Nl7lLOtEnur6Dni-F3D9uUk3LjYb8U7hFDKNcBEJ-p-Q7JX06lW19syRFsE_xJ5LtD0WcRBHzFOOLkfE0k0r5LqlAL3iZV
_ds-hC_Vu5ev-DvySy0lNzw_RUYy_quTbN6ORt2xh8vpuQgyntU_SQ14-N3QKs1qaMCOUWtpZNRvpjhmiOeWlopFp_gp_gpVxKEO3xjep6zP_fbVq2ZjCkom
iOg6wVkabD8p
}

