sprite $Warehouse [446x446/16z] {
xC610000082W_QaNgG800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000061shWD9ZY24JOc24lz_i7Essxu-ReV6AzaLBctI86W4ymGG15XaPXYkQH0ioFm4kbsJ83YPtq5E2a25NVuAJb1G0H7vHv1-Dd-2aRa6
uzGCAC22-IyS6O02dCoNW363G2ac5z-EK_WJW5XG5mOBZbDGPRllJHOO1vGmEjejJmVmunHKWByygfOAQWSHgB3BHKbvZe8A2FBFXGes_kgiBemKirJZz46A
IKU1-rOZIOffXGkWrKYIOlh-Goq8R51GAMQXGzDHmaWnw-K-hF2WTKWnKNxelZQe5BCEMDni9CcrO_Z3duHgWpQ4HLU02mt6mDktGGLduK3TgQ22jHt5P2JL
8o0R6yamPg4Nf_4YDeHTrKWIO8kmYx2xNybU6rI0dzItmeQH91Wx2fMwaIG0VkXPIqRIW665MKQIZdOoakfeKCm68qa3cITtp6MM3-WfTitJIp5b9EaZa964
65h0oKY2SMZgbv641iLik10XnHnTDljpZ1TbEDJaEniMGxqMRIJ1o965YemaMEJCGaL64fmDxscYaIGzaP6aPfYC93Y7rj4oacne0f2H12jOFt9HL6FAI99Y
jXj96iYKaQHURLr1Jmx0iKq6RIGj5LDXLzr8qa2c2eDzito3EfKm90q355E05yexzQ1b9C79aLlvCf9Wr4sz6cPXD90vPCYkuQO0PmEx_vfx-ZTUApQWpji5
m_3VL7ysTsRHcAy2YUR53WraWlbgq4SRIVC7Ci6i86QVdzVZHS28vdxM48Ctaep31p8zYw0TqJT-oiqHP1aynkLkwARs8h8CsZ7TV_IC5_MNBAIRcR_yFnUP
htMw2nttukW_wT4AvKvdWs6Vlh7BzEkQ9IfnUv2HPBjbMbqn-zCUhKAzdMCa-KRe3LFCDG74AFRMMSntcnEJT-tYJTZpRYDfYxsXYhacWDsnLm_0VVRcZnV5
AELS0nliBLAzOcyIUt5jGdbFxAdc57lAUzSaAEyfzfJt57jYJtbFUKyrf_AUs5FU4tlAUphlAVQKzyIUQawnfxodlAVOKzuJUueziQUyDnTryMD-0HHxpHlh
NjZykyHU-mwHOGVb7IAnLqTa7NOfxytTdSMJn1xCxmSAmLTTdSNsEpRWIFRWp1OmxA_lfeROs70jlDnczXRSjVDdV1HvmSBBFIhlWTaA-iPBQt_OP9mKUs1s
8x0XwVMSP-MNUmnxOFR3tpebq_70TnmDx7MHLxyZd6q2Zpv7nY5vB_8847VsJ-kmXjWxCFJkz-6OMKSSmPvduweqdFVVKSnsxZwrpi1s07jWjgvA8sxlI4Rb
7GSNmTUIzupDxTplzCNTpeNNk4T_xFMFVw0WdINsefWr3sAFTdM1zx9dnUlLJsGFLnTY5dksdMhUitSVDWn2CH10aKrnzbyuAtoPBjuDaCBZTEfkwDN9UlJM
XfxkqQD7ZvxTewTxzEZHesVtT8yUFNhqwDaztQD7ZnuzUdPFz-ZHeqUFNdrHJ_VeqQD7p-xHqprwzEZHitlqT8yUFNhqx1uztQD7ZnuzkqTFz-ZHeqVFxj7J
FNhqwD6pU_HqJ_SoHh8-I2ykoNAONWmc6tg3UOxUhwx9KNgDRnpGQ-H-lUlJrslaqthqwD6Z5sT-OrTlkYtBomuVrOctY_8Pfv6VVxjnRRzjPxulMQrhZZSc
wsg__Z_kdtcjYfDkDyTqRtAvEZdjI5p-ZV_su4000000G92_zI1NAm0000000000000000000000000000004
}

