sprite $wireless [446x446/16z] {
xCgr0KHH302WPyd-6tyhprsXfdm-00000000000000000000000000000000000000000000000000000000000000000020McfhjOrDvBuOcxQkPNy2QcjZ
4Okys9B76BsrMjw4raVURsRlJ11Unq4OR0cK-zzuzlMjTHDSa-YRES3hJop044N1iHgVDnqNaabW56F8JEceGCeiarA3q56FOboB0I9rB2ClouM6aJfMeqoC
avZGyJd4KOSJNJqPyyMe0LF75aZ9KOVrifvNaw11wjWFvKybr31rx4gbX5enwz4HuviOvj40rQL0TmVh0sXuD4COPVZOrQF0C4mTFN49IXsDaU3OTKPqSzSP
XS_TPIZ-XEDV67-YemOwTcyZAJD9yjMT9cQcfC_gfpLJ6II0yGO06QbFwAVFdIB6DKHerVbpxAHCic0OBDLUmBWtLn2eNF9r__vTeECCoL4FupY3NAnyZJ8m
LW6UKT5mmlil4lc9zT_pvOj5CwFXy-OXq6z871_bxGNyUBfeAeWj7hnyjdo-5xlsJzz3jnwqtzmQAJtm-27lql8ozRGDxD2TydteIRCZvDrkca9wojrdw8PR
MiZPN_M8KZDk-rJUlTIKUEC6LhprvOeuki6yx-eyr3Qn-pTIdz9C061-cy3lV4e_EPgGMgoP02FYFxiD-kh_lv6aZ22mMZzpT01BOuS8IJhcaJAuzDVYJkMq
k8D_KYQmgd-8xOEteZS7uaglEKb15DJNtSAd-XOM8Urcov9twDofuXI0oACI1OlJdzWzUEB6xabIiFZ7RqbMbiwKLdfReJ3bP-FWYU-SkXQlfLDTXxPGqRm4
aMhmNlfK_8IUmIiGp4AaBFexe5-z8ZQqcnDBZX-xtQya2dhW_HGKqQjnB_ZdGZhsGUBrW-beTFA4tauW2boT_TIbKr3SmFWgUV7p5praKooeLFOMKAX3vKbT
URc0l8yrKZIuTSaBVp1JTx96ehRFVDV90wIZ0r9SffwnUTPJWMRsqS_KrjAPryWCKaShn6jQlvs5K_YGMs1yHNxAcbDTeoSiCwNM7_pqIx8aKtzmd2Scab-_
wEKQ7tzb1WaK6SoTpmknRTxJsKTJ9oCNowqivjCVrQtc56ilD2KbD_2NIvpvcHWV1MU21vsmvHmN0aQgKZwHUzwrwFqkBxMLZocYKZwrvptdky6ZZgF82sJv
ec-y5xxSSa0KDUsvajZqcvlY6qsjjbn-ZvA39-piHAcShl1YR86cqrAM2-Pw2HMcgZJ5Zaj9ukMbfe9ZFGnTNqqnDEqLMq_eTVrFTN7xucESTK2Ibq-29EnZ
hMDJVsfEChlvmiQuCT7H8Yha3xDFrfhAhHHZ8e0OizXCOYDhf7ZsrnWKpP-z1t_MMTc-uXB6lT3n8e4Ro8Vuo9INDocQ5UCsOB7Yu7SO-Sz_-9sr_Niyh4KN
B_2QowyMngusc8CcPAG_gV9AZKn9cjWU9CkVnhn5y6eF7XXQ_bKuwI7Y6NLT0iulPIg3A3j-6Cs1YgeLfAGFUblb4zfsbHmyH0zd7Tw-Ln3tS9jJ1gvk7kBk
9KjiP9uayThZb_SMJd6fO5ukuxfrujDrvGf2si-Q9NJVw44JghcF8y6CFoSU6hqJxYVrJCHFJrJEnEkIkRUrHpolviovQzAjuqVTiz-BiwLTg8Cr1DHNEETp
kjZ5S4vnmcu6zvmmO58p6vo_lEMCGU_MAz2n2OctaeHkELZFWjWL4vZ_fNdBfHOrTBwQznOGnps0PhC8Z_tGoqD7IHrYDpyOKA2lJMVWvNssSJCG6SJQIbCH
6LfOVHgTz9fBaXXVGvAIf39ZEHFl1ow3m6jBdzBrnyyWLwtsWN6jKvFXCOtEc84mfOkAJvEQLqkUBwPqNZqDz2aDGvxSVJ7K9ysJGdhVcSLaoUhil8JEgwV1
5dyuPArkkqENE0e9kNElCvD8RcJjaMCORcP805r--joYA_TxdXm-bMbclNxAhS86tcs5ByUwLn1tBQRIMM_NpefvLZejdBbrEUpexNobaNexUevUxjwDEdhV
XtjV1Jbw3Kg2qAmsE7gA1kisuOwXQFu9_alDgfllMdIv936-BNKPWMjl5JnbYEjK4upyQGUIIUAYy6aydcjknX2IQZzPcxxbVEMXrXBFESL9cH37CDIPP0A6
LZaxKZyPU_ZqnQn9vqbhJhmLl-GmNxtV9rmveAYO7GQ36F_587w7SwPp1RPoPfUlSdNVplJsxcxhcOPPPijfrduAjfD-cZWg4KOPXbhWQbMFfu6zvDDm4rUa
UGnoFqzSiwL7Reu6kDHiy8Q2-_CUfaZk4_gtVhxLx5zwEdZIALD0ZWzWoqVbVx_HZTzXfjOVFiFhLXqGAQtCV2QlDNe4KrfLTXeLV7IDMZAmDImw9gdww1cK
3SKZgwDdM9YTaBLvpw1q701Lrfm6gXtbC0lxFQFgCHnKTjTYibxOGaL7pt31_1ifPxqQbXmCgkRfC4iwCQWawHbeIICMgjZgD5opCeJ85wvCfp7gd90CCgL3
Kc1qn00Ozy8OOumn1cJ-2SbErOvXIXEsSljWc4qN7GoeheigXkhwLgn1tmy_cL1NIok3RFjsYO4Uy6QUWzU_-FJhjSgn5GvUpzDdrDVHmsHVGnOJVHqz3FGq
CpBhPl-sp_PpuxCOzJLoDD7Onz7ejYwgTfIGf9PTWuLJIGmWjEcmpxnqh7BBijFmjGKMQiEwnUX5HQJsaqwZLsF2FdMBhpXrrlMb7eE9ywJDecTY8fV5PedF
vCJi09j5pyIC6Af5z7psD1f4pyHJekVePO_eMJcd2rHZvJIkETtlDOYUYObz1sos5cWmSNUPkzrpcjTd3EWx8V9yRsYxw9byzGMXt6-sRl3QhX-wxRLu6LV1
5zmaD3R5Y_1IPagRlaPae3j-KzrrIrVV9E_Zrhic6R-_PwZ6MSz4v_VMZHhhfc7daiL4Pzqq-QpWEVKfnYuOTJvvHfs3P_BEveuszD_wWyu6kdczukCdOUo9
GRJEUARt4ejXwlWQAKOB32Fplv7BeDFTh-t1iG00003087_hKUoh9W000000000000000000000000000000000000000000G
}

