sprite $wireless [96x96/16z] {
xTPNWgGm30HGgOBlV-CDapoDtKlIPhzFeYnHGFnYox8iox8iIuBK2n8PbK2vRLX454YgFILct4At7MPSbMg7AEC2QDjmaGH8QZiEuLRjdlGvALzVW_gPVZx3
_3mUnM5mhpptrjcFnTdYpNFFcEA0zFJg2Kf-8H4vlOCpzh2zuJZBCLlZMGTxeno6EB9oFF78vSqn1ND2RzB-3R1f8znscPl1vLxpDS-OY7o1JO2DXzLZftwE
6PldTyZMItt-SRBCtfgz57385gGuXCTUNL1VmXbwbldCOSKNRk19nlfGRJ77BZcEuZRjEVl-OhjQdEkEUe5xdqQUkpu-7qqVo1PyfZz12psKdRzhRPAj9EES
CMF8sV-Gek07GdZ-v3lZajuRvVpkDs-WlTDJFIONQFzatha-7byGIVc5c0yzT5n4AUSXSzz1ndrg0qKP-7buguklNm8U4vpeNyQemEr4-xJBwXyZhBeHqsOC
GCHV9cLRZ5BxFnNrCM3KO-kSKQh_4zbZSWjJZFSsHJL-bDt_TSgdouz6uM-gl_UVlV_LFBpvQs7d-QyC6E9de8VgYq6ICWvQbcLPbgy
}

