sprite $wired_IP_phone [96x96/16z] {
xTdPUfmm44JXhgfF2lN-3vnr9dHYX91d-igSkzb-TWdZ-0hTtTtTWId48xJD2_KMevHZ_8bUZd4OHJpZquVjheMwRGnM7_4CJx_RYALezqWbyk25hLXCDivM
F_km4OlXy0X0YagVOgalHQMFOf_2n4Vt99tuKapyxcaQ-fZwi9jEszo7FiM9p-cHQDw6leHYFohypCrzncbzx5EO-U5vRUJhWa_FwZ7sund_bFrdF0ynyh7x
qADtZWyGFqoIyKQVmk185FZnRZ-lDCGIFsr9gQzJl_MURkjwsr_qtYxwCVQxlR_SR6_xj-m-yFDEnvbF9wRvLqeBDg_u7FlwwBTzMrxtyI3JmfGNXYi-ndwq
jCkZfrsExR7WcS-1VxHv_FS5uYL_tbVm8RxkXutF-I3pY_G9ymiWFkKhZmBz_nUArD3NnUkBwP9DrrTkFhxDnuUZyITQ7_e5uzlryRyd1NcNy7HypYfdymlJ
bDAlpY-idN-pAbNxUByVKkdzMnJVV-RJXhyxzD6zxHkwUMEwz3gIl_htIvh6TN3-oxQtKrzpdxFnOUp75Lyl-1IcVkGXXmyoBJbEV8Xpd_akH7d8Rqu7U_dv
mnvYzcBie_Zv34lzaAfzbFeGI_sGQdsAfJwaGx_5OcsmJZnwllrjTG5eTe-Z8F5lOXvw5xAzuVB_5o1rBzOHWv3QznFK5X9Y8GfH6AIeJ68KnfBLVnnRK3Ly
FaShuWD7lDBTtTqF
}

