sprite $wired_IP_phone [93x93/16z] {
xPc7hfr034Hj3rly_n-SYcGY6C0lE9MZSlkvAxEp3QdcvUNbHJT8OBYDSVVXrvgdw7einm_8TuQxpzku-rJIyFtpvjuamU8-v023xUMJk2bmjyEgw4wkxYev
fY-iuNkv91dUICCBvA4haXkiJWxekLnRFsLXyh1n-VGB1fKRZCWZ7RsTqDsDoG4zbpVlL_qRN2vbSgsK6-nIFaxTwbGEw8KSVebIkJ3vxKa34d9IShLlxEMY
TieceRJaMB77uXzo1MA2VaOEA4dg8_9uffLoULWUdKKhv1ObvtBCsML5nnonRfgpVLmU6HtRqLqtyMfC7af0gRnx2E7VXV57iqZk5tADpf8eYx6ovEMop5Z3
sl09Sa4pyWI_H_xAhMkod-_Ztrdy0oxFnpzWOylFnr_1vKRburxykozqFBUduoyREJuI_t1NJNDShdKJjC7gbXPQkIXIe6uv9o5Nh3mn-_FrUJx-YPr5Flw9
FL4-_hcjOZx--Krkn7ySnh_J2nezlV9WeLIkV-bvYm0ryle3D0KAvDNdYln4rBtdtCiQNDxqa7VtiTXjC5XhR7yAhHYUPCWn-_DpXLbFgI6tCQYK0TIv3LRe
BgkAei0D00QWmXqTqkfkHia_mylBPm
}

