sprite $wired_IP_phone [446x446/16z] {
xC6n00000C2WV_x04wa20000000000000000000000000000000006Rltf5antKW31imCeZzB_WwzzrHCwUKQe8f_Jas3eFn3VGieT-QkXprzz5wMZHfPwM_
otfeGlLgqWx0CgEv8oP7K9MRkRwZ_yhEMEFHVjgZjzwJhDQhAJpQJrlqrhkIr7erX4VtQOUUrkiIf3U41z_bXoPVr1c7beXeQeErGK-9TFx3suVe6NRH_RVv
f7VP_IkyOAB3_Y_ThwSO3B__jlQUVaNFs54wts6jv-jrluXFmxSBlfxUXDVQkDtQhQT-VBRfQRjUlqnFiwtdwwqdwbbd2lGuTEe2dgUdD-XfZrvjr-jNP42l
e_JGKx0UUfMhXvuCl6azzEefUkXrb1vw2jP3py133ptq3Bm9FVJGGqy6thGUUlKKFVGwIWyzFKKFFMNfeMUq7dheeMVZvUkXrr5ww5M8tZeiEazFP-ffdHcT
fTSdwccT6w5du8r7eteoyBReQPqTJUhLuNh1Sv3GqmhW6zEhm_LMGixGw-Fq5A6d8JqThhSoCgHNJz53hu_JYnw_YLvAvlLqk5uV5Hbw0wqthTU7HS5ww3Lw
wDs4bwo7dgBqq9FHUjDwwDLJzD3hJNheeOUUdg97xtMM7deAraElq4CFFVJG6y2Br4CFlJMffraztgtFjnw_QydNGw_H2-D33xtvXvnyXR9RJy5ww5M8NYVZ
eQVZyOHUBfyQlTY3PxUbv-DfJ2-VhmVqTAtrwWzp_rwObVJHuHOxfioXXzu6l30zz1IiXrwTg8UUmlJGCmwSqthewLrwz9w3Dw-7de-7tkruTJUUpjP3Jv__
sxiNz8odsjDxGKzVumczO_Jslij5pyTxanvwCl2czT2hC_NGCxZHGm-zdQSzXUYXzxa0FVIyeATWFVGCFFJGUshGGyz_xANxyD3p4w677dherIrwwA67NaNh
IV-gbb5gp9HJhbuFwsdzJowll9QkhweWlJf8RwrrbKz6xOVISRsEqbi_eozABnheuxBe6TrZ3roIKHgervDwpjY63t6MZT3JANhhEe7M1G9xML_FvwX3zEHD
Axg_L2DwbQbd3Ghx76D6MfgUvlHa4FnIgSBqUavl_LKCU7dBekVhwNhf6j0BkkH43pqP1B-cfs0zz1PwlwX7xrM2dcRq6hrloj3Jw_Jq73qvZreUUBVUCNh-
pNhsaxByvvmAqFkMm92Njoozv_CvfTVbczwxuzXfo0UydJKuzkbT9t3adMN7U-yBl66zpmPEurgbuxqthsTtdo4lPza4FMtIksgWRqelr-h3ilIUKozpQNzP
zAusuERI_a2NejS3Ui6Pl-RKJNheqNle2Jrw3ptEU-ZHU_GUUlGUUfptGiEJilpmVWyzUe_UqumUUlGUUWhMGw_pz3ZleKVleKVlvITvu0Twkcs_Gc-Ch_r4
Vdr9_Dwh4_Hqos1aOrbDycNhhVj6WnlB3l85wydvYkv7Z6KLegU3z9nFiRnIcm-z5J1L7BsDNpuRomgzJLF5ry1twm5wJ1KVlU4pz9WgReJ9nkDJnPFrc2eU
hSU4nu4eKK_PUZTgNzSh9XjRO-QqMq_etJYWCxhtc2eUUjd2NEfvFGNheLVfztlvUZBq-0jkqteze1Vwd5FoyERr-dYzWTSJcNfAVB-dPqmLz_LgJaypVx7x
D3qvUe-QAYvdMNflTggud9-ofUZ9qyl_FUSdztcz6jLp-MGSUArbJz4pUZLighZqe_IAdzITgYTRZszdOoywqVEJgOUUVzcYB3tq_EP33pq_wAcDe7Spdmnk
zARrwbWzzD13JtDwwFaQw9sqOqUlilJGqsFqw3sXDwndDL-M7deThOVUdqTpUkZvVCPUq1jllahMGwyEqqDFmNhezGOzz0o-43rfhIN9A3MM3TNJ4Neowc_w
X4A9Uds2tXc_X1_Gyr_PZUkjdp4-O96nRA1U3-iP8szqS-aQrkiBUXhGu-lBBIEi3BsngUAwUrdqxXyDFZrr03qcVdpMgsIzDL0whTTHUkkN26GjYnvJvdmz
pUanuT7dErjF0NheCTbuanvwQrHFw0KVETlGuwhbABr23ptkzsRqQa0lUgguXlKwHw-l2FXwurF5qUjVATLPUdMqNXize83tUpRV-zwjUx-CGC_dCqgDPONU
lgdYVNEfsjIxdqy3UYQVTamLxmrJnQURR-Atr0PzVnEZ5BqF24Qf-Zf17wgd0RqhaQJjfVfGEgcdsvgFx_S6TlmOFVGgIm-zdj533ptq5Ao7djzywA7d1pq5
ww5NMNheAKmFFR_vq4CFFJ_9UkZfANheLPOUUlqOFVGgImyz7QA7djzy2jP3hxBqqEiPFVJGGqyM7th3EtwC7dgLfOUUmlJGyviFFVJGy_COFVGgImyzRTSJ
UcEFgdszGc_NePFUy_5MxpfqAa0FFQFvNBtr0Zpjs_06lShLyrjFZz9R73ZdRXfyFJt-k3ccfr_GKxsApyBphrlkxxqoTfIDjxhdcy_No_Npvi7sTFFvUZ_v
z4WxhO5zRj0hOrz9TWC7cJ9oGUz5wGtH1hq2x-Jc-zj_7Jtqm3Fu3Bq2Brclm9lZy_Mgi4lJKnbyuEtX-xD_MQ-mKuVf_V6J765t7jyNZzF4CVEm1ovVZlN1
xlReSguDPTApqW6PcEf3q2EJVpRd7-tL1me2KH14GM13mx__WPLW99crtQehF7hcoqmlemdJEwU7UlXwwY4UlXvJRproJpnC3_58SJocsdfakfBHGxlMwJ5z
9nxYkPa_-VI4kIFTByLZEhgZt4_4Oxh3hyMZE1xPOZpJ6zz7SpoQhoOftXrftXsfRaVroIJre-Clof4pOw-_7G00000000000000000003i
}

