sprite $wired_port [96x96/16z] {
xTW5KWL134NHf3gw_mNZ3k6tek-KZznnfVyD001ORPqm5Lfk4QteHuQlYunozPaMF6TQDO9sYCFz_FQ--WpfxMlEaSv-fEiup-Zk2usJtNtqBNhOT3_xy6o_
QO_sAuul-kYZZpxwSRZFJAVwp-e--dos7t__-Wf_mlGPyoVHtPTtBsUbo1TQPv_47lZbljkZDlvznvVxBrlx--Y7tn1wf_cjJ5ditz7wPqvRwek8IXHz5H7b
XVw3ga_FVdZVvHtRsV_8lhx7ntxW_wKQ-fpfkiwhFddkuLGGtq7e3m000BW6
}

