sprite $wired_port [446x446/16z] {
xC6n00000C2WV_x04wa20000000000000000000000000000000000000000001ctxxH58g180p6wliVU4Dbwp2ZHlMdcFbuXMSuhFLOOiTl34_i-8tXQGfF
zDIC9tZu3jR3Hu_UC-PgYkyLK_4ru_4RcQckny7J9gfQJ_JeqQCdUcT4J_JeqQD7ZvxeqQD7J_JeqQD7Zvu5j78zkuFLUXO_c_MM2lNWxUWDHK-bUk3wzKJl
3T7xD3nwgjVBPT6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwBLkmT0hts2YLxr-HgzwTx12Znwz6JnwzEZHeqVFknPwz4Alro_qQlqIUhtH
EpbwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF
7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqSlRNhqii_KfaTldpDjUlJsMLEWH-_dwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyU
FNhqwD6ZHuyUFNhqwD6pKqRFFYUzHMzd4vwUVw7GeqUF7ZrwzEZHeqUF7ZrwzEZHeqVl_nq7yV_Ig1Twz0QZHo-TUYdNeqSlzDuVlInwwTNBzNffrilbUkdM
ozLwgTNRNQgNf41lxegRRouzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7Znwzdea3wqe3m-dz8thqwD6ZHuyUFNhqwD6ZHuyUFNhqJ1oSGO-U
YVJeEPRqwD4paHuznvAUYVJeqQD7Zrx_n7T6ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUg97ZnuzUlH4ZnuzUlJeqQD7ZnuzqQD7ZnuzUg97ZnuzVCM7SZrt9hl-
7I4b8toYHmyVl14zUlZWZUZ1mmTlmWyUFdO5VkmGWljg3uu5000000RvM--SH3K0000000000000000000000000000000000000000000000002
}

