sprite $wired_port [93x93/16z] {
xTY5WO0m44JHZQnC_msVEn0zdrV0nud8roCYehHCpkJ0iiXoBB33SRq29ItA0PCZ2fDb5VvdutL2wem7PgIkU05y6A1TyOgGOGRR46UyUWUTZ3jwJCQpTYZV
TCyPPvnnnXbFLZujVkUBuumdht_qFI-0FajoeUYpw8odWxNPCSShkIiknHz5Cnx-f0olYPhnAizsnHdtE-MWUmUByNig7-3EMhpUYUEurLjvTNb-4YzovuV7
tJxO5p-mAwvsAE-8SwV8PT5vf028HG1C3XasS3cHoh8aeuY8Y6u
}

