sprite $AP_MSR1200 [93x93/16z] {
xTH7OcKX34JHaW2Xsl-2k-sVyoCvwuo8ToYC2I6444888IYM4C6zGYnX_l7nY4SyuX4NayLnKnmfy-8uIsyyug9Tf2TUsCdQuqfBNOofELufwCEw5LTviziM
R1CxKHGg07bN7yTt730AjYMUP0WDCEuyYalUIRk7tOm2FHRkuoU5YcvwaNiLPyM0ofPuPiA0nDmGTySGz-ruOiQGpBGPTySWhrlnHDD1Hjs8Lqweh-DAIyEC
yZAUg1YMlo9Uoxiq7oyxTX4NxjNvk7Cluyvql6D2B8x3ES7ncXGRf_WxGWWXXFy
}

