sprite $AP_MSR4000 [93x93/16z] {
xTW5Ojr038HXiJHUt_-yjUCohQroirzeGd_o6EXli2pBiaWSc4vyJlamzSCqwc2SYaxrOIPEyl5iCC3z-bsvfbv_qgrWrunZUYzUH5THpralKm2YX5sJAP_7
vU0eKS2EQO18mQ-fRwUUCn5oehkyy5WPtS69bgGR4d2cXoHkrGrGccZ_NYAe9P4q0mYrA40J332ro7yVN_4LN_4LjvZHThpskMZ6UT-tcNrhncKVJDzd-tZT
yH2APB9IalIV6_UX3eTijl7nfZyppWNDuE55cmtA-9bnsERfloYUDU1bcsuoU0ZivvwWALHG2ZWPygy-Awvu_rfnjAyLAVOvxyP9RKR_ojlG5L_n5L_n5IT0
gSLGtMUJvWf1Cm84DGGWDEL0cJva1JZTu6WnkaMYy50vFpxr-NlddOIJehfdBV_kgPH8ZsPSy88dfqrIYyP1wDiy8fpfLrcMvGq
}

