sprite $AP_MSR4000 [93x93/16z] {
xC610000082W_QaNgG80000000000000000000000000000000000000001WziiZYO4WX85c0eN-_s3domQqjauEz5qreM725rFOy1Mp7wVwz1N3NXXgReQI
Gi-XYX7O46uyP7ClDOwCExQuoQ5YO1U-FUROPHpNoPOmONvnAf8T9VgeFAwlGnXgaD3Vqv4oyrGYZ_TH3sIu4ffbBv3JIJ-yBy9S6Ce2AT7ht6GY50_H1ULm
4ghc8nu8NTXIpBIB265227Nh2IAuyZ1bg27KoMweVWlyMMT8e4Vd1CL9dP3GN-FWMA9Sw8WG2iLOgFvy5_RkH4bj90RZUAiakxGgtlzrzs34e43lEATjmV_B
PHeyfFmRYSPfXrcNr1_HamdEkZNpjycWoyPEo-JfNT1BXrb1seRUKWOtz6PGulFQ-n9AVAj9evSwKxsPhcpgpUx_0Rtn2thKtk_JMywXH-tfRzFp3RqLFMgF
sliZUhwx7hMdRrTxp3bbG-yNNlVGy--llVMdtkyfx_T-D2AgQj_-igAtQcOfWwPgJxkLsdJJJ25VPtij6q_bivsidclPsAd-4dcvLMF-rxl4tLVh3bYxrXl6
xINABktUq6-HvdPBsk57psmOwrnuf6dvwGfTstU5ui2rdNqQQeKFFFYERPk-sEjdRSydFe6JTxgQT39rQRl0VNrzklaPfewh1nSkrnX3cnu4TIvJp0xKyANF
9-SQtfBF6duNsxnXq3sjoNmJl8nviucBWVT_4pZhzLhj_ByAlGw7Uj-pwnoFfN7Vv80yD0eYtkTDWr1wNnMVzfbnAdBDlg7NfpP1rZPwJkFSk1JfhDc-H8FM
sUNTZGjkgUVzz5Rq9gUVh8iUREYXXnvwwA7t8a4FFVJGGmyzzD133ptqq4EFe8SUUkYXXnvwwA677dheeOSUUkYXXnv13ptqq4CFFVJGGmyzzD133ptqq4CF
FVJGGmyzzD133ptqq4CFFVJGGmyzzD133ptqq4CFFVJGGmyzzD133ptqq4CFFVJGGmyzzD133ptqq4CFFVJGGmyzzD133ptqq4DFpXpqleYOkSU9OsQ2tZmM
SJbx8cO4w4bSUYG4lSTOuZNZGo_n-iJHQzasCuPUZLzQ9T0haKkp27htM3SzGs_ogjUlTQAdhw67NhYTDx6XXvwCqqOszD3pyMNGGmyzzD133ptqq4CFFVJG
GmyzzD133ptqq4CFFVJGGq_CpFH-spmYt4QDslEON1zeUgGUUbxsAbyfvFcWHqM-3ReSfOTUAdYvbGcR77EVB68BFKWFlJoWNczbGYPZMfKpSP0UUbxt4izr
JPu5UN-4smTO58Om-xZJTjT3hzQGbozZj_6GpoFkyd5lzbFzRArNvpX23ps9R_Qo-sOwtg2apc_gbbprT6yzzB9JUdnAU99LI7iepP1YMo1trKClPTpkUl6W
5rAWIftbHc6MNVNGoxr2zAwNL_VKxQgNs_LLiMplgOTUzitn4tfQnFGGFVJiMdhP-kPwEkJxQa_tr4Cl-wRLQOSzwTdG9ptFNL8l7x2l7dgU3_v5FRiEwgvw
w5a2REZ92MiFFOayvgdNPiw9Nfg5_9SFFH7fCkT4JovF2UbSU-YDsRaMVpnJfZT6BMVAZjT3p-zwFZdFQISvpubUt7Czc14kMN2rIQPpI84gf0aIjgyUSqwv
_SpML_ujxmOLEPQRbb2VfFvvxpXSZrL9kNrnzxBUI7D5YzVb4fvZKPxpO3tqncHTo_39kXOvuReMz2GAtcJC9iyOSfmUUl5llDpCJbbCx3QrqIgHOqUkvqHF
zDyK0J5pCtbuZBbPsiqVY1xNCQ2tGz133ptqq4CFFVJGGmyzzD133ptqq4CFFVJGGmyzzD133ptqq9E-UkY5ZTF6jlJuxCi8FslYWjuidJ_x4ZtlfbSSqDDk
UleYUdnQFdeIVHidUiCwyOMWzy3N2W-zjdmoq9liti8kTA0tYtgStivaeDSuwA677dheeOSUUkYXXnvww17qq4CFFVJGGmyzzD133ptqq4CFFVJG8-Zr2Nhe
eOSUUkWHzD133ptqq4CFFVJGGmyzzD133ptqq2FejGjwwA677dheeOSUUkYXXnvwwA677dheeOSUUkYXXnvwwA677dheeOSUUkYXXnvwwA677dheeOSUGGyz
zD133ptqq4CFFVJGGmyzzD133pt1xLbFc-XvwX7nkvuq-OkwvXXw_x1l5qYFnJ0CWEsnuv7kV-3bBMOPVhlHDzo11sgKFEALjVPSyPAym9ZqoZuHZ3adoUzq
l8fppTrL5ITZJat0pSIBSwwY5g_IJ9A3bWB1AuJ2Sqmw7rwyAdLdSTHKajnNXNgJEMkM9iEEbk2DSNytf4RUh4KSk2bFXLS-i2wuN1TwawwV5kyW_VWfZwnH
rpXdptu1teFPsFY837SxWdkiv-EFcRLnWLf7gDsnnzpbbiJOrR8Wnwwv137txhg4JUGBb78RAejgpS6A9yDo6yqBocumFx8_KUasaWAijDVY4QiUy0hx7zyG
Bu3zZrihmezxozYxVGhXu5TmVMMpyQFqLfFqTcjefTTWx2azZRs-DFRgDTBJs5kxz9JUka2_UM-tSqgFMzt6tfxIum-4qciC_3xld9xhywZlWdVUEJjTyBjM
v_UgqevNZMSMXuhp3yvGTcw6CFdUUuEh_Sv9eF4RhFcZdPD4t_-s9tRPkLs8PyRxzkgW00000e9W_zRU500pLs1_bpSfhhQDV3m000000000000000000000
002
}

