sprite $AP_MSR1200 [446x446/16z] {
xTf7TcCn34N1CR3__NPWvs0hG3G4gafZ1_6UD_WXxmG00000000000000000000000000000000000000000000000000000000000000000000000000000
00000000G4HkG4JaRh7amsctv5OHW_Ef9z-ySrLFFTHJJptrK0_rzbCFzTHJJptKGptrr5CFzTHJJptrr4CzzTHJ3_LGRp_rK4yzzTH3FTJRJptKKqyzzL0F
zTHJJptKKqyzzTHJ3_NKKqyzr4Ez_TH3FVNKKm_rK6y_zL1FFVNKGptKKqyzzL1FlVhlQwsdNYmZwwaNtnL_dNhgePvwwgc7UgYtdtgefvvwwg4Uwgcdddge
fvvwwgcd7kgffvvwg8Tw-waNvvjRJxjbR3tjbgdrn5iEgnSJg2VUejveG-k9fzvynzIBN_9iPzVBunrNBrwoNXnNBr_0iVLoCRx-UgQdddmzzSHJxtaLhixZ
fmdrn5l6r5lolvypwiLIpfT_YxS-7rNlilpTq7ZrUlN3wwyNhrZlhRCOKIzgqvjVBqVNct-viADUJAiNvzUxDBCZwkLoSh_BnwVU0ANnvTPwUNSyzRAttlxV
uHM9_dgcbwdUQ8FhYPVnate37L8lq_YwwasUddhYzUHJJxtwrQfyS-kbUX6ZwyatgPvuwhbNNQydNe5w1Ug9rv1FlIBralXfGBrZfgTU5iZNK6_szDIB8-gf
bqNozTTZGBr2FEERK4-zQAXNZ8Tw-waNHzHJBmla6r1FlePwfyTJBmjSDFJKYmlegoUUUeokHsEzUZpKUoZrOYxr0lMwgPV_nOHwEPTwUPby0-jXUrlP7hPd
U-hPddgsX-tjPdlOdksfPtllKg-sYBXWOxtb_dgs5p6tdktrrukMUhQddktb4zQplNnuFUBkVBadNrvVZy85muvyXUjAsrigxUhKctz6wlM_DQcUxM5x3Mnl
Q3xrHkTJxq8_Oa2zYyWMygb7ogUUVE8Lyeaddtfz0RNJJpi0000000000000000000000000000000000000000000000000003WCm
}

