sprite $AP_MSR2000 [93x93/16z] {
xTXNWgim38NX8ycsTFQ_uOjvkeqOD3Ef-jBRduGE-8fIIYbbH8GBZbbi6Z8Qfu53mfqWOT2japU_tOnK93Wxz7OyWEjnRPkWjq6sG_kBP6yREvrs9lJJ8pBy
8fAEDIL3SPLqSc396SZef691I4DAi6F1IEHq-ZeUo6cCDuzNlE8LhxWkIJfk9qWoBcQwOAR9k9fXGJyxlaTqNapcvLlZ0XKLdLSc1ll6-6GmcNMOw7V7LNuk
Fgkw4Prf-UxuNWTalqXDvpyKbv-DhwNZK5jxjjLSnIjUyOfN_EUFjoWfI74Eh0G7CfGqh3IovzgEjK56lyh949pGcU62KwJvXWmFqW_y-OPkttmKcbHqEZ86
m-DsVBvX_CoHV-VKa69jitg3uUcLyWi
}

