sprite $AP_MSR200 [93x93/16z] {
xTJ5eKCn34JH4OnjzL_mPrW554xUt0BEHe1dJ2bblLhqh5wZWS_gHXoRLIKwiHQEpQlGogjU1XSkNBXmuSA5syxEnsFipi_5H_gkoBFnmAxoEN0Z7S60Co-E
mun6q6Zf5ySHwGaw4N5nt1C_U5uSzn5kT89EkpHk4G4BWuK__2fU_q8vTfTN_8hsgFzSk73XmeKB5ovSk5qDHzLafrKBHvVLpN5yFdev7hInrahynhKMSR5M
LVrpiwhcO-F2-zloYAbt
}

