sprite $AP_MSR4000 [96x96/16z] {
xTa7bgGm38JXUj8hMoMu_tcNzUO88oQFliw4ltCoU8DQQwtPuQVp_vfSDNNWEkiwn4fXw31-cemQrxAYeHNz-sIYX0f0Sc2ThCjhylmssIJ7qApsvqzz-z4V
F_KDBFITXr2GqYJNoRhyO_8WEQJnRJBzUZrK4SGbb1JZeUBg4-tID1GCoN4kD54p5PTklg769B_qggyAyK9_tkztl_lTxtxtxTITFhVz7Elz_OgjtFTzTpl1
VR_Jnnb_IttxSURH-n68J7WcaPcFtMS6DWIJdfv8V-H-CkpeHxfjFFfyt7va9jVjTqy-_kqtZoFAT6O4DcwF_loQ0tI018psYFr_wxxL-o__-GnUwRFUX_af
Un-_7xhV_Uvtl_jnlryVHBk_QYXmhhwcI-65keNabyTl7quIdtRysKlZvuF_59eS4XSlZ___qnHX4ceeXKxw2fNxfi_YT0lDG9KVy3_c1xo8rjed
}

