sprite $AP_MSR1200 [93x93/16z] {
xTq7ajiw40HGJW5L0zp_mCxPsZzVbBa2gVSSAZhsjfg07BQT000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000028s0v0H6n7YvuZvVVFHSlC7jkX8kTdRVktoFbPtmxLvXV_k7t4c9-Ds8wKXwH7pFaEvPlIazupIMz8J_UGtWxIm-wXUpj83-bXzwIdUz93
UYknU-YUzAGdFUmUkYSzwKaFkxSQtKDwqfEUtKFta9xqf6VtqBtLI0_fIS_kwHxIGthIitkwX_HM8ptidlHqJtf83xidFTsJ7j9RZTr3zwGdFUbXzz0zwKbF
UjYz5UaUqgj9BzgOiyTJqvDUvBxVx3u_osVkdlHYxFlTZZ6_Q4_idlHoVf5xqyidfYUzyM1wumBfIU-9koUzeNi5hvn8Rprs3xkdUzAJ7dOFkwTxqfFUDTaz
x9xkIKzws3tidkv9JthOlHNPlMWvyigVirtsbRFbV04PLqmlShw6qUEakrT_V-ftmjsB-Khw-LuvDU-dTgdq-dmnSQ7TY_dJ6DVzNBnshhrxTVL6jlYYNVBh
dsUY4PTvvOpnAbSqqOlodJ2zNepvbVpuGBtAxaLUxswxdlYuoEwredhAj_8hPnQ_ddEgP-8IwSKbgrS_ekKbTgzuuBni-KPSOFTQyGnztUUMVe5NpZndzQBr
kpv5yIi-PtenJbczFkPzHYlAjzJkHMmtFxtv21RdsgxxnL_bczkVugrFxxfx8z_Ku-OpIsud4Zdlb-NKHyytlK_tQddpcILEzjI_Gt6vL7olJqYl_1dyZFJo
wOrgBiOyGtgZEFjSVlUskFL16xDq_ExLHl4ISitXwzM9FUQijKExr-_wTRHnsfDww_Vv75En66FMuj3q8cSbepYtNbDzK6fbV2EtGzFRefVX5SVMbxshhkFh
iHsmU_UfJwtN5pjVTWxkNatrYhUapv5UVxtLAq-wwwUt_srAxx4li7lrJzyVS5czUwzOlUAATz7qwf_y2pzsvddIith5NSLQk-SFSTOdfdMxL__vQUKxNNh5
_RJoBPHUVKjh-TRVlTjlJofVEqFtl3LKhF-2wRcVhgzwsxhfkP-k5sJXtNDIhv_UrkrUVJ-jVCkbLz-kaqNvbaildFMAQukLTwzOFIVsbRlNYkE24_jgwTL_
cifBvrWuFVVJzNjbo-vUVSAnVBbmzvpKw-FlikdLvnlBbx5kUjuQggzzrzsz-YVgFVPrk-UFizI7g8NJgq_gohTqUgDuuNHTjkxkrRT2JknBTCzVjzpxFB1i
Ucr-a-rtP56-vwSNEIlqLNSlnYmHYtQlpneZ5aXlR_N8M36zkOFoBR9xEVyV-WBTs_kwIQwNNfi_PB-5XTFBwl_CfUrERxnNUcLshil6kjtRg3_2JvoUz5wg
UxetdfyUNVUEPFUmU-kmUzYzcjsJdjt3xkrdzshvM7gwbxDmP7epOtzwTYzoFZMzsVUdftjzbXxPlTg8tUdPlJwVtBtSdvxkvJpFAoTvVFVk-gv7F92UPywn
zq_FrrgE7F_zkSSZ9mRdlUWvHlcvnxP3b1uzhRjhYQWjTOSdlGlyp7Jl0kcvvvIUxadFxiLMa5wUyTy-PowRNf_VPBkT7x50UkMzwCYUDpxxd2kcT-U5EMrR
jtmrwPqsFZAs5VKnQ_HjJQsEZznM5KNz61bhtyGMFB4iBTeRYEr00000000000000000000000000000000000000000000000000000m4S
}

