sprite $AP_MSR200 [96x96/16z] {
xTG5iWH128DX2AGBxd_WvwxBkkGl6V_6suOffPHd3SkHNprk3NXqhnorkh6vdrqsh3glmvSlNxvy-VBbomV_2BlxPFmQSmz-_B4V3-l7Fdq4p83dcGDSVuA8
Z031_Lx_QmG18emunFEFD0ACLt_FrnyFG0A9DFh-hzz91aWOtqz9VVza_Xfv-F7j_CT_-VBbovSlNxvy-V8RCnwZ8xnwNFdaSchCJszucEqM07zVybTmNwr-
w7sn7yh3-TuFhUlnvQEgFe3hOH5szgbx
}

