sprite $AP_MSR200 [446x446/16z] {
xD550G10302Wvqd_m8inWmhy-W00000000000000000000000000003kQBFhtdZNNMloYl7t5ebsxaB9ZHq8msYXwjzv__Uz452SsGujgQMSBxWo-rIFsIOF
7xnLmSFdHczHCNexP_GCdz5Rr9cZb-lKpjJR6Sy5tVWokQGfjYU75dgd31yzUlJeqQD7ZnuzUlJeqTinUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJe
qQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJe
qQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7BsDfUOKUlR6yb-hHosXG
NgP7RuoUVFJwuyrUe4SlOpi-UhFHflof7hsCFhrSZzwrgBnOZzuQlFeiv8Lwz78jAt-h7ZrwzEZHeqUF7ZrwzEZHeqUFNlwlN2iME-dHIxNlkLRjiOiUlPIl
vlnYhOSUlV5zXUYezfa6UlJ6lM8r9VDwFNgvw-LXCONet6sz7hrh-ZnGpV_b9ZftxQ57BtDVTvzgBG_W2_NepUP-2hrYhPCUlTcSi_5CAbUAjJvwz2RQrAdr
faiVFNhJP4SzUkCdUgFOcYxMerVZrNgDPuzUvlwtqwENgRE97hqQhzPBhzizUlLcSu_xdFJgoQlrkiuUlTmriirpBVJoV9_VfDBpUKvwzUJTXgjurUXAMpsl
peuyZEFyJx6sNe_U-8dUhDXdMprwLmge5A8TzUXTp_5kV5TVFNfNxdZ5McCzdsEe3fzYxNmzdqAXHuyUFNhqwD6ZHuyUFNhqwAsF7hq6qQFdMyNxvnlzwLsR
uD6hsmIFNbsQsT4xEdhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6Z
HuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6Z
HuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqrkF5
PMeIlVFvydIktYn7sysEsg2S7pru_GgzdJ9yEKWlyF3PRkA3X-_dUFZWyMF7Zzq4pAc_SacI9EdKnnrPS1ml3zvhh_lb3zNWlPnlrIDjFRrUBwU-A4TFz4IF
7ZrweYTwzEZH4prwzEY9dkZHeqTFz4HlHeyUFT6ZHu-Uw8aUFNhqv5CeUeDhFilmb3VOvhN4aoH9aYH9aYH9aYH9qhy
}

