sprite $AP_MSR2000 [446x446/16z] {
xC610000082W_QaNgG8000000000000000000000000000000000000000000000c7txmCqTXc40B8401Tt_m6zsEd6wM_CtF-nW2Q13PtuMCrOFY8nb9DY3
ul_v3EmJXLX5JUSpz4J64hBw7CAoUgAMY2yvdy_fiQUuNcqUvtDlBjoTx3btP_K5BjphtJxviY_bojNWdOzzYOlF1nVdmkbblsu-5sVnJgrJJRYOp-dXh8Mm
JdhiHyD1fpS9gbPCZyV2S7eF64vFXTFJv_ISdjDpUaxFwVcE8PtUb_7TEZPCBm4UL3-goS4VzF9yF0KWutQ0hDvAaNah_RYdqiylKRqj8gJfDgRpo-hjKNd3
iuBmHojML6vDet9uHkNmZF9x7ecuVGbM7q4vl29Y7uaIZWyzGCPcahBFpSRAJF-Ps4sbtlG_mad5xeJ3Er_6UZENVzIGwaxup7j4jGiNpi9pVD0g2yRsIceR
eJUz-KQIIcij8un2NOHXLilIAIEEcxHHvogEuwbda5dGMLVf-RAJQklCg9XUJFXNAQ7qB0NJOzonVl2RlJlHSHE80J0SsnA8zt_WtgqLIdetuCttznwLrIWV
JAw9TesvIpozhUZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7Zrwz4IF7ZrwzEZHeqUF7ZrwzEZH
eqUFdkYDYHuzUlJeqHCzUlJeqQD7ZnuzUlJeqQD7ZnuzUg97ZnuzUlJcHuyUFNhqwD6Z5tdzWju3kvfGqZieQqf1RnvUHsymNYMzkw9gAX-zoBbwzB9cbK5l
tANNqUkYffLlGeyUlTpTB1Sj1-lH2thqJeyUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6Z5n5nCFZBOt6M7ht8_7H4ndxmyLYNcH_7yWmzUd5uK0_6mLWUGEJp
zUXb7cqpoLySY-eodgn7Bmvt2UN1hhse0-OT_HFrwFKX6Pbz0SNNhn1xqO-IkH_BhsFnP3rwaPKPTpots3dUxiVos_zhoFxRS_KyQhaxEfgYLHwCHO_52Nhq
khrUFDIBWx5RVUmiFNgz8lOYsLBHelttrclnC_JeVRKur8jVrCjpzUZTfkdHwsCRelK-IaNjzV8wUlIQvzVrwXfwzA8FcgP7Brfisif9B_gGMOzQw3NUE3rw
lMpEqwEtl_9-uvMosBzI5a_LezTulwwN1tfnnkkSz7hPxFRl4Et-rhZdlKD4h_4gknPzy2mmwrwlUkovUlIozltEpeYusCu8Ul5BkvBYahkIw1tj_diy5hd3
UwwU-xtCoiflF-zOiaqUZdqQF64tBhrTTiBx50ezUlJ-H_JeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7Bse4NzBptHEla-yxI-ysMOzU35uuwTro
i1wz68P7R-u35thxOZ0UlLiCnAFNPKwmYnkzmoBowaNSw4sE7ZrwzEZHeqUF7ZrwzEY97ZrwzEZHeqUF7ZrwzEZHeqUF7ZtHcnCzUlJeqQCdUlJeqQD7Znuz
UlJeqQD7ZnuzUlH4RqxqwD6ZHu-UwD6ZHuyUFNhqwD6ZHuyUFNhqwD4JlJdHeqUF7ZrweaUF7ZrwzEZHeqUF7ZrwzEZHeqTFz2uRFNhqwD6ZLp_MenTpzUYj
K_GsQb-gSNgzI6YPeXVhZ-wWwIt3PgfOv-drAk7I6xCUrURYko_MEITqh8CVjpYVr_l9Qji6FP2h_MpTwtMpphKrh9kprgBbVhuUidGnOSA3-TmMouRl26-j
suHMV9-gaJT4RNUjzP9siRyPPZrAxfPusGklgzjKlcsD5xVRQlBajtMfU8sgbksxbh5FKblm9TgsqNXxFYt3LtvuhZvuJoiMS8qtBtoZNwkeb_TROlRJLeic
FzVTMTMol21TrNov5bnVIEvDlYnVkvQjMuu7pslTkiCPruDUSClESlJcxXfNszCVB_yPANhqwD6ZHuzUVEk2Ul6rsZfwtVgjxMfwnvFRw1rrGRrkXXwzelUJ
rWlhnT-zVq1l6JmvIsTTS6U0ZoPsouNFxbX_F3dLbS_k-D7as7taMo-ydMUnRlxXli4bBhohQk7MVkk1tNLFhhLSUE_RWmC2000G143_NtSZ5KW700000000
0000000000300G
}

