sprite $AP_MSR2000 [446x446/16z] {
xD6t0O0m40ImyiF-0zC3TkqWJN2Xrm8000000000000000000000000000000000000000000000a5-zb74-ilxqCcgSZnheHUGu7pMqV3vgGhx5PKsazzPM
K_8jBHTVf-RoOU--jkFMOIY0FgGTuVy_-BwDh1jOJhD4pEnpQ-26nKqmHPnbU6VHtyfvPZrwMRkzBV3ECaIFNb-yDItKcHwzpDEZLqFqGg_JQwfcZvxPesVs
p1uzi-VtU_JeUPhmb0cwsM5tQ_XjhvsOEtxB3nu-WySF7ZvcRmBFz3aryVtvw7b1szJHgnT9gcPFdvkFcRjzuyPuag4RE8FjxE5cp_6RiX1XzyYuuSjlT8pF
w0rQZSdjuikiUs8oQZTdi9xjVCj1GS_1wJJAqD6peVjE9S-YP_YYKJ_nNVQAF7aQFNn-WgP7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7
ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJe2JrwzEZHeqUF7ZrwzEZHeqUF7ZrwGczEwD6ZHuyUFQ57ZnuzUlJeqQD7ZnuzUlJeqQD7J-ZHeqUF7htveKUF7Zrw
zEZHovVL4thlvCk8X5uxTrD2hncyEQ7Nu0tbevV1UlI-30kz1czE1kZHexSO7ZrwUG8zUlJId4ahvbIFtZaUFNhqwD6ZHuyUFNhqwD6ZHuyUFNhqwD6ZHuyU
FNhfFkBTMlV1T-dHwpucUwrvntGVV8CUlI-7DCLqdxshNQX7hxzxtHJJlMT7Vx4UlI-ztZ7TUwRxw9lrw7rvKwn6T7_ZNij5UlJwbQnKVjAhffQgargkrQEN
nmh-NwMhfQhIrFPtl5AFNgLo7CETvxIMDyhNwT7himDyQLH-jKQF7hq_nHkeHo-ZzEZrU0Frw7qPfKUlnnkXHw_76w57hyURg-VfRFscNkxKezVZDIfvMyiA
UlHwl2b_Iaslnyl94w9Q-WcHfxDVzkAECkNfBBtPDoFerTXRIVH-vqPWBNOZaDwOsxZqKfNzlwcg_EvD-0S2FQz2eKUF7ZrwzEZHeqUF7ZrwzEZHeqUF7Zrw
zEZHeqUF7ZrwzEZHy_ttwD6Zv_lEqgDNa_NePHfU1klHAtfp-OhUCPFrwDLaF7er6OzUPOPTw4qEFNhqwD6ZHuyUFNhqwD4JUlJeqQD7ZnuzUlJeqQD7Znuz
UlI4tfZGeqUF7ZrwGeyUFNhqwD6ZHuyUFNhqwD6ZHu-Uq9iJUlJeqQD7J-ZHeqUF7ZrwzEZHeqUF7ZrwzEZH4tfpGeyUFNhqw0azUlJeqQD7ZnuzUlJeqQD7
ZnuzUaAF7ZrwzEZHq-SreISPh2VRC3ryz1oSEhMZVryFNwytgDLKoJPlzWnVloAQTN3USb0OlOng5z_Mw8ti5zuseE71VDOY-DvPYMrGq_WQl1bTyylKLSZs
KmpUd3N8zj9-_G9aviQJ7WyVF7pmVfyF7Zvu-E3rlswMkZp63vxnIyRIyQlnITWD1umZSthoGYENUhhac3firiTR3okHkz8trnQFUSbdO2VLNFklfeq7YJi3
lTDYBsJfeVA17hrQMAy6wz5BhqUlpwhDqQFt-w57ZnwzFBCUlGnkpj5PA-jL6RvrTxVH-oWhx-xy3Hw-fKy6TETyTNjoFdcIPENr2RmFal_QdGC2000G143_
NtSZ5HOG6GO000000000000000000E
}

