sprite $175 [446x446/16z] {
xC6n00000C2WV_x04wa20000000000000000000000000000000000000000000000000000000009Yz-q1ssmQZC3gL_mNslz_q5mgADT5Z2W7et2cfrl3J
4KXtBp6pzhZqUvRsiEflpTAULrDSHVhVpggr2VXo_IhWFIytuOthTkLjQxN8LJXw4tpiswMhiFPYMVSguBLCS0EuUkkaLpSzzTw_TLgcqEjNz2prz3xbhhCt
QhsbP_NyDjsirvVJerVqdBqfvknbGprdppBirCllE_No_-trLRJyOFqpLzKsMVc6-TeBkwLNORVq-WUixRiuUDCENxMzL_2Mdjkcc-SQUDdlRbAVWLVPeYhv
YDEtxqSq-p_wQklRoy9n-fAz3rzj_cJOcszest1vBCo-Hw_s_mPHENeBwxLjozAttQwHjVtH6olZKxbofgpPHg_wpgijzUf3zDA-5e-zXVMQvu5GKK95qQCd
QfxHeoTAg2YXzEW95ILK53rweeIA4YgA7ZrHGaK9fKTFg2YXeeJI4oLKb51HzEY94YfAA3rwGaK95IMKdYYXeeIAeaTFb51HGkdH4ofAg2YXz4G95ILK53rw
eeIA4agFdb1HGaK9fIUgZZbM-LuelUIOQVb6ABtKCTVg_L1wntJBcw7qSaouq5lgv8qhUciTlN6XjzJNMCOLlRMEthXlXjAh-tTHZrxr2NPHZrwdHuyUFNhq
9XmzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7hxv-wbSTutgESvbGZrwEuwLUpQr7ByTBlPfSZruzu2IZNkRMerS3JduJojTh_V6V9_rQ2xsyE5fV_sP2FNhZ
5ygfDxpKduf9PjIZrtFa3wFd-saD13MB7hrnWzxuBuvpDQKUlPnwmz4RzOvQGi_PEr-a7lbMq7Fsyl0YgVIUMaFFsHl_SQIONy_PomzU8vFhENl3FzMB7uMO
Mi_P6u_PaVJUaqMUUyxU-0_dvjTpziQZbsEb7sDmziQdtlpVrq8lzQoNuRyChpc77hrnoOk_hr_NtnmzFwUC7ZrwzEZHeqUF7ZrwzEZHeqUF7Zrwz6fXFNf7
PJazUfEEtZlpfsdSC7-I3Rrv3r_VKC-Vu4PlVhxgdTwoVA7tZQZ5yEYDorgtJNhZagefw2gTtWnHGaNHeoTAg2YXzEW95ILKb51weeIA4YgA7ZrHGaK9fKTF
g2YXeeJI4oLKb51HzEY94YfAA3rwGaK95IMKdYYXeeIAeaTFb51HGkdH4ofAg2YXzEW95ILK53rweeIA4agF7ZrHGaK9fKTFg2YXeeJI4oLKb51HzEY94YfA
ABrihfSFqQk-p-f2rTgTUpuFocDl_ooFFGy-UhfyHhDmcCYqXG-VnjgVhvshZJ-OrNTSjOsV3hKoduzdspglsjwFXhJ7xOoN7VMgxNhyzYmRbpQkiikdSjpE
to0Q5qaBjUw_z6rNRVTLttY1XyzjywQbshRh7x0uU2ilOUVyiRjlLMsFLVNqJro6dPpvVUrhbVzlhw-YvI_hzlBdifvwjzpKr_lPZFIAdhCtnPozV92UiqUl
JQ7Nlg5dcUAxxdFj-p5jIprwcUA7aAjV6RuiS1LMKzoohjquBNFSigvTXMMAMrQk7JshAPutkNWLLbEyRKlZ-VKuAO-ydzk3Om400020GVxMWzXRRG000000
000000000000000000000000000001
}

