sprite $175 [96x96/16z] {
xTYvikmW38JXRb3RwlT_uBiaPp_KQ1WoVLLERFEpXE35MckjjTP24l4BIR6Pzp-_DUH_9dRSdjF2pz8C1vv6CirfyMVl7r57kK2ivksy7vOsQ_bqe22SH85A
-Vg0D6heH84JHVdgVlUxt_tkSwnmjp-kDMxshsiiw1gxVM5XT5yVQXpZ_yCp_I6IedXg_I8eI3pNrm26Zfq_11vO_w-whqihsttgMX4s-XNTxtxtkz_z-j_r
5TsUA9aM2kWa2fWcAcHhFanse2PSaO4gpeX8XvpnCplaE_wPn7DkaulxIKm7TiYPl_PlPsxscRQv-9Z40Qsrrlu2
}

