sprite $175 [446x446/16z] {
xC610000082W_QaNgG8000000000000000000000000000000000000000000000000000000000cBqxst9SXQ4mZBJ4Nl3-3to6T9DoYhfmSWQ3_E-UQuHy
5ZBj35k443zcYL4OA2SJQiT8ji8e79WJCVNlkOBlmr60DoSMm3in2XBzXyXs60MnFdBbOU_jar4G_Qod3KP1lArmkzciz_dIIUdrPYiSGzqHEgMdUEJvx_zL
BwPHeFVEaZNsnd69tXX5yr6BR-cXLrRGKzbE3xrv5EXHUnU4saEFshiyzBqe8yJCGwyPDrCRRnXw-ZypHj5FZIBkUEtMG-evqgIus_NpdYcjoUvZr_Fb9dUU
SFMSKUJ7YzQpfYd_fY1pPE3H_FQu_DhsJt-DReBN9FUoUyn3RLeyqv-moDDCqr_yb7-hqCBoJYqZdhN3ecc9rvLc2VKY9zw8ddnDgJSBaVnE_CrBjcZVjiuC
JVd_FoBl52FniZBYBMjlqBwh2fEqwS40kJT5IHTEbSnHpgNp9e_aYDnwpLBhMSkun9XkyWX6PTJpkzoXLHllYz0BzD133ptqq4CFFVJGGmyzzD133ptqq4CF
FVJGGmyzzD133ptqq4CFlRH13ptqq4CFFVJGGmyzzD133ptqq4CFFVJGGmyzzD133ptqq4CFFVJGGmyzzD133ptqq4CFFVJGGmyzzD133ptqq4CFFVJGGmyz
zD133ptqq4FFF5Q8szjww7bKLIsHwc_feMTLAoNil1vwNhLMwcazz5pB9T2B_IflfDevFVH22oRGs_2CPQGQUczslNfzfcq3UkSMpkfsVPwZUKyFFLjYy1_f
eLVBUq4FFVJGGq_e_H-Xzj133ptqw7leKNleeOSUUlGzzAWzzD133ptw7dhK7deMjSRuoo5UIdqcbjH3pwkacE-LLhsOdbbIZxuNLJ_hoHRNe_OiZZWUuOyV
yNZJGw_-VjjQUkYDQgjpQOKa_wKNgvwreEUImYSZVtoPrVNeUw7uHJYNtlXpNJtEERtCUbQbQh-_PFmTjnNrq2lVzGRQ2u72bjP3Rowz4dgcse9wxFTclNZ-
sw96nDWHxg17xTN3RMvV-uhrzT2RCSSEmXVMGsyklUbjg-lHz_o7KnHRVkMazkOo6t_67dhe-V4hr1h-L-fGM5mFlJZ-esvrXOY-zwWpc_N2LjNZdX4Hpqut
_ZxUK__AUDDkUjmhoVvEEHVqk4yPVGyzQWyzzD13Zxw77hM77dheeKVVGu_QGmyzz6GRww4NA_35Xteyet_rwrDvHdzUJMFHy4eswArVVBwl7g_WLaj1xsHY
nQw7tgvyWmEz_Lv1iGuDzCx6ezOLv6eDAoFedOwPBn0RTkWb27eB1ptqq4CFFVJGGmyzzD133ptqq4CFFVJGGmyzzD133ptqq4CFFVJGGmyzzD133ptqq4CF
FVJGGmyzzD133ptqq4CFFVJGGmyzzD133ptqq4CFFVJGGmyzzD133ptqq4CFFVJGGmyzzD133ptqq4CFFVJGGmyzzD133ptqq4CFFVJGGmyzzD133ptqb5nF
GyzAdfY6dgL4c-V9CRbVlAVMwt6BjjU3WtA_j35DPrxx7gEjv8esB3ucEH-MaR_hTSzwBjtbIV7yQugMzy2KPTthZKJ2oINdops_w9cdPsevIsz41pvFZAVi
ZQ6tLELdqV8kB2FHZdnXQUpKHpBlYA8V8uMNtUCkjNx8mCjSVIDjz_HlKSaR6tnP8okP4wdnmahkkDBQjIZfOsgPo39iOYa_HRbB8bdzjSakTpoa36vZttgt
cBc7NZ8AikcHBr_z3_bm5EvcXKptXZniB-pAKNZRveevUYMJ7hKNw55x2uI-bphK7dg-Wbvp-jvdzqMEHtI9NaoZEA-7tfnc5pnKT4f3xwFRJHSiuF_MbLUA
JpkCWbZ_CN7X4d1-52JQ2ajMVBPm4YsnPEcZqYCMI_GRVJOAOb8xH56kYB-CGd9WJiRya2L6GSiZVxO7nm800000W_ojvx2xUW0000000000000000000000
00000000000000W
}

