sprite $274_B [96x96/16z] {
xTTLaiGm38JXbjKbkUz_uCLXTYPUrFUS-iC6_0Ebb59AAQMKKfXTT_Ka5l4kgTybISGuIj4UFXAZcjJmg1GnAELud3Hy-Oa150VQ2zxPoEM4CgM64LqZZnw8
mNx-gtvhER4VUZUl3qRqMVsDK6u4P_GfxVcw_OtDAsuXSKO_rFP3wOG-vVZawXFwBc8ZnAbzIEltcm97Dp2ntvHJ-qZTyMGVsQ-JUkTJ_O67ysFxTcJrFkFO
slqukcJxbNqpcDcqldcOat2kqNVnxFaGeDcqFWqWmcEDFi_w7ZGtm2PS_upl9n_iAx74yHehUEIWJmMMyAFhCXwnuvtQ8g5iZ-nsY8L22iSjdb9WCNRTqntF
yCXRml7xb59AUGK
}

