sprite $274_B [446x446/16z] {
xC610000082W_QaNgG80000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000cBqp
qNPJXw6e9NHOylz_y9jISlKeNGqNLf7iiz_OERaxMmOo-3IIdNO8KGFWsG5WAYr23ExUQ-3kRZy44Z7lzN3JHXJUQ-AmDZS2xtLndzgVUIyEPDwXsUlZO7Y5
SPSPLxp3Gt7avl34ncrwUGvJaPOT4JMuJwxFT-gqbGBxsp-lF8TKNBMz1p3fs7J824TTrcO1KPwsii0dNFjic0L3vzEd7kGDj0QuJ3OtmNjJ3AjR7lM9HtbZ
wNEPPsw2Twdk8OiFE4wwJ9AUQni63V7DiUg1Zycw1vmkV52MmmUzB6W-mM6dnlJ6Z4yd69neWu4Hxvae8l4HEcXyteO1xlq87tX5r-5VyOU15mKRwE5uZBNX
aC7c2lgUeSzfVIXxwh-s9mDV0tGPExsEDY0sr61nsXjX5V-2zkfTLf6D4mVLbTTv6ycUj0qT-bgWUEN9GdkqLtzoqXxRepssHtjiZ-tH7jkZFRP7UsoFxT4U
swCzjiVsQ8_jqHxRepss1zr0ENjih_j6Ptjbw0UmlIfuONjiJzbUPS3s2YFEzYhZRAyovcolCA9gxx_0zWgZR6y4UrPubqcsvvy0G3CfP7idoRJ99DihlqSX
spiFj5fxj1TnONkFuz_NPsplQL1uYr2sr-2zrlHaUn4nRBoju1ZtlJvbUsdutPqLDVYkFhPNwbFPp5FgOtluR0SAyuJ3a-tPP_QQe4PzCgSzE_DPaM1xEGX2
Hj0djFTxVMvihzn70NkkfO_juOmzzUopKsdl8ttQyi3sfDu6eMnFOqlrDmWLsljiThfMQu_scYMCZ-rPlGr2sTxv1wjcZazex-C35olN7kr9mjtQsLxf-DZU
-VZ0zWfSAYjpsAcpsfCHuXFQgnWVsoiU7zix7r_B0Tkh71_RgnmVspk3fJfkONlQYexEy-rnfrQaZ4zex-IJx5QkFTeJxnicQQ2z3x6U4jhx32ziZ_Qii3tQ
Q-XvCThxuC0bAIwqLrSV6krLrUTejFS1OYXN7kr5r1xb7PnjQAEzAdY1u6YFzcYl1BH7UxH7UxH7UxH7UxH7UxH7UxH7UxH7UtAHn-pHdkY2gopoY3tQasMz
0UWJzcXlMUz1_xmzsjFr9fO_Ru_siDw5F6IFzh1SOHkTZzYZFKYxmlAaFTfRsYMKzcYlBBHN6Teh1UtHdirbZv_N4g4zsgCzsYiDxT4UxT6UBl-Wylh_IF2Z
gfBF7kqfuXDsw_zeyRhqaiqUxSNNIIo_jAThIdkqXzUpVV_zHtVs47vI8dkq5qnWsGJ5WRe4FykQrHxNFOahMsmIyfO5shjpo-xRx4KZo_4tiQvAUma-JFRG
NfoK6o6zPLqNoMYFzg8Go3wzRMvAPdkq9_ZvI5I-vcRBQ8_sujp4VjLxpysMqHxjHNcBn9-qoT4V0pMVFTgBvGLvylwsu6KfNtkq5-NjlqF3UJhM5z1azcWl
Ziru_1dihRHtvsxvUf-zE3QZplV_HhBOexqeJ-N5r-b22zowxj6UtsTFruY6zFBROtlBp_PmP2QZFTfJOFtwMr_VWuDhCK0wUxGdgk7l7z-ZqWAtlww5zlYQ
CfxlqHxjdHiUjETIt9vE_ReMhMaFj5Vu_NjXTipytbalO8_R1E_nC7eksCCpzgm7UpEFJboojpxpQJiUbkqPaRuXbxxoIxk0lFhLRnznUfiKlngVhZS1kN3R
9oNiODU-nsEVy6XzGzkaY5yTFyj3wSLRFYteEVJfzs-ujSRulZixzGPzE3ytFMpGFI_Mh-fhYgjhtda1plHsNuUkbIO6LxtzLq9vawk1_iQjshX0QzHNQHNH
A4_Qz7ZG1otmiPGRBer8rETeYH7uuQIWlWtN0kStOPKctYEmbX0n_q0Uw-lka9OBXVT079j4q7Su98j12UeEooFmliSTiCTnzC3nsapKUnLSsW7ChmB7KvCe
UdwWZNnmL9w0SoiUCVUywkZknAbLBXnqT-84AvawQPz2nE1PWBNp4D6_suCF0W106010sh_qMkm2zVxh1m00000000000000000000000000000000000000
W
}

