sprite $274_A [93x93/16z] {
xTO5bkmm34JH4bXIxN_1WnuAT-1ZtW9kGye-mU_gxkxkxkxkxauZft8SJuAiYPZ7wKQcOQBZU2EhqsVZNYm7hi2jo0QSZtTQS0MkIKQdJyObo5Hy9UOjth81
VfJMLloi3k4oM9ycMU6gybezW8kzDxi-oPzdw16yyJsVfj7w7xGJR-xUs2Q7hVd-1ybNLI8zfdmsWyihmZQrFYS3yEHwbRQ0Zsb9ba6Ap5Yjo9GvF8R3Xf4X
htQJZVCjcS67j0Jf09AEZJbp1YyRtYif08o1pGLj2eUE1kg0cIK5cnFc61-cnL8W-c7VNd8LRtthB7Cc7YWeoxWaI_4Q0s2SYJkxTphUpyqrU1zWZnLn7Xwa
__o7U1QkDReTH9ZMamDu7-0mVXMo4-_dPfnQOzXBdgJjmuLic4uOdxUaxiALRVtjn5Ydu_L91lqwN5XduqcWr-ZNuS8w6G_YisGjnH6U4P4RSSabcHNuaVCz
My7NQrGCa_Tm2TxRZCkFpiKzshV2JiNR3y6EulbhSHMe2kGANBI9kgBfSRngzBSuq61s2Uu2DN7t4_0SuEekhwZA2VZ6jGHbpyvr4rx4uodpE_VpX2hGCmPs
58prkqL9mPwIgLZEISE-WineyqLrUrSQNAoQu4YYymd-ykxkxkwU0G
}

