sprite $274_A [96x96/16z] {
xTU7SkKm28LXG6U0y_uFdAx9YhrnYxnLNthxXyb5ZYDRbcLPbcLP5dC-b3A3Efd-02aJE9cGHt927wK-juyaUtr-loNfAZVrBKfzQj-ST1EPsAyhETGDy7TM
-XVhJJurvwSO-XDM4accezcRStrxfsEjr8S7ubJV-66ewSOIdUitXh_etsYbBkYpN-v3NWJxh4DDWuG8F7z0ZkzsZks-EHacPNWLy4NkObcvqZUlNrSdKNv3
UmSIN_R9HBtsX8aqfib1bcnVz6jT-Z19ayEC-RZVK2Vv6BlHvGGd7lKh9_rzMKcJ4uo-txTyVwIJ4QJA6SpjVj_A_hr1EILt-lr8zRvFxeCCbRdzUgGwfchC
xBSS3bFmnSI-SzmkTVUSrEz7gd9wrxxLHn--zZ-bNUlt8xLv4wBcf5tjnyQDLFGZ358lz-LBpZus63VqmTwNOBkZtyhrVNOVqWLjQhyUGT1lxKioDx7scVw2
H_iMMt5cul7zOHxid_ztGD_8v7vreg-3wNqVONf_6DdyZ-_Zv_xhizxNDxW1461ElzNv1I9GkwqF4uNudBxJIXyEXOdQfFdjuFumRzrFPSXvTIp7g2pQQVMF
Yc6WqXcfSadGPPSb8TTea33PeCr9o6NWhcpo7V3Ou6uomR8io_8C
}

