sprite $274_B [93x93/16z] {
xTT50kGm34JH4bcg-nzu69hZJfn1lNr-s82_MckjjTPQQwt9jhtbA6whsDDtid9ioI9zHxiCCwmOU8-o19EIXhSa5RE4XMdYxapC2zfqcvyvvYa3avnXWuPv
mZ4VDtZ7Rnbpr5bn9CbZyUqlvYiz8_v3nUeup9F-MHHpTHm8AhuOpELne-5xtLV7zKTIYh8y7XVVpkAuN1IBk-FRHmJzlBYGzSgXEEnLcLMwBxwD2U1FZikb
jN4PSMLjF71fo8dnE1oFcxWeH1MGC-AcfXhGE1xNkpXCeGPR4lURk1hWC0yv7BUxkBl10DZInxB-Qm5hwZit1jvrEtN6k1GRsuHDGjhss38ui8UI8NX9aebz
jCYC5v9CmLvUV2aDHuY-W6cjjTO-0W
}

