sprite $274_A [93x93/16z] {
xC610000082W_QaNgG80000000000000000000000000000000000000000000000000000000000000cBrpMt8Snu4eCn2uyFy_UE_hw8MhO7CB9P6UFFCy
tQquJeWG8Ue388GGY5q4HZD4BEOr_ysGqGc1nxmE7tqGw9mnBmIZ3RgBUIsXemSYCI-dnHv1SdTIzkZEP-BOx76X6Q6_IrVsYDXCk63yBZtP8x18xa8nVfkE
x15euUwqxD6T9NUxPezyuKwIl4spHyGZkVFaxfpiiS5p6OaziqUUtKNA7RF79g4xUqIUtTb8d9CzDdWo4djcZnGDtcdPuovGU79tJlPumqiDtW7POtEUceG3
iyS6pxLmn-onmUlC7jtbXURssIEGcGYJaTWoUmJgCv7SxPizkeie6hoZiiTTeF2KEsQFesBTsIFYHPF0x75KxABiqTrCxhRD7j4e5YixPuz0ecZEjyuUAKR5
JiiUdsX6sWKw87jiy3fp1m3oBwn2y8Fi4UdV1H9HDNVt-GQERRB7zqcWxX5p0Vj_iqTtip5tW5ZCLIBmW-mnTpsxGD12NGcOlNN4PzkxG12lrDN8ZTdZBb0g
c0TbZpi9q29sMsUFesAmADn52RFtW-QynTty1dStC_ad65yZTsIF2yqSuOoR2e3n0lbvzZXkP6Xq5-5IU6lD7dCNBdqrCxnwQjcVFUu2eIrtaTGnUxtkeikT
n4n4_BTWCdjuoLW5pxdJqU0kxS8pUr1_XKd3g5ZVXj8ZmymUVBucqDMSj_uCc3s9tYFjeNtZHlB27RDdStQ6JxtD7Qnmn-ojs9Ctm_8yRlI3SSycTyoUN7mY
7BnnW8BPk_QW3etEILrcxyfHCNWibLzcB-mhFDcxPDn8Ol5J5inUb9SSqjILhRUBZd6xlVXSUzfwgfZu6mSb0Uiyx0dUvv4zB7A6FOXtlWi4hLUQ456pcDlZ
PYB0VlRgoRoGliTs-SyIzPZd4Eug-zeJxtqNIACem69nYBgy-R-BlNhSA5pnIy63s9mnpqIndJsnc0b1uykqXlIN7KmOjhBN_owGHMevqbzsDg7OnLw_ko75
7KzYVW0kUzY3Thzq3lq-UCDYVWGXEzYJQFukK0vNIBd95n6ksnCHp_NfRdkGzfCOeSLJJJmDywfW784yTwSkjzeJxxuTvvunf7ni9XW70T7ypFO-Ux3eTWUD
Ol43Jqy2ZdznCN2JFUbtD-1LPK7aK9x_Fa3W3djgqNyobTHrnOhd5SU-0sSts9j5WzVMeEUddgS7x-kknswmbyZk-eCt98wLLr-itcpF1IrtWweoef1tjhx0
dVP2Ee8NBneXA-GThi_ki-Sf-4rzGaQYa7UwFht9NYZQrc2b7YiEw3XUN-06UptkKEqdFD_rR7mCbi9tWRtkFKRuEuNOqy_qUF9LNMtFP3GWIPwy-6jrd4fL
KK8liOSewblB3dfTOtny59gwssvx6OcqWzVLirPfHfo-P6cui0vxGzGikUjiq6lBZd4iTL6nTdlzb7jrXURFFUJcSUSxobuzuYvgVn9fQVQ9uPE3xA5gq65H
d7NmMKWgdIVOawY2bzsbTk4pror-WBqgUFbwdf4Fj6Vfhh2xFV7oy12Vtp8-44s_uHliDJReChybnjdKDv4Jx4cyU38MS-vvswCzwAiz2lpLxE4KU_MaRHvx
YWT_3NkshRqwUFLDl3vOvNpsjfUNAxKBVLw9Olu7VBGztzbUjODUsnitssFsn8eNW_QpHtlrHju1zbWvYmRz27lCddZn0OszxT6U5YTtx6sFbHDHDEXRssFs
K0HlHtkqLs_a7M2FbRDeq3Urn-pLmSCum1xj5IFk9zXZvSmDkernW3rchzX1Fy4UxK6A4VUzxR5oejX1tzCUirU_WxvkJ-M_QASzskll4-f1weliiN9Av4dR
HN2NFMOl1q_7EjveZ_Rw6_GQwRJ7ojc_NAdnHdlCNd_mQc1NswEz8dYhm3ljiNBsD-Wrul4dlscFsOEqVwT5_gJN7ktL8-uOlVoUFLPEYMBWhzVUMumQPg-U
j6rdhX1c8g2zlZwXtrvDk0ehPsE3tc-l9aB0x3NkeFVRgma1xJMCk5zbB-F2ojamQTjpVUk4WzbR-YfiFnAp8NwqTq6VKDVeTK9OEPS-EjCF7aWy_j9dHENv
8vDXp5vzSiTrm5_-L4LoPQ2zXWQzXNVEr8FObuSiiN9gt5kMDDahZcNAzpvcprBmzZqHKJtfeps9r2TiVAQUnFykh5Wv9Qt5RxIdInCopkpbBzdS0PAz4ljo
vK9xeJYWqi2-g1Iid25d_5OHwTR7xDriRya6lBzsqbv_mzV_XSb-M3bN1mGrhJjFoXxjmRTUkD1UZSGs2nTMJYolGdIRJ-4mUsFP7dPSkD3UUlZqkCf9UsFV
y35xhv7OB7oqPojNTVUoavKpcnWhuTjZsSdiQMtldE_jqzxwGI9oJkMalNoGICHvsQCzsUzf9-sjXs_gUPMJzZHrxCpU1fiCPpKDj8TaOVrPzKcLa_RoU22E
onxjuM7F3h97UpbyOR8Fh9pBRr37FancxpryRWZjBOHlKrWvNsC7Pu_siA--a5PxzXL-WBqpzTdeiLTokBq1ZTWnUJPexpr_xjl9qq5xRmB8hVZZ0Xw0zWuW
RN6re-_P0-qr3CMr8t5PQydizMDnrVAMsVi5nFm5-dVspaJNKHo8ehxbSc7-_uDdeOTtYPZC4gDGoFVqbaqjdavEcQmWcpsrHr8Vya3jvKVjFH-r9tjgJ_RK
dkofFRKdUnZdflPa3-OnYjijxSaUFAx0RsXFzYXl4Fj-Ux9dSHNuUdkovt4LTbDxikSsWjFU3Ut9NXdZplPapyiOQa_jJOFQapsrf_RKdjgRaAhs7Wn_-0dQ
axtSxScUsbDxU6fxQi_C_y2mdNu1FtPv9bDxQiyyVk4ulNQBuwk2dguzjMT1yCuUg3nHUseFMrLkVrqC_u4tsvocQa_jyGB7tc0fs3dQyqZQdjOzW7tnqkDP
HBYhlL7utVpNjKTTf-NGU8svshl-E4JZxRtPg_G81q_YklPahrtVdjF7gqlxynJoj2Tx_hSNErvTScwMdEsfFROMU3rxI2zpUshFzl9EwTbcDN5xQi_yLTxc
YgS0sAz_yxMdzemk3kbnEVoJs4uWLNjgZsEJW1Tul63tjQUtjR2zTsEJmUrNRbpPdkpXujSOtCnWXaq83lkVsCcpxicUdpwCoIUY-KYTfDldL7kqH_PByCPU
llRK7c5w2TgJlNplAPEzglTpwl7Uz-qjwofxyTJs-ENU4x8y_BtKuF2OaFRmpn3LgUrLZiv7jXVSQPuF7dfxmGFRu-RtCYFWOUJ6saCP0H_QgvsZO-g5ByRi
MI7V-p-2o_QCyDxRCVPDLnWXDl3vuAnbJlhe8oQB3H_Wqo_eRDpsIQdhJXsARnp_VDDRcPLbz4XoTf4yVBpbAuhYYtAdFXlPy6b130yWkwEysaz3OqPg7zTd
FeRzRm5OjEfjn0M7mCKOdqqCfST73HljSUEU-ygQdRqzJLwKsMa7VO6IdRgicfi7OYLBVS9zZIkrGAoaDvIyeAq7MX7x3ZZpG_8r-YnF-aXFwG-DxiwxM1gU
fBTa0b7fJkMzkMEJlaJDOh3MMFfAJl84zP7UbtOtqRbX_xvhhEcPdpZ94wXhUju_g168djzTl7CdQlJd3aq1jCpTrNy9Jw0jlITKjqZT1u-mCh14-n_g150Z
bXpYQeNS_TuU70i000003FAt7iM-QWO000000000000000000000000000000000001
}

