sprite $275_A [96x96/16z] {
xTG5OcKX58FXa2EG_Izux0d3yokCtg_Uqh-MWh_UuN0u75Zra4sjIu7jIagLU82ANUhDW4dzaEJ0fBxt-eI-IJsmUvzDoe99VQQK13gQdt3expD9hxggM_ib
nacMbDJIpKZQmduvUJ79a1JzmA9-qLaycwJrjrVqgPRVLEMvrcuccVtjTVqulSY7awJK24RMJgeNJQfNwM_whBUJ32d1fa_5Y_xT97-42PVI2jvZIFLfNtUt
f4i9c4HygYgVztqSLfKCm91_gyaUzf6EWKcr070b5g3gVV-1b1oiaaGiKLLUz_igeH-mI8Xl-lrVIXLOsdVPYtvVvPH-N-MCVb_bjBuFruyaxTalAJawjbtx
TbhbI8epvvP-N-L8whAixxEf4VSAAV4xRr9PsozIuedKEHjgQ_jydaV8S9AA2NthevAuSt_yc2dtxqFzOrAPq6_zqnKJ-iALLFELTjUlyKs-wZSDTyOR7Fiw
Y_Vz1UFlU8Of_UvlwHzz6t3lleMxn_Knk7FV7J_x-_e6q61cnMpIzs_cPD0vgGydQ8oOr7S30e1pGjzGmgqO68xR_h5FngZit0S7vS-_F-laVeex7noP4X-H
i8f4V22KMCMaik7KUo7PXZFlkQJq5r8zlqP9lP45sz1U8FuVXyFXy1K
}

