sprite $275_B [93x93/16z] {
xTO5hkmm38NXOupF_XVy62xEr9tqeJ-fmkWlMy6_QOmnnXXZYFbzTYwTF2RHPcIvwJqMnLBqAEau9bY2bgBXA6UYmrhh5mK7IQvLrDQbE0vAVb9e42OEglfo
T3mOd_ZY9rV59JFxyORY-YPqUtpnfzmTnuztQekh4UyEZ6HkZmVrnsci4MzE8sNjZYi3toIj4M-EEk7Q7CUJugBhBG_5TViEe0e_YCUxo0Zjnnlh_hhunEMf
pV78PsHdN19FXVvLSL68AbIlYAk6Q8XV4eSQn2JyYhWuu0AONX0tTnZ4_M_xMfuAsHb7F9ERPui-zH-FtAGqzZTDpi01GSS9HSLTmi8PojAxxQBZ52T3S8iN
0oTfaRNUHz9ndgtY-vOB3XjZZF4H
}

