sprite $275_B [446x446/16z] {
xC6n00000C2WV_x04wa2000000000000000000000000000000000000000000000000000000000000000000000000083PkmyTHvKe2A2Ag9h__z-N9_LZ
LXhRMhhWbDBcxUj3DKw2soPxEh87rjUCkZ3xBncLoIuPlKdOLITET_pOBSfdq-IdU5u-mEENwaVWvdofFtNScUyAf_tSbQ-LRiuj-IuqS_LXQEBShNpplFZW
uOFtD5_kyqhFJCNLk-GXcPjKprZ5rOijfIqB36amCz8pchFU8iaLzV8vbpu-hpTRyVS8R9sZLy_MMVmDEbldtRw0TQc3SvoXvyH7pzOvwFKczAvQlT3hEuNJ
Avo47ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZHeqUF7ZrwzEZvPWGzUlJehHDwzEYT57hD2RtcX5ux7xr-G7hzeTUSgzyUZTuSUfLw1TiilJ90UfqRABr-Fdhz
koUzduSUlhFqt6gMNj4rsGhuw8qVT9LUrQmfuQDtd2pDHoy_uGkzikiuV-6ZLp1i3H-zPZvwF-CBlPLEVFiF-Thqw8NUejEck7pqnjxCHwzvxwHNN3vwpVUA
ePUw6sFJIsdvwCtZ5fUFNlLzX-bLbuzUxvcFNj_zGUbbacWg7xtz0RqiM3vwlUMZD_Rcyj5Re7pqwD5hVD50x-TlkD3hqripTzFBO_CMwD6hAH-zvlBHQouV
lVRoqUjl7xr-lj1RpW_Ud2VtcZ8ytUjVl-xHCpqztTCzUhf7p_JqTAyxkgTxz4nl_Rf7J_TqZvxfhL_tT8-Uxj4pFJtTqpthrprwfgUdUxfd_Rf7p_IwHq_t
iZqJUYTsRtj1Gk-KwREz9lHEw5wsLuNUxvz-Urb2xtTtBzjsLlbqhrjFz-ZftlvKw3qMUej7ztIFdkxHqprwkgTxz7IFdkxf7ZtT-_I9J_xt8T2NdwscftjV
tdRUfknPLa_tvhBzMczRIa_tPhrCU5cuUxhtHf6y_NhUilsTjp-VVx8lgEUybtUH2UXTR_7dd5xlJR_-XhaLw7czDtNllNBRMxAkdkxbZMYot3wILVLqR_hb
zv-DrPzpwjxtUFks_EiztJjy4RWVyAsdftlphntycVNqTEyOAqSsQ-hfti7hznOztVk6CzFVMr5FzxOlEOHAikIp5jtRlcRQ8zTznQ1xnthRjtfZRJtTcyvw
QxzJfdivrfl-mcH5ptVAT8zUGNIlBhgdU_HqZvxkwHuztTkAzNHlo_vuGiyr0dNlNdgwjxkwwcbPI2_qpfZ-D3pTSqruzsF86NQwrpozxj7JFNgcfwTx5u_k
wHuzqzFJFTrBvy6tW9xnwT6h33rweLSy_gXUVdPRvxLt3bkdGy_MQUsEtnJhEO1pmgxlCN3SUH1KRzQBemxVEQkcDzByX1EVDJU_S1hDUCetRFRupbeklXHj
z3CUlP4El6CzVADweVX6zIhnPUbDSyR3jxhVWFU38tibmOpnCppjUyjgSF2E-GhIZySlg8vIZIVftZM57R_Jx2HEU02BvUoWDambrBa_suC30W0040H0_rzt
8nM81G00000000000000000000000000000000000C01
}

