sprite $275_A [93x93/16z] {
xTG7heD848JXwjnr_mDlykWjbas6ZNpE7kadjS11ZyVZyR2lS0LlVkKupPeC_vJqIzBoTULiN8jC0Mw8IvAbm87uyVJvU91jm1rnRxPZIaH_9oVZOqIclxCv
zCcurTlqIJJ9oepVD6VYnwOlo0x5K3lYskDWPMP4R9px8t5Zrs-Qhvx4Unf91d0uRgz3rs_JfyrIMEIVoCoXsFd3PJ7-ENr11govJSbyV4pVsswt8iXGmHgn
8dKk_d7lSpB_M11iuwJCn9c22Ics0JBQ6-lrDQwfcBAniQ1Xkw9yn3z8aWvhaeqTdBuQjsO9qAnYOGTXhCLZJ0qBmjmNpyNu6C1ZSQp4nsxViETZ00UMseLx
xfokDidBuf9yFmoFP5qI7mFuJiWUqax4atHyoExH9-le1TMUkud8Y4gn3kvvC32Z6o_9F1fNp4WANefwTTn_bfHrTTpe679brsLtN1dOkkjduYY6BV2FUEXl
ahhbMBMvw2C-wBPZjNbiCy4RZpyuLkBhM9Zppuq_ST4fkJGk6LDvQLm3Kod_ghYQg9cOtH9N5markICEKwY9nnrnCy01kDmIDoZ4xLyrBH8YWE3r9jV64Jdb
_-ExOc4BEHGlOWjbOB-WOuEaue2cOfMnS8InL-j6AWvnCXKBD4d3GLfSKOhZD6f1AFxr7e_7urS
}

