sprite $275_A [446x446/16z] {
xC6n00000C2WV_x04wa2000000000000000000000000000000000000002OlJjRJvm7WZ1ynbFLzt-__vfLH8pJaTrgyjNi6v5uAKi6Xvd65oMMXyYNHL4G
UWSVTciFdjXrrICoUjXThaTiz2ZUnNf4iflg4LNSgUYTPwTee4Tc1pFqw5sX7WiUUlHklHv9sA57yIhqw1rwz6wz7dQEG8zpX08z5hocUjWfq6EzAzJZsMZq
MF3gzJZ1ww_7GHCzxF9wH4hOeSTUfK2FpGfwh7SrUlGEFJOhUJsY2LrJFHOyTTMZTr84UfpWoRFigST6KpwKzNhO-SBFwjj5ZvC4oqEQwB7WEHULwt6I83aR
z19HFLsz7iz6UqWVFJQQTbCzrZl9NVNuf8G_s-c_J1ZMw66dnNJoOBQL7hsJakTlzNfiDBEBMBqUpqQdQrUlnrvbBeUUV21hRdHrXT7J6S_jNcE7ddmmFxpD
4mw_wCc7Kt39ohBdjT6xt4xhyD2x-hhsbQ_1evUqqp8ynMbww4aBxRIsUEXTUQdOujwXv-ikDz9tRmgzv5zORnU92gVrqDErThBbtIFRwg2NME_IU6uMxQqd
ByMJvlENMqRQLK-B7s_psv8RHrlgAT6x59xSFDfDJwVRUVX8lRELtl8Hwd3nyClhpUrqXbtuQQ9AlVncXUAzP0CzBH-N4bjD_39wMZyet-KHdXmzOgtdo-kT
P2SVRvuitayehQVbTg7vxMds9xq5Q_HEUOSS7tvcJD4r7bAYTuATvdRHs6wCjjGxyw2Y15wN-jNeBQx3mnky0A-CJ-Lwwuitnulk6QTRhRTyANTYhdtvLAYd
4qw4vhRn9D4UUbh_PcLAJBGrtrLwURhyDMF3nuDlbTu5Jpuay9gaLayds5c9IVOldoxHYxKVq6E-CKVAbzTJd80dFTQBnbdVXVobqcVOsOa7QE_e6htraUPs
yeSl4pmEdOLwyfZ4c-bmw2pGIrwx4bi4lGUrid-LNlJJUm3ZUVJSUkwXfmSi_dLwQg8tnpkc5y-PJdfo0gzQ3xrvyNheeITDH1eiU-ZDGURRvz-Zvwtrz8tN
WkBtwAbSBs-7dXle-IxHHO_kUOoYN0-zVF6QwA4tiMkWnxgd2Lu3FRetiUkWXvw7I5LwwAtVQgBd0htiYjT4Z-xvBj543prvZA9S3xryyPheiUvDYjT0Z-vf
Khm6UkWfKRnIFVJonUFAY7gzEK0qqQDxIjlLww7tCxnGcHvwIcnNqFCUUYkkdotIetjQSdSNwA6NjnkZo_NGayT4DbVhiUujVcDnQRqUtSiNBvzpzT1Bs2Nq
3aQEuq7lx2ESln-nxkNtcXLwOoIwLsyNuMo4NZbUE1_qydRrUXRhNdghMQzdqxrIl91_5A6NFa6lBv-5NluahzvFh7k9ujLCLPhmqRrfyGhqCdjXzEGn6qvL
NuyGlLAyiDDyh7ltrTEkxw7UXazrUXi_KlNuGOQUebWl_nyKebVz7kfvFjQz1lzvY3p1fdiT7gfkm8VUeVPrqqClwil7kfSVWFFbetlrxyAjJVdGQtpiH2zV
FjQzDhFTI8_kwJdAXrwxyg6NeDXwtsBq6fTFwBNZOzrJEptq8g6dZVMCNhloqJr7TDvsejVxs8bU--UgZLx1oaVtq4ElqR4JlSWfo9i6lIDnIT133pqrraCl
EkkXf-VNEvoEpquqm4ElMVtGwr-_GEz8f3vuw7L-DRs_7dhhbmMXrrXlmzcZ5mNDGszXT21H6FJgWnvwFO8UUkWnVcQF7dhezGXwwA77-9azUkYXroFeeOSU
usVswA67Ne-WXnvwZ9_PeuSUUis27dheIRS54Nebix-jYT0hcFrjLOpUvRFNRLdGktpsjtKHUkXzE-X9aVzIh8TU_2ZeeVUCGGyzzD133ptqq4CFFVJGGmyz
zD2J_hFm_t_k3ryK4Nh_zNPwwEdsblkN_pw_9h6L7deZLpCzz0QjXdfqBwAZ7dhX5uQttrQ4NbJr_jlQSS-9NkZ37mn_R_ZjRVKut_lYWAgNt_Q_tpRMG--h
bUtphaQxwg7dbzyTVjbXruAU9glUPprjgOVUbuV6-xFv3VNGquZXZv-deB6SzNheZNYUx3zVigaUUdSKjrvwlCQWoHQcZHwlCNnypinlAw0KeGQx5bvZU3_5
6_wuWnvwuu5JlSxMqViaum5lOptqDEvFzCRdQAZ7DMKAyGhHuN1587heeOSUUkYXXnvwwAcn7dgtMZtqB2lzzVKsqBjyzhn7O4tGGq_ByFhgySx6HgzYzbfK
FVHgPh_0Je5UrUore7ZebSvUBr-__Lt1-D5Z_CmUFVJGQn3qq4EFyJDxzD133xsEGQy-w0czhgD7J-YnS33wAwF6ZrxqtFeEe7kDowSHZ_9HFVGOEhlkumTz
zAokUj4i782K7pVbOzZvy20srRk_8mGUV3KZvjZfLdXKRxmtr7cuyBdNO8aQtIC2xmyFQBLwd16vXP-Dtf7xHStmQD_MTuvqu046tvQ0-lFOuDiIq8V6HTmW
KplI6e-eDnx1ZlvXXryU3p_eMF-m0v2dnVvk3uu5000000RvMmzYRxK1000000000000000000000000000000000004
}

