sprite $275_B [93x93/16z] {
xC610000082W_QaNgG8000000000000000000000000000000000000000000000000000000000000000000000000009XTCx4L08H1Q0WfnFq7_lTz353m
RM2mG8tR03dIsO2b8N4rUuVZimjhU7LxWl9PYUTgvxCOiNlkpbAkVj09eDG_vsHWNjFSFdwthNWMuFCReLiyQSy2ZDzBZflauy-PUu-EjG8QhNs5Aq-ESQLy
37cnWBxBrvTvGinHt20UdDIrLROuA6lFvTS0RmezC-r0wF5D8-u-giSt4MCdcxtp7dHAUgSp2vehXW-X2S6AugBlePVedIn8lOcjqYfudKRknKJyFvO9xcDC
Dqups5SSCsmSVI4w6_2bTMR_j6LqdsPOaFyaEnScMpnbgwSyyVA_Fy91mUVpByn-I38IHozzdtraxqvm6zbX80oB88f2t__0RxM9KTfmfkDWHCP_lNLsEvzB
wbtwEPzEdSn-_85S_p5wDe_c6otehKMRhVJGMwaI5Bq-UdIlIz133ptcFVJe7dheeOSUynvwT0yzzD13ZtaFFRg77dheeSUyXzxqJBFkeRUcS_VGetjT8lGQ
noTwZIFclSuHtUiSqRtEiQ1xhUCPzjPxvoVeeJVrQSpCq2kLUNs1GckbXrxZPJRGEsUwDTH3BoFhguVU4TvPZzKI0xtDiUE5X3VMOxdBQUXjZcKyIsKFujAS
9pxqobvqTevh5bsT5xtudKfvB7o6Ng-dUldIFqElsSD8DUks3xsuyhZ1GA_O2IExSdsQqAlr56wxT8c5ezVjpNhLPORHqxZ49_Gg9DlKSDb5zEQbvHcYrFMW
wAN7rRkIr4IFeosFrvT4hzsxZOhbGoyktz5f3VGuIRJ6QnymG-zvblAXLsNXddxbGqzNzKQKEy-Etk7NxuONUltUhihEVEXz7YktpuUUld1uRQBNu6xQ1kL3
xthvefyUUbxiF1zwq_gL3xryl_QbyXbwEwElE5Z1FNQwTztywAD7zpAf5uPUk_SRoJVbTQ8tqyiMwI9wwQ3tFD5O3prlh8VUc8trqBDeg8TUHetrq1i-g-B5
-3myBjSrPnSyRaGvnyptvi5QMJxGQ_Rwv_kGeOSUUkYXXnvwwA677dheeOSUUkYXXnvwwA677dheeOSUUkYXXnvwwA677dheeOSUUkYXXnvwwA677dhsIZRg
eMUkL-ERzD3p-8R8DkYXbtWR-5xLGyyKtnFzUJtq5DyLswI7dbvB_1lVf8UUlPIjUkXfl1H73xsV6FJGGmyzzD133ptqq4CFFVJGGmyzCqbk3wwOMB-ZdXvw
fZpVcj_uvNiKcN9wwDc2jUh5gcULzD1B2UdstQkUHktkeJSKihk8hQh-_y-NLTrgGSyyfx_uC1jQTJtqLgvxxFQph8iUUbf-ckokQ6PMMGyzfKTMB_z74I6l
g8TUWiZEbXOP5TH3ByVDZzNBwL39LqmFlJJoXyEekPkPAxjPIm-zjNcFDpGjlKhfePVDo_W36rNKGo-RjsfQ0ptqrkObZXxzEYkaXrxYoMuvGxbP_gnQUkYT
JofazH9gkMcejXvwfXKg8okdXvuY_xhhIIEXTECjTgGClISNiYnda5pkPWCzhYb33xq6GQzlq4CFFVJGGmyzzD0B6wz4M_NGqpVesH_NGy_-rvD_DNdaSw37
4nxV9JnT5JtJhkgXbtgR-JHswV5C-9VjD3ReePU0hyHOZu6rKFO7FVJGGmyzzD133ptqq4CFFVJGi_dMUdxNyvvwnorgR82UlxUUHiUeySjduiXfszvJB-vw
FXhcwBlHnTZZnp9olF745tpq6azyX_FQ6q_yqNZWjF7kG-VXVF3w9VM2prs_gEiNORxx5kSwzy-6rSijJigdJdXpsLMdVAt6pg1wEGQrErwcWzs5Mw8Tduu7
rMFidDPiqflZxQEZ4r_YdQTg-BpFF9tZ9cDdHcq-QKSOTX_vmegVJyxO83aSPMH5xVp8B8CyVFM_C3x1UygNcIht0cF1EnxXCVTbmcrKYIbV7NZFjmWoC-Is
cz3STNvb7_68wJXdpjYRcQrxVb21-3mwH4WzgL_Hz1yrgPyCf2VnADoxtx33RpQs8wPPpyuls05Og84pDCZr7MN5t9kGtB7uQcnl021_jmS7100080Y0_h_k
HYeG2m00000000000000000000000000000000000E
}

