sprite $277_A [124x124/16z] {
xTY5iUGm48JX7X1q_WbVwPWzygeURNy1p6y6uGyY8Y8Y8Y8Y8dt-nGYyWEJVsGkq6zd_C4X_aVR47_AzjTLMMstBFdutoV67ISxnDprmIqwUq0sxOfNNtlJx
nk2IsDDNk3aUvIlViC4coSGHiJbgajDmY9DqL0rou1md9uhoActnCwzSF54_ueR_QRyANB3QSOpCVdbXTlmiid8IhRBB2wxRjjFEma4FSkdNxSpcsIApLTfE
PcNxaipAVZUW0U6Ljf6zqBOWez1k1e-LhxHnjDrQVis_VDlCO5XUkkq_onTjH_k5dMfFhlOnzRPnUPqshFNnIkqbdhSz-cdrzdd5DlhNR_r3livo57dfd9-V
fVO-jTMEpLb6DXpIICEEIHgEiCc9BKbEnm4-xwqxZ1RX3uXeW-J0hiv3ElRvaVe8tEFn8CT79I8Y8Y8Y8Y8YyWa
}

