sprite $277_B [96x96/16z] {
xTc5eKGX34JH8G6IwR_WTVTToDUS0kvp0H0hfPIIDZl2RDLvgc2gugHLsLUDRXjrMjuAZenxhfZ0sN7Ag594H6tAcQeqNFIFPyfcx7wvrmU9KKB3tRvJnqzF
kzytLWngrFlz_jNzx6S_-zdFVlSjnlI5Es7zlgizxsTVz40Y-aqFMaWV1q5zKTMcsgBw48K26jPlwxW6dXyHGABwig4Y4jBN4zj-lX-yRdXClmI__w5zot_e
zpVxsSz-zhDVx_UDYa7wU7vCC8gysrSwXXdhdRuuAuO9_RBljkQaOGAxo1Xtl64AfvttLJOcpf-xN9p_W0bwbIrd2LvWA9XFMjzh29PIIca9
}

