sprite $277_B [124x124/16z] {
xTf5WjWm44JHPdNT_y11J-J1e3fKVsMldXab_tICCSOOOnPPjtmEBZnDPj9BxjsKRGsWN6KN-5AN7QG1r0Ll-rxAeHH0Y3opyseTn1VWyeBzQ9UOdCY1aZTj
CM2TMctvYYqBq3DxExzg1-1dDhbzrJOW3jW1wBVOUS1EGBvgw_zeqwPDcpPjshHfrtgef-t4RjfUwBhgURlsvFzdqzPub4tQaNwlHcsNUwN3jfdOf-PjypJp
C4iTjqLI94mqPDuE-yphl6sPvYOQCc_lfksCUoM3jlgZx1-xdjFklEffkx2RjgtdxPq-z4-zbz2cJPisRTgqQTksn_z1En07R0FygtO29WS2wgjs0-DZBVPC
oOaSoBVj0A1of0Rq9RkxryS08EHC3gmNx7ikfogWNh3NLOKSh9_Z0SX8sa3xgBtJ1M25FRlKZXHubeobsVFsJZrkcVpJCSOOOuoz1m
}

