sprite $ClearPass_Exchange [93x93/16z] {
xC6n00000C2WV_x04wa200000000000000000000000000000000000000000000000000000000001cppvoCzPX00mkkA5v__k-tWkH63OZ8lDj_-w158N-
lkNhgLxf6aliVWzVNiF9mkFtPNZQZAVSZAVL1nRjngEtV-F41uzUrilfKRxcdGRYzy8xZONFqgCtXwVShAVleaUF7Zr_gPfBcCtLFKNFAQDvgBcsUQIU0_xr
mSVEq3FQwlIQUpTZUkeOhcPcsRmin_JK25ttOAyZzEWr3-LfUl3kwLtqwD6ZX--JUadllPnQwDN77ye3zF1zVA1onAn5UM_EcQVDEIs-xh56lGxGi_gQnxAv
kBLVJ_DweYTwzEZH4prwzEZD9thqH4_qwD6Z9tgYHuyUFT6JARKfDJrweaUF7ZtH4prwzEY9dkZHeqTFzEZHeoTweaUF7ZtHEpDweaUF7ZtH4prwzEY9dkZ5
pz7xisLuM_teHQpbenUnbezUnbu-UX6B-UWjvgENg_cSMfRpqPldeuUFNiPoFfEoVqRFvadlA3vw-EZXezSVFUavUTApUT8RuwDdywGNz-lvNZMc5q_ruJUd
TufTh_89Q7etxURrWjvfU5d_B1jfUaVXHNr6B-YTZTVh1RspyQfswD6xyHcdwD4hUklnlkpSGczWHFsE7hsf-mlvj1wz7Bop_hGUlO4xUmVeqSi6xtGzUWtU
aNhqUhm5UlGQl7FrwFLuM_JePODtkXwz1c-T7htQgsVdhBrwz6gldZDdxTNp_rxjrJDhgRLwvfnLY_JezT6RZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7
ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJeqQD7ZnuzUlJenK_bIZrw6R-sKOzU_DuwFNhnbvRf
qSl5UlHYhHwzYBLwz7An7hrOgqSlOgqUlMpmJjUZ5_yij-ZHYmRlI3rw_RQvHOzU_BFSeaSl6hnfFNhvmhOvfKSl7jWswOrs-_8_WFUa7hqOs3Rf7S3Nh3nw
WzqnY0Vm7jUZ5pcmRLRGUualRcsRatZqUeoU9Hve0ezUnE5wzF8BzOhUwEAxxqTldgzPgmVWqUlvwiN5b_HUvglt-AhelSptMMrw1_5blSMNHU_1ybEN-825
HwydgQONwEZDDOz23n-zde_UVZvw-EZXezVpqSD7RvwFtkA2tkRehOxUwkYjhi6ZjuSlwIqi6pnwgwCdUg97ZnuzqQD7ZvxeYHuzUlH4J_JeqQCdUlJeqHCz
qQD7ZvxeYHuzUlH4ZnuzUbb3mNj1xwfjqTlBHs-UJtczeZUVSh6UgWxW4pruY_YKY_LKzQtvu5LU1sJVNEPdvU63jyAFNLzE9AFU7zk30m400000GVxMWrnT
0G0000000000000000000000000000000G
}

