sprite $ClearPass_OnGuard [446x446/16z] {
xC610000082W_QaNgG8000000000000000000000000000000000000000000000000000000000WDcxzrrNSIGAuwvb4F3-BpoPcRv4Meqw94LXIz_tRxBf
o--KWnssphUf86et5DhsYcXRbMst7dNHjaJBQzcEocZV8WzlFugZJIsdzG4ysfUMaPx1WoyIyE8XF5eJzDRZeMYPUDsaBL97RxyzEjvI-wtOx2xepYZMDxyj
R-7SrUwCV7Uz_wftROmfzpunuKeNpsueRxrJajwnjg9eozephEyN8lG8FVJGGu-qhDkwBMfU_E-bLT6iqFzUMc84FRRN--gks-b-AxO_VqpbUkHVNZkVTZzn
zYF8VHb0ZvEH5v_X6P_XsVILwL7iXpcOWlyFN8xtzZezCWOdSjXZEuSzebwFd67r4_vNVkIy6tgz7iLsd0xOQdeEYrv-wB5oBgEldBIUCyZkMaxrObuzTWnR
6q2FuLi-tQstuNRhtBUivmyORMec-_n96SLgfzHkDF0fDNxRgpLQyvR_lQJMFAtRg-U_8QA82o_PQpFhqVnwX1vwwA57wA677dfh54KtwErRKRJdwjL7wA57
w15wwA677g57wA4tq4aPSKhDAJLww15wwA677g57wA677dg47g677dhe4NheeOSUeJTbw15wwA677g57wA677dg47dheIVsLq9iIh_y_eJSjtYkXDotUAw4t
BTuheJSjtYkXDnNUh7pegNj2RngyIVdG2_L_Je7U37YJyg4dzVSqqUg9dcdDmuUUMyt2Xrx8fPmlq9jXy3JFkGjwvqWn-FYX9_dadVC9lPbEfJNirW-zaEDD
m8UUsHcUyGtaXvwpw08oUeCDNdp-Lg7thDsLWT8u1zVenMKD5VgXbq-XRYdG6y5Ert-ktW-zKF_UGFr1F_H2wbxasADNFtTTlp-t9A7tpFDYaVD7G87UROLo
XgRU3psZCxkawmLw1LDdTbVBlwY7ddJN4xQdrqsPGFJ2w797H3e757gPi-5scNwUXDuzUD6yVBzyFlIaijz-2FI-B6uSE_TJwl2Xfp8xzylNGqygs9gWbr8y
S0eY2RsKmkWg2YbL3psrseJUrw677dhenRnww0czX15eTnKngnvwKfSqfHvwEbkN-OvX_9k7E3CAzCQ_SUz5UkYLNbsZww6dZbxHK--wyTfTKQ27NidevTyj
yKnPrE7bxrJGgritM_HSFVJqoEXfB3tq70-zkRvb27jW4xs2uv3yaLRpZFR7qEjHi6xw7ndqHllW2yChM3ZHon-zGA_eaSw2THEzulrwFbwxuLScq5F-8KlT
BWMzej5JYHvw-NZetNQS7BcRXRZnanOz7uNYqUkj8FHIyFmzGc-8Wsh7wmszwgFEWj4B-yUXz_3IwNZreuTUtk4qUWLbhcNww3eTlH67JnEC7dhNyT1x_bkY
YFXztOoEtXF3fwukvOrURsMX9tlz0bxDmebUZtzvHrmvdFOwUlbz_fsS8cVqUg1NitJw6wxZ-MNGArWwtUVx6ydew9KEd-jrpJDwwBcGBk2XLr2S27nW55Vn
qAiVlZZxVz-_qMlerMxvmfXie2xCDtfbMpvtqWbUqMOFlUlBclntAkC2YSmPlPBx5kVJ3wE7Nl5zYq-QJ2HXzD0hUY2iotxZvC9ierSyV7xcOk1FthEWTvNl
oZZPUz4hs3Ga_SrJGk_H7Rj_VWquUkXT7pubN1gzak5hkeuNgiH3J-rplaYuC7gPV8gF-PHm38TUtV25uLNSiw2NjATMlxRtLW4UUWbFrQ8t0zyr3ZsEXvw_
KT4-Ix9te_SWtrMEAAL3hxU9Gi-7R-BGYvOGUlCEdru5UcL5p-CBsMNG6tlu_58IUcMb3P_gRr_HKn9Vs6aeUhLyAhaCUi_Vk3WUA-UiQsVuDT2hvukqIzI7
dWgkW5u1tnnuwCLl__kZlnNeFNhV6MNsw3s_TgRXeLVF9vlRwj2B_YMVdltGGyyLbFPZwDNpIHFXeUSIjNZerVEfZ_cXXrvNullHg-UR20yz1va83pqdcGWF
FKU9axU5uQ4t6D-vYmmFlJ7vmWVFXD4RbCzn_7NqHkPxzv7ZeJSad_l9NsheZSxNfR3Fkp7nq3EeiwAXDyVuUOg6tgnyQWszILTFgQ4tSYeOFFJg_HGDlV4B
pMI7dllDQOUUdx38xD0Rlj0VjRBGgmyzGe_GGmyzz0WzzD13Zz0ZzD133pr2Zz133ptq23tqq4EFq2Fqq4CFFKAFq4CFFVG8FVJGGszhDL7inv-f_THo_Dck
Tcla4tEqtz9HF7oqx7zFJFkjsDxur2e3xzZonlZLljuRRI-xn0yhxST3qHRjns8z7egMbFlNMMBqlBMEZ-nJRqu-y9QyczXfOlASRpjAeytmvhdpPDMCbbgi
srwmW0AtxzlIRaXQrfkZHT6cwJ_jmO4C0000m21_wtjyrGK00000000000000000000000000000000G
}

