sprite $ClearPass_OnGuard [446x446/16z] {
xC6n00000C2WV_x04wa200000000000000000000000000000000000000000000000000000000083PkvFTvdaO2iCBdarq__VxZz-gmq6LqXo0zspbAe2V
a9Qi07qpUXM4F47tgWl13i0-FB8QZx1OWU_L5B8PZwpkcsHrwP7DfKTIIq_duP3dz4v1IAPU2nw70UXHVFLuH9lro0OzWXvwwA77tPQvVtweNuybedVmG_rw
RC_CqCiCpT3ZnQJC-OmPQj83ppXir4Fl7lOrNGyzcMFJDZtmxlLUBNe4FJhdGUysh5e8EmPswvgdXvxslYc3J-Ot3lRF-lNmCmSGid_MhGUW6P8vNDfyEajs
wn7qq4CFFO8UUkYXrnE27de4FO8UUkYXHz0ZwA677de4FRBvBJL13ptqq2FeeOSUUWGzWXvwwA57q2FeeOSUUWGzzD13Zw17qFjbq2Fe4VJGGmyzWXvwwEd_
eBSIB_u4lSLu4UWjnWkXjnSlGkZjnOiGUglmjlAXf_WYwAt1syg7NdmNz1RZHGYzsL6ueBSOBqBeBUgQdpNHsuDtbl2XfyzuApRkw1acpL-ye1VVu0tcG-zx
8LbPz4Rlq2_6EuEU38wfJVI6skdoAlJwcwPdYMb-wCcON5-ANhzT952ZrsFdDMA87tfldG7503_qz2w3kltGqsyENwFJ3ptzykHSNNxeoTXTyAS1ejTmtqlz
qFDsaJYNq2kbK_9y8VHgw7pT-OI9q2kW2tNEx8DU-6Zkxp_HKzWKV3-4NaDdQ__nF7gEJiCNHUWLzZEXbv2-5v92BpUsPUP7UbGFlRKVYPvEGQHyFVIaKnQX
bv2-NVDYFVJGGmyzzD3p7w6LUkZfq-HhzD3JTxC7UhdxhcU_7TL5ZrvcQPiHz4Ok_RHO3xtOguTUeBTtqIc7XrvsVJmujToN1ht-rkdxvcGzz3oUq5lru9F5
4tgJ7do-zCfU4g2NZoVqLhqhay5xw2k3dfx0Yxg7BNhv3ptq5YmwJT-isAQW5mLzi-6nXrvctnHwGnUTlc_wnebUV_4PlCxT7dhtVTDVWbv_w_Hzq-i9lTOz
mpsUq1lIEdtVNA27di7B_ZZqV37azSrLUkZ9b9x_DFJwMwV1womzzExx9dghzWpgBptqmlEuEVfB3ptvQtJJD_rbGg-g-CmzztZzUkZ9Z9lrfhaElRejdpnE
69LHZptqTDat_JJevRTEx-FxPa7feUSxemMI6slLGyyNtsSYDU2Xvs-ivpC3w0qilXFVA1ayynb2hx7uPFfcwsOFFVs0p_RDkiQ9dc-TdkzDFA5Nq3hTey_W
TPOUUleHtrqz2RtYulDycbbww4NwlpSLUgth5i-dXCQCNkNFCGrtUkcXbtA7tomzz3hNBPvF3QM7dh_7_geRa42lSy_d-SwKqaFlldSAlGcHCJ5yL_CAlURY
yzTvlODUR_7vOlAN2xt-ujCTHqdfeQThlhjf3teJYkzSTaAPYz4hBxuZIGqSw0ryBO8UVEWfzIYkSP-0NYYda8LU2r_IL4AlA6d5fq1lR-ziMF-WToAdTmgz
nRqpWiwvTU6YG6zHx_HJeBUfTweF3pqPlkI_Hw-_T_e_HsyJN_IM7deoVEFw9dg-VY817hssubCp7de5Jo-ZZjw2wekcqaFFGoX17Bt1V3ALXzvqFeE7td0-
HNFVHC-3H04UUWryOV3Gcy8dUvbdHg-VRm4UUXSoCHKFlIEF8pEEtaY-y8Fe3UUJ6K5lC9-F3dfh-NJGcvVDUEX9m-tGyzcCXvuq6myz7taxz8P7nWwzfK-_
io3ecNDOzDR4b1rw2o8f91qVz0Xw13tqq4EFe8SUUkWHz0XwwA677a6Fe8SUUkWHzD133ps2thQWHz133ptq27e4FVJGGu-WH_I4davrABrNrqoalz-z6eeF
l3ozqkeZohpXUZM6vDLnVWXwuEtdGsy_7tZx5oxWzLSVUF21ry87tdu_w034xk_su4000000G92_zGOJL0S00000000000000000000000000000000W
}

