sprite $ClearPass_Guest_Access [93x93/16z] {
xTO5OiCm38NX1ujjtV_0OqgTiJog_ZBa2mD-SrLLLLLLoMa9-zWZiOvTBKPFAsBRuIE4j1pz12S-dVZuJ05GZ3HyYn3GRqH6j5oyHrm04K4uOkJY6ft0DXg0
FfoApysuc9OdFBFL-Ffb_lVnmWild9fY5kx3Sd3PchALX1DJ_3iukH2tkGwNpGKu1Knw5dxTf6VWivw4oqSn1QSpyIcU9biBLwYm2AUjPRk_pJ-v-yy7hZgU
w_3BbITevk1yoVxxLro55rvuZwQiV8tjS4TgmYwrdbOJbbLLLNK5
}

