sprite $ClearPass_Exchange [96x96/16z] {
xTS5RaGn38HXsnD5yVqFN0vMM4rAEzyo_ViOxCj4H4H4mEHsG78rstXcOygijYhPZ0cPHxyQ5RVViYxtXTttVCtXxRvajWl3t_hmUsQbzmtBlTkBRv-_hL9z
wjETmr-eVc3zKbzzlziFu6hV0ToTFa3G--SVqFiU4_eaYXUSVc0Nyqr6tm4VUjxixOLJ-c5TR9C_oFsPv_VFf_p-INtrrJ-fxt6rxy3DVW1niUyzp-iRi1G1
6y3f1n0H_VWg9iR-lGyrl3zR6ATl_cB-bNT6wfyJw-hnVm1N-nRnlywFr5SVcOMfPhDDJJBOhbGgsCyI4Na6
}

