sprite $ClearPass_Onboard [93x93/16z] {
xTQ9QkGm3CPnwPEju_rVUDUfGT6a1NVhlVq7SW6_U3HNw8kTJgVJwNHYR8jVROsDMULRXDkk8gpW5essnH5bwHxu0dPHOpEtlWz7H1k37QA5xSLxX0ussXX8
y5QSFOH8mfb8GsaV_koNurlxfRZmlk8NpFpW1pyurx_oP_oz7yBHpKVM-0CPyXP_5cSThgeDlxr7omX8VXcNNB6ekxvhSnxY4pZSbVDEbdhQg6VBE9jtUfnN
cn_dYxY-hXJkPMalAyNGr_11CP7EmR0fKIktgnIDPKEmXlTh2EQNpkPwRRbg6KJc_LPmSqoLnzRucbIxuyzvZ-q2pcuq6YwcJStxdNlE7siu1ZvrdpR1zOQZ
36NkiOpF8tUcZt3W_Yfu3UVtLYxUApwdBDDS7GkPysFc_Vc6GeGnxNLSlKqxFotckECyTP5ommLSt2xEydC-BcKGJ50uBotXmstr6rgdaXzgGRcoX8kxq3tc
FC_FNubf4QTUTDOyIvsfliCBUEgAUInp-gywydWLpycuzIPDpLrVxIaAc34EG2junjtyBHFA2Zy3qogUeVNUSxRF6C1DFezp1p_umQFY5efjjGYwXzXQfvAO
RyiQ_PsTJgVJDm
}

