sprite $ClearPass_Access_Management [446x446/16z] {
xDD13SG054B1yyU_u3Mnb3QPaS0BUG4000000000000000000000000000000000000000000000000000000000W6iWT_rqnNYudO3BTeYdtYeUskctgeTu
yitYKMkNNFwAv-gbWCxCjNRqbzwb4r0zzKRnv9l5Op_ubzl9DuqdNxvM3zzpFl7Kcv5l4W_rrBjvFVdKKm_rKEzHwg6UUkgfXtgefvvwwg4Uwgcdddgefvvw
wg4UwgcdddgeXthggQSUwgcdddgeXthggQSUwg6UUkgfXthggQSUwltOkzETHtaOYkEVVUJxlzrtHIDNzR-6ACn2ZsV53X7mgrMrj7do_uYtL3SsCb__zBE5
cdpayPU6AX-a-eXIXvDxfbxMcAvLlWSC6FPKS9KU4yoGDN3Qf-YnnZQzdFTSdNUQ6GlFqelShiU59ePvQTffOfxpINgHs_KW3th9LPuuvec_GYzlrSiJUZdO
hisB5Jr0h--Jr3Kz7RzOBrIZxWPwM5LEUlKSciBpzDg7k4xgVPvKV9LX7gXsqsRo0TLpWCB3z3uLXpoMcr4zLq3rgjwfKtYGNl3PhVVUKPpqvirsMs4zSbZe
FQeEJRAuMVBdzMGzseils5czl8BPpHjvn5VsdlRtNXctj_SwFR4ULAnNumQzeCPalPhb2eVrQeBqic-Bb-r8q0C-KCfzVDRhegiANieBzO29AzOR-aT0I_1T
TFE2qjORHDOxuwCDUZKxzgNr6EzYxvs-VzHHni3NLgm7UNolSbalfcdP3mkFqSj5FTuj-rZK6wTjOlcbWtilp-cL_qOpRwRGTPqleE1tojRrSikZeWPFOxsr
gnpTdkVriW_h7R6dznA3zJBFwrtYkr3mtLbuBjkfXpScCsaq51xxoOYoSUfYqYMTzQGLFNeSA5yh2OKdwIcxu1hd-IhpWFEVOPlrpX_gW_IqKQ-zFllqMFGi
dlNcl4Qzpc3Mu-ILKuX7wKcxzFZpq-mxwNEwxhc0znWzwTVfQOkUkgE4mlFqb88p7rddYoyUCjzrvQpma89EBVKeFOVrh6Szwpcivx2UzQndFOVr7DQpdlMi
vx2UzQndFOVr7DQpdlMivx2UmthMivxr7DRxzM4zX_K-_VWB1N-RYvVtK4h2pFwmdch4i7G7hMDKjo6pFwmtBm-MDQBLono0hNSNNfx0OvfeXwJrxenfhSrG
rJj8gbubUR66pDwmNeBUyDp8Uf2vBQmdMXoGKzRxNV2EV-Osc_MIqQstFufUpPpKEo9-6Pzxh_XSwhrvrP2yayzwkLDFTHCoTuJrj4CloZPaxWZhnP8UaqB6
UflnQYpeqPoGkJEiToIrgDVp_yPwxhss493P5zP3lW0fpltaTrsiro-NolVx1gDyA-HjUDQBNg_-JyqBSRx7KFNRpFvmxzMjnVjxwVjxlnPFVDUyoO4Ua-lM
i1vObJhRPB_JlNhMKudXms5ATJJLiqm96Uivh6SzwrdFOJs7zPR2UWxhEQndFUjPps4zX_MiPpthhNwRXnFjUFfXSPhksCAI1kFe_YvzvgFrJdpvO_g0yp01
MSq_X74OtZ-6ik6pNbxKIy0xhrSJp6-zrui06l56qUYLAkEn7XyAuCrw-bAzUHaLqcipIacfn6VJkVVWo8iUJFubUhb5hwJWKZOSIOSo3Cz6Jr-afqalzAQX
ZtfwKz1vlVYnBTQhVD-j5pzEDVh6KQjtfBhn0K-Bf_JoVEzPh_PHafxUE7vKM7lMovh0G-7Ua_MEYxsabvrU_PVrIe2UDBp0A2CQFUkzBYGswpKvU447UdgP
WFLU1xAUzTGtKrR6RdWkw4N58BsteuYlrbEv0czw0DC-xDVqikqzWLwPe7mLpRtNwnq1C6_4DIOzM3ShwaRYy3hjb-fLWEOvQzJBeXSy_8XPJyK2zUfKrbEz
u0aQk3GIQw_gnQXN4zO3dO6ZQJDOnVY2tX4YlNwgRzPJ7i6NhDCBNk-ZfE_GgmdhdRXae05wBzFWoy3ZbseDdsAFyUzlhdoxNhrceA66eEaKcdg-lqSF91e-
wrbFhDSrLdPhWbpIu__nszBMA_zhDQHhUlowSLcF6_rBzUBzzcRGad7J6yAVLWhFmWoUpJnDgzPCEOr6pv_dTEpK-xkT-pP2880181XB_HTC3TWR3RivJWUy
V_NKGptrr5CFzL1FFVNKGptKKqyzzL1FFVNKGptKUv5wg8Twwgcd7kgXddfRrrCl-0wWddYtwubN_OJffpv9FktKKs-dw2UUUkBjJDXFl30V_RIhUk9D-upq
evu90cetNtZMx_JZYpEUdsFtR3vMFV6AVgnysYNvjDDFl3AVTWfAr_VJ3W00001cjzXhDVikx7eKBygddNxQvVt4aq-yx-V3OM_nvDFkpNpgxT5ywjsza5My
oryYzVxodOYddebThcTUSpYVUgkUUcuCw_tuxQddjuTw4VLGJptrr5FFrZfkoH5G3_K2wg5UG3tK2wY7UkfTYWS000000000000000000000000000000000
y
}

