sprite $ClearPass_Onboard [96x96/16z] {
xPY9ZYCX34HnEJxu_n_UqDcI1dBH4NiEJn9zFuyADvEa_CTiDflDPhE1hUGowgCkHZezQhMLr1gTtwgjJRlMbNwv72CETHjbfR_PWcDBUhKVjUaknzYYN-Od
KIyS9IfM-qV-X7ynlzrliXByR_Ex_TlVi_qmZmmtFDS0gWhvnA-HnF7OhafmrY-U6OOhwfdvABtc5Ib516tlb1-HgJo0FohGES63ERz41hwwxWkeOiXAvlsU
8RqjiuyOr1DHdVRZi866jcCPZsn4mOepVa-x5M4rAOL7J4VkmbATzClDvPcuwRtTaTu9-x3q66NEZvO52nnwdYIY6EQM9sVyciwSqf87BIK2bGUjf3hdj-I1
PzFJZyT-q7lUZwJreL_1Lg9_FX_ggPK-7x2Bsd3IZmpgNJmJZ-QN4yksdvbVqZNcKO2X4LL6_tDllZ_PwvBfd6JXszO7rAzhgkVMXt1saRTJ_d1zK7IPpVcB
tIrd1L88ct9WVlraw7t7zZ3uBlnfltYcOVndCnR0bxXE-1bHkYdKWk_005e5kS8kclCJU1AJyWY14ldeyucQkpEcXmYkoFvyIBR_4xP_-sFzxvFzSQoaZd-l
rRM4Z8bTLeBoVxFPR3O_
}

