sprite $ClearPass_Policy_Management [446x446/16z] {
xDf7UiGW383HfK3tlsywIvJ66FFDUyja-kzkvNy100000000000000000000000000000000000000000000000000000000043q2z2EJaT6BjNwbSWktZlh
NxyUsKwEHnmSZwS_s9Ilxq8xUDNZcTSy-IABLrkFbWiFEzilJo1PkwjQj-6y9XxBukNUpQPyvzNZ0VLQeXxghQ8UyQxwr_n_c-lHS_eBjPxJU-NZNt7FUWxm
Mn-obOtsrnElLnCbKJnlRptnXacyej1jwgbN_I_cpVkcUk8LYOf2jwmdNr6eU5QxGptrVXjsK4yzzMmv7RKKOVSTjU2CmTbwtF1iNRuVptH57bJFLUgOprgs
t5QF4I9ZEj-NhRYnjFl-7iMyP1I_tCYZNira1EgXtahgeHxg3UfTZzFhePvwg8TwQwY7UgYdddhgeHwkKa-unu1wgAUUUkgX7kfDg8TwgAUUUkgX7keLr4Cz
r5DFFVLG3_KAwg4UwgcdddgeXte5zL0FzTHJJptKGxsAUgY7UkgffnxgeLvDFTIBo4UAL_RkOCbX58W1w25Lg57n_z-xUzlnp8Is8xCrRgHhkBqIIGm6WCi2
RAmNxRy4RmzUNyAR4vqa1qbsxAU7zZqBw1RveNDy3VjUUj5-2-wsEmQy9U3ucOvjzAAzomAxn4-mI_mAw2LuA_XUau1YOhmDiO4UsZGXuyr3ANrCmgYlrvA4
YhUIRypJY-kXfGaDRoNVoD9hwxKJWOAN1yAqcGQLzQ8jvSDh8L-C4o7gwg6TYrIzFCAycQPmzzgFH4JSLhxNsTmoRp8YelymHLKzl4MwfNnuYwJhCRxJlMCj
sxtt3KEqGu9wzK3UoVV-jsKSFukQUZ43Wbm-p80Wwe47lDc7HRitzpdoGTLBcYbzw_MvBUhhaLE-42VE5FTgvkN20RU0tbmddLarFMJTL2PE97oihXSfhwPt
aJTFNgsDzC3VyWozIByOKKGljz7rSZnzwioR5RNraDjWhHvNwc7xxl71UkJMtLkl1-kjx1uUhEUPC_ohvHd_znxsZm7R_sE8RVwjL-zUMwo7bFTYHe8JzP-K
9JeBdb8ddmlbIpulliOGSrm8UkjNYAPu8qfsBwPy2rTdTJnYpFZw1gkpRE_vSF_EYAFimfqHw1FQahkIZaRu-xkICDwzijUFi3lj20J9MBSZ40TKHOySnx23
9CXnJApLysvS27eRxyPbyqxuwc-X1DVgyREWZpoTbVKeD4_cM_y6MB2sNixdjo__i1wV_EOp4xpwUeXasXGZu4dVVGnkVk87ddlY1y4zz431Jk0ZzG2TIV4A
w2L197PQWAHtIX3yvR7BJdeaX6qiwbgx7dIIWuDa9tm-vvA094XmGU3pEHthfR6UzQo7Q4aY5Z_e13yCefDZ4lP0OJsqKmckFR15F15t3bX-VIyFXDwjgjyu
5wBilfQ5VAzB4PwGvNpLpsl90wbuUGIyBFNtKkUHyF90c3Qpz7fwxM92cZRp24VCfUdLzA9TZL2zcyiN7DTIhdjjfTxhamZLIuDjz7I-rs8zZgk9MdgnL6yj
NumlEMVCMdfdMJxHmtcLP5m-SVQJcrxgwd4MLG-SHjJZD3lenLGYqPDVIDVqEgVPNO-Y7X-iv-xHUkwUzTmzTyzwxfxrt3thkNlkdlNSFUkvUzPpzzmzwxbx
rdFtfBXxj9wxPprtpzspdhjdFNVFUkwUksSzTyzwxfxrui5wIF3gwt6n7bPsZycu-dfn3a_Nu_rwaLIllXwPZyhrSZyAUlEp9TXhw-K11JqXkPwU-dhyythM
ivxrh6SzwrdFUf4CKlMIWP9Uz7zJNYyV2aal7oxePKCPVbA6HprhEOx4fdeeiSRmlEvvXIWUl49aFQ-j5z1pzwpdxbdFtREUk-VkMS_TivwxPprtpzt31Jxy
PJsVAfuDrVI8v35dJRquMJxfFeOSHRwFeGlLUwuUsYc-MsxJmBru18zyUKM7xo42pmR_vqqsfmQXc5xiT8iKg-bHq5l21rx8xlVl8OI9CmrMLe-CbHUu-UPI
BiMZRovb27WwdsyD5XCFlh4xnlb4IJt6wjloTJnzxcImfXv3mSkp4e-WWFSSFPsFdmQ2NHfqvdQThAj74cdlb022NHQ0dD4HbF9FUtPknJ0C0r4m5B3z5-oG
1HWFz35JWhvutw-7Ukgffvvwwg6UUkgfXtgefvvwwg4Uwgcdddgefvvwwg4UwgcdddgeXthggQSUwgcdddgeXthggQSUwg6UUkgfXthggQTUPmTZtxpwUB9D
lBbwsSX7zJ7w9rGM67c3Uus-XxpfwQyZtj7NKFdQmKS6z1ta-Tvyd7W_bC_8-_ryuXsr792Cgjv3vcsyCh3s6W000000000000000000000000000000003m
0W
}

