sprite $ClearPass_Exchange [93x93/16z] {
xTZLWUj044JH0i5q_W4_N1BykMQnhvcERR647rhNTLtNTHwLQ-F1LaNR3_XM6v5ALJpYHgvHYk7xCA0n22nZo-AkslyAjG1LfIZEgWrOglpN6OpYu3zA_w-9
97xjYeyzLvtnP1TyTQx9mxpnngM9kArvk6mbyQkUnAzw5AUFyVavFOfVRRq-oOTnMVT3HI7yQkVnWvt6ISp3WK-EDzvuuvg8svg6syOit3QJEErR6mxWqCkQ
qwVm07xGSTMHm07oTRY8Jo64tuxHF0vRyt084t4qtlY6MApYknrNn3AIDd6AiV3ZwxhkDm
}

