sprite $ClearPass_OnGuard [93x93/16z] {
xTW7ZcCn38DXaNp5kl-55wc2OzGDf-kVFaa-uydfyNthkgxhkWxo5I_jQMnmifLvsXev9lp8FNnbOiQt-E_0otVY-NqaNJZpSjXRNiGpXnM_iET5k12P2IkE
SoY2uqJ4Dewmucih3byBRktpSF_C6syS4knusHBCUDcan8_0RsxfHXoIyFY59hnerI58iE6iZQobwC2XefT_lejJ8c89b6Z0Yvx21-6W2STgGBgiQi4LBqcu
u8ODZGMdMFytuv32XbE8TIW1qO13MePIQxw5r_6Bqr9IE70ADuqrb805BqT2NRabMF3QGb6g1JqufTSxSeeUl6PGf1GklAPXVzwoRXy45xxkdvnu3QP6RyH3
uhAG3I-T4hnuFIjIsHQyTB9i2rwndWpvy0heborkl77CRoKDqTMUEQs5aSxscC9--b9yO5tNTVy
}

