sprite $ClearPass_Onboard [446x446/16z] {
xDi7hYCv3411WI04wlu7tfsSEL6MVgX2ThOVsEuu7W8000000000000000000000000000000000000000000000000000000028YFbeP4ICxNBMEeAQiRdT
qNJix1Tp7KPkYrVhEEROuqeyvckF9zzSbn3ZNyMwXVcSHu_O-QzNCn-CkNFuulSt8Tc_VRPlmNce7L_aorslLECCObkzveNEC7npLxqOXp3NH_Niwf47wg7U
TUeH4Hlkkb2FcBLMLNPthPe_Z5JrzgwuMa-xzK55VqP9zljKPbohHwtsHyhrMVOxnEfMFN9zeRujr9PjzaQVhKUjDj5SRTbONuahzSZL9rfzejaSXxrPJxtr
pNnrzQg9VhGUwni_2PlDqwxLerxcx5boZf_CthnMZtx0va_cyYVHyquzgYqqiYyKrOpUlNg6BvkoJQ7cQLVgoJVxmQmORRuSr-lPJLqvlfFLNb0PrNGzNK-_
dDdyGDdSrppjMTP3lPvwg8Twwgcd7kgXNaEz2r1FFTH3FVNKKm_rKE_drAjJU42zZ4DuplivKQ-X7kgXddhggOTwgDTG3_LGJptrr4Czr6keXtgefvvwwg4U
whNKGptKKqyzzL0FzNhgeHxggQUUUgY7UZtrK0_rr5DFFTH3lPvwg7UVUgY7UZtr_cVlZdRhL68e3BF6ihpV_udFrLRhqphzAIPqd5YzAo8ItrvcPW3uB3r9
zbD9nxzL-ga6w3MMpDqZNZzLXBkP_WstPR_KMXgjn-MoMpPqwLav-w2MPkfnkjUVAlof2ARCDG3EqZEF5oftFM1di9Q-e9x5YrTyjj-oCwMlfQTaXyhjoPR9
_URhfTDTU_xwxRZVV3qLTi3lWVCThlKbz83TS-rJTg4qK8ytJNzNFDK-bzMrtWNYDrJFea1nwOUB9AycyQvF3zwIw2HUW_NavNISJmZ3xiAhvVZeHWFqEDwR
hbv7-wp1Yu0505n3zHJWB8QcXdVm2IoYCB-HUWRiQ6Rx-GJiAFj0FOiBmm-Bc_b8p-GZrKtrUF929wDnAzz2TZn-m_HqUTecluzFSE31_KRfoHi6_RVnBHmy
pZT9B_WPZv_zx9xagUKtiEReULDebFbq1rvNX3L5pziYa_cYXQzlhgtCDqDFqRVEbVdy2JpEjuyUn-iS_rXltrJhtjO4lUx37QbtjaQlUVYg_VMikTLbFk_5
Q-RRNa_UYPVu6iAi9Zn90dpRwLbZd-lV9-XpF702-znCB_ZyZ5TNdjM3btQHThhsrhCFcXnu6gVOKj4JlkPP-WA_YPtq56L8p2FSyOCgRkMFecM4eOu0Wn_5
JdfUPiJnagVUcrQzioDwFG4k6l8cUZnwGeqlGrcrvuQpNcVtpQ7UMAySiaJA99jnH9Ng9wEdf0V2ju-Ubm6XOtwbtbk4pvwFdcMeDK1FKURZnVZavNP-fNNo
8yntOkltgBlgMHsFO5ThFIaVhFcUJqrFtonKjQdU1_4IkKL9zLNTBAjh1rujU0A_ZOtqz55lSy3t0LxkotwjvpMTz6RfMJhoaAzEdkeznAKZlrgY1wAzarvk
ROoFu-KTM4FZxCJBluuTzVA84_1HFDuwUUFilq2HPBVMCtIhcS3_LQFEtX4dzw_ZfRtrBAr4mlJnvEKJd_vUJmrz4_o5pVIyw6k43-4TXlNwJtkvRyxNutmY
U7b2QN-lrzKtwotMrdfsS3wCb_Nyh_NMNJV4Q6kzD5_WV12Fnxif63MUGBptrGkTURm8uBNggR5lvfgkbmtElzz33NeDDsrEqZi_87I0rwndL_IKyFRLQ-fg
3l0Uq4EJXM-zmodUytevUekTMsVh7LxWKRrGjnuVRtxhoGiykfJQhIS9zSrllRHzmcFPwzSJM01xzyrllPIZj43po7bFwQZJyUPyFTuwGy_fWSjs0CKsrhFK
0maUvUlNg_C55bb6pXYK600UuElJMr3Fm2BBz9KoXdUUp-xNM_LauLiluK6--wyn92GmtXnuZI7oy97ZSJw_wVhUIdnul9bBSwxEShm0VBTVMxVa1FhcO3q_
WUTom0ScwroFyW4yCDtRxfwoE8Dt79ZFRhkdBETiWSd2jBkISZ8u7kVpbliv5rkBrideQNEzIAsJuW4-yWUudh5tLW6yENVZPXcETuBFxdsEmP8Nw9k3dcF8
1C9ud2_llrzFLbN3_lTw0WpY0JxUE7dhn7nSO-skftJq8HxdouspFNnP0FJDKKzVPW2ZU9pFsvvRNu3W98Q8ziDwF7mEyJYV6jyP0OH97npmpWWuhYZnQZuU
xBPu2E21VM-l5qSgg_5guc87eQjw9intUaYa4UyfizxtjNYXUg8M2SXYUBNvn7S4ChpC5m9lGEiEN-PJG_JsqLDrarZ2m_wjqSjZ4cIy6gAtaTxXHKQSuUKj
6zPPQXYoLSDuQ2iz5USj9Jp6PuNftIyLLx49yjv9Zxy0t18Us4Kul73V_oZNEfkZCU-4LnIViT7xPTDbvKtrlzqsH0zVSTL9YJNbUmo7t_EfT0kOtVuFCd0-
RQlN_zsWN79tltp4THEVrbhIX6-0WRdTSxNQ-OPzBTyx-THzbAsJJvB6wFNpMNGdM92F1rapzFg_D-fuYivhTV4fxMDplJovwnXvAitH7-2Z8TvHZ_FvLRnN
FF2jVBuNJT3BBU_goSyQsY-xXAuB0TvOZ_E5dGzUcru_dyp6wF5tGd2xUANoexLam0y4Ry1v3_9nFu5N4dJpcSxRJHXpyeSi0_d9_DM7nsyVMsfm7w2NnntP
p_vexgyUFAx0_RGCu6skbrTASeLBPSTynowLtxlaoG6N6S0RefUxPqwWzAjSeWEJnSRuPS3VW4ZWDlbPUfalcuIxsxlSFL9CmLIZdI-hBFsejQme7LFryg9d
OVF-LnGOv_HtJruwXkhbkHie5Bp-KeFT03tSFdbr1gy_VcEkplB19w_ejEltqp5RBvTvM-xwIwl1RhBU8VEstFMNPBYMHjtNmW4Z29qTJvGMZjqiFLvoZp_G
wNYij43gPkhn7kLUo3r01nPLqXBCO3rUCdEFU9Ud4VZZfMoe13TSxx_swzj6eYW40E0JGWZwR_YIS_cozi-KWEUZ00000000000087i00000iWS000000000
043jPo_FWz3p8zVAu47DHwwrJCw_Bdu4ecThNSNywOoxeth-BCpWFtrtp3-rDeGVZxK3wF6eSxEOvw1ZwtTyF6BhzNyyykoeUJXoyu5yD3jlJrJFmr1vTaNM
F0ATVtq70000000000000000000000000000000000305m
}

