sprite $ClearPass_QuickConnect [96x96/16z] {
xPG5TaKX34IPO2VxNt0bTKYDCzK_z-j3ReAMGuGGGWWXsg1YYtuucVP2R-wZ4va-N_XRFFE0EzEFXjj9YE_MGFVxhGxnRUwJx0ypYeM_nJSv_-uzzc2x_Puj
z_D8_M1Ycv_Cr_l_mldAaLz--UMN7sPuUYLbyJhqeov4MOQT-2rwFcSh2wBim9-aXIpLACQd_HQgh0nP-O5_zqIULi7mrzVznij_BIj4lvMKIfYVPVyispOB
URJ_3Ri-2Nko_qELOadLsVs3B0BsqARx_oF8Bx_yyiillxclyNmIyJNVvbmcrXbhLCfF8uGGrm
}

