sprite $ClearPass_Guest_Access [96x96/16z] {
xTQ5RaKn38FXfAvQ-VqVU8nPHPEpNV1_GVmTBCIlSyuvvvoRIzaiUcvgs-NioQcCdF6rnHdA9fVI1yg_rWUvNk_niqIe_Kdk5tb5R7Ag_TnxlFndn7Zvr_gr
ev_AVlhY-lrh65_sxTktdpYLCX_dKkGFu7ZGeVAFqhWoFv6j_W2oqmy0sU97HfG3QFmQW5O_0CZynBchyC-bylwS-URtitbyDSyFqUb7uORdV_7wg5_V-_Sd
rxz_is_V_WfbrGEvbP6e1zIseZIWRCJ_vfnpZm
}

