sprite $ClearPass_Policy_Management [446x446/16z] {
xDfLekCW681H8EZ-5ppk4qPkABbopcEz_Mhm9rm600000000000000000000000000000000000000000000000000000000001f0-93qfNMTw3cvUtQs8QU
OrWdbh4L_GYhf3usevUN78yr-M8RTo271SfuiVps7UCcr1YkgkCk76l_ilG7O_oeBlpLwpM5HoEtyLsu9jOB_u6ukgsLbYqNQjY2rCTNUTajfR07TNpLBjOR
N_KOzY2lhzTsrUDGRqezrBkVUiIZr5fBYYTdfL8_o2dyBkN9MNVKixnkluUeytb1xb_diF7MUXRNaqQnpcVbUNpJudtrn9jsgFDfNHu_g3VLeuuVvVbejF_X
W8LqIptYc2TguoV7DEoe--enpp1Y-6xyhCmFDsdFefvwULwlpUlrfDu9zTJppUbVIteM_rgO9oed5SvAnFwILmnMw_tbhDRjb8tdkbCct_mbQZyirMVvxjsb
vYYjrtg44wdKtce99sAkhTTo-uI8cC9KYd--cdfRcAsZddhggOTwg3UdNefxaDVN6sqJ-jfw-w6UUgY7UXkeXtgRgOTws2cpKsQNsem1zIvI3_LGRp7rK0_r
vjH3FTHJJptrK0_rvjH3FTHJJptrK0_rvjH3FTHJJptrK0_rvjH3FTHJJptrK0_rvjH3FTHJJptrK0_rvjH3lPXIEd9AASRm2376bDwpSvw9aV8m0BKgkDp_
kb_TNKm68p9oceRtRqkKyc89sS807n4Ta9br5MR2LxG7nAA_4662wRyPj84uDJmjERTVrBmglPWz5D4zmZ3J7Rq5qomurxQdhlX2zb3q28BfxdeGvhXhHopq
8lQ0TO1GcW3I24nUOAdjcA8lOGz4nz17olFhezp6B13V7egUuQr-GEUumdDjPsICRWz5ps6dF0j7S2hjd0onxO6e1VdIfWKwVXJDOWbj3qHjq2Nlm_J1saog
HhR7-i2ZJm5dtloOqgUFhihZNt5SUt3Oe0EAp2bznmqUu8pIXtLdgQuC081lM_SSrnwFcZlW6RaJXnaItRaJyhwvWotslWNagFPGnlcHnB_ug0TESggtMSYx
222xVuEWzbWtwEo1Hj1RzHu3E2lVqZPMI7jwVPLZsWCvRShHqJKOVYotDb1Fc_9UtnBJNg_dA1PrYyzf3uu4U58djmqwNve5GzfZQstrTbs94qsxZiIvfYDg
PpUaFR4wEdAbJkpas7h7678gfIDaiwSXxPdFb20UUxQRAVPMi0hZ6j4URFRGj2SVOG-VBdnKhOSIoB7jeMaliSCUs5KDJ7jsjrVPheonxSae4lq0UvIEaVds
RdktlTlUdJd1NVVyJor-UqtDqxySpLxyZW6DZY5-juxgjlVntNf1g-mjqNVASA3NirE6bXnqx9IjcnorZlyuf3qoXX-SkzHWxb8xx74xtohJyBlK8AUL3sNY
2L6QVK9KJa-8gFld5UAVplAPF4NlO0IUkaNtwUnONfMean7QmVQ_sLoVVl1EHj39z4ClhnLuZQaa_DYf9F1F9VMihIFBS2f9KbHxg3kO_W-99DeZSyOvSUf4
8EqSrRpy7uQNqdeAlCuqhlo7lW6_vJJkslRKMagfrJ6D6t8Idhxf97nfDaiAR2-XhOyTuS4XpuHiVHb2sxDNdoGNPE79-zKXxtxxqgyFNU6rj3DMI97jsVeu
kJ7IfWiknieBOC_Y1zywW6jjnrI15C6U3R6HDNs0aJLTI3vqjt9ACUpP0CcZEvmOtt3d0RKSk8CKo9uDiaZNjC-_wSfmvm1uBRLkJVj2wILlcJD-jau0_mS-
83pnyX_ATD_mU7FRk-tTzcvxGRdj0P6C8PfnuUuGH5ziMSgOHG5YsRCRlPcD7w3ZVCy29JU3cWNZsaFHAp1utDc0uqfSYynHxP5UHD2_lpbvjrfhkqRLcFP8
huCUUJRea6SYmMUfRGGyEvisw91dKIde6s3NOTUfdWqyVSMSJOPmzbZV1xZIfiqJazINaMZsGFJZ5X_G-m77F995ZcQFj4D6F5dvoC2v-AHrr16j0uBPuyuB
8Ho3tFd39vSU8en0DEoPTneNPHhGJrLBB7iW3ulAwkV9-VRGj5SmeMxow5g2NOFPk_eumaRXyofvmXvU7NHVki8NoXvU7RV59-pzpTwTP4KI0p4OLiYEJChc
_kVjNl6OiIgVUuZIlyuL7pDKgBr4GPg2tjfUHf_bzVfElVYFzQm7wrdFUjQpdlMiPpthMSzwrhEUzQndFUjPpthMivxrh6SzwrdFUjQpdlMiPpthMSzwrhEU
zQndFUjTHP5Unw3hXV2VkweUNlJEHzLhoYl0T3rG-D1Jz5wFISsegxV4byGUlH3mLBqufx15L58FxCAzJbaF23O6TkW1_McC90hh2SbwShhU_lRhMSzwrhEU
zQndFUjPBoB-MpsIV6IzwFcxjaqlA8m8Y7fy6cFSZdXOlSX5vMk_QscnGOz3EDTIKY-bCtEwdl2iflTwtRG_g5xyntzZ2Fzzpt_Vivxrh6SzwwrdFUjPpthM
ivxrV9_JUjQpNWQ-grsxIuszTwdRmhzp5jIBNBpKdzVqYE-BQpVX3tpNhUfDUFIri-BC2tiC2toyjiSmkFI9ypdhRg7qjRsRExTG66juJPaXMldAnrVJcAsO
7b-vPEFdjTSFOJqkZg7mlWstFj-CeNpU-Gfle9WUyj1g46fwqXjXOOZezIDdEJrgU1dOEW9621tFKfFbz90xrnEvTJqnRfBUYNfwbF02M_a8gJu5lD4Awg4B
Ujmrr-tLuFry3NeA7zJYNCOxevAUpfSDznJ2HvxUEPVivXaegeUMmbQ-N530ayknW3TweAmUuaU_P418zYFkZJz-yPi7WNfwhmls_AhEmCNY6y5VxTV7OG0X
3011CgZ_Xlrn3g_ZS9ffOGbIoVdgsp7ZIoyF_c-iXtgejurwgAUUUkgX7kgffvvwg8Twwgcd7kgffvvwg8Twwgcd7kgXddhggOTwwgcd7kgXtZdgePvwwgc7
UgYdddhgeHvjMxqLJqxLO-ogbsSy6Ua0tjoOVh7UY6SjdUNgHKtNz7YsUheTPSQBdAwfAruP_LQC5Q_CRVVuFEgkvUCyPaw_zVAnQhekh_WEzAtxntdY_S_R
9zwBCk8eLalxvBRY74P9UzMn3XHahJbosY-Nscz6AoMT0G0000000000000000000000000000000F
}

