sprite $620 [93x93/16z] {
xTo7SYGf301GP1bAy_yVVFcO3NFjr5Dx3UzjZZObeffMkom0000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000WBgtjApF7gDk5rHWzisqeUjLj1TMpxIRhjepAjfUyBIMDl6im-g9kKrtOdk7hSy_M
UrvOxtFFNDiDlSfeLvTZBdrxRLagsW9YR3RuQgcb8cPpTfeuns9JIMwrPyd5UcD5sq2CrHhRvzIvpKczQv4zYwdJSU6SbNnia-7C1HjLkKdmgYrbZuHBrfhD
ZDck7O8tbfrJUYp_NAXooKFioejVrj8DN3fyqTSDtXnzgywUMSi_XiwnQXEpRbEDLIrwKQBNRJELRf09d-09dsdpmwelatyt-gv-HXzz3xLC-68s9RDj8cQF
hJNoHrNHDXAZRWjSbiZPYitq5URE3UuP7wyOwGxB5MLTlkdZGGUCbzSZqIucntTwB7F9yr7_Uns7NkFYYQIAx_uWsrNbeotBUCDBEn8Hpov0Sl_PmMzECtXJ
BlAsHdymzFApqPiTklAvMRqHtt-a6Fy-S8t-PpZYNT6RsywhJvpjjB6NDRl34oUBkd-ad8jtpZyUxuhUd7dYsj7hxJiluz3hUwRYvr_IxpCIEVlWt8GThdjZ
WHV33jRjFDfqlhnd8HtFZjuCr7WpUYtxTx9DjKJqpjy6FN-Fd0_7tWpkWSMY5-qy3zUzo56Vqtl6pvzndpl6-xfNUV_ZJouSefUZQiIPZ-whn_V__-ZtZvJj
Jtt-BAkgVtZJ9dfJnCdtBgh_ntdouBmdUYU9-hy-0XUzyylLrUXteqxSmehUyw_DLFnqVRr-LVIiU-FJqPj3jzwHvnIzazuLg3njx4NEiJS_vVevprctIj4x
QOjIyRLrx_wbVbZtSlxwGPvpEk6y9zTo_fvpPieUvrgcBN8jSNRdctdEK-_Pvr6USzVepKz_F3dFcNN6o3j_xEKIqQjdhNjJvgXF6Fc71xsZdx7kpGwW-jf1
dlDSlQfwFCXpzazVoLhWNijfuW_jAOxpd9ylNgQWtA-WvcgVWsyxyr6kwciNb0kKR-xUOrZW7Q8HRIkpp7yiKVzfPBiUfH1hNa38Q7l8FXkzKechiOLLQdgf
6N5XwhLSc5f9QuX-sqxFfKfWr6qRy-d4CYApR-A4in400000000000000000000000000000000000000000000000000000000000000000000000000000
00000030xm
}

