sprite $620 [96x96/16z] {
xT9LiiLW309WCXmcoVuNVDsrzBLyTVaTN5H4H4H4H4H4H5274Jxjz46pWctaz0KkRk6u5JmSmQ2bE_cqU4lGUq9RexLnvKJdzgpmgte-FLwwMz3WcDe2wlO4
ZtukkXnfk00a4TpJqQm2k6zcHW1H3q0xqVNjHmhGlXgI0wX42ZXHF_6P-l7q4O5XI_snVXmqZHEwZQZHveIQixOXhYqY8Y8Y8ku1
}

