sprite $650 [446x446/16z] {
xTo7akCe40PWkdgXuFqV-89lWuQnvDkCsE_Rw311_YMwmTIK7mO000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000020sKluaaRMslfDQi_mPQkzzRAVtbcLtMSU-UesoiQXzRArdsLRsiRlUX7TdBSgE
SXoqbXjf_TY-HDbF7PzisPtLButqVl75bsFBsBqmzDmtlBAjjkT1PZ-lwNiUPsxOh_HQjZMVfliKzFC1PT_wtbI36zggmiTzmtEsniaiQ6UvItnnnsPJbpQt
OBNyAexRGHXpwWBZ_mBrNkzrwyCFt_qlvEpDMuuSrfZcVYNA9OlMj_wsBLfhDYrQ2yzAOTousVHot7ELmSnXtfeJ3xJnITublD4_ONoMTzujJPPbnNY17ijF
5SwHoyzjpj7AedAyH5zxuEpv56tjeRDVrMLYwOilhhUmqCV3qcKl2vSjUJgr5fJzgLO-6m_Di7wZZhl7r1WiFt36XsToxwfsfavDUQmxgfT_HNikohQYlvwW
vxhfjSEmyA4zz-7FllPYFEIowRK5qbkjxitNPouxSjJjqpkNpxsxFjkIwHsRbkVXXKqIgwTttdD6kPlQMgkj_VTFBGzvkAlLA5-XBf_ULiORpzw2pZkb9xsK
tgAajm7fxQ6_hdiRz9nVCvU9sWwobClRjPHiH-MTk7n-b3VQzHUVvFJeoNtp_MUzQ5zyhQL-zQB4TBj7J8z7Vt6op-jIxNmZoVHOU_VDV8VNrsIidbx_-lJg
bDxyU8mVc5wV7glIczvZc4bl_LNg70-nLNfPQtxvLHvgJlUzJc_zTuXoFDHDqllwjPRv_lFYigBnq7TFBxy-lRajNr6RXaxfdOnETzmHABq-dTvh6G_jU-Tx
-GlcUx-yxgs_wUx_RjHl_I1BrBUtotmxfzkpR6-tJqO_Q56Eebr_iKdsWreUJhwT-SkklXbtbXSd5zdNVdMYdvTbsbHObfElrjs5rtFzDrHwUuj-WnzubUCQ
KUuQ7ptBogADSzHIxXeVMPQNlO_tw2tB7MHzZoZN00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000Fu6
}

