sprite $650 [93x93/16z] {
xTFLOKGX50JG0QxsN_0AR5oGhyYSfxZZbo4Y8Y8Y8Y8YAatMLMpH35yMwGNhF1is58-AHIMYO8-jzgQ65-pI52neQJWWgIkPl1wnj7c_pqrdnXpxIhqfqC3t
Gih-iT2ySTGi-5RMzSghIAazRxb3oJgh7CCzyrt_l4Jqdp9-DA9AXFGqO5vvjEU5jSpm_Z40rlySaFwJOwhlJxb7AJ2V5hStbTyU7PLh__EH4fcZlIgPWlx2
V45RjjgrThlR-Bn4FFyy_iRpUALWmlAOuHmH4H4H4Lq1
}

