sprite $650 [96x96/16z] {
xT05ZiKm30JGiIqxcViVU3-KH8L4A_ppoX0JVfI8Y8Y8Y8Y8Y7XnH4yCIRQC0SKs5ZunnjaDJnKJewpJyKoZOq8nfWhvtxQTh9n49kvqjdcTXcj6nupu09Yu
5aH-E8OuFnnLk9Q4nniUYKptpCGcsttyXRcRkwyNlFdNyUaRhhctbj-FZ-87iKYoIDPoMKVGo02ETnvX5k6mvVb-FiROu-SIFyc-nE_rZN-y-pm7MR3b6KpS
gExpYeORribvWHyb8Y8Y8Y8l
}

