sprite $651 [93x93/16z] {
xSo5eIin34JH4TZIz5zmm1jc9nyUw2oQBhwSKaeffPHILFLYB3WXn_6yHhAVj9Aadenv7C-ZmoZOymIYuMoS3M-YGIxY_IJM0eZV4QzunIjUSNLlxDxOV2_I
FSElnoQO8S6CLoNPy3hD44nmThpAs3576NYDis6MP0fUqEcO9v6Afu9Dts59mnET7n0yHiSyqGq83GyfnNm3KxXbY8w7BF5wtDrWRe1i0IsUnXSY0jd3XWpx
bV6J6OZCPGhFuqeiWkpZpaugW1mZswyq06OADHjh0g1tF2IqqtZBatYs4TzEZxYGYIGFyNGyrbCNPkDUFXl7luifMtvK6mMFIV1TQVX4AQMKKaefPGq
}

