sprite $651 [93x93/16z] {
xTs7SgCy0mLGQHIrzt_WhpeJ6IlhDVaBai_PQP0ocCiLFHl-1W0000000000000000000000000000000000000000000000000000000000000000000000
00000000000fVqhnF_MRSWm_59yl5h7KrZ-rLc8uBTtzfff-jbXj_6KvJ91QltTwHSNQ3qeuBJyiLWhF2EzyVB7q1-M7uOsg-9xsvVnwAdsYdDwc7hLmZzfd
QdXTwZCjdTocdcyAn7vJ_jLluldgrVAF-fCrdZwpl_skTfkCWSVLLE9XtvN3ozfzrs9kvuUxV5YiT5ki57WeJ7iOIklPFLL-YE3yOjMlgiNXjtEVLPdaUJAz
oPpJwUN9d07rOQMaXTEJNfRUXEv9J_VGlINedkv9J_UaftletXfqJ_UaftlIqprqRmswftlIqptfwHwwjmRTqptfwPxqT0_TMuFkwPxqT4zwkeVkhK7tT4zw
kYSztKFtrg1xkYSztPEUxg5xQz0ztPEUxabFzz2zDUYUxabFzwIdU-ZU6dHFzwIdUzBJFNHl3RgdUzBJFUdf7hgt1jtJFUdfdlHq3zrRW-xfdlHqJtgwX-uj
B0x-JQ_4BxVqugjkMQN9d5UDYtMSS_HUoQLIwg3_ezKlhV-ZlchykUESax-ipUUCIYaflabqkRM-dTPQ2jjBjM-hbRXtTgLlhUMmhzpwxhQjNypz3Mow-ukr
ZRk8ahQHIna-MarRXZT4bpRSexUXVViUQvOSjXI_yikxXTTstwsFMsZBSSlmMWuRYwtVr8tYAyCkOMknx1TVMVPmp6TDTTWUzrVQJkDCV7gyikq1MjgeUJcy
YTHlMjdcocOERoFLFOQRlEp5TuUUSJnJU2knhXzV7OwUtqqUFllQpIlX3UN-ARkokPwyyDN1rBQxOdj-5HG7cyuSN2xwV-twuufd2Z7yBpXdSh9Z53gEzkIs
qebVQgkUvhdKEuQNujzO9xxS-gTwGrlaHOVSVucomB2v8i_9rxuivOlz6MfSUAz7klZ0cMR8xT9d3UcmU4mtxciFd2aioFef_Myrp16lVC4brlU-kXbBcobV
NMiNthpJUm-SiJuzoimNFcV8u_tOz34JDt_-VQxSVqjBLz_jVPIvjqolhh3Z6tTxvHlfhRiNwdNJ6pUiyesFiA_IvreyV4i95pGEwXzxTsykvPmc_s88rpzi
YUC1Ljg_UkT7rn8lE-x7yA-FcR2QL4PnEky5-UBfjR2LraTbid_Bhw-ZkcHwqiiBZ9mdw9uBPRfttexfrKbIUOVkdKylbK6EzzFbE9r2F4m_o6MGZzE__jxZ
mepcNutV7NEMKTorUySDkXocys6uIeVfezGEZ_tqEx-u4z3IOMnC_x5hBUNxRoaNlixvQdhbQNfvnVHgVFAVgrpAymrBUh5TFRqQTqelvT5jltUSDnyvP-bT
-FvU6fPjb_HQ7-L9Ilb9zsRtho_ynm0tJg-ya5w9tttmUl6dagGtxruRVikr7spHlNMUvnoNBfyxtzk_U-NILu9Z-xtR3B7KBoKUfjFzT4qX7AQFOZvy_Muw
7wAkWppxtb4wBEhVOXt5-SUgyRkDh8QBAeTsZ2WNln2Sldy_b7pvFs5Jd_nb4k7rlC1xw-KUTJmKNVJjMT8Ak-OvoW9lqfmdFF49xxpSMdz0M-H8FARyW1X-
7m00000000000000000000000000000000000000000000000000000000000000000000000000000000000C2V
}

