sprite $7005 [446x446/16z] {
xTtfTgGg581HJXqKVFyNlZSzn2A3gPubxlqBxTclCEBAeii_1m0000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000042SGVbXHDPrtSwWhqlDA0-ZhcqxazxMB8yWbjwtq-bzYV8nxRQJwakM8zJMj_Cwcd_a
EhRh9x0DMYrl8ceVdXIM9V-zkgoj3_soVC34QpNZHAkNDjm-oqlatgwlUUwFLfHxnB8zE-VQAfUzNwzbHxI-NvaezswtMpmukhqSnU6vur7PH_lyEypdhjdN
A8DRPjxAatXdbEMByTm-Yl9a7zqEpusZMnbbVxbs8Eh1P_hst6Bic7-wNkxrTh7qyVxEtHM9ydwz-7trRZzIRrJxtTA1N8T7yHFElL4qA_TdsOUBSVQvDpuU
roYNTlSbBqevxTmRBSCpbeN2S1tEEFT6sItSIxR3Btd3nVwPUcKO_VIAuVXldbPvMKPZldWk4EEvBwFRhu_YVfJ3w95dhIkQUEaqhlmkc2_s3-zQvcBb5st-
n-uSybrpeP0nhRpeM-jb-oIkiN9GJptrr5DFFVNwPt3LUYq_WUMgzTRo2LJrpayzzTHJJptrr5DFFVNKKo-Up5bFlQNrrbjEMK-zlZsfPHVVpLLFlV5RfvQO
h9vwoxPR9gkdtZfnFVLg7pRwcAgUUYLtPQvwwXrJxssvtgibNXulnyTV3EUM-5lrr5ksUotgTgz7ZiSb--jl41hFzVmtzTJhKRV1G_NgThPwvjxZzVAeNlml
uyb7zRxyl3pJknPpRsszjI_lDEE3TorFF-tBprpEKi_SwyFv2LRhvjx5wfbxTTWMSAvwwfMitsKPgTVYaNfhgUFnorflrels4_NQKE_OU7TThrUlHtbJvBqe
vV0uNnr_aOCoo6Vnnldo8w9VRz-8-cd-pNMxNhtemwF0lA8DTv6BMBSXt-JnjbOk9OTzegRVQAsMQrdsRJcZp6bVoRHosSsI-fpzOhdiFe7ZWgptlcH4cKL4
Bcry3NF5V8E-pc8Rz5gkA9PjJk9zKNlVvkL_rQXjwdPhBPSMy_RhQnQYhgttFbEttji-xSYiopmoiqm70000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000_WC
}

