sprite $7005 [93x93/16z] {
xSu5LW0n40FGZ7VkVs7MS5l1oQzRNl5vY8Y8Y8Y8Y8ZKtg2umaQFrtKFnrbI7OAvl43c5bs2KtGC1M1JqRN8P9iksu3KK9pWdPZfLWIoWDwLMRRZiEYoNQe3
HrMFdNhWg0hiv2V2_Vl2RG0HUYbSL4KNymnpkmzNaqlXqPtTexgZswqx0N5RmzrF_pmmyQgeogpoAjEQTstj03iT7aEnYup4OTKLEsINu3ZBsY4DFnuH4H4H
4Tq
}

