sprite $7008 [93x93/16z] {
xT17OiGm24RXzuCQzxzmBAVto4uVleM0pPi2vwMKKaeffPHIIacrlwqL3bABKSjRQeiublSn7CHEt1Ew7pKwwqeqDeu9mv5a69gxpSjnDZQ6MDIYm7tSxkCt
5uOpQGnZXNeKVPIDC1QqM3EMueqLlXQlloBkTYokuT3hNCQ0EaPZswJvb7b1Yx13SOkAeiqb0cf4OzjCyoaH7UWHvLmSTmTpjttR7_dD7z9rChxJI_7fVFpb
l-Lud69G_FFZZMTa9ioC_T5yZiLBE0jwPqMBNej_IAaZZ2NMnaVrAivAAQMKKaefNG4
}

