sprite $7008 [96x96/16z] {
xT9LaWCn40DGgUrgM_S_SC0LPi_oHkz3FQX1F6LcPcPcPcPcnleCiLmqgJycjS12gLRmJErABC6k2Y38G06vYG9mjtpO0AGIyqhl79Cig8XHHyGc66C3T_qe
QiIageQ10BUn6xpOC4Jln9IKSaBJv0LQopcAkVwAER-odm2uZOZWIF0y06OkxGybe0v0KWKt6LNgs8IOKjlz2P_Rhy_l9xdBom0p-T7-dSnaR08ZIcR5pcVq
tth_7-j79L3APRy-epznuURxNzoVAfF74rEQUjPNPLTYKid-kWoyDpCpCpCpMmC
}

