sprite $7010 [93x93/16z] {
xT05ZWCn30LGEzzu_mllgCnDfkBzJs6EvJyY8Y8Y8Y8Y8etg1GcPXquRyn3jCilRPGsgXipGRCWgpRQvHwZiu1tJQzQDhw79xjojFuT6E_m7cPyFLzbBX_Yt
mzMFP080KHofzyJXE9BX3ZzatBRCtEMagWHr1CNtmyLaIsg2xkWj7rETMrdzEdQ8xuUFGq9FlFoUvShX4V1mH6p9FEBQaXiQWMFbyuT_38kbUK8YKqPtQ2Qw
Q-5mTOUvdS9YTs61Zos9kH-MRNbBzlLmiyOnZNMPyedtBsh8RaH4H4H4z0S
}

