sprite $7010 [96x96/16z] {
xT05WWCX30NGX1Yv_uLth6u3hFS_t7w5_Yi000000000035leKmjE3AyGTIgj9_KADJ6qh_aRljtuaYb3XnfBT-ZdMNmZZk5UqcjyYf-LA5dFCgObEVvJiGB
wc25NkVxPb-YEx6lZDDsvFE6D49ZQHPJknXEzvsF-SIq8r-KnEQgcPPByrpQQQXq3rVTaM-nrQ8wLRqtF0Znqf8lr_-F7WUdCxojBQ8b__d_4rMcEWsLULrh
P4h__oCN0wdoLAT1YTPr4LL-cHyI8RxK7leYdoF7EBqf0000003u
}

