sprite $7024 [93x93/16z] {
xTo7SjiW00PWni6Xzt_WxW6n6np92b7wVRr5eOk_J5aEFG00000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000003YGmWVJSobrhOzW5PhoJ5y6EcDmT5QYU53Y7NRWO-GNofjsuMMmsBnG7QKiDGuyDe3s3erXcLY
7ruj9Js0KkhsHqjXaLIxAJm6zlLSM2AtloUOi9lyIbmnQsw_rHIuJl-DXxmQzY2tLRDd-lidby3HJjpAchrcIu7Z4rYhQSMi6SCrc3tDcjVlp7BEVnT7XrRZ
-RFcawy9UB-ZGwfddj0jVcN18di5BbwwMJE69-ByNNni3WhlyQWjXHFaUkBiJ3grUwlhbVVRpSVBNKgJnyFO-bcJzTrS5Zm9Tl6oU49c_VOYhPerFNLOTn3X
-B6wnETThwJu7aZ3IdNTLnHe-RhXqGwCllNXKSDUsthyp-b9hot1Kz8hQGNAKzBBOGMoz8BqFYlf8JroAVdAwNaiM-E9wQM9y0inFoQzk9EiyQpqOfrAWU6P
w5IDuxr8EYkzL9yVN-g54CVoM1_Vrlws74CuqZxUrC_VwfehuwV9JaklFZ-zqdhvfbp7yhHzRhroKowp-aavjLwTVuXhhWrZhyOBfLUtNebZkOQszVAqVHdB
B-hRY_eoRLzlsWzsfZSQUgA4bJDdV6PwvOtfbGNf7Pyv--VWDPsMNan7XjxwiTScwRMRzdlJ2xcz-LiUOrf_tbkQtlgnT_sx5kkUzCvVz-PfL-bTTzsRZxsB
tNEE9zIn55-fIodr3TEQTQ-UC7DEEkK3tNF6sbhtAiFtKWvzNVf7tL3AxM_BCgOpbbiATIpVQJ-MyulUpg-sBxVjssjZiuHqPxDV-av9hUru-UVaUywkhrli
_xoMXZyz3iVLzBVKjMoVw0tE-_-u5jxi_7lEsFfCOXsIRKEfgxjf-SbUQAdzorLfRt-VVy-PxgLNXfPZbkNVwRNygTBRoj3V1yPUF3szUIPrbjxsoT8xDFR6
UyxrOwy-EFRAP5TIX_eysUNaoIvalcifxVNwDDO_SUobuPvpmTYRpvnZo-lVjHnBRnI7yzu5njwIUyxrwSsjN_UkF_RQszDB2z9Rj-TSVyzfx3q-Srhtvey3
Mtf6UjQz-bxfjQrNLwrx__kUCpqZlV8vnbwv-fupbywTdylntYlAzIhhNXac_CdflAMRzZVF68RwCjQtoJE5DfJlFgCOszT9UlbEAELUKDkWN6NF6LDlAE_u
zEs2yi7qjeyqzjnpxaZlkklUzJq-zje9Os_TFUVr7Pyvsv2UiVUXqckzdqrYwsNhtZgVyRpdsVh13qPUuBmdlU7PNlSZFZUzUjww9xtva0nx_SohbVnT-Lag
-QUnjDsfgsFfJilh6_znPViX7zNtTmrxbMqrIjWhjMqjMWgN7NoKwtwhE3M60s9jsogq4iCnkMnhK7BuNm40000000000000000000000000000000000000
00000000000000000000000000000000000000000000001V0G
}

