sprite $7024 [96x96/16z] {
xT07ZYun20DWOq42zp_mUxkP_BrbU_CdIzCz2Fmk8Y8Y8Y8Y8Y96VnlYdgYtyzl3ztAyLLJWEbOtl1qhRVd7wwwluUsxMHkLbSJxyRDLizuVZaJwEuiY3gBZ
7Pa3TjxFs63FtJbo_N0ucokV4b5N-eqRxFMgDb9nScZZhC_7MSLjw8a0hytlCpP2HxJcJvc7jZl4F1mUcnDksFD-fVyfdeY45pn7blUJZl8Nzw_lvwoVv4B_
t4_CnPmV8lO7s_eZ0Xv1LkLA_xgjlxK6R-rgV_AG6ackos05zoASNeO3gtVNSCBU6xuR4H4H4H7v3m
}

