sprite $7024 [93x93/16z] {
xTC5biD030DGMmEsxd_WCZVK98zszTymg1ZxHqH4H4H4H4IazDYamqPrzhf52rORvfcmZIgx3IaCjysGEP3Is6mF7Yn3IviDlqqaUzjDCkn5PEpf_Mk8Phln
KysFy58ly3m4N0icHWxOMUqt0CjekByyKRoMl8sIZ86HluTRzUzmkC5UIykybhYD8hCFZAwddzf0UDPpOJ72wU2ohmM04U3p0uDbFjmNVotluGuiUEUFBoCc
HtaDzzQArLOjIPz_vxRK9HmHpIFwK7ZtREV2YdCfXV25mFfwkhO6y3MyS5zfRtnNzbU9Y8Y8Y1m1
}

