sprite $7030 [446x446/16z] {
xTg9RkEy3WPGKOG4-VqV-2xv1zF8rnsdQLp7TyufDgP2jW_qGgMy7W000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000010HkOiQKTvDpJR6M7OnnkWjQtaVxQkvCRAyXUpB4nWjokdQSbNwhuxbUMGvKuvbClQm
J7gynr5pzCoiyMVKpDRl8Xord6JSHLSBpnspsjdle4NXKjzU6z-wTAATT_IC_heJh_ORULhVboTHp_aMSt7KVFKHh9QV4MrwJKxlW_FxtT4puqTFULbUoj6p
7ArFrxbNujQXTdVennxEBlSor9yuUZOt2iTVneyu-kgebmjmz3HUEUC79kt0y4Oj77qvRoXjy7BEjQR1osXN7aeRl8nB7pKDNlBArvfEVktAHqr7pnOlcm5a
_0YolwXZnXc_jEKblxQEiPoCvxklBwTZH7bANTu0zOBf8JtfvKbuGNgZbbDGntNJ8wJtHteFlKVDpBXcxz76D5SveFTYv-y3yT3VUYDkn46zLrlVKmlJZlQk
qM8UAUT1lTSVK6uOoyFQl9kJn_HUz0T4-Q8Szt9T__eGztg9LVrVqVVNb3xknQgkvMNowri8uzZUguUarvTxhRIfxXlVnLZNiV5zrRfCScEtifQvpXFI-mYd
7NpUUvlqsjkdLvV7zUbWcqTTSzQ-AyltqijLCktfzFBKz4eVNzywpp5w7dU_5tL7bABt_b4VbDUTjUodTqBlcNFglKlEEPttdXSdp3drtbNcd6sC5kNJgjUf
YkcMl9PDSn9Pye7UgsDAE3RMnBpcdrUFldfibUPwYX1JbULpTVf_JDM3ShdfX_LUdvv-hjfjvVHMHanLBPkoVSXOrzjhQhkpiQRLrPeiDx5Q4xbUy-W7cCNK
kp6UwEJ3vvnbkPcVEUPxpSsgJzKbz8qFq7Rwfa_LA5zm_9opvFJqTKelvhoMZIpRzJQrsuFfjIclljoKX-tCEOzFhpoTNjpRg6_MZnsnPYEz_bbwyL_xwNtw
4hDvpdcbtbllATIjFOO-FnPplR77q4gPwuqNwr7QNE-cDx_ft4zl_TRtco_B1NhlBUyOzjERwhwVtiPsoAUYJ_c-M-z9hqVPTO7UEtdMSdxl7J_dr7jDxvsG
djxJUm-cf_USzwADqJxcnvVfFRqtJurlJzQls7lF_wQiBfEOanhrpNilVlr_IkpzUo_othgESfFtwghESbEdDUjwOqt-J_rZrvoHuvSsfrUdnDwhzoxY-Dxh
qvbz_gRhk_MUzERUgykTTU-5tZiulRQgFq-lRltmDZzFJ-yTdrxvsFZVIM-zvNyJUk-yzBw_EzkMt_9ovprxwtMw6BvGx-czsU7dlJowzwHNDtilNv3UqcAL
tlJC_u_frIcz-B7qylTBvyVhFfjUZELczF-QYbNL7wckO_l3xIsVgwTUS7hfiJDVszEMqz6-SGGv6QEMP-LoChAKloK-uSrgNqv3h-MRQhPJa5d-KW000000
00000000000000000000000000000000000000000000000000000000000000000000000000000C2_0G
}

