sprite $7030 [93x93/16z] {
xT05YWGm30NG7q_kV-5joxWmLdJp-51N_2EjjTPQQwsrrbhJg9-auIal4_w5PZ8UuZNo8o_50rf1-9sMF_mIRC6PX2iKoTY4eWGNk2fZdxhw1KlRAX9d5jY6
2D2RpTKMmOc8i0ZHAkIsUOtpm15vlpdBmZYfIgzYhHf58bUfScXU8pqG43_Od6TaX6Q62BS8bWYDSFWgXG_Dmu9928eJi_lDtU66CAJE3AeggiIg8m9T9T4g
zBY654X12Qio9lDNcx_-biCQhiFcMgKuUhsvkwaxYVie3BPAvbNueyqD8eIav1URltRxBMQCd5KkkTuyEOB3EKTivhLOQwOoAUC3AItpm1bbRPM2ZxNMMckj
jTR-
}

