sprite $7030 [96x96/16z] {
xT07ijim40DGB8a51_U_S4BH-j-zJqls3MnriE3VKaeffPHIIYcbbDAepoHnXsnzPjWDDyHmnwT29gwYH-0Bqdfm-qFzoaHZcFYMox9kz_WYEN6a-ViIl-Zs
RKCd_K0iU5ViW6o0plgf9R0BAIcr9Z6be4H9M4VYZ7SC9w27ym_RijctWoFN4SEUfpWJxG08NFQ7JZ9bafaHXsFF_9i4joC1ScPQPximB_fdkj4StT4Sp-oF
D1CAI2k9ZVhZ_iVxi_SxrbdOna4yqx_sfSrZNkxFzVuWGJS_xdzizOFx6MVt65j_dFHtCsSwpPN-X35cfg5rjiWqXt14_hh0_wMKKaeffPJo1m
}

