sprite $7205 [93x93/16z] {
xSn5bWD130JH59Ro_WSsCzjTgndz5-l0Fz9QQwsrrbfhhJNBMcG4dagcBn9LYeUaIh5Kql60SGYMSoRk90DJQ9NWYWmQfhX_6Pan3nau6pNcebpC7LFfpTps
1B-98pZbRkvxYj_a4JHmDnSSqcE2dwZVpsiN3LHGXMA5dpZbsTpFSs8hqx0L6TYoJ6nfvcbWWGk2Z-PM2J8WLHWSm2W94iWo8nLHKIM8iNsG2a38-dXUvRjv
LkxdLVjvrVtSqnxCupGNcj2KQiIdr01uXAY9H3ZiSkwSRE22sbpuerfhhRNMMbi3
}

