sprite $7205 [93x93/16z] {
xTo9RkCW5mPGG83W_H_uNzealRCbJboNUkOSRSCueikd2_ZQQWe000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000oBcqBIWvf--ar3R6t8hHMolfUwWl9CVe9QrNndmDo_ChVSnNCThYHNFkmIXfcHR36rin
FuoQriWzxi6jbfBJ8-HIQelxJLjzN1arfsUGwxmQFQzODNVjlRInRFFBRU-vb_eHNrsrQlRq8l97VFqhm_kSEnPwM3sNhDYdOlNCOTNCQH_ArwwUzLFFckJ-
TSMGMonrJhKHbMxLN708FCaYRVKSwIX7hPhaTlHJXnnkJdBYL8V1ugove7rbrTHuwNCiQAzel9pdh4dSdVB9cd74bxnwELqZdFgvRxmKJUbLh-arJUbrrdSZ
svXN9NqDshmO-rRF4Heu-QiGQgQU-KrfsZyOdlZcjq3PSUUn6kt4wT5tf3UMONzwPHdccx4ZlRGCpzQUzAI7z3ZFlaTjvSorvws8KK-SdbTQHZualLpw8pa5
ijXaj9-UwTL3zhtI7olf6SABbJN2yDDhh_JjwT7c4zARFj-r4wOdlJRVbIFIoz8xwF7C-E4DefPMx7inF79__i_CvJfchqVTx-NoIBgXr8tAcJjbI6yNVKxK
dZlybezAh_NUmjNUMmwZUEGiFunoxxt-vbgSatnedpEr7oQg8twfyiFoN6Qybd_edPSHh_NBBGxXRls8VI-Fc4dkCsRIPuoXNKPnclxBjJWdntNAOkErnFHc
JR75siCePXclzSiepfaJeKlzvUdD0zApSfujFQUMddViUylI8xUuwvsvzZX_UcD-g8--px38F9vkr6tFvdfEsxNuo22INaj_rBQbb-UswNgSBZzzvcyB-fnd
Jg-U8Br_eFPAlIXtqylrwavwlqwNvwFfyftqmiVYlpUarsVKDhp5DCwNNlmHHhwNNfiNezzPEUDqvLvwVLwCTY-z4JxMReFsEBqnexxbFPXJfZTl7gONiwhx
qXlpQbjwiyNl83-PNjkMtlfzJtfgxt5wRM5w_ONQavxQMvIUVIyUX__vVQ-ThVRYj_RtrDwukQGNnFJ6rViqTGGnlQjBUYEewMPSpHQcVzT3UZVjX-_WbTgh
y-QlII-LcyiuI46voc4S_kUvwNAv2kEB_FkFvV21LsglZhyjlVCBBuiygBtyOENqV6-1q3iB-WXck1wK4NrcfonBRvyIRVbC_iJqsfBqY0cyOhxhxSqbauiH
BxNvPeHhcqOzpFahnfu_RZpcDy38EmftCLfwJPldelIYtEPYZ99UriPSYPxJ3hcEPUWblGm0000000000000000000000000000000000000000000000000
00000000000000000000000000000000003-2m
}

