sprite $7240_7220_7210 [93x93/16z] {
xT85ZiC030J0DTl_Vt3uoXGbmlF8KDmsWF-ZjTPQQwsrrbfh4dL8Ek4TAnS-GZC5Br6Ku2WlmmkIGJXEwaMCbUCKdCblJybnNdgNdPLndhex2rfsgaXSQU8q
n83i25TRy8zdV5yuouBm5cMjykK_9m7pLZ8LRQNuYMmOwi_XDfN3fpA48NMk4XHZ9QgOaIe__N6zlgonBrpTWQXYSMUjCh2xc9jEort11RdUV_l2eugMSAkI
9Logh2fzMNu9Po4aX-pwvsRB85wRGMPYfbFF1RBb5KGgKb8VmjcdYhd2vqgRgwPItgSipH8teiwbsA-rrbfhhRKs0W
}

