sprite $7240_7220_7210 [93x93/16z] {
xTo9ZgCu40PWbooLYlT_uBrtJJhdCdI3a--Rqpc0yQ_2ng1f-m8000000000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000YeZz5HBIpYSoiMfwYgZ9xjDE8_niSLRsTGj-K79NH3fVBHXmUNzIo6TLFLNZr3ESflro6
ojvxF4FlcNM2-A8sZi3qElhisLVPjGtaTs3vvI_jdJYm0wF6ljich8Q_EAZkAnjpzU8e-egs2sVF-OOyrdKmSRqR_2f_TgpjRIhEdZ7lMTFPixjG-DvrZtx0
RZZ_rNEuKFY9hfrwUSNSixVzTNFD7vrIM5wnRBrzosola7x0MPCJzdFETw7Wx3d_NDF2IvytF0ilMRFEDIsyn7h8Yn_1NWyiHHtme2thNe-P7tCd9WwFt3px
EHuL4wQ7zAJNZq7kaLux1Y4zwRqjwI4zelS-Sthkw-NRfnUFVin-Lw_UEht8f-Q-fHvld5xaSp7r7Td-uUbbEoVfvJJfnOlQF_8quvxQwrcloRmillxMivOv
nhse3JTViohZpQyOufbpJFzVLzPQLgPBB-PDJtfvjjeZDvJUQTOvwQ-AYsVMCxullQpAiUdH6ZEcswt-zRrQl_UurJ-hMlFRqilrvkEYrPwrnZ7q1wsuVc-9
jWFhd55ZMrTRljXrrBhLyk8wT5oLZlVoOMi7Lifo97GllNuhlRZCQxcHPOxMhEb9BtublLZPyBdTN6uurbuvSxQJfTT-8ht86ZBRNLahsNRNgrPphQYr_hpu
UfkXzcBdzFfouSNFLV-csKVUtbrx8COy_UDgBpUbjyHPqXi-STphqfkWzgAM6Z_pNktT--pzzB9MdwreUV7bQBbgBLVlzmFIct3SosKj7zPKB6iLZyQzg2_V
lsptbW_R-KfwQgy_whIXFKnl2Ebj6lVshhrTqwl-9BtSExsnQXnPrMUfFRKt-Y776l7sz8nxrNyolN6egtuzQ-sflJ5XxUDpfqpFk3VKzRxotEcflQ6kNymf
QozsI-z-Drqcad6ZnkxLtjVqOe_qHbH3nIVLNjnxy3RN_jbwV_hQdGtt9-sC9mSIexKIqzRUzlJU_3zGVVVQUp_HisVle_RVUDnxQ-zQUzBhUwINjzBh3zBh
rxKt4deXlVZaz4R_H6rFRsIoLFwfHkEgbRVUoyltNcoDBzPuxwsD7Xl_w1elrlR9qU78jb4iHwFQPdqv5XNje-8Jtj2pbeDG6UqNHHw4Q1yC000000000000
000000000000000000000000000000000000000000000000000000000000000000000000-1q
}

