sprite $1500_48p [93x93/16z] {
xTo9Rgiw401GZopRuly_-ArSKejNGdb0ZEuvsZnrr4uozPgqQKG000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000107CQdArThEuvQSgIFYDgc_uzM8jqiIflEGitfJhbDPw95kasPJaRBwHxH
flDHFp1hjbhoGTJQbI_IvKexSRT4r7RVuXUrcwavTppakvQy78dJNzKQj-mrS-AA5xR5utv5oDs2zDpYcJrBFEstWxXmzepQV-_nsNkQDJzrUrok-ROvNOSh
JkxFdJKT7QAEDckQFSUVDHqTsfdxs9mUnUmPxQDBdekNaewBQL7I8xYsFZw46M2R__XPqxLrVstwA6RFqgsSGp5xZdyfJNIpvx5Hcvx5nKjk0vpGEJG7HfqM
hNuKRVfX-Teq9cBFJcTGr2V_aGBvmTMZ_0RLKxrM1qBxMVKY3OHe7waUgiUHwkNwHawZClPohKyjd-f5hOEKZt6gHvJMSjUUbVRwNm1vRbyvzY8TOnviiMhN
xkj_owEjUzJbqhblb-aVhMiVFp7ajnB7FoNRjr-NbF6bdO-jUxTIlVZIpbtrXZ-jgrvVoMuS3byzwrxxPjsRnhmfi-UitJvpeptMkaVaMdFiR1_VSvPPtehY
dpFdBwcBNdthHxwBKld-nyUkrCh-j3UVnBieTr6VTXVTUDSoj_ijqTBRVzgYVOsY_n1f_UQHjV_0_IhAhoYwgElhaschHADBxTkqInzj95hMYUvBE-wyv-oV
-5Rr-ZeVhDxKFNBrCdIFF5YzqlMjgXTjLw9b8z6fhsoi4ZtghkhbowlNhgzUEQrwCVhOAwUClNRzsCiRrQlNZJrZpzYpxXbxnfvrpxetq7alpZxlrJVdlRZa
lDVrrGFLQmEDlLJsN66KUDCN1wAyYjAgRxPEj2msqxuWqTXCviQnTmG-ZOknP-pbEYjTbFzvu7_tbLZrHQcphg-k-_eeVHFbFfcjHFS_YJwALRHw4WVI_kYU
irrvMj_USwPJzfpHxolxwBGzPxvzp-cqNYywhUSkUjPTYtU8-cJSjHmVUtcKiPVBF_BNLgo-DkJCQUn5-zM_z7vjjIM9bs7UOx3kBJyeyhfwUUajGuyzO-ze
zQnxzu-z0zLxrdiCrxz3rAuOUtsqU-nDUzQzusEljbcT_pHmzdVlgozMVNaZYbrzUICgIp9BjDNtIYsjVc3PbsYVpEw-iefcTVxAgxMaKfSqQZpidXFlCQXU
JGEX_F1_1DOy3Ehkcz8w3OgMteffKEHTS-oGQ6c7gDE0Q95sAMqQ3Ar4sYboRGEXbaW_4GCX_JO000000000000000000000000000000000000000000000
000000000000000000000000003u4m
}

