sprite $1500_12p [93x93/16z] {
xT05bYH120HGdEJ-1zuTTo5bFFxZINTL8K4_3G0000000020wBkOrjYeXbngdsMDxoHBQPQC8TJYvJJ7AgXB9wE9CkhZ73eJYT8CZdOqN2kisrnbMaQtERDU
exQ9vcBNFgJvqt_Ss5KkI_Ig3ZRN6bPf5LuUvLbsSlDm2Rie3Rqe2paRYpo9vIOgSYTLqiEnI0sjv2hEq9AzpM-NtzuyOrePzKZCCve200000F0V
}

