sprite $1500_48p [128x128/16z] {
xC610000082W_QaNgG8000000000c5lom8qOXe4WoGL9xFy_7FVUKYG7Dz1SFuzLFWqrb4Fb1aiM9I5NE9cEOdYGSR7qGPeKHPEfbzyLv7gE84CguAJBdY0X
LJ0ojVBQRsEqYxMllWT1Cgh2vOILhs1pFxGwiUgBJwXKmS_w9cLGPXjjOq7RzijZf2IzVyAsRu1ehpxGv4XRYPKYfg8OdxRz86qGxREJ67JCHgirQc-E2abj
bAL9wgXi-6Tzk6khxJNTYr6PzPsOtVP_i__IUdq6iFFzzLUTnnjzqiUXkpuYTAdrsgZsOgj4-4hlZArjCIo6iPr_MdMIAYF15mYPWLS7N-t1WG000033eFjJ
7sJL0W00000u
}

