sprite $1500_48p [93x93/16z] {
xT07ZWCX38LXu-Tw_mklW1H8KHkoQlxofrip0FrCAQMKKaeffPHIIe7QLGhwY2FThlACJvUNj4O7MEg7tuJEG7gZ5KSmdJ8ljj_icFqOB1ry4ZoD9ibV41ea
Y2Swn_L-yMRJrQit9S5uMIvEXo0vhB_uUd6pjgNS4up4C68TVPvLc10relcoNZoISnOZHxgaQvgcMie8CHg3MCQH8NtSFfyvGKXwJR34lDLmY_ehI43x-9UB
cpUV6TzIz4Hwq1xRQ0xkunZZj3X_B2qqD2nyFnOyQhTunhqsmwrluqJW-NXUdDFFIz34UXxe7vHIIYcbb3y
}

