sprite $1500_24p [93x93/16z] {
xTe9RlEw3WPG4OH4UFyBVkzETgjE_jCcgHASWqb4vdoWBDjgTm4000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000F43j5-KlO_w0KRFQByWSbHjFqPLZxjdTyNa67Vjm2jdHureTnBZwk5HySYD
HxzxU3L6VXjzt7VsZ5xRhdf4-n5Y-aEptLICuvCget7TXgYC-yoQFHfN_rjlUUxNwoOzJeowzTep-hORqQwAFXty7dZMD7ksQukyxQn9Z9jDRJ5kVL60kDMo
8kfX3tbcpplCcinTKXLNMslUFpopvyXs1NboDELcgyDOPYxcyZL6ZmURDPdNz_T_8vPecQnjbz6MO_PSVzPquUMHPqqNNcAXUqxSVh6_qgpffj-8TUuMSlaD
rNp-MtcsJCmNQqRy9lgbVHHzUr6_ZErGSK5u3yXc-NN3exSJiQsBQ5_BRLtaywSdlLmB5wNNriAZf8Vqf1SvJcIqHKalnxbeIv9UZ2TFJthPBaUEgXxln_5k
l5plqUlbXdc-6zSqlkLnBzktsU_NtupR1-FnxVHQv9bsENBxr_XaNA_k5bIiTRv7FnBxU5pnCjuMJK_lzS_wSENUeuuiFX-F8-45qxDLhFeyFfOmqpYMIu_8
qUFLE4_6pvrUrYvULoDRQr6x3wgnL_rTrVfHnUjgjAcAwUE_gj8zXe_LjkjJLTCsgpvL5Qtb--hu_J4z5jCDxfW_SBn-h6s7CJtMfVUnxUVfvVlq3jDZTLbw
NNfdjaFU8htZcK_LUtfl_VIaD_UUcLFlISznJ-zPS_woyKdlZI_I6zSvtykJZvVUgUYxQAtbLCKdLRwhMZzCLRQtRnelrPl7fYhdnwHt7NRZ8Zsa5zCUjvog
cAk-Lxa_TbJjUAn_KOruzrWULPnycOkuns3DkRvjLwwrE5jtdVDJhdD6_rUUZ5PCptNEO-FcooZoUCtnmKkcvphdyVptwKbl_TvxqFGSz_JURCehLzjJrlNU
cHoljrT6VLpDEpW_gFfHpVivpwhy-0ChtZosYx5_eUZ71uvZrEiV_KdI8ovABziwc6Cv3td4IgZj7t-w0AYn3lPGsfcnhOhHpaHjQwAYdSeruwEodOlSLaIs
Fv9LsrgeaUqFHVPHws3qR9U8XT0-1W0000000000000000000000000000000000000000000000000000000000000000000000003y7m
}

