sprite $1500_12p [93x93/16z] {
xTi7SiCu30LGWXnaeFiVU4kQxDKcyLQBudlJmb7Y1kEps6cj0G0000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000G4oW7H4ZgsexlQeSFTgE65NRLjiaglAZVaJMDftgxPM-ssPK8nfLswGgsk9wRRVg
zAJdxZOrAtFqinkPDnMij5nvLH5j3j5p-vJH5XKrRGPbhJxvxQbPO-R87sr1DwdP9m-EjfozyMhsIRkgBxlMp13zJs3IxxNYshEkSbmHkTp1IzyRByF2UIvv
hUVRLpfusREcAim3Snd7r9nVRcji7SPXXtu9VOd9BwSzrtJm4XVU7KNMb6zCvxh76VtIgHcNZvPs4iwKf6VK2blQ6FlMOLmoDSSgtx7AooLALInpbBHbzr7U
TCQbSYRtuerOmPLsHhcjB6FoQM1jO-v9O7LoSsQfUXCRyrUlLdILtgk-eglqNhOLpTbxggTwyvES9wBtuYUNgrvTfthvyfFUJafozfVTREMJd2yJLq_rSe7g
ISvJikQSkNZMd2twzwATa-ISdvCorLEzyQw_nl7zgF_vA8w_kO_-TPBpQrMttvZCxMvKnz7nD_lXsl_MUwgtVQZ3l-xatNSIwZ3QVtFxbATRSwfUFbuzoQdt
pfESUa_rz9xar7jVqtlrd3MdwkN4QqxLwuSz-FWSZUz-yz2bajCvf-fDI7BEJ-yjzDcwLSkuMttShLgslxzgoM_-wlXtTVDpYpxYgSdfhAM-VWVStTyuL6bK
RPLFIqvdBOVV-xfw-SSgnVQgpbezlTU_xBtzLySPabFlZR_IU_kbdA_tzDvUlGdNdEQzt7_nISdfCuQ_F-_rBwfwUkQzZzBMi6FuJjQ7VXYD-Z0ErxuQZGTl
FmvNVxV__BleTki_Y0__pkZns_zwx9ppZ9npLhJrzFcJSsolQgocPsslOkhgBQxQnAAsLKq_xMc-YjadxvL5czmedJUn65LBJdaZsWa00000000000000000
0000000000000000000000000000000000000000000000000000000000000By2
}

