sprite $1500_24p [128x128/16z] {
xC610000082W_QaNgG8000000000c3pwG58OYc4mB5lZeljVUCdIUttKR-QdWqZoSERZ6Cw9raWTECLQoXWdfJOSHIaDGwMQnzyJCHgbn25MQiTutYh37hOI
pr7QlmOX1Pvb6dlYkT_7xMlWBLK-KsdpW5klKElzjkVRsWTZYNYExVrOmo1ijqx4_6vd_mbAGJLQfFhkVITNsNusXSrW0P3mwSxltc_9IlAKBEVtd8f5b69H
-Yni-_Zzo9mohlEDEEMBRDQZzytzQ5XdgxRzuFKFTQfAsOhxzxDgoc8HgtmHb_aYcmMmaXLHpEBElkZFnerzwXM85URp-LzxS4m00020CCZ-gKsn3rWD0000
00u
}

