sprite $1500_12p [128x128/16z] {
xT47YaGn38DXH-34kl-5b-sDDdcU_d_mUb6muYa0000000000000003bEirKz57vTALe8digJgEqCrfCMtj3Mt7SADU8BSkbXkfdx4exEsU_l_hzsIlYMdzG
kJIEqTgUeDn5iIEzPeVbtCnNTD21VEMdSPNy_AAhv3VeprzLRzlytiRhTgdyiiVhjknutJwlBvmVU_dtt_zNx__xLrM-Rf6lrvMXl6Z_ikVh5ilMy8ooBjV_
Ltv-vUSQzzg_N3sis9Bb5XbN0W0000000E05
}

