sprite $2500_24p [446x446/16z] {
xTo9RgC-40TWZqOUY_T_uF-P5B47QHCWiFs-lMAPdZ_v6jYsSmC000000000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000000000003YURGtYknLutbKPRmfkXhJwnWzsi6YRnSTuzWHk75sZ6X7YUsp8zinSje1
5Mr_KOiHNvNFekhWsJF6ShV4Xjk_F6pM71kDT7BERz_XqEVmih7zOZJYY5cpseQenQZOVOGtzXeO_SgpflWgzfoRAngxRWZpohEclMVkLTVCngLsXJ6EhwOw
EbphDCcoXjotVeVPTaPiEbIYNtRMD7l6uRCcynPnv9KF2XQ_QizxSH2p_pT-_-8DnvSbyoGdT3VzhbsKLhQ-tAn9JH_YokKLTnrw-xmJdj3DdbUxbKTyUVUH
O_emwhsOlXPVJ2T5NlWnTqOytgQU5hqzCARtGNhI6tKgV2czQgV2E7TwI4zwysMHjIwpFOK-nlIBNpqs6tjHZsLx0dtwZT7-arKLhwMNzLX6OyiVkf5poIHt
Jw-YRKjwyyYCLzQzt6lcP3szcb-VSDsZhrPJnilf_ISVYVOK8lilVxMsoTXxEy-pZEVNlJTYlBhdV2UoZupBLSfGvrJdl9P-b-qVkTww-RaLlxaoxdrpA-VM
yiElVpB6tlf3n_5_wwQr5ildoHUj6CjJyg8rzzMYRxJM-gAlhtpuHUlJigh7TqflpgI_dbxDLyxftIrQZzABPzAhs_kwO7hIorVhd9UTEPzDh--JthBrsELh
BSRU-AxfZLtIC_QCFNNEtTBh-wTtO9tJUM_wq1-SzvOVFbvFhsMD-ZRdlUWtrJzT-kZBLgnNL-Q-MlOjMxdIwcej6r7dn3q6fDVh9dzkvQ_xQj7N5wt_rxR5
bV6RllZf0qQjV387fMVFkNAQs67FUV5rpsdTs9kkN2apSrwYrfBzF_dngi-leiMjzvpf6NlJpVm9PCoVoFXuvVxU6TUzzVIccsxiISyzXcDcJkbjSzxhyvKl
FbCMpwzx_PkiUp7k-h-j6ZTr-o_YSr-hSHUtlldANFJ5kCi7VVCxpKLVBVfw-r2t_laJYFkhYfRtLzSQUwXIIs_AnlaMzlxPvvbwdWRtKEB2FngNQ8_KT5Bq
zb2CwPGOqIuVd_3MHKrdmwXedvIznebGFTfNn8dG_d0000000000000000000000000000000000000000000000000000000000000000000000003y3G
}

