sprite $2500_48p_48t [446x446/16z] {
xToBRhCw303WH5OSyVuFVFvhsOdunzXAsw1zdsxrWbItLW8n7MLQ00000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000GFqooaj5o-nVHcQByXgjBoSWepnRv78MUjJoH3MNgpB_eYyd8ykJjELy
P2tFaCDxPeilekMmY4Lvk1XNQqwySczFN3LRBPnx-TvhUQGqxnuw9NgKXwdz8HEF-eJLCvQRtigPgFdeQy_sd5NJwbaVkaFFSZxYWLk765RcAx5wrk6gY6jT
qVTdztEidd615Nb4vDbxilQIuZdvzQbt8W-dyHBzgTUQZ5_vjKzvjWxVSjMqUjRbzUqLgsTSRjMatjcO7EuPFXlrdfi2SS5RUHelrryrRHscQqfhlDHlS2lF
rY6MDprVYkLDErQyEP5NBXvnO9jtNIRVCY--GVLKh-TC-5preio4l4prK3tLgv7x8WhdFRQXPpslUZK_LildKPVtrF9BP6RSMRt8ZqNvF79_GzwMNzfzrSkN
L4_rOlaZBZRtLA_zhtevzNdFRuwswcdLApK-KijNK7U-ppEgzogirQlNhPxovJLxBTIuSx_tGkXpwdEslwAMKgBTr7Li6qNvQOXg36E7edRyo36riacjx2KQ
_puojj497-B9rSlb9eOeXryQjY7AyQ5AzHRTtZt6lSrxHqOfjOz73idquUrpZ7PI6_-nE8wblVaGTKpclRHZynqU52qppgrUtwbUxdmDxR7Lo-788PdTH9TD
zTfECa-jNgpflhPwopJLsywzYQft_dvlN8AkClVYudFlf5wBkQTwVRxgpJ_tchctdwZptarETTwxwjmxly_PZk_tJgbU_Tf-RxzwSMpkZT5NztlrfFrUzlls
UtiDZTZhjUn7-osCjjffMhHwEDgc5iTJQwkTHEDuehFtET6bHlLKB_AlLeSVAVrfvETVCKHrCrR6A8wCZL7R6Sj_9Dg6QFm5rHZj9NhtXsXZLAUznp2EnHWz
PCSmfdRuchCTsk_bg-unZAxLQz4f6-crNAjBFNAFOSQvLzjliRvgRw_gswifvvukTL-JpUsheKazttbFbtfzqtMq7wYUkNVPwhd7C5PscQbwES7Sc-CtPUVF
lNhsUUyfrOj-yokk_QPknxB_rOOZe_oqZkLuv6Qij9qergWEOzjarYXZ9z5jL3OVujr4zpv43D6Gw5-n_YNozetMDP5ONtt7FgS-PvOhKhq-tsFWgVtWd5hF
dZ4BMZ_wTDnOPaKSMMBdH9QFrMLAzBZkOyM9muz0cmrPor7Hii-3R54-fSw3yYq000000000000000000000000000000000000000000000000000000000
000000000000003m0m
}

