sprite $2500_48p_48t [93x93/16z] {
xT25ZGGn341HC_JVy8LkioWO4FhbYwqGtAUKKaeffPHIIYcbi9x7y1L5kftb6GIV90tXFBGKUESfS0r9U_-I8BZ8tcmVTY7qPFXdwKnNOd_SLlCE0eCvq8Hm
4d63W03nlxcXJQStpuxDdpU7Quc-R6w6AwKHcx2nh4XNQ2_H6fSvlZ_dPVDCwaMBCoHTqYJLUkAZI8waLkuuOxJ6OV5usPm5X5kuenRriCKl_Pg51V5bStVi
6OtOTIJIOnsPqmXzzpOEsmtVmg5pxStLWVaHzcX6FPpnwcDsZmCopRKtv_JBHH9CBDSZk5yffPHIIla3
}

