sprite $2500_24p [93x93/16z] {
xT4t6eD034JXKPRkVs7dx8QFfPlVpq2r4GSY8Y8Y8Y8Y8YABt2jSy8_sLEvLFOPVFYbO82RnBSUnXdK9tactOXMfCRpOb62Xd7ZxBjEbyhbQdoC4hgAWDuAT
rCu40cG-1fUyKUpKS-RUxuDZBSkjWtjQf5wJ_4uppk5ERElWELvZvthqt3phStQfS1UpTN1riS_SuUUdFSE3R1qyohBqaTGzlJnJBmLU3ZWMwUZihDfyB2Rd
x1u-aqiAc5v_zXhSfckvyUTTnNA6mn4H4H7H2G
}

