sprite $2530_24g_poe__switch_j9773a [128x128/16z] {
xTI7ocin30DW6mVB0lB-htiJRXdTC_cNFb1tZ-Apx1SJ4H4H4H4H4H4H4H4H4P58r1B8iFkIh4N8j7l0T5l4ax2Rl9YsKBByTdspfHehx9hWWlhpZhYwDeOj
5yLs_TYiTlqSIy9j3_1y0I0BUrIHE3ijQYVIJ_l3Diflrw_-b-v-ZOmaVJwJQIH6il7_zf8qa4wcpVJUlNTUxFTCtzFVFpT_0D40dyz0Meu0ELx7J08sua0p
OFPpzDVtFFvLpw-XLSM8p-Ugj4F6wnXfMMKZVlZuol7VVVxrpyqVD-UFA_D_l-Fl93PYdLz8jH7SbX4H4H4H4H4H4H6HVm
}

