sprite $2530_8g_poe__switch_j9774a [93x93/16z] {
xTC5OWKn20HG1WlS_y1rrx2_tddh4WVvuOY8Y8Y8Y8W8xv73hFfTws3ztgcGDy5MgHmGxR8XssGismQTc1aCrpja0bMGRTOf-xGwV21xoRQe76hiL-uoWvzJ
kSMplptWhc4QUcBbdi_-NgtLrkaT9rQk9a-PmnrkwYeYW007Ay_dEPIbgwp2owyJk1fo-Q2LiyfNwrlJSbzvXsYlMULu_ZDmlKDnzoHN3uf9vTvhg6IV-P3A
gOY8Y8Y8w1m
}

