sprite $2530_48g_poe__switch_j9772a [128x128/16z] {
xTE5RiGm60FWdsJ5qi7xl-rsD2WDanluaqfk4-UWzaU9Y8Y8Y8Y8Y8Y8Y8Y8Y8Wd-aXxZspifQMz2MmLRj_F0sI-epwibsmis-8WtFg9HcpLdsvtvI2sLzSR
2D_uTNhQ_eVLvDyvU04WaMCqjhI9u52OzvUFWwL-6sUXN_tN5x380EcdZKIGXMj4OY4A4adMmg19PCVZhev7BFS7AkxRZtC_40KupjifhNcKjyj9D1zaBvwm
tOwvswtqUwQVpZBzSRFJbXcdRNBfIz7oeCjs6sI5SY3l_Vl_pFweSZCx7RBAJbjLUbNSegfy4RryuhGj39f41Y3Mld_OCDvWKuqZbKqv1YhhJ4H4H4H4H4H4
H4GU
}

