sprite $2530_8g_poe__switch_j9774a [128x128/16z] {
xTK5ZiD040NH9hNqxt_WS8HBuvxbUk4OocpxNm00000000000000dhqaRQlKih1zIghmfQqbfUtIKXpOOcLRUAlTbiMc1N2fxOXOct3_NBpL6mxy6kwvYP9o
UkJEyfqZemj1Q8SUzDEdOjQtAP_qwRz-0fKKBRdKrzSdzRFAlxVVh_IpEwhR-_QgJ-f7vci3C_qwD3DkhmllhkXECy-Csxj_vVw_VePKpxjMIlbj_ThIZrUF
l-kGgBAglBskgjAhmkp-7bKnwvTDnQ1lsY7jCE-viYy70000000003W3
}

