sprite $2920_24g_switch_j9726a_ft [93x93/16z] {
xT253KCn30HGi-Fz5su-gSpStjCf2XDT1m000000000uMZr0CEsJbYPyBx4ieLrQCTVoLlEcKKhRh8ncSYkQUJbjykKqopkiRngqbatc6jljb1QotfspCJsM
LCwrLiymxrx-1BbiJazWhzayKZBf0fgXwJAMbjhZOoojroEbroMTCzQRcqiLNS0gUxIQLKHPJuxnyfuiZNAjb6hhpKNOZ2x0fbDaYFJecANElJvDM6_kmNGH
2PSm7aiDjP0flTxZGrsd2UlDMsbhp_eMTnQX2uXR3m-bgakFZL5NdIioJbZVtFJnOjxSwncKFWW000000Am
}

