sprite $2920_48g_poe__switch_j9729a_ft [446x446/16z] {
xTs7RkCw40LGOXv1ZFx_WrzFcImCIwOZcPjpjWeUrOkn62gbJGC000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000Y4cqQqJl8tERG-ReqKuMJmoExEr4CRRduhpy-lPqPBHJZ6rDugllcfavCN0oNEzrz10d35UsD_E3
9IB6YTqN-UnTCSxglluUtcWyyQgUSLdx_W5kz0_4_jlHzxTuHhiZja_8w-CxSiiR6uU6awCa_OtZbH7jO7f4kpI-AAszgvn3WVJlYo-EJiX5VY0EVYZTspFr
oTbmBenlbAqkHNpZ_FaLyOtr9iSOpuqlza-EzRoDk22-NZOsyT2Mm_5bd1TUowsgYBDlLQFiUYezUjifdj9zKSARcryXuv61Ofy8xzYEezz6FDOtVVeZXNOs
iiItR7ZY6rEV0n7jVCJ4CuU-NTrvbFWcvckk9hw94Sz2T5_aYuH7FpnJ4zkQuOclTbxsgp4EzL9iwpBDlJq4wI4zwULBuLXwxQKm5awFb9xUGtelAgPuvxnK
_34bbkezuLKHIwKdlIgySqfFxpqYVkvzJtmHAuyvqNj8ppndP7cizBxKwrUoby-coBYpOY_hxQsiYxMoBavKnhRdVCUzWybQkVywrLVhTextNcpbgBQojTpU
b6FSuiwAjohZJcNvGi9QMHPBPJjK6RjE8kl17AYySvs-lhejaDxjoXfNwnUaLyxtilJomNVEDm-d5z_HUsqYlVWXlLTTttlZv_RUPUdDzDxyEsUSVDyRtzTx
gVTQYn_IUxSR8zUwxnbpNjvxnfoJwUMRVyzcv9lw7QwY35QZhlXWPMjriLQMnNwxij-fl7amzyu-zbRMNTGLVtqrtppOU_rDjD-TUKuy8KBlIIz6ZlptTxHV
zCp_NXsjbBPVLnnlfJ5H-MMnh5SM7wmiIr4ho_dsMdgtyctfxYw-lZhATgR6d8MPiiK-tYiy8LfXhcK-lNXAxtqvjNR9JDdLyvm_kFVqNYupIrqhtVSMV4Aq
_jFPEizvGNfJzxtBdp7Ct_VqdllUnUbvEdlzi_Ny_zTelndpd4WFJuZqNhHrwRtUNWXn8BqN-o4Cz3pmOxzV4nbxclGrCLfRjVd8jaVVbYAyAdfkhuNixJe0
0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000m5y
}

