sprite $2920_24g_poe__switch_j9727a_ft [93x93/16z] {
xT455YKW20LGuW6o_mLFgB-xYtli3hfCAQMKKaeffPHIs5lUhZdJBca1uLi9MjjTNTDfY6lDHQC9RKA29haMJPvAwond7N63dPDsteG6nlLqxOsD9ex6T5-h
7spv24PTkjrV-5oSwM8iwsWNRbYSUDtHnJqaWiw0W8PPw4WHGAZru24Ux25Zp6fnc6JI6JpDqZs1Z4XucYT6Q2d_GgHQkcQi5XTXWCuWa14Ogk1bLS40Qm-Z
TxMuETDPuAeEk4XFrHKpY3dt8EeGnshnbjhQevx5Z4Ne36egfceY1fXeB_yBC37ZVs4qYgrERdf_FXUtV0IXDr9AAQMKKahv2m
}

