sprite $2920_48g_switch_j9728a_ft [93x93/16z] {
xT85aaCn30DGKoBh_WTUyeSiC_kDogscKIj_KckjjTPQQwsrPlv-AW-APEAzadYeVd2yx_jNgMVURvzqANYZg8zhqkGMHLhTiRVJlOik2ptE4dWxFrS8EHYX
ye7gzojEkdqe1wUKJ7ouv5xkyk7iYyhLn8xedUWMMMDtShwt7YxbCJHv5I6DgOJjSSx1E3BfIQjhfYILAUJnzk2eZgLym005153CYc5K0X7moe1Fw83Dy-q2
sFuXHzJ3fTnCH1u_wXgnSvRxsMUnfHmqCxatYpyq2zumIrBdEilGVHQ7nnaxPvbIry3n2KVKmw_vAoBnuJ9bOvz0VfJMMckjjTRQ9G
}

