sprite $2920_48g_switch_j9728a_ft [446x446/16z] {
xTs9YkCw40LGKHIK_FyV_7PF467quYHAtEQSMKrADkrBULNJxGq000000000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000E95jE-8hAhjDVIgocWVbhrlxq7l5P_DRdihFfTVrFPsfCRx7-ABuO1T-PTs7FcNghxTL5lkjhsU
4UqrHDO7uwjRTkqjYFwX-E8MNZJUkLVNxzReZr_WPjxGveRureVtm17s0DUJkJo-l0jl7lGDTM27vTBmUhPtfoUzbhKoljfsSQ1y8BsfXV4TljYiwhz--NMm
GVgYQzgAjWgvxIeMNsoUd_Z6yBBngJS0qTuYju-5H_JtFehCXrSNrN-B-aPyjvN5IozjgSDFFVE3ZwLZcw6EtvtLWZk5jUb9hzNXCVCywkNdA-Hdxnpou6rU
v0J7TlshyTNtxXJ8oTNYjSCJNooRmCBoEuVe9mhFRANyUU5nIw7MNV6iv-1P2-usJiPKp_4LxvTH1pkfjbyglupgX-OArlPpcPYsFGFf8JtfzNFXK7hPpeIG
dlIGtib83-aXFUaXFQI7zAQaX_IGdlI6xrRFVQd7CDSfxYk7EKspobR3cwlV3Enne7AsYR5oN7o-SZxmrrBULUPGEVdqkVIsOMtRxhQsLojR3IdC1lQXihRT
CEvk4-F0iNBSuEyhOr9PRTZ4zAkVLqxtuldJ6pEPf3UhZ4bwqqpoUkdrtMLwBvxelNnZUjkdqXjyjVVwuxsNUc-ItjbxBvptpjPxsvjwx_uC6TVhlScshjvx
wyzxhZaNdFUkVyVGT__UhU_6gzEniaqh_rAtfSd0E5JPXWqE0uVASV7Poc63p-wdQBFrF9bUPVxxEzlbUSw9z92Uz6gNxKxjuguoQjV-4fFAbiFIPE21oZOi
3GE7od7nwSh9m2FxQVRfozUSW-Lt3ED0TmpdJsyOs5RShO_hlFfpJhst_bdBzNklBtaxUzdddFDCUfolzuuVESExzNMzz-cP4IczS_QUyzwujXEVzrnpwhqB
lbllksZNuZadqaDwqgjs9kGFJeywbDvMsSw2o9__O-wfHvhqf7ZeykQSoFQ0gBwT3ZtRn9dperUqRm400000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000_WG
}

