sprite $2920_48g_switch_j9728a_ft [128x128/16z] {
xTI7ZZ8m30FWn4hR-FqV-4O5QPaQh7_uawpw3kXYsAk8Y8Y8Y8Y8Y8Y8Y8Y8YA3rLmgxomUPELuaaqpORKXsjnV2866t1DdigESJZJKj6NPT8s6bzMSwMQNP
DPtfzWP1ThiqjkN1fuCLNDc09uSjyNHN5oke_xo59zCltf9t6li6m4_8xVYzlLtkwyFURcphQtsFy9_ORsnrjnNCx1qpCKUFkEWrwTRhIQVhetSq4a46VXAh
DoUxSMRitP9fWvnZ9ttlFx4Wup0fZhrUS7d-E-ktLw-Ftb7NLDdk_dhcFTTO_VB-_TZhIQVh6s0JS2r-8p07PlVgg6urhjIJJjSFCcPz__tN-X_z_BNcqRl_
Z3EOumni9ROnB6RQxFWPOsRrmqI6RT9wqX_q-mEEzcwTQQKdtovXBo8Y8Y8Y8Y8Y8Y8YyWq
}

