sprite $2920_48g_poe__switch_j9729a_ft [93x93/16z] {
xT05cgH038RXIAN-olqll0l1OGmPpVjytRY5VgEKKaeffPHIIedrEc4wLBtXCdUZFKRJMDEJg6TUQOjRurWJd2JKKmVJYZGCAnTGa7ZFYNgbK74UprCGcfWR
tOdXGeFgq7iLTwMUEExNwdXpEe4NQC-kt5oN-DMR2s_YBjeaKnmhFCIBAAwURyvMn16fr_-PbmWkrRKvmwMvU2Fl_jaXOyNDkagaNelRukRL65LWKmKQLR11
uXzWW011vJxfCaKfNHh5dkLOf5-HvLWYYO74_s7CwxPZ4GU9F3KML74inb9q_4YBiOp_g8Jkds5H346XkXgBBiPol_7cx0stSwF0yW3wLb9AAQMKKah_
}

