sprite $2920_48g_poe__switch_j9729a_ft [128x128/16z] {
xTK7okKm30HW2Kkov_uNtZJ5FsdRKYZpmM01ZllZoLE8Y8Y8Y8Y8Y8Y8Y8Y8Y2oUv2gN741hzHcj0GYv4839amoeLzCtpLhRdRmFs-VOq8OgNTofoAgYwSdq
8My8eCXE0LnInTtgRnPWWCcgsDtAvbVchpxyBGDyVoNlBY1-Jly5azJWhmkufDRaTVh0_6NllEyhyykVpZ_stKQpxVKuX-hIRkfCkKnst9n_X0lGf05IXyGS
pTQ1CjO5iB5M8CRQUkrZAtFgaBRM3MqTD3_SxD-iV3f_X4zhA6Q7qTxgM8-Tbrh7MhBDb4sT0sLdtTw_vXCIlOZqw46j9ya1UkVD_lCVwkByzTRprztyOpwx
V_SY4I7cFgMSHDsr31a_q24_Q-cnCMjjGtBGxBoP_tK_vwy8Vrk5ITAAzuKyXOY8Y8Y8Y8Y8Y8Ze5m
}

