sprite $3500_24f [446x446/16z] {
xTo9Sgkm3W1GZyUIX___uBUMUt5f24tYDhntpcnoDp4eSa5Pocm000000000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000000000051RPFRbGMHcQ-LNjEXzUHezMoq_hBsmSkIbQqShFoQNLoDh-Hap6ezUVtpN
x1dHwaF8JrViKQQBJUcYbkTGQ_xSnSicLs-5Lv_J-aExPXGcdDPMfeavZKVjytVFeSEPrHXbXdhTNTFk6SDSW4jrHquU2Z2UuyljchGfLuMjx_ugi-_8hdUj
ILzMVUAzo7nk7Ue5vW0Zsl97p7iep6Vk6Q_wGrakmEvfA3tJ_8lyw--QnjRLU6M2oRTfrx_MD7WPV_TQZAqli6iQMrzcAEtMeLtkgJpgikfnlbzN-RleonzH
B_nAQVBAnIFkRxHlYrxkQClxud-_UghNCzu9-QtgbRT2_KxriboNwlLoUQhNxYeFeUQNehvkvsnvNta0jHz_TaIDdkt9tiiJQla-Ohcb_wrLlcVroEMcpRIo
FR5ppgiUxN0INTV5KxtNygvMNadpzVgowfNQxgZbCRI3QywwblB2T-lUI1JNlLjtGn7NdBLGMsPzTivPO_qRXt4hg-_7KLOrJiIPvUl4yNZY5aVnFd7Pdjc8
4t6stvYKzJKwZfVjbLJzY6CV_qaGcpWtnzVln6M8TucFurWJ3_7vnCjNSLyJxEBn8DhFLwzkAhEBspukspW_nNqJBr_4iOdhvxXkudOSb_ufpatSXtX_S6rD
lCRrEAwRk7oESuX_i7fvkdfbgEH1zPRpyRvwxOdgzM_4xU1XCyIpgnSHRKBl7LRicjLxkzvxViwfzzg9VcipglVydFEuUlyNlLT_hVVgyc7EpZcZz-8olNU1
wkczzkkzrwzrpUcQS_o_ztlNdExtuk7gjVxyDUVnVENyh6KVvyEpbXk9-y6ifPsOjUIRpLfgPBQdvvpv4UpZzZVkOxngD-Eu6zUy5MUz5vUu5VSuZlV9ojra
UJFPDcvNU3qdNesBLyBhlPOVsdvLyqEigvlVYtLLTwiImulJsh2AW_GF75f-aJvNHmTpFdqSfV-DPuZ-_jhoHnrMhPJIXrKignY-5yFtbk6jkZb-nC_mlMMt
sgRV7LgE2OTL3YdQZVGv9gm7wUkuEZWNxVDLPIqtnPFFhP-lNfHInoFEuJGimohFLMyyOUsuUdMiPJ-eNX-hD_pHkFMzEgpELo_6Sx4xpJ7lTItdgpSSiUeT
dOkn6BtEUKtPc_LUVKdrsjlqtlhNOigKElNUrEhbjEhDxpqxPyojtgJUqtjZVUgSvzRztvlPU-jNu_0vXlvBztivFjnlLA-_h7gb7wmEx_UELcFwvtiloaQB
Z7hu74CyEsk9_107gop_qePLpTi3ZPghjXzlv2hsgtPmC6FwDYOyI5_pOBYpEz33zFVFXIdr2UQSItaVd2zBVSSFDARVtHA7AvMCzy7fZrVDvLtHocK_NfLU
osMRZoZbgkMZbLFQydRehPnLixyJifRt0G00000000000000000000000000000000000000000000000000000000000000000000000000_mG
}

