sprite $3500_24p [93x93/16z] {
xTk7KiEy4WPGQPPTZT__WU_zE_902i4EDZbdgeREvbDPEUrC000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000003wWsW_gKTarLWUH5L6zFOJ8hSe7AEYFLlKiXL6zZFNZcXF4ylMU5RyUYxRO_Id
1szKPSP3gConl1lHTXVJ3yputfc57bdJ_xFjBBV-MSHuqk8NjSCF8fyoUyROEtZY5sTxYUpFxDbh-LVrjYtw78splJheiL_vUZwpgMFst6tMZ3PXnxN9GS7H
uRopfjcpvzn8FGUpv_dtceuEyUo-9h7y9mvuXhoEs6RsxEEdsoiMlpXpKzhicQ_MbDQsZgCqfUqzAquyQohV4gUUDSsUht6Lv-WGoscBf_6IoxjHFuhbNTvN
l6CYVdVnb6yiHqN-vhS7UQDANmwBwlTbh_90gAzbBzg1qEjBsUljU5Hlt5czQ6SdU_5sIs-F8EfJsR-NlNdTYxhfBThN4JVE155BnlUorz_gjhVsTOpbadZl
T-NZsTkpUYmNrPJCs3rxqROcUparnXxVSqRTjEssnRfNVQfjVM_FsTzkYDuUGUILFMTToTv9UYsIEVffUotADwATCdj4LlPT-vpeS-AE8LQRjboDelwr7iLV
_vL_v5-Zh7zy7BMxFfPNHmzuXNMlhq-xwqUGwyeeBup6wamsrX_hyyUMM8q-_Z8FFPGUcT_gS_wQwlLBjQmFrQiBrLisgDxTYPZwdA-UlNfAzNBBx4q_-NJd
FTdRfi_vCsHlipxdyydUR-bpMlVYNDcJlVbzNo_JvxoMlTgaUl7SyrvLnUlqMiO_gi-ZN8qgvj7uQrJpg7y--gUxCd-irJIQFfRj3vT6_HnzJlGvETkwXpk6
o7cq_bXVV-ppcuEyTSVGuieTGrouO-YozxdxxXZYnfupxzfprYPxphXQpgWwx1s3yrxFgsU8wRodptcyNak-VwlJzLfaRrnjl-IX-vooTxbvDjSs3vazsRjU
lP8zwzvUx3d77NlEV9K-vxNgxVnCMN_il9TP6UsIo77_7OFdEIlM7xlOXxdzF6VF2xzCM-ljclwgVKvzpcWdf7fzJ1az0APCvRqFD8qy3EO3u7Mn70ztJuXZ
EIQgjTE6ZzREMZv6jBl4M8w6xErUaUD8oDwE0m00000000000000000000000000000000000000000000000000000000000000000000000000_Wy
}

