sprite $3500_48p [93x93/16z] {
xT47hjmm38HXTfFtlt2KqDlxodbrFlmmcZ1kzBi1000000000B3QDA6hEAfoMkMrUSaKciTHJkUiWkPTNueocdVu1fj_akkFQfN2cueAQbh_mxfkoT9urc4b
zkCKJMZIKeFhGdGqperciGnyDcxE8-zidxXswhAlpruxJZjoCbubXxBJMaPMuHLH_YzRIaTPagNhyJMjf9KN7uzxy2WwxoIiqz2H_KswzNXVVH-jMEcvSRqx
7cVZ8llnxJzBBbS-o_K_f7pbX_Az7yfy_aErOdlfr2osv_JT0G000C0V
}

