sprite $3500_48p [128x128/16z] {
xT45ZiGm44JHHijr_mClXN5fx0ZgINzuqefRNeo8Y8Y8Y8Y8Y8Y8Y8Y8Y8X8BR8TLxdd5MqLbMkQG75hngEYcbpHvTjMD86GSxwSJXltKn98wS1EJrahODA5
5i1bou2gqai0gVkpL-d7wkPs2u3Q5R1Qj-8HiSmlqfrlv-VCsqqSg1UzcM_IYDKlHIloCB-di_ltJFtCCcsT3lcgc9BF8aCZKpxIAJzcib0xxhy0da3ayXm1
f0yL6rEWsaVwaGpFcAjBLeRcYygY8Axc-rFpBKBNQOJjydqo5E9BEcMxP4NbRl_wY_qFHURKOVys9YAcZ-xVKP_S__ryEwxCxCNxr-dy3_j7T5VXCaayeAhC
pFjJQOs8Y8Y8Y8Y8YEWT
}

