sprite $3500_24p [128x128/16z] {
xT45oaGn40FWCD9Exd_WNrRUkc_xa7mGYgTCy6qY8Y8Y8Y8Y8Y8Y8Y8Y8Y8Y5ZbCE1xmubY9Uv9iRiDu5Zjkwop3M8tbjs_VCLoGUUlsYGcisA_VtZ7UOURB
JqsJP5oECf4N6muQoPgBB2p8cexqGt_3T7dQdml78C6DZcZt-Ws3UDzeAFf5_qoU-Bm_CvR4aZnw4twKO_Pvlv4TP2sfpKlKBlqGQwJXeDDNxhVFxn_XPmdu
dPpuolv-kVycUMj_my4Azm_cgli7S-3-lddVtBzYkiqHTe8hQ3Wmdyumd8Y8Y8Y8Y8Y8o2y
}

