sprite $3500_24f [93x93/16z] {
xT47ZaCX30JGSGNV_y8B9ZrVRTCJFur6ZGv-Mocbb59AAQMKKWg9teonYLf4lrbqnZNkdN4xyb1Sid3SXuPVFOdYJl8DxluasqVLQ4ntvU67jH_1aAmHBtIh
uohk-yNX2-D6FGQL1fmiJXCJRaKyGCyNTwYWGVHGDeeDdaNieyXXV2mqg1nAH-qHdosUGpfKHyae4blLvhgDiyZXJ6sL2Vf9vSmzYxF55KopU1HboNL180Gz
AUQpsYCvMzoSVCLMU4P7n6L5dJDacVCP6GMODnRlGH4yqqTBz8nhkCsOXxNG5ZBICpbyDEKaoG2zRJsBmOncz2J26J5UqHawn6PmCWDWklnG2R-_C2pgzsVu
TAMKKaefvGy
}

