sprite $3500_48p [446x446/16z] {
xTk9afmi401WgWbD-VuF_9zxKMR7YIkk9j-Ni-EMcEc0q90o6m0000000000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000000000H6sPkUn4psmrodU8bdtvEZAZdApcSXXwBIUAN0x5YVslBKUZrpidZrPE47sS
DMMhiGSjSvZuPPckVcWlQ_aYQfxuUURX0pKVybTF6ZMpSA-FjVRPhrZTBsFwNBD7EHHrykWPQTGyPpPOfzuz2tDxHynReKSPSFNFEDhmxu8xpGhZjdDDIuTn
FiHPrP2OUCFvp3rlNLunUjvwr3Hwtc_Kf0sZvnzONZ5wrkKAoLEsllEegV1I9vRTvbDucRVicC_BhyUzjl8Oir1lDsfITvmNZFlEDIqTsl8klndBcnutFYbD
ZnidZonR-d9PRCzOlX6o9tkvqhxZk--ll_nIzg9S2V5BsIkNGlnXVK_sweyjPH_ov-fn8-UFt5Rs83V-ythhIulzVU_PxEtfVSJogVVB_PRPaxrS_jCdZ9pJ
ioTxouluIj-hfoVFUwz-p6tzqfmpVcoePHyYVohAnxvtuzMwdfdtNQqx3z7ZdjcZPjQRrZbHvrJdp5T3rCP9Kwo-ikIh6A8wH6rzqpP4UvgFrRNInkQ7gAsR
Nr_BLVJmxniFhfsuGnJZQVZy96f3j0mdctA8-hXGNKNbFOeXgiE1cpP4uxK-DDXM3rE71kk3vkD3j6emFtdG7Axr8SholDPQ_MBVY-MJ9yu7JxmCqUxirU7Q
EdlBZkprCL_nE7jrY69e_idiBNkpruUl_rEpbsDqJFRgrEmTKkUSbhrwTj_BG_fUERFlBI_YPdrFtnlgdBz_zjhMU---VUz28wU-TsgTqtll_3ddMEUSaxrn
i5e_SJrWlRUHlTpHztQjz_RtlVN3F2sEg7FM_YB_kpH6sL-CrsAuLii_7aMjlsX3WsEKOpGs7n-R7wECfviVepP4-Vp3b7zzqdnSkCw9AZLEmkjxZyhwGzJY
twYDkmf3r1wK_ElJKMmypFOUGumttNoOiS43FejJinVzgJbdsvXdrQ_FEMDeuj6SCpVs6EB9EUSgEdhEsJ9Zwjxw_TTxUTKzXbZdSxtUiqDqqLhBoztQHgr5
bVgAUmpniTMLc5_drFVcPw_-_dNEDk-zDx_ltN5_Jz_hmnzDs5lttfiuvwopvvmFrZXrQuqpTu-XJZzJDd-F8JApbK-rp1PppdFcre7AyadKrb4x-3ndNLqh
EVKyvnZ5Wp9G_SthdDXZaBqiLqBRojvOm-djEdXDIjcIorMHPTDoLKJPL9ThefLor_IHvIcrBvT3BS-gsQ-4REKw00000000000000000000000000000000
0000000000000000000000000000000000000000003WRm
}

