sprite $3810_24g_switch_jl071a_ft [93x93/16z] {
xSur5WH130DHcTltF_0oy_PCg1yeSprZ2X4H4H4H4H7fDC4NqPMJgXCVLGbs9Fvar-jtP1Im88uSWZTq9FQi_gVdkhvh1mv4_uUJQCCBrYahY7OyqHuhwHVn
mX9guW9HLQmVjx0sYBjFnIqaR3VkUXa9jK3ORY0gs9kAHsjdj8pojkCCRQz6PxMsO4-7pCH5eR8VlGvKv3IE8r_ukRMTHjjpe7CtLpDnIqdVJsZgQIJD4-cU
N-83IxsFIusL5DP3H4H4H4Iq1G
}

