sprite $3810_48g_switch_jl072a_ft [128x128/16z] {
xTG5ZiDG30HGowYv_uKtpluoCyqhZHBdawNA5oCY8Y8Y8Y8Y8Y8Y8Y8Y8YqyWCkP7AYm-_8eb9mbLeNcTw3BRPMS8TVAS0yfWm4gfnHI7aLFBm086GftakiB
C3biyxx7dTZ617xYV1xbT7yDI7yue0xj_bdimFmgpw3G9y-F4i15D2Rs_Fap18YNpT-gx8ppLq0DK20x5ag0T420KC1gZfw0r5od7KSvK5qJyvKQutIvcYoP
NZc_Npz_mMGmrB7pTrTrxv_-cDlXA_zHEgwkhCMrfpHbAO_kFxC_acaT8tr4oTJ-U4R_MAPCKKTSAny3J76CCpyvlAh_Tvb_zBywnZn_hUQFKTurFjySyyVv
yx_-_w_Y6VBGFWlFKV9GH4H4H4H4H4H4H4H_
}

