sprite $3810_40g_poe__switch_jl076a_ft [128x128/16z] {
xTG7hjn030DGQIH-WVU_S2oCOM_A5WGkANmeeXleRlym4H4H4H4H4H4H4H4H4H7nuWbW7mgo4CTA5Eds2R3SfiW3ZFsoncVrMouUe6mrFZc1OjbP1Xblwx77
W-mNv6JQ4pzjJnmaVhg-9-O3EbUnNdrtUJe-FG5U9PzS_y8kGDWlVKMudQ4utpl78fxsC-mSW1Nhjlw6safVzPC0sMEG0wIJqR5OGNhDZHr969dhxZtMtUUQ
wbYiFjZ3Dk7NznTZgsUzwiyS8xE7P_gCtZ4obc7BM3Vss7QVOzrzhFjjH_c0RJ1UzGCZ00F20PznT0Ho09PpJKVWSVTU4uyRisC2VR1Djpt_8_khIt_kpxs_
O_rclyNE5h7ny_z_BE1hXyN3qd6UzOCNSJkJY8Y8Y8Y8Y8Y8YCWt
}

