sprite $3810_16sfp__switch_jl075a_ft [93x93/16z] {
xSu54iL020FGB84jtF_0trshetcLLJ9W5X4H4H4H4H7fELzl-ALTBjXKf-AUlz8j0oTzc0WdaOPlM7uQOph7YHVnsUt4Op8-zFT9b64vLdpChbn3VKeVl2r1
8mz_qg9_22UMICi48eA-SlY9EqxM2kzs6yDn4jmWt8aJ_n9EDX8y_K-37LwZuJGqkntSRdtqEJoBLLR5IXm6h-7mHWMY-b1-UBCC3xUcXDkj9tlil3rt_d1h
V7ZaIYhmhgq4wn4H4H4H4Ta3
}

