sprite $3810_40g_poe__switch_jl076a_ft [446x446/16z] {
xTo9SkCe50LGU0PJ-lyFxfMaS6OqZQOZ1vNFwIKetdthiNb9Bm8000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000CZ_XRIkABMrRH-jrH9fHMKgE5gBj9eydnsBvPVhTWGbBQHjnz0Mx3LRQ-M7I1zHVXWdTJMj
8TfRTZKIVvgMRrtBIuLNqWHoMoY-CZSGMvQl65_TVcl5Uc9Kf-ABHSARAj3EagvkNRb25rwtbnDfjVZcUm2rbsT7dAyEh-RKARxfcgfVksulnzQTvPN4aLtz
cavmyerJsfdLT_AmImppXXMNUQ_jG7nvlV2gL_7-PAY-nLOAuLMW0qzbMMoDNgItt0HYlhEEjhssUd3bjT1AGV6rV73Xt1PQetDyA5fWihae2x-sTP4uQHP_
cc6-miNg8axidYadZadUVNJj-M1iNSsd8De9yJrzwKqLtZlnFJSyqgVQaDxNaDxzzYxIUSXdf7SRH3eDSK9wzoUbHrubFNBAEUNVpTmFHldXpo-nIi_9zalx
zpT0vFi7CTJUuhCMwTt_uQpQE_r5FUdruiiNJKzw-JAr9xsuVvIMh3t6z7RZY_N7FUdjktBjIM_HsgEsxcjhBvSk7jifIfV7JygcyU2nFLvaRCzTrNZmToTy
wgCQsuUTNtjbw-hO_lYUjkrD6W_6zcDtijzERU-gyjQrX_PuaJosz-x9fpwgiVs_v1T9BzPFJ-rjLwwzqlgZc7WlTOkbQa_F6OU-_gCjLNjwpdvLRV9Z35dj
hPHUcqilXeTht5iclNhXsjDpvhROk1UrYw7zQvLQkvnIgc_IUF3O7YyojiVRsBsgyQ2CxOVh7ThxzsJtKSNqezg_tjQcFXLKszPQNcoVavmZfmavykNsER7F
6VOvTrWnsEUqpscVK-tfETMUdbFjgJtZtelKdfvJxKNzwVv3HDoxntO_UDmHt3lNUF5MVuXbzZdBt-rphbTxNTmcH1h4RKOYpa_lDkLuUY6zl4fwUStqrDxb
UawrLsi-4bzEer1wCw9U-jjsaDv8UdLx8cho9O72UrUUb1-jf7K000000000000000000000000000000000000000000000000000000000000000000000
000000000000000000000Dy1
}

