sprite $3810_48g_poe__switch_jl074a_ft [93x93/16z] {
xT05ejWm20RW7uVxNtXfbqvgpvsl4XV0fzDQQwsrrbfhhJNM5o3SeKn_lYZ5DIx3Wkp9vjqSLwGKpz_yVdUTUui_mxPx1E649Sy9yWoCoPDmu2Nq6ZYIiUFv
Yh2Z8dWH8HQ0c8aAEw5ucM0lWhhRsUR4nECbOl1uYPVoRoVj6liPW1XMPvjhQPIKUN4cbqMXKalMpb5MMecFqaTPmULHN36NkSsjnSysPsCrDX4Z6w-emMph
7ANzCuDDrndqjrCLApvDYuHOSAW6nr9w85o2FMGT3DVWPORfqg1G2mhVbc6wJuizDYtc_wJ5xZS70ImgurK6RJFdZq3_bWFj1cyszun5_XOlaOazVZs4pwQr
rbfhhRNs2m
}

