sprite $3810_24g_switch_jl071a_ft [128x128/16z] {
xTC5hXmn40RX1dLQ__qF7F8eosnl7jGdy70DsRuw0000000000000F397ektPkkokuLKuJQHPwljJgbs6wfVLZQKscxP7JYldoUFTMy-SWhVtO32RcdrRd6A
sl-lucQ-R9sGyiQyIrl9hpvVIEh5fBhswwsdljnlMo73Ciqi_h1-Tp_KBhdPZp_Ut1z6VvZLhoxhzZ74RisxRLlBRj_bPlV7QssrIJ7MejKXsRPMOwsrYsjQ
FokjQXiy_grvbMrhKULLY_e-VkiOmydQRlZVx_yJz-UxtbUiTwMVUeUofG0000000000m2y
}

