sprite $3810_24g_poe__switch_jl073a_ft [128x128/16z] {
xTK5iiGm30DGcUBn_G-yp52OJJxgbL4k1dyT4H4H4H4H4H4H4H4H4P5qXbMYkWii9bbDfIjhbO9bDCjmvFcnm95NAPRGcnsjVInmOiiAy2h1WNWNUdDXZZbH
ANrVmhnzi3uVZt4aAp0bgs4acGoGhCh1Qg80pwzGx_Dr1zsPmHs0w0vY8Zy50rH9bG1jJwRo2oE87F9tzgDU-PefcMgPo3JFXfOU6JTBTjX5SADZ_k6scbMX
ogCIMH6LDqj-lFDHSWtlTlyb0X5odAY6mqCj_6P98oHYLBuPpEHceYPgUbnIw7aRlll-__9ylH1qC9dl-YmkJ3jeDTd-ZDSm514H4H4H4H4H4H4HRG4
}

