sprite $3810_48g_switch_jl072a_ft [93x93/16z] {
xT15biD030HGCTp_mYFJX9aJ_ONgoUwk0BoTrbfhhRNMMckjiTm0uHYAiEjvAXp6yrlIYy40m-0GIO4HNbaEw7wmcwUqAoYKue6mXmN1YFWQwpKxF1Zlmf9t
l_STmHPdk0qZLGKI4Tw_tDaJGSnqNpaI424XrY0Wt5pcb-k9kFuGG1H6-yersPDJAzCfpIjDKZ8erHCZQgbChuoiXrQZ7d96FLogoVULiw8eQIMfeFAuK0qT
5r2jHMgHvI7Nq7415PQvtFQLYvCwkrIwaejM2jSJ6nTqgsL8hJIlXp8_TAk7K1xsjnml1wpdorZBCkV-X_CuLcxXzn81s-X-4DvDQwsrrbfhxGy
}

