sprite $3810_48g_poe__switch_jl074a_ft [128x128/16z] {
xC413G000C8W-wUsnmSi30000000080JKnP8R0Kn33NAe_jVkFMdRSEqoGjflDQyi88J27aG9v7-MIABa8S8bcxHumEOh2HBRdA-Llm0ETxNKha729c5aogt
AMB43v6oOwJ93VJVRsdaXx3_12vNiJwTJ35k_UvYDadcjLV_BUoo7-ukyz4RVfqZJ26Z3N-ng_vPNpvD5p9_vcy0t-CjFnbEAfb66aWXCqa1sPDS3hrZiNgr
9wCbP6ojdcmjzM7n7_Xh68DvonzX6h4_s1fjYNsewqGrGZrytncjiMCwMWxPKUWjFs062E0Ag2CxEY21N2VedOw9wDM-ZLR7hTKxMqi6F_dyN_VNyDUP7xqQ
r_os-Eiv_uBwmLV__rYvW45E05Vy0dw7-jCU71C0000W3B9_QbFi0vO200000803
}

