sprite $3810_24g_poe__switch_jl073a_ft [93x93/16z] {
xT55bW9H44JHTDd_XZkhSOSFmxY3LsYS4be2000000000BACwGMhZ4NP-NpUItR73objeXwlxxvT6hV3_uKUu4oc8VavfN_U-c2xadQ-U9ZMHdT8fV3tl9rk
SDUFjDoEkmgjOsCJOX6XkZDUz0q9RICsCruPPnVNYTb4NRQmYqnKVTjdsYoTkRPsJAecqRP5scqIqOVpdUFAE0aBRv492s-XKunsRFNCAoQvEtEzF7CwMXgN
aB29nyHsuL2TcCMhSRxSqXtwmCDnolgHPFeP00000020Fm
}

