sprite $3810_16sfp__switch_jl075a_ft [128x128/16z] {
xTM5gWL130FGq0djvFz_-75bhllAinmexMfW5SipCpCpCpCpCpCpCpCpCukPlHTUcbtYPI4nCAj85LxKrCUOVJ9YXogyXEh7EITh9-TzvQ8UBrJZBE9uNHKl
nETnd0KnXDJmM8bOJdHnolRfwb50IEeBU_GXe79vlJ_8nnBOG09e6yYryqCP4e3SM3r_8uuNVUtyOSNyfZmRInXAA-H7v-bucfZrmwz_Lg4EbK2hQgmAxZl6
fat5fcEpEgj6dvGldHSeCQKsEZQhGof8VTknMLrIZ3ubd-HP8SXe9uNhNJQhDyFe4_BP5bVzqUzl1SGVPcPcPcPcPcPcPcPcNm
}

