sprite $5400r [93x93/16z] {
xC610000082W_QaNgG800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
06RlJ9GSrM4eggj8ilt_F_oc5mSwP7-0HUMUsLnJpb8vBP30LWQZNkfTI36JXC2YFGMf2ac5HcrFGwgbYhiNtP54-gATgVyero3r7-sCGrAWPtd5JQ60N850
eUQb_HAG1A3sjwFo6A8baJxK5q_4nFf7fZ8OUptmY2RHr-KLUGFgQoxZWBzt22TQXkj3l2kF84Rh2nus3_kZh_MmaKTzMjUwvaDzkhkyHdch9NrrPttdrtLv
7s93zAtyGqDzJMKl4AlBepwdl4VmieiEI9Lupo5fcKVGzHKSM1uBlugT5h0OvMsWhwXiY6zSepFrj2ENUKmzTVFuXcm5Ky_gs3Gr2ihRzlFTTEcO70tUCZ8k
7Jlk4YzhdReTf6rH-47RFf3rzI7Qpf1OJP-stI5AUntQEpAqLt2TzeLYBKZPmbx8TTeNa5pW6paaCSgUkaCoK6_yJC7S89VGNgyigYUsP_NMJJJQY_QDPhNN
BmJ7XzfJjJ-_T6uFPRl5KUPpyAOzRJ_W8-rPNA9NxCLciTInr-nPgQ7VWyJs4BNwflOq5ipjHO-z7UrfcrENzheponnx_Tvwx6jFkxrfNiMUzkoXFTJpsqAa
FU_LzetjQi_czaIxl4onrsTeFpm491_j1z_Etb8VP66lx6lFNhVdyg7sbbmvScg2s3leaRFg07i3inPZrhAIlJB0djOvSQjYAAmOdhGNmwlrFbzcvBR7AsMF
qPhslCUhr4jUl4hDEqGgURb-XuZsQlccbhJeJ_vo0Dhkzl9JqSzxwQ6z9IfYRMzeZ_Pehw1Nf9VGNdXsy9iJvwUEgXYy59LZmcgzzdd7W_PyXRO79C4T8aJv
mSH_Hm7HFjJ74vvv4fqcI1-ws3JX9l1J_wMqTtcFGTil8QKFCMltCfzGhquGkJ4dhZu9-h1AF4xRS9gXCi7Oiopsx6bxjDSlH1KSBFPeJ_65zgKPUMDlgK-5
zkQVHkhOMq9xVfh0tuwli_Q5rdxHnnDkFebVVHBKiqX_qHxjBSuZXuEnTtnxZ3t8iQ0zkvI7NwOHP1e_dl3gamYMasdlpQu3KpQuI3XwklWW8n5vF4VRCcif
AsGjj9UuthiExG4GoLVl0RWOHfiJoyNsUZd7b-i8zEt_GVj3VsSOQizhQqMpnLxVjDU7ZdVinPhsT64FtjS9Zx9d_TIKA_QcHX68Fbp4rT3OEoihIB27w3Lx
vJLx_cBiwN9D6KOVENLXhxzAYljxy5zKj0zb6kBQ1FipuU-JsACdES-msOGrxSMQzf3NdaiMdhNdmjWJpxWxhcifyrv9-M8lHkzy5dZDs3GUvPnpQX-cE-yX
kho1zPug91s0Odg3QUizrN7rtWgG8zl37IGDkCr7s_FJRTBeqzDjz8FjuNG7JQ8FftlWS-tfwHu7jiVOyzpsQ4y6XHxFUsuhu7Um_yktVjtsJRgjGUNEvmM5
FIFOTO3sXb1LH0zfZ_RwlNNQutLENkSaj4Txj4TxXFO8xRqAxH7Q8xH7UxH7UuJsCa9xXFPeZ_PeJoF2yecqYB1fg98HZGZ7yFwSaKsVjo_yFAmcwUYVCHBq
nit4_7jdTHfcept_ZTtS-PoBN5q71a1xex-vb4VEgkFiQKcOjVI8iobhqRHVYUiOPq_WAIi6zN2Tyd98ElfdT-XgdT3Uwz0UeJr2UxH7UxH7Q2yNj4TeZ_Pe
Z_PAP0VzCcTwsAzbIOK82hiEi5_B6j0UxV78INin26Ojh1XOxn7Q8xJtAhH7Q8_G7ktH7kqHsai9xH7QeptQepslHIKTYFEcGetca8p0MkZI7dTVrelltxUq
kozje3rdpuYtgKDtFhDd17j6qDvnk-tmoDbqTAUhYfGPU4n3btnO-wACxJ9NgqEoOQKMao_WfOP9HYngSOojrW592835C1_0aQ-r4Dfx3Er1pnpD7ktXD74q
UxId7sMFzWZjqHxFUymv9sYFzTwsq5uDrskqBqpNWVZwko_9SNS-exIT8HLhBfdP5L9TrWDMsexGdJ9v8-I_zk1O0000062Gl_KiTbKh0000000000000000
000000000000000000000000000000000008
}

