sprite $5400r [446x446/16z] {
xTq7RkCm441H09833Ez_t-rfNCiDYcOcVczxv_A7AhObZsG0000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000043S0k4KJ8o7TkfbnQDglD65QTBjBgLcIxcaASl_IDBFEEIpsKoREV6iFl6oPayy-SJBca5d2l9bnTDFFCilwvzKBrh7
qqyy-Qh5aqyy-KAyX6aLp-exf9r-ujbu9iNJxvkqi_5ql29V70ljv2iVJpxrr4Czr9kfT-KNI-byQffMBtufFGER_n7ruf-wCx0vGFMYVBruzPJr8jRfqr7r
uZFr7gdtCelwzJP6MBBPbzPRN_wJN2ycRUl5FuVMMp_-MnbhxtgzUANUBCxCqoXQRnhXqzMBETyokjHJxvnlikLKByhLwt_Kejvmnd1KFMVh7kTybL1FlOI9
KQ_-4p3p0DNhejLWrPkD4Ugffvvwwgddg4MzwNWSP-iPlAQiD_NYpQFVtUKlsRIStZwjqQkUUii7Nv9FlJYmddgZuTfJRpPgrvlpsU_5Eir6vNepzKxB1ytg
EMDOFbX7HzPU_thMNem-r9lpRHsrtBSZk_Cl6VPxEzrrm56BUkfbFBzNhzwPbonUV-Rsbj-pry_4cRdpIDdM2ElLktuXdNhngcozy0pHvthnwWdggQVUNMAN
HujZR6XSpwkI-k_tr7FCUVqNgyLpldT7lHvYrDMvNYpRHXMnR8idhXUdfK6-TTcsnlFMMovPe-BIcprnlVNwnEHRBhFspZfPUxNhnT9WlnVVRB-tezEsNQvc
J1-aQsTT-QnUFlNKKq-ziHVKswAUUkgXddhggOTwgAUUUkgXNadgePvwwgbND6D4JD-jEqXNeLo_XcWq7gJhzxPvxyiwlE-iUkgffvvwZbg6UiuOTfLxnh07
r5DFFVLGhnxrK4yzzTH3FTHJpxlbvr7FNGVKKqyzzTHprAAUCmRdUwYdddhgeHxggQUUUgXNaNgefvvwwbM-id7wRjL1klhIFIDS-ToyddhggQUUUevQHlbw
xZBdBdFky9ZIh_DZBQXtZNgnh6-QrLClOddNhPwrj_QjfrwefnxsUtTpp1dgETyxW7e9oAc7UepU-TIJJxmHX_PZT0G00000000000000000000000000000
000000000000000000000Fm4
}

