sprite $5400r [93x93/16z] {
xC610000082W_QaNgG800E3swWBBZI280QYauljVECOaQvXUvcySqglN-4ve_WB2bkoCvyi9t5T5l0Ix5fVMdb6UEl5osSGrcy1hY1Ok-GHVHuvTrVsQU55u
OSUAJjob12330aUNuHOHdXhXWge2S7TeuEQDJOmRuPHeoI4kQ2Q1xeO66QjmDKUtcqKbNfB48v6mueBkX4-lfFVIdV1aQyTer0wDD1aF_qmIzaXYq_rcOKsE
JtJN-BXFxl_7nEGKzYWzBzmCt04FG80duABYPNZ2q5kLIpIBqFuJ4OXmHTY_mu3T3TT8TcvpksXp4ogZOyPpncQQCsKpiJ_i6SwCZUvM_W0FS84Iznz9C3EP
YH9q_6oqEH_m0_4_0FzdlcUF6kTTAswrj6YMb_b-uInYIuGLDgbuDpo9BMuAR6BosxNvz4eyVpqlhH1Q-eRZl8aj6LxFtVqJRpNEAN-xPg7YRS9jUc_wLH3V
tAzVltxz-lK7
}

